Repository OCA/l10n-spain, pull requests merged in 2020-12, with the labels that each got.

#1443 [13.0] [MIG] l10n_es_aeat_mod349
  l10n_es_aeat_mod349/README.rst
  l10n_es_aeat_mod349/__init__.py
  l10n_es_aeat_mod349/__manifest__.py
  l10n_es_aeat_mod349/data/aeat_349_map_data.xml
  l10n_es_aeat_mod349/data/aeat_export_mod349_data.xml
  l10n_es_aeat_mod349/data/aeat_export_mod349_partner_data.xml
  l10n_es_aeat_mod349/data/aeat_export_mod349_partner_refund_data.xml
  l10n_es_aeat_mod349/docs/BOE-A-2010-5098.pdf
  l10n_es_aeat_mod349/docs/NREG-349-2016.docx
  l10n_es_aeat_mod349/i18n/es.po
  l10n_es_aeat_mod349/i18n/l10n_es_aeat_mod349.pot
  l10n_es_aeat_mod349/migrations/13.0.1.0.0/post-migration.py
  l10n_es_aeat_mod349/migrations/13.0.1.0.0/pre-migration.py
  l10n_es_aeat_mod349/models/__init__.py
  l10n_es_aeat_mod349/models/account_move.py
  l10n_es_aeat_mod349/models/account_tax.py
  l10n_es_aeat_mod349/models/account_tax_template.py
  l10n_es_aeat_mod349/models/aeat_349_map_line.py
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod349/readme/DESCRIPTION.rst
  l10n_es_aeat_mod349/readme/ROADMAP.rst
  l10n_es_aeat_mod349/readme/USAGE.rst
  l10n_es_aeat_mod349/report/aeat_mod349.xml
  l10n_es_aeat_mod349/report/common_templates.xml
  l10n_es_aeat_mod349/report/report_views.xml
  l10n_es_aeat_mod349/security/ir.model.access.csv
  l10n_es_aeat_mod349/security/mod_349_security.xml
  l10n_es_aeat_mod349/static/description/icon.png
  l10n_es_aeat_mod349/static/description/icon_source.svg
  l10n_es_aeat_mod349/static/description/index.html
  l10n_es_aeat_mod349/tests/__init__.py
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
  l10n_es_aeat_mod349/views/account_move_view.xml
  l10n_es_aeat_mod349/views/account_tax_view.xml
  l10n_es_aeat_mod349/views/aeat_349_map_view.xml
  l10n_es_aeat_mod349/views/mod349_view.xml
  setup/l10n_es_aeat_mod349/odoo/addons/l10n_es_aeat_mod349
  setup/l10n_es_aeat_mod349/setup.py
Labels: bot is merging ⏳, needs review

#1530 [MIG] l10n_es_dua: Migration to 14.0
  l10n_es_dua/README.rst
  l10n_es_dua/__init__.py
  l10n_es_dua/__manifest__.py
  l10n_es_dua/data/fiscal_position_taxes_dua.xml
  l10n_es_dua/data/fiscal_positions_dua.xml
  l10n_es_dua/data/products_dua.xml
  l10n_es_dua/data/tax_group_data.xml
  l10n_es_dua/data/taxes_dua.xml
  l10n_es_dua/i18n/es.po
  l10n_es_dua/i18n/l10n_es_dua.pot
  l10n_es_dua/readme/CONFIGURE.rst
  l10n_es_dua/readme/CONTRIBUTORS.rst
  l10n_es_dua/readme/DESCRIPTION.rst
  l10n_es_dua/readme/USAGE.rst
  l10n_es_dua/static/description/icon.png
  l10n_es_dua/static/description/index.html
  setup/l10n_es_dua/odoo/addons/l10n_es_dua
  setup/l10n_es_dua/setup.py
Labels: bot is merging ⏳

#1535 [11.0][FIX] DUA ImporteTotal no notificar al SII
  l10n_es_dua_sii/models/account_invoice.py
Labels: approved, bot is merging ⏳

#1540 [12.0][FIX] l10n_es_aeat_sii: Change key when invoicing purchase order
  l10n_es_aeat_sii/models/account_invoice.py
Labels: approved, bot is merging ⏳

#1537 [12.0] [FIX] account_promissory_note_caixabank: fit text to template
  account_promissory_note_caixabank/views/report_promissory_note.xml
Labels: bot is merging ⏳

#1476 [11.0][FIX] Sing tax l10n es aeat sii
  l10n_es_aeat_sii/data/aeat_sii_map_data.xml
  l10n_es_aeat_sii/models/account_invoice.py
Labels: approved, bot is merging ⏳
