Repository OCA/l10n-spain, pull requests merged in 2020-11, with the labels that each got.

#1365 [12.0][FIX] facturae: keys were not loaded properly
  l10n_es_facturae_efact/models/account_invoice_integration_log.py
  l10n_es_facturae_efact/tests/test_efact.py
Labels: approved, bot is merging ⏳

#1503 [12.0][IMP] payment_redsys: Confirmar pedido de venta inmediatamente al recibir la contestación de Redsys si es OK.
  payment_redsys/models/redsys.py
  payment_redsys/tests/test_redsys.py
Labels: approved, bot is merging ⏳

#1475 [ADD] account_promissory_note_deutsbnk_es: Add promissory note format for Deutsche Bank
  account_promissory_note_deutschebank_es/README.rst
  account_promissory_note_deutschebank_es/__init__.py
  account_promissory_note_deutschebank_es/__manifest__.py
  account_promissory_note_deutschebank_es/data/account_promissory_note_report_data.xml
  account_promissory_note_deutschebank_es/i18n/account_promissory_note_deutschebank_es.pot
  account_promissory_note_deutschebank_es/i18n/es.po
  account_promissory_note_deutschebank_es/readme/CONFIGURE.rst
  account_promissory_note_deutschebank_es/readme/CONTRIBUTORS.rst
  account_promissory_note_deutschebank_es/readme/DESCRIPTION.rst
  account_promissory_note_deutschebank_es/readme/USAGE.rst
  account_promissory_note_deutschebank_es/report/__init__.py
  account_promissory_note_deutschebank_es/report/account_promissory_note_writing_report.xml
  account_promissory_note_deutschebank_es/report/check_print.py
  account_promissory_note_deutschebank_es/static/description/icon.png
  account_promissory_note_deutschebank_es/static/description/index.html
  account_promissory_note_deutschebank_es/views/report_promissory_note.xml
Labels: approved, bot is merging ⏳, ready to merge

#1502 [13.0] [MIG] account_promissory_note_bankia: Migration to v13
  account_promissory_note_bankia/README.rst
  account_promissory_note_bankia/__init__.py
  account_promissory_note_bankia/__manifest__.py
  account_promissory_note_bankia/data/account_promissory_note_report_data.xml
  account_promissory_note_bankia/i18n/account_promissory_note_bankia.pot
  account_promissory_note_bankia/i18n/es.po
  account_promissory_note_bankia/readme/CONFIGURE.rst
  account_promissory_note_bankia/readme/CONTRIBUTORS.rst
  account_promissory_note_bankia/readme/DESCRIPTION.rst
  account_promissory_note_bankia/readme/USAGE.rst
  account_promissory_note_bankia/report/__init__.py
  account_promissory_note_bankia/report/account_promissory_note_writing_report.xml
  account_promissory_note_bankia/report/check_print.py
  account_promissory_note_bankia/static/description/icon.png
  account_promissory_note_bankia/static/description/index.html
  account_promissory_note_bankia/views/report_promissory_note.xml
  oca_dependencies.txt
  setup/account_promissory_note_bankia/odoo/addons/account_promissory_note_bankia
  setup/account_promissory_note_bankia/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1508 [11.0] fix send importe total IRPF
  l10n_es_aeat_sii/README.rst
  l10n_es_aeat_sii/data/aeat_sii_map_data.xml
  l10n_es_aeat_sii/models/account_invoice.py
  l10n_es_aeat_sii/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii/static/description/index.html
  l10n_es_aeat_sii/tests/test_l10n_es_aeat_sii.py
Labels: bot is merging ⏳

#1505 12.0 mig account invoice import facturae
  account_invoice_import_facturae/README.rst
  account_invoice_import_facturae/__init__.py
  account_invoice_import_facturae/__manifest__.py
  account_invoice_import_facturae/data/Extension FACEB2B v1-1.xsd
  account_invoice_import_facturae/data/FormatoXSD V1.0.xsd
  account_invoice_import_facturae/data/UtilitiesExtension.xsd
  account_invoice_import_facturae/data/xmldsig-core-schema.xsd
  account_invoice_import_facturae/i18n/account_invoice_import_facturae.pot
  account_invoice_import_facturae/readme/CONTRIBUTORS.rst
  account_invoice_import_facturae/readme/DESCRIPTION.rst
  account_invoice_import_facturae/readme/ROADMAP.rst
  account_invoice_import_facturae/readme/USAGE.rst
  account_invoice_import_facturae/static/description/icon.png
  account_invoice_import_facturae/static/description/index.html
  account_invoice_import_facturae/tests/__init__.py
  account_invoice_import_facturae/tests/files/facturae_01.xsig
  account_invoice_import_facturae/tests/files/facturae_02.xsig
  account_invoice_import_facturae/tests/files/facturae_03.xsig
  account_invoice_import_facturae/tests/files/facturae_04.xsig
  account_invoice_import_facturae/tests/test_import_facturae.py
  account_invoice_import_facturae/wizard/__init__.py
  account_invoice_import_facturae/wizard/account_invoice_import.py
  oca_dependencies.txt
  setup/account_invoice_import_facturae/odoo/addons/account_invoice_import_facturae
  setup/account_invoice_import_facturae/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1511 11.0 [FIX] l10n_es_aeat_sii: Allow to merge tax dictionaries w/o TipoImpositivo key
  l10n_es_aeat_sii/models/account_invoice.py
Labels: bot is merging ⏳

#1509 [MIG] l10n_es_partner: Migration to 14.0
  l10n_es_partner/README.rst
  l10n_es_partner/__init__.py
  l10n_es_partner/__manifest__.py
  l10n_es_partner/data/l10n_es_partner_data.xml
  l10n_es_partner/gen_src/README.rst
  l10n_es_partner/gen_src/__init__.py
  l10n_es_partner/gen_src/bics.xls
  l10n_es_partner/gen_src/gen_data_banks.py
  l10n_es_partner/i18n/bg.po
  l10n_es_partner/i18n/ca.po
  l10n_es_partner/i18n/cs.po
  l10n_es_partner/i18n/de.po
  l10n_es_partner/i18n/es.po
  l10n_es_partner/i18n/es_CO.po
  l10n_es_partner/i18n/es_CR.po
  l10n_es_partner/i18n/es_ES.po
  l10n_es_partner/i18n/eu.po
  l10n_es_partner/i18n/fr.po
  l10n_es_partner/i18n/gl.po
  l10n_es_partner/i18n/hr.po
  l10n_es_partner/i18n/l10n_es_partner.pot
  l10n_es_partner/i18n/nl.po
  l10n_es_partner/i18n/pl.po
  l10n_es_partner/i18n/pt.po
  l10n_es_partner/i18n/pt_BR.po
  l10n_es_partner/i18n/ru.po
  l10n_es_partner/i18n/sl.po
  l10n_es_partner/i18n/sv.po
  l10n_es_partner/i18n/tr.po
  l10n_es_partner/i18n/vi.po
  l10n_es_partner/models/__init__.py
  l10n_es_partner/models/res_bank.py
  l10n_es_partner/models/res_partner.py
  l10n_es_partner/readme/CONFIGURE.rst
  l10n_es_partner/readme/CONTRIBUTORS.rst
  l10n_es_partner/readme/DESCRIPTION.rst
  l10n_es_partner/readme/INSTALL.rst
  l10n_es_partner/readme/ROADMAP.rst
  l10n_es_partner/security/ir.model.access.csv
  l10n_es_partner/static/description/bank.svg
  l10n_es_partner/static/description/icon.png
  l10n_es_partner/static/description/index.html
  l10n_es_partner/tests/__init__.py
  l10n_es_partner/tests/test_l10n_es_partner.py
  l10n_es_partner/views/res_bank_view.xml
  l10n_es_partner/views/res_partner_view.xml
  l10n_es_partner/wizard/__init__.py
  l10n_es_partner/wizard/data_banks.xml
  l10n_es_partner/wizard/l10n_es_partner_wizard.py
  l10n_es_partner/wizard/l10n_es_partner_wizard.xml
  requirements.txt
  setup/l10n_es_partner/odoo/addons/l10n_es_partner
  setup/l10n_es_partner/setup.py
Labels: approved, bot is merging ⏳

#1515 [13.0][FIX] payment_redsys: Set Merchant titular as billing partner.
  payment_redsys/data/payment_redsys.xml
  payment_redsys/i18n/payment_redsys.pot
  payment_redsys/models/redsys.py
  payment_redsys/views/payment_acquirer.xml
Labels: approved, bot is merging ⏳

#1517 [13.0][IMP] payment_redsys: Ejecutar post procesado al recibir el formulario POST de Redsys
  payment_redsys/models/redsys.py
  payment_redsys/tests/test_redsys.py
Labels: approved, bot is merging ⏳

#1516 [12.0][IMP] payment_redsys: Ejecutar post procesado al recibir el formulario POST de Redsys
  payment_redsys/models/redsys.py
  payment_redsys/tests/test_redsys.py
Labels: approved, bot is merging ⏳

#1520 [12.0][FIX] payment_redsys: Avoid execute method por non Redsys acquirer
  payment_redsys/models/redsys.py
Labels: approved

#1523 [13.0][FIX] l10n_es_aeat_sii_oca: Proper registration key domain
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/views/account_move_views.xml
Labels: approved, bot is merging ⏳

#1513 [FIX]+[IMP]l10n_es_aeat_sii_oca: Added description image and fixed a micro typo
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/static/description/SII_1.jpg
Labels: bot is merging ⏳
