Repository OCA/l10n-spain, pull requests merged in 2020-04, with the labels that each got.

#1331 [12.0] l10n_es_aeat_*: Incluir nuevos tipos de no deducible
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_sii/data/aeat_sii_map_data.xml
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#1330 [IMP] l10n_es_account_bank_statement_import_n43: Set Date of the stat…
  l10n_es_account_bank_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
  l10n_es_account_bank_statement_import_n43/wizards/account_bank_statement_import_n43.py
Labels: bot is merging ⏳

#1339 [12.0] l10n_es_facturae: Aligerar dependencias
  l10n_es_facturae/README.rst
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae/models/account_invoice.py
  l10n_es_facturae/readme/INSTALL.rst
  l10n_es_facturae/static/description/index.html
  l10n_es_facturae/tests/test_l10n_es_facturae.py
  l10n_es_facturae/views/report_facturae.xml
Labels: approved, bot is merging ⏳

#1340 [FIX] l10n_es_aeat_mod303: fix 303 map for field number 60
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: bot is merging ⏳

#1314 [11.0][IMP] l10n_es_vat_book: Avoid error on irregular cases of taxes combination
  l10n_es_vat_book/models/l10n_es_vat_book.py
Labels: bot is merging ⏳

#1345 [11.0][FIX] l10n_es_aeat_mod349: operation key not computed on custom taxes
  l10n_es_aeat_mod349/README.rst
  l10n_es_aeat_mod349/models/account_tax.py
Labels: bot is merging ⏳

#1262 [12.0][FIX] 303,facturas rectivicativas en 93 y 94
  l10n_es_aeat_mod303/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: approved, bot is merging ⏳, ready to merge

#1349 [12.0] l10n_es_aeat_*: [FIX] Caracteres no válidos 'NIF Empresa Desarrollo'
  l10n_es_aeat_mod111/data/aeat_export_mod111_data.xml
  l10n_es_aeat_mod115/data/aeat_export_mod115_data.xml
  l10n_es_aeat_mod123/data/aeat_export_mod123_data.xml
  l10n_es_aeat_mod130/data/aeat_export_mod130_data.xml
  l10n_es_aeat_mod303/data/aeat_export_mod303_2018_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_main_data.xml
Labels: bot is merging ⏳

#1351 [11.0] l10n_es_aeat_*: [FIX] Caracteres no válidos 'NIF Empresa Desar…
  l10n_es_aeat_mod111/data/aeat_export_mod111_data.xml
  l10n_es_aeat_mod115/data/aeat_export_mod115_data.xml
  l10n_es_aeat_mod123/data/aeat_export_mod123_data.xml
  l10n_es_aeat_mod130/data/aeat_export_mod130_data.xml
  l10n_es_aeat_mod303/data/aeat_export_mod303_2018_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_main_data.xml
Labels: bot is merging ⏳

#1353 [8.0] l10n_es_aeat_*: [FIX] Caracteres no válidos 'NIF Empresa Desarr…
  l10n_es_aeat_mod111/data/aeat_export_mod111_data.xml
  l10n_es_aeat_mod123/data/aeat_export_mod123_data.xml
  l10n_es_aeat_mod303/data/aeat_export_mod303_2018_data.xml
Labels: bot is merging ⏳

#1299 [11.0][FIX] l10n_es_dua_sii: SII tab hidden when DUA's fiscal position has not been defined
  l10n_es_dua_sii/models/account_invoice.py
  l10n_es_dua_sii/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳
