Repository OCA/l10n-spain, pull requests merged in 2020-09, with the labels that each got.

#1452 [FIX] payment_redsys: quotation marks affecting order_lines_view
  payment_redsys/views/redsys.xml
Labels: approved, bot is merging ⏳

#1385 [12.0][IMP] l10n_es_facturae_face: Add cron & filter
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/data/cron_data.xml
  l10n_es_facturae_face/models/account_invoice_integration.py
  l10n_es_facturae_face/models/res_company.py
  l10n_es_facturae_face/tests/test_facturae_face.py
  l10n_es_facturae_face/wizard/account_invoice_integration_cancel.py
Labels: bot is merging ⏳

#1454 [11.0] [fix] l10n_es_account_bank_statement_import_n43
  l10n_es_account_bank_statement_import_n43/wizards/account_bank_statement_import_n43.py
Labels: approved, bot is merging ⏳

#1441 [13.0][MIG] l10n_es_aeat_mod115
  l10n_es_aeat_mod115/README.rst
  l10n_es_aeat_mod115/__init__.py
  l10n_es_aeat_mod115/__manifest__.py
  l10n_es_aeat_mod115/data/aeat_export_mod115_data.xml
  l10n_es_aeat_mod115/data/tax_code_map_mod115_data.xml
  l10n_es_aeat_mod115/docs/DR115e15v11.xls
  l10n_es_aeat_mod115/i18n/bg.po
  l10n_es_aeat_mod115/i18n/ca.po
  l10n_es_aeat_mod115/i18n/cs.po
  l10n_es_aeat_mod115/i18n/es.po
  l10n_es_aeat_mod115/i18n/es_CO.po
  l10n_es_aeat_mod115/i18n/es_CR.po
  l10n_es_aeat_mod115/i18n/eu.po
  l10n_es_aeat_mod115/i18n/fr.po
  l10n_es_aeat_mod115/i18n/gl.po
  l10n_es_aeat_mod115/i18n/hr.po
  l10n_es_aeat_mod115/i18n/l10n_es_aeat_mod115.pot
  l10n_es_aeat_mod115/i18n/nl.po
  l10n_es_aeat_mod115/i18n/pl.po
  l10n_es_aeat_mod115/i18n/pt.po
  l10n_es_aeat_mod115/i18n/pt_BR.po
  l10n_es_aeat_mod115/i18n/ru.po
  l10n_es_aeat_mod115/i18n/sl.po
  l10n_es_aeat_mod115/i18n/sv.po
  l10n_es_aeat_mod115/i18n/tr.po
  l10n_es_aeat_mod115/i18n/vi.po
  l10n_es_aeat_mod115/migrations/13.0.1.0.0/noupdate_changes.xml
  l10n_es_aeat_mod115/migrations/13.0.1.0.0/post-migration.py
  l10n_es_aeat_mod115/migrations/13.0.1.0.0/pre_migration.py
  l10n_es_aeat_mod115/models/__init__.py
  l10n_es_aeat_mod115/models/mod115.py
  l10n_es_aeat_mod115/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod115/readme/DESCRIPTION.rst
  l10n_es_aeat_mod115/readme/USAGE.rst
  l10n_es_aeat_mod115/security/ir.model.access.csv
  l10n_es_aeat_mod115/security/l10n_es_aeat_mod115_security.xml
  l10n_es_aeat_mod115/static/description/icon.png
  l10n_es_aeat_mod115/static/description/icon_source.svg
  l10n_es_aeat_mod115/static/description/index.html
  l10n_es_aeat_mod115/tests/__init__.py
  l10n_es_aeat_mod115/tests/test_l10n_es_aeat_mod115.py
  l10n_es_aeat_mod115/views/mod115_view.xml
  setup/l10n_es_aeat_mod115/odoo/addons/l10n_es_aeat_mod115
  setup/l10n_es_aeat_mod115/setup.py
Labels: approved, bot is merging ⏳, needs review

#1456 [FIX] delivery_seur: Cash on Delivery value
  delivery_seur/models/delivery_carrier.py
Labels: bot is merging ⏳

#1461 [11.0][FIX] l10n_es_aeat_sii: Added rounding for "Régimen agrario" key ImporteCompensacionREAGYP
  l10n_es_aeat_sii/models/account_invoice.py
Labels: approved, bot is merging ⏳

#1462 [12.0][FIX] l10n_es_aeat_sii: Added rounding for "Régimen agrario" key ImporteCompensacionREAGYP
  l10n_es_aeat_sii/models/account_invoice.py
Labels: bot is merging ⏳

#1460 [13][FIX] l10n_es_vat_book: multicompany_rule
  l10n_es_vat_book/migrations/13.0.1.1.0/post-migration.py
  l10n_es_vat_book/security/ir_rule.xml
Labels: bot is merging ⏳

#1458 [FIX][12.0] delivery_seur: weight data and error catching
  delivery_seur/README.rst
  delivery_seur/__manifest__.py
  delivery_seur/models/__init__.py
  delivery_seur/models/delivery_carrier.py
  delivery_seur/models/stock_picking.py
  delivery_seur/readme/CONTRIBUTORS.rst
  delivery_seur/static/description/index.html
  delivery_seur/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#1470 [12.0] [REF+FIX] l10n_es_aeat_sii: Fusionar bloques `DetalleIva` para el mismo `TipoImpositivo`
  l10n_es_aeat_sii/models/account_invoice.py
Labels: approved, bot is merging ⏳

#1463 [IMP] l10n_es_aeat_sii: Refund type
  l10n_es_aeat_sii/models/account_invoice.py
  l10n_es_aeat_sii/tests/test_l10n_es_aeat_sii.py
Labels: approved, bot is merging ⏳
