Repository OCA/l10n-spain, pull requests merged in 2020-08, with the labels that each got.

#1440 [13.0][MIG] l10n_es_aeat_mod347: Migration to v13
  l10n_es_aeat_mod347/README.rst
  l10n_es_aeat_mod347/__init__.py
  l10n_es_aeat_mod347/__manifest__.py
  l10n_es_aeat_mod347/controllers/__init__.py
  l10n_es_aeat_mod347/controllers/main.py
  l10n_es_aeat_mod347/data/aeat_export_mod347_data.xml
  l10n_es_aeat_mod347/data/aeat_export_mod347_partner_data.xml
  l10n_es_aeat_mod347/data/aeat_export_mod347_real_state_data.xml
  l10n_es_aeat_mod347/data/mail_template_data.xml
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
  l10n_es_aeat_mod347/docs/347_register_design.pdf
  l10n_es_aeat_mod347/i18n/bg.po
  l10n_es_aeat_mod347/i18n/ca.po
  l10n_es_aeat_mod347/i18n/cs.po
  l10n_es_aeat_mod347/i18n/es.po
  l10n_es_aeat_mod347/i18n/es_CO.po
  l10n_es_aeat_mod347/i18n/es_CR.po
  l10n_es_aeat_mod347/i18n/eu.po
  l10n_es_aeat_mod347/i18n/fr.po
  l10n_es_aeat_mod347/i18n/gl.po
  l10n_es_aeat_mod347/i18n/hr.po
  l10n_es_aeat_mod347/i18n/l10n_es_aeat_mod347.pot
  l10n_es_aeat_mod347/i18n/nl.po
  l10n_es_aeat_mod347/i18n/pl.po
  l10n_es_aeat_mod347/i18n/pt.po
  l10n_es_aeat_mod347/i18n/pt_BR.po
  l10n_es_aeat_mod347/i18n/ru.po
  l10n_es_aeat_mod347/i18n/sl.po
  l10n_es_aeat_mod347/i18n/sv.po
  l10n_es_aeat_mod347/i18n/tr.po
  l10n_es_aeat_mod347/i18n/vi.po
  l10n_es_aeat_mod347/images/l10n_es_aeat_mod347.png
  l10n_es_aeat_mod347/migrations/13.0.1.0.0/noupdate_changes.xml
  l10n_es_aeat_mod347/migrations/13.0.1.0.0/post-migration.py
  l10n_es_aeat_mod347/models/__init__.py
  l10n_es_aeat_mod347/models/account_move.py
  l10n_es_aeat_mod347/models/mod347.py
  l10n_es_aeat_mod347/models/res_partner.py
  l10n_es_aeat_mod347/readme/CONFIG.rst
  l10n_es_aeat_mod347/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod347/readme/DESCRIPTION.rst
  l10n_es_aeat_mod347/readme/INSTALL.rst
  l10n_es_aeat_mod347/readme/ROADMAP.rst
  l10n_es_aeat_mod347/readme/USAGE.rst
  l10n_es_aeat_mod347/security/ir.model.access.csv
  l10n_es_aeat_mod347/security/mod_347_security.xml
  l10n_es_aeat_mod347/static/description/icon.png
  l10n_es_aeat_mod347/static/description/icon_source.svg
  l10n_es_aeat_mod347/static/description/index.html
  l10n_es_aeat_mod347/static/src/img/347_bad.svg
  l10n_es_aeat_mod347/static/src/img/347_ok.svg
  l10n_es_aeat_mod347/tests/__init__.py
  l10n_es_aeat_mod347/tests/test_l10n_es_aeat_mod347.py
  l10n_es_aeat_mod347/views/account_move_view.xml
  l10n_es_aeat_mod347/views/mod347_templates.xml
  l10n_es_aeat_mod347/views/mod347_view.xml
  l10n_es_aeat_mod347/views/report_347_partner.xml
  l10n_es_aeat_mod347/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#1445 [IMP] l10n_es_mis_report: Unfold 746 in 2 accounts
  l10n_es_mis_report/data/mis_report_pyg_normal.xml
  l10n_es_mis_report/data/mis_report_pyg_sme.xml
Labels: approved, bot is merging ⏳

#1391 [13.0][MIG] l10n_es_account_asset
  l10n_es_account_asset/README.rst
  l10n_es_account_asset/__init__.py
  l10n_es_account_asset/__manifest__.py
  l10n_es_account_asset/i18n/ca.po
  l10n_es_account_asset/i18n/cs.po
  l10n_es_account_asset/i18n/de.po
  l10n_es_account_asset/i18n/es.po
  l10n_es_account_asset/i18n/es_CO.po
  l10n_es_account_asset/i18n/fr.po
  l10n_es_account_asset/i18n/fr_BE.po
  l10n_es_account_asset/i18n/gl.po
  l10n_es_account_asset/i18n/hr.po
  l10n_es_account_asset/i18n/l10n_es_account_asset.pot
  l10n_es_account_asset/i18n/pl.po
  l10n_es_account_asset/i18n/pt.po
  l10n_es_account_asset/i18n/pt_BR.po
  l10n_es_account_asset/i18n/ru.po
  l10n_es_account_asset/i18n/sl.po
  l10n_es_account_asset/i18n/sv.po
  l10n_es_account_asset/i18n/vi.po
  l10n_es_account_asset/models/__init__.py
  l10n_es_account_asset/models/account_asset.py
  l10n_es_account_asset/models/account_asset_profile.py
  l10n_es_account_asset/readme/CONTRIBUTORS.rst
  l10n_es_account_asset/readme/DESCRIPTION.rst
  l10n_es_account_asset/static/description/icon.png
  l10n_es_account_asset/static/description/index.html
  l10n_es_account_asset/tests/__init__.py
  l10n_es_account_asset/tests/test_l10n_es_account_asset.py
  l10n_es_account_asset/views/account_asset_profile_views.xml
  l10n_es_account_asset/views/account_asset_views.xml
  oca_dependencies.txt
  setup/l10n_es_account_asset/odoo/addons/l10n_es_account_asset
  setup/l10n_es_account_asset/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1448 [12.0][IMP] delivery_seur: replace field weight to shipping_weight
  delivery_seur/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#1392 [12.0][ADD] delivery_gls_asm: New module
  delivery_gls_asm/README.rst
  delivery_gls_asm/__init__.py
  delivery_gls_asm/__manifest__.py
  delivery_gls_asm/api/gls_asm_api.wsdl
  delivery_gls_asm/data/delivery_asm_data.xml
  delivery_gls_asm/i18n/delivery_gls_asm.pot
  delivery_gls_asm/i18n/es.po
  delivery_gls_asm/models/__init__.py
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/models/gls_asm_request.py
  delivery_gls_asm/models/stock_picking.py
  delivery_gls_asm/readme/CONFIGURE.rst
  delivery_gls_asm/readme/CONTRIBUTORS.rst
  delivery_gls_asm/readme/DESCRIPTION.rst
  delivery_gls_asm/readme/INSTALL.rst
  delivery_gls_asm/readme/ROADMAP.rst
  delivery_gls_asm/readme/USAGE.rst
  delivery_gls_asm/static/description/icon.png
  delivery_gls_asm/static/description/icon.svg
  delivery_gls_asm/static/description/index.html
  delivery_gls_asm/tests/__init__.py
  delivery_gls_asm/tests/test_delivery_gls_asm.py
  delivery_gls_asm/views/delivery_asm_view.xml
  delivery_gls_asm/views/gls_asm_manifest_template.xml
  delivery_gls_asm/views/stock_picking_views.xml
  delivery_gls_asm/wizard/__init__.py
  delivery_gls_asm/wizard/gls_asm_manifest_wizard.py
  delivery_gls_asm/wizard/gls_asm_manifest_wizard_views.xml
Labels: bot is merging ⏳

#1315 [13.0][MIG] l10n_es_account_banking_sepa_fsdd
  l10n_es_account_banking_sepa_fsdd/README.rst
  l10n_es_account_banking_sepa_fsdd/__init__.py
  l10n_es_account_banking_sepa_fsdd/__manifest__.py
  l10n_es_account_banking_sepa_fsdd/i18n/ca.po
  l10n_es_account_banking_sepa_fsdd/i18n/es.po
  l10n_es_account_banking_sepa_fsdd/i18n/es_ES.po
  l10n_es_account_banking_sepa_fsdd/i18n/fr.po
  l10n_es_account_banking_sepa_fsdd/i18n/l10n_es_account_banking_sepa_fsdd.pot
  l10n_es_account_banking_sepa_fsdd/i18n/nl.po
  l10n_es_account_banking_sepa_fsdd/i18n/pt_BR.po
  l10n_es_account_banking_sepa_fsdd/i18n/sl.po
  l10n_es_account_banking_sepa_fsdd/models/__init__.py
  l10n_es_account_banking_sepa_fsdd/models/account_payment_mode.py
  l10n_es_account_banking_sepa_fsdd/models/account_payment_order.py
  l10n_es_account_banking_sepa_fsdd/readme/CONFIGURE.rst
  l10n_es_account_banking_sepa_fsdd/readme/CONTRIBUTORS.rst
  l10n_es_account_banking_sepa_fsdd/readme/DESCRIPTION.rst
  l10n_es_account_banking_sepa_fsdd/readme/INSTALL.rst
  l10n_es_account_banking_sepa_fsdd/static/description/icon.png
  l10n_es_account_banking_sepa_fsdd/static/description/index.html
  l10n_es_account_banking_sepa_fsdd/tests/__init__.py
  l10n_es_account_banking_sepa_fsdd/tests/test_l10n_es_account_banking_sepa_fsdd.py
  l10n_es_account_banking_sepa_fsdd/views/payment_mode_view.xml
  oca_dependencies.txt
  setup/l10n_es_account_banking_sepa_fsdd/odoo/addons/l10n_es_account_banking_sepa_fsdd
  setup/l10n_es_account_banking_sepa_fsdd/setup.py
Labels: bot is merging ⏳

#1432 [13.0][MIG] l10n_es_account_bank_statement_import_n43: Migration to v.13
  l10n_es_account_bank_statement_import_n43/README.rst
  l10n_es_account_bank_statement_import_n43/__init__.py
  l10n_es_account_bank_statement_import_n43/__manifest__.py
  l10n_es_account_bank_statement_import_n43/doc/norma_43_castellano.pdf
  l10n_es_account_bank_statement_import_n43/i18n/ca.po
  l10n_es_account_bank_statement_import_n43/i18n/es.po
  l10n_es_account_bank_statement_import_n43/i18n/eu.po
  l10n_es_account_bank_statement_import_n43/i18n/fr.po
  l10n_es_account_bank_statement_import_n43/i18n/gl.po
  l10n_es_account_bank_statement_import_n43/i18n/l10n_es_account_bank_statement_import_n43.pot
  l10n_es_account_bank_statement_import_n43/i18n/sl.po
  l10n_es_account_bank_statement_import_n43/models/__init__.py
  l10n_es_account_bank_statement_import_n43/models/account_journal.py
  l10n_es_account_bank_statement_import_n43/readme/CONTRIBUTORS.rst
  l10n_es_account_bank_statement_import_n43/readme/DESCRIPTION.rst
  l10n_es_account_bank_statement_import_n43/readme/ROADMAP.rst
  l10n_es_account_bank_statement_import_n43/readme/USAGE.rst
  l10n_es_account_bank_statement_import_n43/static/description/icon.png
  l10n_es_account_bank_statement_import_n43/static/description/icon_src.svg
  l10n_es_account_bank_statement_import_n43/static/description/index.html
  l10n_es_account_bank_statement_import_n43/tests/__init__.py
  l10n_es_account_bank_statement_import_n43/tests/test.n43
  l10n_es_account_bank_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
  l10n_es_account_bank_statement_import_n43/views/account_journal_views.xml
  l10n_es_account_bank_statement_import_n43/wizards/__init__.py
  l10n_es_account_bank_statement_import_n43/wizards/account_bank_statement_import_n43.py
  l10n_es_account_bank_statement_import_n43/wizards/account_bank_statement_import_view.xml
  setup/l10n_es_account_bank_statement_import_n43/odoo/addons/l10n_es_account_bank_statement_import_n43
  setup/l10n_es_account_bank_statement_import_n43/setup.py
Labels: approved, bot is merging ⏳, ready to merge
