Repository OCA/l10n-spain, pull requests merged in 2020-10, with the labels that each got.

#1414 [12.0][FIX] Envío al SII ImporteTotal sin IRPF en facturas de proveedor
  l10n_es_aeat_sii/README.rst
  l10n_es_aeat_sii/data/aeat_sii_map_data.xml
  l10n_es_aeat_sii/models/account_invoice.py
  l10n_es_aeat_sii/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii/static/description/index.html
  l10n_es_aeat_sii/tests/test_l10n_es_aeat_sii.py
Labels: bot is merging ⏳

#1478 [13.0][UPD] Eficent -> ForgeFlow
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/readme/CONTRIBUTORS.rst
  l10n_es_vat_book/__manifest__.py
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/models/l10n_es_vat_book_line.py
  l10n_es_vat_book/models/l10n_es_vat_book_line_tax.py
  l10n_es_vat_book/models/l10n_es_vat_book_summary.py
  l10n_es_vat_book/models/l10n_es_vat_book_tax_summary.py
  l10n_es_vat_book/readme/CONTRIBUTORS.rst
  l10n_es_vat_book/tests/test_l10n_es_aeat_vat_book.py
Labels: bot is merging ⏳

#1468 [FIX] delivery_seur: dead locks
  delivery_seur/models/delivery_carrier.py
Labels: approved, bot is merging ⏳, ready to merge

#1482 [IMP] delivery_gls and delivery_seur: add informative exceptions
  delivery_gls_asm/models/delivery_carrier.py
  delivery_seur/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#1484 [FIX] delivery_gls_asm: manifest
  delivery_gls_asm/models/gls_asm_request.py
Labels: approved, bot is merging ⏳

#1489 [FIX] delivery_gls_manifest: manifest destination name
  delivery_gls_asm/views/gls_asm_manifest_template.xml
Labels: bot is merging ⏳

#1451 [13.0][MIG] l10n_es_aeat_mod123: Migration to v.13
  l10n_es_aeat_mod123/README.rst
  l10n_es_aeat_mod123/__init__.py
  l10n_es_aeat_mod123/__manifest__.py
  l10n_es_aeat_mod123/data/aeat_export_mod123_data.xml
  l10n_es_aeat_mod123/data/tax_code_map_mod123.xml
  l10n_es_aeat_mod123/i18n/bg.po
  l10n_es_aeat_mod123/i18n/ca.po
  l10n_es_aeat_mod123/i18n/cs.po
  l10n_es_aeat_mod123/i18n/de.po
  l10n_es_aeat_mod123/i18n/es.po
  l10n_es_aeat_mod123/i18n/es_CO.po
  l10n_es_aeat_mod123/i18n/es_CR.po
  l10n_es_aeat_mod123/i18n/es_ES.po
  l10n_es_aeat_mod123/i18n/eu.po
  l10n_es_aeat_mod123/i18n/fr.po
  l10n_es_aeat_mod123/i18n/gl.po
  l10n_es_aeat_mod123/i18n/hr.po
  l10n_es_aeat_mod123/i18n/l10n_es_aeat_mod123.pot
  l10n_es_aeat_mod123/i18n/nl.po
  l10n_es_aeat_mod123/i18n/pl.po
  l10n_es_aeat_mod123/i18n/pt.po
  l10n_es_aeat_mod123/i18n/pt_BR.po
  l10n_es_aeat_mod123/i18n/sl.po
  l10n_es_aeat_mod123/i18n/sv.po
  l10n_es_aeat_mod123/i18n/tr.po
  l10n_es_aeat_mod123/i18n/vi.po
  l10n_es_aeat_mod123/models/__init__.py
  l10n_es_aeat_mod123/models/mod123.py
  l10n_es_aeat_mod123/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod123/readme/DESCRIPTION.rst
  l10n_es_aeat_mod123/readme/USAGE.rst
  l10n_es_aeat_mod123/security/ir.model.access.csv
  l10n_es_aeat_mod123/static/description/icon.png
  l10n_es_aeat_mod123/static/description/icon_source.svg
  l10n_es_aeat_mod123/static/description/index.html
  l10n_es_aeat_mod123/tests/__init__.py
  l10n_es_aeat_mod123/tests/test_l10n_es_aeat_mod123.py
  l10n_es_aeat_mod123/views/mod123_view.xml
  setup/l10n_es_aeat_mod123/odoo/addons/l10n_es_aeat_mod123
  setup/l10n_es_aeat_mod123/setup.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1492 [MIG] l10n_es_partner_mercantil: Migration to 14.0
  l10n_es_partner_mercantil/README.rst
  l10n_es_partner_mercantil/__init__.py
  l10n_es_partner_mercantil/__manifest__.py
  l10n_es_partner_mercantil/i18n/bg.po
  l10n_es_partner_mercantil/i18n/ca.po
  l10n_es_partner_mercantil/i18n/en.po
  l10n_es_partner_mercantil/i18n/es.po
  l10n_es_partner_mercantil/i18n/eu.po
  l10n_es_partner_mercantil/i18n/fr.po
  l10n_es_partner_mercantil/i18n/gl.po
  l10n_es_partner_mercantil/i18n/hr.po
  l10n_es_partner_mercantil/i18n/l10n_es_partner_mercantil.pot
  l10n_es_partner_mercantil/i18n/nl.po
  l10n_es_partner_mercantil/i18n/pt.po
  l10n_es_partner_mercantil/i18n/pt_BR.po
  l10n_es_partner_mercantil/i18n/sl.po
  l10n_es_partner_mercantil/models/__init__.py
  l10n_es_partner_mercantil/models/partner_es.py
  l10n_es_partner_mercantil/readme/CONTRIBUTORS.rst
  l10n_es_partner_mercantil/readme/DESCRIPTION.rst
  l10n_es_partner_mercantil/readme/USAGE.rst
  l10n_es_partner_mercantil/static/description/icon.png
  l10n_es_partner_mercantil/static/description/icon.svg
  l10n_es_partner_mercantil/static/description/index.html
  l10n_es_partner_mercantil/views/res_partner_view.xml
  setup/l10n_es_partner_mercantil/odoo/addons/l10n_es_partner_mercantil
  setup/l10n_es_partner_mercantil/setup.py
Labels: approved, bot is merging ⏳

#1459 [11.0][FIX] payment_redsys: Set Merchant titular as billing partner.
  payment_redsys/data/payment_redsys.xml
  payment_redsys/i18n/es.po
  payment_redsys/i18n/payment_redsys.pot
  payment_redsys/models/redsys.py
  payment_redsys/tests/test_redsys.py
  payment_redsys/views/payment_acquirer.xml
Labels: bot is merging ⏳

#1280 [11.0][ADD] Modelo 190 Aeat
  l10n_es_aeat_mod190/README.rst
  l10n_es_aeat_mod190/__init__.py
  l10n_es_aeat_mod190/__manifest__.py
  l10n_es_aeat_mod190/data/aeat_export_mod190_data.xml
  l10n_es_aeat_mod190/data/aeat_export_mod190_partner_data.xml
  l10n_es_aeat_mod190/data/perception_key_data.xml
  l10n_es_aeat_mod190/data/perception_subkey_data.xml
  l10n_es_aeat_mod190/data/tax_code_map_mod190_data.xml
  l10n_es_aeat_mod190/docs/DR190_2017.pdf
  l10n_es_aeat_mod190/migrations/11.0.2.0.0/post-migration.py
  l10n_es_aeat_mod190/models/__init__.py
  l10n_es_aeat_mod190/models/account_fiscal_position.py
  l10n_es_aeat_mod190/models/account_invoice.py
  l10n_es_aeat_mod190/models/account_move_line.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_perception.py
  l10n_es_aeat_mod190/models/l10n_es_mod190_additional_data_mixin.py
  l10n_es_aeat_mod190/models/l10n_es_mod190_mixin.py
  l10n_es_aeat_mod190/models/res_partner.py
  l10n_es_aeat_mod190/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod190/readme/DESCRIPTION.rst
  l10n_es_aeat_mod190/readme/USAGE.rst
  l10n_es_aeat_mod190/security/ir.model.access.csv
  l10n_es_aeat_mod190/security/l10n_es_aeat_mod190_security.xml
  l10n_es_aeat_mod190/static/description/icon.png
  l10n_es_aeat_mod190/static/description/icon_source.svg
  l10n_es_aeat_mod190/static/description/index.html
  l10n_es_aeat_mod190/tests/__init__.py
  l10n_es_aeat_mod190/tests/test_mod190.py
  l10n_es_aeat_mod190/views/account_fiscal_position.xml
  l10n_es_aeat_mod190/views/account_invoice_view.xml
  l10n_es_aeat_mod190/views/account_move_view.xml
  l10n_es_aeat_mod190/views/mod190_line_view.xml
  l10n_es_aeat_mod190/views/mod190_view.xml
  l10n_es_aeat_mod190/views/partner_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1358 12.0 mig l10n es aeat mod190
  l10n_es_aeat_mod190/README.rst
  l10n_es_aeat_mod190/__init__.py
  l10n_es_aeat_mod190/__manifest__.py
  l10n_es_aeat_mod190/data/aeat_export_mod190_data.xml
  l10n_es_aeat_mod190/data/aeat_export_mod190_partner_data.xml
  l10n_es_aeat_mod190/data/perception_key_data.xml
  l10n_es_aeat_mod190/data/perception_subkey_data.xml
  l10n_es_aeat_mod190/data/res_country_state.xml
  l10n_es_aeat_mod190/data/tax_code_map_mod190_data.xml
  l10n_es_aeat_mod190/docs/DR190_2017.pdf
  l10n_es_aeat_mod190/models/__init__.py
  l10n_es_aeat_mod190/models/account_fiscal_position.py
  l10n_es_aeat_mod190/models/account_invoice.py
  l10n_es_aeat_mod190/models/account_move_line.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_perception.py
  l10n_es_aeat_mod190/models/res_country_state.py
  l10n_es_aeat_mod190/models/res_partner.py
  l10n_es_aeat_mod190/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod190/readme/DESCRIPTION.rst
  l10n_es_aeat_mod190/readme/USAGE.rst
  l10n_es_aeat_mod190/security/ir.model.access.csv
  l10n_es_aeat_mod190/security/l10n_es_aeat_mod190_security.xml
  l10n_es_aeat_mod190/static/description/icon.png
  l10n_es_aeat_mod190/static/description/icon_source.svg
  l10n_es_aeat_mod190/static/description/index.html
  l10n_es_aeat_mod190/tests/__init__.py
  l10n_es_aeat_mod190/tests/test_mod190.py
  l10n_es_aeat_mod190/views/account_fiscal_position.xml
  l10n_es_aeat_mod190/views/account_invoice_view.xml
  l10n_es_aeat_mod190/views/account_move_view.xml
  l10n_es_aeat_mod190/views/mod190_line_view.xml
  l10n_es_aeat_mod190/views/mod190_view.xml
  l10n_es_aeat_mod190/views/partner_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1496 [12.0][FIX] payment_redsys: Set Merchant titular as billing partner.
  payment_redsys/data/payment_redsys.xml
  payment_redsys/i18n/payment_redsys.pot
  payment_redsys/models/redsys.py
  payment_redsys/views/payment_acquirer.xml
Labels: bot is merging ⏳

#1487 [FIX] delivery_seur: zebra label
  delivery_seur/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#941 [ADD] account invoice import facturae
  account_invoice_import_facturae/__init__.py
  account_invoice_import_facturae/__manifest__.py
  account_invoice_import_facturae/data/Extension FACEB2B v1-1.xsd
  account_invoice_import_facturae/data/Facturaev3_2.xsd
  account_invoice_import_facturae/data/Facturaev3_2_1.xsd
  account_invoice_import_facturae/data/Facturaev3_2_1_wrapper.xsd
  account_invoice_import_facturae/data/FormatoXSD V1.0.xsd
  account_invoice_import_facturae/data/UtilitiesExtension.xsd
  account_invoice_import_facturae/data/xmldsig-core-schema.xsd
  account_invoice_import_facturae/readme/CONTRIBUTORS.rst
  account_invoice_import_facturae/readme/DESCRIPTION.rst
  account_invoice_import_facturae/readme/ROADMAP.rst
  account_invoice_import_facturae/readme/USAGE.rst
  account_invoice_import_facturae/tests/__init__.py
  account_invoice_import_facturae/tests/files/facturae_01.xsig
  account_invoice_import_facturae/tests/files/facturae_02.xsig
  account_invoice_import_facturae/tests/files/facturae_03.xsig
  account_invoice_import_facturae/tests/files/facturae_04.xsig
  account_invoice_import_facturae/tests/test_import_facturae.py
  account_invoice_import_facturae/wizard/__init__.py
  account_invoice_import_facturae/wizard/account_invoice_import.py
  oca_dependencies.txt
Labels: approved, bot is merging ⏳, ready to merge

#1473 [12.0] [ADD] account_promissory_note_bankia: Add promissory note format for Bankia Bank
  account_promissory_note_bankia/README.rst
  account_promissory_note_bankia/__init__.py
  account_promissory_note_bankia/__manifest__.py
  account_promissory_note_bankia/data/account_promissory_note_report_data.xml
  account_promissory_note_bankia/i18n/account_promissory_note_bankia.pot
  account_promissory_note_bankia/i18n/es.po
  account_promissory_note_bankia/readme/CONFIGURE.rst
  account_promissory_note_bankia/readme/CONTRIBUTORS.rst
  account_promissory_note_bankia/readme/DESCRIPTION.rst
  account_promissory_note_bankia/readme/USAGE.rst
  account_promissory_note_bankia/report/__init__.py
  account_promissory_note_bankia/report/account_promissory_note_writing_report.xml
  account_promissory_note_bankia/report/check_print.py
  account_promissory_note_bankia/static/description/icon.png
  account_promissory_note_bankia/static/description/index.html
  account_promissory_note_bankia/views/report_promissory_note.xml
  oca_dependencies.txt
Labels: bot is merging ⏳
