Repository OCA/l10n-spain, pull requests merged in 2020-05, with the labels that each got.

#1354 [11.0][FIX] l10n_es_vat_book: Error on special line
  l10n_es_vat_book/models/l10n_es_vat_book.py
Labels: bot is merging ⏳

#1355 [11.0][FIX] l10n_es_aeat_mod303: Se añade el iva exento repercutido
  l10n_es_aeat_mod303/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: approved, bot is merging ⏳, ready to merge

#1370 [12.0][FIX] Double button box
  l10n_es_facturae/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳

#1329 [11.0] l10n_es_aeat_*: Incluir nuevos tipos de no deducible
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_sii/data/aeat_sii_map_data.xml
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: approved, bot is merging ⏳

#1361 [13.0][MIG] l10n_es_pos: Migration to v13.0
  l10n_es_pos/README.rst
  l10n_es_pos/__init__.py
  l10n_es_pos/__manifest__.py
  l10n_es_pos/hooks.py
  l10n_es_pos/i18n/ca.po
  l10n_es_pos/i18n/ca_ES.po
  l10n_es_pos/i18n/es.po
  l10n_es_pos/i18n/l10n_es_pos.pot
  l10n_es_pos/models/__init__.py
  l10n_es_pos/models/ir_sequence.py
  l10n_es_pos/models/pos_config.py
  l10n_es_pos/models/pos_order.py
  l10n_es_pos/readme/CONFIGURE.rst
  l10n_es_pos/readme/CONTRIBUTORS.rst
  l10n_es_pos/readme/DESCRIPTION.rst
  l10n_es_pos/readme/INSTALL.rst
  l10n_es_pos/readme/ROADMAP.rst
  l10n_es_pos/static/description/icon.png
  l10n_es_pos/static/description/index.html
  l10n_es_pos/static/src/js/models.js
  l10n_es_pos/static/src/js/screens.js
  l10n_es_pos/static/src/xml/pos.xml
  l10n_es_pos/views/pos_templates.xml
  l10n_es_pos/views/pos_views.xml
  setup/l10n_es_pos/odoo/addons/l10n_es_pos
  setup/l10n_es_pos/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1343 [13.0] [MIG] payment_redsys: Migration to v13
  payment_redsys/README.rst
  payment_redsys/__init__.py
  payment_redsys/__manifest__.py
  payment_redsys/controllers/__init__.py
  payment_redsys/controllers/main.py
  payment_redsys/data/payment_redsys.xml
  payment_redsys/i18n/bg.po
  payment_redsys/i18n/ca.po
  payment_redsys/i18n/es.po
  payment_redsys/i18n/fr.po
  payment_redsys/i18n/gl.po
  payment_redsys/i18n/hr.po
  payment_redsys/i18n/payment_redsys.pot
  payment_redsys/i18n/pt_BR.po
  payment_redsys/i18n/sl.po
  payment_redsys/models/__init__.py
  payment_redsys/models/redsys.py
  payment_redsys/readme/CONFIGURE.rst
  payment_redsys/readme/CONTRIBUTORS.rst
  payment_redsys/readme/DESCRIPTION.rst
  payment_redsys/readme/INSTALL.rst
  payment_redsys/static/description/icon.png
  payment_redsys/static/description/index.html
  payment_redsys/static/src/img/redsys_icon.png
  payment_redsys/tests/__init__.py
  payment_redsys/tests/test_redsys.py
  payment_redsys/views/payment_acquirer.xml
  payment_redsys/views/payment_redsys_templates.xml
  payment_redsys/views/redsys.xml
  requirements.txt
  setup/payment_redsys/odoo/addons/payment_redsys
  setup/payment_redsys/setup.py
Labels: bot is merging ⏳

#1356 [12.0][MIG] l10n_es_aeat_vat_prorrate: Migration to 12.0
  l10n_es_aeat_vat_prorrate/README.rst
  l10n_es_aeat_vat_prorrate/__init__.py
  l10n_es_aeat_vat_prorrate/__manifest__.py
  l10n_es_aeat_vat_prorrate/data/aeat_export_mod303_data.xml
  l10n_es_aeat_vat_prorrate/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_vat_prorrate/i18n/bg.po
  l10n_es_aeat_vat_prorrate/i18n/ca.po
  l10n_es_aeat_vat_prorrate/i18n/ca_ES.po
  l10n_es_aeat_vat_prorrate/i18n/cs.po
  l10n_es_aeat_vat_prorrate/i18n/de.po
  l10n_es_aeat_vat_prorrate/i18n/es.po
  l10n_es_aeat_vat_prorrate/i18n/es_CO.po
  l10n_es_aeat_vat_prorrate/i18n/es_CR.po
  l10n_es_aeat_vat_prorrate/i18n/es_ES.po
  l10n_es_aeat_vat_prorrate/i18n/eu.po
  l10n_es_aeat_vat_prorrate/i18n/fr.po
  l10n_es_aeat_vat_prorrate/i18n/gl.po
  l10n_es_aeat_vat_prorrate/i18n/hr.po
  l10n_es_aeat_vat_prorrate/i18n/l10n_es_aeat_vat_prorrate.pot
  l10n_es_aeat_vat_prorrate/i18n/nl.po
  l10n_es_aeat_vat_prorrate/i18n/pl.po
  l10n_es_aeat_vat_prorrate/i18n/pt.po
  l10n_es_aeat_vat_prorrate/i18n/pt_BR.po
  l10n_es_aeat_vat_prorrate/i18n/ru.po
  l10n_es_aeat_vat_prorrate/i18n/sl.po
  l10n_es_aeat_vat_prorrate/i18n/sv.po
  l10n_es_aeat_vat_prorrate/i18n/tr.po
  l10n_es_aeat_vat_prorrate/i18n/vi.po
  l10n_es_aeat_vat_prorrate/models/__init__.py
  l10n_es_aeat_vat_prorrate/models/mod303.py
  l10n_es_aeat_vat_prorrate/readme/CONFIGURATION.rst
  l10n_es_aeat_vat_prorrate/readme/CONTRIBUTORS.rst
  l10n_es_aeat_vat_prorrate/readme/DESCRIPTION.rst
  l10n_es_aeat_vat_prorrate/readme/ROADMAP.rst
  l10n_es_aeat_vat_prorrate/readme/USAGE.rst
  l10n_es_aeat_vat_prorrate/static/description/icon.png
  l10n_es_aeat_vat_prorrate/static/description/icon_source.svg
  l10n_es_aeat_vat_prorrate/static/description/index.html
  l10n_es_aeat_vat_prorrate/tests/__init__.py
  l10n_es_aeat_vat_prorrate/tests/test_l10n_es_vat_prorrate.py
  l10n_es_aeat_vat_prorrate/views/mod303_view.xml
  l10n_es_aeat_vat_prorrate/wizard/__init__.py
  l10n_es_aeat_vat_prorrate/wizard/l10n_es_aeat_compute_vat_prorrate.py
  l10n_es_aeat_vat_prorrate/wizard/l10n_es_aeat_compute_vat_prorrate_view.xml
Labels: bot is merging ⏳

#1357 [12.0][MIG] l10n_es_aeat_vat_prorrate_asset: Migration to 12.0
  l10n_es_aeat_vat_prorrate_asset/README.rst
  l10n_es_aeat_vat_prorrate_asset/__init__.py
  l10n_es_aeat_vat_prorrate_asset/__manifest__.py
  l10n_es_aeat_vat_prorrate_asset/i18n/ca.po
  l10n_es_aeat_vat_prorrate_asset/i18n/cs.po
  l10n_es_aeat_vat_prorrate_asset/i18n/es.po
  l10n_es_aeat_vat_prorrate_asset/i18n/es_CO.po
  l10n_es_aeat_vat_prorrate_asset/i18n/es_CR.po
  l10n_es_aeat_vat_prorrate_asset/i18n/fr.po
  l10n_es_aeat_vat_prorrate_asset/i18n/gl.po
  l10n_es_aeat_vat_prorrate_asset/i18n/hr.po
  l10n_es_aeat_vat_prorrate_asset/i18n/l10n_es_aeat_vat_prorrate_asset.pot
  l10n_es_aeat_vat_prorrate_asset/i18n/nl.po
  l10n_es_aeat_vat_prorrate_asset/i18n/pl.po
  l10n_es_aeat_vat_prorrate_asset/i18n/pt.po
  l10n_es_aeat_vat_prorrate_asset/i18n/pt_BR.po
  l10n_es_aeat_vat_prorrate_asset/i18n/ru.po
  l10n_es_aeat_vat_prorrate_asset/i18n/sl.po
  l10n_es_aeat_vat_prorrate_asset/i18n/sv.po
  l10n_es_aeat_vat_prorrate_asset/i18n/tr.po
  l10n_es_aeat_vat_prorrate_asset/i18n/vi.po
  l10n_es_aeat_vat_prorrate_asset/models/__init__.py
  l10n_es_aeat_vat_prorrate_asset/models/account_asset.py
  l10n_es_aeat_vat_prorrate_asset/models/account_invoice.py
  l10n_es_aeat_vat_prorrate_asset/models/account_move.py
  l10n_es_aeat_vat_prorrate_asset/models/mod303.py
  l10n_es_aeat_vat_prorrate_asset/readme/CONTRIBUTORS.rst
  l10n_es_aeat_vat_prorrate_asset/readme/DESCRIPTION.rst
  l10n_es_aeat_vat_prorrate_asset/readme/ROADMAP.rst
  l10n_es_aeat_vat_prorrate_asset/readme/USAGE.rst
  l10n_es_aeat_vat_prorrate_asset/static/description/icon.png
  l10n_es_aeat_vat_prorrate_asset/static/description/icon_source.svg
  l10n_es_aeat_vat_prorrate_asset/static/description/index.html
  l10n_es_aeat_vat_prorrate_asset/tests/__init__.py
  l10n_es_aeat_vat_prorrate_asset/tests/test_l10n_es_aeat_vat_prorrate_asset.py
  l10n_es_aeat_vat_prorrate_asset/views/account_asset_views.xml
  l10n_es_aeat_vat_prorrate_asset/views/account_invoice_views.xml
Labels: bot is merging ⏳

#1307 [13.0][MIG] l10n_es_aeat_mod111
  l10n_es_aeat_mod111/README.rst
  l10n_es_aeat_mod111/__init__.py
  l10n_es_aeat_mod111/__manifest__.py
  l10n_es_aeat_mod111/data/aeat_export_mod111_data.xml
  l10n_es_aeat_mod111/data/tax_code_map_mod111_data.xml
  l10n_es_aeat_mod111/docs/dr111e16v17.xls
  l10n_es_aeat_mod111/i18n/bg.po
  l10n_es_aeat_mod111/i18n/ca.po
  l10n_es_aeat_mod111/i18n/cs.po
  l10n_es_aeat_mod111/i18n/de.po
  l10n_es_aeat_mod111/i18n/es.po
  l10n_es_aeat_mod111/i18n/es_CO.po
  l10n_es_aeat_mod111/i18n/es_CR.po
  l10n_es_aeat_mod111/i18n/es_ES.po
  l10n_es_aeat_mod111/i18n/eu.po
  l10n_es_aeat_mod111/i18n/fr.po
  l10n_es_aeat_mod111/i18n/gl.po
  l10n_es_aeat_mod111/i18n/hr.po
  l10n_es_aeat_mod111/i18n/l10n_es_aeat_mod111.pot
  l10n_es_aeat_mod111/i18n/nl.po
  l10n_es_aeat_mod111/i18n/pl.po
  l10n_es_aeat_mod111/i18n/pt.po
  l10n_es_aeat_mod111/i18n/pt_BR.po
  l10n_es_aeat_mod111/i18n/ru.po
  l10n_es_aeat_mod111/i18n/sl.po
  l10n_es_aeat_mod111/i18n/sv.po
  l10n_es_aeat_mod111/i18n/tr.po
  l10n_es_aeat_mod111/i18n/vi.po
  l10n_es_aeat_mod111/migrations/13.0.1.0.0/pre-migration.py
  l10n_es_aeat_mod111/models/__init__.py
  l10n_es_aeat_mod111/models/mod111.py
  l10n_es_aeat_mod111/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod111/readme/DESCRIPTION.rst
  l10n_es_aeat_mod111/readme/ROADMAP.rst
  l10n_es_aeat_mod111/readme/USAGE.rst
  l10n_es_aeat_mod111/security/ir.model.access.csv
  l10n_es_aeat_mod111/security/l10n_es_aeat_mod111_security.xml
  l10n_es_aeat_mod111/static/description/icon.png
  l10n_es_aeat_mod111/static/description/icon_source.svg
  l10n_es_aeat_mod111/static/description/index.html
  l10n_es_aeat_mod111/tests/__init__.py
  l10n_es_aeat_mod111/tests/test_l10n_es_aeat_mod111.py
  l10n_es_aeat_mod111/views/mod111_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1383 [12.0][l10n_es_vat_book] Avoid considering tax fee as base, for taxes with subsequent taxes base checked
  l10n_es_vat_book/models/l10n_es_vat_book.py
Labels: approved, bot is merging ⏳

#1387 [12.0][IMP] efact: no eliminar ficheros hasta el final. No requerir datos no obligatorios
  l10n_es_facturae_efact/models/account_invoice_integration_log.py
Labels: approved, bot is merging ⏳
