Repository OCA/l10n-spain, pull requests merged in 2021-03, with the labels that each got.

#1620 [14.0][FIX] l10n_es_aeat_sii_oca: Fix tests + move_type reference
  l10n_es_aeat_sii_oca/wizards/account_move_reversal.py
Labels: bot is merging ⏳

#1625 [12.0][FIX] delivery_seur: Remove lines in test to check delivery_price_method addon is installed
  delivery_seur/readme/CONTRIBUTORS.rst
  delivery_seur/tests/test_delivery_seur.py
Labels: approved, bot is merging ⏳

#1578 [14.0][MIG] l10n_es_pos: Migration to 14.0
  l10n_es_pos/README.rst
  l10n_es_pos/__init__.py
  l10n_es_pos/__manifest__.py
  l10n_es_pos/hooks.py
  l10n_es_pos/i18n/ca.po
  l10n_es_pos/i18n/ca_ES.po
  l10n_es_pos/i18n/es.po
  l10n_es_pos/i18n/l10n_es_pos.pot
  l10n_es_pos/models/__init__.py
  l10n_es_pos/models/ir_sequence.py
  l10n_es_pos/models/pos_config.py
  l10n_es_pos/models/pos_order.py
  l10n_es_pos/readme/CONFIGURE.rst
  l10n_es_pos/readme/CONTRIBUTORS.rst
  l10n_es_pos/readme/DESCRIPTION.rst
  l10n_es_pos/readme/INSTALL.rst
  l10n_es_pos/readme/ROADMAP.rst
  l10n_es_pos/static/description/icon.png
  l10n_es_pos/static/description/index.html
  l10n_es_pos/static/src/js/PaymentScreen.js
  l10n_es_pos/static/src/js/models.js
  l10n_es_pos/static/src/xml/pos.xml
  l10n_es_pos/views/pos_templates.xml
  l10n_es_pos/views/pos_views.xml
  setup/l10n_es_pos/odoo/addons/l10n_es_pos
  setup/l10n_es_pos/setup.py
Labels: bot is merging ⏳

#1589 [12.0][FIX] l10n_es_aeat_sii_oca: Exclude base amount from ImporteTotal
  l10n_es_aeat_sii/data/aeat_sii_map_data.xml
  l10n_es_aeat_sii/models/account_invoice.py
Labels: bot is merging ⏳

#1561 [IMP] l10n_es_aeat_mod349: add missing tax
  l10n_es_aeat_mod349/data/aeat_349_map_data.xml
Labels: bot is merging ⏳

#1531 [ADD] account_promissory_note_santander: new romissory note for Santa…
  account_promissory_note_santander/README.rst
  account_promissory_note_santander/__init__.py
  account_promissory_note_santander/__manifest__.py
  account_promissory_note_santander/data/account_promissory_note_report_data.xml
  account_promissory_note_santander/i18n/account_promissory_note_santander.pot
  account_promissory_note_santander/i18n/es.po
  account_promissory_note_santander/readme/CONFIGURE.rst
  account_promissory_note_santander/readme/CONTRIBUTORS.rst
  account_promissory_note_santander/readme/DESCRIPTION.rst
  account_promissory_note_santander/readme/USAGE.rst
  account_promissory_note_santander/report/__init__.py
  account_promissory_note_santander/report/account_promissory_note_writing_report.xml
  account_promissory_note_santander/report/check_print.py
  account_promissory_note_santander/static/description/icon.png
  account_promissory_note_santander/static/description/index.html
  account_promissory_note_santander/views/report_promissory_note.xml
Labels: bot is merging ⏳

#1630 [8.0][IMP] l10n_es_aeat_mod303: New 2021 BOE format
  l10n_es_aeat_mod303/__openerp__.py
  l10n_es_aeat_mod303/data/aeat_export_mod303_2018_data.xml
  l10n_es_aeat_mod303/data/aeat_export_mod303_2021_data.xml
  l10n_es_aeat_mod303/docs/DR303e21v100.xlsx
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: bot is merging ⏳

#1631 [13.0][FIX] account_promissory_note_caixabank: Add _description to report model
  account_promissory_note_caixabank/report/check_print.py
Labels: approved, bot is merging ⏳

#1610 [14.0][MIG] l10n_es_intrastat_report: Migration to 14.0
  l10n_es_intrastat_report/README.rst
  l10n_es_intrastat_report/__init__.py
  l10n_es_intrastat_report/__manifest__.py
  l10n_es_intrastat_report/data/NC_20.xls
  l10n_es_intrastat_report/data/account_fiscal_position_template.xml
  l10n_es_intrastat_report/data/intrastat_transaction.xml
  l10n_es_intrastat_report/hooks.py
  l10n_es_intrastat_report/i18n/es.po
  l10n_es_intrastat_report/i18n/l10n_es_intrastat_report.pot
  l10n_es_intrastat_report/models/__init__.py
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
  l10n_es_intrastat_report/models/stock_location.py
  l10n_es_intrastat_report/readme/CONFIGURE.rst
  l10n_es_intrastat_report/readme/CONTRIBUTORS.rst
  l10n_es_intrastat_report/readme/DESCRIPTION.rst
  l10n_es_intrastat_report/readme/INSTALL.rst
  l10n_es_intrastat_report/readme/ROADMAP.rst
  l10n_es_intrastat_report/readme/USAGE.rst
  l10n_es_intrastat_report/security/ir.model.access.csv
  l10n_es_intrastat_report/security/l10n_es_intrastat_report_security.xml
  l10n_es_intrastat_report/static/description/icon.png
  l10n_es_intrastat_report/static/description/index.html
  l10n_es_intrastat_report/tests/__init__.py
  l10n_es_intrastat_report/tests/test_l10n_es_intrastat_report.py
  l10n_es_intrastat_report/views/l10n_es_intrastat_product.xml
  l10n_es_intrastat_report/wizards/__init__.py
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.py
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.xml
  oca_dependencies.txt
  setup/l10n_es_intrastat_report/odoo/addons/l10n_es_intrastat_report
  setup/l10n_es_intrastat_report/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1634 [13.0][FIX] l10n_es_aeat_sii_oca: Prevent duplicate label in some fields
  l10n_es_aeat_sii_oca/models/res_company.py
Labels: bot is merging ⏳

#1633 [13.0][FIX] l10n_es_intrastat_report: Add _description to models
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.py
Labels: bot is merging ⏳

#1635 [FIX] l10n_es_facturae: Fix components names using the new logic
  l10n_es_facturae/components/edi_output_l10n_es_facturae.py
Labels: bot is merging ⏳

#1621 [13.0][MIG] delivery_gls_asm: Migration to 13.0
  delivery_gls_asm/README.rst
  delivery_gls_asm/__init__.py
  delivery_gls_asm/__manifest__.py
  delivery_gls_asm/api/gls_asm_api.wsdl
  delivery_gls_asm/data/delivery_asm_data.xml
  delivery_gls_asm/i18n/delivery_gls_asm.pot
  delivery_gls_asm/i18n/es.po
  delivery_gls_asm/models/__init__.py
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/models/gls_asm_request.py
  delivery_gls_asm/models/stock_picking.py
  delivery_gls_asm/readme/CONFIGURE.rst
  delivery_gls_asm/readme/CONTRIBUTORS.rst
  delivery_gls_asm/readme/DESCRIPTION.rst
  delivery_gls_asm/readme/INSTALL.rst
  delivery_gls_asm/readme/ROADMAP.rst
  delivery_gls_asm/readme/USAGE.rst
  delivery_gls_asm/static/description/icon.png
  delivery_gls_asm/static/description/icon.svg
  delivery_gls_asm/static/description/index.html
  delivery_gls_asm/tests/__init__.py
  delivery_gls_asm/tests/test_delivery_gls_asm.py
  delivery_gls_asm/views/delivery_asm_view.xml
  delivery_gls_asm/views/gls_asm_manifest_template.xml
  delivery_gls_asm/views/stock_picking_views.xml
  delivery_gls_asm/wizard/__init__.py
  delivery_gls_asm/wizard/gls_asm_manifest_wizard.py
  delivery_gls_asm/wizard/gls_asm_manifest_wizard_views.xml
  oca_dependencies.txt
  requirements.txt
  setup/delivery_gls_asm/odoo/addons/delivery_gls_asm
  setup/delivery_gls_asm/setup.py
Labels: approved, bot is merging ⏳

#1570 [8.0] l10n_es_aeat_sii 2021
  l10n_es_aeat_sii/README.rst
  l10n_es_aeat_sii/data/aeat_sii_map_data.xml
  l10n_es_aeat_sii/models/account_invoice.py
  l10n_es_aeat_sii/tests/test_l10n_es_aeat_sii.py
Labels: bot is merging ⏳

#1638 [12.0][FIX] l10n_es_partner: Change Abanca BIC
  l10n_es_partner/gen_src/bics.xls
Labels: bot is merging ⏳

#1639 [13.0][FIX] l10n_es_partner: Change Abanca BIC
  l10n_es_partner/gen_src/bics.xls
Labels: bot is merging ⏳

#1640 [14.0][FIX] l10n_es_partner: Change Abanca BIC
  l10n_es_partner/gen_src/bics.xls
Labels: bot is merging ⏳

#1645 [FIX] facturae: Change of function mame on `edi`
  l10n_es_facturae/components/account_move_l10n_es_facturae_listener.py
Labels: approved, bot is merging ⏳

#1590 [MIG] l10n_es_facturae_face: Migration to 13.0
  l10n_es_facturae_face/README.rst
  l10n_es_facturae_face/__init__.py
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/components/__init__.py
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_face_listener.py
  l10n_es_facturae_face/components/edi_input_process_l10n_es_facturae_l10n_es_facturae_face_update.py
  l10n_es_facturae_face/components/edi_send_l10n_es_facturae_face.py
  l10n_es_facturae_face/components/edi_send_l10n_es_facturae_face_cancel.py
  l10n_es_facturae_face/components/edi_webservice_receive_face_l10n_es_facturae_face_update.py
  l10n_es_facturae_face/components/webservice_face.py
  l10n_es_facturae_face/data/face_data.xml
  l10n_es_facturae_face/i18n/es.po
  l10n_es_facturae_face/i18n/l10n_es_facturae_face.pot
  l10n_es_facturae_face/migrations/13.0.1.0.1/post-migration.py
  l10n_es_facturae_face/models/__init__.py
  l10n_es_facturae_face/models/account_move.py
  l10n_es_facturae_face/models/config.py
  l10n_es_facturae_face/models/edi_exchange_record.py
  l10n_es_facturae_face/models/res_company.py
  l10n_es_facturae_face/models/res_partner.py
  l10n_es_facturae_face/models/webservice_backend.py
  l10n_es_facturae_face/models/wsse_signature.py
  l10n_es_facturae_face/readme/CONFIGURE.rst
  l10n_es_facturae_face/readme/DESCRIPTION.rst
  l10n_es_facturae_face/readme/INSTALL.rst
  l10n_es_facturae_face/readme/USAGE.rst
  l10n_es_facturae_face/static/description/icon.png
  l10n_es_facturae_face/static/description/index.html
  l10n_es_facturae_face/tests/__init__.py
  l10n_es_facturae_face/tests/test_facturae_face.py
  l10n_es_facturae_face/views/account_move.xml
  l10n_es_facturae_face/views/res_company_view.xml
  l10n_es_facturae_face/views/res_config_views.xml
  l10n_es_facturae_face/wizards/__init__.py
  l10n_es_facturae_face/wizards/edi_l10n_es_facturae_face_cancel.py
  l10n_es_facturae_face/wizards/edi_l10n_es_facturae_face_cancel.xml
Labels: bot is merging ⏳

#1647 [FIX] l10n_es_aeat_mod303: Write fees to compensate together
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/models/mod303.py
Labels: bot is merging ⏳

#1648 [13.0][FIX] l10n_es_aeat_sii_oca: Hook on post low level method
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#1652 [13.0][FIX]l10n_es_aeat: added ._origin for search accounts and taxes templates
  l10n_es_aeat/models/l10n_es_aeat_report_tax_mapping.py
Labels: approved, bot is merging ⏳

#1574 [MIG] l10n_es_aeat_vat_prorrate: Migration to 13.0
  l10n_es_aeat_vat_prorrate/README.rst
  l10n_es_aeat_vat_prorrate/__init__.py
  l10n_es_aeat_vat_prorrate/__manifest__.py
  l10n_es_aeat_vat_prorrate/data/aeat_export_mod303_data.xml
  l10n_es_aeat_vat_prorrate/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_vat_prorrate/i18n/bg.po
  l10n_es_aeat_vat_prorrate/i18n/ca.po
  l10n_es_aeat_vat_prorrate/i18n/ca_ES.po
  l10n_es_aeat_vat_prorrate/i18n/cs.po
  l10n_es_aeat_vat_prorrate/i18n/de.po
  l10n_es_aeat_vat_prorrate/i18n/es.po
  l10n_es_aeat_vat_prorrate/i18n/es_CO.po
  l10n_es_aeat_vat_prorrate/i18n/es_CR.po
  l10n_es_aeat_vat_prorrate/i18n/es_ES.po
  l10n_es_aeat_vat_prorrate/i18n/eu.po
  l10n_es_aeat_vat_prorrate/i18n/fr.po
  l10n_es_aeat_vat_prorrate/i18n/gl.po
  l10n_es_aeat_vat_prorrate/i18n/hr.po
  l10n_es_aeat_vat_prorrate/i18n/l10n_es_aeat_vat_prorrate.pot
  l10n_es_aeat_vat_prorrate/i18n/nl.po
  l10n_es_aeat_vat_prorrate/i18n/pl.po
  l10n_es_aeat_vat_prorrate/i18n/pt.po
  l10n_es_aeat_vat_prorrate/i18n/pt_BR.po
  l10n_es_aeat_vat_prorrate/i18n/ru.po
  l10n_es_aeat_vat_prorrate/i18n/sl.po
  l10n_es_aeat_vat_prorrate/i18n/sv.po
  l10n_es_aeat_vat_prorrate/i18n/tr.po
  l10n_es_aeat_vat_prorrate/i18n/vi.po
  l10n_es_aeat_vat_prorrate/models/__init__.py
  l10n_es_aeat_vat_prorrate/models/mod303.py
  l10n_es_aeat_vat_prorrate/readme/CONFIGURATION.rst
  l10n_es_aeat_vat_prorrate/readme/CONTRIBUTORS.rst
  l10n_es_aeat_vat_prorrate/readme/DESCRIPTION.rst
  l10n_es_aeat_vat_prorrate/readme/ROADMAP.rst
  l10n_es_aeat_vat_prorrate/readme/USAGE.rst
  l10n_es_aeat_vat_prorrate/static/description/icon.png
  l10n_es_aeat_vat_prorrate/static/description/icon_source.svg
  l10n_es_aeat_vat_prorrate/static/description/index.html
  l10n_es_aeat_vat_prorrate/tests/__init__.py
  l10n_es_aeat_vat_prorrate/tests/test_l10n_es_vat_prorrate.py
  l10n_es_aeat_vat_prorrate/views/mod303_view.xml
  l10n_es_aeat_vat_prorrate/wizard/__init__.py
  l10n_es_aeat_vat_prorrate/wizard/l10n_es_aeat_compute_vat_prorrate.py
  l10n_es_aeat_vat_prorrate/wizard/l10n_es_aeat_compute_vat_prorrate_view.xml
  setup/l10n_es_aeat_vat_prorrate/odoo/addons/l10n_es_aeat_vat_prorrate
  setup/l10n_es_aeat_vat_prorrate/setup.py
Labels: approved, bot is merging ⏳
