Repository OCA/l10n-spain, pull requests merged in 2021-11, with the labels that each got.

#1887 [14.0][ADD] l10n_es_aeat_sii_oca: add Araba/Alava and Bizkaia/Vizvaya
  l10n_es_aeat_sii_oca/data/aeat_sii_tax_agency_data.xml
Labels: approved, bot is merging ⏳

#1885 [13.0][IMP] delivery_dhl_parcel: Producto DHL (B2B/B2C/R2C)
  delivery_dhl_parcel/i18n/delivery_dhl_parcel.pot
  delivery_dhl_parcel/i18n/es.po
  delivery_dhl_parcel/models/delivery_carrier.py
  delivery_dhl_parcel/views/delivery_carrier_view.xml
Labels: approved, bot is merging ⏳

#1890 [14.0][FIX] l10n_es_aeat_sii_oca: Error en la obtención del certificado en multicompañía
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: approved, bot is merging ⏳

#1803 [12.0][IMP] l10n_es_ticketbai: operation description value can be configured
  l10n_es_ticketbai/README.rst
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/res_company_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1891 [14.0][FIX] l10n_es_aeat_sii_oca: Send invoice's commercial_partner_id
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: approved, bot is merging ⏳

#1900 [13.0][IMP] delivery_dhl_parcel: Remove dhl_parcel_last_request + dhl_parcel_last_response fields.
  delivery_dhl_parcel/README.rst
  delivery_dhl_parcel/models/delivery_carrier.py
  delivery_dhl_parcel/models/dhl_parcel_request.py
  delivery_dhl_parcel/readme/USAGE.rst
  delivery_dhl_parcel/static/description/index.html
  delivery_dhl_parcel/views/delivery_carrier_view.xml
Labels: approved, bot is merging ⏳

#1875 [12.0][IMP] l10n_es_aeat_partner_check: Add unknown state
  l10n_es_aeat_partner_check/models/res_partner.py
Labels: approved, bot is merging ⏳

#1898 [13.0][IMP] delivery_gls_asm: Remove gls_last_request + gls_last_response fields.
  delivery_gls_asm/README.rst
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/readme/USAGE.rst
  delivery_gls_asm/static/description/index.html
  delivery_gls_asm/views/delivery_asm_view.xml
Labels: approved, bot is merging ⏳

#1897 [13.0][REF] delivery_seur: Code refactor.
  delivery_seur/__manifest__.py
  delivery_seur/models/__init__.py
  delivery_seur/models/delivery_carrier.py
  delivery_seur/models/seur_request.py
  delivery_seur/models/stock_picking.py
  delivery_seur/tests/test_delivery_seur.py
  delivery_seur/views/stock_picking_views.xml
Labels: bot is merging ⏳

#1902 [14.0][IMP] delivery_dhl_parcel: Remove dhl_parcel_last_request + dhl_parcel_last_response fields.
  delivery_dhl_parcel/README.rst
  delivery_dhl_parcel/models/delivery_carrier.py
  delivery_dhl_parcel/models/dhl_parcel_request.py
  delivery_dhl_parcel/readme/USAGE.rst
  delivery_dhl_parcel/static/description/index.html
  delivery_dhl_parcel/views/delivery_carrier_view.xml
Labels: approved, bot is merging ⏳

#1899 [10.0][FIX] l10n_es_vat_book: Error on special line
  l10n_es_vat_book/models/l10n_es_vat_book.py
Labels: bot is merging ⏳

#1858 [12.0][IMP] l10n_es_ticketbai: journals are able not to send invoices to tax agency
  l10n_es_ticketbai/README.rst
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/models/account_journal.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/account_invoice_views.xml
  l10n_es_ticketbai/views/account_journal_views.xml
Labels: approved, bot is merging ⏳

#1913 [14.0][FIX] delivery_dhl_parcel: Fix log_xml
  delivery_dhl_parcel/models/dhl_parcel_request.py
Labels: approved, bot is merging ⏳

#1914 [13.0][FIX] delivery_dhl_parcel: Fix log_xml
  delivery_dhl_parcel/models/dhl_parcel_request.py
Labels: approved, bot is merging ⏳

#1896 [13.0][IMP] l10n_es_ticketbai: operation description value can be configured
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/res_company_views.xml
Labels: approved, ready to merge, bot is merging ⏳
