Repository OCA/l10n-spain, pull requests merged in 2021-07, with the labels that each got.

#1746 [12.0][IMP]payment_redsys: Remove send_quotation
  payment_redsys/models/redsys.py
  payment_redsys/tests/test_redsys.py
  payment_redsys/views/payment_acquirer.xml
Labels: approved, bot is merging ⏳

#1753 [13.0][FIX] l10n_es_ticketbai_api: create partners from test file
  l10n_es_ticketbai_api/tests/common.py
Labels: bot is merging ⏳

#1750 [14.0][FIX] l10n_es_pos: Incorrect label texts and translations
  l10n_es_pos/i18n/ca.po
  l10n_es_pos/i18n/l10n_es_pos.pot
  l10n_es_pos/static/src/xml/pos.xml
Labels: approved, bot is merging ⏳

#1759 [13.0][IMP]payment_redsys: Remove send_quotation
  payment_redsys/models/redsys.py
  payment_redsys/tests/test_redsys.py
  payment_redsys/views/payment_acquirer.xml
Labels: bot is merging ⏳

#1754 [13.0][MIG] l10n_es_aeat_mod216: Migration to 13.0
  l10n_es_aeat_mod216/README.rst
  l10n_es_aeat_mod216/__init__.py
  l10n_es_aeat_mod216/__manifest__.py
  l10n_es_aeat_mod216/data/aeat_export_mod216_data.xml
  l10n_es_aeat_mod216/data/tax_code_map_mod216_data.xml
  l10n_es_aeat_mod216/docs/DR-216e16_v1.06.pdf
  l10n_es_aeat_mod216/i18n/bg.po
  l10n_es_aeat_mod216/i18n/ca.po
  l10n_es_aeat_mod216/i18n/cs.po
  l10n_es_aeat_mod216/i18n/de.po
  l10n_es_aeat_mod216/i18n/es.po
  l10n_es_aeat_mod216/i18n/es_CO.po
  l10n_es_aeat_mod216/i18n/es_CR.po
  l10n_es_aeat_mod216/i18n/es_ES.po
  l10n_es_aeat_mod216/i18n/eu.po
  l10n_es_aeat_mod216/i18n/fr.po
  l10n_es_aeat_mod216/i18n/gl.po
  l10n_es_aeat_mod216/i18n/hr.po
  l10n_es_aeat_mod216/i18n/l10n_es_aeat_mod216.pot
  l10n_es_aeat_mod216/i18n/nl.po
  l10n_es_aeat_mod216/i18n/pl.po
  l10n_es_aeat_mod216/i18n/pt.po
  l10n_es_aeat_mod216/i18n/pt_BR.po
  l10n_es_aeat_mod216/i18n/ru.po
  l10n_es_aeat_mod216/i18n/sl.po
  l10n_es_aeat_mod216/i18n/sv.po
  l10n_es_aeat_mod216/i18n/tr.po
  l10n_es_aeat_mod216/i18n/vi.po
  l10n_es_aeat_mod216/models/__init__.py
  l10n_es_aeat_mod216/models/mod216.py
  l10n_es_aeat_mod216/readme/CONFIGURE.rst
  l10n_es_aeat_mod216/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod216/readme/DESCRIPTION.rst
  l10n_es_aeat_mod216/readme/USAGE.rst
  l10n_es_aeat_mod216/security/ir.model.access.csv
  l10n_es_aeat_mod216/security/ir_rule.xml
  l10n_es_aeat_mod216/static/description/icon.png
  l10n_es_aeat_mod216/static/description/icon_source.svg
  l10n_es_aeat_mod216/static/description/index.html
  l10n_es_aeat_mod216/tests/__init__.py
  l10n_es_aeat_mod216/tests/test_l10n_es_aeat_mod216.py
  l10n_es_aeat_mod216/views/mod216_view.xml
  setup/l10n_es_aeat_mod216/odoo/addons/l10n_es_aeat_mod216
  setup/l10n_es_aeat_mod216/setup.py
Labels: approved, bot is merging ⏳

#1764 [13.0][FIX]l10n_es_vat_book: error in the partner origin when the account.move is not an invoice
  l10n_es_vat_book/models/l10n_es_vat_book.py
Labels: approved, bot is merging ⏳

#1765 [14.0][FIX]l10n_es_vat_book: error in the partner origin when the account.move is not an invoice
  l10n_es_vat_book/models/l10n_es_vat_book.py
Labels: approved, bot is merging ⏳

#1771 [13.0][FIX] delivery_seur: avoid error due to non existent field
  delivery_seur/models/delivery_carrier.py
Labels: bot is merging ⏳

#1736 [13.0][MIG] l10n_es_ticketbai
  l10n_es_ticketbai/README.rst
  l10n_es_ticketbai/__init__.py
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/data/account_fiscal_position_template.xml
  l10n_es_ticketbai/data/tax_map_data.xml
  l10n_es_ticketbai/data/vat_exemption_key_data.xml
  l10n_es_ticketbai/data/vat_regime_key_data.xml
  l10n_es_ticketbai/hooks.py
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/models/__init__.py
  l10n_es_ticketbai/models/account_fiscal_position.py
  l10n_es_ticketbai/models/account_journal.py
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/account_tax.py
  l10n_es_ticketbai/models/aeat_certificate.py
  l10n_es_ticketbai/models/chart_template.py
  l10n_es_ticketbai/models/ir_sequence.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/models/ticketbai_invoice.py
  l10n_es_ticketbai/models/ticketbai_tax_map.py
  l10n_es_ticketbai/models/ticketbai_vat_exemption_key.py
  l10n_es_ticketbai/models/ticketbai_vat_regime_key.py
  l10n_es_ticketbai/security/ir.model.access.csv
  l10n_es_ticketbai/static/description/icon.png
  l10n_es_ticketbai/tests/__init__.py
  l10n_es_ticketbai/tests/certs/ciudadano_act.p12
  l10n_es_ticketbai/tests/certs/ciudadano_act_p12_password.txt
  l10n_es_ticketbai/tests/certs/private_up_8mgwq.pem
  l10n_es_ticketbai/tests/certs/public_362gar7l.crt
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_cancellation.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/account_fiscal_position_template_views.xml
  l10n_es_ticketbai/views/account_fiscal_position_views.xml
  l10n_es_ticketbai/views/account_journal_views.xml
  l10n_es_ticketbai/views/account_move_views.xml
  l10n_es_ticketbai/views/ir_sequence_views.xml
  l10n_es_ticketbai/views/l10n_es_ticketbai_views.xml
  l10n_es_ticketbai/views/report_invoice.xml
  l10n_es_ticketbai/views/res_company_views.xml
  l10n_es_ticketbai/views/res_partner_views.xml
  l10n_es_ticketbai/views/tax_map_views.xml
  l10n_es_ticketbai/views/ticketbai_invoice_views.xml
  l10n_es_ticketbai/views/vat_exemption_key_views.xml
  l10n_es_ticketbai/views/vat_regime_key_views.xml
  l10n_es_ticketbai/wizard/__init__.py
  l10n_es_ticketbai/wizard/account_move_reversal.py
  l10n_es_ticketbai/wizard/aeat_certificate_password.py
  l10n_es_ticketbai/wizard/ticketbai_info.py
  l10n_es_ticketbai/wizard/ticketbai_info_views.xml
  setup/l10n_es_ticketbai/odoo/addons/l10n_es_ticketbai
  setup/l10n_es_ticketbai/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1733 [ADD] l10n_es_aeat_sii_oss: Compatibilización del SII con OSS
  l10n_es_aeat_sii_oss/__init__.py
  l10n_es_aeat_sii_oss/__manifest__.py
  l10n_es_aeat_sii_oss/data/aeat_sii_mapping_registration_keys_data.xml
  l10n_es_aeat_sii_oss/models/__init__.py
  l10n_es_aeat_sii_oss/models/account_invoice.py
  l10n_es_aeat_sii_oss/readme/CONFIGURE.rst
  l10n_es_aeat_sii_oss/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_oss/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_oss/readme/INSTALL.rst
  l10n_es_aeat_sii_oss/static/description/icon.png
  l10n_es_aeat_sii_oss/static/description/icon_source.svg
  l10n_es_aeat_sii_oss/tests/__init__.py
  l10n_es_aeat_sii_oss/tests/test_l10n_es_aeat_sii.py
  oca_dependencies.txt
Labels: approved, bot is merging ⏳

#1774 [8.0] [MIG] l10n es aeat sii eu oss
  l10n_es_aeat_sii_oss/__init__.py
  l10n_es_aeat_sii_oss/__openerp__.py
  l10n_es_aeat_sii_oss/data/aeat_sii_mapping_registration_keys_data.xml
  l10n_es_aeat_sii_oss/models/__init__.py
  l10n_es_aeat_sii_oss/models/account_invoice.py
  l10n_es_aeat_sii_oss/readme/CONFIGURE.rst
  l10n_es_aeat_sii_oss/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_oss/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_oss/readme/INSTALL.rst
  l10n_es_aeat_sii_oss/static/description/icon.png
  l10n_es_aeat_sii_oss/static/description/icon_source.svg
  l10n_es_aeat_sii_oss/tests/__init__.py
  l10n_es_aeat_sii_oss/tests/test_l10n_es_aeat_sii.py
  oca_dependencies.txt
Labels: approved, bot is merging ⏳

#1758 [MIG] [12.0] l10n_es_aeat_sii_eu_oss
  l10n_es_aeat_sii_oss/__init__.py
  l10n_es_aeat_sii_oss/__manifest__.py
  l10n_es_aeat_sii_oss/data/aeat_sii_mapping_registration_keys_data.xml
  l10n_es_aeat_sii_oss/models/__init__.py
  l10n_es_aeat_sii_oss/models/account_invoice.py
  l10n_es_aeat_sii_oss/readme/CONFIGURE.rst
  l10n_es_aeat_sii_oss/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_oss/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_oss/readme/INSTALL.rst
  l10n_es_aeat_sii_oss/static/description/icon.png
  l10n_es_aeat_sii_oss/static/description/icon_source.svg
  l10n_es_aeat_sii_oss/tests/__init__.py
  l10n_es_aeat_sii_oss/tests/test_l10n_es_aeat_sii.py
  oca_dependencies.txt
Labels: approved, bot is merging ⏳

#1778 [IMP] l10n_es_facturae: Fix on tax calculation
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/views/report_facturae.xml
Labels: approved, bot is merging ⏳

#1724 [IMP] l10n_es_facturae: Round taxable Base and Tax Amount
  l10n_es_facturae/models/account_invoice.py
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#1781 [14.0][UPD] l10n_es_aeat_sii_oca: updated ROADMAP
  l10n_es_aeat_sii_oca/readme/ROADMAP.rst
Labels: bot is merging ⏳

#1782 [14.0][IMP]payment_redsys: Remove send_quotation
  payment_redsys/models/redsys.py
  payment_redsys/tests/test_redsys.py
  payment_redsys/views/payment_acquirer.xml
Labels: bot is merging ⏳

#1783 [IMP]payment_redsys: module_id in data file
  payment_redsys/data/payment_redsys.xml
Labels: bot is merging ⏳

#1785 [14.0][IMP]payment_redsys: module_id in data file
  payment_redsys/data/payment_redsys.xml
Labels: bot is merging ⏳

#1784 [13.0][IMP]payment_redsys: module_id in data file
  payment_redsys/data/payment_redsys.xml
Labels: bot is merging ⏳

#1779 [13.0][IMP] l10n_es_aeat_sii_oca: Allow send invoices with LC type (create get_sii_invoice_type() function to set 'TipoFactura'
  l10n_es_aeat_sii_oca/i18n/es.po
  l10n_es_aeat_sii_oca/i18n/l10n_es_aeat_sii_oca.pot
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/views/account_move_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#1786 [14.0][IMP] l10n_es_aeat_sii_oca: Allow send invoices with LC type (create get_sii_invoice_type() function to set 'TipoFactura'
  l10n_es_aeat_sii_oca/i18n/es.po
  l10n_es_aeat_sii_oca/i18n/l10n_es_aeat_sii_oca.pot
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/views/account_move_views.xml
Labels: approved, bot is merging ⏳

#1787 [FIX] l10n_es_aeat_mod190: expected singleton bug
  l10n_es_aeat_mod190/models/account_move.py
Labels: approved, bot is merging ⏳

#1742 [ADD] l10n_es_ticketbai: send invoices to the Basque Country tax agen…
  l10n_es_ticketbai/README.rst
  l10n_es_ticketbai/__init__.py
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/data/account_fiscal_position_template.xml
  l10n_es_ticketbai/data/tax_map_data.xml
  l10n_es_ticketbai/data/vat_exemption_key_data.xml
  l10n_es_ticketbai/data/vat_regime_key_data.xml
  l10n_es_ticketbai/hooks.py
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/models/__init__.py
  l10n_es_ticketbai/models/account_fiscal_position.py
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/models/account_invoice_tax.py
  l10n_es_ticketbai/models/account_tax.py
  l10n_es_ticketbai/models/aeat_certificate.py
  l10n_es_ticketbai/models/chart_template.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/models/ticketbai_invoice.py
  l10n_es_ticketbai/models/ticketbai_tax_map.py
  l10n_es_ticketbai/models/ticketbai_vat_exemption_key.py
  l10n_es_ticketbai/models/ticketbai_vat_regime_key.py
  l10n_es_ticketbai/security/ir.model.access.csv
  l10n_es_ticketbai/static/description/icon.png
  l10n_es_ticketbai/tests/__init__.py
  l10n_es_ticketbai/tests/certs/ciudadano_act_p12_password.txt
  l10n_es_ticketbai/tests/certs/ciudadano_eidas_act.p12
  l10n_es_ticketbai/tests/certs/private_n4c_8fov.pem
  l10n_es_ticketbai/tests/certs/public_076ebb7u.crt
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_cancellation.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/account_fiscal_position_template_views.xml
  l10n_es_ticketbai/views/account_fiscal_position_views.xml
  l10n_es_ticketbai/views/account_invoice_views.xml
  l10n_es_ticketbai/views/l10n_es_ticketbai_views.xml
  l10n_es_ticketbai/views/report_invoice.xml
  l10n_es_ticketbai/views/res_company_views.xml
  l10n_es_ticketbai/views/res_partner_views.xml
  l10n_es_ticketbai/views/tax_map_views.xml
  l10n_es_ticketbai/views/ticketbai_invoice_views.xml
  l10n_es_ticketbai/views/vat_exemption_key_views.xml
  l10n_es_ticketbai/views/vat_regime_key_views.xml
  l10n_es_ticketbai/wizard/__init__.py
  l10n_es_ticketbai/wizard/account_invoice_refund.py
  l10n_es_ticketbai/wizard/aeat_certificate_password.py
  l10n_es_ticketbai/wizard/ticketbai_info.py
  l10n_es_ticketbai/wizard/ticketbai_info_views.xml
Labels: approved, bot is merging ⏳

#1788 [12.0][FIX] l10n_es_aeat_partner_check: Only set if not submitted
  l10n_es_aeat_partner_check/models/res_partner.py
Labels: bot is merging ⏳

#1773 [12.0][FIX]l10n_es_facturae: check partner lastname empty.
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳
