Repository OCA/l10n-spain, pull requests merged in 2021-08, with the labels that each got.

#1641 [14.0][MIG] l10n_es_aeat_mod349: migration to 14.0
  l10n_es_aeat_mod349/README.rst
  l10n_es_aeat_mod349/__init__.py
  l10n_es_aeat_mod349/__manifest__.py
  l10n_es_aeat_mod349/data/aeat_349_map_data.xml
  l10n_es_aeat_mod349/data/aeat_export_mod349_data.xml
  l10n_es_aeat_mod349/data/aeat_export_mod349_partner_data.xml
  l10n_es_aeat_mod349/data/aeat_export_mod349_partner_refund_data.xml
  l10n_es_aeat_mod349/docs/BOE-A-2010-5098.pdf
  l10n_es_aeat_mod349/docs/NREG-349-2016.docx
  l10n_es_aeat_mod349/i18n/es.po
  l10n_es_aeat_mod349/i18n/l10n_es_aeat_mod349.pot
  l10n_es_aeat_mod349/models/__init__.py
  l10n_es_aeat_mod349/models/account_move.py
  l10n_es_aeat_mod349/models/account_tax.py
  l10n_es_aeat_mod349/models/account_tax_template.py
  l10n_es_aeat_mod349/models/aeat_349_map_line.py
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod349/readme/DESCRIPTION.rst
  l10n_es_aeat_mod349/readme/ROADMAP.rst
  l10n_es_aeat_mod349/readme/USAGE.rst
  l10n_es_aeat_mod349/report/aeat_mod349.xml
  l10n_es_aeat_mod349/report/common_templates.xml
  l10n_es_aeat_mod349/report/report_views.xml
  l10n_es_aeat_mod349/security/ir.model.access.csv
  l10n_es_aeat_mod349/security/mod_349_security.xml
  l10n_es_aeat_mod349/static/description/icon.png
  l10n_es_aeat_mod349/static/description/icon_source.svg
  l10n_es_aeat_mod349/static/description/index.html
  l10n_es_aeat_mod349/tests/__init__.py
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
  l10n_es_aeat_mod349/views/account_move_view.xml
  l10n_es_aeat_mod349/views/account_tax_view.xml
  l10n_es_aeat_mod349/views/aeat_349_map_view.xml
  l10n_es_aeat_mod349/views/mod349_view.xml
  setup/l10n_es_aeat_mod349/odoo/addons/l10n_es_aeat_mod349
  setup/l10n_es_aeat_mod349/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1797 [13.0][IMP]l10n_es_vat_book: refactorización para mejorar herencias
  l10n_es_vat_book/models/aeat_vat_book_map_line.py
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#1577 [MIG] l10n_es_aeat_vat_prorrate_asset: Migration to 13.0
  l10n_es_aeat_vat_prorrate_asset/README.rst
  l10n_es_aeat_vat_prorrate_asset/__init__.py
  l10n_es_aeat_vat_prorrate_asset/__manifest__.py
  l10n_es_aeat_vat_prorrate_asset/i18n/ca.po
  l10n_es_aeat_vat_prorrate_asset/i18n/cs.po
  l10n_es_aeat_vat_prorrate_asset/i18n/es.po
  l10n_es_aeat_vat_prorrate_asset/i18n/es_CO.po
  l10n_es_aeat_vat_prorrate_asset/i18n/es_CR.po
  l10n_es_aeat_vat_prorrate_asset/i18n/fr.po
  l10n_es_aeat_vat_prorrate_asset/i18n/gl.po
  l10n_es_aeat_vat_prorrate_asset/i18n/hr.po
  l10n_es_aeat_vat_prorrate_asset/i18n/l10n_es_aeat_vat_prorrate_asset.pot
  l10n_es_aeat_vat_prorrate_asset/i18n/nl.po
  l10n_es_aeat_vat_prorrate_asset/i18n/pl.po
  l10n_es_aeat_vat_prorrate_asset/i18n/pt.po
  l10n_es_aeat_vat_prorrate_asset/i18n/pt_BR.po
  l10n_es_aeat_vat_prorrate_asset/i18n/ru.po
  l10n_es_aeat_vat_prorrate_asset/i18n/sl.po
  l10n_es_aeat_vat_prorrate_asset/i18n/sv.po
  l10n_es_aeat_vat_prorrate_asset/i18n/tr.po
  l10n_es_aeat_vat_prorrate_asset/i18n/vi.po
  l10n_es_aeat_vat_prorrate_asset/models/__init__.py
  l10n_es_aeat_vat_prorrate_asset/models/account_asset.py
  l10n_es_aeat_vat_prorrate_asset/models/account_move.py
  l10n_es_aeat_vat_prorrate_asset/models/mod303.py
  l10n_es_aeat_vat_prorrate_asset/readme/CONTRIBUTORS.rst
  l10n_es_aeat_vat_prorrate_asset/readme/DESCRIPTION.rst
  l10n_es_aeat_vat_prorrate_asset/readme/ROADMAP.rst
  l10n_es_aeat_vat_prorrate_asset/readme/USAGE.rst
  l10n_es_aeat_vat_prorrate_asset/static/description/icon.png
  l10n_es_aeat_vat_prorrate_asset/static/description/icon_source.svg
  l10n_es_aeat_vat_prorrate_asset/static/description/index.html
  l10n_es_aeat_vat_prorrate_asset/tests/__init__.py
  l10n_es_aeat_vat_prorrate_asset/tests/test_l10n_es_aeat_vat_prorrate_asset.py
  l10n_es_aeat_vat_prorrate_asset/views/account_asset_views.xml
  l10n_es_aeat_vat_prorrate_asset/views/account_move_views.xml
  setup/l10n_es_aeat_vat_prorrate_asset/odoo/addons/l10n_es_aeat_vat_prorrate_asset
  setup/l10n_es_aeat_vat_prorrate_asset/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1802 [IMP] delivery_seur: missing product codes and fix id_mercancia bug
  delivery_seur/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#1806 [12.0][FIX] l10n_es_aeat_mod303: quitar impuestos a la casilla 61, añdir impuestos a las casillas 120 y 122, marca_sepa solo tiene valor si es devolución
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/models/mod303.py
Labels: bot is merging ⏳

#1804 [13.0][IMP] l10n_es_aeat_mod303: New 2021/07 format
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat/views/aeat_export_configuration_view.xml
  l10n_es_aeat/wizard/compare_boe_file.py
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2021-07/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2021-07/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/aeat_export_mod303_2021_data.xml
  l10n_es_aeat_mod303/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_mod303/docs/DR303e21v200.xlsx
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: bot is merging ⏳

#1801 [14.0][MIG] l10n_es_ticketbai
  l10n_es_ticketbai/README.rst
  l10n_es_ticketbai/__init__.py
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/data/account_fiscal_position_template.xml
  l10n_es_ticketbai/data/tax_map_data.xml
  l10n_es_ticketbai/data/vat_exemption_key_data.xml
  l10n_es_ticketbai/data/vat_regime_key_data.xml
  l10n_es_ticketbai/hooks.py
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/models/__init__.py
  l10n_es_ticketbai/models/account_fiscal_position.py
  l10n_es_ticketbai/models/account_journal.py
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/account_resequence.py
  l10n_es_ticketbai/models/account_tax.py
  l10n_es_ticketbai/models/aeat_certificate.py
  l10n_es_ticketbai/models/chart_template.py
  l10n_es_ticketbai/models/ir_sequence.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/models/ticketbai_invoice.py
  l10n_es_ticketbai/models/ticketbai_tax_map.py
  l10n_es_ticketbai/models/ticketbai_vat_exemption_key.py
  l10n_es_ticketbai/models/ticketbai_vat_regime_key.py
  l10n_es_ticketbai/security/ir.model.access.csv
  l10n_es_ticketbai/static/description/icon.png
  l10n_es_ticketbai/tests/__init__.py
  l10n_es_ticketbai/tests/certs/ciudadano_act.p12
  l10n_es_ticketbai/tests/certs/ciudadano_act_p12_password.txt
  l10n_es_ticketbai/tests/certs/private_up_8mgwq.pem
  l10n_es_ticketbai/tests/certs/public_362gar7l.crt
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_cancellation.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/account_fiscal_position_template_views.xml
  l10n_es_ticketbai/views/account_fiscal_position_views.xml
  l10n_es_ticketbai/views/account_journal_views.xml
  l10n_es_ticketbai/views/account_move_views.xml
  l10n_es_ticketbai/views/ir_sequence_views.xml
  l10n_es_ticketbai/views/l10n_es_ticketbai_views.xml
  l10n_es_ticketbai/views/report_invoice.xml
  l10n_es_ticketbai/views/res_company_views.xml
  l10n_es_ticketbai/views/res_partner_views.xml
  l10n_es_ticketbai/views/tax_map_views.xml
  l10n_es_ticketbai/views/ticketbai_invoice_views.xml
  l10n_es_ticketbai/views/vat_exemption_key_views.xml
  l10n_es_ticketbai/views/vat_regime_key_views.xml
  l10n_es_ticketbai/wizard/__init__.py
  l10n_es_ticketbai/wizard/account_move_reversal.py
  l10n_es_ticketbai/wizard/aeat_certificate_password.py
  l10n_es_ticketbai/wizard/ticketbai_info.py
  l10n_es_ticketbai/wizard/ticketbai_info_views.xml
  setup/l10n_es_ticketbai/odoo/addons/l10n_es_ticketbai
  setup/l10n_es_ticketbai/setup.py
Labels: approved, ready to merge, bot is merging ⏳
