Repository OCA/l10n-spain, pull requests merged in 2021-09, with the labels that each got.

#1780 [13.0][IMP] l10n_es_aeat_sii_oca: Add SII third-party
  l10n_es_aeat_sii_oca/i18n/es.po
  l10n_es_aeat_sii_oca/i18n/l10n_es_aeat_sii_oca.pot
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/static/description/index.html
  l10n_es_aeat_sii_oca/views/account_move_views.xml
Labels: bot is merging ⏳

#1819 [14.0][IMP] l10n_es_aeat_sii_oca: Add SII third-party
  l10n_es_aeat_sii_oca/i18n/es.po
  l10n_es_aeat_sii_oca/i18n/l10n_es_aeat_sii_oca.pot
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/views/account_move_views.xml
Labels: approved, bot is merging ⏳

#1807 [12.0][IMP] l10n_es_aeat_mod349: Don't mangle VAT number
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/views/mod349_view.xml
Labels: bot is merging ⏳

#1752 [13.0][ADD] ecoembes: Add some data related to ecoembes.com
  ecoembes/README.rst
  ecoembes/__init__.py
  ecoembes/__manifest__.py
  ecoembes/data/ecoembes.market.type.csv
  ecoembes/data/ecoembes.material.csv
  ecoembes/data/ecoembes.packaging.csv
  ecoembes/data/ecoembes.sector.csv
  ecoembes/data/ecoembes.submaterial.csv
  ecoembes/i18n/ecoembes.pot
  ecoembes/i18n/es.po
  ecoembes/models/__init__.py
  ecoembes/models/abstract_ecoembes_mixin.py
  ecoembes/models/ecoembes_market_type.py
  ecoembes/models/ecoembes_material.py
  ecoembes/models/ecoembes_packaging.py
  ecoembes/models/ecoembes_sector.py
  ecoembes/models/ecoembes_submaterial.py
  ecoembes/models/product_composition.py
  ecoembes/models/product_product.py
  ecoembes/models/res_company.py
  ecoembes/readme/CONFIGURE.rst
  ecoembes/readme/CONTRIBUTORS.rst
  ecoembes/readme/DESCRIPTION.rst
  ecoembes/readme/USAGE.rst
  ecoembes/report/__init__.py
  ecoembes/report/account_move_line_ecoembes_report.py
  ecoembes/report/external_layout.xml
  ecoembes/security/ir.model.access.csv
  ecoembes/static/description/icon.png
  ecoembes/static/description/index.html
  ecoembes/tests/__init__.py
  ecoembes/tests/common.py
  ecoembes/tests/test_ecoembes_misc.py
  ecoembes/tests/test_ecoembes_wizard.py
  ecoembes/views/ecoembes_market_type_view.xml
  ecoembes/views/ecoembes_material_view.xml
  ecoembes/views/ecoembes_packaging_view.xml
  ecoembes/views/ecoembes_sector_view.xml
  ecoembes/views/ecoembes_submaterial_view.xml
  ecoembes/views/product_composition_view.xml
  ecoembes/views/product_product_view.xml
  ecoembes/views/res_company_view.xml
  ecoembes/wizard/__init__.py
  ecoembes/wizard/ecoembes_sig_report_wizard.py
  ecoembes/wizard/ecoembes_sig_report_wizard_view.xml
  setup/ecoembes/odoo/addons/ecoembes
  setup/ecoembes/setup.py
Labels: approved, bot is merging ⏳

#1772 [IMP] l10n_es_aeat: button_box
  l10n_es_aeat/views/aeat_report_view.xml
Labels: bot is merging ⏳

#1810 [11.0][FIX/I18N] l10n_es_ticketbai: fix invoice with VAT not subject to.
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/data/account_fiscal_position_template.xml
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/migrations/11.0.0.2.0/post-migration.py
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/models/account_invoice_tax.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
Labels: approved, ready to merge, bot is merging ⏳

#1798 [13.0][ADD]l10n_es_vat_book_oss: Libro de IVA con impuestos OSS
  l10n_es_vat_book_oss/__init__.py
  l10n_es_vat_book_oss/__manifest__.py
  l10n_es_vat_book_oss/models/__init__.py
  l10n_es_vat_book_oss/models/aeat_vat_book_map_lines.py
  l10n_es_vat_book_oss/models/l10n_es_vat_book.py
  l10n_es_vat_book_oss/readme/CONFIGURE.rst
  l10n_es_vat_book_oss/readme/CONTRIBUTORS.rst
  l10n_es_vat_book_oss/readme/DESCRIPTION.rst
  l10n_es_vat_book_oss/readme/INSTALL.rst
  l10n_es_vat_book_oss/readme/ROADMAP.rst
  l10n_es_vat_book_oss/readme/USAGE.rst
  l10n_es_vat_book_oss/static/description/icon.png
  oca_dependencies.txt
  setup/l10n_es_vat_book_oss/odoo/addons/l10n_es_vat_book_oss
  setup/l10n_es_vat_book_oss/setup.py
Labels: approved, bot is merging ⏳

#1816 [12.0][FIX] Correct production URLs and removed label repeating warning
  l10n_es_ticketbai_api/data/tax_agency_data.xml
  l10n_es_ticketbai_api/i18n/es.po
  l10n_es_ticketbai_api/models/res_company.py
  l10n_es_ticketbai_api/models/ticketbai_tax_agency.py
Labels: bot is merging ⏳

#1824 [12.0][FIX] l10n_es_ticketbai: fix invoice with VAT not subject to
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/data/account_fiscal_position_template.xml
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/migrations/12.0.1.0.2/post-migration.py
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/models/account_invoice_tax.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
Labels: bot is merging ⏳

#1827 [11.0][IMP]l10n_es_vat_book, refactorizacion para mejorar herencias
  l10n_es_vat_book/models/aeat_vat_book_map_line.py
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#1814 [13.0][FIX] l10n_es_ticketbai: tbai_vat_exemption_key in invoice line taxes
  l10n_es_ticketbai/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1830 [13.0][FIX] Correct production URL for Gipuzkoa
  l10n_es_ticketbai_api/data/tax_agency_data.xml
  l10n_es_ticketbai_api/i18n/es.po
Labels: bot is merging ⏳

#1831 [13.0][FIX] l10n_es_ticketbai: fix invoice with VAT not subject to
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/data/account_fiscal_position_template.xml
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/migrations/13.0.1.0.2/post-migration.py
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/account_tax.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
Labels: bot is merging ⏳

#1833 [14.0][FIX] Correct production URL for Gipuzkoa
  l10n_es_ticketbai_api/data/tax_agency_data.xml
  l10n_es_ticketbai_api/i18n/es.po
Labels: bot is merging ⏳

#1834 [14.0][FIX] l10n_es_ticketbai: fix invoice with VAT not subject to
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/data/account_fiscal_position_template.xml
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/migrations/14.0.1.0.1/post-migration.py
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/account_tax.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
Labels: bot is merging ⏳

#1832 [14.0][Forward-port][FIX] l10n_es_ticketbai: tbai_vat_exemption_key in invoice line taxes
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#1835 [14.0][FIX]l10n_es_aeat_sii_oca: Fix field name on default type function.
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#1775 [12.0][UPD] payment_redsys: add 'Bizum' option to 'redsys_pay_method' field.
  payment_redsys/data/payment_redsys.xml
  payment_redsys/models/redsys.py
  payment_redsys/readme/CONFIGURE.rst
  payment_redsys/readme/DESCRIPTION.rst
  payment_redsys/static/img/bizum.png
Labels: approved, bot is merging ⏳

#1840 [13.0][FIX] l10n_es_aeat_sii_oca: Only assign sii_registration_key if is set in fiscal position
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#1825 [10.0] l10n_es_aeat_mod303 version 2021 07
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/aeat_export_mod303_2021_data.xml
  l10n_es_aeat_mod303/data/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_mod303/docs/DR303e21v200.xlsx
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: bot is merging ⏳

#1842 [14.0][FIX] l10n_es_aeat_sii_oca: Only assign sii_registration_key if is set in fiscal position
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#1844 [14.0][MIG] l10n_es_irnr: Migration to 14.0
  l10n_es_irnr/README.rst
  l10n_es_irnr/__init__.py
  l10n_es_irnr/__manifest__.py
  l10n_es_irnr/data/account_data.xml
  l10n_es_irnr/data/fiscal_position_taxes_irnr.xml
  l10n_es_irnr/data/fiscal_positions_irnr.xml
  l10n_es_irnr/data/taxes_irnr.xml
  l10n_es_irnr/i18n/l10n_es_irnr.pot
  l10n_es_irnr/readme/CONFIGURE.rst
  l10n_es_irnr/readme/CONTRIBUTORS.rst
  l10n_es_irnr/readme/DESCRIPTION.rst
  l10n_es_irnr/readme/ROADMAP.rst
  l10n_es_irnr/readme/USAGE.rst
  l10n_es_irnr/static/description/icon.png
  l10n_es_irnr/static/description/index.html
  setup/l10n_es_irnr/odoo/addons/l10n_es_irnr
  setup/l10n_es_irnr/setup.py
Labels: bot is merging ⏳

#1843 [13.0][FIX] l10n_es_dua_sii: Remove service taxes
  l10n_es_dua_sii/__manifest__.py
  l10n_es_dua_sii/data/tax_code_map_dua_sii_data.xml
  l10n_es_dua_sii/migrations/13.0.1.1.0/post-migration.py
  l10n_es_dua_sii/tests/json/sii_in_invoice_p_iva21_ibc_dict.json
  l10n_es_dua_sii/tests/test_dua_sii.py
Labels: approved, bot is merging ⏳

#1755 [13.0][MIG] l10n_es_aeat_mod296: Migration to 13.0
  l10n_es_aeat_mod296/README.rst
  l10n_es_aeat_mod296/__init__.py
  l10n_es_aeat_mod296/__manifest__.py
  l10n_es_aeat_mod296/data/aeat_export_mod296_data.xml
  l10n_es_aeat_mod296/data/aeat_export_mod296_line_data.xml
  l10n_es_aeat_mod296/data/tax_code_map_mod296_data.xml
  l10n_es_aeat_mod296/docs/DR296_2017.pdf
  l10n_es_aeat_mod296/docs/instrucciones_296.pdf
  l10n_es_aeat_mod296/docs/register_design_296_2008.pdf
  l10n_es_aeat_mod296/i18n/es.po
  l10n_es_aeat_mod296/i18n/l10n_es_aeat_mod296.pot
  l10n_es_aeat_mod296/models/__init__.py
  l10n_es_aeat_mod296/models/mod296.py
  l10n_es_aeat_mod296/readme/CONFIGURE.rst
  l10n_es_aeat_mod296/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod296/readme/DESCRIPTION.rst
  l10n_es_aeat_mod296/readme/USAGE.rst
  l10n_es_aeat_mod296/security/ir.model.access.csv
  l10n_es_aeat_mod296/security/ir_rule.xml
  l10n_es_aeat_mod296/static/description/icon.png
  l10n_es_aeat_mod296/static/description/icon_source.svg
  l10n_es_aeat_mod296/static/description/index.html
  l10n_es_aeat_mod296/tests/__init__.py
  l10n_es_aeat_mod296/tests/test_l10n_es_aeat_mod296.py
  l10n_es_aeat_mod296/views/mod296_views.xml
  setup/l10n_es_aeat_mod296/odoo/addons/l10n_es_aeat_mod296
  setup/l10n_es_aeat_mod296/setup.py
Labels: bot is merging ⏳

#1799 11.0 imp l10n es aeat mod303 version 2021 07
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2021-07/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2021-07/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/aeat_export_mod303_2021_data.xml
  l10n_es_aeat_mod303/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_mod303/docs/DR303e21v200.xlsx
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: bot is merging ⏳

#1829 [11.0][MIG]l10n_es_vat_book_oss, backport to 11.0
  l10n_es_vat_book_oss/README.rst
  l10n_es_vat_book_oss/__init__.py
  l10n_es_vat_book_oss/__manifest__.py
  l10n_es_vat_book_oss/i18n/l10n_es_vat_book_oss.pot
  l10n_es_vat_book_oss/models/__init__.py
  l10n_es_vat_book_oss/models/aeat_vat_book_map_lines.py
  l10n_es_vat_book_oss/models/l10n_es_vat_book.py
  l10n_es_vat_book_oss/readme/CONFIGURE.rst
  l10n_es_vat_book_oss/readme/CONTRIBUTORS.rst
  l10n_es_vat_book_oss/readme/DESCRIPTION.rst
  l10n_es_vat_book_oss/readme/INSTALL.rst
  l10n_es_vat_book_oss/readme/ROADMAP.rst
  l10n_es_vat_book_oss/readme/USAGE.rst
  l10n_es_vat_book_oss/static/description/icon.png
  l10n_es_vat_book_oss/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#1800 [11.0][MIG] l10n_es_aeat_mod303_oss: Migration to 11.0
  l10n_es_aeat/models/l10n_es_aeat_report_tax_mapping.py
  l10n_es_aeat_mod303_oss/README.rst
  l10n_es_aeat_mod303_oss/__init__.py
  l10n_es_aeat_mod303_oss/__manifest__.py
  l10n_es_aeat_mod303_oss/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_mod303_oss/models/__init__.py
  l10n_es_aeat_mod303_oss/models/mod303.py
  l10n_es_aeat_mod303_oss/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303_oss/readme/DESCRIPTION.rst
  l10n_es_aeat_mod303_oss/static/description/icon.png
  l10n_es_aeat_mod303_oss/static/description/icon_source.svg
  l10n_es_aeat_mod303_oss/static/description/index.html
Labels: bot is merging ⏳
