Repository OCA/l10n-spain, pull requests merged in 2021-06, with the labels that each got.

#1722 [13.0][FIX] l10n_es_aeat_sii_oca: SII Refund Type not required
  l10n_es_aeat_sii_oca/wizards/account_move_reversal.py
Labels: approved, bot is merging ⏳

#1723 [14.0][FIX] l10n_es_aeat_sii_oca: SII Refund Type not required
  l10n_es_aeat_sii_oca/wizards/account_move_reversal.py
Labels: bot is merging ⏳

#1701 [13.0][MIG]l10n_es_aeat_mod190
  l10n_es_aeat_mod190/README.rst
  l10n_es_aeat_mod190/__init__.py
  l10n_es_aeat_mod190/__manifest__.py
  l10n_es_aeat_mod190/data/aeat_export_mod190_data.xml
  l10n_es_aeat_mod190/data/aeat_export_mod190_partner_data.xml
  l10n_es_aeat_mod190/data/perception_key_data.xml
  l10n_es_aeat_mod190/data/perception_subkey_data.xml
  l10n_es_aeat_mod190/data/res_country_state.xml
  l10n_es_aeat_mod190/data/tax_code_map_mod190_data.xml
  l10n_es_aeat_mod190/docs/DR190_2017.pdf
  l10n_es_aeat_mod190/models/__init__.py
  l10n_es_aeat_mod190/models/account_fiscal_position.py
  l10n_es_aeat_mod190/models/account_move.py
  l10n_es_aeat_mod190/models/account_move_line.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_perception.py
  l10n_es_aeat_mod190/models/res_country_state.py
  l10n_es_aeat_mod190/models/res_partner.py
  l10n_es_aeat_mod190/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod190/readme/DESCRIPTION.rst
  l10n_es_aeat_mod190/readme/USAGE.rst
  l10n_es_aeat_mod190/security/ir.model.access.csv
  l10n_es_aeat_mod190/security/l10n_es_aeat_mod190_security.xml
  l10n_es_aeat_mod190/static/description/icon.png
  l10n_es_aeat_mod190/static/description/icon_source.svg
  l10n_es_aeat_mod190/static/description/index.html
  l10n_es_aeat_mod190/tests/__init__.py
  l10n_es_aeat_mod190/tests/test_mod190.py
  l10n_es_aeat_mod190/views/account_fiscal_position.xml
  l10n_es_aeat_mod190/views/account_invoice_view.xml
  l10n_es_aeat_mod190/views/account_move_view.xml
  l10n_es_aeat_mod190/views/mod190_line_view.xml
  l10n_es_aeat_mod190/views/mod190_view.xml
  l10n_es_aeat_mod190/views/partner_view.xml
  setup/l10n_es_aeat_mod190/odoo/addons/l10n_es_aeat_mod190
  setup/l10n_es_aeat_mod190/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1726 [13.0][IMP]l10n_es_aeat_mod190: no cargar información superflua
  l10n_es_aeat_mod190/__manifest__.py
  l10n_es_aeat_mod190/data/res_country_state.xml
  l10n_es_aeat_mod190/models/__init__.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
  l10n_es_aeat_mod190/models/res_country_state.py
Labels: bot is merging ⏳

#1694 [12.0][ADD] l10n_es_aeat_partner_check: Comprobación recargo equiv.
  l10n_es_aeat_partner_check/i18n/es.po
  l10n_es_aeat_partner_check/i18n/l10n_es_aeat_partner_check.pot
  l10n_es_aeat_partner_check/models/res_partner.py
  l10n_es_aeat_partner_check/readme/CONTRIBUTORS.rst
  l10n_es_aeat_partner_check/readme/DESCRIPTION.rst
  l10n_es_aeat_partner_check/views/res_partner_view.xml
Labels: bot is merging ⏳

#1708 [13.0][FIX] payment_redsys: Proper controller visibility
  payment_redsys/controllers/main.py
Labels: approved, bot is merging ⏳

#1728 [14.0][FIX]l10n_es_aeat_mod_347: correccion readme
  l10n_es_aeat_mod347/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#1710 [12.0][MIG] l10n_es_ticketbai
  l10n_es_ticketbai/README.rst
  l10n_es_ticketbai/__init__.py
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/data/account_fiscal_position_template.xml
  l10n_es_ticketbai/data/tax_map_data.xml
  l10n_es_ticketbai/data/vat_exemption_key_data.xml
  l10n_es_ticketbai/data/vat_regime_key_data.xml
  l10n_es_ticketbai/hooks.py
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/models/__init__.py
  l10n_es_ticketbai/models/account_fiscal_position.py
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/models/account_invoice_tax.py
  l10n_es_ticketbai/models/account_journal.py
  l10n_es_ticketbai/models/account_tax.py
  l10n_es_ticketbai/models/aeat_certificate.py
  l10n_es_ticketbai/models/chart_template.py
  l10n_es_ticketbai/models/ir_sequence.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/models/ticketbai_invoice.py
  l10n_es_ticketbai/models/ticketbai_tax_map.py
  l10n_es_ticketbai/models/ticketbai_vat_exemption_key.py
  l10n_es_ticketbai/models/ticketbai_vat_regime_key.py
  l10n_es_ticketbai/security/ir.model.access.csv
  l10n_es_ticketbai/static/description/icon.png
  l10n_es_ticketbai/tests/__init__.py
  l10n_es_ticketbai/tests/certs/ciudadano_act.p12
  l10n_es_ticketbai/tests/certs/ciudadano_act_p12_password.txt
  l10n_es_ticketbai/tests/certs/private_up_8mgwq.pem
  l10n_es_ticketbai/tests/certs/public_362gar7l.crt
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_cancellation.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/account_fiscal_position_template_views.xml
  l10n_es_ticketbai/views/account_fiscal_position_views.xml
  l10n_es_ticketbai/views/account_invoice_views.xml
  l10n_es_ticketbai/views/account_journal_views.xml
  l10n_es_ticketbai/views/ir_sequence_views.xml
  l10n_es_ticketbai/views/l10n_es_ticketbai_views.xml
  l10n_es_ticketbai/views/report_invoice.xml
  l10n_es_ticketbai/views/res_company_views.xml
  l10n_es_ticketbai/views/res_partner_views.xml
  l10n_es_ticketbai/views/tax_map_views.xml
  l10n_es_ticketbai/views/ticketbai_invoice_views.xml
  l10n_es_ticketbai/views/vat_exemption_key_views.xml
  l10n_es_ticketbai/views/vat_regime_key_views.xml
  l10n_es_ticketbai/wizard/__init__.py
  l10n_es_ticketbai/wizard/account_invoice_refund.py
  l10n_es_ticketbai/wizard/aeat_certificate_password.py
  l10n_es_ticketbai/wizard/ticketbai_info.py
  l10n_es_ticketbai/wizard/ticketbai_info_views.xml
  l10n_es_ticketbai_api/i18n/es.po
  l10n_es_ticketbai_api/models/ticketbai_installation.py
  l10n_es_ticketbai_api/models/ticketbai_tax_agency.py
Labels: bot is merging ⏳

#1729 [14.0][FIX] l10n_es_aeat_sii_oca: type in domain to move_type
  l10n_es_aeat_sii_oca/views/account_move_views.xml
Labels: bot is merging ⏳

#1731 [12.0][FIX] l10n_es_ticketbai_api state label and l10n_es_ticketbai installation wizard info
  l10n_es_ticketbai/wizard/ticketbai_info.py
  l10n_es_ticketbai_api/i18n/es.po
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
  l10n_es_ticketbai_api/models/ticketbai_response.py
Labels: bot is merging ⏳

#1734 [12.0][FIX] payment_redsys: Proper controller auth
  payment_redsys/controllers/main.py
Labels: bot is merging ⏳

#1711 [11.0] Evitar error 500 y confirmación de pedido después de pago OK
  payment_redsys/controllers/main.py
Labels: approved, bot is merging ⏳

#1737 [14.0][FIX] l10n_es_mis_report: expresión incorrecta
  l10n_es_mis_report/data/mis_report_pyg_sme_sfl.xml
Labels: bot is merging ⏳

#1745 [FIX] l10n_es_facture: Fixing defintition of the exchange type
  l10n_es_facturae/data/edi.xml
Labels: approved, bot is merging ⏳

#1747 [FIX] l10n_es_ticketbai_api: fix execution warnings
  l10n_es_ticketbai_api/i18n/es.po
  l10n_es_ticketbai_api/models/res_company.py
  l10n_es_ticketbai_api/models/ticketbai_tax_agency.py
Labels: bot is merging ⏳

#1749 [FIX] No actualizar productos dua
  l10n_es_dua/data/products_dua.xml
Labels: approved, bot is merging ⏳

#1735 [12.0][FIX] l10n_es_ticketbai
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/hooks.py
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/models/account_invoice_tax.py
  l10n_es_ticketbai/models/account_tax.py
  l10n_es_ticketbai/models/chart_template.py
  l10n_es_ticketbai/wizard/ticketbai_info.py
Labels: approved, bot is merging ⏳

#1751 [12.0][FIX] l10n_es_ticketbai_api
  l10n_es_ticketbai_api/__manifest__.py
  l10n_es_ticketbai_api/tests/common.py
Labels: bot is merging ⏳
