Repository OCA/l10n-spain, pull requests merged in 2021-12, with the labels that each got.

#1928 [MIG]l10n_es_partner_mercantil: Migration to 15.0
  l10n_es_partner_mercantil/README.rst
  l10n_es_partner_mercantil/__init__.py
  l10n_es_partner_mercantil/__manifest__.py
  l10n_es_partner_mercantil/i18n/bg.po
  l10n_es_partner_mercantil/i18n/ca.po
  l10n_es_partner_mercantil/i18n/en.po
  l10n_es_partner_mercantil/i18n/es.po
  l10n_es_partner_mercantil/i18n/eu.po
  l10n_es_partner_mercantil/i18n/fr.po
  l10n_es_partner_mercantil/i18n/gl.po
  l10n_es_partner_mercantil/i18n/hr.po
  l10n_es_partner_mercantil/i18n/l10n_es_partner_mercantil.pot
  l10n_es_partner_mercantil/i18n/nl.po
  l10n_es_partner_mercantil/i18n/pt.po
  l10n_es_partner_mercantil/i18n/pt_BR.po
  l10n_es_partner_mercantil/i18n/sl.po
  l10n_es_partner_mercantil/models/__init__.py
  l10n_es_partner_mercantil/models/partner_es.py
  l10n_es_partner_mercantil/readme/CONTRIBUTORS.rst
  l10n_es_partner_mercantil/readme/DESCRIPTION.rst
  l10n_es_partner_mercantil/readme/USAGE.rst
  l10n_es_partner_mercantil/static/description/icon.png
  l10n_es_partner_mercantil/static/description/icon.svg
  l10n_es_partner_mercantil/static/description/index.html
  l10n_es_partner_mercantil/views/res_partner_view.xml
  setup/l10n_es_partner_mercantil/odoo/addons/l10n_es_partner_mercantil
  setup/l10n_es_partner_mercantil/setup.py
Labels: approved, bot is merging ⏳

#1929 [15.0][MIG] l10n_es_toponyms: Migration to 15.0
  l10n_es_toponyms/README.rst
  l10n_es_toponyms/__init__.py
  l10n_es_toponyms/__manifest__.py
  l10n_es_toponyms/i18n/bg.po
  l10n_es_toponyms/i18n/ca.po
  l10n_es_toponyms/i18n/cs.po
  l10n_es_toponyms/i18n/de.po
  l10n_es_toponyms/i18n/es.po
  l10n_es_toponyms/i18n/es_CO.po
  l10n_es_toponyms/i18n/es_CR.po
  l10n_es_toponyms/i18n/eu.po
  l10n_es_toponyms/i18n/fr.po
  l10n_es_toponyms/i18n/gl.po
  l10n_es_toponyms/i18n/hr.po
  l10n_es_toponyms/i18n/l10n_es_toponyms.pot
  l10n_es_toponyms/i18n/nl.po
  l10n_es_toponyms/i18n/pl.po
  l10n_es_toponyms/i18n/pt.po
  l10n_es_toponyms/i18n/pt_BR.po
  l10n_es_toponyms/i18n/ru.po
  l10n_es_toponyms/i18n/sl.po
  l10n_es_toponyms/i18n/sv.po
  l10n_es_toponyms/i18n/tr.po
  l10n_es_toponyms/i18n/vi.po
  l10n_es_toponyms/readme/CONTRIBUTORS.rst
  l10n_es_toponyms/readme/DESCRIPTION.rst
  l10n_es_toponyms/readme/INSTALL.rst
  l10n_es_toponyms/readme/USAGE.rst
  l10n_es_toponyms/security/ir.model.access.csv
  l10n_es_toponyms/static/description/icon.png
  l10n_es_toponyms/static/description/icon.svg
  l10n_es_toponyms/static/description/index.html
  l10n_es_toponyms/tests/__init__.py
  l10n_es_toponyms/tests/test_l10n_es_toponyms.py
  l10n_es_toponyms/wizard/__init__.py
  l10n_es_toponyms/wizard/geonames_import.py
  l10n_es_toponyms/wizard/l10n_es_toponyms_wizard.py
  l10n_es_toponyms/wizard/l10n_es_toponyms_wizard.xml
  setup/l10n_es_toponyms/odoo/addons/l10n_es_toponyms
  setup/l10n_es_toponyms/setup.py
Labels: approved, bot is merging ⏳

#1934 [IMP] delivery_gls_asm: warn about reference limit
  delivery_gls_asm/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#1930 [MIG]l10n_es_partner: Migration to 15.0
  l10n_es_partner/README.rst
  l10n_es_partner/__init__.py
  l10n_es_partner/__manifest__.py
  l10n_es_partner/data/l10n_es_partner_data.xml
  l10n_es_partner/gen_src/README.rst
  l10n_es_partner/gen_src/__init__.py
  l10n_es_partner/gen_src/bics.xls
  l10n_es_partner/gen_src/gen_data_banks.py
  l10n_es_partner/i18n/bg.po
  l10n_es_partner/i18n/ca.po
  l10n_es_partner/i18n/cs.po
  l10n_es_partner/i18n/de.po
  l10n_es_partner/i18n/es.po
  l10n_es_partner/i18n/es_CO.po
  l10n_es_partner/i18n/es_CR.po
  l10n_es_partner/i18n/es_ES.po
  l10n_es_partner/i18n/eu.po
  l10n_es_partner/i18n/fr.po
  l10n_es_partner/i18n/gl.po
  l10n_es_partner/i18n/hr.po
  l10n_es_partner/i18n/l10n_es_partner.pot
  l10n_es_partner/i18n/nl.po
  l10n_es_partner/i18n/pl.po
  l10n_es_partner/i18n/pt.po
  l10n_es_partner/i18n/pt_BR.po
  l10n_es_partner/i18n/ru.po
  l10n_es_partner/i18n/sl.po
  l10n_es_partner/i18n/sv.po
  l10n_es_partner/i18n/tr.po
  l10n_es_partner/i18n/vi.po
  l10n_es_partner/models/__init__.py
  l10n_es_partner/models/res_bank.py
  l10n_es_partner/models/res_partner.py
  l10n_es_partner/readme/CONFIGURE.rst
  l10n_es_partner/readme/CONTRIBUTORS.rst
  l10n_es_partner/readme/DESCRIPTION.rst
  l10n_es_partner/readme/INSTALL.rst
  l10n_es_partner/readme/ROADMAP.rst
  l10n_es_partner/security/ir.model.access.csv
  l10n_es_partner/static/description/bank.svg
  l10n_es_partner/static/description/icon.png
  l10n_es_partner/static/description/index.html
  l10n_es_partner/tests/__init__.py
  l10n_es_partner/tests/test_l10n_es_partner.py
  l10n_es_partner/views/res_bank_view.xml
  l10n_es_partner/views/res_partner_view.xml
  l10n_es_partner/wizard/__init__.py
  l10n_es_partner/wizard/data_banks.xml
  l10n_es_partner/wizard/l10n_es_partner_wizard.py
  l10n_es_partner/wizard/l10n_es_partner_wizard.xml
  oca_dependencies.txt
  requirements.txt
  setup/l10n_es_partner/odoo/addons/l10n_es_partner
  setup/l10n_es_partner/setup.py
Labels: approved, bot is merging ⏳

#1935 [13.0][IMP] delivery_gls_asm: warn about reference limit
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/tests/test_delivery_gls_asm.py
Labels: bot is merging ⏳

#1942 [14.0][FIX]l10n_es_aeat_mod347: not_in_mod347 checkbox display in invoice
  l10n_es_aeat_mod347/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#1921 [11.0][IMP] l10n_es_ticketbai: Remove l10n_es_account_invoice_sequence module dependency
  l10n_es_ticketbai/README.rst
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/hooks.py
  l10n_es_ticketbai/models/__init__.py
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/models/ir_sequence.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/ir_sequence_views.xml
Labels: bot is merging ⏳

#1924 11.0 ticketbai batuz enable rest test url
  l10n_es_ticketbai_api_batuz/data/tax_agency_data.xml
  l10n_es_ticketbai_api_batuz/models/lroe_operation_response.py
  l10n_es_ticketbai_api_batuz/tests/certs/EntitateOrdezkaria_RepresentanteDeEntidad.p12
  l10n_es_ticketbai_api_batuz/tests/certs/EntitateOrdezkaria_RepresentanteDeEntidad_pin.txt
  l10n_es_ticketbai_api_batuz/tests/certs/PertsonaFisikoa_PersonaFísica.p12
  l10n_es_ticketbai_api_batuz/tests/certs/PertsonaFisikoa_PersonaFísica_pin.txt
  l10n_es_ticketbai_api_batuz/tests/company-bizkaia-pf-140.json
  l10n_es_ticketbai_api_batuz/tests/company-bizkaia-pj-240.json
  l10n_es_ticketbai_api_batuz/tests/tbai-batuz-soft-developer.json
  l10n_es_ticketbai_api_batuz/tests/tbai-p12-bizkaia-pf-140.json
  l10n_es_ticketbai_api_batuz/tests/tbai-p12-bizkaia-pj-240.json
  l10n_es_ticketbai_api_batuz/tests/test_lroe_operation.py
Labels: approved, ready to merge, bot is merging ⏳

#1917 [FIX] l10n_es_aeat_partner_check: Add missing return values
  l10n_es_aeat_partner_check/README.rst
  l10n_es_aeat_partner_check/models/res_partner.py
  l10n_es_aeat_partner_check/readme/CONTRIBUTORS.rst
Labels: approved, ready to merge, bot is merging ⏳

#1947 [11.0][IMP] Add production URLs for Araba
  l10n_es_ticketbai_api/data/tax_agency_data.xml
  l10n_es_ticketbai_api/tests/test_l10n_es_ticketbai_tax_agency.py
Labels: bot is merging ⏳

#1949 [12.0][IMP] Add production URLs for Araba
  l10n_es_ticketbai_api/data/tax_agency_data.xml
  l10n_es_ticketbai_api/tests/test_l10n_es_ticketbai_tax_agency.py
Labels: bot is merging ⏳

#1951 [12.0][IMP] l10n_es_ticketbai_api: modify rest api response codes
  l10n_es_ticketbai_api/models/ticketbai_response.py
Labels: bot is merging ⏳

#1950 [12.0][IMP] l10n_es_ticketbai_api Move XML schema dir to tests and make usa…
  l10n_es_ticketbai_api/tests/common.py
  l10n_es_ticketbai_api/tests/schemas/XAdES01903v132-201601.xsd
  l10n_es_ticketbai_api/tests/schemas/XAdES01903v141-201601.xsd
  l10n_es_ticketbai_api/tests/schemas/XMLSchema.xsd
  l10n_es_ticketbai_api/tests/schemas/catalog.xml
  l10n_es_ticketbai_api/tests/schemas/v1.0/Anula_ticketBai V1-0.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.0/TicketBAI_Especificaciones.pdf
  l10n_es_ticketbai_api/tests/schemas/v1.0/TicketBAI_Política_firma_1_0.pdf
  l10n_es_ticketbai_api/tests/schemas/v1.0/response.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.0/ticketBai V1-0.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.1/Anula_ticketBai V1-1.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.1/TicketBAI_Especificaciones_v_1_1.pdf
  l10n_es_ticketbai_api/tests/schemas/v1.1/test_Anula_ticketBai V1-1.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.1/test_ticketBai V1-1.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.1/ticketBai V1-1.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.2/Anula_ticketBai V1-2.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.2/TBAI_Descripción_Servicios_Rest Gipuzkoa v_0_2.pdf
  l10n_es_ticketbai_api/tests/schemas/v1.2/TicketBAIResponse.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.2/TicketBAI_Especificaciones funcionales y técnicas_1_2.pdf
  l10n_es_ticketbai_api/tests/schemas/v1.2/test_Anula_ticketBai V1-2.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.2/test_ticketBai V1-2.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.2/ticketBai V1-2.xsd
  l10n_es_ticketbai_api/tests/schemas/xmldsig-core-schema.xsd
Labels: bot is merging ⏳

#1960 [MIG] l10n_es_dua: Migration to 15.0
  l10n_es_dua/README.rst
  l10n_es_dua/__init__.py
  l10n_es_dua/__manifest__.py
  l10n_es_dua/data/fiscal_position_taxes_dua.xml
  l10n_es_dua/data/fiscal_positions_dua.xml
  l10n_es_dua/data/products_dua.xml
  l10n_es_dua/data/tax_group_data.xml
  l10n_es_dua/data/taxes_dua.xml
  l10n_es_dua/i18n/ca.po
  l10n_es_dua/i18n/es.po
  l10n_es_dua/i18n/l10n_es_dua.pot
  l10n_es_dua/readme/CONFIGURE.rst
  l10n_es_dua/readme/CONTRIBUTORS.rst
  l10n_es_dua/readme/DESCRIPTION.rst
  l10n_es_dua/readme/USAGE.rst
  l10n_es_dua/static/description/icon.png
  l10n_es_dua/static/description/index.html
  setup/l10n_es_dua/odoo/addons/l10n_es_dua
  setup/l10n_es_dua/setup.py
Labels: bot is merging ⏳

#1964 [15.0][FIX] l10n_es_aeat: Fix development_status
  l10n_es_aeat/__manifest__.py
Labels: bot is merging ⏳

#1952 [12.0][FIX] l10n_es_ticketbai_api If an invoice substitutes simplified invo…
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
Labels: approved, ready to merge, bot is merging ⏳

#1954 [12.0][FIX] l10n_es_ticketbai_api: Remove access to tbai.certificate for gro…
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
  l10n_es_ticketbai_api/security/ir.model.access.csv
  l10n_es_ticketbai_api/tests/common.py
Labels: bot is merging ⏳

#1962 [FIX] delivery_seur: partner name
  delivery_seur/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#1971 [12.0][IMP] l10n_es_ticketbai simplify document schema validation.
  l10n_es_ticketbai_api/ticketbai/xml_schema.py
Labels: bot is merging ⏳

#1966 [15.0][FIX] l10n_es_dua: Fix development_status
  l10n_es_dua/__manifest__.py
Labels: bot is merging ⏳

#1968 [15.0][FIX] l10n_es_partner_mercantil: Fix development_status
  l10n_es_partner_mercantil/__manifest__.py
Labels: bot is merging ⏳

#1967 [15.0][FIX] l10n_es_toponyms: Fix development_status
  l10n_es_toponyms/__manifest__.py
Labels: bot is merging ⏳

#1959 [MIG] l10n_es_aeat_mod303: Migration to 15.0
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/__init__.py
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2021-07/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2021-07/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/aeat_export_mod303_2018_data.xml
  l10n_es_aeat_mod303/data/aeat_export_mod303_2021_data.xml
  l10n_es_aeat_mod303/data/l10n_es_aeat_mod303_report_activity_code_data.xml
  l10n_es_aeat_mod303/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_mod303/docs/303_register_design_e15v32.xlsx
  l10n_es_aeat_mod303/docs/DR303e15v34.xlsx
  l10n_es_aeat_mod303/docs/DR303e17v20_04.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_00.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_40.xlsx
  l10n_es_aeat_mod303/docs/DR303e21v100.xlsx
  l10n_es_aeat_mod303/docs/DR303e21v200.xlsx
  l10n_es_aeat_mod303/i18n/bg.po
  l10n_es_aeat_mod303/i18n/ca.po
  l10n_es_aeat_mod303/i18n/cs.po
  l10n_es_aeat_mod303/i18n/de.po
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/es_CO.po
  l10n_es_aeat_mod303/i18n/es_CR.po
  l10n_es_aeat_mod303/i18n/eu.po
  l10n_es_aeat_mod303/i18n/fr.po
  l10n_es_aeat_mod303/i18n/gl.po
  l10n_es_aeat_mod303/i18n/hr.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/i18n/nl.po
  l10n_es_aeat_mod303/i18n/pl.po
  l10n_es_aeat_mod303/i18n/pt.po
  l10n_es_aeat_mod303/i18n/pt_BR.po
  l10n_es_aeat_mod303/i18n/sl.po
  l10n_es_aeat_mod303/i18n/sv.po
  l10n_es_aeat_mod303/i18n/tr.po
  l10n_es_aeat_mod303/i18n/vi.po
  l10n_es_aeat_mod303/models/__init__.py
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303/readme/DESCRIPTION.rst
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/security/ir.model.access.csv
  l10n_es_aeat_mod303/security/l10n_es_aeat_mod303_security.xml
  l10n_es_aeat_mod303/static/description/icon.png
  l10n_es_aeat_mod303/static/description/icon_source.svg
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_mod303/tests/__init__.py
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
  l10n_es_aeat_mod303/views/l10n_es_aeat_mod303_report_activity_code_data_views.xml
  l10n_es_aeat_mod303/views/mod303_view.xml
  setup/l10n_es_aeat_mod303/odoo/addons/l10n_es_aeat_mod303
  setup/l10n_es_aeat_mod303/setup.py
Labels: bot is merging ⏳

#1922 [14.0][IMP] l10n_es_ticketbai: operation description value can be configured
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/res_company_views.xml
Labels: bot is merging ⏳

#1944 [MIG] l10n_es_aeat_mod111: Migration to 15.0
  l10n_es_aeat_mod111/README.rst
  l10n_es_aeat_mod111/__init__.py
  l10n_es_aeat_mod111/__manifest__.py
  l10n_es_aeat_mod111/data/aeat_export_mod111_data.xml
  l10n_es_aeat_mod111/data/tax_code_map_mod111_data.xml
  l10n_es_aeat_mod111/docs/dr111e16v17.xls
  l10n_es_aeat_mod111/i18n/bg.po
  l10n_es_aeat_mod111/i18n/ca.po
  l10n_es_aeat_mod111/i18n/cs.po
  l10n_es_aeat_mod111/i18n/de.po
  l10n_es_aeat_mod111/i18n/es.po
  l10n_es_aeat_mod111/i18n/es_CO.po
  l10n_es_aeat_mod111/i18n/es_CR.po
  l10n_es_aeat_mod111/i18n/es_ES.po
  l10n_es_aeat_mod111/i18n/eu.po
  l10n_es_aeat_mod111/i18n/fr.po
  l10n_es_aeat_mod111/i18n/gl.po
  l10n_es_aeat_mod111/i18n/hr.po
  l10n_es_aeat_mod111/i18n/l10n_es_aeat_mod111.pot
  l10n_es_aeat_mod111/i18n/nl.po
  l10n_es_aeat_mod111/i18n/pl.po
  l10n_es_aeat_mod111/i18n/pt.po
  l10n_es_aeat_mod111/i18n/pt_BR.po
  l10n_es_aeat_mod111/i18n/ru.po
  l10n_es_aeat_mod111/i18n/sl.po
  l10n_es_aeat_mod111/i18n/sv.po
  l10n_es_aeat_mod111/i18n/tr.po
  l10n_es_aeat_mod111/i18n/vi.po
  l10n_es_aeat_mod111/models/__init__.py
  l10n_es_aeat_mod111/models/mod111.py
  l10n_es_aeat_mod111/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod111/readme/DESCRIPTION.rst
  l10n_es_aeat_mod111/readme/ROADMAP.rst
  l10n_es_aeat_mod111/readme/USAGE.rst
  l10n_es_aeat_mod111/security/ir.model.access.csv
  l10n_es_aeat_mod111/security/l10n_es_aeat_mod111_security.xml
  l10n_es_aeat_mod111/static/description/icon.png
  l10n_es_aeat_mod111/static/description/icon_source.svg
  l10n_es_aeat_mod111/static/description/index.html
  l10n_es_aeat_mod111/tests/__init__.py
  l10n_es_aeat_mod111/tests/test_l10n_es_aeat_mod111.py
  l10n_es_aeat_mod111/views/mod111_view.xml
  setup/l10n_es_aeat_mod111/odoo/addons/l10n_es_aeat_mod111
  setup/l10n_es_aeat_mod111/setup.py
Labels: bot is merging ⏳

#1973 [15.0][FIX] l10n_es_aeat: Added group group_erp_manager in the Account mana…
  l10n_es_aeat/tests/test_l10n_es_aeat_mod_base.py
Labels: bot is merging ⏳

#1975 Revert "[15.0][FIX] l10n_es_aeat: Added group group_erp_manager in the Account mana…"
  l10n_es_aeat/tests/test_l10n_es_aeat_mod_base.py
Labels: needs review, bot is merging ⏳

#1970 [12.0][IMP] l10n_es_ticketbai: refund invoice without having a tbai.invoice…
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/models/ticketbai_invoice.py
  l10n_es_ticketbai/security/ir.model.access.csv
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/account_invoice_views.xml
Labels: bot is merging ⏳
