Repository OCA/l10n-spain, pull requests merged in 2021-01, with the labels that each got.

#1533 [14.0][MIG] payment_redsys: Migration to 14.0
  payment_redsys/README.rst
  payment_redsys/__init__.py
  payment_redsys/__manifest__.py
  payment_redsys/controllers/__init__.py
  payment_redsys/controllers/main.py
  payment_redsys/data/payment_redsys.xml
  payment_redsys/i18n/bg.po
  payment_redsys/i18n/ca.po
  payment_redsys/i18n/es.po
  payment_redsys/i18n/fr.po
  payment_redsys/i18n/gl.po
  payment_redsys/i18n/hr.po
  payment_redsys/i18n/payment_redsys.pot
  payment_redsys/i18n/pt_BR.po
  payment_redsys/i18n/sl.po
  payment_redsys/models/__init__.py
  payment_redsys/models/redsys.py
  payment_redsys/readme/CONFIGURE.rst
  payment_redsys/readme/CONTRIBUTORS.rst
  payment_redsys/readme/DESCRIPTION.rst
  payment_redsys/readme/INSTALL.rst
  payment_redsys/static/description/icon.png
  payment_redsys/static/description/index.html
  payment_redsys/static/src/img/redsys_icon.png
  payment_redsys/tests/__init__.py
  payment_redsys/tests/test_redsys.py
  payment_redsys/views/payment_acquirer.xml
  payment_redsys/views/payment_redsys_templates.xml
  payment_redsys/views/redsys.xml
  requirements.txt
  setup/payment_redsys/odoo/addons/payment_redsys
  setup/payment_redsys/setup.py
Labels: approved, bot is merging ⏳

#1501 Haciendo campo 06 del Modelo 130 editable
  l10n_es_aeat_mod130/models/mod130.py
  l10n_es_aeat_mod130/views/mod130_view.xml
Labels: approved, bot is merging ⏳

#1546 [12.0][FIX] Sing tax l10n_es_aeat_sii
  l10n_es_aeat_sii/data/aeat_sii_map_data.xml
  l10n_es_aeat_sii/models/account_invoice.py
Labels: bot is merging ⏳

#1364 [12.0][IMP] facturae attach as annex
  l10n_es_facturae/models/account_invoice.py
  l10n_es_facturae/models/account_invoice_integration_method.py
  l10n_es_facturae/models/res_partner.py
  l10n_es_facturae/readme/CONTRIBUTORS.rst
  l10n_es_facturae/tests/common.py
  l10n_es_facturae/views/report_facturae.xml
  l10n_es_facturae/views/res_partner_view.xml
  l10n_es_facturae/wizard/__init__.py
  l10n_es_facturae/wizard/account_invoice_integration_cancel.py
  l10n_es_facturae/wizard/account_invoice_refund.py
  l10n_es_facturae/wizard/create_facturae.py
Labels: approved, bot is merging ⏳

#1494 [13.0][MIG] l10n_es_aeat_mod390: Migration to 13.0
  l10n_es_aeat_mod390/README.rst
  l10n_es_aeat_mod390/__init__.py
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_main_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub01_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub02_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub03_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub04_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub05_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub06_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub07_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub08_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_main_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub01_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub02_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub03_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub04_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub05_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub06_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub07_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub08_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_main_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub01_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub02_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub03_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub04_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub05_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub06_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub07_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub08_data.xml
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/docs/dr390e2017v3.xlsx
  l10n_es_aeat_mod390/docs/dr390e2018.xlsx
  l10n_es_aeat_mod390/docs/dr390e2019v100.xlsx
  l10n_es_aeat_mod390/docs/instr390.pdf
  l10n_es_aeat_mod390/i18n/es.po
  l10n_es_aeat_mod390/i18n/l10n_es_aeat_mod390.pot
  l10n_es_aeat_mod390/migrations/13.0.1.0.0/pre-migration.py
  l10n_es_aeat_mod390/models/__init__.py
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod390/readme/DESCRIPTION.rst
  l10n_es_aeat_mod390/readme/INSTALL.rst
  l10n_es_aeat_mod390/readme/ROADMAP.rst
  l10n_es_aeat_mod390/readme/USAGE.rst
  l10n_es_aeat_mod390/security/ir.model.access.csv
  l10n_es_aeat_mod390/security/l10n_es_aeat_mod390_security.xml
  l10n_es_aeat_mod390/static/description/icon.png
  l10n_es_aeat_mod390/static/description/icon.svg
  l10n_es_aeat_mod390/static/description/index.html
  l10n_es_aeat_mod390/tests/__init__.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
  l10n_es_aeat_mod390/views/mod390_view.xml
  setup/l10n_es_aeat_mod390/odoo/addons/l10n_es_aeat_mod390
  setup/l10n_es_aeat_mod390/setup.py
Labels: approved, bot is merging ⏳

#1551 [14.0][MIG] l10n_es_toponyms: Migration to 14.0
  l10n_es_toponyms/README.rst
  l10n_es_toponyms/__init__.py
  l10n_es_toponyms/__manifest__.py
  l10n_es_toponyms/i18n/bg.po
  l10n_es_toponyms/i18n/ca.po
  l10n_es_toponyms/i18n/cs.po
  l10n_es_toponyms/i18n/de.po
  l10n_es_toponyms/i18n/es.po
  l10n_es_toponyms/i18n/es_CO.po
  l10n_es_toponyms/i18n/es_CR.po
  l10n_es_toponyms/i18n/eu.po
  l10n_es_toponyms/i18n/fr.po
  l10n_es_toponyms/i18n/gl.po
  l10n_es_toponyms/i18n/hr.po
  l10n_es_toponyms/i18n/l10n_es_toponyms.pot
  l10n_es_toponyms/i18n/nl.po
  l10n_es_toponyms/i18n/pl.po
  l10n_es_toponyms/i18n/pt.po
  l10n_es_toponyms/i18n/pt_BR.po
  l10n_es_toponyms/i18n/ru.po
  l10n_es_toponyms/i18n/sl.po
  l10n_es_toponyms/i18n/sv.po
  l10n_es_toponyms/i18n/tr.po
  l10n_es_toponyms/i18n/vi.po
  l10n_es_toponyms/readme/CONTRIBUTORS.rst
  l10n_es_toponyms/readme/DESCRIPTION.rst
  l10n_es_toponyms/readme/INSTALL.rst
  l10n_es_toponyms/readme/USAGE.rst
  l10n_es_toponyms/security/ir.model.access.csv
  l10n_es_toponyms/static/description/icon.png
  l10n_es_toponyms/static/description/icon.svg
  l10n_es_toponyms/static/description/index.html
  l10n_es_toponyms/tests/__init__.py
  l10n_es_toponyms/tests/test_l10n_es_toponyms.py
  l10n_es_toponyms/wizard/__init__.py
  l10n_es_toponyms/wizard/geonames_import.py
  l10n_es_toponyms/wizard/l10n_es_toponyms_wizard.py
  l10n_es_toponyms/wizard/l10n_es_toponyms_wizard.xml
  setup/l10n_es_toponyms/odoo/addons/l10n_es_toponyms
  setup/l10n_es_toponyms/setup.py
Labels: approved, bot is merging ⏳

#1499 [MIG] l10n_es_aeat_mod303: Migration to 14.0
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/__init__.py
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/aeat_export_mod303_2017_data.xml
  l10n_es_aeat_mod303/data/aeat_export_mod303_2018_data.xml
  l10n_es_aeat_mod303/data/aeat_export_mod303_data.xml
  l10n_es_aeat_mod303/data/l10n_es_aeat_mod303_report_activity_code_data.xml
  l10n_es_aeat_mod303/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_mod303/docs/303_register_design_e15v32.xlsx
  l10n_es_aeat_mod303/docs/DR303e15v34.xlsx
  l10n_es_aeat_mod303/docs/DR303e17v20_04.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_00.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_40.xlsx
  l10n_es_aeat_mod303/i18n/bg.po
  l10n_es_aeat_mod303/i18n/ca.po
  l10n_es_aeat_mod303/i18n/cs.po
  l10n_es_aeat_mod303/i18n/de.po
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/es_CO.po
  l10n_es_aeat_mod303/i18n/es_CR.po
  l10n_es_aeat_mod303/i18n/es_ES.po
  l10n_es_aeat_mod303/i18n/eu.po
  l10n_es_aeat_mod303/i18n/fr.po
  l10n_es_aeat_mod303/i18n/gl.po
  l10n_es_aeat_mod303/i18n/hr.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/i18n/nl.po
  l10n_es_aeat_mod303/i18n/pl.po
  l10n_es_aeat_mod303/i18n/pt.po
  l10n_es_aeat_mod303/i18n/pt_BR.po
  l10n_es_aeat_mod303/i18n/sl.po
  l10n_es_aeat_mod303/i18n/sv.po
  l10n_es_aeat_mod303/i18n/tr.po
  l10n_es_aeat_mod303/i18n/vi.po
  l10n_es_aeat_mod303/models/__init__.py
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303/readme/DESCRIPTION.rst
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/security/ir.model.access.csv
  l10n_es_aeat_mod303/security/l10n_es_aeat_mod303_security.xml
  l10n_es_aeat_mod303/static/description/icon.png
  l10n_es_aeat_mod303/static/description/icon_source.svg
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_mod303/tests/__init__.py
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
  l10n_es_aeat_mod303/views/l10n_es_aeat_mod303_report_activity_code_data_views.xml
  l10n_es_aeat_mod303/views/mod303_view.xml
  setup/l10n_es_aeat_mod303/odoo/addons/l10n_es_aeat_mod303
  setup/l10n_es_aeat_mod303/setup.py
Labels: bot is merging ⏳

#1556 [12.0] [FIX] modelo 190 float_compare
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
Labels: bot is merging ⏳

#1565 [FIX] l10n_es_aeat_mod190: expected singleton on _compute_amount method
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
Labels: bot is merging ⏳

#1562 [FIX] l10n_es_aeat_mod390: incorrect taxes
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
Labels: approved, bot is merging ⏳

#1566 [10.0][FIX] l10n_es_aeat_mod390: incorrect taxes
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
Labels: bot is merging ⏳

#1567 [14.0][MIG] l10n_es_aeat_mod390: Migration to 14.0
  l10n_es_aeat_mod390/README.rst
  l10n_es_aeat_mod390/__init__.py
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_main_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub01_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub02_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub03_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub04_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub05_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub06_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub07_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub08_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_main_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub01_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub02_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub03_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub04_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub05_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub06_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub07_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub08_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_main_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub01_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub02_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub03_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub04_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub05_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub06_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub07_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub08_data.xml
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/docs/dr390e2017v3.xlsx
  l10n_es_aeat_mod390/docs/dr390e2018.xlsx
  l10n_es_aeat_mod390/docs/dr390e2019v100.xlsx
  l10n_es_aeat_mod390/docs/instr390.pdf
  l10n_es_aeat_mod390/i18n/es.po
  l10n_es_aeat_mod390/i18n/l10n_es_aeat_mod390.pot
  l10n_es_aeat_mod390/models/__init__.py
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod390/readme/DESCRIPTION.rst
  l10n_es_aeat_mod390/readme/INSTALL.rst
  l10n_es_aeat_mod390/readme/ROADMAP.rst
  l10n_es_aeat_mod390/readme/USAGE.rst
  l10n_es_aeat_mod390/security/ir.model.access.csv
  l10n_es_aeat_mod390/security/l10n_es_aeat_mod390_security.xml
  l10n_es_aeat_mod390/static/description/icon.png
  l10n_es_aeat_mod390/static/description/icon.svg
  l10n_es_aeat_mod390/static/description/index.html
  l10n_es_aeat_mod390/tests/__init__.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
  l10n_es_aeat_mod390/views/mod390_view.xml
  setup/l10n_es_aeat_mod390/odoo/addons/l10n_es_aeat_mod390
  setup/l10n_es_aeat_mod390/setup.py
Labels: bot is merging ⏳

#1507 [MIG] l10n_es_aeat_mod111: Migration to 14.0
  l10n_es_aeat_mod111/README.rst
  l10n_es_aeat_mod111/__init__.py
  l10n_es_aeat_mod111/__manifest__.py
  l10n_es_aeat_mod111/data/aeat_export_mod111_data.xml
  l10n_es_aeat_mod111/data/tax_code_map_mod111_data.xml
  l10n_es_aeat_mod111/docs/dr111e16v17.xls
  l10n_es_aeat_mod111/i18n/bg.po
  l10n_es_aeat_mod111/i18n/ca.po
  l10n_es_aeat_mod111/i18n/cs.po
  l10n_es_aeat_mod111/i18n/de.po
  l10n_es_aeat_mod111/i18n/es.po
  l10n_es_aeat_mod111/i18n/es_CO.po
  l10n_es_aeat_mod111/i18n/es_CR.po
  l10n_es_aeat_mod111/i18n/es_ES.po
  l10n_es_aeat_mod111/i18n/eu.po
  l10n_es_aeat_mod111/i18n/fr.po
  l10n_es_aeat_mod111/i18n/gl.po
  l10n_es_aeat_mod111/i18n/hr.po
  l10n_es_aeat_mod111/i18n/l10n_es_aeat_mod111.pot
  l10n_es_aeat_mod111/i18n/nl.po
  l10n_es_aeat_mod111/i18n/pl.po
  l10n_es_aeat_mod111/i18n/pt.po
  l10n_es_aeat_mod111/i18n/pt_BR.po
  l10n_es_aeat_mod111/i18n/ru.po
  l10n_es_aeat_mod111/i18n/sl.po
  l10n_es_aeat_mod111/i18n/sv.po
  l10n_es_aeat_mod111/i18n/tr.po
  l10n_es_aeat_mod111/i18n/vi.po
  l10n_es_aeat_mod111/models/__init__.py
  l10n_es_aeat_mod111/models/mod111.py
  l10n_es_aeat_mod111/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod111/readme/DESCRIPTION.rst
  l10n_es_aeat_mod111/readme/ROADMAP.rst
  l10n_es_aeat_mod111/readme/USAGE.rst
  l10n_es_aeat_mod111/security/ir.model.access.csv
  l10n_es_aeat_mod111/security/l10n_es_aeat_mod111_security.xml
  l10n_es_aeat_mod111/static/description/icon.png
  l10n_es_aeat_mod111/static/description/icon_source.svg
  l10n_es_aeat_mod111/static/description/index.html
  l10n_es_aeat_mod111/tests/__init__.py
  l10n_es_aeat_mod111/tests/test_l10n_es_aeat_mod111.py
  l10n_es_aeat_mod111/views/mod111_view.xml
  setup/l10n_es_aeat_mod111/odoo/addons/l10n_es_aeat_mod111
  setup/l10n_es_aeat_mod111/setup.py
Labels: bot is merging ⏳

#1563 [14.0][MIG] l10n_es_vat_book: Migration to 14.0
  l10n_es_vat_book/README.rst
  l10n_es_vat_book/__init__.py
  l10n_es_vat_book/__manifest__.py
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
  l10n_es_vat_book/i18n/bg.po
  l10n_es_vat_book/i18n/ca.po
  l10n_es_vat_book/i18n/cs.po
  l10n_es_vat_book/i18n/de.po
  l10n_es_vat_book/i18n/es.po
  l10n_es_vat_book/i18n/es_CO.po
  l10n_es_vat_book/i18n/es_CR.po
  l10n_es_vat_book/i18n/eu.po
  l10n_es_vat_book/i18n/fr.po
  l10n_es_vat_book/i18n/gl.po
  l10n_es_vat_book/i18n/hr.po
  l10n_es_vat_book/i18n/l10n_es_vat_book.pot
  l10n_es_vat_book/i18n/nl.po
  l10n_es_vat_book/i18n/pl.po
  l10n_es_vat_book/i18n/pt.po
  l10n_es_vat_book/i18n/pt_BR.po
  l10n_es_vat_book/i18n/ru.po
  l10n_es_vat_book/i18n/sl.po
  l10n_es_vat_book/i18n/sv.po
  l10n_es_vat_book/i18n/tr.po
  l10n_es_vat_book/i18n/vi.po
  l10n_es_vat_book/models/__init__.py
  l10n_es_vat_book/models/aeat_vat_book_map_line.py
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/models/l10n_es_vat_book_line.py
  l10n_es_vat_book/models/l10n_es_vat_book_line_tax.py
  l10n_es_vat_book/models/l10n_es_vat_book_summary.py
  l10n_es_vat_book/models/l10n_es_vat_book_tax_summary.py
  l10n_es_vat_book/readme/CONFIGURE.rst
  l10n_es_vat_book/readme/CONTRIBUTORS.rst
  l10n_es_vat_book/readme/DESCRIPTION.rst
  l10n_es_vat_book/readme/INSTALL.rst
  l10n_es_vat_book/readme/ROADMAP.rst
  l10n_es_vat_book/readme/USAGE.rst
  l10n_es_vat_book/report/__init__.py
  l10n_es_vat_book/report/common_templates.xml
  l10n_es_vat_book/report/report_views.xml
  l10n_es_vat_book/report/vat_book_invoices_issued.xml
  l10n_es_vat_book/report/vat_book_invoices_received.xml
  l10n_es_vat_book/report/vat_book_xlsx.py
  l10n_es_vat_book/report/vat_book_xlsx.xml
  l10n_es_vat_book/security/ir.model.access.csv
  l10n_es_vat_book/security/ir_rule.xml
  l10n_es_vat_book/static/description/icon.png
  l10n_es_vat_book/static/description/index.html
  l10n_es_vat_book/tests/__init__.py
  l10n_es_vat_book/tests/test_l10n_es_aeat_vat_book.py
  l10n_es_vat_book/views/aeat_vat_book_map_view.xml
  l10n_es_vat_book/views/l10n_es_vat_book.xml
  l10n_es_vat_book/views/l10n_es_vat_book_line.xml
  l10n_es_vat_book/views/l10n_es_vat_book_summary.xml
  l10n_es_vat_book/views/l10n_es_vat_book_tax_summary.xml
  oca_dependencies.txt
  setup/l10n_es_vat_book/odoo/addons/l10n_es_vat_book
  setup/l10n_es_vat_book/setup.py
Labels: bot is merging ⏳

#1555 [14.0] [MIG] l10n_es_account_statement_import_n43: Migration to v14
  l10n_es_account_statement_import_n43/README.rst
  l10n_es_account_statement_import_n43/__init__.py
  l10n_es_account_statement_import_n43/__manifest__.py
  l10n_es_account_statement_import_n43/doc/norma_43_castellano.pdf
  l10n_es_account_statement_import_n43/i18n/ca.po
  l10n_es_account_statement_import_n43/i18n/es.po
  l10n_es_account_statement_import_n43/i18n/eu.po
  l10n_es_account_statement_import_n43/i18n/fr.po
  l10n_es_account_statement_import_n43/i18n/gl.po
  l10n_es_account_statement_import_n43/i18n/l10n_es_account_bank_statement_import_n43.pot
  l10n_es_account_statement_import_n43/i18n/sl.po
  l10n_es_account_statement_import_n43/models/__init__.py
  l10n_es_account_statement_import_n43/models/account_journal.py
  l10n_es_account_statement_import_n43/readme/CONTRIBUTORS.rst
  l10n_es_account_statement_import_n43/readme/DESCRIPTION.rst
  l10n_es_account_statement_import_n43/readme/ROADMAP.rst
  l10n_es_account_statement_import_n43/readme/USAGE.rst
  l10n_es_account_statement_import_n43/static/description/icon.png
  l10n_es_account_statement_import_n43/static/description/icon_src.svg
  l10n_es_account_statement_import_n43/static/description/index.html
  l10n_es_account_statement_import_n43/tests/__init__.py
  l10n_es_account_statement_import_n43/tests/test.n43
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
  l10n_es_account_statement_import_n43/views/account_journal_views.xml
  l10n_es_account_statement_import_n43/wizards/__init__.py
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
  l10n_es_account_statement_import_n43/wizards/account_statement_import_view.xml
  requirements.txt
  setup/l10n_es_account_statement_import_n43/odoo/addons/l10n_es_account_statement_import_n43
  setup/l10n_es_account_statement_import_n43/setup.py
Labels: bot is merging ⏳

#1554 [14.0][MIG] l10n_es_account_asset: Migration to 14.0
  .travis.yml
  l10n_es_account_asset/README.rst
  l10n_es_account_asset/__init__.py
  l10n_es_account_asset/__manifest__.py
  l10n_es_account_asset/i18n/ca.po
  l10n_es_account_asset/i18n/cs.po
  l10n_es_account_asset/i18n/de.po
  l10n_es_account_asset/i18n/es.po
  l10n_es_account_asset/i18n/es_CO.po
  l10n_es_account_asset/i18n/fr.po
  l10n_es_account_asset/i18n/fr_BE.po
  l10n_es_account_asset/i18n/gl.po
  l10n_es_account_asset/i18n/hr.po
  l10n_es_account_asset/i18n/l10n_es_account_asset.pot
  l10n_es_account_asset/i18n/pl.po
  l10n_es_account_asset/i18n/pt.po
  l10n_es_account_asset/i18n/pt_BR.po
  l10n_es_account_asset/i18n/ru.po
  l10n_es_account_asset/i18n/sl.po
  l10n_es_account_asset/i18n/sv.po
  l10n_es_account_asset/i18n/vi.po
  l10n_es_account_asset/models/__init__.py
  l10n_es_account_asset/models/account_asset.py
  l10n_es_account_asset/models/account_asset_profile.py
  l10n_es_account_asset/readme/CONTRIBUTORS.rst
  l10n_es_account_asset/readme/DESCRIPTION.rst
  l10n_es_account_asset/static/description/icon.png
  l10n_es_account_asset/static/description/index.html
  l10n_es_account_asset/tests/__init__.py
  l10n_es_account_asset/tests/test_l10n_es_account_asset.py
  l10n_es_account_asset/views/account_asset_profile_views.xml
  l10n_es_account_asset/views/account_asset_views.xml
  oca_dependencies.txt
  setup/l10n_es_account_asset/odoo/addons/l10n_es_account_asset
  setup/l10n_es_account_asset/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1581 [12.0][IMP] l10n_es_aeat_mod390: Check 303 manual summary on confirmation
  l10n_es_aeat_mod390/i18n/es.po
  l10n_es_aeat_mod390/i18n/l10n_es_aeat_mod390.pot
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
Labels: approved, bot is merging ⏳

#1582 [FIX] l10n_es_aeat_mod190: bad perceptors vat
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
Labels: approved, bot is merging ⏳
