Repository OCA/l10n-spain, pull requests merged in 2021-05, with the labels that each got.

#1698 [FIX] l10n_es_facturae: improve calculation of TotalCost
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#1697 [FIX] l10n_es_facturae: improve calculation of TotalCost
  l10n_es_facturae/views/report_facturae.xml
Labels: approved, bot is merging ⏳

#1388 [12.0][IMP] Facturae: Add integration issue field
  l10n_es_facturae/models/account_invoice.py
  l10n_es_facturae/models/account_invoice_integration.py
  l10n_es_facturae/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1704 [FIX] l10n_es_intrastat_report: additional check if company's country…
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.py
Labels: bot is merging ⏳

#1705 [IMP] l10n_es_aeat: Remove pyOpenSSL dependancy
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat/wizard/aeat_certificate_password.py
  l10n_es_aeat_sii_oca/__manifest__.py
  requirements.txt
Labels: approved, bot is merging ⏳

#1629 [14.0][MIG] l10n_es_aeat_mod115: Migration to 14.0
  l10n_es_aeat_mod115/README.rst
  l10n_es_aeat_mod115/__init__.py
  l10n_es_aeat_mod115/__manifest__.py
  l10n_es_aeat_mod115/data/aeat_export_mod115_data.xml
  l10n_es_aeat_mod115/data/tax_code_map_mod115_data.xml
  l10n_es_aeat_mod115/docs/DR115e15v11.xls
  l10n_es_aeat_mod115/i18n/bg.po
  l10n_es_aeat_mod115/i18n/ca.po
  l10n_es_aeat_mod115/i18n/cs.po
  l10n_es_aeat_mod115/i18n/es.po
  l10n_es_aeat_mod115/i18n/es_CO.po
  l10n_es_aeat_mod115/i18n/es_CR.po
  l10n_es_aeat_mod115/i18n/eu.po
  l10n_es_aeat_mod115/i18n/fr.po
  l10n_es_aeat_mod115/i18n/gl.po
  l10n_es_aeat_mod115/i18n/hr.po
  l10n_es_aeat_mod115/i18n/l10n_es_aeat_mod115.pot
  l10n_es_aeat_mod115/i18n/nl.po
  l10n_es_aeat_mod115/i18n/pl.po
  l10n_es_aeat_mod115/i18n/pt.po
  l10n_es_aeat_mod115/i18n/pt_BR.po
  l10n_es_aeat_mod115/i18n/ru.po
  l10n_es_aeat_mod115/i18n/sl.po
  l10n_es_aeat_mod115/i18n/sv.po
  l10n_es_aeat_mod115/i18n/tr.po
  l10n_es_aeat_mod115/i18n/vi.po
  l10n_es_aeat_mod115/models/__init__.py
  l10n_es_aeat_mod115/models/mod115.py
  l10n_es_aeat_mod115/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod115/readme/DESCRIPTION.rst
  l10n_es_aeat_mod115/readme/USAGE.rst
  l10n_es_aeat_mod115/security/ir.model.access.csv
  l10n_es_aeat_mod115/security/l10n_es_aeat_mod115_security.xml
  l10n_es_aeat_mod115/static/description/icon.png
  l10n_es_aeat_mod115/static/description/icon_source.svg
  l10n_es_aeat_mod115/static/description/index.html
  l10n_es_aeat_mod115/tests/__init__.py
  l10n_es_aeat_mod115/tests/test_l10n_es_aeat_mod115.py
  l10n_es_aeat_mod115/views/mod115_view.xml
Labels: bot is merging ⏳

#1699 [14.0][MIG]l10n_es_aeat_mod123: Migration to 14.0
  l10n_es_aeat_mod123/README.rst
  l10n_es_aeat_mod123/__init__.py
  l10n_es_aeat_mod123/__manifest__.py
  l10n_es_aeat_mod123/data/aeat_export_mod123_data.xml
  l10n_es_aeat_mod123/data/tax_code_map_mod123.xml
  l10n_es_aeat_mod123/i18n/bg.po
  l10n_es_aeat_mod123/i18n/ca.po
  l10n_es_aeat_mod123/i18n/cs.po
  l10n_es_aeat_mod123/i18n/de.po
  l10n_es_aeat_mod123/i18n/es.po
  l10n_es_aeat_mod123/i18n/es_CO.po
  l10n_es_aeat_mod123/i18n/es_CR.po
  l10n_es_aeat_mod123/i18n/es_ES.po
  l10n_es_aeat_mod123/i18n/eu.po
  l10n_es_aeat_mod123/i18n/fr.po
  l10n_es_aeat_mod123/i18n/gl.po
  l10n_es_aeat_mod123/i18n/hr.po
  l10n_es_aeat_mod123/i18n/l10n_es_aeat_mod123.pot
  l10n_es_aeat_mod123/i18n/nl.po
  l10n_es_aeat_mod123/i18n/pl.po
  l10n_es_aeat_mod123/i18n/pt.po
  l10n_es_aeat_mod123/i18n/pt_BR.po
  l10n_es_aeat_mod123/i18n/sl.po
  l10n_es_aeat_mod123/i18n/sv.po
  l10n_es_aeat_mod123/i18n/tr.po
  l10n_es_aeat_mod123/i18n/vi.po
  l10n_es_aeat_mod123/models/__init__.py
  l10n_es_aeat_mod123/models/mod123.py
  l10n_es_aeat_mod123/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod123/readme/DESCRIPTION.rst
  l10n_es_aeat_mod123/readme/USAGE.rst
  l10n_es_aeat_mod123/security/ir.model.access.csv
  l10n_es_aeat_mod123/security/mod_123_security.xml
  l10n_es_aeat_mod123/static/description/icon.png
  l10n_es_aeat_mod123/static/description/icon_source.svg
  l10n_es_aeat_mod123/static/description/index.html
  l10n_es_aeat_mod123/tests/__init__.py
  l10n_es_aeat_mod123/tests/test_l10n_es_aeat_mod123.py
  l10n_es_aeat_mod123/views/mod123_view.xml
  setup/l10n_es_aeat_mod123/odoo/addons/l10n_es_aeat_mod123
  setup/l10n_es_aeat_mod123/setup.py
Labels: bot is merging ⏳

#1707 [IMP] l10n_es_facturae_face: update readme
  l10n_es_facturae_face/README.rst
  l10n_es_facturae_face/readme/CONFIGURE.rst
  l10n_es_facturae_face/static/description/index.html
Labels: approved, bot is merging ⏳

#1712 [IMP] l10n_es_aeat: Fullfill data from the certificate
  l10n_es_aeat/tests/cert/entidadspj_act.p12
  l10n_es_aeat/tests/test_l10n_es_aeat_certificate.py
  l10n_es_aeat/wizard/aeat_certificate_password.py
Labels: bot is merging ⏳

#1715 [FIX] facturae: tests where failing due to changes on bank-payment
  l10n_es_facturae/tests/common.py
Labels: approved, bot is merging ⏳

#1714 [FIX] l10n_es_irnr:fix tax groups
  l10n_es_irnr/__manifest__.py
  l10n_es_irnr/data/account_data.xml
  l10n_es_irnr/data/taxes_irnr.xml
  l10n_es_irnr/i18n/l10n_es_irnr.pot
  l10n_es_irnr/migrations/13.0.1.0.1/pre-migration.py
Labels: approved, bot is merging ⏳
