Repository OCA/l10n-spain, pull requests merged in 2022-12, with the labels that each got.

#2574 [15.0][ADD] account_promissory_note_cajamar: Module to print Cajamar's promissory notes
  account_promissory_note_cajamar/README.rst
  account_promissory_note_cajamar/__init__.py
  account_promissory_note_cajamar/__manifest__.py
  account_promissory_note_cajamar/i18n/account_promissory_note_cajamar.pot
  account_promissory_note_cajamar/i18n/es.po
  account_promissory_note_cajamar/models/__init__.py
  account_promissory_note_cajamar/models/account_journal.py
  account_promissory_note_cajamar/models/res_company.py
  account_promissory_note_cajamar/readme/CONFIGURE.rst
  account_promissory_note_cajamar/readme/CONTRIBUTORS.rst
  account_promissory_note_cajamar/readme/DESCRIPTION.rst
  account_promissory_note_cajamar/readme/USAGE.rst
  account_promissory_note_cajamar/report/__init__.py
  account_promissory_note_cajamar/report/account_promissory_note_writing_report.xml
  account_promissory_note_cajamar/report/check_print.py
  account_promissory_note_cajamar/static/description/icon.png
  account_promissory_note_cajamar/static/description/index.html
  account_promissory_note_cajamar/views/report_promissory_note.xml
  setup/account_promissory_note_cajamar/odoo/addons/account_promissory_note_cajamar
  setup/account_promissory_note_cajamar/setup.py
Labels: bot is merging ⏳

#2435 [14.0][FIX] l10n_es_vat_book: Use aeat identification types
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/models/l10n_es_vat_book_line.py
  l10n_es_vat_book/readme/CONTRIBUTORS.rst
  l10n_es_vat_book/views/l10n_es_vat_book.xml
Labels: bot is merging ⏳

#2673 [13.0][FIX] l10n_es_aeat_sii_oca: Remove ISP taxes from NotIncludedInTotalNegative
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: approved, bot is merging ⏳

#2678 [15.0][IMP] l10n_es_aeat: Improve install time
  l10n_es_aeat/__init__.py
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat/hooks.py
  l10n_es_aeat/migrations/14.0.2.4.0/pre-migration.py
Labels: bot is merging ⏳

#2674 [13.0][FIX] delivery_seur: trackings
  delivery_seur/models/delivery_carrier.py
  delivery_seur/models/seur_request.py
Labels: approved, bot is merging ⏳

#2680 [13.0][FIX] delivery_seur: tracking error condition
  delivery_seur/models/seur_request.py
Labels: bot is merging ⏳

#2681 [13.0][FIX] l10n_es_aeat: Avoid error on record initialization
  l10n_es_aeat/models/l10n_es_aeat_report.py
Labels: bot is merging ⏳

#2679 [16.0][MIG] l10n_es_aeat_mod347: Migration to 16.0
  l10n_es_aeat_mod347/README.rst
  l10n_es_aeat_mod347/__init__.py
  l10n_es_aeat_mod347/__manifest__.py
  l10n_es_aeat_mod347/controllers/__init__.py
  l10n_es_aeat_mod347/controllers/main.py
  l10n_es_aeat_mod347/data/aeat_export_mod347_data.xml
  l10n_es_aeat_mod347/data/aeat_export_mod347_partner_data.xml
  l10n_es_aeat_mod347/data/aeat_export_mod347_real_state_data.xml
  l10n_es_aeat_mod347/data/mail_template_data.xml
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
  l10n_es_aeat_mod347/docs/347_register_design.pdf
  l10n_es_aeat_mod347/i18n/bg.po
  l10n_es_aeat_mod347/i18n/ca.po
  l10n_es_aeat_mod347/i18n/cs.po
  l10n_es_aeat_mod347/i18n/es.po
  l10n_es_aeat_mod347/i18n/es_CO.po
  l10n_es_aeat_mod347/i18n/es_CR.po
  l10n_es_aeat_mod347/i18n/eu.po
  l10n_es_aeat_mod347/i18n/fr.po
  l10n_es_aeat_mod347/i18n/gl.po
  l10n_es_aeat_mod347/i18n/hr.po
  l10n_es_aeat_mod347/i18n/l10n_es_aeat_mod347.pot
  l10n_es_aeat_mod347/i18n/nl.po
  l10n_es_aeat_mod347/i18n/pl.po
  l10n_es_aeat_mod347/i18n/pt.po
  l10n_es_aeat_mod347/i18n/pt_BR.po
  l10n_es_aeat_mod347/i18n/ru.po
  l10n_es_aeat_mod347/i18n/sl.po
  l10n_es_aeat_mod347/i18n/sv.po
  l10n_es_aeat_mod347/i18n/tr.po
  l10n_es_aeat_mod347/i18n/vi.po
  l10n_es_aeat_mod347/images/l10n_es_aeat_mod347.png
  l10n_es_aeat_mod347/models/__init__.py
  l10n_es_aeat_mod347/models/account_move.py
  l10n_es_aeat_mod347/models/mod347.py
  l10n_es_aeat_mod347/models/res_partner.py
  l10n_es_aeat_mod347/readme/CONFIG.rst
  l10n_es_aeat_mod347/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod347/readme/DESCRIPTION.rst
  l10n_es_aeat_mod347/readme/INSTALL.rst
  l10n_es_aeat_mod347/readme/ROADMAP.rst
  l10n_es_aeat_mod347/readme/USAGE.rst
  l10n_es_aeat_mod347/security/ir.model.access.csv
  l10n_es_aeat_mod347/security/mod_347_security.xml
  l10n_es_aeat_mod347/static/description/icon.png
  l10n_es_aeat_mod347/static/description/icon_source.svg
  l10n_es_aeat_mod347/static/description/index.html
  l10n_es_aeat_mod347/static/src/img/347_bad.svg
  l10n_es_aeat_mod347/static/src/img/347_ok.svg
  l10n_es_aeat_mod347/tests/__init__.py
  l10n_es_aeat_mod347/tests/test_l10n_es_aeat_mod347.py
  l10n_es_aeat_mod347/views/account_move_view.xml
  l10n_es_aeat_mod347/views/mod347_templates.xml
  l10n_es_aeat_mod347/views/mod347_view.xml
  l10n_es_aeat_mod347/views/report_347_partner.xml
  l10n_es_aeat_mod347/views/res_partner_view.xml
  setup/l10n_es_aeat_mod347/odoo/addons/l10n_es_aeat_mod347
  setup/l10n_es_aeat_mod347/setup.py
Labels: bot is merging ⏳

#2576 [15.0][MIG] account_promissory_note_caixabank: Migration to 15.0
  account_promissory_note_caixabank/README.rst
  account_promissory_note_caixabank/__init__.py
  account_promissory_note_caixabank/__manifest__.py
  account_promissory_note_caixabank/i18n/account_promissory_note_caixabank.pot
  account_promissory_note_caixabank/i18n/ca.po
  account_promissory_note_caixabank/i18n/es.po
  account_promissory_note_caixabank/models/__init__.py
  account_promissory_note_caixabank/models/account_payment.py
  account_promissory_note_caixabank/models/res_company.py
  account_promissory_note_caixabank/readme/CONFIGURE.rst
  account_promissory_note_caixabank/readme/CONTRIBUTORS.rst
  account_promissory_note_caixabank/readme/DESCRIPTION.rst
  account_promissory_note_caixabank/readme/USAGE.rst
  account_promissory_note_caixabank/report/__init__.py
  account_promissory_note_caixabank/report/account_promissory_note_writing_report.xml
  account_promissory_note_caixabank/report/check_print.py
  account_promissory_note_caixabank/static/description/icon.png
  account_promissory_note_caixabank/static/description/index.html
  account_promissory_note_caixabank/views/report_promissory_note.xml
  setup/account_promissory_note_caixabank/odoo/addons/account_promissory_note_caixabank
  setup/account_promissory_note_caixabank/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1472 [12.0] [ADD] l10n_es_aeat_mod390_vat_prorrate
  l10n_es_aeat_mod390_vat_prorate/README.rst
  l10n_es_aeat_mod390_vat_prorate/__init__.py
  l10n_es_aeat_mod390_vat_prorate/__manifest__.py
  l10n_es_aeat_mod390_vat_prorate/data/aeat_export_mod390_prorate_data.xml
  l10n_es_aeat_mod390_vat_prorate/models/__init__.py
  l10n_es_aeat_mod390_vat_prorate/models/mod390.py
  l10n_es_aeat_mod390_vat_prorate/models/mod390_line_prorate.py
  l10n_es_aeat_mod390_vat_prorate/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod390_vat_prorate/readme/DESCRIPTION.rst
  l10n_es_aeat_mod390_vat_prorate/readme/ROADMAP.rst
  l10n_es_aeat_mod390_vat_prorate/readme/USAGE.rst
  l10n_es_aeat_mod390_vat_prorate/security/ir.model.access.csv
  l10n_es_aeat_mod390_vat_prorate/static/description/icon.png
  l10n_es_aeat_mod390_vat_prorate/static/description/icon.svg
  l10n_es_aeat_mod390_vat_prorate/static/description/index.html
  l10n_es_aeat_mod390_vat_prorate/tests/__init__.py
  l10n_es_aeat_mod390_vat_prorate/tests/test_l10n_es_aeat_mod390_vat_prorate.py
  l10n_es_aeat_mod390_vat_prorate/views/mod390_view.xml
  setup/l10n_es_aeat_mod390_vat_prorate/odoo/addons/l10n_es_aeat_mod390_vat_prorate
  setup/l10n_es_aeat_mod390_vat_prorate/setup.py
Labels: bot is merging ⏳

#2684 [16.0][MIG] l10n_es_vat_book: Migration to 16.0
  l10n_es_vat_book/README.rst
  l10n_es_vat_book/__init__.py
  l10n_es_vat_book/__manifest__.py
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
  l10n_es_vat_book/i18n/bg.po
  l10n_es_vat_book/i18n/ca.po
  l10n_es_vat_book/i18n/cs.po
  l10n_es_vat_book/i18n/de.po
  l10n_es_vat_book/i18n/es.po
  l10n_es_vat_book/i18n/es_CO.po
  l10n_es_vat_book/i18n/es_CR.po
  l10n_es_vat_book/i18n/eu.po
  l10n_es_vat_book/i18n/fr.po
  l10n_es_vat_book/i18n/gl.po
  l10n_es_vat_book/i18n/hr.po
  l10n_es_vat_book/i18n/l10n_es_vat_book.pot
  l10n_es_vat_book/i18n/nl.po
  l10n_es_vat_book/i18n/pl.po
  l10n_es_vat_book/i18n/pt.po
  l10n_es_vat_book/i18n/pt_BR.po
  l10n_es_vat_book/i18n/ru.po
  l10n_es_vat_book/i18n/sl.po
  l10n_es_vat_book/i18n/sv.po
  l10n_es_vat_book/i18n/tr.po
  l10n_es_vat_book/i18n/vi.po
  l10n_es_vat_book/models/__init__.py
  l10n_es_vat_book/models/aeat_vat_book_map_line.py
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/models/l10n_es_vat_book_line.py
  l10n_es_vat_book/models/l10n_es_vat_book_line_tax.py
  l10n_es_vat_book/models/l10n_es_vat_book_summary.py
  l10n_es_vat_book/models/l10n_es_vat_book_tax_summary.py
  l10n_es_vat_book/readme/CONFIGURE.rst
  l10n_es_vat_book/readme/CONTRIBUTORS.rst
  l10n_es_vat_book/readme/DESCRIPTION.rst
  l10n_es_vat_book/readme/INSTALL.rst
  l10n_es_vat_book/readme/ROADMAP.rst
  l10n_es_vat_book/readme/USAGE.rst
  l10n_es_vat_book/report/__init__.py
  l10n_es_vat_book/report/common_templates.xml
  l10n_es_vat_book/report/report_views.xml
  l10n_es_vat_book/report/vat_book_invoices_issued.xml
  l10n_es_vat_book/report/vat_book_invoices_received.xml
  l10n_es_vat_book/report/vat_book_xlsx.py
  l10n_es_vat_book/report/vat_book_xlsx.xml
  l10n_es_vat_book/security/ir.model.access.csv
  l10n_es_vat_book/security/ir_rule.xml
  l10n_es_vat_book/static/description/icon.png
  l10n_es_vat_book/static/description/index.html
  l10n_es_vat_book/tests/__init__.py
  l10n_es_vat_book/tests/test_l10n_es_aeat_vat_book.py
  l10n_es_vat_book/views/aeat_vat_book_map_view.xml
  l10n_es_vat_book/views/l10n_es_vat_book.xml
  l10n_es_vat_book/views/l10n_es_vat_book_line.xml
  l10n_es_vat_book/views/l10n_es_vat_book_summary.xml
  l10n_es_vat_book/views/l10n_es_vat_book_tax_summary.xml
  setup/l10n_es_vat_book/odoo/addons/l10n_es_vat_book
  setup/l10n_es_vat_book/setup.py
Labels: approved, bot is merging ⏳

#2683 [13.0][FIX] delivery_seur: tracking states
  delivery_seur/models/seur_request.py
Labels: approved, bot is merging ⏳

#2705 [14.0][FIX] l10n_es_aeat_sii_oca: Remove ISP taxes from NotIncludedInTotalNegative
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: bot is merging ⏳

#2706 [15.0][FIX] l10n_es_aeat_sii_oca: Remove ISP taxes from NotIncludedInTotalNegative
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: bot is merging ⏳

#2698 [16.0][MIG] l10n_es_irnr: Migration to 16.0
  l10n_es_irnr/README.rst
  l10n_es_irnr/__init__.py
  l10n_es_irnr/__manifest__.py
  l10n_es_irnr/data/account_data.xml
  l10n_es_irnr/data/fiscal_position_taxes_irnr.xml
  l10n_es_irnr/data/fiscal_positions_irnr.xml
  l10n_es_irnr/data/taxes_irnr.xml
  l10n_es_irnr/i18n/ca.po
  l10n_es_irnr/i18n/l10n_es_irnr.pot
  l10n_es_irnr/readme/CONFIGURE.rst
  l10n_es_irnr/readme/CONTRIBUTORS.rst
  l10n_es_irnr/readme/DESCRIPTION.rst
  l10n_es_irnr/readme/ROADMAP.rst
  l10n_es_irnr/readme/USAGE.rst
  l10n_es_irnr/static/description/icon.png
  l10n_es_irnr/static/description/index.html
  setup/l10n_es_irnr/odoo/addons/l10n_es_irnr
  setup/l10n_es_irnr/setup.py
Labels: approved, bot is merging ⏳

#2693 [16.0][MIG] l10n_es_aeat_mod303: Migration to 16.0
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/__init__.py
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2021-07/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2021-07/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/aeat_export_mod303_2018_data.xml
  l10n_es_aeat_mod303/data/aeat_export_mod303_2021_data.xml
  l10n_es_aeat_mod303/data/l10n_es_aeat_mod303_report_activity_code_data.xml
  l10n_es_aeat_mod303/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_mod303/docs/303_register_design_e15v32.xlsx
  l10n_es_aeat_mod303/docs/DR303e15v34.xlsx
  l10n_es_aeat_mod303/docs/DR303e17v20_04.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_00.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_40.xlsx
  l10n_es_aeat_mod303/docs/DR303e21v100.xlsx
  l10n_es_aeat_mod303/docs/DR303e21v200.xlsx
  l10n_es_aeat_mod303/docs/DR303e22.xlsx
  l10n_es_aeat_mod303/i18n/bg.po
  l10n_es_aeat_mod303/i18n/ca.po
  l10n_es_aeat_mod303/i18n/cs.po
  l10n_es_aeat_mod303/i18n/de.po
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/es_CO.po
  l10n_es_aeat_mod303/i18n/es_CR.po
  l10n_es_aeat_mod303/i18n/eu.po
  l10n_es_aeat_mod303/i18n/fr.po
  l10n_es_aeat_mod303/i18n/gl.po
  l10n_es_aeat_mod303/i18n/hr.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/i18n/nl.po
  l10n_es_aeat_mod303/i18n/pl.po
  l10n_es_aeat_mod303/i18n/pt.po
  l10n_es_aeat_mod303/i18n/pt_BR.po
  l10n_es_aeat_mod303/i18n/sl.po
  l10n_es_aeat_mod303/i18n/sv.po
  l10n_es_aeat_mod303/i18n/tr.po
  l10n_es_aeat_mod303/i18n/vi.po
  l10n_es_aeat_mod303/models/__init__.py
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303/readme/DESCRIPTION.rst
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/security/ir.model.access.csv
  l10n_es_aeat_mod303/security/l10n_es_aeat_mod303_security.xml
  l10n_es_aeat_mod303/static/description/icon.png
  l10n_es_aeat_mod303/static/description/icon_source.svg
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_mod303/tests/__init__.py
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
  l10n_es_aeat_mod303/views/l10n_es_aeat_mod303_report_activity_code_data_views.xml
  l10n_es_aeat_mod303/views/mod303_view.xml
  setup/l10n_es_aeat_mod303/odoo/addons/l10n_es_aeat_mod303
  setup/l10n_es_aeat_mod303/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2695 [16.0][MIG] l10n_es_aeat_mod115: Migration to 16.0
  l10n_es_aeat_mod115/README.rst
  l10n_es_aeat_mod115/__init__.py
  l10n_es_aeat_mod115/__manifest__.py
  l10n_es_aeat_mod115/data/aeat_export_mod115_data.xml
  l10n_es_aeat_mod115/data/tax_code_map_mod115_data.xml
  l10n_es_aeat_mod115/docs/DR115e15v11.xls
  l10n_es_aeat_mod115/i18n/bg.po
  l10n_es_aeat_mod115/i18n/ca.po
  l10n_es_aeat_mod115/i18n/cs.po
  l10n_es_aeat_mod115/i18n/es.po
  l10n_es_aeat_mod115/i18n/es_CO.po
  l10n_es_aeat_mod115/i18n/es_CR.po
  l10n_es_aeat_mod115/i18n/eu.po
  l10n_es_aeat_mod115/i18n/fr.po
  l10n_es_aeat_mod115/i18n/gl.po
  l10n_es_aeat_mod115/i18n/hr.po
  l10n_es_aeat_mod115/i18n/l10n_es_aeat_mod115.pot
  l10n_es_aeat_mod115/i18n/nl.po
  l10n_es_aeat_mod115/i18n/pl.po
  l10n_es_aeat_mod115/i18n/pt.po
  l10n_es_aeat_mod115/i18n/pt_BR.po
  l10n_es_aeat_mod115/i18n/ru.po
  l10n_es_aeat_mod115/i18n/sl.po
  l10n_es_aeat_mod115/i18n/sv.po
  l10n_es_aeat_mod115/i18n/tr.po
  l10n_es_aeat_mod115/i18n/vi.po
  l10n_es_aeat_mod115/models/__init__.py
  l10n_es_aeat_mod115/models/mod115.py
  l10n_es_aeat_mod115/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod115/readme/DESCRIPTION.rst
  l10n_es_aeat_mod115/readme/USAGE.rst
  l10n_es_aeat_mod115/security/ir.model.access.csv
  l10n_es_aeat_mod115/security/l10n_es_aeat_mod115_security.xml
  l10n_es_aeat_mod115/static/description/icon.png
  l10n_es_aeat_mod115/static/description/icon_source.svg
  l10n_es_aeat_mod115/static/description/index.html
  l10n_es_aeat_mod115/tests/__init__.py
  l10n_es_aeat_mod115/tests/test_l10n_es_aeat_mod115.py
  l10n_es_aeat_mod115/views/mod115_view.xml
  setup/l10n_es_aeat_mod115/odoo/addons/l10n_es_aeat_mod115
  setup/l10n_es_aeat_mod115/setup.py
Labels: approved, bot is merging ⏳

#2709 [16.0][MIG] l10n_es_partner: Migration to 16.0
  l10n_es_partner/README.rst
  l10n_es_partner/__init__.py
  l10n_es_partner/__manifest__.py
  l10n_es_partner/data/l10n_es_partner_data.xml
  l10n_es_partner/gen_src/README.rst
  l10n_es_partner/gen_src/__init__.py
  l10n_es_partner/gen_src/bics.xls
  l10n_es_partner/gen_src/gen_data_banks.py
  l10n_es_partner/i18n/bg.po
  l10n_es_partner/i18n/ca.po
  l10n_es_partner/i18n/cs.po
  l10n_es_partner/i18n/de.po
  l10n_es_partner/i18n/es.po
  l10n_es_partner/i18n/es_CO.po
  l10n_es_partner/i18n/es_CR.po
  l10n_es_partner/i18n/es_ES.po
  l10n_es_partner/i18n/eu.po
  l10n_es_partner/i18n/fr.po
  l10n_es_partner/i18n/gl.po
  l10n_es_partner/i18n/hr.po
  l10n_es_partner/i18n/l10n_es_partner.pot
  l10n_es_partner/i18n/nl.po
  l10n_es_partner/i18n/pl.po
  l10n_es_partner/i18n/pt.po
  l10n_es_partner/i18n/pt_BR.po
  l10n_es_partner/i18n/ru.po
  l10n_es_partner/i18n/sl.po
  l10n_es_partner/i18n/sv.po
  l10n_es_partner/i18n/tr.po
  l10n_es_partner/i18n/vi.po
  l10n_es_partner/models/__init__.py
  l10n_es_partner/models/res_bank.py
  l10n_es_partner/models/res_partner.py
  l10n_es_partner/readme/CONFIGURE.rst
  l10n_es_partner/readme/CONTRIBUTORS.rst
  l10n_es_partner/readme/DESCRIPTION.rst
  l10n_es_partner/readme/INSTALL.rst
  l10n_es_partner/readme/ROADMAP.rst
  l10n_es_partner/security/ir.model.access.csv
  l10n_es_partner/static/description/bank.svg
  l10n_es_partner/static/description/icon.png
  l10n_es_partner/static/description/index.html
  l10n_es_partner/tests/__init__.py
  l10n_es_partner/tests/test_l10n_es_partner.py
  l10n_es_partner/views/res_bank_view.xml
  l10n_es_partner/views/res_partner_view.xml
  l10n_es_partner/wizard/__init__.py
  l10n_es_partner/wizard/data_banks.xml
  l10n_es_partner/wizard/l10n_es_partner_wizard.py
  l10n_es_partner/wizard/l10n_es_partner_wizard.xml
  setup/l10n_es_partner/odoo/addons/l10n_es_partner
  setup/l10n_es_partner/setup.py
Labels: approved, bot is merging ⏳

#2702 [16.0][MIG] l10n_es_aeat_mod390: Migration to 16.0
  l10n_es_aeat_mod390/README.rst
  l10n_es_aeat_mod390/__init__.py
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_main_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub01_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub02_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub03_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub04_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub05_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub06_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub07_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub08_data.xml
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/docs/dr390e2017v3.xlsx
  l10n_es_aeat_mod390/docs/dr390e2018.xlsx
  l10n_es_aeat_mod390/docs/dr390e2019v100.xlsx
  l10n_es_aeat_mod390/docs/instr390.pdf
  l10n_es_aeat_mod390/i18n/ca.po
  l10n_es_aeat_mod390/i18n/es.po
  l10n_es_aeat_mod390/i18n/l10n_es_aeat_mod390.pot
  l10n_es_aeat_mod390/models/__init__.py
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod390/readme/DESCRIPTION.rst
  l10n_es_aeat_mod390/readme/INSTALL.rst
  l10n_es_aeat_mod390/readme/ROADMAP.rst
  l10n_es_aeat_mod390/readme/USAGE.rst
  l10n_es_aeat_mod390/security/ir.model.access.csv
  l10n_es_aeat_mod390/security/l10n_es_aeat_mod390_security.xml
  l10n_es_aeat_mod390/static/description/icon.png
  l10n_es_aeat_mod390/static/description/icon.svg
  l10n_es_aeat_mod390/static/description/index.html
  l10n_es_aeat_mod390/tests/__init__.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
  l10n_es_aeat_mod390/views/mod390_view.xml
  setup/l10n_es_aeat_mod390/odoo/addons/l10n_es_aeat_mod390
  setup/l10n_es_aeat_mod390/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2701 [16.0][MIG] l10n_es_aeat_partner_check: Migration to 16.0
  l10n_es_aeat_partner_check/README.rst
  l10n_es_aeat_partner_check/__init__.py
  l10n_es_aeat_partner_check/__manifest__.py
  l10n_es_aeat_partner_check/i18n/ca.po
  l10n_es_aeat_partner_check/i18n/es.po
  l10n_es_aeat_partner_check/i18n/l10n_es_aeat_partner_check.pot
  l10n_es_aeat_partner_check/models/__init__.py
  l10n_es_aeat_partner_check/models/res_company.py
  l10n_es_aeat_partner_check/models/res_config_settings.py
  l10n_es_aeat_partner_check/models/res_partner.py
  l10n_es_aeat_partner_check/readme/CONTRIBUTORS.rst
  l10n_es_aeat_partner_check/readme/DESCRIPTION.rst
  l10n_es_aeat_partner_check/readme/INSTALL.rst
  l10n_es_aeat_partner_check/readme/USAGE.rst
  l10n_es_aeat_partner_check/static/description/icon.png
  l10n_es_aeat_partner_check/static/description/index.html
  l10n_es_aeat_partner_check/tests/__init__.py
  l10n_es_aeat_partner_check/tests/test_res_partner.py
  l10n_es_aeat_partner_check/views/res_company_view.xml
  l10n_es_aeat_partner_check/views/res_config_settings_view.xml
  l10n_es_aeat_partner_check/views/res_partner_view.xml
  setup/l10n_es_aeat_partner_check/odoo/addons/l10n_es_aeat_partner_check
  setup/l10n_es_aeat_partner_check/setup.py
Labels: approved, ready to merge, bot is merging ⏳
