Repository OCA/l10n-spain, pull requests merged in 2022-07, with the labels that each got.

#2368 [MIG] l10n_es_ticketbai_batuz: Migration to 13.0
  l10n_es_ticketbai_batuz/README.rst
  l10n_es_ticketbai_batuz/__init__.py
  l10n_es_ticketbai_batuz/__manifest__.py
  l10n_es_ticketbai_batuz/data/account_fiscal_position_template_data.xml
  l10n_es_ticketbai_batuz/data/queue_job_data.xml
  l10n_es_ticketbai_batuz/data/tbai_tax_map_data.xml
  l10n_es_ticketbai_batuz/data/tbai_vat_regime_key_data.xml
  l10n_es_ticketbai_batuz/hooks.py
  l10n_es_ticketbai_batuz/i18n/es.po
  l10n_es_ticketbai_batuz/i18n/l10n_es_ticketbai_batuz.pot
  l10n_es_ticketbai_batuz/models/__init__.py
  l10n_es_ticketbai_batuz/models/account_fiscal_position.py
  l10n_es_ticketbai_batuz/models/account_move.py
  l10n_es_ticketbai_batuz/models/chart_template.py
  l10n_es_ticketbai_batuz/models/lroe_operation.py
  l10n_es_ticketbai_batuz/models/res_company.py
  l10n_es_ticketbai_batuz/models/res_partner.py
  l10n_es_ticketbai_batuz/models/ticketbai_invoice.py
  l10n_es_ticketbai_batuz/models/ticketbai_vat_regime_key.py
  l10n_es_ticketbai_batuz/readme/CONTRIBUTORS.rst
  l10n_es_ticketbai_batuz/readme/DESCRIPTION.rst
  l10n_es_ticketbai_batuz/readme/INSTALL.rst
  l10n_es_ticketbai_batuz/readme/USAGE.rst
  l10n_es_ticketbai_batuz/security/ir_rule.xml
  l10n_es_ticketbai_batuz/static/description/icon.png
  l10n_es_ticketbai_batuz/static/description/index.html
  l10n_es_ticketbai_batuz/static/src/description/icon.png
  l10n_es_ticketbai_batuz/static/src/img/binovo_logo.jpg
  l10n_es_ticketbai_batuz/static/src/img/binovo_logo_peque.jpg
  l10n_es_ticketbai_batuz/views/account_fiscal_position_views.xml
  l10n_es_ticketbai_batuz/views/account_move_views.xml
  l10n_es_ticketbai_batuz/views/lroe_operation_views.xml
  l10n_es_ticketbai_batuz/views/res_company_views.xml
  l10n_es_ticketbai_batuz/views/res_partner_views.xml
  l10n_es_ticketbai_batuz/views/tbai_vat_regime_key_views.xml
  l10n_es_ticketbai_batuz/wizard/__init__.py
  l10n_es_ticketbai_batuz/wizard/account_move_reversal.py
  l10n_es_ticketbai_batuz/wizard/account_move_reversal_views.xml
  setup/l10n_es_ticketbai_batuz/odoo/addons/l10n_es_ticketbai_batuz
  setup/l10n_es_ticketbai_batuz/setup.py
Labels: approved, bot is merging ⏳

#2337 [IMP]l10n_es_aeat_mod349: Mostrar errores en líneas del 349
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod349/views/mod349_view.xml
Labels: bot is merging ⏳

#2366 [15.0][FIX] l10n_es_facturae: Fill InvoiceDescription with plain text
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#2386 [15.0][FIX] l10n_es_facturae_face: validate fields before creting exchange record
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_listener.py
Labels: bot is merging ⏳

#2381 [15.0][FIX] l10n_es_ticketbai: Corrección de valores de impuestos y posición fiscal default en facturas
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/account_tax.py
Labels: bot is merging ⏳

#1982 [15.0][MIG]l10n_es_pos
  l10n_es_pos/README.rst
  l10n_es_pos/__init__.py
  l10n_es_pos/__manifest__.py
  l10n_es_pos/hooks.py
  l10n_es_pos/i18n/ca.po
  l10n_es_pos/i18n/ca_ES.po
  l10n_es_pos/i18n/es.po
  l10n_es_pos/i18n/l10n_es_pos.pot
  l10n_es_pos/models/__init__.py
  l10n_es_pos/models/ir_sequence.py
  l10n_es_pos/models/pos_config.py
  l10n_es_pos/models/pos_order.py
  l10n_es_pos/readme/CONFIGURE.rst
  l10n_es_pos/readme/CONTRIBUTORS.rst
  l10n_es_pos/readme/DESCRIPTION.rst
  l10n_es_pos/readme/INSTALL.rst
  l10n_es_pos/readme/ROADMAP.rst
  l10n_es_pos/static/description/icon.png
  l10n_es_pos/static/description/index.html
  l10n_es_pos/static/src/js/PaymentScreen.js
  l10n_es_pos/static/src/js/Screens/TicketScreen/TicketScreen.js
  l10n_es_pos/static/src/js/models.js
  l10n_es_pos/static/src/xml/Screens/OrderManagementScreen/TicketScreen.xml
  l10n_es_pos/static/src/xml/pos.xml
  l10n_es_pos/views/pos_views.xml
  setup/l10n_es_pos/odoo/addons/l10n_es_pos
  setup/l10n_es_pos/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2388 [15.0][IMP] l10n_es_ticketbai: posibilitar envío de factura simplificada de…
  l10n_es_ticketbai/README.rst
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#2392 [13.0][FIX]l10n_es_facturae: Show printer icon in facturae export wizard
  l10n_es_facturae/wizard/create_facturae_view.xml
Labels: approved, bot is merging ⏳

#2393 [14.0][FIX]l10n_es_facturae: Show printer icon in facturae export wizard
  l10n_es_facturae/wizard/create_facturae_view.xml
Labels: approved, bot is merging ⏳

#2323 [15.0][IMP] l10n_es_facturae_face: Only attach data if data changes
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/components/__init__.py
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_listener.py
  l10n_es_facturae_face/components/edi_output_l10n_es_facturae.py
  l10n_es_facturae_face/data/cron_data.xml
  l10n_es_facturae_face/models/__init__.py
  l10n_es_facturae_face/models/config.py
  l10n_es_facturae_face/models/edi_exchange_record.py
  l10n_es_facturae_face/tests/test_facturae_face.py
  l10n_es_facturae_face/views/res_config_views.xml
Labels: approved, bot is merging ⏳

#2398 [15.0][FIX] l10n_es_facturae: minor translation fixes (forward port)
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae/i18n/bg.po
  l10n_es_facturae/i18n/ca.po
  l10n_es_facturae/i18n/cs.po
  l10n_es_facturae/i18n/de.po
  l10n_es_facturae/i18n/es.po
  l10n_es_facturae/i18n/es_CO.po
  l10n_es_facturae/i18n/es_CR.po
  l10n_es_facturae/i18n/es_ES.po
  l10n_es_facturae/i18n/eu.po
  l10n_es_facturae/i18n/fr.po
  l10n_es_facturae/i18n/gl.po
  l10n_es_facturae/i18n/hr.po
  l10n_es_facturae/i18n/l10n_es_facturae.pot
  l10n_es_facturae/i18n/nl.po
  l10n_es_facturae/i18n/pl.po
  l10n_es_facturae/i18n/pt.po
  l10n_es_facturae/i18n/pt_BR.po
  l10n_es_facturae/i18n/ru.po
  l10n_es_facturae/i18n/sl.po
  l10n_es_facturae/i18n/sv.po
  l10n_es_facturae/i18n/tr.po
  l10n_es_facturae/i18n/vi.po
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/readme/INSTALL.rst
  l10n_es_facturae/readme/USAGE.rst
  l10n_es_facturae/reports/report_facturae.py
  l10n_es_facturae/static/description/index.html
  l10n_es_facturae/views/report_facturae.xml
  l10n_es_facturae/views/res_company.xml
  l10n_es_facturae/wizard/account_move_reversal.py
  l10n_es_facturae/wizard/create_facturae.py
  l10n_es_facturae/wizard/create_facturae_view.xml
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/data/cron_data.xml
  l10n_es_facturae_face/i18n/es.po
  l10n_es_facturae_face/i18n/l10n_es_facturae_face.pot
  l10n_es_facturae_face/models/account_move.py
  l10n_es_facturae_face/static/description/index.html
  l10n_es_facturae_face/wizards/edi_l10n_es_facturae_face_cancel.xml
Labels: approved, bot is merging ⏳

#2400 [13.0][FIX] l10n_es_dua: Product taxes should not be rewritten
  l10n_es_dua/data/products_dua.xml
Labels: approved, bot is merging ⏳

#2356 [MIG] l10n_es_ticketbai_pos: Migration to 13.0
  l10n_es_ticketbai_pos/README.rst
  l10n_es_ticketbai_pos/__init__.py
  l10n_es_ticketbai_pos/__manifest__.py
  l10n_es_ticketbai_pos/i18n/es.po
  l10n_es_ticketbai_pos/i18n/l10n_es_ticketbai_pos.pot
  l10n_es_ticketbai_pos/models/__init__.py
  l10n_es_ticketbai_pos/models/account_move.py
  l10n_es_ticketbai_pos/models/pos_config.py
  l10n_es_ticketbai_pos/models/pos_order.py
  l10n_es_ticketbai_pos/models/ticketbai_invoice.py
  l10n_es_ticketbai_pos/security/ir.model.access.csv
  l10n_es_ticketbai_pos/static/description/icon.png
  l10n_es_ticketbai_pos/static/lib/qrcode.js
  l10n_es_ticketbai_pos/static/lib/tbai.js
  l10n_es_ticketbai_pos/static/src/img/oca_logo.png
  l10n_es_ticketbai_pos/static/src/js/db.js
  l10n_es_ticketbai_pos/static/src/js/models.js
  l10n_es_ticketbai_pos/static/src/js/screens.js
  l10n_es_ticketbai_pos/static/src/js/tbai_models.js
  l10n_es_ticketbai_pos/static/src/js/widgets.js
  l10n_es_ticketbai_pos/static/src/xml/pos.xml
  l10n_es_ticketbai_pos/tests/__init__.py
  l10n_es_ticketbai_pos/tests/common.py
  l10n_es_ticketbai_pos/tests/test_l10n_es_ticketbai_pos.py
  l10n_es_ticketbai_pos/views/l10n_es_ticketbai_pos.xml
  l10n_es_ticketbai_pos/views/l10n_es_ticketbai_pos_views.xml
  l10n_es_ticketbai_pos/views/pos_order_views.xml
  l10n_es_ticketbai_pos/views/ticketbai_certificate_views.xml
  setup/l10n_es_ticketbai_pos/odoo/addons/l10n_es_ticketbai_pos
  setup/l10n_es_ticketbai_pos/setup.py
Labels: approved, bot is merging ⏳

#2403 [14.0][IMP] l10n_es_intrastat_report: 2022 NC codes
  l10n_es_intrastat_report/README.rst
  l10n_es_intrastat_report/data/Estruc_NC2022.xlsx
  l10n_es_intrastat_report/readme/INSTALL.rst
  l10n_es_intrastat_report/static/description/index.html
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.py
Labels: bot is merging ⏳

#2405 [12.0][FIX] l10n_es_ticketbai_pos: Permitir reimprimir ticket sin código QR
  l10n_es_ticketbai_pos/models/pos_order.py
Labels: bot is merging ⏳

#2387 [12.0][FIX] l10n_es_ticketbai_batuz: En los diarios de compras hacer visibles los campos de Ticketbai
  l10n_es_ticketbai_batuz/__manifest__.py
  l10n_es_ticketbai_batuz/views/account_journal_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2408 [14.0][FIX] l10n_es_dua: Product taxes should not be rewritten
  l10n_es_dua/data/products_dua.xml
Labels: bot is merging ⏳

#2409 [13.0][FIX] l10n_es_ticketbai_api: res.partner tbai_enabled field calculation
  l10n_es_ticketbai_api/models/res_partner.py
Labels: approved, bot is merging ⏳

#2414 [14.0][FIX] l10n_es_ticketbai_api: res.partner tbai_enabled field calculation
  l10n_es_ticketbai_api/models/res_partner.py
Labels: bot is merging ⏳

#2415 [15.0][FIX] l10n_es_ticketbai_api: res.partner tbai_enabled field calculation
  l10n_es_ticketbai_api/models/res_partner.py
Labels: bot is merging ⏳

#2375 [MIG] l10n_es_dua_ticketbai_batuz: Migration to 13.0
  l10n_es_dua_ticketbai_batuz/README.rst
  l10n_es_dua_ticketbai_batuz/__init__.py
  l10n_es_dua_ticketbai_batuz/__manifest__.py
  l10n_es_dua_ticketbai_batuz/data/account_fiscal_position_template_data.xml
  l10n_es_dua_ticketbai_batuz/data/tax_code_map_dua_ticketbai_data.xml
  l10n_es_dua_ticketbai_batuz/i18n/l10n_es_dua_ticketbai_batuz.pot
  l10n_es_dua_ticketbai_batuz/models/__init__.py
  l10n_es_dua_ticketbai_batuz/models/account_move.py
  l10n_es_dua_ticketbai_batuz/readme/CONFIGURATION.rst
  l10n_es_dua_ticketbai_batuz/readme/CONTRIBUTORS.rst
  l10n_es_dua_ticketbai_batuz/readme/DESCRIPTION.rst
  l10n_es_dua_ticketbai_batuz/readme/USAGE.rst
  l10n_es_dua_ticketbai_batuz/static/description/icon.png
  l10n_es_dua_ticketbai_batuz/static/description/index.html
  setup/l10n_es_dua_ticketbai_batuz/odoo/addons/l10n_es_dua_ticketbai_batuz
  setup/l10n_es_dua_ticketbai_batuz/setup.py
Labels: approved, bot is merging ⏳

#2422 [13.0][IMP] TicketBAI: Add myself as maintainer
  l10n_es_ticketbai_api_batuz/__manifest__.py
  l10n_es_ticketbai_pos/__manifest__.py
Labels: bot is merging ⏳

#2423 [14.0][IMP] TicketBAI: Add myself as maintainer
  l10n_es_ticketbai_api_batuz/__manifest__.py
Labels: bot is merging ⏳

#2420 [ADD][12.0] l10n_es_extra_data: new module
  l10n_es_extra_data/README.rst
  l10n_es_extra_data/__init__.py
  l10n_es_extra_data/__manifest__.py
  l10n_es_extra_data/data/account_data.xml
  l10n_es_extra_data/data/account_tax_data.xml
  l10n_es_extra_data/readme/CONTRIBUTORS.rst
  l10n_es_extra_data/readme/DESCRIPTION.rst
  l10n_es_extra_data/readme/HISTORY.rst
  l10n_es_extra_data/readme/USAGE.rst
  l10n_es_extra_data/static/description/icon.png
  l10n_es_extra_data/static/description/index.html
Labels: bot is merging ⏳

#2424 [14.0] l10n_es_aeat_*: Include new 5% tax
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: bot is merging ⏳

#2410 [13.0] l10n_es_aeat_*: Include new 5% tax
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: bot is merging ⏳

#2427 [FIX] l10n_es_extra_data: country_id does not exist
  l10n_es_extra_data/data/account_data.xml
Labels: bot is merging ⏳

#2428 [ADD][12.0] l10n_es_vat_book_extra_data: new module
  l10n_es_vat_book_extra_data/README.rst
  l10n_es_vat_book_extra_data/__init__.py
  l10n_es_vat_book_extra_data/__manifest__.py
  l10n_es_vat_book_extra_data/data/aeat_vat_book_map_data.xml
  l10n_es_vat_book_extra_data/readme/CONTRIBUTORS.rst
  l10n_es_vat_book_extra_data/readme/DESCRIPTION.rst
  l10n_es_vat_book_extra_data/static/description/index.html
Labels: approved, bot is merging ⏳

#2426 [ADD][12.0] l10n_es_aeat_sii_extra_data: new module
  l10n_es_aeat_sii_extra_data/README.rst
  l10n_es_aeat_sii_extra_data/__init__.py
  l10n_es_aeat_sii_extra_data/__manifest__.py
  l10n_es_aeat_sii_extra_data/data/aeat_sii_map_data.xml
  l10n_es_aeat_sii_extra_data/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_extra_data/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_extra_data/static/description/index.html
Labels: approved, bot is merging ⏳

#2425 [ADD][12.0] l10n_es_aeat_mod303_extra_data: new module
  l10n_es_aeat_mod303_extra_data/README.rst
  l10n_es_aeat_mod303_extra_data/__init__.py
  l10n_es_aeat_mod303_extra_data/__manifest__.py
  l10n_es_aeat_mod303_extra_data/data/2021-07/l10n_es_aeat_map_tax_line.xml
  l10n_es_aeat_mod303_extra_data/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303_extra_data/readme/DESCRIPTION.rst
  l10n_es_aeat_mod303_extra_data/readme/HISTORY.rst
  l10n_es_aeat_mod303_extra_data/static/description/index.html
Labels: bot is merging ⏳

#2429 [14.0][FIX] delivery_gls_asm: prevent escape of bool
  delivery_gls_asm/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#2434 [FIX][13.0]l10n_es_ticketbai,l10n_es_ticketbai_batuz: Correcciones cuando no está activado ticketbai
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai_batuz/views/account_move_views.xml
Labels: approved, bot is merging ⏳

#2436 [FIX]l10n_es_ticketbai: Corregido filtered refund
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#2432 [14.0][MIG] l10n_es_ticketbai_batuz: Migration to 14.0
  l10n_es_ticketbai_api_batuz/models/lroe_operation.py
  l10n_es_ticketbai_batuz/README.rst
  l10n_es_ticketbai_batuz/__init__.py
  l10n_es_ticketbai_batuz/__manifest__.py
  l10n_es_ticketbai_batuz/data/account_fiscal_position_template_data.xml
  l10n_es_ticketbai_batuz/data/queue_job_data.xml
  l10n_es_ticketbai_batuz/data/tbai_tax_map_data.xml
  l10n_es_ticketbai_batuz/data/tbai_vat_regime_key_data.xml
  l10n_es_ticketbai_batuz/hooks.py
  l10n_es_ticketbai_batuz/i18n/es.po
  l10n_es_ticketbai_batuz/i18n/l10n_es_ticketbai_batuz.pot
  l10n_es_ticketbai_batuz/models/__init__.py
  l10n_es_ticketbai_batuz/models/account_fiscal_position.py
  l10n_es_ticketbai_batuz/models/account_move.py
  l10n_es_ticketbai_batuz/models/chart_template.py
  l10n_es_ticketbai_batuz/models/lroe_operation.py
  l10n_es_ticketbai_batuz/models/res_company.py
  l10n_es_ticketbai_batuz/models/res_partner.py
  l10n_es_ticketbai_batuz/models/ticketbai_invoice.py
  l10n_es_ticketbai_batuz/models/ticketbai_vat_regime_key.py
  l10n_es_ticketbai_batuz/readme/CONTRIBUTORS.rst
  l10n_es_ticketbai_batuz/readme/DESCRIPTION.rst
  l10n_es_ticketbai_batuz/readme/INSTALL.rst
  l10n_es_ticketbai_batuz/readme/USAGE.rst
  l10n_es_ticketbai_batuz/security/ir_rule.xml
  l10n_es_ticketbai_batuz/static/description/icon.png
  l10n_es_ticketbai_batuz/static/description/index.html
  l10n_es_ticketbai_batuz/static/src/description/icon.png
  l10n_es_ticketbai_batuz/static/src/img/binovo_logo.jpg
  l10n_es_ticketbai_batuz/static/src/img/binovo_logo_peque.jpg
  l10n_es_ticketbai_batuz/views/account_fiscal_position_views.xml
  l10n_es_ticketbai_batuz/views/account_move_views.xml
  l10n_es_ticketbai_batuz/views/lroe_operation_views.xml
  l10n_es_ticketbai_batuz/views/res_company_views.xml
  l10n_es_ticketbai_batuz/views/res_partner_views.xml
  l10n_es_ticketbai_batuz/views/tbai_vat_regime_key_views.xml
  l10n_es_ticketbai_batuz/wizard/__init__.py
  l10n_es_ticketbai_batuz/wizard/account_move_reversal.py
  l10n_es_ticketbai_batuz/wizard/account_move_reversal_views.xml
  setup/l10n_es_ticketbai_batuz/odoo/addons/l10n_es_ticketbai_batuz
  setup/l10n_es_ticketbai_batuz/setup.py
Labels: approved, bot is merging ⏳

#2441 [13.0][IMP] l10n_es_aeat_sii_oca: Avoid modifying third-party number when an invoice has already been sent to the SII + Tests.
  l10n_es_aeat_sii_oca/i18n/es.po
  l10n_es_aeat_sii_oca/i18n/l10n_es_aeat_sii_oca.pot
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: approved, bot is merging ⏳

#2444 [13.0][FIX] l10n_es_aeat_mod303: Default value for regularizacion_anual
  l10n_es_aeat_mod303/models/mod303.py
Labels: bot is merging ⏳

#2445 [14.0][IMP] l10n_es_aeat_sii_oca: Avoid modifying third-party number when an invoice has already been sent to the SII + Tests.
  l10n_es_aeat_sii_oca/i18n/es.po
  l10n_es_aeat_sii_oca/i18n/l10n_es_aeat_sii_oca.pot
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: bot is merging ⏳
