Repository OCA/l10n-spain, pull requests merged in 2022-02, with the labels that each got.

#2046 [13.0][FIX] l10n_es_ticketbai_api: Fix araba communication
  l10n_es_ticketbai_api/models/ticketbai_response.py
Labels: bot is merging ⏳

#2028 [11.0][FIX] l10n_es_vat_book: Recargo de equivalencia en Excel
  l10n_es_vat_book/models/l10n_es_vat_book.py
Labels: approved, bot is merging ⏳

#2008 [13.0][IMP] l10n_es_ticketbai: Allow the user to say that the line detail i…
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/res_company_views.xml
Labels: bot is merging ⏳

#2078 [14.0][IMP] l10n_es_ticketbai: Allow the user to say that the line detail i…
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/res_company_views.xml
Labels: bot is merging ⏳

#2037 [14.0][IMP] l10n_es_ticketbai: refund invoice without having a tbai.invoice…
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/ticketbai_invoice.py
  l10n_es_ticketbai/security/ir.model.access.csv
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/account_move_views.xml
Labels: bot is merging ⏳

#2084 [12.0][FIX] l10n_es_ticketbai - añadidos impuestos al mapeo de No sujeto R…
  l10n_es_ticketbai/data/tax_map_data.xml
Labels: bot is merging ⏳

#2075 [14.0][IMP] l10n_es_ticketbai and l10n_es_ticketbai_api: Add missing tests
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai_api/demo/res_partner_demo.xml
  l10n_es_ticketbai_api/static/src/img/derbi.png
  l10n_es_ticketbai_api/static/src/img/peugeot.png
  l10n_es_ticketbai_api/tests/__init__.py
  l10n_es_ticketbai_api/tests/certs/ciudadano_act.p12
  l10n_es_ticketbai_api/tests/certs/ciudadano_act_p12_password.txt
  l10n_es_ticketbai_api/tests/common.py
  l10n_es_ticketbai_api/tests/company.json
  l10n_es_ticketbai_api/tests/test_l10n_es_ticketbai_tax_agency.py
Labels: bot is merging ⏳

#2085 [13.0][FIX] l10n_es_ticketbai - añadidos impuestos al mapeo de No sujeto Re…
  l10n_es_ticketbai/data/tax_map_data.xml
Labels: bot is merging ⏳

#2087 [FIX] payment_redsys: wrong reference
  payment_redsys/models/redsys.py
Labels: approved, bot is merging ⏳

#2088 [14.0][FIX] l10n_es_ticketbai - añadidos impuestos al mapeo de No sujeto Re…
  l10n_es_ticketbai/data/tax_map_data.xml
Labels: bot is merging ⏳

#2090 [14.0][FIX] payment_redsys: wrong reference
  payment_redsys/models/redsys.py
Labels: bot is merging ⏳

#2029 [13.0][IMP] l10n_es_aeat_sii_oca + l10n_es_facturae: Hide thirdparty fields in some cases
  l10n_es_aeat_sii_oca/models/account_journal.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_facturae/models/account_journal.py
  l10n_es_facturae/models/account_move.py
Labels: approved, bot is merging ⏳

#1961 [14.0][IMP] l10n_es_vat_book: Mejora de rendimiento
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#2095 [14.0][IMP] l10n_es_aeat_sii_oca + l10n_es_facturae: Hide thirdparty fields in some cases
  l10n_es_aeat_sii_oca/models/account_journal.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_facturae/models/account_journal.py
  l10n_es_facturae/models/account_move.py
Labels: bot is merging ⏳

#2067 [10.0][IMP]l10n_es_vat_book: Mejorar capacidad de herencias
  l10n_es_vat_book/models/aeat_vat_book_map_line.py
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#2066 [FIX]l10n_es_aeat_sii: Error con el campo amount_total
  l10n_es_aeat_sii/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2039 [11.0][FIX] Corregir importe de retención y totales en XML ticketbai
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
Labels: approved, bot is merging ⏳

#2102 [11.0][FIX] l10n_es_ticketbai_api - partner nacional con NIF empezando por N
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
Labels: bot is merging ⏳

#2106 [13.0][FIX] l10n_es_aeat_mod347: Proper invoice name
  l10n_es_aeat_mod347/views/report_347_partner.xml
Labels: bot is merging ⏳

#2099 [10.0][MIG]l10n_es_vat_book_oss
  l10n_es_vat_book_oss/README.rst
  l10n_es_vat_book_oss/__init__.py
  l10n_es_vat_book_oss/__manifest__.py
  l10n_es_vat_book_oss/i18n/l10n_es_vat_book_oss.pot
  l10n_es_vat_book_oss/models/__init__.py
  l10n_es_vat_book_oss/models/aeat_vat_book_map_lines.py
  l10n_es_vat_book_oss/models/l10n_es_vat_book.py
  l10n_es_vat_book_oss/readme/CONFIGURE.rst
  l10n_es_vat_book_oss/readme/CONTRIBUTORS.rst
  l10n_es_vat_book_oss/readme/DESCRIPTION.rst
  l10n_es_vat_book_oss/readme/INSTALL.rst
  l10n_es_vat_book_oss/readme/ROADMAP.rst
  l10n_es_vat_book_oss/readme/USAGE.rst
  l10n_es_vat_book_oss/static/description/icon.png
  l10n_es_vat_book_oss/static/description/index.html
Labels: approved, bot is merging ⏳

#1981 [15.0][MIG]l10n_es_aeat_sii_oss
  l10n_es_aeat_sii_oss/README.rst
  l10n_es_aeat_sii_oss/__init__.py
  l10n_es_aeat_sii_oss/__manifest__.py
  l10n_es_aeat_sii_oss/data/aeat_sii_mapping_registration_keys_data.xml
  l10n_es_aeat_sii_oss/i18n/l10n_es_aeat_sii_oss.pot
  l10n_es_aeat_sii_oss/models/__init__.py
  l10n_es_aeat_sii_oss/models/account_move.py
  l10n_es_aeat_sii_oss/readme/CONFIGURE.rst
  l10n_es_aeat_sii_oss/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_oss/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_oss/readme/INSTALL.rst
  l10n_es_aeat_sii_oss/static/description/icon.png
  l10n_es_aeat_sii_oss/static/description/icon_source.svg
  l10n_es_aeat_sii_oss/static/description/index.html
  l10n_es_aeat_sii_oss/tests/__init__.py
  l10n_es_aeat_sii_oss/tests/test_l10n_es_aeat_sii.py
  oca_dependencies.txt
  setup/l10n_es_aeat_sii_oss/odoo/addons/l10n_es_aeat_sii_oss
  setup/l10n_es_aeat_sii_oss/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2107 [13.0][FIX] l10n_es_ticketbai_api y l10n_es_ticketbai: Corregir importe de retenc…
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
Labels: bot is merging ⏳

#2108 [12.0][FIX] l10n_es_ticketbai_api - partner nacional con NIF empezando por N
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
Labels: bot is merging ⏳

#2109 [14.0][FIX] l10n_es_ticketbai_api y l10n_es_ticketbai: Corregir importe de …
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
Labels: bot is merging ⏳

#2111 [14.0][FIX] l10n_es_ticketbai_api - partner nacional con NIF empezando por N
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
Labels: bot is merging ⏳

#2083 [12.0][IMP] l10n_es_ticketbai_api: multi-company rule for ticketbai invoices
  l10n_es_ticketbai_api/__manifest__.py
  l10n_es_ticketbai_api/i18n/es.po
  l10n_es_ticketbai_api/i18n/l10n_es_ticketbai_api.pot
  l10n_es_ticketbai_api/models/res_company.py
  l10n_es_ticketbai_api/security/l10n_es_ticketbai_security.xml
Labels: bot is merging ⏳

#2040 [15.0] [MIG] l10n_es_mis_report
  l10n_es_mis_report/README.rst
  l10n_es_mis_report/__init__.py
  l10n_es_mis_report/__manifest__.py
  l10n_es_mis_report/data/mis_report_balance_abreviated.xml
  l10n_es_mis_report/data/mis_report_balance_normal.xml
  l10n_es_mis_report/data/mis_report_balance_sme.xml
  l10n_es_mis_report/data/mis_report_balance_sme_sfl.xml
  l10n_es_mis_report/data/mis_report_pyg_abreviated.xml
  l10n_es_mis_report/data/mis_report_pyg_normal.xml
  l10n_es_mis_report/data/mis_report_pyg_sme.xml
  l10n_es_mis_report/data/mis_report_pyg_sme_sfl.xml
  l10n_es_mis_report/data/mis_report_revenues_expenses_normal.xml
  l10n_es_mis_report/data/mis_report_styles.xml
  l10n_es_mis_report/i18n/ca.po
  l10n_es_mis_report/i18n/es.po
  l10n_es_mis_report/i18n/l10n_es_mis_report.pot
  l10n_es_mis_report/readme/DESCRIPTION.rst
  l10n_es_mis_report/readme/INSTALL.rst
  l10n_es_mis_report/readme/USAGE.rst
  l10n_es_mis_report/static/description/icon.png
  l10n_es_mis_report/static/description/index.html
  setup/l10n_es_mis_report/odoo/addons/l10n_es_mis_report
  setup/l10n_es_mis_report/setup.py
Labels: approved, bot is merging ⏳

#2114 [11.0][FIX] l10n_es_ticketbai_api_batuz: Usar fecha contable para calcular …
  l10n_es_ticketbai_api_batuz/models/lroe_operation.py
Labels: approved, bot is merging ⏳

#2118 [13.0][IMP] delivery_gls_asm: master data and requiered info
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/models/gls_asm_master_data.py
  delivery_gls_asm/models/gls_asm_request.py
Labels: bot is merging ⏳

#2123 [12.0][FIX] l10n_es_aeat_mod347: Preserve balance sign on partner move records
  l10n_es_aeat_mod347/__manifest__.py
  l10n_es_aeat_mod347/data/aeat_export_mod347_partner_data.xml
  l10n_es_aeat_mod347/migrations/12.0.2.0.0/pre-migration.py
  l10n_es_aeat_mod347/models/mod347.py
  l10n_es_aeat_mod347/tests/test_l10n_es_aeat_mod347.py
  l10n_es_aeat_mod347/views/mod347_view.xml
  l10n_es_aeat_mod347/views/report_347_partner.xml
Labels: bot is merging ⏳

#2127 [13.0] l10n_es_aeat_mod303: Nuevo formato BOE 2022
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2021-07/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/docs/303_register_design_e15v32.xlsx
  l10n_es_aeat_mod303/docs/DR303e15v34.xlsx
  l10n_es_aeat_mod303/docs/DR303e17v20_04.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_00.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_40.xlsx
  l10n_es_aeat_mod303/docs/DR303e22.xlsx
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: bot is merging ⏳

#2128 [11.0] l10n_es_aeat_mod303: Nuevo formato BOE 2022
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2021-07/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/docs/303_register_design_e15v32.xlsx
  l10n_es_aeat_mod303/docs/DR303e15v34.xlsx
  l10n_es_aeat_mod303/docs/DR303e17v20_04.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_00.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_40.xlsx
  l10n_es_aeat_mod303/docs/DR303e22.xlsx
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: bot is merging ⏳

#2056 [15.0][MIG] l10n_es_aeat_partner_check: Standard migration
  l10n_es_aeat_partner_check/README.rst
  l10n_es_aeat_partner_check/__init__.py
  l10n_es_aeat_partner_check/__manifest__.py
  l10n_es_aeat_partner_check/i18n/ca.po
  l10n_es_aeat_partner_check/i18n/es.po
  l10n_es_aeat_partner_check/i18n/l10n_es_aeat_partner_check.pot
  l10n_es_aeat_partner_check/models/__init__.py
  l10n_es_aeat_partner_check/models/res_company.py
  l10n_es_aeat_partner_check/models/res_config_settings.py
  l10n_es_aeat_partner_check/models/res_partner.py
  l10n_es_aeat_partner_check/readme/CONTRIBUTORS.rst
  l10n_es_aeat_partner_check/readme/DESCRIPTION.rst
  l10n_es_aeat_partner_check/readme/INSTALL.rst
  l10n_es_aeat_partner_check/readme/USAGE.rst
  l10n_es_aeat_partner_check/static/description/icon.png
  l10n_es_aeat_partner_check/static/description/index.html
  l10n_es_aeat_partner_check/tests/__init__.py
  l10n_es_aeat_partner_check/tests/test_res_partner.py
  l10n_es_aeat_partner_check/views/res_company_view.xml
  l10n_es_aeat_partner_check/views/res_config_settings_view.xml
  l10n_es_aeat_partner_check/views/res_partner_view.xml
  setup/l10n_es_aeat_partner_check/odoo/addons/l10n_es_aeat_partner_check
  setup/l10n_es_aeat_partner_check/setup.py
Labels: bot is merging ⏳

#2126 [13.0][FIX] l10n_es_intrastat_report: Actualizar el link a los códigos
  l10n_es_intrastat_report/README.rst
  l10n_es_intrastat_report/readme/INSTALL.rst
  l10n_es_intrastat_report/static/description/index.html
Labels: bot is merging ⏳

#2129 Set the standar name for all AEAT modules
  l10n_es_aeat_mod349/__manifest__.py
Labels: bot is merging ⏳

#2132 [15.0][l10n_es_aeat_mod349] Set the standar name for all AEAT modules
  l10n_es_aeat_mod349/__manifest__.py
Labels: bot is merging ⏳

#2133 [14.0][FIX] l10n_es_intrastat_report: Actualizar el link a los códigos
  l10n_es_intrastat_report/README.rst
  l10n_es_intrastat_report/readme/INSTALL.rst
  l10n_es_intrastat_report/static/description/index.html
Labels: bot is merging ⏳

#2135 [FIX] delivery_seur: label filename
  delivery_seur/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#2131 [14.0]l10n_es_aeat_partner_check: aeat_partner_vat string update
  l10n_es_aeat_partner_check/models/res_partner.py
Labels: approved

#2116 [15.0][MIG] l10n_es_aeat_mod123: Migration to 15.0
  l10n_es_aeat_mod123/README.rst
  l10n_es_aeat_mod123/__init__.py
  l10n_es_aeat_mod123/__manifest__.py
  l10n_es_aeat_mod123/data/aeat_export_mod123_data.xml
  l10n_es_aeat_mod123/data/tax_code_map_mod123.xml
  l10n_es_aeat_mod123/i18n/bg.po
  l10n_es_aeat_mod123/i18n/ca.po
  l10n_es_aeat_mod123/i18n/cs.po
  l10n_es_aeat_mod123/i18n/de.po
  l10n_es_aeat_mod123/i18n/es.po
  l10n_es_aeat_mod123/i18n/es_CO.po
  l10n_es_aeat_mod123/i18n/es_CR.po
  l10n_es_aeat_mod123/i18n/es_ES.po
  l10n_es_aeat_mod123/i18n/eu.po
  l10n_es_aeat_mod123/i18n/fr.po
  l10n_es_aeat_mod123/i18n/gl.po
  l10n_es_aeat_mod123/i18n/hr.po
  l10n_es_aeat_mod123/i18n/l10n_es_aeat_mod123.pot
  l10n_es_aeat_mod123/i18n/nl.po
  l10n_es_aeat_mod123/i18n/pl.po
  l10n_es_aeat_mod123/i18n/pt.po
  l10n_es_aeat_mod123/i18n/pt_BR.po
  l10n_es_aeat_mod123/i18n/sl.po
  l10n_es_aeat_mod123/i18n/sv.po
  l10n_es_aeat_mod123/i18n/tr.po
  l10n_es_aeat_mod123/i18n/vi.po
  l10n_es_aeat_mod123/models/__init__.py
  l10n_es_aeat_mod123/models/mod123.py
  l10n_es_aeat_mod123/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod123/readme/DESCRIPTION.rst
  l10n_es_aeat_mod123/readme/USAGE.rst
  l10n_es_aeat_mod123/security/ir.model.access.csv
  l10n_es_aeat_mod123/security/mod_123_security.xml
  l10n_es_aeat_mod123/static/description/icon.png
  l10n_es_aeat_mod123/static/description/icon_source.svg
  l10n_es_aeat_mod123/static/description/index.html
  l10n_es_aeat_mod123/tests/__init__.py
  l10n_es_aeat_mod123/tests/test_l10n_es_aeat_mod123.py
  l10n_es_aeat_mod123/views/mod123_view.xml
  setup/l10n_es_aeat_mod123/odoo/addons/l10n_es_aeat_mod123
  setup/l10n_es_aeat_mod123/setup.py
Labels: bot is merging ⏳

#2113 [13.0][IMP] l10n_es_ticketbai_api: multi-company rule for ticketbai invoices
  l10n_es_ticketbai_api/__manifest__.py
  l10n_es_ticketbai_api/migrations/13.0.1.5.0/noupdate_changes.xml
  l10n_es_ticketbai_api/migrations/13.0.1.5.0/post-migration.py
  l10n_es_ticketbai_api/models/res_company.py
  l10n_es_ticketbai_api/security/l10n_es_ticketbai_security.xml
Labels: bot is merging ⏳

#2139 [14.0][IMP] l10n_es_ticketbai_api: multi-company rule for ticketbai invoices
  l10n_es_ticketbai_api/models/res_company.py
  l10n_es_ticketbai_api/security/l10n_es_ticketbai_security.xml
Labels: bot is merging ⏳

#2070 [15.0][MIG] l10n_es_account_statement_import_n43
  l10n_es_account_statement_import_n43/README.rst
  l10n_es_account_statement_import_n43/__init__.py
  l10n_es_account_statement_import_n43/__manifest__.py
  l10n_es_account_statement_import_n43/doc/norma_43_castellano.pdf
  l10n_es_account_statement_import_n43/i18n/ca.po
  l10n_es_account_statement_import_n43/i18n/es.po
  l10n_es_account_statement_import_n43/i18n/eu.po
  l10n_es_account_statement_import_n43/i18n/fr.po
  l10n_es_account_statement_import_n43/i18n/gl.po
  l10n_es_account_statement_import_n43/i18n/l10n_es_account_bank_statement_import_n43.pot
  l10n_es_account_statement_import_n43/i18n/l10n_es_account_statement_import_n43.pot
  l10n_es_account_statement_import_n43/i18n/sl.po
  l10n_es_account_statement_import_n43/models/__init__.py
  l10n_es_account_statement_import_n43/models/account_journal.py
  l10n_es_account_statement_import_n43/readme/CONTRIBUTORS.rst
  l10n_es_account_statement_import_n43/readme/DESCRIPTION.rst
  l10n_es_account_statement_import_n43/readme/ROADMAP.rst
  l10n_es_account_statement_import_n43/readme/USAGE.rst
  l10n_es_account_statement_import_n43/static/description/icon.png
  l10n_es_account_statement_import_n43/static/description/icon_src.svg
  l10n_es_account_statement_import_n43/static/description/index.html
  l10n_es_account_statement_import_n43/tests/__init__.py
  l10n_es_account_statement_import_n43/tests/test.n43
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
  l10n_es_account_statement_import_n43/views/account_journal_views.xml
  l10n_es_account_statement_import_n43/wizards/__init__.py
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
  l10n_es_account_statement_import_n43/wizards/account_statement_import_view.xml
  requirements.txt
  setup/l10n_es_account_statement_import_n43/odoo/addons/l10n_es_account_statement_import_n43
  setup/l10n_es_account_statement_import_n43/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2053 [15.0][MIG] l10n_es_aeat_mod347
  l10n_es_aeat_mod347/README.rst
  l10n_es_aeat_mod347/__init__.py
  l10n_es_aeat_mod347/__manifest__.py
  l10n_es_aeat_mod347/controllers/__init__.py
  l10n_es_aeat_mod347/controllers/main.py
  l10n_es_aeat_mod347/data/aeat_export_mod347_data.xml
  l10n_es_aeat_mod347/data/aeat_export_mod347_partner_data.xml
  l10n_es_aeat_mod347/data/aeat_export_mod347_real_state_data.xml
  l10n_es_aeat_mod347/data/mail_template_data.xml
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
  l10n_es_aeat_mod347/docs/347_register_design.pdf
  l10n_es_aeat_mod347/i18n/bg.po
  l10n_es_aeat_mod347/i18n/ca.po
  l10n_es_aeat_mod347/i18n/cs.po
  l10n_es_aeat_mod347/i18n/es.po
  l10n_es_aeat_mod347/i18n/es_CO.po
  l10n_es_aeat_mod347/i18n/es_CR.po
  l10n_es_aeat_mod347/i18n/eu.po
  l10n_es_aeat_mod347/i18n/fr.po
  l10n_es_aeat_mod347/i18n/gl.po
  l10n_es_aeat_mod347/i18n/hr.po
  l10n_es_aeat_mod347/i18n/l10n_es_aeat_mod347.pot
  l10n_es_aeat_mod347/i18n/nl.po
  l10n_es_aeat_mod347/i18n/pl.po
  l10n_es_aeat_mod347/i18n/pt.po
  l10n_es_aeat_mod347/i18n/pt_BR.po
  l10n_es_aeat_mod347/i18n/ru.po
  l10n_es_aeat_mod347/i18n/sl.po
  l10n_es_aeat_mod347/i18n/sv.po
  l10n_es_aeat_mod347/i18n/tr.po
  l10n_es_aeat_mod347/i18n/vi.po
  l10n_es_aeat_mod347/images/l10n_es_aeat_mod347.png
  l10n_es_aeat_mod347/migrations/14.0.2.0.0/pre-migration.py
  l10n_es_aeat_mod347/models/__init__.py
  l10n_es_aeat_mod347/models/account_move.py
  l10n_es_aeat_mod347/models/mod347.py
  l10n_es_aeat_mod347/models/res_partner.py
  l10n_es_aeat_mod347/readme/CONFIG.rst
  l10n_es_aeat_mod347/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod347/readme/DESCRIPTION.rst
  l10n_es_aeat_mod347/readme/INSTALL.rst
  l10n_es_aeat_mod347/readme/ROADMAP.rst
  l10n_es_aeat_mod347/readme/USAGE.rst
  l10n_es_aeat_mod347/security/ir.model.access.csv
  l10n_es_aeat_mod347/security/mod_347_security.xml
  l10n_es_aeat_mod347/static/description/icon.png
  l10n_es_aeat_mod347/static/description/icon_source.svg
  l10n_es_aeat_mod347/static/description/index.html
  l10n_es_aeat_mod347/static/src/img/347_bad.svg
  l10n_es_aeat_mod347/static/src/img/347_ok.svg
  l10n_es_aeat_mod347/tests/__init__.py
  l10n_es_aeat_mod347/tests/test_l10n_es_aeat_mod347.py
  l10n_es_aeat_mod347/views/account_move_view.xml
  l10n_es_aeat_mod347/views/mod347_templates.xml
  l10n_es_aeat_mod347/views/mod347_view.xml
  l10n_es_aeat_mod347/views/report_347_partner.xml
  l10n_es_aeat_mod347/views/res_partner_view.xml
  setup/l10n_es_aeat_mod347/odoo/addons/l10n_es_aeat_mod347
  setup/l10n_es_aeat_mod347/setup.py
Labels: bot is merging ⏳

#2080 [15.0] [MIG] l10n_es_aeat_mod115
  l10n_es_aeat_mod115/README.rst
  l10n_es_aeat_mod115/__init__.py
  l10n_es_aeat_mod115/__manifest__.py
  l10n_es_aeat_mod115/data/aeat_export_mod115_data.xml
  l10n_es_aeat_mod115/data/tax_code_map_mod115_data.xml
  l10n_es_aeat_mod115/docs/DR115e15v11.xls
  l10n_es_aeat_mod115/i18n/bg.po
  l10n_es_aeat_mod115/i18n/ca.po
  l10n_es_aeat_mod115/i18n/cs.po
  l10n_es_aeat_mod115/i18n/es.po
  l10n_es_aeat_mod115/i18n/es_CO.po
  l10n_es_aeat_mod115/i18n/es_CR.po
  l10n_es_aeat_mod115/i18n/eu.po
  l10n_es_aeat_mod115/i18n/fr.po
  l10n_es_aeat_mod115/i18n/gl.po
  l10n_es_aeat_mod115/i18n/hr.po
  l10n_es_aeat_mod115/i18n/l10n_es_aeat_mod115.pot
  l10n_es_aeat_mod115/i18n/nl.po
  l10n_es_aeat_mod115/i18n/pl.po
  l10n_es_aeat_mod115/i18n/pt.po
  l10n_es_aeat_mod115/i18n/pt_BR.po
  l10n_es_aeat_mod115/i18n/ru.po
  l10n_es_aeat_mod115/i18n/sl.po
  l10n_es_aeat_mod115/i18n/sv.po
  l10n_es_aeat_mod115/i18n/tr.po
  l10n_es_aeat_mod115/i18n/vi.po
  l10n_es_aeat_mod115/models/__init__.py
  l10n_es_aeat_mod115/models/mod115.py
  l10n_es_aeat_mod115/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod115/readme/DESCRIPTION.rst
  l10n_es_aeat_mod115/readme/USAGE.rst
  l10n_es_aeat_mod115/security/ir.model.access.csv
  l10n_es_aeat_mod115/security/l10n_es_aeat_mod115_security.xml
  l10n_es_aeat_mod115/static/description/icon.png
  l10n_es_aeat_mod115/static/description/icon_source.svg
  l10n_es_aeat_mod115/static/description/index.html
  l10n_es_aeat_mod115/tests/__init__.py
  l10n_es_aeat_mod115/tests/test_l10n_es_aeat_mod115.py
  l10n_es_aeat_mod115/views/mod115_view.xml
  setup/l10n_es_aeat_mod115/odoo/addons/l10n_es_aeat_mod115
  setup/l10n_es_aeat_mod115/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2101 [12.0][IMP] l10n_es_intrastat_report: Add to notes when missing partner_vat and missing product_origin_country_id in line.
  l10n_es_intrastat_report/i18n/es.po
  l10n_es_intrastat_report/i18n/l10n_es_intrastat_report.pot
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
Labels: approved, bot is merging ⏳

#2120 [11.0][FIX] l10n_es_ticketbai_batuz - clave CuotaIVADeducible en capítulo 2
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai_api_batuz/models/lroe_operation.py
  l10n_es_ticketbai_batuz/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2121 [FIX] 11.0 l10n_es_ticketbai no dejar validar facturas rectificativas sin datos de rectificación
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/views/account_invoice_views.xml
Labels: approved, bot is merging ⏳

#2144 [10.0][MIG]l10n_es_aeat_sii_oss
  l10n_es_aeat_sii_oss/README.rst
  l10n_es_aeat_sii_oss/__init__.py
  l10n_es_aeat_sii_oss/__manifest__.py
  l10n_es_aeat_sii_oss/data/aeat_sii_mapping_registration_keys_data.xml
  l10n_es_aeat_sii_oss/i18n/l10n_es_aeat_sii_oss.pot
  l10n_es_aeat_sii_oss/models/__init__.py
  l10n_es_aeat_sii_oss/models/account_invoice.py
  l10n_es_aeat_sii_oss/readme/CONFIGURE.rst
  l10n_es_aeat_sii_oss/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_oss/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_oss/readme/INSTALL.rst
  l10n_es_aeat_sii_oss/static/description/icon.png
  l10n_es_aeat_sii_oss/static/description/icon_source.svg
  l10n_es_aeat_sii_oss/static/description/index.html
  l10n_es_aeat_sii_oss/tests/__init__.py
  l10n_es_aeat_sii_oss/tests/test_l10n_es_aeat_sii.py
Labels: approved, bot is merging ⏳

#2147 [12.0][FIX] l10n_es_ticketbai: no dejar validar facturas rectificativas sin…
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/views/account_invoice_views.xml
Labels: bot is merging ⏳

#2049 [13.0][IMP] ecoembes: Añadir campos de ecoembes a nivel de plantilla de producto
  ecoembes/__manifest__.py
  ecoembes/models/__init__.py
  ecoembes/models/product_composition.py
  ecoembes/models/product_template.py
  ecoembes/tests/test_ecoembes_misc.py
  ecoembes/views/menu.xml
  ecoembes/views/product_composition_view.xml
  ecoembes/views/product_template_view.xml
Labels: bot is merging ⏳

#2148 [14.0][IMP] l10n_es_intrastat_report: Add to notes when missing partner_vat and missing product_origin_country_id in line.
  l10n_es_intrastat_report/i18n/es.po
  l10n_es_intrastat_report/i18n/l10n_es_intrastat_report.pot
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
  l10n_es_intrastat_report/tests/test_l10n_es_intrastat_report.py
Labels: approved, bot is merging ⏳

#2155 [FIX] l10n_es_aeat_sii_oca: Duplicated third party fields
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_facturae/models/account_move.py
Labels: bot is merging ⏳

#2156 [14.0][FIX] l10n_es_ticketbai: no dejar validar facturas rectificativas sin…
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/views/account_move_views.xml
Labels: bot is merging ⏳

#2153 [11.0][FIX] l10n_es_ticketbai_batuz: no dejar validar facturas rectificativ…
  l10n_es_ticketbai_batuz/views/account_invoice_views.xml
Labels: approved, bot is merging ⏳

#2161 [14.0][UPD] l10n_es_aeat_mod349: Eficent -> ForgeFlow
  l10n_es_aeat_mod349/__manifest__.py
  l10n_es_aeat_mod349/models/account_move.py
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod349/static/description/index.html
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
Labels: bot is merging ⏳

#2162 [15.0][UPD] l10n_es_aeat_mod349: Eficent -> ForgeFlow
  l10n_es_aeat_mod349/__manifest__.py
  l10n_es_aeat_mod349/models/account_move.py
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod349/static/description/index.html
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
Labels: bot is merging ⏳

#2157 [15.0][IMP] l10n_es_aeat_sii_oca: Remove required condition in reference field from invoices.
  l10n_es_aeat_sii_oca/views/account_move_views.xml
Labels: bot is merging ⏳

#2158 [14.0][IMP] l10n_es_aeat_sii_oca: Remove required condition in reference field from invoices.
  l10n_es_aeat_sii_oca/views/account_move_views.xml
Labels: bot is merging ⏳

#2159 [12.0][IMP] l10n_es_ticketbai: especificar tipo de facturas que no se puede…
  l10n_es_ticketbai/models/account_invoice.py
Labels: bot is merging ⏳

#2163 [13.0][IMP] l10n_es_ticketbai: especificar tipo de facturas que no se puede…
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#2164 [14.0][IMP] l10n_es_ticketbai: especificar tipo de facturas que no se puede…
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#2165 [FIX] 11.0 l10n_es_ticketbai corregir signo del importe del descuento tbai en las líneas de las facturas rectificadass
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2166 [12.0][FIX] l10n_es_ticketbai: corregir signo del importe del descuento tba…
  l10n_es_ticketbai/models/account_invoice.py
Labels: bot is merging ⏳

#2002 [11.0][ADD] l10n_es_dua_ticketbai_batuz module
  l10n_es_dua_ticketbai_batuz/README.rst
  l10n_es_dua_ticketbai_batuz/__init__.py
  l10n_es_dua_ticketbai_batuz/__manifest__.py
  l10n_es_dua_ticketbai_batuz/data/account_fiscal_position_template_data.xml
  l10n_es_dua_ticketbai_batuz/data/tax_code_map_dua_ticketbai_data.xml
  l10n_es_dua_ticketbai_batuz/models/__init__.py
  l10n_es_dua_ticketbai_batuz/models/account_invoice.py
  l10n_es_dua_ticketbai_batuz/readme/CONFIGURATION.rst
  l10n_es_dua_ticketbai_batuz/readme/CONTRIBUTORS.rst
  l10n_es_dua_ticketbai_batuz/readme/DESCRIPTION.rst
  l10n_es_dua_ticketbai_batuz/readme/USAGE.rst
Labels: approved, bot is merging ⏳
