Repository OCA/l10n-spain, pull requests merged in 2022-11, with the labels that each got.

#2578 [15.0][FIX] l10n_es_aeat_mod349: Set the date field to store=True to allow the records to be sorted.
  l10n_es_aeat_mod349/models/mod349.py
Labels: approved, bot is merging ⏳

#2460 [MIG] l10n_es_dua_ticketbai_batuz: Migration to 15.0
  l10n_es_dua_ticketbai_batuz/README.rst
  l10n_es_dua_ticketbai_batuz/__init__.py
  l10n_es_dua_ticketbai_batuz/__manifest__.py
  l10n_es_dua_ticketbai_batuz/data/account_fiscal_position_template_data.xml
  l10n_es_dua_ticketbai_batuz/data/tax_code_map_dua_ticketbai_data.xml
  l10n_es_dua_ticketbai_batuz/i18n/l10n_es_dua_ticketbai_batuz.pot
  l10n_es_dua_ticketbai_batuz/models/__init__.py
  l10n_es_dua_ticketbai_batuz/models/account_move.py
  l10n_es_dua_ticketbai_batuz/readme/CONFIGURATION.rst
  l10n_es_dua_ticketbai_batuz/readme/CONTRIBUTORS.rst
  l10n_es_dua_ticketbai_batuz/readme/DESCRIPTION.rst
  l10n_es_dua_ticketbai_batuz/readme/USAGE.rst
  l10n_es_dua_ticketbai_batuz/static/description/icon.png
  l10n_es_dua_ticketbai_batuz/static/description/index.html
  setup/l10n_es_dua_ticketbai_batuz/odoo/addons/l10n_es_dua_ticketbai_batuz
  setup/l10n_es_dua_ticketbai_batuz/setup.py
Labels: approved, bot is merging ⏳

#2583 [FIX] l10n_es_aeat: do not require administration permissions
  l10n_es_aeat/models/l10n_es_aeat_report.py
Labels: bot is merging ⏳

#2589 [IMP] l10n_es_irnr: Promote to Mature
  l10n_es_irnr/__manifest__.py
Labels: approved, bot is merging ⏳

#2587 [14.0][MIG] l10n es aeat mod216: Migration to 14.0
  l10n_es_aeat_mod216/README.rst
  l10n_es_aeat_mod216/__init__.py
  l10n_es_aeat_mod216/__manifest__.py
  l10n_es_aeat_mod216/data/aeat_export_mod216_data.xml
  l10n_es_aeat_mod216/data/tax_code_map_mod216_data.xml
  l10n_es_aeat_mod216/docs/DR-216e16_v1.06.pdf
  l10n_es_aeat_mod216/i18n/bg.po
  l10n_es_aeat_mod216/i18n/ca.po
  l10n_es_aeat_mod216/i18n/cs.po
  l10n_es_aeat_mod216/i18n/de.po
  l10n_es_aeat_mod216/i18n/es.po
  l10n_es_aeat_mod216/i18n/es_CO.po
  l10n_es_aeat_mod216/i18n/es_CR.po
  l10n_es_aeat_mod216/i18n/es_ES.po
  l10n_es_aeat_mod216/i18n/eu.po
  l10n_es_aeat_mod216/i18n/fr.po
  l10n_es_aeat_mod216/i18n/gl.po
  l10n_es_aeat_mod216/i18n/hr.po
  l10n_es_aeat_mod216/i18n/l10n_es_aeat_mod216.pot
  l10n_es_aeat_mod216/i18n/nl.po
  l10n_es_aeat_mod216/i18n/pl.po
  l10n_es_aeat_mod216/i18n/pt.po
  l10n_es_aeat_mod216/i18n/pt_BR.po
  l10n_es_aeat_mod216/i18n/ru.po
  l10n_es_aeat_mod216/i18n/sl.po
  l10n_es_aeat_mod216/i18n/sv.po
  l10n_es_aeat_mod216/i18n/tr.po
  l10n_es_aeat_mod216/i18n/vi.po
  l10n_es_aeat_mod216/models/__init__.py
  l10n_es_aeat_mod216/models/mod216.py
  l10n_es_aeat_mod216/readme/CONFIGURE.rst
  l10n_es_aeat_mod216/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod216/readme/DESCRIPTION.rst
  l10n_es_aeat_mod216/readme/USAGE.rst
  l10n_es_aeat_mod216/security/ir.model.access.csv
  l10n_es_aeat_mod216/security/ir_rule.xml
  l10n_es_aeat_mod216/static/description/icon.png
  l10n_es_aeat_mod216/static/description/icon_source.svg
  l10n_es_aeat_mod216/static/description/index.html
  l10n_es_aeat_mod216/tests/__init__.py
  l10n_es_aeat_mod216/tests/test_l10n_es_aeat_mod216.py
  l10n_es_aeat_mod216/views/mod216_view.xml
  setup/l10n_es_aeat_mod216/odoo/addons/l10n_es_aeat_mod216
  setup/l10n_es_aeat_mod216/setup.py
Labels: bot is merging ⏳

#2130 [15.0] l10n_es_aeat_partner_check: Update aeat_partner_vat string: AEAT VAT
  l10n_es_aeat_partner_check/i18n/ca.po
  l10n_es_aeat_partner_check/i18n/es.po
  l10n_es_aeat_partner_check/i18n/l10n_es_aeat_partner_check.pot
  l10n_es_aeat_partner_check/models/res_partner.py
Labels: approved, bot is merging ⏳, stale

#2588 [14.0][MIG] l10n_es_vat_prorate
  l10n_es_vat_prorate/README.rst
  l10n_es_vat_prorate/__init__.py
  l10n_es_vat_prorate/__manifest__.py
  l10n_es_vat_prorate/data/account_template_tax.xml
  l10n_es_vat_prorate/models/__init__.py
  l10n_es_vat_prorate/models/account_move.py
  l10n_es_vat_prorate/models/account_tax.py
  l10n_es_vat_prorate/models/res_company.py
  l10n_es_vat_prorate/readme/CONFIGURE.rst
  l10n_es_vat_prorate/readme/CONTRIBUTORS.rst
  l10n_es_vat_prorate/readme/DESCRIPTION.rst
  l10n_es_vat_prorate/security/ir.model.access.csv
  l10n_es_vat_prorate/static/description/icon.png
  l10n_es_vat_prorate/static/description/index.html
  l10n_es_vat_prorate/tests/__init__.py
  l10n_es_vat_prorate/tests/test_vat_prorate.py
  l10n_es_vat_prorate/views/account_move_views.xml
  l10n_es_vat_prorate/views/account_tax_views.xml
  l10n_es_vat_prorate/views/res_company_prorate_views.xml
  l10n_es_vat_prorate/views/res_company_views.xml
  setup/l10n_es_vat_prorate/odoo/addons/l10n_es_vat_prorate
  setup/l10n_es_vat_prorate/setup.py
Labels: approved, bot is merging ⏳

#2566 [14.0][ADD] delivery_mrw
  delivery_mrw/README.rst
  delivery_mrw/__init__.py
  delivery_mrw/__manifest__.py
  delivery_mrw/api/mrw-api-tracking-prod.wsdl
  delivery_mrw/api/mrw_api.xml
  delivery_mrw/data/delivery_mrw.xml
  delivery_mrw/i18n/delivery_mrw.pot
  delivery_mrw/i18n/es.po
  delivery_mrw/models/__init__.py
  delivery_mrw/models/delivery_carrier.py
  delivery_mrw/models/mrw_request.py
  delivery_mrw/models/stock_picking.py
  delivery_mrw/readme/CONFIGURE.rst
  delivery_mrw/readme/CONTRIBUTORS.rst
  delivery_mrw/readme/DESCRIPTION.rst
  delivery_mrw/readme/INSTALL.rst
  delivery_mrw/readme/ROADMAP.rst
  delivery_mrw/readme/USAGE.rst
  delivery_mrw/security/ir.model.access.csv
  delivery_mrw/static/description/icon.jpg
  delivery_mrw/static/description/index.html
  delivery_mrw/tests/__init__.py
  delivery_mrw/tests/test_delivery_mrw.py
  delivery_mrw/views/delivery_mrw_view.xml
  delivery_mrw/views/mrw_manifest_template.xml
  delivery_mrw/views/stock_picking_views.xml
  delivery_mrw/wizard/__init__.py
  delivery_mrw/wizard/mrw_manifest_wizard.py
  delivery_mrw/wizard/mrw_manifest_wizard_views.xml
  delivery_mrw/wizard/stock_immediate_transfer_views.xml
  delivery_mrw/wizard/stock_inmediate_transfer.py
  setup/delivery_mrw/odoo/addons/delivery_mrw
  setup/delivery_mrw/setup.py
Labels: approved, bot is merging ⏳

#2595 [14.0][FIX] Avoid override of function passing it to l10n_es_aeat: Ticketbai / SII.
  l10n_es_aeat/models/__init__.py
  l10n_es_aeat/models/account_move.py
  l10n_es_aeat/tests/__init__.py
  l10n_es_aeat/tests/test_l10n_es_aeat_taxinfo.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_dua_ticketbai_batuz/models/account_move.py
  l10n_es_ticketbai_batuz/models/account_move.py
Labels: approved, bot is merging ⏳

#2600 [11.0][FIX] l10n_es_aeat_sii: actualizar url de WSDLs
  l10n_es_aeat_sii/data/aeat_sii_tax_agency_data.xml
Labels: bot is merging ⏳

#2603 [13.0][FIX] l10n_es_intrastat_report: Set the correct country code in csv file.
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
Labels: approved, bot is merging ⏳

#2605 [14.0][FIX] l10n_es_intrastat_report: Set the correct country code in csv file.
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
Labels: bot is merging ⏳

#2606 [15.0][FIX] l10n_es_intrastat_report: Set the correct country code in csv file.
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
Labels: approved, bot is merging ⏳

#2608 [14.0][IMP] l10n_es_aeat: Hook for deprecated method
  l10n_es_aeat/models/account_move.py
Labels: bot is merging ⏳

#2540 [15.0][MIG] delivery_seur: Migration to 15.0
  delivery_seur/README.rst
  delivery_seur/__init__.py
  delivery_seur/__manifest__.py
  delivery_seur/doc/SEUR_Track_and_Tracing_Webservice.doc
  delivery_seur/doc/Servicios_WEB_Seur.doc
  delivery_seur/doc/WS_Cancelation_and_Modification_shipments_webservice.doc
  delivery_seur/doc/WebServices_Integration_Process_ENG_PDF.docx
  delivery_seur/doc/WebServices_Integration_Process_ENG_ZEBRA.docx
  delivery_seur/i18n/ca.po
  delivery_seur/i18n/delivery_seur.pot
  delivery_seur/i18n/es.po
  delivery_seur/models/__init__.py
  delivery_seur/models/delivery_carrier.py
  delivery_seur/models/seur_request.py
  delivery_seur/readme/CONTRIBUTORS.rst
  delivery_seur/readme/DESCRIPTION.rst
  delivery_seur/readme/USAGE.rst
  delivery_seur/static/description/icon.png
  delivery_seur/static/description/index.html
  delivery_seur/tests/__init__.py
  delivery_seur/tests/test_delivery_seur.py
  delivery_seur/views/delivery_carrier_views.xml
  setup/delivery_seur/odoo/addons/delivery_seur
  setup/delivery_seur/setup.py
Labels: approved, bot is merging ⏳

#2567 [12.0][FIX][l10n_es_facturae]Fix bank account required
  l10n_es_facturae/models/account_invoice.py
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#2607 [FIX] [15.0] l10n_es_aeat_sii_oca, l10n_es_facturae: remove fields view get account journal
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat/models/__init__.py
  l10n_es_aeat/models/account_journal.py
  l10n_es_aeat/views/account_journal_view.xml
  l10n_es_aeat_sii_oca/__init__.py
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/models/__init__.py
  l10n_es_aeat_sii_oca/models/account_journal.py
  l10n_es_aeat_sii_oca/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_oca/views/account_journal_view.xml
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae/models/__init__.py
  l10n_es_facturae/models/account_journal.py
  l10n_es_facturae/readme/CONTRIBUTORS.rst
  l10n_es_facturae/views/account_journal_view.xml
Labels: approved, bot is merging ⏳

#2611 [14.0][IMP] l10n_es_payment_order_confirming_sabadell: Convertir float/int
  l10n_es_payment_order_confirming_sabadell/models/confirming_sabadell.py
Labels: approved, ready to merge, bot is merging ⏳

#2612 [15.0][IMP] l10n_es_ticketbai_api, l10n_es_ticketbai: R5 code support
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
Labels: approved, bot is merging ⏳

#2619 [14.0][FIX] l10n_es_aeat_sii_oca, l10n_es_facturae: remove fields view get account journal
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat/models/__init__.py
  l10n_es_aeat/models/account_journal.py
  l10n_es_aeat/models/account_move.py
  l10n_es_aeat/views/account_journal_view.xml
  l10n_es_aeat/views/account_move_view.xml
  l10n_es_aeat_sii_oca/__init__.py
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/models/__init__.py
  l10n_es_aeat_sii_oca/models/account_journal.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
  l10n_es_aeat_sii_oca/views/account_journal_view.xml
  l10n_es_aeat_sii_oca/views/account_move_views.xml
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae/models/__init__.py
  l10n_es_facturae/models/account_journal.py
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/readme/CONTRIBUTORS.rst
  l10n_es_facturae/tests/common.py
  l10n_es_facturae/views/account_journal_view.xml
  l10n_es_facturae/views/account_move_view.xml
Labels: bot is merging ⏳

#2593 [12.0][FIX] l10n_es_ticketbai: Send line price subtotal correctly
  l10n_es_ticketbai/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2628 [14.0] [FWP] l10n_es_aeat_sii_oca: EU VAT number requires country code
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: approved, bot is merging ⏳

#2629 [15.0] [FWP] l10n_es_aeat_sii_oca: EU VAT number requires country code
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: approved, bot is merging ⏳

#2581 [11.0][FIX] l10n_es_ticketbai: Assign sign to re tax amount
  l10n_es_ticketbai/models/account_invoice_tax.py
Labels: approved, ready to merge, bot is merging ⏳

#2634 [12.0][FIX] l10n_es_ticketbai: Assign sign to re tax amount
  l10n_es_ticketbai/models/account_invoice_tax.py
Labels: bot is merging ⏳

#2630 [14.0][FIX] l10n_es_aeat_sii_oca & l10n_es_facturae: Old parent view is still being inherited
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/views/account_journal_view.xml
  l10n_es_aeat_sii_oca/views/account_move_views.xml
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae/readme/CONTRIBUTORS.rst
  l10n_es_facturae/views/account_journal_view.xml
  l10n_es_facturae/views/account_move_view.xml
Labels: bot is merging ⏳

#2635 [14.0] [REF] l10n_es_facturae_face: Quitar dependencia de webservice
  l10n_es_facturae_efact/__manifest__.py
  l10n_es_facturae_efact/tests/test_efact.py
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/components/__init__.py
  l10n_es_facturae_face/components/edi_send_l10n_es_facturae_face.py
  l10n_es_facturae_face/components/edi_send_l10n_es_facturae_face_cancel.py
  l10n_es_facturae_face/components/edi_webservice_receive_face_l10n_es_facturae_face_update.py
  l10n_es_facturae_face/components/webservice_face.py
  l10n_es_facturae_face/data/face_data.xml
  l10n_es_facturae_face/models/__init__.py
  l10n_es_facturae_face/models/edi_exchange_record.py
  l10n_es_facturae_face/models/webservice_backend.py
  l10n_es_facturae_face/tests/test_facturae_face.py
  requirements.txt
Labels: bot is merging ⏳

#2633 [OU] l10n_es_aeat_sii_oca: Fix migration
  l10n_es_aeat_sii_oca/migrations/14.0.1.0.0/pre-migrate.py
  l10n_es_aeat_sii_oca/migrations/14.0.2.1.0/post-migration.py
  l10n_es_aeat_sii_oca/migrations/14.0.2.1.0/pre-migration.py
Labels: approved

#2626 [15.0][IMP] l10n_es_ticketbai: Dynamic TicketBAI menu parent
  l10n_es_ticketbai/views/l10n_es_ticketbai_views.xml
Labels: bot is merging ⏳

#2302 [13.0][IMP] l10n_es_facturae_face: remove edi_webservice dependancy
  l10n_es_facturae_efact/tests/test_efact.py
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/components/__init__.py
  l10n_es_facturae_face/components/edi_send_l10n_es_facturae_face.py
  l10n_es_facturae_face/components/edi_send_l10n_es_facturae_face_cancel.py
  l10n_es_facturae_face/components/edi_webservice_receive_face_l10n_es_facturae_face_update.py
  l10n_es_facturae_face/components/webservice_face.py
  l10n_es_facturae_face/data/face_data.xml
  l10n_es_facturae_face/migrations/13.0.1.0.1/post-migration.py
  l10n_es_facturae_face/migrations/13.0.3.0.0/post-migration.py
  l10n_es_facturae_face/migrations/13.0.3.0.0/pre-migration.py
  l10n_es_facturae_face/models/__init__.py
  l10n_es_facturae_face/models/edi_exchange_record.py
  l10n_es_facturae_face/models/webservice_backend.py
  l10n_es_facturae_face/tests/test_facturae_face.py
Labels: bot is merging ⏳

#2625 [13.0][FIX] l10n_es_ticketbai: Send line price subtotal correctly
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#2636 [13.0][FIX] l10n_es_ticketbai: Assign sign to re tax amount
  l10n_es_ticketbai/models/account_tax.py
Labels: bot is merging ⏳

#2621 [15.0][FIX] l10n_es_aeat_sii_oca, l10n_es_facturae: remove fields view get account move
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat/models/__init__.py
  l10n_es_aeat/models/account_move.py
  l10n_es_aeat/views/account_move_view.xml
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
  l10n_es_aeat_sii_oca/views/account_journal_view.xml
  l10n_es_aeat_sii_oca/views/account_move_views.xml
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/tests/common.py
  l10n_es_facturae/views/account_journal_view.xml
  l10n_es_facturae/views/account_move_view.xml
Labels: bot is merging ⏳

#2622 [13.0][FIX] l10n_es_aeat_sii_oca, l10n_es_facturae: remove fields view get account.journal + account.move
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat/models/__init__.py
  l10n_es_aeat/models/account_journal.py
  l10n_es_aeat/models/account_move.py
  l10n_es_aeat/views/account_journal_view.xml
  l10n_es_aeat/views/account_move_view.xml
  l10n_es_aeat_sii_oca/__init__.py
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/models/__init__.py
  l10n_es_aeat_sii_oca/models/account_journal.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
  l10n_es_aeat_sii_oca/views/account_journal_view.xml
  l10n_es_aeat_sii_oca/views/account_move_views.xml
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae/models/__init__.py
  l10n_es_facturae/models/account_journal.py
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/readme/CONTRIBUTORS.rst
  l10n_es_facturae/tests/common.py
  l10n_es_facturae/views/account_journal_view.xml
  l10n_es_facturae/views/account_move_view.xml
Labels: bot is merging ⏳

#2641 [14.0][FIX] l10n_es_ticketbai: Send line price subtotal correctly
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#2642 [14.0][FIX] l10n_es_ticketbai: Assign sign to re tax amount
  l10n_es_ticketbai/models/account_tax.py
Labels: bot is merging ⏳

#2643 [15.0][FIX] l10n_es_ticketbai: Assign sign to re tax amount
  l10n_es_ticketbai/models/account_tax.py
Labels: bot is merging ⏳

#2644 [15.0][FIX] l10n_es_ticketbai: Send line price subtotal correctly
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#2617 [12.0][FIX] l10n_es_ticketbai*: Send country code when neccesary and get correct country code
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/models/account_invoice_tax.py
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
  l10n_es_ticketbai_batuz/models/account_invoice.py
  l10n_es_ticketbai_pos/models/pos_order.py
Labels: approved, bot is merging ⏳

#2650 [12.0] TicketBAI: Actualizar mantenedores
  l10n_es_dua_ticketbai_batuz/__manifest__.py
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai_api/__manifest__.py
  l10n_es_ticketbai_api_batuz/__manifest__.py
  l10n_es_ticketbai_batuz/__manifest__.py
  l10n_es_ticketbai_batuz_extra_data/__manifest__.py
  l10n_es_ticketbai_extra_data/__manifest__.py
  l10n_es_ticketbai_pos/__manifest__.py
Labels: approved, bot is merging ⏳

#2639 [14.0][IMP+FIX] l10n_es_aeat: Added support for tax groups in the calculation of tax info
  l10n_es_aeat/models/account_move.py
  l10n_es_aeat/readme/CONTRIBUTORS.rst
  l10n_es_aeat/tests/test_l10n_es_aeat_taxinfo.py
Labels: bot is merging ⏳

#2654 [15.0][FIX] l10n_es_ticketbai*: Send country code when neccesary and get correct country code
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/account_tax.py
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
  l10n_es_ticketbai_batuz/models/account_move.py
  l10n_es_ticketbai_pos/models/pos_order.py
Labels: bot is merging ⏳

#2649 [13.0][FIX] l10n_es_aeat_mod303: Avoid rounding problems
  l10n_es_aeat_mod303/models/mod303.py
Labels: bot is merging ⏳

#2631 [15.0][MIG] l10n_es_aeat_mod296: Migration to 15.0
  l10n_es_aeat_mod296/README.rst
  l10n_es_aeat_mod296/__init__.py
  l10n_es_aeat_mod296/__manifest__.py
  l10n_es_aeat_mod296/data/aeat_export_mod296_data.xml
  l10n_es_aeat_mod296/data/aeat_export_mod296_line_data.xml
  l10n_es_aeat_mod296/data/tax_code_map_mod296_data.xml
  l10n_es_aeat_mod296/docs/DR296_2017.pdf
  l10n_es_aeat_mod296/docs/instrucciones_296.pdf
  l10n_es_aeat_mod296/docs/register_design_296_2008.pdf
  l10n_es_aeat_mod296/i18n/es.po
  l10n_es_aeat_mod296/i18n/l10n_es_aeat_mod296.pot
  l10n_es_aeat_mod296/models/__init__.py
  l10n_es_aeat_mod296/models/mod296.py
  l10n_es_aeat_mod296/readme/CONFIGURE.rst
  l10n_es_aeat_mod296/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod296/readme/DESCRIPTION.rst
  l10n_es_aeat_mod296/readme/USAGE.rst
  l10n_es_aeat_mod296/security/ir.model.access.csv
  l10n_es_aeat_mod296/security/ir_rule.xml
  l10n_es_aeat_mod296/static/description/icon.png
  l10n_es_aeat_mod296/static/description/icon_source.svg
  l10n_es_aeat_mod296/static/description/index.html
  l10n_es_aeat_mod296/tests/__init__.py
  l10n_es_aeat_mod296/tests/test_l10n_es_aeat_mod296.py
  l10n_es_aeat_mod296/views/mod296_views.xml
  setup/l10n_es_aeat_mod296/odoo/addons/l10n_es_aeat_mod296
  setup/l10n_es_aeat_mod296/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2656 [14.0][FIX] l10n_es_aeat_mod303: Avoid rounding problems
  l10n_es_aeat_mod303/models/mod303.py
Labels: bot is merging ⏳

#2657 [15.0][FIX] l10n_es_aeat_mod303: Avoid rounding problems
  l10n_es_aeat_mod303/models/mod303.py
Labels: bot is merging ⏳
