Repository OCA/l10n-spain, pull requests merged in 2022-03, with the labels that each got.

#2175 [14.0][FIX] l10n_es_ticketbai: corregir signo del importe del descuento tba…
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#2177 [11.0][FIX] l10n_es_ticketbai_batuz: Fix multi-currency rate selection depe…
  l10n_es_ticketbai_batuz/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2179 [FIX] l10n_es_ticketbai_api: Fix tests
  l10n_es_ticketbai_api/tests/test_l10n_es_ticketbai_tax_agency.py
Labels: bot is merging ⏳

#2182 [14.0][FIX] l10n_es_ticketbai_api: Load security data
  l10n_es_ticketbai_api/__manifest__.py
Labels: bot is merging ⏳

#1941 [FIX] l10n_es_pos: search seq. prefix config parameter and create ir.…
  l10n_es_pos/models/pos_config.py
Labels: approved, bot is merging ⏳

#2185 [MIG] l10n_es_facturae_efact: Migración a 13.0
  l10n_es_facturae/migrations/13.0.2.0.0/pre-migration.py
  l10n_es_facturae_efact/README.rst
  l10n_es_facturae_efact/__init__.py
  l10n_es_facturae_efact/__manifest__.py
  l10n_es_facturae_efact/components/__init__.py
  l10n_es_facturae_efact/components/edi_input_process_l10n_es_facturae_l10n_es_facturae_efact_update.py
  l10n_es_facturae_efact/data/efact_data.xml
  l10n_es_facturae_efact/i18n/ca.po
  l10n_es_facturae_efact/i18n/es.po
  l10n_es_facturae_efact/i18n/l10n_es_facturae_efact.pot
  l10n_es_facturae_efact/migrations/13.0.1.0.0/post-migration.py
  l10n_es_facturae_efact/migrations/13.0.2.0.0/post-migration.py
  l10n_es_facturae_efact/models/__init__.py
  l10n_es_facturae_efact/models/account_move.py
  l10n_es_facturae_efact/models/edi_exchange_record.py
  l10n_es_facturae_efact/readme/CONFIG.rst
  l10n_es_facturae_efact/readme/CONTRIBUTORS.rst
  l10n_es_facturae_efact/readme/DESCRIPTION.rst
  l10n_es_facturae_efact/readme/INSTALL.rst
  l10n_es_facturae_efact/readme/ROADMAP.rst
  l10n_es_facturae_efact/static/description/icon.png
  l10n_es_facturae_efact/static/description/index.html
  l10n_es_facturae_efact/tests/__init__.py
  l10n_es_facturae_efact/tests/result.xml
  l10n_es_facturae_efact/tests/result_02.xml
  l10n_es_facturae_efact/tests/test_efact.py
  oca_dependencies.txt
  setup/l10n_es_facturae_efact/odoo/addons/l10n_es_facturae_efact
  setup/l10n_es_facturae_efact/setup.py
Labels: bot is merging ⏳

#2186 [11.0][FIX] l10n_es_ticketbai_api_batuz: Response values
  l10n_es_ticketbai_api_batuz/models/lroe_operation_response.py
  l10n_es_ticketbai_api_batuz/tests/test_lroe_operation.py
Labels: bot is merging ⏳

#2183 [11.0][IMP] l10n_es_ticketbai* - añadir tbai_active_date al diario
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/models/__init__.py
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/models/account_journal.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/account_journal_views.xml
  l10n_es_ticketbai_batuz/models/account_invoice.py
Labels: bot is merging ⏳

#2194 [FIX] l10n_es_aeat_mod303: Change sign on compute_casilla_69 operation
  l10n_es_aeat_mod303/models/mod303.py
Labels: bot is merging ⏳

#2195 [14.0][FIX] delivery_gls_asm: stock_picking_batch fail
  delivery_gls_asm/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳

#2100 [15.0][MIG] l10n_es_vat_book: Migration to 15.0
  l10n_es_vat_book/README.rst
  l10n_es_vat_book/__init__.py
  l10n_es_vat_book/__manifest__.py
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
  l10n_es_vat_book/i18n/bg.po
  l10n_es_vat_book/i18n/ca.po
  l10n_es_vat_book/i18n/cs.po
  l10n_es_vat_book/i18n/de.po
  l10n_es_vat_book/i18n/es.po
  l10n_es_vat_book/i18n/es_CO.po
  l10n_es_vat_book/i18n/es_CR.po
  l10n_es_vat_book/i18n/eu.po
  l10n_es_vat_book/i18n/fr.po
  l10n_es_vat_book/i18n/gl.po
  l10n_es_vat_book/i18n/hr.po
  l10n_es_vat_book/i18n/l10n_es_vat_book.pot
  l10n_es_vat_book/i18n/nl.po
  l10n_es_vat_book/i18n/pl.po
  l10n_es_vat_book/i18n/pt.po
  l10n_es_vat_book/i18n/pt_BR.po
  l10n_es_vat_book/i18n/ru.po
  l10n_es_vat_book/i18n/sl.po
  l10n_es_vat_book/i18n/sv.po
  l10n_es_vat_book/i18n/tr.po
  l10n_es_vat_book/i18n/vi.po
  l10n_es_vat_book/models/__init__.py
  l10n_es_vat_book/models/aeat_vat_book_map_line.py
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/models/l10n_es_vat_book_line.py
  l10n_es_vat_book/models/l10n_es_vat_book_line_tax.py
  l10n_es_vat_book/models/l10n_es_vat_book_summary.py
  l10n_es_vat_book/models/l10n_es_vat_book_tax_summary.py
  l10n_es_vat_book/readme/CONFIGURE.rst
  l10n_es_vat_book/readme/CONTRIBUTORS.rst
  l10n_es_vat_book/readme/DESCRIPTION.rst
  l10n_es_vat_book/readme/INSTALL.rst
  l10n_es_vat_book/readme/ROADMAP.rst
  l10n_es_vat_book/readme/USAGE.rst
  l10n_es_vat_book/report/__init__.py
  l10n_es_vat_book/report/common_templates.xml
  l10n_es_vat_book/report/report_views.xml
  l10n_es_vat_book/report/vat_book_invoices_issued.xml
  l10n_es_vat_book/report/vat_book_invoices_received.xml
  l10n_es_vat_book/report/vat_book_xlsx.py
  l10n_es_vat_book/report/vat_book_xlsx.xml
  l10n_es_vat_book/security/ir.model.access.csv
  l10n_es_vat_book/security/ir_rule.xml
  l10n_es_vat_book/static/description/icon.png
  l10n_es_vat_book/static/description/index.html
  l10n_es_vat_book/tests/__init__.py
  l10n_es_vat_book/tests/test_l10n_es_aeat_vat_book.py
  l10n_es_vat_book/views/aeat_vat_book_map_view.xml
  l10n_es_vat_book/views/l10n_es_vat_book.xml
  l10n_es_vat_book/views/l10n_es_vat_book_line.xml
  l10n_es_vat_book/views/l10n_es_vat_book_summary.xml
  l10n_es_vat_book/views/l10n_es_vat_book_tax_summary.xml
  setup/l10n_es_vat_book/odoo/addons/l10n_es_vat_book
  setup/l10n_es_vat_book/setup.py
Labels: bot is merging ⏳

#2167 [13.0][FIX] l10n_es_ticketbai: corregir signo del importe del descuento tba…
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#2187 [14.0][IMP] l10n_es_mis_report: actualización de plantillas y readme
  l10n_es_mis_report/data/mis_report_balance_abreviated.xml
  l10n_es_mis_report/data/mis_report_balance_sme.xml
  l10n_es_mis_report/data/mis_report_pyg_abreviated.xml
  l10n_es_mis_report/data/mis_report_pyg_sme.xml
  l10n_es_mis_report/readme/CONTRIBUTORS.rst
  l10n_es_mis_report/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#2152 [13.0][OU-ADD] ecoembes: Add migration script.
  ecoembes/__manifest__.py
  ecoembes/migrations/13.0.1.2.0/post-migration.py
Labels: bot is merging ⏳

#2193 [14.0][FIX] l10n_es_facturae_face: Add lost job
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/components/__init__.py
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_listener.py
  l10n_es_facturae_face/components/edi_output_l10n_es_facturae.py
  l10n_es_facturae_face/data/cron_data.xml
  l10n_es_facturae_face/models/__init__.py
  l10n_es_facturae_face/models/config.py
  l10n_es_facturae_face/views/res_config_views.xml
Labels: bot is merging ⏳

#2197 [14.0][MIG] l10n_es_facturae_efact
  l10n_es_facturae_efact/README.rst
  l10n_es_facturae_efact/__init__.py
  l10n_es_facturae_efact/__manifest__.py
  l10n_es_facturae_efact/components/__init__.py
  l10n_es_facturae_efact/components/edi_input_process_l10n_es_facturae_l10n_es_facturae_efact_update.py
  l10n_es_facturae_efact/data/efact_data.xml
  l10n_es_facturae_efact/i18n/ca.po
  l10n_es_facturae_efact/i18n/es.po
  l10n_es_facturae_efact/i18n/l10n_es_facturae_efact.pot
  l10n_es_facturae_efact/models/__init__.py
  l10n_es_facturae_efact/models/account_move.py
  l10n_es_facturae_efact/models/edi_exchange_record.py
  l10n_es_facturae_efact/readme/CONFIG.rst
  l10n_es_facturae_efact/readme/CONTRIBUTORS.rst
  l10n_es_facturae_efact/readme/DESCRIPTION.rst
  l10n_es_facturae_efact/readme/INSTALL.rst
  l10n_es_facturae_efact/readme/ROADMAP.rst
  l10n_es_facturae_efact/static/description/icon.png
  l10n_es_facturae_efact/static/description/index.html
  l10n_es_facturae_efact/tests/__init__.py
  l10n_es_facturae_efact/tests/result.xml
  l10n_es_facturae_efact/tests/result_02.xml
  l10n_es_facturae_efact/tests/test_efact.py
  requirements.txt
  setup/l10n_es_facturae_efact/odoo/addons/l10n_es_facturae_efact
  setup/l10n_es_facturae_efact/setup.py
Labels: approved, bot is merging ⏳

#2199 [15.0][MIG] l10n_es_facturae_face: Migration to 15.0
  l10n_es_facturae_face/README.rst
  l10n_es_facturae_face/__init__.py
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/components/__init__.py
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_face_listener.py
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_listener.py
  l10n_es_facturae_face/components/edi_input_process_l10n_es_facturae_l10n_es_facturae_face_update.py
  l10n_es_facturae_face/components/edi_output_l10n_es_facturae.py
  l10n_es_facturae_face/components/edi_send_l10n_es_facturae_face.py
  l10n_es_facturae_face/components/edi_send_l10n_es_facturae_face_cancel.py
  l10n_es_facturae_face/components/edi_webservice_receive_face_l10n_es_facturae_face_update.py
  l10n_es_facturae_face/components/webservice_face.py
  l10n_es_facturae_face/data/edi.xml
  l10n_es_facturae_face/data/edi_output.xml
  l10n_es_facturae_face/data/face_data.xml
  l10n_es_facturae_face/i18n/es.po
  l10n_es_facturae_face/i18n/l10n_es_facturae_face.pot
  l10n_es_facturae_face/models/__init__.py
  l10n_es_facturae_face/models/account_move.py
  l10n_es_facturae_face/models/config.py
  l10n_es_facturae_face/models/edi_exchange_record.py
  l10n_es_facturae_face/models/res_company.py
  l10n_es_facturae_face/models/res_partner.py
  l10n_es_facturae_face/models/webservice_backend.py
  l10n_es_facturae_face/models/wsse_signature.py
  l10n_es_facturae_face/readme/CONFIGURE.rst
  l10n_es_facturae_face/readme/DESCRIPTION.rst
  l10n_es_facturae_face/readme/INSTALL.rst
  l10n_es_facturae_face/readme/USAGE.rst
  l10n_es_facturae_face/security/ir.model.access.csv
  l10n_es_facturae_face/static/description/icon.png
  l10n_es_facturae_face/static/description/index.html
  l10n_es_facturae_face/tests/__init__.py
  l10n_es_facturae_face/tests/test_facturae_face.py
  l10n_es_facturae_face/views/account_move.xml
  l10n_es_facturae_face/views/edi_exchange_record.xml
  l10n_es_facturae_face/views/res_company_view.xml
  l10n_es_facturae_face/views/res_config_views.xml
  l10n_es_facturae_face/views/res_partner.xml
  l10n_es_facturae_face/wizards/__init__.py
  l10n_es_facturae_face/wizards/edi_l10n_es_facturae_face_cancel.py
  l10n_es_facturae_face/wizards/edi_l10n_es_facturae_face_cancel.xml
  setup/l10n_es_facturae_face/odoo/addons/l10n_es_facturae_face
  setup/l10n_es_facturae_face/setup.py
Labels: bot is merging ⏳

#2205 [12.0][FIX] - use sudo to compute l10n_es_aeat_349_operation_key
  l10n_es_aeat_mod349/models/account_tax.py
Labels: bot is merging ⏳

#2200 [14.0][MIG] l10n_es_facturae_sale_stock
  l10n_es_facturae_sale_stock/README.rst
  l10n_es_facturae_sale_stock/__init__.py
  l10n_es_facturae_sale_stock/__manifest__.py
  l10n_es_facturae_sale_stock/models/__init__.py
  l10n_es_facturae_sale_stock/models/account_move_line.py
  l10n_es_facturae_sale_stock/readme/CONTRIBUTORS.rst
  l10n_es_facturae_sale_stock/readme/DESCRIPTION.rst
  l10n_es_facturae_sale_stock/readme/INSTALL.rst
  l10n_es_facturae_sale_stock/static/description/icon.png
  l10n_es_facturae_sale_stock/static/description/index.html
  l10n_es_facturae_sale_stock/views/report_facturae.xml
  setup/l10n_es_facturae_sale_stock/odoo/addons/l10n_es_facturae_sale_stock
  setup/l10n_es_facturae_sale_stock/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2203 [14.0][FIX] l10n_es_facturae_face: skip check step.
  l10n_es_facturae_efact/tests/test_efact.py
  l10n_es_facturae_face/data/face_data.xml
  l10n_es_facturae_face/migrations/14.0.1.2.0/noupdate_changes.xml
  l10n_es_facturae_face/migrations/14.0.1.2.0/post-migration.py
  l10n_es_facturae_face/tests/test_facturae_face.py
Labels: bot is merging ⏳

#2207 [FIX] l10n_es_mis_report: Fix 1146 account
  l10n_es_mis_report/__manifest__.py
  l10n_es_mis_report/data/mis_report_balance_normal.xml
Labels: bot is merging ⏳
