Repository OCA/l10n-spain, pull requests merged in 2022-05, with the labels that each got.

#2229 [11.0][FIX] l10n_es_ticketbai - corregido filtered para no enviar rec…
  l10n_es_ticketbai/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2249 [FIX] l10n_es_aeat_sii_oca fix vat problem described in #2248
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#2253 [FIX] Missing alert role
  l10n_es_vat_book/views/l10n_es_vat_book.xml
Labels: bot is merging ⏳

#2254 [FIX] Missing alert role
  l10n_es_vat_book/views/l10n_es_vat_book.xml
Labels: bot is merging ⏳

#2257 [FIX] [14.0] l10n_es_vat_book: Change order on lines
  l10n_es_vat_book/models/l10n_es_vat_book_line.py
Labels: approved, bot is merging ⏳

#2260 [14.0][IMP] delivery_gls_asm: master data and requiered info
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/models/gls_asm_master_data.py
  delivery_gls_asm/models/gls_asm_request.py
Labels: approved, bot is merging ⏳

#2258 [12.0][REF]l10n_es_ticketbai: Facilitar herencia en generación de lineas
  l10n_es_ticketbai/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2251 [11.0][FIX] l10n_es_ticketbai_api - corregida generación de url en supuestos sin serie de factura
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
  l10n_es_ticketbai_api/ticketbai/xml_schema.py
Labels: approved, bot is merging ⏳

#1864 [11.0]l10n_es_intrastat_report: backport to v11
  l10n_es_intrastat_report/README.rst
  l10n_es_intrastat_report/__init__.py
  l10n_es_intrastat_report/__manifest__.py
  l10n_es_intrastat_report/data/NC_20.xlsx
  l10n_es_intrastat_report/data/intrastat_transaction.xml
  l10n_es_intrastat_report/i18n/es.po
  l10n_es_intrastat_report/i18n/l10n_es_intrastat_report.pot
  l10n_es_intrastat_report/models/__init__.py
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
  l10n_es_intrastat_report/models/stock_location.py
  l10n_es_intrastat_report/readme/CONFIGURE.rst
  l10n_es_intrastat_report/readme/CONTRIBUTORS.rst
  l10n_es_intrastat_report/readme/DESCRIPTION.rst
  l10n_es_intrastat_report/readme/INSTALL.rst
  l10n_es_intrastat_report/readme/ROADMAP.rst
  l10n_es_intrastat_report/readme/USAGE.rst
  l10n_es_intrastat_report/report/__init__.py
  l10n_es_intrastat_report/report/intrastat_product_report_xls.py
  l10n_es_intrastat_report/security/ir.model.access.csv
  l10n_es_intrastat_report/security/l10n_es_intrastat_report_security.xml
  l10n_es_intrastat_report/static/description/icon.png
  l10n_es_intrastat_report/static/description/index.html
  l10n_es_intrastat_report/views/l10n_es_intrastat_product.xml
  l10n_es_intrastat_report/wizards/__init__.py
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.py
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳

#2267 [12.0][FIX] l10n_es_ticketbai_api: corregida generación de url en supuestos…
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
  l10n_es_ticketbai_api/ticketbai/xml_schema.py
Labels: bot is merging ⏳

#2052 [ADD] Implementación de TicketBai para el POS
  l10n_es_ticketbai_pos/README.rst
  l10n_es_ticketbai_pos/__init__.py
  l10n_es_ticketbai_pos/__manifest__.py
  l10n_es_ticketbai_pos/i18n/es.po
  l10n_es_ticketbai_pos/i18n/l10n_es_ticketbai_pos.pot
  l10n_es_ticketbai_pos/models/__init__.py
  l10n_es_ticketbai_pos/models/account_invoice.py
  l10n_es_ticketbai_pos/models/pos_config.py
  l10n_es_ticketbai_pos/models/pos_order.py
  l10n_es_ticketbai_pos/models/ticketbai_invoice.py
  l10n_es_ticketbai_pos/security/ir.model.access.csv
  l10n_es_ticketbai_pos/static/description/icon.png
  l10n_es_ticketbai_pos/static/lib/qrcode.js
  l10n_es_ticketbai_pos/static/lib/tbai.js
  l10n_es_ticketbai_pos/static/src/img/oca_logo.png
  l10n_es_ticketbai_pos/static/src/js/db.js
  l10n_es_ticketbai_pos/static/src/js/models.js
  l10n_es_ticketbai_pos/static/src/js/screens.js
  l10n_es_ticketbai_pos/static/src/js/tbai_models.js
  l10n_es_ticketbai_pos/static/src/js/widgets.js
  l10n_es_ticketbai_pos/static/src/xml/pos.xml
  l10n_es_ticketbai_pos/tests/__init__.py
  l10n_es_ticketbai_pos/tests/common.py
  l10n_es_ticketbai_pos/tests/test_l10n_es_ticketbai_pos.py
  l10n_es_ticketbai_pos/views/l10n_es_ticketbai_pos.xml
  l10n_es_ticketbai_pos/views/l10n_es_ticketbai_pos_views.xml
  l10n_es_ticketbai_pos/views/pos_order_views.xml
  l10n_es_ticketbai_pos/views/ticketbai_certificate_views.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳

#2274 [IMP] Facturae: Add myself as maintainer
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae_face/__manifest__.py
Labels: bot is merging ⏳

#2272 [IMP] Facturae: add myself as maintainer
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae_efact/__manifest__.py
  l10n_es_facturae_face/__manifest__.py
Labels: bot is merging ⏳

#2273 [IMP] Facturae: Add myself as maintainer
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae_efact/__manifest__.py
  l10n_es_facturae_face/__manifest__.py
Labels: bot is merging ⏳

#2279 [FIX]l10n_es_aeat: Considerar modelo en comprobación de rango de fechas
  l10n_es_aeat/models/l10n_es_aeat_map_tax.py
  l10n_es_aeat/readme/CONTRIBUTORS.rst
  l10n_es_aeat/tests/test_l10n_es_aeat.py
Labels: bot is merging ⏳

#2268 [13.0][FIX] l10n_es_ticketbai_api: corregida generación de url en supuestos…
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
  l10n_es_ticketbai_api/ticketbai/xml_schema.py
Labels: bot is merging ⏳

#2184 [MIG] l10n_es_ticketbai: Migration to 15.0
  l10n_es_ticketbai/README.rst
  l10n_es_ticketbai/__init__.py
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/data/account_fiscal_position_template.xml
  l10n_es_ticketbai/data/tax_map_data.xml
  l10n_es_ticketbai/data/vat_exemption_key_data.xml
  l10n_es_ticketbai/data/vat_regime_key_data.xml
  l10n_es_ticketbai/hooks.py
  l10n_es_ticketbai/i18n/ca.po
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/models/__init__.py
  l10n_es_ticketbai/models/account_fiscal_position.py
  l10n_es_ticketbai/models/account_journal.py
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/account_resequence.py
  l10n_es_ticketbai/models/account_tax.py
  l10n_es_ticketbai/models/aeat_certificate.py
  l10n_es_ticketbai/models/chart_template.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/models/ticketbai_invoice.py
  l10n_es_ticketbai/models/ticketbai_tax_map.py
  l10n_es_ticketbai/models/ticketbai_vat_exemption_key.py
  l10n_es_ticketbai/models/ticketbai_vat_regime_key.py
  l10n_es_ticketbai/readme/CONFIGURE.rst
  l10n_es_ticketbai/readme/CONTRIBUTORS.rst
  l10n_es_ticketbai/readme/DESCRIPTION.rst
  l10n_es_ticketbai/readme/USAGE.rst
  l10n_es_ticketbai/security/ir.model.access.csv
  l10n_es_ticketbai/static/description/icon.png
  l10n_es_ticketbai/static/description/index.html
  l10n_es_ticketbai/tests/__init__.py
  l10n_es_ticketbai/tests/certs/ciudadano_act.p12
  l10n_es_ticketbai/tests/certs/ciudadano_act_p12_password.txt
  l10n_es_ticketbai/tests/certs/private_up_8mgwq.pem
  l10n_es_ticketbai/tests/certs/public_362gar7l.crt
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_cancellation.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/account_fiscal_position_template_views.xml
  l10n_es_ticketbai/views/account_fiscal_position_views.xml
  l10n_es_ticketbai/views/account_journal_views.xml
  l10n_es_ticketbai/views/account_move_views.xml
  l10n_es_ticketbai/views/l10n_es_ticketbai_views.xml
  l10n_es_ticketbai/views/report_invoice.xml
  l10n_es_ticketbai/views/res_company_views.xml
  l10n_es_ticketbai/views/res_partner_views.xml
  l10n_es_ticketbai/views/tax_map_views.xml
  l10n_es_ticketbai/views/ticketbai_invoice_views.xml
  l10n_es_ticketbai/views/vat_exemption_key_views.xml
  l10n_es_ticketbai/views/vat_regime_key_views.xml
  l10n_es_ticketbai/wizard/__init__.py
  l10n_es_ticketbai/wizard/account_move_reversal.py
  l10n_es_ticketbai/wizard/aeat_certificate_password.py
  l10n_es_ticketbai/wizard/ticketbai_info.py
  l10n_es_ticketbai/wizard/ticketbai_info_views.xml
  setup/l10n_es_ticketbai/odoo/addons/l10n_es_ticketbai
  setup/l10n_es_ticketbai/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2269 [14.0][FIX] l10n_es_ticketbai_api: corregida generación de url en supuestos…
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
  l10n_es_ticketbai_api/ticketbai/xml_schema.py
Labels: bot is merging ⏳

#2270 [15.0][FIX] l10n_es_ticketbai_api: corregida generación de url en supuestos…
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
  l10n_es_ticketbai_api/ticketbai/xml_schema.py
Labels: bot is merging ⏳

#2284 [FIX]l10n_es_aeat: Considerar modelo en comprobación de rango de fechas
  l10n_es_aeat/models/l10n_es_aeat_map_tax.py
  l10n_es_aeat/readme/CONTRIBUTORS.rst
  l10n_es_aeat/tests/test_l10n_es_aeat.py
Labels: bot is merging ⏳

#2277 [MIG] l10n_es_irnr: Migration to 15.0
  l10n_es_irnr/README.rst
  l10n_es_irnr/__init__.py
  l10n_es_irnr/__manifest__.py
  l10n_es_irnr/data/account_data.xml
  l10n_es_irnr/data/fiscal_position_taxes_irnr.xml
  l10n_es_irnr/data/fiscal_positions_irnr.xml
  l10n_es_irnr/data/taxes_irnr.xml
  l10n_es_irnr/i18n/ca.po
  l10n_es_irnr/i18n/l10n_es_irnr.pot
  l10n_es_irnr/readme/CONFIGURE.rst
  l10n_es_irnr/readme/CONTRIBUTORS.rst
  l10n_es_irnr/readme/DESCRIPTION.rst
  l10n_es_irnr/readme/ROADMAP.rst
  l10n_es_irnr/readme/USAGE.rst
  l10n_es_irnr/static/description/icon.png
  l10n_es_irnr/static/description/index.html
  setup/l10n_es_irnr/odoo/addons/l10n_es_irnr
  setup/l10n_es_irnr/setup.py
Labels: approved, bot is merging ⏳

#2278 [MIG] l10n_es_ticketbai_pos: Migration to 12.0
  l10n_es_ticketbai_pos/README.rst
  l10n_es_ticketbai_pos/__init__.py
  l10n_es_ticketbai_pos/__manifest__.py
  l10n_es_ticketbai_pos/i18n/es.po
  l10n_es_ticketbai_pos/i18n/l10n_es_ticketbai_pos.pot
  l10n_es_ticketbai_pos/models/__init__.py
  l10n_es_ticketbai_pos/models/account_invoice.py
  l10n_es_ticketbai_pos/models/pos_config.py
  l10n_es_ticketbai_pos/models/pos_order.py
  l10n_es_ticketbai_pos/models/ticketbai_invoice.py
  l10n_es_ticketbai_pos/security/ir.model.access.csv
  l10n_es_ticketbai_pos/static/description/icon.png
  l10n_es_ticketbai_pos/static/lib/qrcode.js
  l10n_es_ticketbai_pos/static/lib/tbai.js
  l10n_es_ticketbai_pos/static/src/img/oca_logo.png
  l10n_es_ticketbai_pos/static/src/js/db.js
  l10n_es_ticketbai_pos/static/src/js/models.js
  l10n_es_ticketbai_pos/static/src/js/screens.js
  l10n_es_ticketbai_pos/static/src/js/tbai_models.js
  l10n_es_ticketbai_pos/static/src/js/widgets.js
  l10n_es_ticketbai_pos/static/src/xml/pos.xml
  l10n_es_ticketbai_pos/tests/__init__.py
  l10n_es_ticketbai_pos/tests/common.py
  l10n_es_ticketbai_pos/tests/test_l10n_es_ticketbai_pos.py
  l10n_es_ticketbai_pos/views/l10n_es_ticketbai_pos.xml
  l10n_es_ticketbai_pos/views/l10n_es_ticketbai_pos_views.xml
  l10n_es_ticketbai_pos/views/pos_order_views.xml
  l10n_es_ticketbai_pos/views/ticketbai_certificate_views.xml
Labels: approved, bot is merging ⏳

#2216 [14.0][IMP] delivery_gls_asm: Cash on delivery
  delivery_gls_asm/i18n/delivery_gls_asm.pot
  delivery_gls_asm/i18n/es.po
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/views/delivery_asm_view.xml
Labels: approved, bot is merging ⏳

#2264 [12.0][mig] l10n_es_ticketbai_batuz
  l10n_es_ticketbai_batuz/README.rst
  l10n_es_ticketbai_batuz/__init__.py
  l10n_es_ticketbai_batuz/__manifest__.py
  l10n_es_ticketbai_batuz/data/account_fiscal_position_template_data.xml
  l10n_es_ticketbai_batuz/data/queue_job_data.xml
  l10n_es_ticketbai_batuz/data/tbai_tax_map_data.xml
  l10n_es_ticketbai_batuz/data/tbai_vat_regime_key_data.xml
  l10n_es_ticketbai_batuz/hooks.py
  l10n_es_ticketbai_batuz/i18n/es.po
  l10n_es_ticketbai_batuz/i18n/l10n_es_ticketbai_batuz.pot
  l10n_es_ticketbai_batuz/models/__init__.py
  l10n_es_ticketbai_batuz/models/account_fiscal_position.py
  l10n_es_ticketbai_batuz/models/account_invoice.py
  l10n_es_ticketbai_batuz/models/chart_template.py
  l10n_es_ticketbai_batuz/models/lroe_operation.py
  l10n_es_ticketbai_batuz/models/res_company.py
  l10n_es_ticketbai_batuz/models/res_partner.py
  l10n_es_ticketbai_batuz/models/ticketbai_invoice.py
  l10n_es_ticketbai_batuz/models/ticketbai_vat_regime_key.py
  l10n_es_ticketbai_batuz/readme/CONTRIBUTORS.rst
  l10n_es_ticketbai_batuz/readme/DESCRIPTION.rst
  l10n_es_ticketbai_batuz/readme/INSTALL.rst
  l10n_es_ticketbai_batuz/readme/USAGE.rst
  l10n_es_ticketbai_batuz/security/ir_rule.xml
  l10n_es_ticketbai_batuz/static/description/icon.png
  l10n_es_ticketbai_batuz/static/description/index.html
  l10n_es_ticketbai_batuz/static/src/description/icon.png
  l10n_es_ticketbai_batuz/static/src/img/binovo_logo.jpg
  l10n_es_ticketbai_batuz/static/src/img/binovo_logo_peque.jpg
  l10n_es_ticketbai_batuz/views/account_fiscal_position_views.xml
  l10n_es_ticketbai_batuz/views/account_invoice_views.xml
  l10n_es_ticketbai_batuz/views/lroe_operation_views.xml
  l10n_es_ticketbai_batuz/views/res_company_views.xml
  l10n_es_ticketbai_batuz/views/res_partner_views.xml
  l10n_es_ticketbai_batuz/views/tbai_vat_regime_key_views.xml
  l10n_es_ticketbai_batuz/wizard/__init__.py
  l10n_es_ticketbai_batuz/wizard/account_invoice_refund.py
  l10n_es_ticketbai_batuz/wizard/account_invoice_refund_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2261 [FIX] l10n_es_facturae_face: Certificate must be public
  l10n_es_facturae_face/data/face_data.xml
Labels: approved, ready to merge, bot is merging ⏳

#2276 [11.0][FIX] l10n_es_ticketbai_batuz: Se buscan los impuestos de la compañía…
  l10n_es_ticketbai_batuz/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2096 [IMP] l10n_es_pos: Generate offline invoice number
  l10n_es_pos/static/src/js/PaymentScreen.js
  l10n_es_pos/static/src/js/Screens/OrderManagementScreen/OrderManagementControlPanel.js
  l10n_es_pos/static/src/js/models.js
Labels: approved, ready to merge, bot is merging ⏳

#2265 [12.0][MIG] l10n_es_dua_ticketbai_batuz
  l10n_es_dua_ticketbai_batuz/README.rst
  l10n_es_dua_ticketbai_batuz/__init__.py
  l10n_es_dua_ticketbai_batuz/__manifest__.py
  l10n_es_dua_ticketbai_batuz/data/account_fiscal_position_template_data.xml
  l10n_es_dua_ticketbai_batuz/data/tax_code_map_dua_ticketbai_data.xml
  l10n_es_dua_ticketbai_batuz/i18n/l10n_es_dua_ticketbai_batuz.pot
  l10n_es_dua_ticketbai_batuz/models/__init__.py
  l10n_es_dua_ticketbai_batuz/models/account_invoice.py
  l10n_es_dua_ticketbai_batuz/readme/CONFIGURATION.rst
  l10n_es_dua_ticketbai_batuz/readme/CONTRIBUTORS.rst
  l10n_es_dua_ticketbai_batuz/readme/DESCRIPTION.rst
  l10n_es_dua_ticketbai_batuz/readme/USAGE.rst
  l10n_es_dua_ticketbai_batuz/static/description/icon.png
  l10n_es_dua_ticketbai_batuz/static/description/index.html
Labels: approved, bot is merging ⏳

#2298 [FIX] l10n_es_facturae_face: Certificate must be public
  l10n_es_facturae_face/data/face_data.xml
Labels: bot is merging ⏳

#2297 [FIX] l10n_es_facturae_face: Certificate must be public
  l10n_es_facturae_face/data/face_data.xml
Labels: bot is merging ⏳

#2208 [14.0][IMP] delivery_gls_asm: Referencia albarán
  delivery_gls_asm/i18n/delivery_gls_asm.pot
  delivery_gls_asm/i18n/es.po
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/models/stock_picking.py
Labels: bot is merging ⏳

#2122 [14.0][IMP] delivery_dhl_parcel: Minimum 1kg
  delivery_dhl_parcel/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#2291 [12.0][FIX] l10n_es_ticketbai_api_batuz: Remove migrations folder from prev…
  l10n_es_ticketbai_api_batuz/migrations/11.0.1.0.1/post-migrate.py
Labels: bot is merging ⏳

#2300 [IMP]l10n_es_aeat: Base para mostrar numero errores en reports
  l10n_es_aeat/models/l10n_es_aeat_report.py
  l10n_es_aeat/readme/CONFIGURE.rst
  l10n_es_aeat/views/aeat_report_view.xml
Labels: approved, bot is merging ⏳

#2014 [11.0][IMP] l10n_es_ticketbai: Add hook which fills previous invoice tbai f…
  l10n_es_ticketbai/hooks.py
Labels: approved, bot is merging ⏳, stale

#2308 [12.0][IMP] l10n_es_ticketbai: Add hook which fills previous invoice tbai f…
  l10n_es_ticketbai/hooks.py
Labels: bot is merging ⏳

#2311 [14.0][FIX] l10n_es_facturae: obtener certificados con sudo.
  l10n_es_facturae/reports/report_facturae.py
Labels: approved, bot is merging ⏳

#2312 [15.0][FIX] l10n_es_facturae: obtener certificados con sudo.
  l10n_es_facturae/reports/report_facturae.py
Labels: bot is merging ⏳

#2307 [14.0][IMP] l10n_es_aeat: Show used Fiscal Position Templates on Map Tax models
  l10n_es_aeat/models/l10n_es_aeat_map_tax_line.py
  l10n_es_aeat/views/aeat_tax_code_mapping_view.xml
Labels: approved, bot is merging ⏳

#2310 [13.0][IMP] l10n_es_facturae: Prevent error if bank account is not set.
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#2318 [14.0][IMP] l10n_es_facturae: Prevent error if bank account is not set
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#2319 [15.0][IMP] l10n_es_facturae: Prevent error if bank account is not set
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳
