Repository OCA/l10n-spain, pull requests merged in 2022-08, with the labels that each got.

#2447 [14.0][IMP] l10n_es_aeat_sii_oca: Avoid modifying customer invoice name when an invoice has already been sent to the SII + Tests.
  l10n_es_aeat_sii_oca/i18n/es.po
  l10n_es_aeat_sii_oca/i18n/l10n_es_aeat_sii_oca.pot
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: bot is merging ⏳

#2019 [15.0][IMP] l10n_es_aeat_sii_oca: Add thirdparty fields to allow inheritance in other addons.
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/i18n/es.po
  l10n_es_aeat_sii_oca/i18n/l10n_es_aeat_sii_oca.pot
  l10n_es_aeat_sii_oca/migrations/15.0.2.3.0/pre-migration.py
  l10n_es_aeat_sii_oca/models/__init__.py
  l10n_es_aeat_sii_oca/models/account_journal.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/static/description/index.html
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
  l10n_es_aeat_sii_oca/views/account_move_views.xml
Labels: bot is merging ⏳

#2446 [14.0][FIX] l10n_es_ticketbai-clean-old-library-methods
  l10n_es_ticketbai/models/aeat_certificate.py
Labels: approved, bot is merging ⏳

#2448 [14.0][FIX] l10n_es_ticketbai: Get company IRPF taxes correctly
  l10n_es_ticketbai/models/account_move.py
Labels: approved, bot is merging ⏳

#2454 [13.0][FIX] l10n_es_ticketbai: Get company IRPF taxes correctly
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#2438 [12.0][FIX]-l10n_es_ticketbai_api_batuz-fields_have_same_label
  l10n_es_ticketbai_api_batuz/models/lroe_operation.py
Labels: approved, ready to merge, bot is merging ⏳

#2437 [12.0][FIX]-l10n_es_ticketbai_batuz-fields_have_same_label
  l10n_es_ticketbai_batuz/models/account_invoice.py
Labels: approved, ready to merge, bot is merging ⏳

#2459 [13.0][FIX] l10n_es_ticketbai_pos: Fix tbai file generation with operation …
  l10n_es_ticketbai_pos/models/account_move.py
Labels: approved, bot is merging ⏳

#2455 [FIX] l10n_es_aeat: _parse_aeat_vat_info - show correct aeat identification
  l10n_es_aeat/models/res_partner.py
  l10n_es_aeat/tests/test_l10n_es_aeat.py
Labels: bot is merging ⏳

#2417 [MIG] l10n_es_dua_ticketbai_batuz: Migration to 14.0
  l10n_es_dua_ticketbai_batuz/README.rst
  l10n_es_dua_ticketbai_batuz/__init__.py
  l10n_es_dua_ticketbai_batuz/__manifest__.py
  l10n_es_dua_ticketbai_batuz/data/account_fiscal_position_template_data.xml
  l10n_es_dua_ticketbai_batuz/data/tax_code_map_dua_ticketbai_data.xml
  l10n_es_dua_ticketbai_batuz/i18n/l10n_es_dua_ticketbai_batuz.pot
  l10n_es_dua_ticketbai_batuz/models/__init__.py
  l10n_es_dua_ticketbai_batuz/models/account_move.py
  l10n_es_dua_ticketbai_batuz/readme/CONFIGURATION.rst
  l10n_es_dua_ticketbai_batuz/readme/CONTRIBUTORS.rst
  l10n_es_dua_ticketbai_batuz/readme/DESCRIPTION.rst
  l10n_es_dua_ticketbai_batuz/readme/USAGE.rst
  l10n_es_dua_ticketbai_batuz/static/description/icon.png
  l10n_es_dua_ticketbai_batuz/static/description/index.html
  setup/l10n_es_dua_ticketbai_batuz/odoo/addons/l10n_es_dua_ticketbai_batuz
  setup/l10n_es_dua_ticketbai_batuz/setup.py
Labels: approved, bot is merging ⏳

#2464 [15.0] l10n_es_aeat_*: Include new 5% tax
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: bot is merging ⏳

#2457 [MIG] l10n_es_ticketbai_pos: Migration to 14.0
  l10n_es_ticketbai_pos/README.rst
  l10n_es_ticketbai_pos/__init__.py
  l10n_es_ticketbai_pos/__manifest__.py
  l10n_es_ticketbai_pos/i18n/es.po
  l10n_es_ticketbai_pos/i18n/l10n_es_ticketbai_pos.pot
  l10n_es_ticketbai_pos/models/__init__.py
  l10n_es_ticketbai_pos/models/account_move.py
  l10n_es_ticketbai_pos/models/pos_config.py
  l10n_es_ticketbai_pos/models/pos_order.py
  l10n_es_ticketbai_pos/models/ticketbai_invoice.py
  l10n_es_ticketbai_pos/security/ir.model.access.csv
  l10n_es_ticketbai_pos/static/description/icon.png
  l10n_es_ticketbai_pos/static/lib/qrcode.js
  l10n_es_ticketbai_pos/static/lib/tbai.js
  l10n_es_ticketbai_pos/static/src/img/oca_logo.png
  l10n_es_ticketbai_pos/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  l10n_es_ticketbai_pos/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  l10n_es_ticketbai_pos/static/src/js/Screens/ProductScreen/ProductScreen.js
  l10n_es_ticketbai_pos/static/src/js/db.js
  l10n_es_ticketbai_pos/static/src/js/models.js
  l10n_es_ticketbai_pos/static/src/js/tbai_models.js
  l10n_es_ticketbai_pos/static/src/js/widgets.js
  l10n_es_ticketbai_pos/static/src/xml/pos.xml
  l10n_es_ticketbai_pos/tests/__init__.py
  l10n_es_ticketbai_pos/tests/common.py
  l10n_es_ticketbai_pos/tests/test_l10n_es_ticketbai_pos.py
  l10n_es_ticketbai_pos/views/l10n_es_ticketbai_pos.xml
  l10n_es_ticketbai_pos/views/l10n_es_ticketbai_pos_views.xml
  l10n_es_ticketbai_pos/views/pos_order_views.xml
  l10n_es_ticketbai_pos/views/ticketbai_certificate_views.xml
  setup/l10n_es_ticketbai_pos/odoo/addons/l10n_es_ticketbai_pos
  setup/l10n_es_ticketbai_pos/setup.py
Labels: approved, bot is merging ⏳

#2465 [13.0][FIX] l10n_es_intrastat_report: Add the necessary arguments to the functions
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
Labels: bot is merging ⏳

#2462 [15.0][MIG] l10n_es_ticketbai_batuz
  l10n_es_ticketbai_batuz/README.rst
  l10n_es_ticketbai_batuz/__init__.py
  l10n_es_ticketbai_batuz/__manifest__.py
  l10n_es_ticketbai_batuz/data/account_fiscal_position_template_data.xml
  l10n_es_ticketbai_batuz/data/queue_job_data.xml
  l10n_es_ticketbai_batuz/data/tbai_tax_map_data.xml
  l10n_es_ticketbai_batuz/data/tbai_vat_regime_key_data.xml
  l10n_es_ticketbai_batuz/hooks.py
  l10n_es_ticketbai_batuz/i18n/es.po
  l10n_es_ticketbai_batuz/i18n/l10n_es_ticketbai_batuz.pot
  l10n_es_ticketbai_batuz/models/__init__.py
  l10n_es_ticketbai_batuz/models/account_fiscal_position.py
  l10n_es_ticketbai_batuz/models/account_move.py
  l10n_es_ticketbai_batuz/models/chart_template.py
  l10n_es_ticketbai_batuz/models/lroe_operation.py
  l10n_es_ticketbai_batuz/models/res_company.py
  l10n_es_ticketbai_batuz/models/res_partner.py
  l10n_es_ticketbai_batuz/models/ticketbai_invoice.py
  l10n_es_ticketbai_batuz/models/ticketbai_vat_regime_key.py
  l10n_es_ticketbai_batuz/readme/CONTRIBUTORS.rst
  l10n_es_ticketbai_batuz/readme/DESCRIPTION.rst
  l10n_es_ticketbai_batuz/readme/INSTALL.rst
  l10n_es_ticketbai_batuz/readme/USAGE.rst
  l10n_es_ticketbai_batuz/security/ir_rule.xml
  l10n_es_ticketbai_batuz/static/description/icon.png
  l10n_es_ticketbai_batuz/static/description/index.html
  l10n_es_ticketbai_batuz/static/src/description/icon.png
  l10n_es_ticketbai_batuz/static/src/img/binovo_logo.jpg
  l10n_es_ticketbai_batuz/static/src/img/binovo_logo_peque.jpg
  l10n_es_ticketbai_batuz/views/account_fiscal_position_views.xml
  l10n_es_ticketbai_batuz/views/account_move_views.xml
  l10n_es_ticketbai_batuz/views/lroe_operation_views.xml
  l10n_es_ticketbai_batuz/views/res_company_views.xml
  l10n_es_ticketbai_batuz/views/res_partner_views.xml
  l10n_es_ticketbai_batuz/views/tbai_vat_regime_key_views.xml
  l10n_es_ticketbai_batuz/wizard/__init__.py
  l10n_es_ticketbai_batuz/wizard/account_move_reversal.py
  l10n_es_ticketbai_batuz/wizard/account_move_reversal_views.xml
  setup/l10n_es_ticketbai_batuz/odoo/addons/l10n_es_ticketbai_batuz
  setup/l10n_es_ticketbai_batuz/setup.py
Labels: approved, bot is merging ⏳

#2374 [13.0][IMP+FIX] delivery_gls_asm: Add gls_asm_use_packages_from_picking field in carrier to use (or not) package from pickings + Set the correct weight if we use packages.
  delivery_gls_asm/i18n/delivery_gls_asm.pot
  delivery_gls_asm/i18n/es.po
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/views/delivery_asm_view.xml
Labels: approved, bot is merging ⏳

#2119 [14.0][MIG] l10n_es_payment_order_confirming_sabadell: Migration to 14.0
  l10n_es_payment_order_confirming_sabadell/README.rst
  l10n_es_payment_order_confirming_sabadell/__init__.py
  l10n_es_payment_order_confirming_sabadell/__manifest__.py
  l10n_es_payment_order_confirming_sabadell/data/account_payment_method.xml
  l10n_es_payment_order_confirming_sabadell/i18n/ca.po
  l10n_es_payment_order_confirming_sabadell/i18n/es.po
  l10n_es_payment_order_confirming_sabadell/i18n/l10n_es_payment_order_confirming_sabadell.pot
  l10n_es_payment_order_confirming_sabadell/models/__init__.py
  l10n_es_payment_order_confirming_sabadell/models/account_payment_mode.py
  l10n_es_payment_order_confirming_sabadell/models/account_payment_order.py
  l10n_es_payment_order_confirming_sabadell/models/confirming_sabadell.py
  l10n_es_payment_order_confirming_sabadell/readme/CONFIGURE.rst
  l10n_es_payment_order_confirming_sabadell/readme/CONTRIBUTORS.rst
  l10n_es_payment_order_confirming_sabadell/readme/DESCRIPTION.rst
  l10n_es_payment_order_confirming_sabadell/readme/USAGE.rst
  l10n_es_payment_order_confirming_sabadell/static/description/icon.png
  l10n_es_payment_order_confirming_sabadell/static/description/index.html
  l10n_es_payment_order_confirming_sabadell/tests/__init__.py
  l10n_es_payment_order_confirming_sabadell/tests/test_payment_order_confirming_sabadell.py
  l10n_es_payment_order_confirming_sabadell/views/account_payment_mode_view.xml
  setup/l10n_es_payment_order_confirming_sabadell/odoo/addons/l10n_es_payment_order_confirming_sabadell
  setup/l10n_es_payment_order_confirming_sabadell/setup.py
Labels: bot is merging ⏳

#2470 [IMP] l10n_es_aeat_mod303_extra_data: add missing taxes
  l10n_es_aeat_mod303_extra_data/__manifest__.py
  l10n_es_aeat_mod303_extra_data/data/l10n_es_aeat_map_tax_line.xml
  l10n_es_aeat_mod303_extra_data/i18n/l10n_es_aeat_mod303_extra_data.pot
  l10n_es_aeat_mod303_extra_data/static/description/icon.png
  l10n_es_aeat_mod303_extra_data/static/description/index.html
Labels: approved, bot is merging ⏳

#2373 [13.0][IMP+FIX] delivery_seur: Add seur_use_packages_from_picking field in carrier to use (or not) package from pickings + Set the correct weight if we use packages.
  delivery_seur/i18n/delivery_seur.pot
  delivery_seur/i18n/es.po
  delivery_seur/models/delivery_carrier.py
  delivery_seur/models/seur_request.py
  delivery_seur/views/delivery_carrier_views.xml
Labels: approved, bot is merging ⏳

#2473 [14.0][FIX] l10n_es_facturae_face: Change to the correct field name to fix tests.
  l10n_es_facturae_face/tests/test_facturae_face.py
Labels: bot is merging ⏳

#2472 [MIG] delivery_seur: Migration to 14.0
  delivery_seur/README.rst
  delivery_seur/__init__.py
  delivery_seur/__manifest__.py
  delivery_seur/doc/SEUR_Track_and_Tracing_Webservice.doc
  delivery_seur/doc/Servicios_WEB_Seur.doc
  delivery_seur/doc/WS_Cancelation_and_Modification_shipments_webservice.doc
  delivery_seur/doc/WebServices_Integration_Process_ENG_PDF.docx
  delivery_seur/doc/WebServices_Integration_Process_ENG_ZEBRA.docx
  delivery_seur/i18n/ca.po
  delivery_seur/i18n/delivery_seur.pot
  delivery_seur/i18n/es.po
  delivery_seur/models/__init__.py
  delivery_seur/models/delivery_carrier.py
  delivery_seur/models/seur_request.py
  delivery_seur/readme/CONTRIBUTORS.rst
  delivery_seur/readme/DESCRIPTION.rst
  delivery_seur/readme/USAGE.rst
  delivery_seur/static/description/icon.png
  delivery_seur/static/description/index.html
  delivery_seur/tests/__init__.py
  delivery_seur/tests/test_delivery_seur.py
  delivery_seur/views/delivery_carrier_views.xml
  setup/delivery_seur/odoo/addons/delivery_seur
  setup/delivery_seur/setup.py
Labels: bot is merging ⏳
