Repository OCA/l10n-spain, pull requests merged in 2022-01, with the labels that each got.

#1955 [12.0][IMP] l10n_es_ticketbai and l10n_es_ticketbai_api: Add missing tests
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai_api/demo/res_partner_demo.xml
  l10n_es_ticketbai_api/static/src/img/derbi.png
  l10n_es_ticketbai_api/static/src/img/peugeot.png
  l10n_es_ticketbai_api/tests/__init__.py
  l10n_es_ticketbai_api/tests/certs/ciudadano_act.p12
  l10n_es_ticketbai_api/tests/certs/ciudadano_act_p12_password.txt
  l10n_es_ticketbai_api/tests/common.py
  l10n_es_ticketbai_api/tests/company.json
Labels: bot is merging ⏳

#1956 [12.0][FIX] l10n_es_ticketbai: Add support for 'IVA Exento Repercutido Sujeto'
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/data/account_fiscal_position_template.xml
  l10n_es_ticketbai/migrations/12.0.2.3.0/post-migrate.py
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
Labels: bot is merging ⏳

#1920 [12.0][FIX] delivery_gls_asm: Escape destination street
  delivery_gls_asm/models/delivery_carrier.py
Labels: bot is merging ⏳

#1895 [MIG] l10n_es_aeat_sii_oss: Migration to 14.0
  l10n_es_aeat_sii_oss/README.rst
  l10n_es_aeat_sii_oss/__init__.py
  l10n_es_aeat_sii_oss/__manifest__.py
  l10n_es_aeat_sii_oss/data/aeat_sii_mapping_registration_keys_data.xml
  l10n_es_aeat_sii_oss/i18n/l10n_es_aeat_sii_oss.pot
  l10n_es_aeat_sii_oss/models/__init__.py
  l10n_es_aeat_sii_oss/models/account_move.py
  l10n_es_aeat_sii_oss/readme/CONFIGURE.rst
  l10n_es_aeat_sii_oss/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_oss/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_oss/readme/INSTALL.rst
  l10n_es_aeat_sii_oss/static/description/icon.png
  l10n_es_aeat_sii_oss/static/description/icon_source.svg
  l10n_es_aeat_sii_oss/static/description/index.html
  l10n_es_aeat_sii_oss/tests/__init__.py
  l10n_es_aeat_sii_oss/tests/test_l10n_es_aeat_sii.py
  setup/l10n_es_aeat_sii_oss/odoo/addons/l10n_es_aeat_sii_oss
  setup/l10n_es_aeat_sii_oss/setup.py
Labels: bot is merging ⏳

#1888 [IMP] l10n_es_facturae: Use queue
  l10n_es_facturae/components/account_move_l10n_es_facturae_listener.py
  l10n_es_facturae_face/tests/test_facturae_face.py
Labels: bot is merging ⏳

#1985 [FIX] l10n_es_aeat_mod349: gestión incorrecta del valor de la resta
  l10n_es_aeat_mod349/models/mod349.py
Labels: bot is merging ⏳

#1974 [MIG] l10n_es_aeat_mod349: Migration to 15.0
  l10n_es_aeat/models/res_company.py
  l10n_es_aeat_mod349/README.rst
  l10n_es_aeat_mod349/__init__.py
  l10n_es_aeat_mod349/__manifest__.py
  l10n_es_aeat_mod349/data/aeat_349_map_data.xml
  l10n_es_aeat_mod349/data/aeat_export_mod349_data.xml
  l10n_es_aeat_mod349/data/aeat_export_mod349_partner_data.xml
  l10n_es_aeat_mod349/data/aeat_export_mod349_partner_refund_data.xml
  l10n_es_aeat_mod349/docs/BOE-A-2010-5098.pdf
  l10n_es_aeat_mod349/docs/NREG-349-2016.docx
  l10n_es_aeat_mod349/i18n/es.po
  l10n_es_aeat_mod349/i18n/l10n_es_aeat_mod349.pot
  l10n_es_aeat_mod349/models/__init__.py
  l10n_es_aeat_mod349/models/account_move.py
  l10n_es_aeat_mod349/models/account_tax.py
  l10n_es_aeat_mod349/models/account_tax_template.py
  l10n_es_aeat_mod349/models/aeat_349_map_line.py
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod349/readme/DESCRIPTION.rst
  l10n_es_aeat_mod349/readme/ROADMAP.rst
  l10n_es_aeat_mod349/readme/USAGE.rst
  l10n_es_aeat_mod349/report/aeat_mod349.xml
  l10n_es_aeat_mod349/report/common_templates.xml
  l10n_es_aeat_mod349/report/report_views.xml
  l10n_es_aeat_mod349/security/ir.model.access.csv
  l10n_es_aeat_mod349/security/mod_349_security.xml
  l10n_es_aeat_mod349/static/description/icon.png
  l10n_es_aeat_mod349/static/description/icon_source.svg
  l10n_es_aeat_mod349/static/description/index.html
  l10n_es_aeat_mod349/tests/__init__.py
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
  l10n_es_aeat_mod349/views/account_move_view.xml
  l10n_es_aeat_mod349/views/account_tax_view.xml
  l10n_es_aeat_mod349/views/aeat_349_map_view.xml
  l10n_es_aeat_mod349/views/mod349_view.xml
  setup/l10n_es_aeat_mod349/odoo/addons/l10n_es_aeat_mod349
  setup/l10n_es_aeat_mod349/setup.py
Labels: bot is merging ⏳

#1983 [FIX] l10n_es_ticketbai_api - use commercial_partner_id
  l10n_es_ticketbai_api/models/res_partner.py
Labels: approved, bot is merging ⏳

#1987 [12.0][FIX] l10n_es_ticketbai_api use commercial partner and delete validation error if name longer than 120 chars
  l10n_es_ticketbai_api/models/res_partner.py
Labels: bot is merging ⏳

#1990 [13.0][FIX] l10n_es_ticketbai_api use commercial partner
  l10n_es_ticketbai_api/models/res_partner.py
Labels: bot is merging ⏳

#1978 [13.0][IMP] l10n_es_ticketbai_api: simplify document schema validation.
  l10n_es_ticketbai_api/ticketbai/xml_schema.py
Labels: bot is merging ⏳

#1994 [13.0][IMP] l10n_es_ticketbai_api Update Tax Agency Rest Api response codes
  l10n_es_ticketbai_api/models/ticketbai_response.py
Labels: bot is merging ⏳

#1991 [14.0][FIX] l10n_es_ticketbai_api use commercial partner
  l10n_es_ticketbai_api/models/res_partner.py
Labels: bot is merging ⏳

#1989 [11.0][FIX] Check 'Incorrect' state of LROE not to retry sending
  l10n_es_ticketbai_api_batuz/models/lroe_operation_response.py
Labels: bot is merging ⏳

#1992 [13.0][FIX] l10n_es_ticketbai_api Remove access to tbai.certificate for gro…
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
  l10n_es_ticketbai_api/security/ir.model.access.csv
  l10n_es_ticketbai_api/tests/common.py
Labels: bot is merging ⏳

#1932 [11.0][IMP] Add multi-company rule for ticketbai invoices
  l10n_es_ticketbai_api/__manifest__.py
  l10n_es_ticketbai_api/security/l10n_es_ticketbai_security.xml
Labels: bot is merging ⏳

#1999 [FIX] delivery_gls_asm: escaped int
  delivery_gls_asm/models/delivery_carrier.py
Labels: bot is merging ⏳

#1996 [13.0][IMP] l10n_es_ticketbai_api: Move XML schema dir to tests and make usa…
  l10n_es_ticketbai_api/tests/common.py
  l10n_es_ticketbai_api/tests/schemas/XAdES01903v132-201601.xsd
  l10n_es_ticketbai_api/tests/schemas/XAdES01903v141-201601.xsd
  l10n_es_ticketbai_api/tests/schemas/XMLSchema.xsd
  l10n_es_ticketbai_api/tests/schemas/catalog.xml
  l10n_es_ticketbai_api/tests/schemas/v1.0/Anula_ticketBai V1-0.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.0/TicketBAI_Especificaciones.pdf
  l10n_es_ticketbai_api/tests/schemas/v1.0/TicketBAI_Política_firma_1_0.pdf
  l10n_es_ticketbai_api/tests/schemas/v1.0/response.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.0/ticketBai V1-0.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.1/Anula_ticketBai V1-1.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.1/TicketBAI_Especificaciones_v_1_1.pdf
  l10n_es_ticketbai_api/tests/schemas/v1.1/test_Anula_ticketBai V1-1.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.1/test_ticketBai V1-1.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.1/ticketBai V1-1.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.2/Anula_ticketBai V1-2.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.2/TBAI_Descripción_Servicios_Rest Gipuzkoa v_0_2.pdf
  l10n_es_ticketbai_api/tests/schemas/v1.2/TicketBAIResponse.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.2/TicketBAI_Especificaciones funcionales y técnicas_1_2.pdf
  l10n_es_ticketbai_api/tests/schemas/v1.2/test_Anula_ticketBai V1-2.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.2/test_ticketBai V1-2.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.2/ticketBai V1-2.xsd
  l10n_es_ticketbai_api/tests/schemas/xmldsig-core-schema.xsd
Labels: bot is merging ⏳

#2004 [13.0][FIX] l10n_es_aeat_mod347: Don't include cancel and draft moves
  l10n_es_aeat_mod347/models/mod347.py
  l10n_es_aeat_mod347/tests/test_l10n_es_aeat_mod347.py
Labels: bot is merging ⏳

#2009 [13.0][FIX] l10n_es_ticketbai: Add support for 'IVA Exento Repercutido Sujeto
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/data/account_fiscal_position_template.xml
  l10n_es_ticketbai/migrations/13.0.1.2.0/post-migrate.py
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
Labels: bot is merging ⏳

#1993 [13.0][FIX] l10n_es_ticketbai_api If an invoice substitutes simplified invo…
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
Labels: bot is merging ⏳

#2007 [13.0][IMP] l10n_es_ticketbai_api: Save warning messages from IRS also when …
  l10n_es_ticketbai_api/models/ticketbai_response.py
Labels: bot is merging ⏳

#1906 [13.0][IMP] l10n_es_aeat_sii_oca + l10n_es_facturae: Add thirdparty fields to allow inheritance in other addons.
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/migrations/13.0.1.7.0/pre-migration.py
  l10n_es_aeat_sii_oca/models/__init__.py
  l10n_es_aeat_sii_oca/models/account_journal.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
  l10n_es_aeat_sii_oca/views/account_move_views.xml
  l10n_es_facturae/models/__init__.py
  l10n_es_facturae/models/account_journal.py
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/tests/common.py
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#1909 [14.0][FIX] l10n_es_pos: Cambio del campos pos_reference <> l10n_es_unique_id
  l10n_es_pos/__manifest__.py
  l10n_es_pos/migrations/14.0.2.1.0/pre-migration.py
  l10n_es_pos/models/pos_order.py
  l10n_es_pos/static/src/js/Screens/OrderManagementScreen/OrderManagementControlPanel.js
  l10n_es_pos/static/src/js/Screens/OrderManagementScreen/OrderRow.js
  l10n_es_pos/static/src/js/models.js
  l10n_es_pos/static/src/xml/Screens/OrderManagementScreen/OrderList.xml
  l10n_es_pos/static/src/xml/Screens/OrderManagementScreen/OrderRow.xml
  l10n_es_pos/static/src/xml/pos.xml
  l10n_es_pos/views/pos_templates.xml
  l10n_es_pos/views/pos_views.xml
Labels: approved, bot is merging ⏳

#1986 [13.0][IMP] l10n_es_ticketbai: refund invoice without having a tbai.invoice…
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/ticketbai_invoice.py
  l10n_es_ticketbai/security/ir.model.access.csv
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/account_move_views.xml
Labels: bot is merging ⏳

#2016 [14.0][IMP] l10n_es_aeat_sii_oca + l10n_es_facturae: Add thirdparty fields to allow inheritance in other addons.
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/migrations/14.0.1.9.0/pre-migration.py
  l10n_es_aeat_sii_oca/models/__init__.py
  l10n_es_aeat_sii_oca/models/account_journal.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
  l10n_es_aeat_sii_oca/views/account_move_views.xml
  l10n_es_facturae/models/__init__.py
  l10n_es_facturae/models/account_journal.py
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/tests/common.py
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#2020 [14.0][FIX] l10n_es_aeat_sii_oca + l10n_es_facturae: Fix fields_view_get() function.
  l10n_es_aeat_sii_oca/models/account_journal.py
  l10n_es_facturae/models/account_journal.py
Labels: bot is merging ⏳

#2021 [FIX] l10n_es_aeat_mod303: Last BOE export inaccuracies
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/aeat.model.export.config.line.csv
Labels: bot is merging ⏳

#2015 [11.0][FIX] l10n_es_ticketbai_api: Call make_image function correctly
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
Labels: approved, bot is merging ⏳

#1965 [12.0][IMP] l10n_es_ticketbai: Allow the user to say that the line detail i…
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/res_company_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2023 [11.0][FIX] Obtain company correctly when creating invoice
  l10n_es_ticketbai/models/account_invoice.py
Labels: bot is merging ⏳

#1919 [13.0][IMP] journals can be configured so that they don't send invoices to tax agency
  l10n_es_ticketbai/README.rst
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/models/account_journal.py
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/account_journal_views.xml
  l10n_es_ticketbai/views/account_move_views.xml
Labels: approved, bot is merging ⏳

#2027 [14.0][MIG] l10n_es_location_nuts: Migration to 14.0
  l10n_es_location_nuts/README.rst
  l10n_es_location_nuts/__init__.py
  l10n_es_location_nuts/__manifest__.py
  l10n_es_location_nuts/hooks.py
  l10n_es_location_nuts/i18n/es.po
  l10n_es_location_nuts/i18n/l10n_es_location_nuts.pot
  l10n_es_location_nuts/readme/CONFIGURE.rst
  l10n_es_location_nuts/readme/CONTRIBUTORS.rst
  l10n_es_location_nuts/readme/DESCRIPTION.rst
  l10n_es_location_nuts/readme/USAGE.rst
  l10n_es_location_nuts/static/description/icon.png
  l10n_es_location_nuts/static/description/index.html
  l10n_es_location_nuts/wizard/__init__.py
  l10n_es_location_nuts/wizard/nuts_import.py
  setup/l10n_es_location_nuts/odoo/addons/l10n_es_location_nuts
  setup/l10n_es_location_nuts/setup.py
Labels: bot is merging ⏳

#2026 [14.0][IMP] l10n_es_ticketbai_api: simplify document schema validation.
  l10n_es_ticketbai_api/ticketbai/xml_schema.py
Labels: bot is merging ⏳

#1998 [8.0][MIG] l10n_es_aeat_mod303_oss: Migration to 8.0
  l10n_es_aeat_mod303_oss/README.rst
  l10n_es_aeat_mod303_oss/__init__.py
  l10n_es_aeat_mod303_oss/__openerp__.py
  l10n_es_aeat_mod303_oss/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_mod303_oss/models/__init__.py
  l10n_es_aeat_mod303_oss/models/mod303.py
  l10n_es_aeat_mod303_oss/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303_oss/readme/DESCRIPTION.rst
  l10n_es_aeat_mod303_oss/static/description/icon.png
  l10n_es_aeat_mod303_oss/static/description/icon_source.svg
  l10n_es_aeat_mod303_oss/static/description/index.html
Labels: bot is merging ⏳

#2006 [11.0][FIX] l10n_es_ticketbai - añadidos impuestos al mapeo no sujeto repercutido servicios
  l10n_es_ticketbai/data/tax_map_data.xml
Labels: approved, bot is merging ⏳

#2035 [14.0][IMP] l10n_es_ticketbai_api: Update Tax Agency Rest Api response codes
  l10n_es_ticketbai_api/models/ticketbai_response.py
Labels: bot is merging ⏳

#2030 [8.0][FIX] l10n_es_aeat_mod303: Last BOE export inaccuracies
  l10n_es_aeat_mod303/__openerp__.py
  l10n_es_aeat_mod303/data/202107/aeat.model.export.config.line.csv
Labels: bot is merging ⏳

#2036 [14.0][IMP] l10n_es_ticketbai_api: Move XML schema dir to tests and make usa…
  l10n_es_ticketbai_api/tests/common.py
  l10n_es_ticketbai_api/tests/schemas/XAdES01903v132-201601.xsd
  l10n_es_ticketbai_api/tests/schemas/XAdES01903v141-201601.xsd
  l10n_es_ticketbai_api/tests/schemas/XMLSchema.xsd
  l10n_es_ticketbai_api/tests/schemas/catalog.xml
  l10n_es_ticketbai_api/tests/schemas/v1.0/Anula_ticketBai V1-0.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.0/TicketBAI_Especificaciones.pdf
  l10n_es_ticketbai_api/tests/schemas/v1.0/TicketBAI_Política_firma_1_0.pdf
  l10n_es_ticketbai_api/tests/schemas/v1.0/response.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.0/ticketBai V1-0.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.1/Anula_ticketBai V1-1.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.1/TicketBAI_Especificaciones_v_1_1.pdf
  l10n_es_ticketbai_api/tests/schemas/v1.1/test_Anula_ticketBai V1-1.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.1/test_ticketBai V1-1.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.1/ticketBai V1-1.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.2/Anula_ticketBai V1-2.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.2/TBAI_Descripción_Servicios_Rest Gipuzkoa v_0_2.pdf
  l10n_es_ticketbai_api/tests/schemas/v1.2/TicketBAIResponse.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.2/TicketBAI_Especificaciones funcionales y técnicas_1_2.pdf
  l10n_es_ticketbai_api/tests/schemas/v1.2/test_Anula_ticketBai V1-2.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.2/test_ticketBai V1-2.xsd
  l10n_es_ticketbai_api/tests/schemas/v1.2/ticketBai V1-2.xsd
  l10n_es_ticketbai_api/tests/schemas/xmldsig-core-schema.xsd
Labels: bot is merging ⏳

#2034 [14.0][FIX] l10n_es_ticketbai_api: Remove access to tbai.certificate for gro…
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
  l10n_es_ticketbai_api/security/ir.model.access.csv
  l10n_es_ticketbai_api/tests/common.py
Labels: bot is merging ⏳

#1675 [14.0][MIG] delivery_gls_asm: Migration to 14.0
  delivery_gls_asm/README.rst
  delivery_gls_asm/__init__.py
  delivery_gls_asm/__manifest__.py
  delivery_gls_asm/api/gls_asm_api.wsdl
  delivery_gls_asm/data/delivery_asm_data.xml
  delivery_gls_asm/i18n/ca.po
  delivery_gls_asm/i18n/delivery_gls_asm.pot
  delivery_gls_asm/i18n/es.po
  delivery_gls_asm/models/__init__.py
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/models/gls_asm_request.py
  delivery_gls_asm/models/stock_picking.py
  delivery_gls_asm/readme/CONFIGURE.rst
  delivery_gls_asm/readme/CONTRIBUTORS.rst
  delivery_gls_asm/readme/DESCRIPTION.rst
  delivery_gls_asm/readme/INSTALL.rst
  delivery_gls_asm/readme/ROADMAP.rst
  delivery_gls_asm/readme/USAGE.rst
  delivery_gls_asm/security/ir.model.access.csv
  delivery_gls_asm/static/description/icon.png
  delivery_gls_asm/static/description/icon.svg
  delivery_gls_asm/static/description/index.html
  delivery_gls_asm/tests/__init__.py
  delivery_gls_asm/tests/test_delivery_gls_asm.py
  delivery_gls_asm/views/delivery_asm_view.xml
  delivery_gls_asm/views/gls_asm_manifest_template.xml
  delivery_gls_asm/views/stock_picking_views.xml
  delivery_gls_asm/wizard/__init__.py
  delivery_gls_asm/wizard/gls_asm_manifest_wizard.py
  delivery_gls_asm/wizard/gls_asm_manifest_wizard_views.xml
  requirements.txt
  setup/delivery_gls_asm/odoo/addons/delivery_gls_asm
  setup/delivery_gls_asm/setup.py
Labels: bot is merging ⏳

#2055 [12.0][IMP] l10n_es_aeat_sii: Se añade nuevo mapeo para el SII
  l10n_es_aeat_sii/data/aeat_sii_map_data.xml
  l10n_es_aeat_sii/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#2058 [12.0][FIX] l10n_es_aeat_mod390: Ajuste de impuestos
  l10n_es_aeat_mod390/data/aeat_export_mod390_2021_sub06_data.xml
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
Labels: approved, bot is merging ⏳

#2051 [13.0][FIX] payment_redsys: JSON request
  payment_redsys/models/redsys.py
Labels: approved, bot is merging ⏳

#2062 [13.0][IMP] l10n_es_aeat_mod390: Nuevo formato de exportación BOE 2021
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_main_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub01_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub02_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub03_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub04_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub05_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub06_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub07_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2018_sub08_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_main_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub01_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub02_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub03_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub04_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub05_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub07_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub08_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_main_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub01_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub02_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub03_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub04_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub05_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub06_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub07_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_sub08_data.xml
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
Labels: bot is merging ⏳

#2065 [10.0][MIG]l10n_es_aeat_mod303_oss
  l10n_es_aeat_mod303_oss/README.rst
  l10n_es_aeat_mod303_oss/__init__.py
  l10n_es_aeat_mod303_oss/__manifest__.py
  l10n_es_aeat_mod303_oss/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_mod303_oss/i18n/l10n_es_aeat_mod303_oss.pot
  l10n_es_aeat_mod303_oss/models/__init__.py
  l10n_es_aeat_mod303_oss/models/mod303.py
  l10n_es_aeat_mod303_oss/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303_oss/readme/DESCRIPTION.rst
  l10n_es_aeat_mod303_oss/static/description/icon.png
  l10n_es_aeat_mod303_oss/static/description/icon_source.svg
  l10n_es_aeat_mod303_oss/static/description/index.html
  oca_dependencies.txt
Labels: approved, bot is merging ⏳

#2050 [14.0][FIX] l10n_es_ticketbai: Add support for 'IVA Exento Repercutido Sujeto
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/data/account_fiscal_position_template.xml
  l10n_es_ticketbai/migrations/14.0.1.2.0/post-migrate.py
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
Labels: bot is merging ⏳

#2048 [14.0][FIX] l10n_es_ticketbai_api If an invoice substitutes simplified invo…
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
Labels: bot is merging ⏳
