Repository OCA/l10n-spain, pull requests merged in 2022-04, with the labels that each got.

#2196 [15.0][MIG] l10n_es_aeat_mod390
  l10n_es_aeat_mod390/README.rst
  l10n_es_aeat_mod390/__init__.py
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_main_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub01_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub02_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub03_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub04_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub05_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub06_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub07_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub08_data.xml
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/docs/dr390e2017v3.xlsx
  l10n_es_aeat_mod390/docs/dr390e2018.xlsx
  l10n_es_aeat_mod390/docs/dr390e2019v100.xlsx
  l10n_es_aeat_mod390/docs/instr390.pdf
  l10n_es_aeat_mod390/i18n/ca.po
  l10n_es_aeat_mod390/i18n/es.po
  l10n_es_aeat_mod390/i18n/l10n_es_aeat_mod390.pot
  l10n_es_aeat_mod390/models/__init__.py
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod390/readme/DESCRIPTION.rst
  l10n_es_aeat_mod390/readme/INSTALL.rst
  l10n_es_aeat_mod390/readme/ROADMAP.rst
  l10n_es_aeat_mod390/readme/USAGE.rst
  l10n_es_aeat_mod390/security/ir.model.access.csv
  l10n_es_aeat_mod390/security/l10n_es_aeat_mod390_security.xml
  l10n_es_aeat_mod390/static/description/icon.png
  l10n_es_aeat_mod390/static/description/icon.svg
  l10n_es_aeat_mod390/static/description/index.html
  l10n_es_aeat_mod390/tests/__init__.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
  l10n_es_aeat_mod390/views/mod390_view.xml
  setup/l10n_es_aeat_mod390/odoo/addons/l10n_es_aeat_mod390
  setup/l10n_es_aeat_mod390/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2226 [15.0][IMP]l10n_es_mis_report: actualizado 'balance de pymes' y 'perd…
  l10n_es_mis_report/data/mis_report_balance_abreviated.xml
  l10n_es_mis_report/data/mis_report_balance_sme.xml
  l10n_es_mis_report/data/mis_report_pyg_abreviated.xml
  l10n_es_mis_report/data/mis_report_pyg_sme.xml
  l10n_es_mis_report/readme/CONTRIBUTORS.rst
  l10n_es_mis_report/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#2225 [13.0][IMP]l10n_es_mis_report: actualizado 'balance de pymes' y 'perdidas y…
  l10n_es_mis_report/data/mis_report_balance_abreviated.xml
  l10n_es_mis_report/data/mis_report_balance_sme.xml
  l10n_es_mis_report/data/mis_report_pyg_abreviated.xml
  l10n_es_mis_report/data/mis_report_pyg_sme.xml
  l10n_es_mis_report/readme/CONTRIBUTORS.rst
  l10n_es_mis_report/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#2227 [15.0][MIG]l10n_es_vat_book_oss
  l10n_es_vat_book_oss/README.rst
  l10n_es_vat_book_oss/__init__.py
  l10n_es_vat_book_oss/__manifest__.py
  l10n_es_vat_book_oss/i18n/l10n_es_vat_book_oss.pot
  l10n_es_vat_book_oss/models/__init__.py
  l10n_es_vat_book_oss/models/aeat_vat_book_map_lines.py
  l10n_es_vat_book_oss/models/l10n_es_vat_book.py
  l10n_es_vat_book_oss/readme/CONFIGURE.rst
  l10n_es_vat_book_oss/readme/CONTRIBUTORS.rst
  l10n_es_vat_book_oss/readme/DESCRIPTION.rst
  l10n_es_vat_book_oss/readme/INSTALL.rst
  l10n_es_vat_book_oss/readme/ROADMAP.rst
  l10n_es_vat_book_oss/readme/USAGE.rst
  l10n_es_vat_book_oss/static/description/icon.png
  l10n_es_vat_book_oss/static/description/index.html
  setup/l10n_es_vat_book_oss/odoo/addons/l10n_es_vat_book_oss
  setup/l10n_es_vat_book_oss/setup.py
Labels: approved, bot is merging ⏳

#2228 [15.0][MIG]l10n_es_aeat_mod303_oss
  l10n_es_aeat_mod303_oss/README.rst
  l10n_es_aeat_mod303_oss/__init__.py
  l10n_es_aeat_mod303_oss/__manifest__.py
  l10n_es_aeat_mod303_oss/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_mod303_oss/i18n/ca.po
  l10n_es_aeat_mod303_oss/models/__init__.py
  l10n_es_aeat_mod303_oss/models/mod303.py
  l10n_es_aeat_mod303_oss/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303_oss/readme/DESCRIPTION.rst
  l10n_es_aeat_mod303_oss/static/description/icon.png
  l10n_es_aeat_mod303_oss/static/description/icon_source.svg
  l10n_es_aeat_mod303_oss/static/description/index.html
  l10n_es_aeat_mod303_oss/tests/__init__.py
  l10n_es_aeat_mod303_oss/tests/test_l10n_es_aeat_mod303_oss.py
  setup/l10n_es_aeat_mod303_oss/odoo/addons/l10n_es_aeat_mod303_oss
  setup/l10n_es_aeat_mod303_oss/setup.py
Labels: approved, bot is merging ⏳

#2232 [8.0][FIX] l10n_es_aeat_mod303: Error fichero 303 2022
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
Labels: bot is merging ⏳

#2146 [13.0][IMP] l10n_es_facturae: Fix Invoice class calculation
  l10n_es_facturae/views/report_facturae.xml
Labels: approved, bot is merging ⏳

#2234 [13.0][FIX+IMP] l10n_es_vat_book: Filter accounts only for the restricted taxes + regression tests
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/tests/test_l10n_es_aeat_vat_book.py
Labels: bot is merging ⏳

#2024 [IMP] l10n_es_aeat_sii_oca: Mejorar deteccion de VAT
  l10n_es_aeat/models/res_partner.py
  l10n_es_aeat/tests/test_l10n_es_aeat.py
  l10n_es_aeat/views/res_partner_view.xml
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/models/res_partner.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: bot is merging ⏳

#2241 [15.0][IMP] l10n_es_aeat_sii_oca: Mejorar deteccion de VAT
  l10n_es_aeat/models/res_partner.py
  l10n_es_aeat/tests/test_l10n_es_aeat.py
  l10n_es_aeat/views/res_partner_view.xml
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/models/res_partner.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: approved, bot is merging ⏳

#2240 [14.0][IMP] l10n_es_aeat_sii_oca: Mejorar deteccion de VAT
  l10n_es_aeat/models/res_partner.py
  l10n_es_aeat/tests/test_l10n_es_aeat.py
  l10n_es_aeat/views/res_partner_view.xml
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/models/res_partner.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: approved, bot is merging ⏳

#2235 [15.0][FIX] l10n_es_vat_book: UX Improvements
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/report/vat_book_xlsx.py
  l10n_es_vat_book/views/l10n_es_vat_book.xml
Labels: approved, bot is merging ⏳

#2242 [14.0][BKP] UX Improvements
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/report/vat_book_xlsx.py
  l10n_es_vat_book/views/l10n_es_vat_book.xml
Labels: approved, bot is merging ⏳

#2244 [15.0][FIX] l10n_es_facturae_face: changes the way the 'inbound_payment_method_line_ids' is entered in the journal in the tests.
  l10n_es_facturae_face/tests/test_facturae_face.py
Labels: approved, bot is merging ⏳

#2243 [15.0][FIX] l10n_es_facturae: changes the way the 'inbound_payment_me…
  l10n_es_facturae/tests/common.py
Labels: approved, bot is merging ⏳

#2236 [15.0][MIG] l10n_es_account_banking_sepa_fsdd: Migration to 15.0
  l10n_es_account_banking_sepa_fsdd/README.rst
  l10n_es_account_banking_sepa_fsdd/__init__.py
  l10n_es_account_banking_sepa_fsdd/__manifest__.py
  l10n_es_account_banking_sepa_fsdd/i18n/ca.po
  l10n_es_account_banking_sepa_fsdd/i18n/es.po
  l10n_es_account_banking_sepa_fsdd/i18n/es_ES.po
  l10n_es_account_banking_sepa_fsdd/i18n/fr.po
  l10n_es_account_banking_sepa_fsdd/i18n/l10n_es_account_banking_sepa_fsdd.pot
  l10n_es_account_banking_sepa_fsdd/i18n/nl.po
  l10n_es_account_banking_sepa_fsdd/i18n/pt_BR.po
  l10n_es_account_banking_sepa_fsdd/i18n/sl.po
  l10n_es_account_banking_sepa_fsdd/models/__init__.py
  l10n_es_account_banking_sepa_fsdd/models/account_payment_mode.py
  l10n_es_account_banking_sepa_fsdd/models/account_payment_order.py
  l10n_es_account_banking_sepa_fsdd/readme/CONFIGURE.rst
  l10n_es_account_banking_sepa_fsdd/readme/CONTRIBUTORS.rst
  l10n_es_account_banking_sepa_fsdd/readme/DESCRIPTION.rst
  l10n_es_account_banking_sepa_fsdd/readme/INSTALL.rst
  l10n_es_account_banking_sepa_fsdd/static/description/icon.png
  l10n_es_account_banking_sepa_fsdd/static/description/index.html
  l10n_es_account_banking_sepa_fsdd/tests/__init__.py
  l10n_es_account_banking_sepa_fsdd/tests/test_l10n_es_account_banking_sepa_fsdd.py
  l10n_es_account_banking_sepa_fsdd/views/payment_mode_view.xml
  setup/l10n_es_account_banking_sepa_fsdd/odoo/addons/l10n_es_account_banking_sepa_fsdd
  setup/l10n_es_account_banking_sepa_fsdd/setup.py
Labels: approved, bot is merging ⏳
