Repository OCA/l10n-spain, pull requests merged in 2022-09, with the labels that each got.

#2188 [13.0][MIG] account_promissory_note_santander
  account_promissory_note_santander/README.rst
  account_promissory_note_santander/__init__.py
  account_promissory_note_santander/__manifest__.py
  account_promissory_note_santander/data/account_promissory_note_report_data.xml
  account_promissory_note_santander/i18n/account_promissory_note_santander.pot
  account_promissory_note_santander/i18n/es.po
  account_promissory_note_santander/readme/CONFIGURE.rst
  account_promissory_note_santander/readme/CONTRIBUTORS.rst
  account_promissory_note_santander/readme/DESCRIPTION.rst
  account_promissory_note_santander/readme/USAGE.rst
  account_promissory_note_santander/report/__init__.py
  account_promissory_note_santander/report/account_promissory_note_writing_report.xml
  account_promissory_note_santander/report/check_print.py
  account_promissory_note_santander/static/description/icon.png
  account_promissory_note_santander/static/description/index.html
  account_promissory_note_santander/views/report_promissory_note.xml
  setup/account_promissory_note_santander/odoo/addons/account_promissory_note_santander
  setup/account_promissory_note_santander/setup.py
Labels: bot is merging ⏳, stale

#2477 [FIX] l10n_es_facturae_face: Fix changes applied on EDI
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_face_listener.py
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_listener.py
  l10n_es_facturae_face/data/edi.xml
  l10n_es_facturae_face/data/face_data.xml
  l10n_es_facturae_face/models/account_move.py
  l10n_es_facturae_face/wizards/edi_l10n_es_facturae_face_cancel.py
Labels: bot is merging ⏳

#2480 [13.0][IMP] Update copier template
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  l10n_es_partner/wizard/l10n_es_partner_wizard.xml
  l10n_es_toponyms/wizard/l10n_es_toponyms_wizard.xml
Labels: bot is merging ⏳

#2479 [13.0][FIX] l10n_es_aeat: Consider correctly French overseas
  l10n_es_aeat/models/res_partner.py
  l10n_es_aeat/tests/test_l10n_es_aeat.py
Labels: approved, bot is merging ⏳

#2485 [15.0][FIX] l10n_es_aeat: Consider correctly French overseas
  l10n_es_aeat/models/res_partner.py
  l10n_es_aeat/tests/test_l10n_es_aeat.py
Labels: bot is merging ⏳

#2474 [FIX]vat regime key now takes code (str 2 digits) instead of id(int)
  l10n_es_ticketbai_pos/static/src/js/tbai_models.js
Labels: bot is merging ⏳

#2486 [14.0][FIX] l10n_es_aeat: Consider correctly French overseas
  l10n_es_aeat/models/res_partner.py
  l10n_es_aeat/tests/test_l10n_es_aeat.py
Labels: bot is merging ⏳

#2487 [FIX] l10n_es_aeat_mod349: broken form UI
  l10n_es_aeat_mod349/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod349/views/mod349_view.xml
Labels: approved, bot is merging ⏳

#2492 [13.0][IMP] l10n_es_ticketbai: Include new tax 5%
  l10n_es_ticketbai/data/tax_map_data.xml
Labels: bot is merging ⏳

#2493 [13.0][IMP] l10n_es_ticketbai_batuz: Include new tax 5%
  l10n_es_ticketbai_batuz/data/tbai_tax_map_data.xml
Labels: bot is merging ⏳

#2491 [FIX]l10n_es_aeat_sii: actualizar url de WSDLs
  l10n_es_aeat_sii/data/aeat_sii_tax_agency_data.xml
Labels: bot is merging ⏳

#2490 [12.0][ADD]l10n_es_ticketbai_batuz_extra_data: new module
  l10n_es_ticketbai_batuz_extra_data/README.rst
  l10n_es_ticketbai_batuz_extra_data/__init__.py
  l10n_es_ticketbai_batuz_extra_data/__manifest__.py
  l10n_es_ticketbai_batuz_extra_data/data/tbai_tax_map_data.xml
  l10n_es_ticketbai_batuz_extra_data/static/description/icon.png
Labels: approved, bot is merging ⏳

#2489 [12.0][ADD]l10n_es_ticketbai_extra_data: new module
  l10n_es_ticketbai_extra_data/README.rst
  l10n_es_ticketbai_extra_data/__init__.py
  l10n_es_ticketbai_extra_data/__manifest__.py
  l10n_es_ticketbai_extra_data/data/tbai_tax_map_data.xml
  l10n_es_ticketbai_extra_data/i18n/l10n_es_ticketbai_extra_data.pot
  l10n_es_ticketbai_extra_data/static/description/icon.png
Labels: approved, bot is merging ⏳

#2496 [14.0][IMP] l10n_es_ticketbai: Include new tax 5%
  l10n_es_ticketbai/data/tax_map_data.xml
Labels: bot is merging ⏳

#2497 [14.0][IMP] l10n_es_ticketbai_batuz: Include new tax 5%
  l10n_es_ticketbai_batuz/data/tbai_tax_map_data.xml
Labels: bot is merging ⏳

#2498 [15.0][IMP] l10n_es_ticketbai_batuz: Include new tax 5%
  l10n_es_ticketbai_batuz/data/tbai_tax_map_data.xml
Labels: bot is merging ⏳

#2499 [11.0][IMP] Update copier template + switch to GH actions
  .copier-answers.yml
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
  l10n_es_account_asset/__manifest__.py
  l10n_es_account_banking_sepa_fsdd/__manifest__.py
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat_certificate/__manifest__.py
  l10n_es_aeat_sii/__manifest__.py
  l10n_es_aeat_sii_oss/__manifest__.py
  l10n_es_aeat_soap/__manifest__.py
  l10n_es_intrastat_report/__manifest__.py
  l10n_es_partner_mercantil/__manifest__.py
  l10n_es_pos/migrations/11.0.2.0.0/pre-migration.py
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai_api/__manifest__.py
  l10n_es_ticketbai_api_batuz/__manifest__.py
  l10n_es_ticketbai_pos/__manifest__.py
  l10n_es_toponyms/gen_src/gen_toponyms_geonames.py
  payment_redsys/__manifest__.py
Labels: bot is merging ⏳

#2478 [MIG][15.0] migration l10n_es_ticketbai_pos to v15
  l10n_es_ticketbai_pos/README.rst
  l10n_es_ticketbai_pos/__init__.py
  l10n_es_ticketbai_pos/__manifest__.py
  l10n_es_ticketbai_pos/i18n/es.po
  l10n_es_ticketbai_pos/i18n/eu.po
  l10n_es_ticketbai_pos/i18n/l10n_es_ticketbai_pos.pot
  l10n_es_ticketbai_pos/models/__init__.py
  l10n_es_ticketbai_pos/models/account_move.py
  l10n_es_ticketbai_pos/models/pos_config.py
  l10n_es_ticketbai_pos/models/pos_order.py
  l10n_es_ticketbai_pos/models/ticketbai_invoice.py
  l10n_es_ticketbai_pos/security/ir.model.access.csv
  l10n_es_ticketbai_pos/static/description/icon.png
  l10n_es_ticketbai_pos/static/lib/qrcode.js
  l10n_es_ticketbai_pos/static/lib/tbai.js
  l10n_es_ticketbai_pos/static/src/img/oca_logo.png
  l10n_es_ticketbai_pos/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  l10n_es_ticketbai_pos/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  l10n_es_ticketbai_pos/static/src/js/Screens/ProductScreen/ProductScreen.js
  l10n_es_ticketbai_pos/static/src/js/db.js
  l10n_es_ticketbai_pos/static/src/js/models.js
  l10n_es_ticketbai_pos/static/src/js/tbai_models.js
  l10n_es_ticketbai_pos/static/src/js/widgets.js
  l10n_es_ticketbai_pos/static/src/xml/pos.xml
  l10n_es_ticketbai_pos/tests/__init__.py
  l10n_es_ticketbai_pos/tests/common.py
  l10n_es_ticketbai_pos/tests/test_l10n_es_ticketbai_pos.py
  l10n_es_ticketbai_pos/views/l10n_es_ticketbai_pos_views.xml
  l10n_es_ticketbai_pos/views/pos_order_views.xml
  l10n_es_ticketbai_pos/views/ticketbai_certificate_views.xml
  setup/l10n_es_ticketbai_pos/odoo/addons/l10n_es_ticketbai_pos
  setup/l10n_es_ticketbai_pos/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2189 [13.0][FIX] l10n_es_partner: Orden incorrecto ignorando funcionalidad res_partner_search_mode
  l10n_es_partner/models/res_partner.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#2466 [11.0][MIG] l10n_es_extra_data
  l10n_es_extra_data/README.rst
  l10n_es_extra_data/__init__.py
  l10n_es_extra_data/__manifest__.py
  l10n_es_extra_data/data/account_data.xml
  l10n_es_extra_data/data/account_tax_data.xml
  l10n_es_extra_data/i18n/l10n_es_extra_data.pot
  l10n_es_extra_data/readme/CONTRIBUTORS.rst
  l10n_es_extra_data/readme/DESCRIPTION.rst
  l10n_es_extra_data/readme/HISTORY.rst
  l10n_es_extra_data/readme/USAGE.rst
  l10n_es_extra_data/static/description/icon.png
  l10n_es_extra_data/static/description/index.html
  setup/l10n_es_extra_data/odoo/addons/l10n_es_extra_data
  setup/l10n_es_extra_data/setup.cfg
  setup/l10n_es_extra_data/setup.py
Labels: approved, bot is merging ⏳

#2504 [14.0][FIX] l10n_es_ticketbai: Make reversed_entry_id field not readonly on…
  l10n_es_ticketbai/views/account_move_views.xml
Labels: approved, bot is merging ⏳

#2505 [15.0][FIX] l10n_es_ticketbai: Make reversed_entry_id field not readonly on…
  l10n_es_ticketbai/views/account_move_views.xml
Labels: bot is merging ⏳

#2508 [14.0][FIX] l10n_es_aeat_sii_oca: admit E3 export exempt cause
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: approved, bot is merging ⏳

#1855 [IMP] l10n_es_facturae: Add disable_edi_auto configuration
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/security/ir.model.access.csv
  l10n_es_facturae/tests/common.py
  l10n_es_facturae/views/account_move_view.xml
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_listener.py
Labels: approved, ready to merge, bot is merging ⏳

#2512 [14.0][FIX] l10n_es_dua_ticketbai_batuz - hacer compatible con módulo l10n_es_dua_sii
  l10n_es_dua_ticketbai_batuz/models/account_move.py
Labels: bot is merging ⏳

#2516 [FIX] l10n_es_aeat: specify cryptography version
  l10n_es_aeat/README.rst
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat/readme/CONTRIBUTORS.rst
  l10n_es_aeat/static/description/index.html
  l10n_es_aeat/wizard/aeat_certificate_password.py
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/readme/INSTALL.rst
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae_face/__manifest__.py
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai_api/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳
