Repository OCA/l10n-spain, pull requests merged in 2022-10, with the labels that each got.

#2469 [11.0][MIG] l10n_es_vat_book_extra_data
  l10n_es_vat_book_extra_data/README.rst
  l10n_es_vat_book_extra_data/__init__.py
  l10n_es_vat_book_extra_data/__manifest__.py
  l10n_es_vat_book_extra_data/data/aeat_vat_book_map_data.xml
  l10n_es_vat_book_extra_data/i18n/l10n_es_vat_book_extra_data.pot
  l10n_es_vat_book_extra_data/readme/CONTRIBUTORS.rst
  l10n_es_vat_book_extra_data/readme/DESCRIPTION.rst
  l10n_es_vat_book_extra_data/static/description/icon.png
  l10n_es_vat_book_extra_data/static/description/index.html
  setup/l10n_es_vat_book_extra_data/odoo/addons/l10n_es_vat_book_extra_data
  setup/l10n_es_vat_book_extra_data/setup.cfg
  setup/l10n_es_vat_book_extra_data/setup.py
Labels: bot is merging ⏳

#2468 [11.0][MIG] l10n_es_aeat_mod303_extra_data
  l10n_es_aeat_mod303_extra_data/README.rst
  l10n_es_aeat_mod303_extra_data/__init__.py
  l10n_es_aeat_mod303_extra_data/__manifest__.py
  l10n_es_aeat_mod303_extra_data/data/2021-07/l10n_es_aeat_map_tax_line.xml
  l10n_es_aeat_mod303_extra_data/i18n/l10n_es_aeat_mod303_extra_data.pot
  l10n_es_aeat_mod303_extra_data/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303_extra_data/readme/DESCRIPTION.rst
  l10n_es_aeat_mod303_extra_data/readme/HISTORY.rst
  l10n_es_aeat_mod303_extra_data/static/description/icon.png
  l10n_es_aeat_mod303_extra_data/static/description/index.html
  setup/l10n_es_aeat_mod303_extra_data/odoo/addons/l10n_es_aeat_mod303_extra_data
  setup/l10n_es_aeat_mod303_extra_data/setup.cfg
  setup/l10n_es_aeat_mod303_extra_data/setup.py
Labels: bot is merging ⏳

#1937 [14.0][IMP] l10n_es_aeat: add settings option to the soap connection
  l10n_es_aeat/models/aeat_soap.py
Labels: approved, bot is merging ⏳, stale

#2467 [11.0][MIG] l10n_es_aeat_sii_extra_data
  l10n_es_aeat_sii_extra_data/README.rst
  l10n_es_aeat_sii_extra_data/__init__.py
  l10n_es_aeat_sii_extra_data/__manifest__.py
  l10n_es_aeat_sii_extra_data/data/aeat_sii_map_data.xml
  l10n_es_aeat_sii_extra_data/i18n/l10n_es_aeat_sii_extra_data.pot
  l10n_es_aeat_sii_extra_data/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_extra_data/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_extra_data/static/description/icon.png
  l10n_es_aeat_sii_extra_data/static/description/index.html
  setup/l10n_es_aeat_sii_extra_data/odoo/addons/l10n_es_aeat_sii_extra_data
  setup/l10n_es_aeat_sii_extra_data/setup.cfg
  setup/l10n_es_aeat_sii_extra_data/setup.py
Labels: bot is merging ⏳

#2519 [14.0][FIX] l10n_es_account_statement_import_n43: Fix tests
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
Labels: bot is merging ⏳

#2523 [15.0][FIX] l10n_es_account_statement_import_n43: Fix tests
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
Labels: bot is merging ⏳

#2511 [IMP] l10n_es_facturae: Allow to use invoice addresses
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/views/report_facturae.xml
  l10n_es_facturae/views/res_partner_view.xml
Labels: bot is merging ⏳

#2524 [FIX] l10n_es_vat_book: missing 5% tax
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#2528 [FIX][15.0] l10n_es_vat_book: missing 5% tax
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#2529 [FIX][14.0] l10n_es_vat_book: missing 5% tax
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#2514 [14.0][FIX] l10n_es_ticketbai* - corregir problemas en entornos multicompany
  l10n_es_ticketbai/wizard/ticketbai_info.py
  l10n_es_ticketbai_api/models/ticketbai_certificate.py
  l10n_es_ticketbai_batuz/models/account_move.py
Labels: approved, bot is merging ⏳

#2530 [FIX][12.0] l10n_es_vat_book: add missing tax in vat book
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#2531 [FIX][13.0] l10n_es_vat_book: add missing tax in vat book
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#2534 [FIX][15.0] l10n_es_vat_book: add missing tax in vat book
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#2532 [FIX][14.0] l10n_es_vat_book: add missing tax in vat book
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#2521 [12.0][IMP] Update copier template + switch to GH actions
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  LICENSE
  README.md
  l10n_es_account_asset/__manifest__.py
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat/i18n/en.po
  l10n_es_aeat/i18n/es.po
  l10n_es_aeat/i18n/l10n_es_aeat.pot
  l10n_es_aeat/views/res_partner_view.xml
  l10n_es_aeat_mod130/i18n/es.po
  l10n_es_aeat_mod130/i18n/l10n_es_aeat_mod130.pot
  l10n_es_aeat_mod130/views/mod130_view.xml
  l10n_es_aeat_partner_check/i18n/ca.po
  l10n_es_aeat_partner_check/i18n/es.po
  l10n_es_aeat_partner_check/i18n/l10n_es_aeat_partner_check.pot
  l10n_es_aeat_partner_check/views/res_partner_view.xml
  l10n_es_aeat_sii/__manifest__.py
  l10n_es_aeat_sii_oss/__manifest__.py
  l10n_es_intrastat_report/__manifest__.py
  l10n_es_ticketbai_api_batuz/__manifest__.py
  l10n_es_ticketbai_pos/__manifest__.py
  payment_redsys/__manifest__.py
Labels: bot is merging ⏳

#2533 [14.0][IMP] l10n_es_facturae: Allow to use invoice addresses
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/views/report_facturae.xml
  l10n_es_facturae/views/res_partner_view.xml
Labels: bot is merging ⏳

#2536 [15.0][IMP] l10n_es_facturae: Allow to use invoice addresses
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/views/report_facturae.xml
  l10n_es_facturae/views/res_partner_view.xml
Labels: bot is merging ⏳

#2517 [12.0][FIX] l10n_es_ticketbai_pos - fix error when some product in tpv is scanned and have ta…
  l10n_es_ticketbai_pos/static/src/js/models.js
Labels: approved, ready to merge, bot is merging ⏳

#2463 [12.0][FIX]l10n_es_ticketbai_batuz: error_canceling_purchase_invoice
  l10n_es_ticketbai_batuz/models/account_invoice.py
  l10n_es_ticketbai_batuz/models/lroe_operation.py
  l10n_es_ticketbai_batuz/views/account_journal_views.xml
Labels: approved, bot is merging ⏳

#2256 [13.0][FIX] l10n_es_aeat: Error when user creates an export line. Missing parent config.
  l10n_es_aeat/views/aeat_export_configuration_view.xml
Labels: bot is merging ⏳, stale

#2522 [FIX] Crypto dependancy: Fix to 2.6.1
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat/tests/test_l10n_es_aeat_certificate.py
  l10n_es_aeat/wizard/aeat_certificate_password.py
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae/reports/report_facturae.py
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/components/webservice_face.py
  l10n_es_facturae_face/models/wsse_signature.py
  l10n_es_ticketbai/models/aeat_certificate.py
  l10n_es_ticketbai/wizard/aeat_certificate_password.py
  l10n_es_ticketbai_api/models/ticketbai_certificate.py
  requirements.txt
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#2538 [14.0][FIX] l10n_es_aeat: Don't error on manually created export lines
  l10n_es_aeat/views/aeat_export_configuration_view.xml
Labels: bot is merging ⏳

#2542 [13.0][IMP] ecoembes: Avoid duplicated code in product reference
  ecoembes/tests/test_ecoembes_misc.py
Labels: bot is merging ⏳

#2543 [FIX] l10n_es_irnr: Development Status Mature
  l10n_es_irnr/README.rst
  l10n_es_irnr/__manifest__.py
Labels: bot is merging ⏳

#2510 [IMP] l10n_es_aeat_partner_check: add new selection
  l10n_es_aeat_partner_check/models/res_partner.py
Labels: approved, bot is merging ⏳

#2549 [13.0][IMP] ecoembes: Add Ecoembes Manager group to manage product.composition records
  ecoembes/__manifest__.py
  ecoembes/i18n/ecoembes.pot
  ecoembes/i18n/es.po
  ecoembes/security/groups.xml
  ecoembes/security/ir.model.access.csv
  ecoembes/tests/common.py
  ecoembes/tests/test_ecoembes_misc.py
  ecoembes/tests/test_ecoembes_wizard.py
  ecoembes/wizard/ecoembes_sig_report_wizard_view.xml
Labels: approved, bot is merging ⏳

#2136 [15.0][MIG] l10n_es_intrastat_report
  l10n_es_intrastat_report/README.rst
  l10n_es_intrastat_report/__init__.py
  l10n_es_intrastat_report/__manifest__.py
  l10n_es_intrastat_report/data/Estruc_NC2022.xlsx
  l10n_es_intrastat_report/data/NC_20.xls
  l10n_es_intrastat_report/data/account_fiscal_position_template.xml
  l10n_es_intrastat_report/data/intrastat_transaction.xml
  l10n_es_intrastat_report/hooks.py
  l10n_es_intrastat_report/i18n/ca.po
  l10n_es_intrastat_report/i18n/es.po
  l10n_es_intrastat_report/i18n/l10n_es_intrastat_report.pot
  l10n_es_intrastat_report/models/__init__.py
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
  l10n_es_intrastat_report/models/stock_location.py
  l10n_es_intrastat_report/readme/CONFIGURE.rst
  l10n_es_intrastat_report/readme/CONTRIBUTORS.rst
  l10n_es_intrastat_report/readme/DESCRIPTION.rst
  l10n_es_intrastat_report/readme/INSTALL.rst
  l10n_es_intrastat_report/readme/ROADMAP.rst
  l10n_es_intrastat_report/readme/USAGE.rst
  l10n_es_intrastat_report/report/__init__.py
  l10n_es_intrastat_report/report/intrastat_product_report_xls.py
  l10n_es_intrastat_report/security/ir.model.access.csv
  l10n_es_intrastat_report/security/l10n_es_intrastat_report_security.xml
  l10n_es_intrastat_report/static/description/icon.png
  l10n_es_intrastat_report/static/description/index.html
  l10n_es_intrastat_report/tests/__init__.py
  l10n_es_intrastat_report/tests/test_l10n_es_intrastat_report.py
  l10n_es_intrastat_report/views/l10n_es_intrastat_product.xml
  l10n_es_intrastat_report/wizards/__init__.py
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.py
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.xml
  setup/l10n_es_intrastat_report/odoo/addons/l10n_es_intrastat_report
  setup/l10n_es_intrastat_report/setup.py
Labels: bot is merging ⏳

#2552 [14.0][MIG] l10n_es_aeat_mod130: Migration to 14.0
  l10n_es_aeat_mod130/README.rst
  l10n_es_aeat_mod130/__init__.py
  l10n_es_aeat_mod130/__manifest__.py
  l10n_es_aeat_mod130/data/aeat_export_mod130_data.xml
  l10n_es_aeat_mod130/doc/DR130e15v12.xls
  l10n_es_aeat_mod130/i18n/bg.po
  l10n_es_aeat_mod130/i18n/ca.po
  l10n_es_aeat_mod130/i18n/ca_ES.po
  l10n_es_aeat_mod130/i18n/cs.po
  l10n_es_aeat_mod130/i18n/en_US.po
  l10n_es_aeat_mod130/i18n/es.po
  l10n_es_aeat_mod130/i18n/es_CO.po
  l10n_es_aeat_mod130/i18n/es_CR.po
  l10n_es_aeat_mod130/i18n/eu.po
  l10n_es_aeat_mod130/i18n/fr.po
  l10n_es_aeat_mod130/i18n/gl.po
  l10n_es_aeat_mod130/i18n/hr.po
  l10n_es_aeat_mod130/i18n/l10n_es_aeat_mod130.pot
  l10n_es_aeat_mod130/i18n/nl.po
  l10n_es_aeat_mod130/i18n/pl.po
  l10n_es_aeat_mod130/i18n/pt.po
  l10n_es_aeat_mod130/i18n/pt_BR.po
  l10n_es_aeat_mod130/i18n/ru.po
  l10n_es_aeat_mod130/i18n/sl.po
  l10n_es_aeat_mod130/i18n/sv.po
  l10n_es_aeat_mod130/i18n/tr.po
  l10n_es_aeat_mod130/i18n/vi.po
  l10n_es_aeat_mod130/models/__init__.py
  l10n_es_aeat_mod130/models/mod130.py
  l10n_es_aeat_mod130/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod130/readme/DESCRIPTION.rst
  l10n_es_aeat_mod130/readme/ROADMAP.rst
  l10n_es_aeat_mod130/security/ir.model.access.csv
  l10n_es_aeat_mod130/security/ir_rule.xml
  l10n_es_aeat_mod130/static/description/icon.png
  l10n_es_aeat_mod130/static/description/icon_source.svg
  l10n_es_aeat_mod130/static/description/index.html
  l10n_es_aeat_mod130/tests/__init__.py
  l10n_es_aeat_mod130/tests/test_l10n_es_aeat_mod130.py
  l10n_es_aeat_mod130/views/mod130_view.xml
  setup/l10n_es_aeat_mod130/odoo/addons/l10n_es_aeat_mod130
  setup/l10n_es_aeat_mod130/setup.py
Labels: bot is merging ⏳

#2550 [15.0][MIG] delivery_gls_asm: Migration to 15.0
  delivery_gls_asm/README.rst
  delivery_gls_asm/__init__.py
  delivery_gls_asm/__manifest__.py
  delivery_gls_asm/api/gls_asm_api.wsdl
  delivery_gls_asm/data/delivery_asm_data.xml
  delivery_gls_asm/i18n/ca.po
  delivery_gls_asm/i18n/delivery_gls_asm.pot
  delivery_gls_asm/i18n/es.po
  delivery_gls_asm/models/__init__.py
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/models/gls_asm_master_data.py
  delivery_gls_asm/models/gls_asm_request.py
  delivery_gls_asm/models/stock_picking.py
  delivery_gls_asm/readme/CONFIGURE.rst
  delivery_gls_asm/readme/CONTRIBUTORS.rst
  delivery_gls_asm/readme/DESCRIPTION.rst
  delivery_gls_asm/readme/INSTALL.rst
  delivery_gls_asm/readme/ROADMAP.rst
  delivery_gls_asm/readme/USAGE.rst
  delivery_gls_asm/security/ir.model.access.csv
  delivery_gls_asm/static/description/icon.png
  delivery_gls_asm/static/description/icon.svg
  delivery_gls_asm/static/description/index.html
  delivery_gls_asm/tests/__init__.py
  delivery_gls_asm/tests/test_delivery_gls_asm.py
  delivery_gls_asm/views/delivery_asm_view.xml
  delivery_gls_asm/views/gls_asm_manifest_template.xml
  delivery_gls_asm/views/stock_picking_views.xml
  delivery_gls_asm/wizard/__init__.py
  delivery_gls_asm/wizard/gls_asm_manifest_wizard.py
  delivery_gls_asm/wizard/gls_asm_manifest_wizard_views.xml
  requirements.txt
  setup/delivery_gls_asm/odoo/addons/delivery_gls_asm
  setup/delivery_gls_asm/setup.py
Labels: approved, bot is merging ⏳

#2554 [13.0][FIX] delivery_dhl_parcel: Improve changes
  delivery_dhl_parcel/doc/Documentacion_Integracion_DHL_Parcel.pdf
  delivery_dhl_parcel/doc/Documento_integracion_WEB_SERVICE_B2B_B2C_ver6.pdf
  delivery_dhl_parcel/i18n/es.po
  delivery_dhl_parcel/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#2556 [14.0][FIX] delivery_dhl_parcel: Improve changes
  delivery_dhl_parcel/doc/Documentacion_Integracion_DHL_Parcel.pdf
  delivery_dhl_parcel/doc/Documento_integracion_WEB_SERVICE_B2B_B2C_ver6.pdf
  delivery_dhl_parcel/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#2555 [16.0][MIG] l10n_es_toponyms: Migration top 16.0
  l10n_es_toponyms/README.rst
  l10n_es_toponyms/__init__.py
  l10n_es_toponyms/__manifest__.py
  l10n_es_toponyms/i18n/bg.po
  l10n_es_toponyms/i18n/ca.po
  l10n_es_toponyms/i18n/cs.po
  l10n_es_toponyms/i18n/de.po
  l10n_es_toponyms/i18n/es.po
  l10n_es_toponyms/i18n/es_CO.po
  l10n_es_toponyms/i18n/es_CR.po
  l10n_es_toponyms/i18n/eu.po
  l10n_es_toponyms/i18n/fr.po
  l10n_es_toponyms/i18n/gl.po
  l10n_es_toponyms/i18n/hr.po
  l10n_es_toponyms/i18n/l10n_es_toponyms.pot
  l10n_es_toponyms/i18n/nl.po
  l10n_es_toponyms/i18n/pl.po
  l10n_es_toponyms/i18n/pt.po
  l10n_es_toponyms/i18n/pt_BR.po
  l10n_es_toponyms/i18n/ru.po
  l10n_es_toponyms/i18n/sl.po
  l10n_es_toponyms/i18n/sv.po
  l10n_es_toponyms/i18n/tr.po
  l10n_es_toponyms/i18n/vi.po
  l10n_es_toponyms/readme/CONTRIBUTORS.rst
  l10n_es_toponyms/readme/DESCRIPTION.rst
  l10n_es_toponyms/readme/INSTALL.rst
  l10n_es_toponyms/readme/USAGE.rst
  l10n_es_toponyms/security/ir.model.access.csv
  l10n_es_toponyms/static/description/icon.png
  l10n_es_toponyms/static/description/icon.svg
  l10n_es_toponyms/static/description/index.html
  l10n_es_toponyms/tests/__init__.py
  l10n_es_toponyms/tests/test_l10n_es_toponyms.py
  l10n_es_toponyms/wizard/__init__.py
  l10n_es_toponyms/wizard/geonames_import.py
  l10n_es_toponyms/wizard/l10n_es_toponyms_wizard.py
  l10n_es_toponyms/wizard/l10n_es_toponyms_wizard.xml
  setup/l10n_es_toponyms/odoo/addons/l10n_es_toponyms
  setup/l10n_es_toponyms/setup.py
Labels: bot is merging ⏳

#2561 [15.0][FIX] l10n_es_account_bank_statement_import_n43: Requerir 6 caracteres…
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
Labels: bot is merging ⏳

#2560 [14.0][FIX] l10n_es_account_bank_statement_import_n43: Requerir 6 caracteres…
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
Labels: bot is merging ⏳

#2559 [13.0][FIX] l10n_es_account_bank_statement_import_n43: Requerir 6 caracteres…
  l10n_es_account_bank_statement_import_n43/wizards/account_bank_statement_import_n43.py
Labels: bot is merging ⏳

#2558 [12.0][FIX] l10n_es_account_bank_statement_import_n43: Requerir 6 caracteres…
  l10n_es_account_bank_statement_import_n43/wizards/account_bank_statement_import_n43.py
Labels: approved, bot is merging ⏳

#2557 [15.0][FIX] l10n_es_ticketbai_batuz: Send in type invoices to LROE if bizka…
  l10n_es_ticketbai_batuz/models/account_move.py
Labels: approved, bot is merging ⏳

#2537 [FIX] l10n_es_aeat_sii_oca: EU VAT number requires country code
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: approved, bot is merging ⏳

#2570 [MIG] l10n_es_partner_mercantil: Migration to 16.0
  l10n_es_partner_mercantil/README.rst
  l10n_es_partner_mercantil/__init__.py
  l10n_es_partner_mercantil/__manifest__.py
  l10n_es_partner_mercantil/i18n/bg.po
  l10n_es_partner_mercantil/i18n/ca.po
  l10n_es_partner_mercantil/i18n/en.po
  l10n_es_partner_mercantil/i18n/es.po
  l10n_es_partner_mercantil/i18n/eu.po
  l10n_es_partner_mercantil/i18n/fr.po
  l10n_es_partner_mercantil/i18n/gl.po
  l10n_es_partner_mercantil/i18n/hr.po
  l10n_es_partner_mercantil/i18n/l10n_es_partner_mercantil.pot
  l10n_es_partner_mercantil/i18n/nl.po
  l10n_es_partner_mercantil/i18n/pt.po
  l10n_es_partner_mercantil/i18n/pt_BR.po
  l10n_es_partner_mercantil/i18n/sl.po
  l10n_es_partner_mercantil/models/__init__.py
  l10n_es_partner_mercantil/models/partner_es.py
  l10n_es_partner_mercantil/readme/CONTRIBUTORS.rst
  l10n_es_partner_mercantil/readme/DESCRIPTION.rst
  l10n_es_partner_mercantil/readme/USAGE.rst
  l10n_es_partner_mercantil/static/description/icon.png
  l10n_es_partner_mercantil/static/description/icon.svg
  l10n_es_partner_mercantil/static/description/index.html
  l10n_es_partner_mercantil/views/res_partner_view.xml
  setup/l10n_es_partner_mercantil/odoo/addons/l10n_es_partner_mercantil
  setup/l10n_es_partner_mercantil/setup.py
Labels: bot is merging ⏳

#2535 [12.0][FIX] l10n_es_ticketbai_batuz: End of year quarter calculation
  l10n_es_ticketbai_batuz/models/lroe_operation.py
  l10n_es_ticketbai_batuz/models/res_company.py
Labels: approved, bot is merging ⏳
