Repository OCA/l10n-spain, pull requests merged in 2023-07, with the labels that each got.

#3068 [14.0][IMP] l10n_es_vat_prorate: Manage intracommunity and extracommunity taxes
  l10n_es_vat_prorate/data/account_template_tax.xml
  l10n_es_vat_prorate/models/account_tax.py
  l10n_es_vat_prorate/tests/json/sii_in_invoice_p_iva21_sp_ex_dict.json
  l10n_es_vat_prorate/tests/json/sii_in_refund_p_iva21_sp_in_dict.json
  l10n_es_vat_prorate/tests/test_prorate_sii.py
  l10n_es_vat_prorate/views/account_tax_views.xml
Labels: bot is merging ⏳

#2961 [12.0][MIG] l10n_es_aeat_mod369: Migration to version 12.0
  l10n_es_aeat_mod369/README.rst
  l10n_es_aeat_mod369/__init__.py
  l10n_es_aeat_mod369/__manifest__.py
  l10n_es_aeat_mod369/data/2022/00/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/04/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/05/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/06/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/07/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/08/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/09/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod369/data/2022/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod369/data/2022/main/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/tax_code_map_mod369_data.xml
  l10n_es_aeat_mod369/docs/DR369e21.xlsx
  l10n_es_aeat_mod369/docs/Descripcion_PresentacionFichero369_v1.pdf
  l10n_es_aeat_mod369/i18n/es.po
  l10n_es_aeat_mod369/i18n/l10n_es_aeat_mod369.pot
  l10n_es_aeat_mod369/models/__init__.py
  l10n_es_aeat_mod369/models/account_fiscal_position.py
  l10n_es_aeat_mod369/models/account_invoice.py
  l10n_es_aeat_mod369/models/account_tax.py
  l10n_es_aeat_mod369/models/l10n_es_aeat_map_tax_line.py
  l10n_es_aeat_mod369/models/l10n_es_aeat_tax_line.py
  l10n_es_aeat_mod369/models/mod369.py
  l10n_es_aeat_mod369/models/mod369_line.py
  l10n_es_aeat_mod369/models/mod369_line_grouped.py
  l10n_es_aeat_mod369/models/res_country.py
  l10n_es_aeat_mod369/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod369/readme/DESCRIPTION.rst
  l10n_es_aeat_mod369/readme/ROADMAP.rst
  l10n_es_aeat_mod369/readme/USAGE.rst
  l10n_es_aeat_mod369/security/ir.model.access.csv
  l10n_es_aeat_mod369/security/l10n_es_aeat_mod369_security.xml
  l10n_es_aeat_mod369/static/description/icon.png
  l10n_es_aeat_mod369/static/description/index.html
  l10n_es_aeat_mod369/tests/__init__.py
  l10n_es_aeat_mod369/tests/test_l10n_es_aeat_mod369.py
  l10n_es_aeat_mod369/views/account_fiscal_position_view.xml
  l10n_es_aeat_mod369/views/account_invoice_view.xml
  l10n_es_aeat_mod369/views/account_tax_view.xml
  l10n_es_aeat_mod369/views/mod369_view.xml
  l10n_es_aeat_mod369/views/res_country_view.xml
  requirements.txt
  setup/l10n_es_aeat_mod369/odoo/addons/l10n_es_aeat_mod369
  setup/l10n_es_aeat_mod369/setup.py
  test-requirements.txt
Labels: bot is merging ⏳

#3128 [15.0][IMP] l10n_es_facturae: Improve test case to allow inheritance with only base setup
  l10n_es_facturae/tests/common.py
Labels: approved, bot is merging ⏳

#3130 [16.0][IMP] l10n_es_facturae: Improve test case to allow inheritance with only base setup
  l10n_es_facturae/tests/common.py
Labels: bot is merging ⏳

#3134 [15.0][MIG] l10n_es_payment_order_confirming_aef: Migration to version 15.0
  l10n_es_payment_order_confirming_aef/README.rst
  l10n_es_payment_order_confirming_aef/__init__.py
  l10n_es_payment_order_confirming_aef/__manifest__.py
  l10n_es_payment_order_confirming_aef/data/account_payment_method.xml
  l10n_es_payment_order_confirming_aef/i18n/l10n_es_payment_order_confirming_aef.pot
  l10n_es_payment_order_confirming_aef/models/__init__.py
  l10n_es_payment_order_confirming_aef/models/account_payment_mode.py
  l10n_es_payment_order_confirming_aef/models/account_payment_order.py
  l10n_es_payment_order_confirming_aef/models/confirming_aef.py
  l10n_es_payment_order_confirming_aef/readme/CONFIGURE.rst
  l10n_es_payment_order_confirming_aef/readme/CONTRIBUTORS.rst
  l10n_es_payment_order_confirming_aef/readme/DESCRIPTION.rst
  l10n_es_payment_order_confirming_aef/readme/USAGE.rst
  l10n_es_payment_order_confirming_aef/static/description/icon.png
  l10n_es_payment_order_confirming_aef/static/description/index.html
  l10n_es_payment_order_confirming_aef/tests/__init__.py
  l10n_es_payment_order_confirming_aef/tests/test_payment_order_confirming_aef.py
  l10n_es_payment_order_confirming_aef/views/account_payment_mode_view.xml
  setup/l10n_es_payment_order_confirming_aef/odoo/addons/l10n_es_payment_order_confirming_aef
  setup/l10n_es_payment_order_confirming_aef/setup.py
Labels: bot is merging ⏳

#3119 [16.0][MIG] l10n_es_payment_order_confirming_aef: Migration to version 16.0
  l10n_es_payment_order_confirming_aef/README.rst
  l10n_es_payment_order_confirming_aef/__init__.py
  l10n_es_payment_order_confirming_aef/__manifest__.py
  l10n_es_payment_order_confirming_aef/data/account_payment_method.xml
  l10n_es_payment_order_confirming_aef/i18n/l10n_es_payment_order_confirming_aef.pot
  l10n_es_payment_order_confirming_aef/models/__init__.py
  l10n_es_payment_order_confirming_aef/models/account_payment_mode.py
  l10n_es_payment_order_confirming_aef/models/account_payment_order.py
  l10n_es_payment_order_confirming_aef/models/confirming_aef.py
  l10n_es_payment_order_confirming_aef/readme/CONFIGURE.rst
  l10n_es_payment_order_confirming_aef/readme/CONTRIBUTORS.rst
  l10n_es_payment_order_confirming_aef/readme/DESCRIPTION.rst
  l10n_es_payment_order_confirming_aef/readme/USAGE.rst
  l10n_es_payment_order_confirming_aef/static/description/icon.png
  l10n_es_payment_order_confirming_aef/static/description/index.html
  l10n_es_payment_order_confirming_aef/tests/__init__.py
  l10n_es_payment_order_confirming_aef/tests/test_payment_order_confirming_aef.py
  l10n_es_payment_order_confirming_aef/views/account_payment_mode_view.xml
  setup/l10n_es_payment_order_confirming_aef/odoo/addons/l10n_es_payment_order_confirming_aef
  setup/l10n_es_payment_order_confirming_aef/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3088 [15.0][ADD] l10n_es_pos_sii: envío de pos.order al SII
  l10n_es_aeat_sii_oca/models/__init__.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/models/sii_mixin.py
  l10n_es_aeat_sii_oss/models/account_move.py
  l10n_es_dua_sii/models/account_move.py
  l10n_es_pos_sii/README.rst
  l10n_es_pos_sii/__init__.py
  l10n_es_pos_sii/__manifest__.py
  l10n_es_pos_sii/models/__init__.py
  l10n_es_pos_sii/models/pos_order.py
  l10n_es_pos_sii/models/pos_session.py
  l10n_es_pos_sii/models/res_company.py
  l10n_es_pos_sii/readme/CONFIGURE.rst
  l10n_es_pos_sii/readme/CONTRIBUTORS.rst
  l10n_es_pos_sii/readme/DESCRIPTION.rst
  l10n_es_pos_sii/readme/ROADMAP.rst
  l10n_es_pos_sii/static/description/index.html
  l10n_es_pos_sii/tests/__init__.py
  l10n_es_pos_sii/tests/json/sii_pos_order_iva10b.json
  l10n_es_pos_sii/tests/json/sii_pos_order_iva21b.json
  l10n_es_pos_sii/tests/json/sii_pos_order_iva21b_iva10b.json
  l10n_es_pos_sii/tests/json/sii_pos_order_refund_iva21b.json
  l10n_es_pos_sii/tests/test_l10n_es_pos_sii.py
  l10n_es_pos_sii/views/pos_order.xml
  l10n_es_pos_sii/views/res_company.xml
  setup/l10n_es_pos_sii/odoo/addons/l10n_es_pos_sii
  setup/l10n_es_pos_sii/setup.py
Labels: bot is merging ⏳

#3138 [13.0][IMP] l10n_es_ticketbai_*: Make TBAI software version visible and e…
  l10n_es_ticketbai_api/__manifest__.py
  l10n_es_ticketbai_api/migrations/13.0.1.5.7/post-migrate.py
  l10n_es_ticketbai_api/models/res_company.py
  l10n_es_ticketbai_api/models/ticketbai_installation.py
  l10n_es_ticketbai_api/tests/common.py
  l10n_es_ticketbai_api/tests/company.json
  l10n_es_ticketbai_api/views/ticketbai_installation_views.xml
  l10n_es_ticketbai_pos/static/src/js/models.js
  l10n_es_ticketbai_pos/static/src/js/tbai_models.js
Labels: bot is merging ⏳

#3144 [14.0][IMP] l10n_es_ticketbai_*: Make TBAI software version a visible and e…
  l10n_es_ticketbai_api/__manifest__.py
  l10n_es_ticketbai_api/migrations/14.0.2.4.1/post-migrate.py
  l10n_es_ticketbai_api/models/res_company.py
  l10n_es_ticketbai_api/models/ticketbai_installation.py
  l10n_es_ticketbai_api/tests/common.py
  l10n_es_ticketbai_api/tests/company.json
  l10n_es_ticketbai_api/views/ticketbai_installation_views.xml
  l10n_es_ticketbai_pos/static/src/js/models.js
  l10n_es_ticketbai_pos/static/src/js/tbai_models.js
Labels: bot is merging ⏳

#3149 [15.0][IMP] l10n_es_ticketbai_*: Make TBAI software version a visible and e…
  l10n_es_ticketbai_api/__manifest__.py
  l10n_es_ticketbai_api/migrations/15.0.1.1.3/post-migrate.py
  l10n_es_ticketbai_api/models/res_company.py
  l10n_es_ticketbai_api/models/ticketbai_installation.py
  l10n_es_ticketbai_api/tests/common.py
  l10n_es_ticketbai_api/tests/company.json
  l10n_es_ticketbai_api/views/ticketbai_installation_views.xml
  l10n_es_ticketbai_pos/static/src/js/models.js
  l10n_es_ticketbai_pos/static/src/js/tbai_models.js
Labels: bot is merging ⏳

#3150 [16.0][IMP] l10n_es_ticketbai_api: Make TBAI software version a visible and…
  l10n_es_ticketbai_api/__manifest__.py
  l10n_es_ticketbai_api/migrations/16.0.1.0.3/post-migrate.py
  l10n_es_ticketbai_api/models/res_company.py
  l10n_es_ticketbai_api/models/ticketbai_installation.py
  l10n_es_ticketbai_api/tests/common.py
  l10n_es_ticketbai_api/tests/company.json
  l10n_es_ticketbai_api/views/ticketbai_installation_views.xml
Labels: bot is merging ⏳

#3148 [14.0][FIX] l10n_es_aeat: Consider financial_type="other" as regular operations
  l10n_es_aeat/models/l10n_es_aeat_report_tax_mapping.py
Labels: bot is merging ⏳

#3155 [15.0][FIX] l10n_es_aeat: Consider financial_type="other" as regular operations
  l10n_es_aeat/models/l10n_es_aeat_report_tax_mapping.py
Labels: bot is merging ⏳

#3156 [16.0][FIX] l10n_es_aeat: Consider financial_type="other" as regular operations
  l10n_es_aeat/models/l10n_es_aeat_report_tax_mapping.py
Labels: bot is merging ⏳

#3125 [16.0][MIG] payment redsys: Migration to 16.0
  payment_redsys/README.rst
  payment_redsys/__init__.py
  payment_redsys/__manifest__.py
  payment_redsys/controllers/__init__.py
  payment_redsys/controllers/main.py
  payment_redsys/data/payment_redsys.xml
  payment_redsys/i18n/bg.po
  payment_redsys/i18n/ca.po
  payment_redsys/i18n/es.po
  payment_redsys/i18n/fr.po
  payment_redsys/i18n/gl.po
  payment_redsys/i18n/hr.po
  payment_redsys/i18n/payment_redsys.pot
  payment_redsys/i18n/pt_BR.po
  payment_redsys/i18n/sl.po
  payment_redsys/models/__init__.py
  payment_redsys/models/account_payment_method.py
  payment_redsys/models/payment_provider.py
  payment_redsys/models/payment_transaction.py
  payment_redsys/readme/CONFIGURE.rst
  payment_redsys/readme/CONTRIBUTORS.rst
  payment_redsys/readme/DESCRIPTION.rst
  payment_redsys/readme/INSTALL.rst
  payment_redsys/readme/ROADMAP.rst
  payment_redsys/static/description/icon.png
  payment_redsys/static/description/index.html
  payment_redsys/static/img/bizum.png
  payment_redsys/static/src/img/redsys_icon.png
  payment_redsys/tests/__init__.py
  payment_redsys/tests/common.py
  payment_redsys/tests/test_redsys.py
  payment_redsys/views/payment_provider.xml
  payment_redsys/views/payment_redsys_templates.xml
  requirements.txt
  setup/payment_redsys/odoo/addons/payment_redsys
  setup/payment_redsys/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3160 [14.0][FIX] l10n_es_aeat_mod303: mapeo incorrecto mod 303.
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/tax_code_map_mod303_data.xml
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: approved, bot is merging ⏳

#3165 [15.0][FIX] l10n_es_aeat_sii_oca: rename method confirm_one_invoice
  l10n_es_aeat_sii_oca/data/aeat_sii_queue_job.xml
  l10n_es_aeat_sii_oca/models/sii_mixin.py
Labels: bot is merging ⏳
