Repository OCA/l10n-spain, pull requests merged in 2023-05, with the labels that each got.

#3025 [14.0][FIX] l10n_es_partner: Orden incorrecto ignorando funcionalidad res_partner_search_mode
  l10n_es_partner/models/res_partner.py
Labels: approved, bot is merging ⏳

#3027 [15.0][FIX] l10n_es_partner: Orden incorrecto ignorando funcionalidad res_partner_search_mode
  l10n_es_partner/models/res_partner.py
Labels: approved, bot is merging ⏳

#3026 [14.0][FIX] l10n_es_pos: simplified invoice limit
  l10n_es_pos/static/src/js/PaymentScreen.js
Labels: approved, bot is merging ⏳

#2710 [14.0][FIX] l10n_es_ticketbai_batuz - corregir filtered y tener en cuenta checkbox de diario
  l10n_es_ticketbai_batuz/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#3029 [15.0][FIX] l10n_es_pos: simplified invoice limit
  l10n_es_pos/static/src/js/PaymentScreen.js
Labels: bot is merging ⏳

#3028 [14.0][FIX] l10n_es_ticketbai_pos: Manages correctly simplified regime in POS
  l10n_es_ticketbai_pos/static/lib/tbai.js
  l10n_es_ticketbai_pos/static/src/js/models.js
  l10n_es_ticketbai_pos/static/src/js/tbai_models.js
Labels: bot is merging ⏳

#2938 [14.0][FIX] l10n_es_facturae: The "global" tax calculation rounding method …
  l10n_es_facturae/models/account_move.py
Labels: bot is merging ⏳

#3037 [16.0][IMP] l10n_es_aeat_sii_oca: Change registration key to computed writable
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: bot is merging ⏳

#3033 [15.0][FIX] l10n_es_aeat: No ir.model forbidden access
  l10n_es_aeat/models/l10n_es_aeat_report.py
  l10n_es_aeat/models/l10n_es_aeat_tax_line.py
  l10n_es_aeat/models/res_company.py
Labels: bot is merging ⏳

#3038 [16.0][FIX] l10n_es_aeat: No ir.model forbidden access
  l10n_es_aeat/models/l10n_es_aeat_report.py
  l10n_es_aeat/models/l10n_es_aeat_tax_line.py
  l10n_es_aeat/models/res_company.py
Labels: bot is merging ⏳

#3041 [15.0][IMP] payment_redsys: set redirect_form_view_id to the acquirer
  payment_redsys/migrations/15.0.1.0.0/post-migration.py
Labels: approved

#3046 [FIX]delivery_gls_asm: API response error
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/models/gls_asm_master_data.py
  delivery_gls_asm/models/gls_asm_request.py
Labels: approved, bot is merging ⏳

#3047 [14.0][FIX] l10n_es_pos_by_device: Do not obtain order number from DB if pe…
  l10n_es_pos_by_device/static/src/js/models.js
Labels: bot is merging ⏳

#3032 [15.0][FIX] l10n_es_ticketbai_pos: Manages correctly simplified regime in POS
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
  l10n_es_ticketbai_pos/static/lib/tbai.js
  l10n_es_ticketbai_pos/static/src/js/models.js
  l10n_es_ticketbai_pos/static/src/js/tbai_models.js
Labels: bot is merging ⏳

#3050 [16.0][FIX] l10n_es_ticketbai: Fix migrated views
  l10n_es_ticketbai/views/account_move_views.xml
  l10n_es_ticketbai/views/ticketbai_invoice_views.xml
Labels: bot is merging ⏳
