Repository OCA/l10n-spain, pull requests merged in 2023-03, with the labels that each got.

#2899 [14.0][FIX] l10n_es_aeat_mod303: Don't put bank details if not foreign
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/models/mod303.py
Labels: bot is merging ⏳

#2900 [14.0][IMP] delivery_mrw: set today instead of scheduled date for del…
  delivery_mrw/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#2903 [15.0][FIX] l10n_es_aeat_mod303: Don't put bank details if not foreign
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/models/mod303.py
Labels: bot is merging ⏳

#2896 [14.0][IMP] l10n_es_aeat_mod303_oss: include lines oss in map mod303 2023
  l10n_es_aeat_mod303_oss/__manifest__.py
  l10n_es_aeat_mod303_oss/data/2021-07/l10n_es_aeat_map_tax_line.xml
  l10n_es_aeat_mod303_oss/data/2023/l10n_es_aeat_map_tax_line.xml
  l10n_es_aeat_mod303_oss/models/mod303.py
Labels: approved, bot is merging ⏳

#2908 [14.0][IMP] l10n_es_vat_book: Prevent sections and notes when return move lines
  l10n_es_vat_book/models/l10n_es_vat_book.py
Labels: bot is merging ⏳

#2909 [15.0][IMP] l10n_es_vat_book: Prevent sections and notes when return move lines
  l10n_es_aeat/tests/test_l10n_es_aeat_map_tax.py
  l10n_es_vat_book/models/l10n_es_vat_book.py
Labels: bot is merging ⏳

#2910 [16.0][IMP] l10n_es_vat_book: Prevent sections and notes when return move lines
  l10n_es_aeat/tests/test_l10n_es_aeat_map_tax.py
  l10n_es_vat_book/models/l10n_es_vat_book.py
Labels: bot is merging ⏳

#2866 [11.0][IMP] l10n_es_extra_data: add new 2023 taxes and mod 303 tags
  l10n_es_extra_data/README.rst
  l10n_es_extra_data/__manifest__.py
  l10n_es_extra_data/data/account_fiscal_position_template_data.xml
  l10n_es_extra_data/data/account_tax_data.xml
  l10n_es_extra_data/readme/CONTRIBUTORS.rst
  l10n_es_extra_data/readme/HISTORY.rst
Labels: approved, bot is merging ⏳

#2871 [11.0][IMP] l10n_es_aeat_mod303: New BOE format for 2023
  l10n_es_aeat/models/l10n_es_aeat_map_tax.py
  l10n_es_aeat/tests/__init__.py
  l10n_es_aeat/tests/test_l10n_es_aeat_map_tax.py
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/docs/DR303e21v100.xlsx
  l10n_es_aeat_mod303/docs/DR303e21v200.xlsx
  l10n_es_aeat_mod303/docs/DR303e23.xlsx
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: bot is merging ⏳

#2873 [11.0][IMP] l10n_es_aeat_mod303_extra_data: New BOE format for 2023
  l10n_es_aeat_mod303_extra_data/__manifest__.py
  l10n_es_aeat_mod303_extra_data/data/2023/l10n_es_aeat_map_tax_line.xml
Labels: bot is merging ⏳

#2884 [11.0][IMP] l10n_es_aeat_mod303_oss: include lines oss in map mod303 2023
  l10n_es_aeat_mod303_oss/__manifest__.py
  l10n_es_aeat_mod303_oss/data/2021-07/l10n_es_aeat_map_tax_line.xml
  l10n_es_aeat_mod303_oss/data/2023/l10n_es_aeat_map_tax_line.xml
  l10n_es_aeat_mod303_oss/models/mod303.py
Labels: approved, ready to merge, bot is merging ⏳

#2876 [11.0][IMP] l10n_es_aeat_sii_extra_data: include 2023 taxes
  l10n_es_aeat_sii_extra_data/__manifest__.py
  l10n_es_aeat_sii_extra_data/data/aeat_sii_map_data.xml
Labels: bot is merging ⏳

#2868 [11.0][ADD] l10n_es_aeat_mod349_extra_data: Include food taxes + missing intra-community ones
  l10n_es_aeat_mod349_extra_data/__init__.py
  l10n_es_aeat_mod349_extra_data/__manifest__.py
  l10n_es_aeat_mod349_extra_data/data/aeat_349_map_data.xml
  l10n_es_aeat_mod349_extra_data/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod349_extra_data/readme/DESCRIPTION.rst
  l10n_es_aeat_mod349_extra_data/readme/HISTORY.rst
  l10n_es_aeat_mod349_extra_data/static/description/icon.png
  l10n_es_aeat_mod349_extra_data/static/description/index.html
  setup/l10n_es_aeat_mod349_extra_data/odoo/addons/l10n_es_aeat_mod349_extra_data
  setup/l10n_es_aeat_mod349_extra_data/setup.cfg
  setup/l10n_es_aeat_mod349_extra_data/setup.py
Labels: bot is merging ⏳

#2911 [15.0][IMP] l10n_es_aeat: Change Warning to UserError exception to prevent warning log
  l10n_es_aeat/models/l10n_es_aeat_map_tax.py
Labels: bot is merging ⏳

#2912 [16.0][IMP] l10n_es_aeat: Change Warning to UserError exception to prevent warning log
  l10n_es_aeat/models/l10n_es_aeat_map_tax.py
Labels: bot is merging ⏳

#2598 [14.0][IMP] l10n_es_vat_prorrate: Make it work with SII
  l10n_es_aeat/models/account_move.py
  l10n_es_aeat/tests/test_l10n_es_aeat_taxinfo.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_vat_prorate/__manifest__.py
  l10n_es_vat_prorate/models/account_move.py
  l10n_es_vat_prorate/tests/__init__.py
  l10n_es_vat_prorate/tests/json/sii_in_invoice_p_iva0_ns_p_iva10_bc_dict.json
  l10n_es_vat_prorate/tests/json/sii_in_invoice_p_iva10_bc_dict.json
  l10n_es_vat_prorate/tests/json/sii_in_invoice_p_iva10_bc_p_irpf19_p_iva21_sc_p_irpf19_dict.json
  l10n_es_vat_prorate/tests/json/sii_in_invoice_p_iva10_bc_p_irpf1_dict.json
  l10n_es_vat_prorate/tests/json/sii_in_invoice_p_iva10_bc_p_req014_p_iva21_sc_p_req52_dict.json
  l10n_es_vat_prorate/tests/json/sii_in_invoice_p_iva21_sp_ex_dict.json
  l10n_es_vat_prorate/tests/json/sii_in_refund_p_iva10_bc_dict.json
  l10n_es_vat_prorate/tests/json/sii_in_refund_p_iva21_sp_in_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva0_sp_i_s_iva0_ic_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva10b_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva10b_s_irpf1_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva10b_s_iva0_ns_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva10b_s_iva21s_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva10b_s_req014_s_iva21s_s_req52_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva_e_s_iva0_e_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_refund_s_iva0_sp_i_s_iva0_ic_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_refund_s_iva10b_s_iva10b_s_iva21s_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_refund_s_iva_e_s_iva0_e_dict.json
  l10n_es_vat_prorate/tests/test_prorate_sii.py
Labels: bot is merging ⏳

#2880 [11.0][IMP] l10n_es_vat_book_extra_data: include 2023 map taxes
  l10n_es_vat_book_extra_data/__manifest__.py
  l10n_es_vat_book_extra_data/data/aeat_vat_book_map_data.xml
Labels: approved, ready to merge, bot is merging ⏳

#2914 [14.0][IMP] l10n_es_ticketbai: fecha expedición en origen rectificativa a t…
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/migrations/14.0.2.8.4/post-migration.py
  l10n_es_ticketbai/migrations/14.0.2.8.4/pre-migration.py
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/ticketbai_invoice.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
Labels: bot is merging ⏳

#2915 [15.0][IMP] l10n_es_ticketbai: fecha expedición en origen rectificativa a t…
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/migrations/15.0.1.4.6/post-migration.py
  l10n_es_ticketbai/migrations/15.0.1.4.6/pre-migration.py
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/ticketbai_invoice.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
Labels: bot is merging ⏳

#2919 [15.0][FIX] l10n_es_ticketbai: 'Recargo' fiscal position TBAI regime key
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/data/account_fiscal_position_template.xml
  l10n_es_ticketbai/migrations/15.0.1.4.7/post-migration.py
Labels: approved, bot is merging ⏳

#2922 [14.0][FIX] l10n_es_ticketbai: 'Recargo' fiscal position TBAI regime key
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/data/account_fiscal_position_template.xml
  l10n_es_ticketbai/migrations/14.0.2.8.5/post-migration.py
Labels: bot is merging ⏳

#2920 [15.0][FIX]l10n_es_pos: Wrong customer info when reprinting receipt
  l10n_es_pos/static/src/xml/pos.xml
Labels: approved, bot is merging ⏳

#2925 [16.0][IMP] l10n_es_ticketbai_api: Limit tbai.invoice model compute registers
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
Labels: approved, bot is merging ⏳

#2610 [14.0][IMP] l10n_es_account_statement_import_n43: Importación de múltiples ficheros
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
  l10n_es_account_statement_import_n43/tests/testmulti.n43
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
Labels: bot is merging ⏳

#2879 [15.0] [IMP] l10n_es_aeat_sii_oca: informative wizard invoices sii
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/views/account_move_views.xml
  l10n_es_aeat_sii_oca/wizards/__init__.py
  l10n_es_aeat_sii_oca/wizards/account_move_send_sii.py
  l10n_es_aeat_sii_oca/wizards/account_move_send_sii_views.xml
Labels: bot is merging ⏳

#2883 [15.0] [IMP] l10n_es_facturae: improvements wizard facturae
  l10n_es_facturae/tests/common.py
  l10n_es_facturae/wizard/create_facturae.py
Labels: bot is merging ⏳

#2933 [14.0][FIX] l10n_es_vat_prorate: Handle analytic information
  l10n_es_vat_prorate/__manifest__.py
  l10n_es_vat_prorate/models/account_move.py
  l10n_es_vat_prorate/tests/test_vat_prorate.py
Labels: bot is merging ⏳

#2362 [14.0][ADD] l10n_es_aeat_mod369: Modelo 369
  l10n_es_aeat_mod369/README.rst
  l10n_es_aeat_mod369/__init__.py
  l10n_es_aeat_mod369/__manifest__.py
  l10n_es_aeat_mod369/data/2022/00/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/04/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/05/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/06/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/07/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/08/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/09/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod369/data/2022/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod369/data/2022/main/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/tax_code_map_mod369_data.xml
  l10n_es_aeat_mod369/docs/DR369e21.xlsx
  l10n_es_aeat_mod369/docs/Descripcion_PresentacionFichero369_v1.pdf
  l10n_es_aeat_mod369/i18n/es.po
  l10n_es_aeat_mod369/i18n/l10n_es_aeat_mod369.pot
  l10n_es_aeat_mod369/models/__init__.py
  l10n_es_aeat_mod369/models/account_tax.py
  l10n_es_aeat_mod369/models/l10n_es_aeat_tax_line.py
  l10n_es_aeat_mod369/models/mod369.py
  l10n_es_aeat_mod369/models/mod369_line.py
  l10n_es_aeat_mod369/models/mod369_line_grouped.py
  l10n_es_aeat_mod369/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod369/readme/DESCRIPTION.rst
  l10n_es_aeat_mod369/readme/ROADMAP.rst
  l10n_es_aeat_mod369/readme/USAGE.rst
  l10n_es_aeat_mod369/security/ir.model.access.csv
  l10n_es_aeat_mod369/security/l10n_es_aeat_mod369_security.xml
  l10n_es_aeat_mod369/static/description/icon.png
  l10n_es_aeat_mod369/static/description/index.html
  l10n_es_aeat_mod369/tests/__init__.py
  l10n_es_aeat_mod369/tests/test_l10n_es_aeat_mod369.py
  l10n_es_aeat_mod369/views/account_tax_view.xml
  l10n_es_aeat_mod369/views/mod369_view.xml
  setup/l10n_es_aeat_mod369/odoo/addons/l10n_es_aeat_mod369
  setup/l10n_es_aeat_mod369/setup.py
Labels: bot is merging ⏳

#2927 [14.0][IMP] l10n_es_account_statement_import_n43: Use the proper currency
  l10n_es_account_statement_import_n43/readme/CONTRIBUTORS.rst
  l10n_es_account_statement_import_n43/readme/ROADMAP.rst
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
Labels: bot is merging ⏳

#2926 [15.0][IMP] l10n_es_account_statement_import_n43: Allow to create different…
  l10n_es_account_statement_import_n43/readme/CONTRIBUTORS.rst
  l10n_es_account_statement_import_n43/readme/ROADMAP.rst
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
  l10n_es_account_statement_import_n43/tests/testmulti.n43
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
Labels: bot is merging ⏳

#2812 [14.0][IMP] l10n_es_pos: Secuencias por dispositivo
  l10n_es_pos/models/pos_order.py
  l10n_es_pos/readme/ROADMAP.rst
  l10n_es_pos/static/src/js/PaymentScreen.js
  l10n_es_pos/static/src/js/models.js
  l10n_es_pos_by_device/README.rst
  l10n_es_pos_by_device/__init__.py
  l10n_es_pos_by_device/__manifest__.py
  l10n_es_pos_by_device/i18n/es.po
  l10n_es_pos_by_device/i18n/l10n_es_pos_by_device.pot
  l10n_es_pos_by_device/models/__init__.py
  l10n_es_pos_by_device/models/pos_config.py
  l10n_es_pos_by_device/models/pos_device.py
  l10n_es_pos_by_device/models/pos_order.py
  l10n_es_pos_by_device/models/res_company.py
  l10n_es_pos_by_device/models/res_config_settings.py
  l10n_es_pos_by_device/readme/CONFIGURE.rst
  l10n_es_pos_by_device/readme/CONTRIBUTORS.rst
  l10n_es_pos_by_device/readme/DESCRIPTION.rst
  l10n_es_pos_by_device/readme/USAGE.rst
  l10n_es_pos_by_device/security/device_security.xml
  l10n_es_pos_by_device/security/ir.model.access.csv
  l10n_es_pos_by_device/static/description/index.html
  l10n_es_pos_by_device/static/src/js/PaymentScreen.js
  l10n_es_pos_by_device/static/src/js/Screens/Chrome/Chrome.js
  l10n_es_pos_by_device/static/src/js/Screens/Chrome/DeviceName.js
  l10n_es_pos_by_device/static/src/js/models.js
  l10n_es_pos_by_device/static/src/xml/Screens/Chrome/Chrome.xml
  l10n_es_pos_by_device/static/src/xml/Screens/Chrome/DeviceName.xml
  l10n_es_pos_by_device/static/src/xml/pos.xml
  l10n_es_pos_by_device/views/pos_templates.xml
  l10n_es_pos_by_device/views/pos_views.xml
  l10n_es_pos_by_device/views/res_config_views.xml
  setup/l10n_es_pos_by_device/odoo/addons/l10n_es_pos_by_device
  setup/l10n_es_pos_by_device/setup.py
Labels: approved, bot is merging ⏳

#2924 [14.0][ADD] l10n_es_aeat_mod303_vat_prorate: New module
  l10n_es_aeat_mod303_vat_prorate/README.rst
  l10n_es_aeat_mod303_vat_prorate/__init__.py
  l10n_es_aeat_mod303_vat_prorate/__manifest__.py
  l10n_es_aeat_mod303_vat_prorate/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303_vat_prorate/i18n/es.po
  l10n_es_aeat_mod303_vat_prorate/i18n/l10n_es_aeat_mod303_vat_prorate.pot
  l10n_es_aeat_mod303_vat_prorate/models/__init__.py
  l10n_es_aeat_mod303_vat_prorate/models/mod303.py
  l10n_es_aeat_mod303_vat_prorate/readme/CONFIGURE.rst
  l10n_es_aeat_mod303_vat_prorate/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303_vat_prorate/readme/DESCRIPTION.rst
  l10n_es_aeat_mod303_vat_prorate/readme/ROADMAP.rst
  l10n_es_aeat_mod303_vat_prorate/readme/USAGE.rst
  l10n_es_aeat_mod303_vat_prorate/static/description/icon.png
  l10n_es_aeat_mod303_vat_prorate/static/description/index.html
  l10n_es_aeat_mod303_vat_prorate/tests/__init__.py
  l10n_es_aeat_mod303_vat_prorate/tests/test_l10n_es_aeat_mod303_vat_prorate.py
  l10n_es_aeat_mod303_vat_prorate/views/mod303_views.xml
  setup/l10n_es_aeat_mod303_vat_prorate/odoo/addons/l10n_es_aeat_mod303_vat_prorate
  setup/l10n_es_aeat_mod303_vat_prorate/setup.py
Labels: bot is merging ⏳

#2874 [15.0][IMP] l10n_es_aeat_sii_oca: more frendly error sii errors and get json
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#2934 [14.0][FIX]l10n_es_pos: Wrong customer info when reprinting receipt
  l10n_es_pos/static/src/xml/pos.xml
Labels: approved, bot is merging ⏳

#2937 [14.0][IMP] l10n_es_ticketbai_api, l10n_es_ticketbai: R5 code support
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai_api/models/ticketbai_invoice.py
Labels: bot is merging ⏳

#2867 [12.0][IMP] l10n_es_intrastat_report: update hs codes to last version
  l10n_es_intrastat_report/README.rst
  l10n_es_intrastat_report/data/Estruc_NC2023.xlsx
  l10n_es_intrastat_report/readme/INSTALL.rst
  l10n_es_intrastat_report/static/description/index.html
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.py
Labels: bot is merging ⏳

#2940 [14.0][FIX] l10n_es_aeat_mod303: Add new result_types to domain
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: bot is merging ⏳

#2941 [13.0][FIX] l10n_es_aeat_mod303: Add new result_types to domain
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: bot is merging ⏳

#2942 [15.0][FIX] l10n_es_aeat_mod303: Add new result_types to domain
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: bot is merging ⏳

#2869 [12.0][IMP] l10n_es_aeat_mod303: New BOE format for 2023
  l10n_es_aeat/models/l10n_es_aeat_map_tax.py
  l10n_es_aeat/tests/__init__.py
  l10n_es_aeat/tests/test_l10n_es_aeat_map_tax.py
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/docs/DR303e21v100.xlsx
  l10n_es_aeat_mod303/docs/DR303e21v200.xlsx
  l10n_es_aeat_mod303/docs/DR303e23.xlsx
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
  l10n_es_aeat_mod303_extra_data/__manifest__.py
  l10n_es_aeat_mod303_extra_data/data/2023/l10n_es_aeat_map_tax_line.xml
  l10n_es_extra_data/README.rst
  l10n_es_extra_data/data/account_fiscal_position_template_data.xml
  l10n_es_extra_data/data/account_tax_data.xml
  l10n_es_extra_data/readme/CONTRIBUTORS.rst
  l10n_es_extra_data/readme/HISTORY.rst
Labels: bot is merging ⏳

#2946 [15.0][FIX] l10n_es_aeat_sii_oca: solve error access
  l10n_es_aeat_sii_oca/security/ir.model.access.csv
Labels: bot is merging ⏳

#2947 [16.0][MIG] l10n_es_aeat_sii_oca: informative wizard invoices sii
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/security/ir.model.access.csv
  l10n_es_aeat_sii_oca/views/account_move_views.xml
  l10n_es_aeat_sii_oca/wizards/__init__.py
  l10n_es_aeat_sii_oca/wizards/account_move_send_sii.py
  l10n_es_aeat_sii_oca/wizards/account_move_send_sii_views.xml
Labels: bot is merging ⏳

#2889 [15.0][IMP] l10n_es_facturae: improvements validation facturae
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/models/res_partner.py
  l10n_es_facturae/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2953 [16.0][FIX] l10n_es_ticketbai: Send invoice line correctly when it has no name
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#2931 [16.0][MIG] l10n_es_dua: Migration to 16.0
  l10n_es_dua/README.rst
  l10n_es_dua/__init__.py
  l10n_es_dua/__manifest__.py
  l10n_es_dua/data/fiscal_position_taxes_dua.xml
  l10n_es_dua/data/fiscal_positions_dua.xml
  l10n_es_dua/data/products_dua.xml
  l10n_es_dua/data/tax_group_data.xml
  l10n_es_dua/data/taxes_dua.xml
  l10n_es_dua/i18n/ca.po
  l10n_es_dua/i18n/es.po
  l10n_es_dua/i18n/l10n_es_dua.pot
  l10n_es_dua/readme/CONFIGURE.rst
  l10n_es_dua/readme/CONTRIBUTORS.rst
  l10n_es_dua/readme/DESCRIPTION.rst
  l10n_es_dua/readme/USAGE.rst
  l10n_es_dua/static/description/icon.png
  l10n_es_dua/static/description/index.html
  setup/l10n_es_dua/odoo/addons/l10n_es_dua
  setup/l10n_es_dua/setup.py
Labels: bot is merging ⏳

#2956 [12.0][FIX] l10n_es_intrastat_report: fix wrong type on importing hs codes
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.py
Labels: bot is merging ⏳

#2948 [14.0] l10n_es_aeat_mod303: Nuevos impuestos de ISP bienes de inversión
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#2958 [14.0][FIX] l10n_es_ticketbai: Do not check reverse entries when account.mo…
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#2959 [15.0][FIX] l10n_es_ticketbai: Do not check reverse entries when account.mo…
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#2960 [16.0][FIX] l10n_es_ticketbai: Do not check reverse entries when account.mo…
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#2949 [14.0] l10n_es_aeat_mod347: Nuevos impuestos de ISP bienes de inversión
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
Labels: bot is merging ⏳

#2952 [14.0] l10n_es_aeat_sii_oca: Nuevos impuestos de ISP bienes de inversión
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#2964 [13.0] l10n_es_aeat_*: Include ISP investments taxes
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#2962 [15.0] l10n_es_aeat_*: Include ISP investments taxes
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#2963 [16.0] l10n_es_aeat_*: Include ISP investments taxes
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#2936 [14.0][IMP] l10n_es_*_pos: Adapt TicketBAI POS to sequences by device
  l10n_es_pos/models/pos_config.py
  l10n_es_pos/static/src/js/PaymentScreen.js
  l10n_es_pos/static/src/js/models.js
  l10n_es_pos/static/src/xml/pos.xml
  l10n_es_pos/views/pos_views.xml
  l10n_es_pos_by_device/__manifest__.py
  l10n_es_pos_by_device/models/pos_config.py
  l10n_es_pos_by_device/models/pos_order.py
  l10n_es_pos_by_device/static/src/js/models.js
  l10n_es_pos_by_device/static/src/xml/pos.xml
  l10n_es_pos_by_device/views/pos_views.xml
  l10n_es_ticketbai_pos/models/pos_config.py
  l10n_es_ticketbai_pos/models/pos_order.py
  l10n_es_ticketbai_pos/static/src/js/models.js
  l10n_es_ticketbai_pos/static/src/js/tbai_models.js
Labels: approved, ready to merge, bot is merging ⏳
