Repository OCA/l10n-spain, pull requests merged in 2023-01, with the labels that each got.

#2720 [16.0][FIX] l10n_es_aeat: Move thirdparty_invoice + thirdparty_number field to l10n_es_aeat
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat/migrations/14.0.2.4.0/pre-migration.py
  l10n_es_aeat/models/account_move.py
  l10n_es_aeat/views/account_move_view.xml
Labels: bot is merging ⏳

#2725 [13.0][DCK] freeze version of cryptography
  l10n_es_ticketbai_api/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳

#2718 [15.0][FIX] l10n_es_aeat_sii_oca: admit E3 export exempt cause
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#2697 [16.0][MIG] l10n_es_aeat_mod216: Migration to 16.0
  l10n_es_aeat_mod216/README.rst
  l10n_es_aeat_mod216/__init__.py
  l10n_es_aeat_mod216/__manifest__.py
  l10n_es_aeat_mod216/data/aeat_export_mod216_data.xml
  l10n_es_aeat_mod216/data/tax_code_map_mod216_data.xml
  l10n_es_aeat_mod216/docs/DR-216e16_v1.06.pdf
  l10n_es_aeat_mod216/i18n/bg.po
  l10n_es_aeat_mod216/i18n/ca.po
  l10n_es_aeat_mod216/i18n/cs.po
  l10n_es_aeat_mod216/i18n/de.po
  l10n_es_aeat_mod216/i18n/es.po
  l10n_es_aeat_mod216/i18n/es_CO.po
  l10n_es_aeat_mod216/i18n/es_CR.po
  l10n_es_aeat_mod216/i18n/es_ES.po
  l10n_es_aeat_mod216/i18n/eu.po
  l10n_es_aeat_mod216/i18n/fr.po
  l10n_es_aeat_mod216/i18n/gl.po
  l10n_es_aeat_mod216/i18n/hr.po
  l10n_es_aeat_mod216/i18n/l10n_es_aeat_mod216.pot
  l10n_es_aeat_mod216/i18n/nl.po
  l10n_es_aeat_mod216/i18n/pl.po
  l10n_es_aeat_mod216/i18n/pt.po
  l10n_es_aeat_mod216/i18n/pt_BR.po
  l10n_es_aeat_mod216/i18n/ru.po
  l10n_es_aeat_mod216/i18n/sl.po
  l10n_es_aeat_mod216/i18n/sv.po
  l10n_es_aeat_mod216/i18n/tr.po
  l10n_es_aeat_mod216/i18n/vi.po
  l10n_es_aeat_mod216/models/__init__.py
  l10n_es_aeat_mod216/models/mod216.py
  l10n_es_aeat_mod216/readme/CONFIGURE.rst
  l10n_es_aeat_mod216/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod216/readme/DESCRIPTION.rst
  l10n_es_aeat_mod216/readme/USAGE.rst
  l10n_es_aeat_mod216/security/ir.model.access.csv
  l10n_es_aeat_mod216/security/ir_rule.xml
  l10n_es_aeat_mod216/static/description/icon.png
  l10n_es_aeat_mod216/static/description/icon_source.svg
  l10n_es_aeat_mod216/static/description/index.html
  l10n_es_aeat_mod216/tests/__init__.py
  l10n_es_aeat_mod216/tests/test_l10n_es_aeat_mod216.py
  l10n_es_aeat_mod216/views/mod216_view.xml
  setup/l10n_es_aeat_mod216/odoo/addons/l10n_es_aeat_mod216
  setup/l10n_es_aeat_mod216/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2731 [15.0][FIX] l10n_es_aeat_sii_oca: compute macrodata from company currency amount
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#2730 [14.0][FIX] Restrict library versions
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_facturae/__manifest__.py
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai_api/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳

#2728 [14.0][FIX] l10n_es_aeat_sii_oca: compute macrodata from company currency amount
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#2726 [16.0][MIG] l10n_es_account_asset: Migration to 16.0
  l10n_es_account_asset/README.rst
  l10n_es_account_asset/__init__.py
  l10n_es_account_asset/__manifest__.py
  l10n_es_account_asset/i18n/ca.po
  l10n_es_account_asset/i18n/cs.po
  l10n_es_account_asset/i18n/de.po
  l10n_es_account_asset/i18n/es.po
  l10n_es_account_asset/i18n/es_CO.po
  l10n_es_account_asset/i18n/fr.po
  l10n_es_account_asset/i18n/fr_BE.po
  l10n_es_account_asset/i18n/gl.po
  l10n_es_account_asset/i18n/hr.po
  l10n_es_account_asset/i18n/l10n_es_account_asset.pot
  l10n_es_account_asset/i18n/pl.po
  l10n_es_account_asset/i18n/pt.po
  l10n_es_account_asset/i18n/pt_BR.po
  l10n_es_account_asset/i18n/ru.po
  l10n_es_account_asset/i18n/sl.po
  l10n_es_account_asset/i18n/sv.po
  l10n_es_account_asset/i18n/vi.po
  l10n_es_account_asset/models/__init__.py
  l10n_es_account_asset/models/account_asset.py
  l10n_es_account_asset/models/account_asset_profile.py
  l10n_es_account_asset/readme/CONTRIBUTORS.rst
  l10n_es_account_asset/readme/DESCRIPTION.rst
  l10n_es_account_asset/static/description/icon.png
  l10n_es_account_asset/static/description/index.html
  l10n_es_account_asset/tests/__init__.py
  l10n_es_account_asset/tests/test_l10n_es_account_asset.py
  l10n_es_account_asset/views/account_asset_profile_views.xml
  l10n_es_account_asset/views/account_asset_views.xml
  setup/l10n_es_account_asset/odoo/addons/l10n_es_account_asset
  setup/l10n_es_account_asset/setup.py
Labels: bot is merging ⏳

#2736 [FIX] l10n_es_vat_prorate: signature was wrong
  l10n_es_vat_prorate/models/account_move.py
Labels: approved, bot is merging ⏳

#2665 [14.0][IMP] l10n_es_aeat_mod111: IRPF AEE 7% y 15%
  l10n_es_aeat_mod111/data/tax_code_map_mod111_data.xml
  l10n_es_aeat_mod111/models/mod111.py
  l10n_es_aeat_mod111/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod111/views/mod111_view.xml
Labels: approved, bot is merging ⏳

#2737 [IMP] [15.0] l10n_es_aeat_mod111: IRPF AEE 7% y 15%
  l10n_es_aeat_mod111/data/tax_code_map_mod111_data.xml
  l10n_es_aeat_mod111/models/mod111.py
  l10n_es_aeat_mod111/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod111/views/mod111_view.xml
Labels: bot is merging ⏳

#2742 [14.0][FIX] l10n_es_ticketbai: ignore section lines
  l10n_es_ticketbai/models/account_move.py
Labels: approved, bot is merging ⏳

#2743 [13.0][FIX] l10n_es_ticketbai: ignore section lines
  l10n_es_ticketbai/models/account_move.py
Labels: approved, bot is merging ⏳

#2744 [15.0][FIX] l10n_es_ticketbai: ignore section lines
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#2724 [14.0][FIX] l10n_es_ticketbai_api_batuz - normalizar cálculo de ejercicio
  l10n_es_ticketbai_api_batuz/lroe/lroe_api.py
  l10n_es_ticketbai_api_batuz/models/lroe_operation.py
  l10n_es_ticketbai_api_batuz/tests/test_lroe_api.py
Labels: approved, ready to merge, bot is merging ⏳

#2747 [15.0][FIX] l10n_es_ticketbai_api_batuz - normalizar cálculo de ejercicio
  l10n_es_ticketbai_api_batuz/lroe/lroe_api.py
  l10n_es_ticketbai_api_batuz/models/lroe_operation.py
  l10n_es_ticketbai_api_batuz/tests/test_lroe_api.py
Labels: bot is merging ⏳

#2748 [13.0][FIX] l10n_es_ticketbai_api_batuz - normalizar cálculo de ejercicio
  l10n_es_ticketbai_api_batuz/lroe/lroe_api.py
  l10n_es_ticketbai_api_batuz/models/lroe_operation.py
  l10n_es_ticketbai_api_batuz/tests/test_lroe_api.py
Labels: bot is merging ⏳

#2750 [14.0][FIX] l10n_es_aeat: Don't error on manually created export lines
  l10n_es_aeat/views/aeat_export_configuration_view.xml
Labels: bot is merging ⏳

#2751 [16.0][FIX] l10n_es_aeat: Don't error on manually created export lines
  l10n_es_aeat/views/aeat_export_configuration_view.xml
Labels: bot is merging ⏳

#2745 [14.0][FIX] l10n_es_aeat: error en los reports al generar un número de sequencia en un entorno multicompañía
  l10n_es_aeat/models/l10n_es_aeat_report.py
  l10n_es_aeat/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#2755 [FIX] l10n_es_aeat_mod347: cáclulo importe entregas
  l10n_es_aeat_mod347/models/mod347.py
  l10n_es_aeat_mod347/views/mod347_view.xml
  l10n_es_aeat_mod347/views/report_347_partner.xml
Labels: approved, bot is merging ⏳

#2760 [12.0][DCK] freeze version of cryptography
  setup/l10n_es_ticketbai_api/setup.py
Labels: approved, bot is merging ⏳

#2762 [12.0][FIX] l10n_es_aeat_mod347: Save proper real state fields
  l10n_es_aeat_mod347/models/mod347.py
Labels: bot is merging ⏳

#2764 [15.0][FIX] Fix pre-commit
  l10n_es_aeat/migrations/14.0.2.4.0/pre-migration.py
  l10n_es_aeat_mod347/migrations/14.0.2.0.0/pre-migration.py
Labels: approved, bot is merging ⏳

#2753 [15.0][FIX] l10n_es_ticketbai: Display TBAI ID and QR always on same page
  l10n_es_ticketbai/views/report_invoice.xml
Labels: approved, bot is merging ⏳

#2765 [16.0][FIX] Campo company_id en vista l10n_es_aeat. Error al actualizar 303
  l10n_es_aeat/views/aeat_report_view.xml
Labels: bot is merging ⏳

#2768 [14.0][FIX] l10n_es_ticketbai: Display TBAI ID and QR always on same page
  l10n_es_ticketbai/views/report_invoice.xml
Labels: bot is merging ⏳

#2757 [15.0][FIX] l10n_es_aeat_mod347: cálculo importe entregas
  l10n_es_aeat_mod347/models/mod347.py
  l10n_es_aeat_mod347/views/mod347_view.xml
Labels: approved, bot is merging ⏳

#2767 [13.0][FIX] l10n_es_aeat_mod303: 2022 para exonerados 390
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/l10n.es.aeat.mod303.report.activity.code.csv
  l10n_es_aeat_mod303/data/l10n_es_aeat_mod303_report_activity_code_data.xml
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/views/l10n_es_aeat_mod303_report_activity_code_data_views.xml
Labels: bot is merging ⏳

#2769 [14.0][FIX] l10n_es_aeat_mod303: 2022 para exonerados 390
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/l10n.es.aeat.mod303.report.activity.code.csv
  l10n_es_aeat_mod303/data/l10n_es_aeat_mod303_report_activity_code_data.xml
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/views/l10n_es_aeat_mod303_report_activity_code_data_views.xml
Labels: bot is merging ⏳

#2761 [15.0][IMP] l10n_es_aeat_sii_oca: Includes new taxes 0%, 0.62% and 5%
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: bot is merging ⏳

#2772 [15.0][FIX] l10n_es_aeat_mod303: 2022 para exonerados 390
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/l10n.es.aeat.mod303.report.activity.code.csv
  l10n_es_aeat_mod303/data/l10n_es_aeat_mod303_report_activity_code_data.xml
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/views/l10n_es_aeat_mod303_report_activity_code_data_views.xml
Labels: bot is merging ⏳

#2775 [16.0][FIX] l10n_es_aeat_mod347: cálculo importe entregas
  l10n_es_aeat_mod347/models/mod347.py
  l10n_es_aeat_mod347/views/mod347_view.xml
Labels: bot is merging ⏳

#2763 [16.0][FIX] l10n_es_aeat_mod347: Formato informe PDF
  l10n_es_aeat_mod347/views/report_347_partner.xml
Labels: approved, bot is merging ⏳

#2776 [16.0][FIX] l10n_es_aeat_mod303: 2022 para exonerados 390
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/l10n.es.aeat.mod303.report.activity.code.csv
  l10n_es_aeat_mod303/data/l10n_es_aeat_mod303_report_activity_code_data.xml
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/views/l10n_es_aeat_mod303_report_activity_code_data_views.xml
Labels: bot is merging ⏳

#2782 [12.0][FIX] l10n_es_aeat_mod303: 2022 para exonerados 390
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/l10n.es.aeat.mod303.report.activity.code.csv
  l10n_es_aeat_mod303/data/l10n_es_aeat_mod303_report_activity_code_data.xml
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/views/l10n_es_aeat_mod303_report_activity_code_data_views.xml
Labels: bot is merging ⏳

#2777 [11.0][FIX] l10n_es_aeat_mod303: 2022 exonerados 390
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/l10n.es.aeat.mod303.report.activity.code.csv
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/views/l10n_es_aeat_mod303_report_activity_code_data_views.xml
Labels: bot is merging ⏳

#2781 [13.0][FIX] l10n_es_aeat_mod390_2022: 2022 format
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/docs/dr390e2017v3.xlsx
  l10n_es_aeat_mod390/docs/dr390e2018.xlsx
  l10n_es_aeat_mod390/docs/dr390e2019v100.xlsx
  l10n_es_aeat_mod390/docs/dr390e2022.xlsx
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: bot is merging ⏳

#2780 [14.0][FIX] l10n_es_aeat_mod390_2022: 2022 format
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/docs/dr390e2017v3.xlsx
  l10n_es_aeat_mod390/docs/dr390e2018.xlsx
  l10n_es_aeat_mod390/docs/dr390e2019v100.xlsx
  l10n_es_aeat_mod390/docs/dr390e2022.xlsx
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: approved, bot is merging ⏳

#2716 [12.0][ADD] l10n_es_extra_data: añadir 0% para alimentación
  l10n_es_extra_data/README.rst
  l10n_es_extra_data/__manifest__.py
  l10n_es_extra_data/data/account_data.xml
  l10n_es_extra_data/data/account_fiscal_position_template_data.xml
  l10n_es_extra_data/data/account_tax_data.xml
  l10n_es_extra_data/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#2785 [16.0][FIX] l10n_es_aeat_mod390_2022: 2022 format
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/docs/dr390e2017v3.xlsx
  l10n_es_aeat_mod390/docs/dr390e2018.xlsx
  l10n_es_aeat_mod390/docs/dr390e2019v100.xlsx
  l10n_es_aeat_mod390/docs/dr390e2022.xlsx
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: bot is merging ⏳

#2789 [16.0][FIX] l10n_es_aeat_mod303: Domain for other activity codes
  l10n_es_aeat_mod303/models/mod303.py
Labels: bot is merging ⏳

#2790 [14.0][FIX] l10n_es_aeat_mod303: Domain for other activity codes
  l10n_es_aeat_mod303/models/mod303.py
Labels: bot is merging ⏳

#2752 [12.0][IMP] l10n_es_aeat_mod_390: BOE format 2022
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: bot is merging ⏳

#2783 [15.0][FIX] l10n_es_aeat_mod390_2022: 2022 format
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/docs/dr390e2017v3.xlsx
  l10n_es_aeat_mod390/docs/dr390e2018.xlsx
  l10n_es_aeat_mod390/docs/dr390e2019v100.xlsx
  l10n_es_aeat_mod390/docs/dr390e2022.xlsx
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: bot is merging ⏳

#2792 [15.0][FIX] l10n_es_aeat_mod303: Domain for other activity codes
  l10n_es_aeat_mod303/models/mod303.py
Labels: bot is merging ⏳

#2794 [12.0][FIX] l10n_es_aeat_mod390: BOE export typo + required
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: bot is merging ⏳

#2798 [13.0][FIX] l10n_es_mod390: Set main_activity_code as required only for calculated state
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: bot is merging ⏳

#2799 [14.0][FIX] l10n_es_mod390: Set main_activity_code as required only for calculated state
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: bot is merging ⏳

#2800 [15.0][FIX] l10n_es_mod390: Set main_activity_code as required only for calculated state
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: bot is merging ⏳

#2801 [16.0][FIX] l10n_es_mod390: Set main_activity_code as required only for calculated state
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: bot is merging ⏳

#2774 [14.0][FIX] l10n_es_aeat_mod349: Operation key not taken into account in refunds
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#2722 [12.0][FIX] l10n_es_ticketbai_api_batuz - normalizar cálculo de ejercicio
  l10n_es_ticketbai_api_batuz/lroe/lroe_api.py
  l10n_es_ticketbai_api_batuz/models/lroe_operation.py
  l10n_es_ticketbai_api_batuz/tests/test_lroe_api.py
Labels: bot is merging ⏳

#2803 [15.0][FIX] l10n_es_aeat_mod349: Operation key not taken into account in refunds
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#2721 [11.0][FIX] l10n_es_ticketbai_api_batuz - normalizar cálculo de ejercicio
  l10n_es_ticketbai_api_batuz/lroe/lroe_api.py
  l10n_es_ticketbai_api_batuz/models/lroe_operation.py
  l10n_es_ticketbai_api_batuz/tests/test_lroe_api.py
Labels: bot is merging ⏳

#2805 [13.0][FIX] l10n_es_aeat_mod349: Operation key not taken into account in refunds
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#2809 [FIX] l10n_es_aeat_mod390: missing dependency
  l10n_es_aeat_mod390/__manifest__.py
Labels: bot is merging ⏳

#2715 [11.0][ADD] l10n_es_extra_data: añadir 0% para alimentación
  l10n_es_extra_data/README.rst
  l10n_es_extra_data/__manifest__.py
  l10n_es_extra_data/data/account_data.xml
  l10n_es_extra_data/data/account_fiscal_position_template_data.xml
  l10n_es_extra_data/data/account_tax_data.xml
  l10n_es_extra_data/readme/CONTRIBUTORS.rst
Labels: approved, ready to merge, bot is merging ⏳
