Repository OCA/l10n-spain, pull requests merged in 2023-10, with the labels that each got.

#3233 [16.0][IMP] l10n_es_account_statement_import_n43: Support for 0 amount lines
  l10n_es_account_statement_import_n43/tests/test.n43
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
Labels: approved, bot is merging ⏳

#3111 [16.0][MIG] l10n_es_intrastat_report: Migration to 16.0
  l10n_es_intrastat_report/README.rst
  l10n_es_intrastat_report/__init__.py
  l10n_es_intrastat_report/__manifest__.py
  l10n_es_intrastat_report/data/Estruc_NC2023.xlsx
  l10n_es_intrastat_report/data/NC_20.xls
  l10n_es_intrastat_report/data/account_fiscal_position_template.xml
  l10n_es_intrastat_report/data/intrastat_transaction.xml
  l10n_es_intrastat_report/hooks.py
  l10n_es_intrastat_report/i18n/ca.po
  l10n_es_intrastat_report/i18n/es.po
  l10n_es_intrastat_report/i18n/l10n_es_intrastat_report.pot
  l10n_es_intrastat_report/migrations/16.0.1.0.0/post-migration.py
  l10n_es_intrastat_report/models/__init__.py
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
  l10n_es_intrastat_report/models/stock_location.py
  l10n_es_intrastat_report/readme/CONFIGURE.rst
  l10n_es_intrastat_report/readme/CONTRIBUTORS.rst
  l10n_es_intrastat_report/readme/DESCRIPTION.rst
  l10n_es_intrastat_report/readme/INSTALL.rst
  l10n_es_intrastat_report/readme/ROADMAP.rst
  l10n_es_intrastat_report/readme/USAGE.rst
  l10n_es_intrastat_report/report/__init__.py
  l10n_es_intrastat_report/report/intrastat_product_report_xls.py
  l10n_es_intrastat_report/security/ir.model.access.csv
  l10n_es_intrastat_report/security/l10n_es_intrastat_report_security.xml
  l10n_es_intrastat_report/static/description/icon.png
  l10n_es_intrastat_report/static/description/index.html
  l10n_es_intrastat_report/tests/__init__.py
  l10n_es_intrastat_report/tests/test_l10n_es_intrastat_report.py
  l10n_es_intrastat_report/views/l10n_es_intrastat_product.xml
  l10n_es_intrastat_report/wizards/__init__.py
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.py
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.xml
  setup/l10n_es_intrastat_report/odoo/addons/l10n_es_intrastat_report
  setup/l10n_es_intrastat_report/setup.py
Labels: bot is merging ⏳

#3135 [13.0][FIX] l10n_es_aeat_mod303: update map tax line for field number 31.
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
Labels: approved, ready to merge, bot is merging ⏳

#3256 [16.0][FIX] l10n_es_pos_sii: Set auto_install correctly on manifest
  l10n_es_pos_sii/__manifest__.py
Labels: bot is merging ⏳

#3261 [13.0][FIX] l10n_es_partner: Bank data download URL
  l10n_es_partner/wizard/l10n_es_partner_wizard.py
Labels: bot is merging ⏳

#3260 [13.0][FIX] l10n_es_facturae_face: Error de vista y mejora de README
  l10n_es_facturae_face/readme/CONTRIBUTORS.rst
  l10n_es_facturae_face/readme/INSTALL.rst
  l10n_es_facturae_face/readme/USAGE.rst
  l10n_es_facturae_face/views/res_partner.xml
Labels: bot is merging ⏳

#3262 [14.0][FIX] l10n_es_partner: Bank data download URL
  l10n_es_partner/wizard/l10n_es_partner_wizard.py
Labels: bot is merging ⏳

#3259 [14.0][IMP] l10n_es_facturae_face: Improve readme
  l10n_es_facturae_face/readme/INSTALL.rst
  l10n_es_facturae_face/readme/USAGE.rst
Labels: bot is merging ⏳

#3264 [16.0][FIX] l10n_es_partner: Bank data download URL + local file fallback
  l10n_es_partner/gen_src/REGBANESP_CONESTAB_A.xls
  l10n_es_partner/wizard/l10n_es_partner_wizard.py
Labels: bot is merging ⏳

#3263 [15.0][FIX] l10n_es_partner: Bank data download URL + local file fallback
  l10n_es_partner/gen_src/REGBANESP_CONESTAB_A.xls
  l10n_es_partner/wizard/l10n_es_partner_wizard.py
Labels: bot is merging ⏳

#3265 [12.0][FIX] l10n_es_partner: Bank data download URL
  l10n_es_partner/wizard/l10n_es_partner_wizard.py
Labels: bot is merging ⏳

#3253 [15.0][MIG] l10n_es_aeat_mod130: Migration to version 15.0
  l10n_es_aeat_mod130/README.rst
  l10n_es_aeat_mod130/__init__.py
  l10n_es_aeat_mod130/__manifest__.py
  l10n_es_aeat_mod130/data/aeat_export_mod130_data.xml
  l10n_es_aeat_mod130/doc/DR130e15v12.xls
  l10n_es_aeat_mod130/i18n/bg.po
  l10n_es_aeat_mod130/i18n/ca.po
  l10n_es_aeat_mod130/i18n/ca_ES.po
  l10n_es_aeat_mod130/i18n/cs.po
  l10n_es_aeat_mod130/i18n/en_US.po
  l10n_es_aeat_mod130/i18n/es.po
  l10n_es_aeat_mod130/i18n/es_CO.po
  l10n_es_aeat_mod130/i18n/es_CR.po
  l10n_es_aeat_mod130/i18n/eu.po
  l10n_es_aeat_mod130/i18n/fr.po
  l10n_es_aeat_mod130/i18n/gl.po
  l10n_es_aeat_mod130/i18n/hr.po
  l10n_es_aeat_mod130/i18n/l10n_es_aeat_mod130.pot
  l10n_es_aeat_mod130/i18n/nl.po
  l10n_es_aeat_mod130/i18n/pl.po
  l10n_es_aeat_mod130/i18n/pt.po
  l10n_es_aeat_mod130/i18n/pt_BR.po
  l10n_es_aeat_mod130/i18n/ru.po
  l10n_es_aeat_mod130/i18n/sl.po
  l10n_es_aeat_mod130/i18n/sv.po
  l10n_es_aeat_mod130/i18n/tr.po
  l10n_es_aeat_mod130/i18n/vi.po
  l10n_es_aeat_mod130/models/__init__.py
  l10n_es_aeat_mod130/models/mod130.py
  l10n_es_aeat_mod130/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod130/readme/DESCRIPTION.rst
  l10n_es_aeat_mod130/readme/ROADMAP.rst
  l10n_es_aeat_mod130/security/ir.model.access.csv
  l10n_es_aeat_mod130/security/ir_rule.xml
  l10n_es_aeat_mod130/static/description/icon.png
  l10n_es_aeat_mod130/static/description/icon_source.svg
  l10n_es_aeat_mod130/static/description/index.html
  l10n_es_aeat_mod130/tests/__init__.py
  l10n_es_aeat_mod130/tests/test_l10n_es_aeat_mod130.py
  l10n_es_aeat_mod130/views/mod130_view.xml
  setup/l10n_es_aeat_mod130/odoo/addons/l10n_es_aeat_mod130
  setup/l10n_es_aeat_mod130/setup.py
Labels: bot is merging ⏳

#3266 [14.0][IMP] l10n_es_intrastat_report: Set the fiscal position "Régimen Intracomunitario" with Intrastat flag
  l10n_es_intrastat_report/data/account_fiscal_position_template.xml
  l10n_es_intrastat_report/hooks.py
Labels: bot is merging ⏳

#3269 [14.0][IMP] l10n_es_aeat: Make it work with multicompanies
  l10n_es_aeat/models/l10n_es_aeat_report.py
Labels: bot is merging ⏳

#3270 [16.0][IMP] l10n_es_aeat: Make it work with multicompanies
  l10n_es_aeat/models/l10n_es_aeat_report.py
Labels: bot is merging ⏳

#3271 [15.0][IMP] l10n_es_aeat: Make it work with multicompanies
  l10n_es_aeat/models/l10n_es_aeat_report.py
Labels: bot is merging ⏳

#3272 [15.0][IMP] l10n_es_intrastat_report: Set the fiscal position "Régimen Intracomunitario" with Intrastat flag
  l10n_es_intrastat_report/data/account_fiscal_position_template.xml
  l10n_es_intrastat_report/hooks.py
Labels: bot is merging ⏳

#3273 [16.0][IMP] l10n_es_intrastat_report: Set the fiscal position "Régimen Intracomunitario" with Intrastat flag
  l10n_es_intrastat_report/data/account_fiscal_position_template.xml
  l10n_es_intrastat_report/hooks.py
Labels: bot is merging ⏳

#3274 [16.0][FIX] l10n_es_intrastat_report: Change fp_intra_private to b2c (type of transaction)
  l10n_es_intrastat_report/data/account_fiscal_position_template.xml
Labels: bot is merging ⏳

#3276 [13.0[FIX] l10n_es_facturae: Missing l10n_es_aeat dependency
  l10n_es_facturae/__manifest__.py
Labels: bot is merging ⏳

#3249 [MIG] l10n_es_aeat_sii_match: Migration to 13.0
  l10n_es_aeat_sii_match/README.rst
  l10n_es_aeat_sii_match/__init__.py
  l10n_es_aeat_sii_match/__manifest__.py
  l10n_es_aeat_sii_match/i18n/es.po
  l10n_es_aeat_sii_match/i18n/l10n_es_aeat_sii_match.pot
  l10n_es_aeat_sii_match/migrations/13.0.1.0.0/post-migration.py
  l10n_es_aeat_sii_match/migrations/13.0.1.0.0/pre-migration.py
  l10n_es_aeat_sii_match/models/__init__.py
  l10n_es_aeat_sii_match/models/account_move.py
  l10n_es_aeat_sii_match/models/aeat_sii_match_difference.py
  l10n_es_aeat_sii_match/models/aeat_sii_match_report.py
  l10n_es_aeat_sii_match/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_match/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_match/security/aeat_sii.xml
  l10n_es_aeat_sii_match/security/ir.model.access.csv
  l10n_es_aeat_sii_match/static/description/icon.png
  l10n_es_aeat_sii_match/static/description/index.html
  l10n_es_aeat_sii_match/views/account_move_views.xml
  l10n_es_aeat_sii_match/views/aeat_sii_match_report.xml
  setup/l10n_es_aeat_sii_match/odoo/addons/l10n_es_aeat_sii_match
  setup/l10n_es_aeat_sii_match/setup.py
Labels: bot is merging ⏳

#3280 [FWP] [16.0] l10n_es_aeat_sii_oca: Check for SII Exceptions when posting an invoice
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: approved, bot is merging ⏳

#3278 [15.0][IMP] l10n-spain : test performance improvement
  l10n_es_account_asset/tests/test_l10n_es_account_asset.py
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
  l10n_es_aeat/tests/test_l10n_es_aeat.py
  l10n_es_aeat/tests/test_l10n_es_aeat_certificate.py
  l10n_es_aeat/tests/test_l10n_es_aeat_export_config.py
  l10n_es_aeat/tests/test_l10n_es_aeat_map_tax.py
  l10n_es_aeat/tests/test_l10n_es_aeat_mod_base.py
  l10n_es_aeat/tests/test_l10n_es_aeat_report.py
  l10n_es_partner/tests/test_l10n_es_partner.py
  l10n_es_toponyms/tests/test_l10n_es_toponyms.py
Labels: bot is merging ⏳

#3287 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  delivery_gls_asm/i18n/ca.po
  delivery_gls_asm/i18n/delivery_gls_asm.pot
  delivery_gls_asm/i18n/es.po
  delivery_gls_asm/models/delivery_carrier.py
  l10n_es_aeat/i18n/l10n_es_aeat.pot
  l10n_es_aeat_mod111/i18n/l10n_es_aeat_mod111.pot
  l10n_es_aeat_mod115/i18n/l10n_es_aeat_mod115.pot
  l10n_es_aeat_mod123/i18n/l10n_es_aeat_mod123.pot
  l10n_es_aeat_mod130/i18n/l10n_es_aeat_mod130.pot
  l10n_es_aeat_mod190/i18n/l10n_es_aeat_mod190.pot
  l10n_es_aeat_mod216/i18n/l10n_es_aeat_mod216.pot
  l10n_es_aeat_mod296/i18n/l10n_es_aeat_mod296.pot
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod347/i18n/l10n_es_aeat_mod347.pot
  l10n_es_aeat_mod349/i18n/l10n_es_aeat_mod349.pot
  l10n_es_aeat_mod369/i18n/l10n_es_aeat_mod369.pot
  l10n_es_aeat_mod390/i18n/l10n_es_aeat_mod390.pot
  l10n_es_intrastat_report/i18n/l10n_es_intrastat_report.pot
  l10n_es_ticketbai_api/__manifest__.py
  l10n_es_vat_book/i18n/l10n_es_vat_book.pot
Labels: help wanted, needs review

#3286 [16.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  l10n_es_aeat/i18n/l10n_es_aeat.pot
  l10n_es_aeat_mod111/i18n/l10n_es_aeat_mod111.pot
  l10n_es_aeat_mod115/i18n/l10n_es_aeat_mod115.pot
  l10n_es_aeat_mod123/i18n/l10n_es_aeat_mod123.pot
  l10n_es_aeat_mod216/i18n/l10n_es_aeat_mod216.pot
  l10n_es_aeat_mod296/i18n/l10n_es_aeat_mod296.pot
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod347/i18n/l10n_es_aeat_mod347.pot
  l10n_es_aeat_mod349/i18n/l10n_es_aeat_mod349.pot
  l10n_es_aeat_mod390/i18n/l10n_es_aeat_mod390.pot
  l10n_es_facturae/models/__init__.py
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/models/account_move_line.py
  l10n_es_intrastat_report/i18n/l10n_es_intrastat_report.pot
  l10n_es_pos/static/src/js/models.js
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/wizard/account_move_reversal.py
  l10n_es_vat_book/i18n/l10n_es_vat_book.pot
Labels: help wanted, needs review, bot is merging ⏳

#3079 [16.0][ADD] l10n_es_atc
  l10n_es_atc/README.rst
  l10n_es_atc/__init__.py
  l10n_es_atc/__manifest__.py
  l10n_es_atc/data/atc_partner.xml
  l10n_es_atc/readme/CONTRIBUTORS.rst
  l10n_es_atc/readme/DESCRIPTION.rst
  l10n_es_atc/security/atc_security.xml
  l10n_es_atc/static/description/icon.png
  l10n_es_atc/static/description/index.html
  l10n_es_atc/views/atc_menuitem.xml
  setup/l10n_es_atc/odoo/addons/l10n_es_atc
  setup/l10n_es_atc/setup.py
Labels: bot is merging ⏳

#3268 [14.0][ADD] l10n_es_aeat_mod322
  l10n_es_aeat_mod322/README.rst
  l10n_es_aeat_mod322/__init__.py
  l10n_es_aeat_mod322/__manifest__.py
  l10n_es_aeat_mod322/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod322/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod322/data/2023/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod322/data/2023/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod322/models/__init__.py
  l10n_es_aeat_mod322/models/l10n_es_aeat_mod322_group.py
  l10n_es_aeat_mod322/models/l10n_es_aeat_mod322_report.py
  l10n_es_aeat_mod322/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod322/readme/DESCRIPTION.rst
  l10n_es_aeat_mod322/readme/USAGE.rst
  l10n_es_aeat_mod322/security/ir.model.access.csv
  l10n_es_aeat_mod322/security/security.xml
  l10n_es_aeat_mod322/static/description/icon.png
  l10n_es_aeat_mod322/static/description/icon_source.svg
  l10n_es_aeat_mod322/static/description/index.html
  l10n_es_aeat_mod322/tests/__init__.py
  l10n_es_aeat_mod322/tests/test_mod322.py
  l10n_es_aeat_mod322/views/l10n_es_aeat_mod322_group.xml
  l10n_es_aeat_mod322/views/l10n_es_aeat_mod322_report.xml
  setup/l10n_es_aeat_mod322/odoo/addons/l10n_es_aeat_mod322
  setup/l10n_es_aeat_mod322/setup.py
Labels: bot is merging ⏳

#3284 [14.0][IMP] l10n_es_account_statement_import_n43: Define transaction reference (same as v13)
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
Labels: bot is merging ⏳

#3255 [16.0][MIG] l10n_es_aeat_mod190
  l10n_es_aeat_mod190/README.rst
  l10n_es_aeat_mod190/__init__.py
  l10n_es_aeat_mod190/__manifest__.py
  l10n_es_aeat_mod190/data/aeat_export_mod190_data.xml
  l10n_es_aeat_mod190/data/aeat_export_mod190_partner_data.xml
  l10n_es_aeat_mod190/data/perception_key_data.xml
  l10n_es_aeat_mod190/data/perception_subkey_data.xml
  l10n_es_aeat_mod190/data/tax_code_map_mod190_data.xml
  l10n_es_aeat_mod190/docs/DR190_2017.pdf
  l10n_es_aeat_mod190/i18n/ca.po
  l10n_es_aeat_mod190/i18n/ca_ES.po
  l10n_es_aeat_mod190/i18n/es.po
  l10n_es_aeat_mod190/i18n/l10n_es_aeat_mod190.pot
  l10n_es_aeat_mod190/models/__init__.py
  l10n_es_aeat_mod190/models/account_fiscal_position.py
  l10n_es_aeat_mod190/models/account_move.py
  l10n_es_aeat_mod190/models/account_move_line.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_perception.py
  l10n_es_aeat_mod190/models/res_partner.py
  l10n_es_aeat_mod190/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod190/readme/DESCRIPTION.rst
  l10n_es_aeat_mod190/readme/USAGE.rst
  l10n_es_aeat_mod190/security/ir.model.access.csv
  l10n_es_aeat_mod190/security/l10n_es_aeat_mod190_security.xml
  l10n_es_aeat_mod190/static/description/icon.png
  l10n_es_aeat_mod190/static/description/icon_source.svg
  l10n_es_aeat_mod190/static/description/index.html
  l10n_es_aeat_mod190/tests/__init__.py
  l10n_es_aeat_mod190/tests/test_mod190.py
  l10n_es_aeat_mod190/views/account_fiscal_position.xml
  l10n_es_aeat_mod190/views/account_invoice_view.xml
  l10n_es_aeat_mod190/views/account_move_view.xml
  l10n_es_aeat_mod190/views/mod190_line_view.xml
  l10n_es_aeat_mod190/views/mod190_view.xml
  l10n_es_aeat_mod190/views/partner_view.xml
  setup/l10n_es_aeat_mod190/odoo/addons/l10n_es_aeat_mod190
  setup/l10n_es_aeat_mod190/setup.py
Labels: bot is merging ⏳

#3292 [REM] DESCRIPTION.rst function that does not exist.
  l10n_es_account_asset/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#3291 [15.0][IMP] l10n_es_account_statement_import_n43: Define transaction reference (same as v13)
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
Labels: bot is merging ⏳

#3293 [16.0][IMP] l10n_es_account_statement_import_n43: Define transaction reference (same as v13)
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
Labels: bot is merging ⏳
