Repository OCA/l10n-spain, pull requests merged in 2023-04, with the labels that each got.

#2968 [15.0][MIG] payment_redsys: Migration to version 15.0
  payment_redsys/README.rst
  payment_redsys/__init__.py
  payment_redsys/__manifest__.py
  payment_redsys/controllers/__init__.py
  payment_redsys/controllers/main.py
  payment_redsys/data/payment_redsys.xml
  payment_redsys/i18n/bg.po
  payment_redsys/i18n/ca.po
  payment_redsys/i18n/es.po
  payment_redsys/i18n/fr.po
  payment_redsys/i18n/gl.po
  payment_redsys/i18n/hr.po
  payment_redsys/i18n/payment_redsys.pot
  payment_redsys/i18n/pt_BR.po
  payment_redsys/i18n/sl.po
  payment_redsys/models/__init__.py
  payment_redsys/models/account_payment_method.py
  payment_redsys/models/payment_acquirer.py
  payment_redsys/models/payment_transaction.py
  payment_redsys/readme/CONFIGURE.rst
  payment_redsys/readme/CONTRIBUTORS.rst
  payment_redsys/readme/DESCRIPTION.rst
  payment_redsys/readme/INSTALL.rst
  payment_redsys/readme/ROADMAP.rst
  payment_redsys/static/description/icon.png
  payment_redsys/static/description/index.html
  payment_redsys/static/img/bizum.png
  payment_redsys/static/src/img/redsys_icon.png
  payment_redsys/tests/__init__.py
  payment_redsys/tests/common.py
  payment_redsys/tests/test_redsys.py
  payment_redsys/views/payment_acquirer.xml
  payment_redsys/views/payment_redsys_templates.xml
  requirements.txt
  setup/payment_redsys/odoo/addons/payment_redsys
  setup/payment_redsys/setup.py
Labels: bot is merging ⏳

#2971 [16.0][MIG] l10n_es_mis_report: Migration to 16.0
  l10n_es_mis_report/README.rst
  l10n_es_mis_report/__init__.py
  l10n_es_mis_report/__manifest__.py
  l10n_es_mis_report/data/mis_report_balance_abreviated.xml
  l10n_es_mis_report/data/mis_report_balance_normal.xml
  l10n_es_mis_report/data/mis_report_balance_sme.xml
  l10n_es_mis_report/data/mis_report_balance_sme_sfl.xml
  l10n_es_mis_report/data/mis_report_pyg_abreviated.xml
  l10n_es_mis_report/data/mis_report_pyg_normal.xml
  l10n_es_mis_report/data/mis_report_pyg_sme.xml
  l10n_es_mis_report/data/mis_report_pyg_sme_sfl.xml
  l10n_es_mis_report/data/mis_report_revenues_expenses_normal.xml
  l10n_es_mis_report/data/mis_report_styles.xml
  l10n_es_mis_report/i18n/ca.po
  l10n_es_mis_report/i18n/es.po
  l10n_es_mis_report/i18n/l10n_es_mis_report.pot
  l10n_es_mis_report/readme/CONTRIBUTORS.rst
  l10n_es_mis_report/readme/DESCRIPTION.rst
  l10n_es_mis_report/readme/INSTALL.rst
  l10n_es_mis_report/readme/USAGE.rst
  l10n_es_mis_report/static/description/icon.png
  l10n_es_mis_report/static/description/index.html
  setup/l10n_es_mis_report/odoo/addons/l10n_es_mis_report
  setup/l10n_es_mis_report/setup.py
Labels: approved, bot is merging ⏳

#2614 [15.0][MIG] l10n_es_aeat_mod190: Migration to 15.0
  l10n_es_aeat_mod190/README.rst
  l10n_es_aeat_mod190/__init__.py
  l10n_es_aeat_mod190/__manifest__.py
  l10n_es_aeat_mod190/data/aeat_export_mod190_data.xml
  l10n_es_aeat_mod190/data/aeat_export_mod190_partner_data.xml
  l10n_es_aeat_mod190/data/perception_key_data.xml
  l10n_es_aeat_mod190/data/perception_subkey_data.xml
  l10n_es_aeat_mod190/data/tax_code_map_mod190_data.xml
  l10n_es_aeat_mod190/docs/DR190_2017.pdf
  l10n_es_aeat_mod190/i18n/l10n_es_aeat_mod190.pot
  l10n_es_aeat_mod190/models/__init__.py
  l10n_es_aeat_mod190/models/account_fiscal_position.py
  l10n_es_aeat_mod190/models/account_move.py
  l10n_es_aeat_mod190/models/account_move_line.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_perception.py
  l10n_es_aeat_mod190/models/res_partner.py
  l10n_es_aeat_mod190/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod190/readme/DESCRIPTION.rst
  l10n_es_aeat_mod190/readme/USAGE.rst
  l10n_es_aeat_mod190/security/ir.model.access.csv
  l10n_es_aeat_mod190/security/l10n_es_aeat_mod190_security.xml
  l10n_es_aeat_mod190/static/description/icon.png
  l10n_es_aeat_mod190/static/description/icon_source.svg
  l10n_es_aeat_mod190/static/description/index.html
  l10n_es_aeat_mod190/tests/__init__.py
  l10n_es_aeat_mod190/tests/test_mod190.py
  l10n_es_aeat_mod190/views/account_fiscal_position.xml
  l10n_es_aeat_mod190/views/account_invoice_view.xml
  l10n_es_aeat_mod190/views/account_move_view.xml
  l10n_es_aeat_mod190/views/mod190_line_view.xml
  l10n_es_aeat_mod190/views/mod190_view.xml
  l10n_es_aeat_mod190/views/partner_view.xml
  l10n_es_aeat_mod303_oss/tests/test_l10n_es_aeat_mod303_oss.py
  setup/l10n_es_aeat_mod190/odoo/addons/l10n_es_aeat_mod190
  setup/l10n_es_aeat_mod190/setup.py
Labels: bot is merging ⏳

#2793 [16.0][MIG] l10n_es_account_statement_import_n43
  l10n_es_account_statement_import_n43/README.rst
  l10n_es_account_statement_import_n43/__init__.py
  l10n_es_account_statement_import_n43/__manifest__.py
  l10n_es_account_statement_import_n43/doc/norma_43_castellano.pdf
  l10n_es_account_statement_import_n43/i18n/ca.po
  l10n_es_account_statement_import_n43/i18n/es.po
  l10n_es_account_statement_import_n43/i18n/eu.po
  l10n_es_account_statement_import_n43/i18n/fr.po
  l10n_es_account_statement_import_n43/i18n/gl.po
  l10n_es_account_statement_import_n43/i18n/l10n_es_account_bank_statement_import_n43.pot
  l10n_es_account_statement_import_n43/i18n/l10n_es_account_statement_import_n43.pot
  l10n_es_account_statement_import_n43/i18n/sl.po
  l10n_es_account_statement_import_n43/models/__init__.py
  l10n_es_account_statement_import_n43/models/account_journal.py
  l10n_es_account_statement_import_n43/readme/CONTRIBUTORS.rst
  l10n_es_account_statement_import_n43/readme/DESCRIPTION.rst
  l10n_es_account_statement_import_n43/readme/ROADMAP.rst
  l10n_es_account_statement_import_n43/readme/USAGE.rst
  l10n_es_account_statement_import_n43/static/description/icon.png
  l10n_es_account_statement_import_n43/static/description/icon_src.svg
  l10n_es_account_statement_import_n43/static/description/index.html
  l10n_es_account_statement_import_n43/tests/__init__.py
  l10n_es_account_statement_import_n43/tests/test.n43
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
  l10n_es_account_statement_import_n43/tests/testmulti.n43
  l10n_es_account_statement_import_n43/views/account_journal_views.xml
  l10n_es_account_statement_import_n43/wizards/__init__.py
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
  l10n_es_account_statement_import_n43/wizards/account_statement_import_view.xml
  requirements.txt
  setup/l10n_es_account_statement_import_n43/odoo/addons/l10n_es_account_statement_import_n43
  setup/l10n_es_account_statement_import_n43/setup.py
Labels: approved, bot is merging ⏳

#2981 [15.0][IMP] l10n_es_aeat_mod303_oss: include lines oss in map mod303 2023
  l10n_es_aeat_mod303_oss/__manifest__.py
  l10n_es_aeat_mod303_oss/data/2021-07/l10n_es_aeat_map_tax_line.xml
  l10n_es_aeat_mod303_oss/data/2023/l10n_es_aeat_map_tax_line.xml
  l10n_es_aeat_mod303_oss/models/mod303.py
Labels: bot is merging ⏳

#2977 [16.0][FIX] l10n_es_partner: _rec_names_search
  l10n_es_partner/models/res_partner.py
  l10n_es_partner/tests/test_l10n_es_partner.py
Labels: bot is merging ⏳

#2987 [15.0][FIX] l10n_es_facturae: Field should not be invisible
  l10n_es_facturae/views/account_move_view.xml
Labels: bot is merging ⏳

#2967 [15.0][IMP] l10n_es_facturae: improvements view facturae
  l10n_es_facturae/wizard/create_facturae_view.xml
Labels: bot is merging ⏳

#2988 [14.0][IMP] l10n_es_vat_book: Clean vat book line
  l10n_es_vat_book/models/l10n_es_vat_book_line.py
Labels: bot is merging ⏳

#2989 [15.0][IMP] l10n_es_vat_book: Clean vat book line
  l10n_es_vat_book/models/l10n_es_vat_book_line.py
Labels: bot is merging ⏳

#2994 [15.0][IMP] l10n_es_vat_book: Remove duplicated taxes
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#2986 [12.0][IMP] l10n_es_vat_book_extra_data: include 2023 map taxes.
  l10n_es_vat_book_extra_data/data/aeat_vat_book_map_data.xml
Labels: approved, ready to merge, bot is merging ⏳

#2999 [14.0][FIX] l10n_es_aeat_mod130: Type for 0 result must be N
  l10n_es_aeat_mod130/models/mod130.py
Labels: bot is merging ⏳

#2997 [14.0][IMP] l10n_es_vat_prorate: Onchange should apply on invoice line, not lines
  l10n_es_vat_prorate/models/account_move.py
Labels: bot is merging ⏳

#3007 [12.0][IMP] l10n_es_vat_book_extra_data: include 2023 map taxes.
  l10n_es_vat_book_extra_data/data/aeat_vat_book_map_data.xml
Labels: approved, bot is merging ⏳

#3006 [11.0][IMP] l10n_es_vat_book_extra_data: include 2023 map taxes.
  l10n_es_vat_book_extra_data/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#2573 [13.0][FIX] l10n_es_ticketbai_batuz: end of quarter calculation
  l10n_es_ticketbai_batuz/models/lroe_operation.py
  l10n_es_ticketbai_batuz/models/res_company.py
Labels: approved, bot is merging ⏳, stale

#3012 [14.0][FIX] l10n_es_ticketbai_batuz: end of quarter calculation
  l10n_es_ticketbai_batuz/models/lroe_operation.py
  l10n_es_ticketbai_batuz/models/res_company.py
Labels: bot is merging ⏳

#3014 [15.0][FIX] l10n_es_ticketbai_batuz: end of quarter calculation
  l10n_es_ticketbai_batuz/models/lroe_operation.py
  l10n_es_ticketbai_batuz/models/res_company.py
Labels: bot is merging ⏳

#3013 [12.0][FIX] l10n_es_aeat_mod303: Don't put bank details if not foreign
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: bot is merging ⏳

#3018 [16.0][IMP] l10n_es_vat_book: Remove duplicated taxes
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳
