Repository OCA/l10n-spain, pull requests merged in 2023-09, with the labels that each got.

#2991 [14.0][IMP] delivery_dhl_parcel: Cash on delivery
  delivery_dhl_parcel/i18n/delivery_dhl_parcel.pot
  delivery_dhl_parcel/i18n/es.po
  delivery_dhl_parcel/models/__init__.py
  delivery_dhl_parcel/models/delivery_carrier.py
  delivery_dhl_parcel/models/sale_order.py
  delivery_dhl_parcel/readme/USAGE.rst
  delivery_dhl_parcel/views/delivery_carrier_view.xml
Labels: approved, bot is merging ⏳

#3152 [16.0][MIG] l10n_es_pos_sii: Migration to 16.0
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/data/aeat_sii_queue_job.xml
  l10n_es_aeat_sii_oca/migrations/16.0.1.4.0/post-migration.py
  l10n_es_aeat_sii_oca/models/__init__.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/models/sii_mixin.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
  l10n_es_aeat_sii_oss/models/account_move.py
  l10n_es_dua_sii/models/account_move.py
  l10n_es_pos_sii/README.rst
  l10n_es_pos_sii/__init__.py
  l10n_es_pos_sii/__manifest__.py
  l10n_es_pos_sii/i18n/es.po
  l10n_es_pos_sii/models/__init__.py
  l10n_es_pos_sii/models/pos_order.py
  l10n_es_pos_sii/models/pos_session.py
  l10n_es_pos_sii/models/res_company.py
  l10n_es_pos_sii/readme/CONFIGURE.rst
  l10n_es_pos_sii/readme/CONTRIBUTORS.rst
  l10n_es_pos_sii/readme/DESCRIPTION.rst
  l10n_es_pos_sii/readme/ROADMAP.rst
  l10n_es_pos_sii/static/description/index.html
  l10n_es_pos_sii/tests/__init__.py
  l10n_es_pos_sii/tests/json/sii_pos_order_iva10b.json
  l10n_es_pos_sii/tests/json/sii_pos_order_iva21b.json
  l10n_es_pos_sii/tests/json/sii_pos_order_iva21b_iva10b.json
  l10n_es_pos_sii/tests/json/sii_pos_order_refund_iva21b.json
  l10n_es_pos_sii/tests/test_l10n_es_pos_sii.py
  l10n_es_pos_sii/views/pos_order.xml
  l10n_es_pos_sii/views/res_company.xml
  setup/l10n_es_pos_sii/odoo/addons/l10n_es_pos_sii
  setup/l10n_es_pos_sii/setup.py
Labels: approved, bot is merging ⏳

#3216 [16.0][FIX] l10n_es_vat_prorate: Restrict vat prorate value
  l10n_es_vat_prorate/i18n/l10n_es_vat_prorate.pot
  l10n_es_vat_prorate/models/res_company.py
  l10n_es_vat_prorate/readme/CONTRIBUTORS.rst
  l10n_es_vat_prorate/static/description/index.html
  l10n_es_vat_prorate/tests/test_vat_prorate.py
Labels: bot is merging ⏳

#3219 [14.0][IMP]l10n_es_account_statement_import_n43: Usar partners de la compañía solamente
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
Labels: bot is merging ⏳

#3221 [14.0][FIX] l10n_es_facturae_face: Set rules in the new way
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/data/edi.xml
  l10n_es_facturae_face/migrations/14.0.2.4.0/pre-migration.py
Labels: bot is merging ⏳

#3042 [14.0][IMP] delivery_gls_asm: Notas envío GLS
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/models/stock_picking.py
  delivery_gls_asm/views/stock_picking_views.xml
Labels: bot is merging ⏳, stale

#3225 [15.0][FIX] delivery_gls_asm: wrong keyword literals
  delivery_gls_asm/i18n/ca.po
  delivery_gls_asm/i18n/delivery_gls_asm.pot
  delivery_gls_asm/i18n/es.po
  delivery_gls_asm/models/gls_asm_request.py
  delivery_gls_asm/tests/test_delivery_gls_asm.py
Labels: bot is merging ⏳

#3224 [15.0][FIX] l10n_es_dua_sii: Mapeo de impuestos del SII del 0% Importaciones a la clave DUA
  l10n_es_dua_sii/data/tax_code_map_dua_sii_data.xml
Labels: bot is merging ⏳

#3230 [16.0][FIX] l10n_es_aeat_sii_oca: Avoid invoice copy with type change in tests
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: bot is merging ⏳

#3223 [15.0][IMP] delivery_gls_asm: Notas envío GLS
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/models/stock_picking.py
  delivery_gls_asm/views/stock_picking_views.xml
Labels: bot is merging ⏳

#3226 [16.0][MIG] l10n_es_aeat_mod303_vat_prorate: Migration to version 16.0
  l10n_es_aeat_mod303_vat_prorate/README.rst
  l10n_es_aeat_mod303_vat_prorate/__init__.py
  l10n_es_aeat_mod303_vat_prorate/__manifest__.py
  l10n_es_aeat_mod303_vat_prorate/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303_vat_prorate/i18n/es.po
  l10n_es_aeat_mod303_vat_prorate/i18n/l10n_es_aeat_mod303_vat_prorate.pot
  l10n_es_aeat_mod303_vat_prorate/models/__init__.py
  l10n_es_aeat_mod303_vat_prorate/models/mod303.py
  l10n_es_aeat_mod303_vat_prorate/readme/CONFIGURE.rst
  l10n_es_aeat_mod303_vat_prorate/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303_vat_prorate/readme/DESCRIPTION.rst
  l10n_es_aeat_mod303_vat_prorate/readme/ROADMAP.rst
  l10n_es_aeat_mod303_vat_prorate/readme/USAGE.rst
  l10n_es_aeat_mod303_vat_prorate/static/description/icon.png
  l10n_es_aeat_mod303_vat_prorate/static/description/index.html
  l10n_es_aeat_mod303_vat_prorate/tests/__init__.py
  l10n_es_aeat_mod303_vat_prorate/tests/test_l10n_es_aeat_mod303_vat_prorate.py
  l10n_es_aeat_mod303_vat_prorate/views/mod303_views.xml
  setup/l10n_es_aeat_mod303_vat_prorate/odoo/addons/l10n_es_aeat_mod303_vat_prorate
  setup/l10n_es_aeat_mod303_vat_prorate/setup.py
Labels: bot is merging ⏳

#3151 [15.0][MIG] l10n_es_aeat_sii_match: Migration to 15.0
  l10n_es_aeat_sii_match/README.rst
  l10n_es_aeat_sii_match/__init__.py
  l10n_es_aeat_sii_match/__manifest__.py
  l10n_es_aeat_sii_match/data/queue_job.xml
  l10n_es_aeat_sii_match/i18n/es.po
  l10n_es_aeat_sii_match/i18n/l10n_es_aeat_sii_match.pot
  l10n_es_aeat_sii_match/models/__init__.py
  l10n_es_aeat_sii_match/models/account_move.py
  l10n_es_aeat_sii_match/models/aeat_sii_match_difference.py
  l10n_es_aeat_sii_match/models/aeat_sii_match_report.py
  l10n_es_aeat_sii_match/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_match/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_match/security/aeat_sii.xml
  l10n_es_aeat_sii_match/security/ir.model.access.csv
  l10n_es_aeat_sii_match/static/description/icon.png
  l10n_es_aeat_sii_match/static/description/index.html
  l10n_es_aeat_sii_match/tests/__init__.py
  l10n_es_aeat_sii_match/tests/test_l10n_es_aeat_sii_match.py
  l10n_es_aeat_sii_match/views/account_move_views.xml
  l10n_es_aeat_sii_match/views/aeat_sii_match_report.xml
  requirements.txt
  setup/l10n_es_aeat_sii_match/odoo/addons/l10n_es_aeat_sii_match
  setup/l10n_es_aeat_sii_match/setup.py
Labels: bot is merging ⏳

#3228 [FIX][16.0] payment_redsys: Missing parameter in method override
  payment_redsys/models/payment_provider.py
  payment_redsys/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#3231 [16.0][FIX] l10n_es_dua_sii: Add 2 taxes to SII DUA map
  l10n_es_dua_sii/data/tax_code_map_dua_sii_data.xml
Labels: bot is merging ⏳

#3234 [16.0][FIX] l10n_es_vat_book: Fill correctly special taxes data
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/models/l10n_es_vat_book_line_tax.py
Labels: bot is merging ⏳

#3115 [14.0][FIX] l10n_es_vat_book: Fill correctly special taxes data
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/models/l10n_es_vat_book_line_tax.py
Labels: bot is merging ⏳

#3236 [15.0][FIX] l10n_es_vat_book: Fill correctly special taxes data
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/models/l10n_es_vat_book_line_tax.py
Labels: bot is merging ⏳

#3239 [16.0][BPRT] l10n_es_facturae
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#3238 [15.0][BPRT] l10n_es_facturae
  l10n_es_facturae/models/account_move.py
Labels: bot is merging ⏳

#3242 [14.0][FIX] delivery_gls_asm: Set explicitly # of packages in tests
  delivery_gls_asm/tests/test_delivery_gls_asm.py
Labels: bot is merging ⏳

#3240 [14.0][FIX] l10n_es_facturae_face: improve readme
  l10n_es_facturae_face/readme/CONFIGURE.rst
Labels: bot is merging ⏳

#3235 [15.0][ADD] l10n_es_irnr_sii: Add taxes irnr to sii map
  l10n_es_irnr_sii/README.rst
  l10n_es_irnr_sii/__init__.py
  l10n_es_irnr_sii/__manifest__.py
  l10n_es_irnr_sii/data/tax_code_map_irnr_sii_data.xml
  l10n_es_irnr_sii/readme/CONFIGURE.rst
  l10n_es_irnr_sii/readme/CONTRIBUTORS.rst
  l10n_es_irnr_sii/readme/DESCRIPTION.rst
  l10n_es_irnr_sii/readme/USAGE.rst
  l10n_es_irnr_sii/static/description/icon.png
  setup/l10n_es_irnr_sii/odoo/addons/l10n_es_irnr_sii
  setup/l10n_es_irnr_sii/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3244 [16.0][ADD] l10n_es_irnr_sii: Add taxes irnr to sii map
  l10n_es_irnr_sii/README.rst
  l10n_es_irnr_sii/__init__.py
  l10n_es_irnr_sii/__manifest__.py
  l10n_es_irnr_sii/data/tax_code_map_irnr_sii_data.xml
  l10n_es_irnr_sii/readme/CONFIGURE.rst
  l10n_es_irnr_sii/readme/CONTRIBUTORS.rst
  l10n_es_irnr_sii/readme/DESCRIPTION.rst
  l10n_es_irnr_sii/readme/USAGE.rst
  l10n_es_irnr_sii/static/description/icon.png
  setup/l10n_es_irnr_sii/odoo/addons/l10n_es_irnr_sii
  setup/l10n_es_irnr_sii/setup.py
Labels: bot is merging ⏳

#3246 [14.0][FIX] l10n_es_aeat_sii_oca: wrong job channel name
  l10n_es_aeat_sii_oca/data/aeat_sii_queue_job.xml
Labels: bot is merging ⏳

#3247 [15.0][FIX] l10n_es_aeat_sii_oca: wrong job channel name
  l10n_es_aeat_sii_oca/data/aeat_sii_queue_job.xml
Labels: bot is merging ⏳

#3248 [16.0][FIX] l10n_es_aeat_sii_oca: wrong job channel name
  l10n_es_aeat_sii_oca/data/aeat_sii_queue_job.xml
Labels: bot is merging ⏳

#3197 [16.0][FIX] l10n_es_pos_sii: don't allow invoicing order in a closed session
  l10n_es_pos_sii/__manifest__.py
  l10n_es_pos_sii/i18n/es.po
  l10n_es_pos_sii/models/pos_order.py
  l10n_es_pos_sii/static/src/js/Screens/TicketScreen/ControlButtons/InvoiceButton.js
  l10n_es_pos_sii/static/src/js/models.js
  l10n_es_pos_sii/tests/test_l10n_es_pos_sii.py
Labels: approved, ready to merge, bot is merging ⏳
