Repository OCA/l10n-spain, pull requests merged in 2023-02, with the labels that each got.

#2787 [12.0][FIX] l10n_es_aeat_vat_prorrate: exportar casilla 44 en fichero 2022
  l10n_es_aeat_vat_prorrate/data/aeat_export_mod303_data.xml
  l10n_es_aeat_vat_prorrate/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#2821 [14.0][FIX] l10n_es_payment_order_confirming_sabadell: Align left
  l10n_es_payment_order_confirming_sabadell/models/confirming_sabadell.py
Labels: approved, bot is merging ⏳

#2696 [16.0][MIG] l10n_es_aeat_mod123: Migration to 16.0
  l10n_es_aeat_mod123/README.rst
  l10n_es_aeat_mod123/__init__.py
  l10n_es_aeat_mod123/__manifest__.py
  l10n_es_aeat_mod123/data/aeat_export_mod123_data.xml
  l10n_es_aeat_mod123/data/tax_code_map_mod123.xml
  l10n_es_aeat_mod123/i18n/bg.po
  l10n_es_aeat_mod123/i18n/ca.po
  l10n_es_aeat_mod123/i18n/cs.po
  l10n_es_aeat_mod123/i18n/de.po
  l10n_es_aeat_mod123/i18n/es.po
  l10n_es_aeat_mod123/i18n/es_CO.po
  l10n_es_aeat_mod123/i18n/es_CR.po
  l10n_es_aeat_mod123/i18n/es_ES.po
  l10n_es_aeat_mod123/i18n/eu.po
  l10n_es_aeat_mod123/i18n/fr.po
  l10n_es_aeat_mod123/i18n/gl.po
  l10n_es_aeat_mod123/i18n/hr.po
  l10n_es_aeat_mod123/i18n/l10n_es_aeat_mod123.pot
  l10n_es_aeat_mod123/i18n/nl.po
  l10n_es_aeat_mod123/i18n/pl.po
  l10n_es_aeat_mod123/i18n/pt.po
  l10n_es_aeat_mod123/i18n/pt_BR.po
  l10n_es_aeat_mod123/i18n/sl.po
  l10n_es_aeat_mod123/i18n/sv.po
  l10n_es_aeat_mod123/i18n/tr.po
  l10n_es_aeat_mod123/i18n/vi.po
  l10n_es_aeat_mod123/models/__init__.py
  l10n_es_aeat_mod123/models/mod123.py
  l10n_es_aeat_mod123/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod123/readme/DESCRIPTION.rst
  l10n_es_aeat_mod123/readme/USAGE.rst
  l10n_es_aeat_mod123/security/ir.model.access.csv
  l10n_es_aeat_mod123/security/mod_123_security.xml
  l10n_es_aeat_mod123/static/description/icon.png
  l10n_es_aeat_mod123/static/description/icon_source.svg
  l10n_es_aeat_mod123/static/description/index.html
  l10n_es_aeat_mod123/tests/__init__.py
  l10n_es_aeat_mod123/tests/test_l10n_es_aeat_mod123.py
  l10n_es_aeat_mod123/views/mod123_view.xml
  setup/l10n_es_aeat_mod123/odoo/addons/l10n_es_aeat_mod123
  setup/l10n_es_aeat_mod123/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2822 [14.0][FIX] l10n_es_facturae: Field type does not longer exist
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#2686 [14.0][FIX] l10n_es_facturae_face: "Sending method" field is not displayed on partner's main view (only in the child view)
  l10n_es_facturae_face/readme/CONTRIBUTORS.rst
  l10n_es_facturae_face/views/res_partner.xml
Labels: bot is merging ⏳

#2824 [13.0][FIX] payment_redsys: feedback error string format
  payment_redsys/models/redsys.py
Labels: approved, bot is merging ⏳

#2825 [14.0][FIX] payment_redsys: feedback error string format
  payment_redsys/models/redsys.py
Labels: bot is merging ⏳

#2830 [14.0][FIX] l10n_es_aeat: xmlids
  l10n_es_aeat/wizard/compare_boe_file.py
Labels: bot is merging ⏳

#2699 [16.0][MIG] l10n_es_aeat_mod349: Migration to 16.0
  l10n_es_aeat_mod349/README.rst
  l10n_es_aeat_mod349/__init__.py
  l10n_es_aeat_mod349/__manifest__.py
  l10n_es_aeat_mod349/data/aeat_349_map_data.xml
  l10n_es_aeat_mod349/data/aeat_export_mod349_data.xml
  l10n_es_aeat_mod349/data/aeat_export_mod349_partner_data.xml
  l10n_es_aeat_mod349/data/aeat_export_mod349_partner_refund_data.xml
  l10n_es_aeat_mod349/docs/BOE-A-2010-5098.pdf
  l10n_es_aeat_mod349/docs/NREG-349-2016.docx
  l10n_es_aeat_mod349/i18n/ca.po
  l10n_es_aeat_mod349/i18n/es.po
  l10n_es_aeat_mod349/i18n/l10n_es_aeat_mod349.pot
  l10n_es_aeat_mod349/models/__init__.py
  l10n_es_aeat_mod349/models/account_move.py
  l10n_es_aeat_mod349/models/account_tax.py
  l10n_es_aeat_mod349/models/account_tax_template.py
  l10n_es_aeat_mod349/models/aeat_349_map_line.py
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod349/readme/DESCRIPTION.rst
  l10n_es_aeat_mod349/readme/ROADMAP.rst
  l10n_es_aeat_mod349/readme/USAGE.rst
  l10n_es_aeat_mod349/report/aeat_mod349.xml
  l10n_es_aeat_mod349/report/common_templates.xml
  l10n_es_aeat_mod349/report/report_views.xml
  l10n_es_aeat_mod349/security/ir.model.access.csv
  l10n_es_aeat_mod349/security/mod_349_security.xml
  l10n_es_aeat_mod349/static/description/icon.png
  l10n_es_aeat_mod349/static/description/icon_source.svg
  l10n_es_aeat_mod349/static/description/index.html
  l10n_es_aeat_mod349/tests/__init__.py
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
  l10n_es_aeat_mod349/views/account_move_view.xml
  l10n_es_aeat_mod349/views/account_tax_view.xml
  l10n_es_aeat_mod349/views/aeat_349_map_view.xml
  l10n_es_aeat_mod349/views/mod349_view.xml
  setup/l10n_es_aeat_mod349/odoo/addons/l10n_es_aeat_mod349
  setup/l10n_es_aeat_mod349/setup.py
Labels: approved, bot is merging ⏳

#2833 [14.0][IMP] l10n_es_facturae: Add disable_edi_auto configuration
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_listener.py
Labels: bot is merging ⏳

#2834 [14.0][FIX] l10n_es_vat_book: Don't mix company / partner terminology
  l10n_es_vat_book/i18n/ca.po
  l10n_es_vat_book/i18n/es.po
  l10n_es_vat_book/i18n/l10n_es_vat_book.pot
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/report/common_templates.xml
Labels: bot is merging ⏳

#2836 [14.0][IMP] l10n_es_aeat_sii_oca: Includes new food taxes reduction
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: bot is merging ⏳

#2838 [FIX] l10n_es_facturae_face: Fix changes applied on EDI
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_face_listener.py
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_listener.py
  l10n_es_facturae_face/data/edi.xml
  l10n_es_facturae_face/data/face_data.xml
  l10n_es_facturae_face/models/account_move.py
  l10n_es_facturae_face/tests/test_facturae_face.py
  l10n_es_facturae_face/wizards/edi_l10n_es_facturae_face_cancel.py
Labels: bot is merging ⏳

#2839 [15.0][FIX] l10n_es_vat_book: Don't mix company / partner terminology
  l10n_es_vat_book/i18n/ca.po
  l10n_es_vat_book/i18n/es.po
  l10n_es_vat_book/i18n/l10n_es_vat_book.pot
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/report/common_templates.xml
Labels: bot is merging ⏳

#2828 [15.0][IMP] l10n_es_facturae: mensaje de error más legible para el us…
  l10n_es_facturae/reports/report_facturae.py
Labels: approved, bot is merging ⏳

#2837 [15.0][FIX] l10n_es_aeat_sii_oca: Proper places for some food taxes reduction
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: bot is merging ⏳

#2168 [14.0][ADD] modulo REAV
  l10n_es_reav/README.rst
  l10n_es_reav/__init__.py
  l10n_es_reav/__manifest__.py
  l10n_es_reav/data/fiscal_position_taxes_reav.xml
  l10n_es_reav/data/fiscal_positions_reav.xml
  l10n_es_reav/data/tax_group_data.xml
  l10n_es_reav/data/taxes_reav.xml
  l10n_es_reav/i18n/es.po
  l10n_es_reav/i18n/l10n_es_reav.pot
  l10n_es_reav/readme/CONFIGURE.rst
  l10n_es_reav/readme/CONTRIBUTORS.rst
  l10n_es_reav/readme/DESCRIPTION.rst
  l10n_es_reav/readme/USAGE.rst
  l10n_es_reav/static/description/icon.png
  l10n_es_reav/static/description/index.html
  setup/l10n_es_reav/odoo/addons/l10n_es_reav
  setup/l10n_es_reav/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#2604 [15.0][ADD] l10n_es_ticketbai_oss
  l10n_es_ticketbai_oss/README.rst
  l10n_es_ticketbai_oss/__init__.py
  l10n_es_ticketbai_oss/__manifest__.py
  l10n_es_ticketbai_oss/data/vat_regime_key_data.xml
  l10n_es_ticketbai_oss/i18n/es.po
  l10n_es_ticketbai_oss/i18n/l10n_es_ticketbai_oss.pot
  l10n_es_ticketbai_oss/models/__init__.py
  l10n_es_ticketbai_oss/models/ticketbai_invoice_tax.py
  l10n_es_ticketbai_oss/readme/CONFIGURE.rst
  l10n_es_ticketbai_oss/readme/CONTRIBUTORS.rst
  l10n_es_ticketbai_oss/readme/DESCRIPTION.rst
  l10n_es_ticketbai_oss/readme/INSTALL.rst
  l10n_es_ticketbai_oss/static/description/icon.png
  l10n_es_ticketbai_oss/static/description/index.html
  setup/l10n_es_ticketbai_oss/odoo/addons/l10n_es_ticketbai_oss
  setup/l10n_es_ticketbai_oss/setup.py
Labels: approved, bot is merging ⏳

#2844 [15.0][FIX] l10n_es_aeat_sii_oca: Missing retention in species taxes
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: bot is merging ⏳

#2848 [15.0][FIX] l10n_es_aeat_partner_check: permitir a todos escribir en res.partner
  l10n_es_aeat_partner_check/models/res_partner.py
Labels: bot is merging ⏳

#2850 [16.0][FIX] l10n_es_aeat_partner_check: permitir a todos escribir en res.partner
  l10n_es_aeat_partner_check/models/res_partner.py
Labels: bot is merging ⏳

#2851 [14.0][FIX] l10n_es_aeat_partner_check: permitir a todos escribir en res.pa…
  l10n_es_aeat_partner_check/models/res_partner.py
Labels: bot is merging ⏳

#2840 [13.0][IMP] l10n_es_intrastat_report: 2023 NC codes
  l10n_es_intrastat_report/README.rst
  l10n_es_intrastat_report/data/Estruc_NC2022.xlsx
  l10n_es_intrastat_report/data/Estruc_NC2023.xlsx
  l10n_es_intrastat_report/readme/INSTALL.rst
  l10n_es_intrastat_report/static/description/index.html
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.py
Labels: bot is merging ⏳

#2853 [15.0][IMP] l10n_es_aeat_mod303: New BOE format for 2023
  l10n_es_aeat/models/l10n_es_aeat_map_tax.py
  l10n_es_aeat/tests/__init__.py
  l10n_es_aeat/tests/test_l10n_es_aeat_map_tax.py
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/docs/DR303e21v100.xlsx
  l10n_es_aeat_mod303/docs/DR303e21v200.xlsx
  l10n_es_aeat_mod303/docs/DR303e23.xlsx
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: bot is merging ⏳

#2852 [14.0][IMP] l10n_es_aeat_mod303: New BOE format for 2023
  l10n_es_aeat/models/l10n_es_aeat_map_tax.py
  l10n_es_aeat/tests/__init__.py
  l10n_es_aeat/tests/test_l10n_es_aeat_map_tax.py
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/docs/DR303e21v100.xlsx
  l10n_es_aeat_mod303/docs/DR303e21v200.xlsx
  l10n_es_aeat_mod303/docs/DR303e23.xlsx
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: bot is merging ⏳

#2854 [16.0][IMP] l10n_es_aeat_mod303: New BOE format for 2023
  l10n_es_aeat/models/l10n_es_aeat_map_tax.py
  l10n_es_aeat/tests/__init__.py
  l10n_es_aeat/tests/test_l10n_es_aeat_map_tax.py
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/docs/DR303e21v100.xlsx
  l10n_es_aeat_mod303/docs/DR303e21v200.xlsx
  l10n_es_aeat_mod303/docs/DR303e23.xlsx
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: bot is merging ⏳

#2847 [13.0][IMP] l10n_es_aeat_mod303: New BOE format for 2023
  l10n_es_aeat/models/l10n_es_aeat_map_tax.py
  l10n_es_aeat/tests/__init__.py
  l10n_es_aeat/tests/test_l10n_es_aeat_map_tax.py
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/docs/DR303e21v100.xlsx
  l10n_es_aeat_mod303/docs/DR303e21v200.xlsx
  l10n_es_aeat_mod303/docs/DR303e23.xlsx
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: bot is merging ⏳

#2849 [13.0][IMP] l10n_es_aeat_mod349: Include food taxes + missing intra-community ones
  l10n_es_aeat_mod349/__manifest__.py
  l10n_es_aeat_mod349/data/aeat_349_map_data.xml
Labels: bot is merging ⏳

#2823 [15.0][IMP] l10n_es_facturae: improvements readme
  l10n_es_facturae/README.rst
  l10n_es_facturae/readme/CONFIGURE.rst
  l10n_es_facturae/readme/USAGE.rst
Labels: bot is merging ⏳

#2856 [13.0][FIX] l10n_es_intrastat_report: Search archived records when importing codes.
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.py
Labels: bot is merging ⏳

#2842 [15.0][IMP] l10n_es_aeat_sii_oca: move sii view of account.fiscal.position
  l10n_es_aeat_sii_oca/views/account_fiscal_position_view.xml
Labels: approved, bot is merging ⏳

#2859 [16.0][IMP] l10n_es_aeat_mod349: Include food taxes + missing intra-community ones
  l10n_es_aeat_mod349/__manifest__.py
  l10n_es_aeat_mod349/data/aeat_349_map_data.xml
Labels: bot is merging ⏳

#2857 [14.0][IMP] l10n_es_aeat_mod349: Include food taxes + missing intra-community ones
  l10n_es_aeat_mod349/__manifest__.py
  l10n_es_aeat_mod349/data/aeat_349_map_data.xml
Labels: bot is merging ⏳

#2858 [15.0][IMP] l10n_es_aeat_mod349: Include food taxes + missing intra-community ones
  l10n_es_aeat_mod349/__manifest__.py
  l10n_es_aeat_mod349/data/aeat_349_map_data.xml
Labels: bot is merging ⏳

#2545 [11.0][FIX] l10n_es_intrastat_report: missing country error replaced by note message
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
Labels: approved, bot is merging ⏳, stale

#2860 [14.0][IMP] l10n_es_intrastat_report: 2023 NC codes
  l10n_es_intrastat_report/README.rst
  l10n_es_intrastat_report/data/Estruc_NC2022.xlsx
  l10n_es_intrastat_report/data/Estruc_NC2023.xlsx
  l10n_es_intrastat_report/readme/INSTALL.rst
  l10n_es_intrastat_report/static/description/index.html
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.py
Labels: bot is merging ⏳

#2863 [FIX] l10n_es_aeat_mod347: remove taxes not required
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
Labels: bot is merging ⏳

#2865 [15.0][IMP] l10n_es_intrastat_report: 2023 NC codes
  l10n_es_intrastat_report/README.rst
  l10n_es_intrastat_report/data/Estruc_NC2022.xlsx
  l10n_es_intrastat_report/data/Estruc_NC2023.xlsx
  l10n_es_intrastat_report/readme/INSTALL.rst
  l10n_es_intrastat_report/static/description/index.html
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.py
Labels: bot is merging ⏳

#2870 [12.0][FIX] l10n_es_aeat_mod347: add missing taxes
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
Labels: approved, bot is merging ⏳

#2671 [13.0][IMP] l10n_es_intrastat_report: Improve tests to test an invoice with delivery address in a country other than the country of contact.
  l10n_es_intrastat_report/tests/test_l10n_es_intrastat_report.py
Labels: approved, bot is merging ⏳

#2717 [13.0][IMP] l10n_es_aeat_sii_oca: Includes new food taxes reduction
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: approved, bot is merging ⏳

#2881 [13.0][IMP] l10n_es_vat_book: Include new food taxes reduction
  l10n_es_vat_book/__manifest__.py
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#2882 [14.0][FIX] l10n_es_payment_order_sabadell: Missing string cast
  l10n_es_payment_order_confirming_sabadell/models/confirming_sabadell.py
Labels: approved, bot is merging ⏳

#2885 [14.0][IMP] l10n_es_vat_book: Include new food taxes reduction
  l10n_es_vat_book/__manifest__.py
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#2887 [16.0][IMP] l10n_es_vat_book: Include new food taxes reduction
  l10n_es_vat_book/__manifest__.py
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#2672 [14.0][IMP] l10n_es_intrastat_report: Improve tests to test an invoice with delivery address in a country other than the country of contact.
  l10n_es_intrastat_report/tests/test_l10n_es_intrastat_report.py
Labels: approved, ready to merge, bot is merging ⏳

#2864 [15.0] [FIX] l10n_es_aeat_sii_oca: fix error sii header
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#2890 [15.0][IMP] l10n_es_intrastat_report: Improve tests to test an invoice with delivery address in a country other than the country of contact
  l10n_es_intrastat_report/tests/test_l10n_es_intrastat_report.py
Labels: bot is merging ⏳

#2891 [16.0][FIX] l10n_es_aeat_sii_oca: fix error sii header
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#2897 [13.0][FIX] l10n_es_aeat_mod303: Don't put bank details if not foreign
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/models/mod303.py
Labels: approved, bot is merging ⏳

#2832 [16.0][MIG] l10n_es_ticketbai: Migration to 16.0
  l10n_es_ticketbai/README.rst
  l10n_es_ticketbai/__init__.py
  l10n_es_ticketbai/__manifest__.py
  l10n_es_ticketbai/data/account_fiscal_position_template.xml
  l10n_es_ticketbai/data/tax_map_data.xml
  l10n_es_ticketbai/data/vat_exemption_key_data.xml
  l10n_es_ticketbai/data/vat_regime_key_data.xml
  l10n_es_ticketbai/hooks.py
  l10n_es_ticketbai/i18n/ca.po
  l10n_es_ticketbai/i18n/es.po
  l10n_es_ticketbai/i18n/eu.po
  l10n_es_ticketbai/i18n/l10n_es_ticketbai.pot
  l10n_es_ticketbai/models/__init__.py
  l10n_es_ticketbai/models/account_fiscal_position.py
  l10n_es_ticketbai/models/account_journal.py
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai/models/account_resequence.py
  l10n_es_ticketbai/models/account_tax.py
  l10n_es_ticketbai/models/aeat_certificate.py
  l10n_es_ticketbai/models/chart_template.py
  l10n_es_ticketbai/models/res_company.py
  l10n_es_ticketbai/models/ticketbai_invoice.py
  l10n_es_ticketbai/models/ticketbai_tax_map.py
  l10n_es_ticketbai/models/ticketbai_vat_exemption_key.py
  l10n_es_ticketbai/models/ticketbai_vat_regime_key.py
  l10n_es_ticketbai/readme/CONFIGURE.rst
  l10n_es_ticketbai/readme/CONTRIBUTORS.rst
  l10n_es_ticketbai/readme/DESCRIPTION.rst
  l10n_es_ticketbai/readme/USAGE.rst
  l10n_es_ticketbai/security/ir.model.access.csv
  l10n_es_ticketbai/static/description/icon.png
  l10n_es_ticketbai/static/description/index.html
  l10n_es_ticketbai/tests/__init__.py
  l10n_es_ticketbai/tests/certs/ciudadano_act.p12
  l10n_es_ticketbai/tests/certs/ciudadano_act_p12_password.txt
  l10n_es_ticketbai/tests/certs/private_up_8mgwq.pem
  l10n_es_ticketbai/tests/certs/public_362gar7l.crt
  l10n_es_ticketbai/tests/common.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_cancellation.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
  l10n_es_ticketbai/views/account_fiscal_position_template_views.xml
  l10n_es_ticketbai/views/account_fiscal_position_views.xml
  l10n_es_ticketbai/views/account_journal_views.xml
  l10n_es_ticketbai/views/account_move_views.xml
  l10n_es_ticketbai/views/l10n_es_ticketbai_views.xml
  l10n_es_ticketbai/views/report_invoice.xml
  l10n_es_ticketbai/views/res_company_views.xml
  l10n_es_ticketbai/views/res_partner_views.xml
  l10n_es_ticketbai/views/tax_map_views.xml
  l10n_es_ticketbai/views/ticketbai_invoice_views.xml
  l10n_es_ticketbai/views/vat_exemption_key_views.xml
  l10n_es_ticketbai/views/vat_regime_key_views.xml
  l10n_es_ticketbai/wizard/__init__.py
  l10n_es_ticketbai/wizard/account_move_reversal.py
  l10n_es_ticketbai/wizard/aeat_certificate_password.py
  l10n_es_ticketbai/wizard/ticketbai_info.py
  l10n_es_ticketbai/wizard/ticketbai_info_views.xml
  setup/l10n_es_ticketbai/odoo/addons/l10n_es_ticketbai
  setup/l10n_es_ticketbai/setup.py
Labels: approved, ready to merge, bot is merging ⏳
