Repository OCA/l10n-spain, pull requests merged in 2023-11, with the labels that each got.

#3283 [16.0][MIG] l10n_es_facturae_face
  l10n_es_facturae/views/report_facturae.xml
  l10n_es_facturae_face/README.rst
  l10n_es_facturae_face/__init__.py
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/components/__init__.py
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_face_listener.py
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_listener.py
  l10n_es_facturae_face/components/edi_input_process_l10n_es_facturae_l10n_es_facturae_face_update.py
  l10n_es_facturae_face/components/edi_send_l10n_es_facturae_face.py
  l10n_es_facturae_face/components/edi_send_l10n_es_facturae_face_cancel.py
  l10n_es_facturae_face/components/edi_webservice_receive_face_l10n_es_facturae_face_update.py
  l10n_es_facturae_face/components/webservice_face.py
  l10n_es_facturae_face/data/cron_data.xml
  l10n_es_facturae_face/data/edi.xml
  l10n_es_facturae_face/data/face_data.xml
  l10n_es_facturae_face/i18n/ca.po
  l10n_es_facturae_face/i18n/es.po
  l10n_es_facturae_face/i18n/l10n_es_facturae_face.pot
  l10n_es_facturae_face/migrations/16.0.1.0.0/pre-migration.py
  l10n_es_facturae_face/models/__init__.py
  l10n_es_facturae_face/models/account_move.py
  l10n_es_facturae_face/models/edi_exchange_record.py
  l10n_es_facturae_face/models/res_company.py
  l10n_es_facturae_face/models/res_partner.py
  l10n_es_facturae_face/models/wsse_signature.py
  l10n_es_facturae_face/readme/CONFIGURE.rst
  l10n_es_facturae_face/readme/CONTRIBUTORS.rst
  l10n_es_facturae_face/readme/DESCRIPTION.rst
  l10n_es_facturae_face/readme/USAGE.rst
  l10n_es_facturae_face/security/ir.model.access.csv
  l10n_es_facturae_face/static/description/icon.png
  l10n_es_facturae_face/static/description/index.html
  l10n_es_facturae_face/tests/__init__.py
  l10n_es_facturae_face/tests/test_facturae_face.py
  l10n_es_facturae_face/views/account_move.xml
  l10n_es_facturae_face/views/edi_exchange_record.xml
  l10n_es_facturae_face/views/res_company_view.xml
  l10n_es_facturae_face/views/res_partner.xml
  l10n_es_facturae_face/wizards/__init__.py
  l10n_es_facturae_face/wizards/edi_l10n_es_facturae_face_cancel.py
  l10n_es_facturae_face/wizards/edi_l10n_es_facturae_face_cancel.xml
  setup/l10n_es_facturae_face/odoo/addons/l10n_es_facturae_face
  setup/l10n_es_facturae_face/setup.py
Labels: approved, bot is merging ⏳

#3295 [14.0][FIX] l10n_es_facturae: Add missing templates map
  l10n_es_facturae/data/account_tax_template.xml
Labels: bot is merging ⏳

#3297 [16.0][FIX] l10n_es_facturae: Add missing templates map
  l10n_es_facturae/data/account_tax_template.xml
Labels: bot is merging ⏳

#3296 [15.0][FIX] l10n_es_facturae: Add missing templates map
  l10n_es_facturae/data/account_tax_template.xml
Labels: bot is merging ⏳

#3123 [16.0][IMP] l10n_es_aeat: Add tax agency
  l10n_es_aeat/models/l10n_es_aeat_report.py
Labels: approved, ready to merge, bot is merging ⏳

#3251 [MIG] l10n_es_aeat_sii_match: Migration to 16.0
  l10n_es_aeat_sii_match/README.rst
  l10n_es_aeat_sii_match/__init__.py
  l10n_es_aeat_sii_match/__manifest__.py
  l10n_es_aeat_sii_match/data/queue_job.xml
  l10n_es_aeat_sii_match/i18n/es.po
  l10n_es_aeat_sii_match/i18n/l10n_es_aeat_sii_match.pot
  l10n_es_aeat_sii_match/models/__init__.py
  l10n_es_aeat_sii_match/models/account_move.py
  l10n_es_aeat_sii_match/models/aeat_sii_match_difference.py
  l10n_es_aeat_sii_match/models/aeat_sii_match_report.py
  l10n_es_aeat_sii_match/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_match/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_match/readme/MAINTAINERS.rst
  l10n_es_aeat_sii_match/security/aeat_sii.xml
  l10n_es_aeat_sii_match/security/ir.model.access.csv
  l10n_es_aeat_sii_match/static/description/icon.png
  l10n_es_aeat_sii_match/static/description/index.html
  l10n_es_aeat_sii_match/tests/__init__.py
  l10n_es_aeat_sii_match/tests/test_l10n_es_aeat_sii_match.py
  l10n_es_aeat_sii_match/views/account_move_views.xml
  l10n_es_aeat_sii_match/views/aeat_sii_match_report.xml
  requirements.txt
  setup/l10n_es_aeat_sii_match/odoo/addons/l10n_es_aeat_sii_match
  setup/l10n_es_aeat_sii_match/setup.py
Labels: approved, bot is merging ⏳

#3303 [16.0][FIX] l10n_es_partner: Wizard UI colspan
  l10n_es_partner/wizard/l10n_es_partner_wizard.xml
Labels: bot is merging ⏳

#3301 [16.0][FIX] l10n_es_intrastat_report: Move methods to the correct class + Improve test
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
  l10n_es_intrastat_report/tests/test_l10n_es_intrastat_report.py
Labels: bot is merging ⏳

#3304 [16.0][IMP] l10n_es_aeat_sii_oca: Add neutralize.sql file for test enabling
  l10n_es_aeat_sii_oca/data/neutralize.sql
Labels: bot is merging ⏳

#3299 [16.0][IMP] l10n_es_vat_book: Add tax agency
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
  l10n_es_vat_book/models/aeat_vat_book_map_line.py
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/tests/test_l10n_es_aeat_vat_book.py
  l10n_es_vat_book/views/aeat_vat_book_map_view.xml
  l10n_es_vat_book/views/l10n_es_vat_book.xml
Labels: bot is merging ⏳

#3300 [16.0][FIX] l10n_es_intrastat_report: Remove transactions, the data is already defined in intrastat_product.
  l10n_es_intrastat_report/README.rst
  l10n_es_intrastat_report/__manifest__.py
  l10n_es_intrastat_report/data/intrastat_transaction.xml
  l10n_es_intrastat_report/migrations/16.0.1.3.0/post-migration.py
  l10n_es_intrastat_report/static/description/index.html
Labels: bot is merging ⏳

#3311 [16.0][IMP] l10n_es_aeat: Add country ISO code mapper function
  l10n_es_aeat/models/res_partner.py
  l10n_es_aeat/tests/test_l10n_es_aeat.py
Labels: bot is merging ⏳

#3312 [16.0][IMP] l10n_es_facturae: rename field parent_facturae
  l10n_es_facturae/models/res_partner.py
Labels: approved, bot is merging ⏳

#3313 [14.0][FIX] l10n_es_mis_report: Corrección cuentas 7460% y 7461% en PyG abreviado.
  l10n_es_mis_report/data/mis_report_pyg_abreviated.xml
Labels: approved, bot is merging ⏳

#3316 [15.0][FIX] l10n_es_mis_report: Corrección cuentas 7460% y 7461% en PyG abreviado.
  l10n_es_mis_report/data/mis_report_pyg_abreviated.xml
Labels: bot is merging ⏳

#3317 [FIX] l10n_es_mis_report: Corrección cuentas 7460% y 7461% en PyG abreviado.
  l10n_es_mis_report/data/mis_report_pyg_abreviated.xml
Labels: bot is merging ⏳

#3222 [15.0][FIX] l10n_es_facturae_face: Set rules in the new way
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/data/edi.xml
  l10n_es_facturae_face/migrations/15.0.2.3.0/pre-migration.py
Labels: bot is merging ⏳

#3319 [17.0][MIG] l10n_es_partner_mercantil : Migration to 17.0
  l10n_es_partner_mercantil/README.rst
  l10n_es_partner_mercantil/__init__.py
  l10n_es_partner_mercantil/__manifest__.py
  l10n_es_partner_mercantil/i18n/bg.po
  l10n_es_partner_mercantil/i18n/ca.po
  l10n_es_partner_mercantil/i18n/es.po
  l10n_es_partner_mercantil/i18n/eu.po
  l10n_es_partner_mercantil/i18n/fr.po
  l10n_es_partner_mercantil/i18n/gl.po
  l10n_es_partner_mercantil/i18n/hr.po
  l10n_es_partner_mercantil/i18n/l10n_es_partner_mercantil.pot
  l10n_es_partner_mercantil/i18n/nl.po
  l10n_es_partner_mercantil/i18n/pt.po
  l10n_es_partner_mercantil/i18n/pt_BR.po
  l10n_es_partner_mercantil/i18n/sl.po
  l10n_es_partner_mercantil/models/__init__.py
  l10n_es_partner_mercantil/models/partner_es.py
  l10n_es_partner_mercantil/pyproject.toml
  l10n_es_partner_mercantil/readme/CONTRIBUTORS.md
  l10n_es_partner_mercantil/readme/DESCRIPTION.md
  l10n_es_partner_mercantil/readme/USAGE.md
  l10n_es_partner_mercantil/static/description/icon.png
  l10n_es_partner_mercantil/static/description/icon.svg
  l10n_es_partner_mercantil/static/description/index.html
  l10n_es_partner_mercantil/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#3326 [15.0][FIX] l10n_es_facturae: Might be possible to generate facturae report on non facturae customers
  l10n_es_facturae/models/account_move.py
Labels: approved, bot is merging ⏳

#3324 [16.0][FIX] l10n_es_intrastat_report: Do not display missing VAT number err…
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
  l10n_es_intrastat_report/tests/test_l10n_es_intrastat_report.py
Labels: approved, bot is merging ⏳

#3329 [15.0][FIX] l10n_es_payment_order_confirming_aef: Forward port #3323 and #3328
  l10n_es_payment_order_confirming_aef/models/confirming_aef.py
Labels: bot is merging ⏳

#3330 [16.0][FIX] l10n_es_payment_order_confirming_aef: Forward port #3323 and #3328
  l10n_es_payment_order_confirming_aef/models/confirming_aef.py
Labels: bot is merging ⏳
