Repository OCA/l10n-spain, pull requests merged in 2023-06, with the labels that each got.

#3049 [16.0][FIX] l10n_es_aeat: replace deprecated method.
  l10n_es_aeat/models/l10n_es_aeat_report_tax_mapping.py
Labels: bot is merging ⏳

#2984 [16.0][FIX] l10n_es_aeat_sii_oca: cliente intracomunitario, entrega extracomunitaria
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: approved, ready to merge, bot is merging ⏳

#2983 [15.0][FIX] l10n_es_aeat_sii_oca: cliente intracomunitario, entrega extracomunitaria
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: approved, ready to merge, bot is merging ⏳

#3062 [16.0][FIX] l10n_es_ticketbai_api_batuz: Fix model field definition on lroe…
  l10n_es_ticketbai_api_batuz/models/lroe_operation.py
Labels: bot is merging ⏳

#3053 [14.0][FIX] l10n_es_pos: Impresión de fecha en recibo
  l10n_es_pos/static/src/js/models.js
Labels: approved, bot is merging ⏳

#3064 [16.0][IMP] l10n_es_aeat_mod347: extra EU taxes are added.
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
Labels: approved, bot is merging ⏳

#3063 [15.0][IMP] l10n_es_aeat_mod347: extra EU taxes are added.
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
Labels: approved, bot is merging ⏳

#2615 [16.0][MIG] l10n_es_pos: Migration to 16.0
  l10n_es_pos/README.rst
  l10n_es_pos/__init__.py
  l10n_es_pos/__manifest__.py
  l10n_es_pos/hooks.py
  l10n_es_pos/i18n/ca.po
  l10n_es_pos/i18n/ca_ES.po
  l10n_es_pos/i18n/es.po
  l10n_es_pos/i18n/l10n_es_pos.pot
  l10n_es_pos/models/__init__.py
  l10n_es_pos/models/ir_sequence.py
  l10n_es_pos/models/pos_config.py
  l10n_es_pos/models/pos_order.py
  l10n_es_pos/models/pos_session.py
  l10n_es_pos/readme/CONFIGURE.rst
  l10n_es_pos/readme/CONTRIBUTORS.rst
  l10n_es_pos/readme/DESCRIPTION.rst
  l10n_es_pos/readme/INSTALL.rst
  l10n_es_pos/readme/ROADMAP.rst
  l10n_es_pos/static/description/icon.png
  l10n_es_pos/static/description/index.html
  l10n_es_pos/static/src/js/PaymentScreen.js
  l10n_es_pos/static/src/js/Screens/TicketScreen/TicketScreen.js
  l10n_es_pos/static/src/js/models.js
  l10n_es_pos/static/src/xml/Screens/OrderManagementScreen/TicketScreen.xml
  l10n_es_pos/static/src/xml/pos.xml
  l10n_es_pos/views/pos_views.xml
  l10n_es_pos/views/res_config_settings_views.xml
  l10n_es_pos/wizard/__init__.py
  l10n_es_pos/wizard/res_config_settings.py
  setup/l10n_es_pos/odoo/addons/l10n_es_pos
  setup/l10n_es_pos/setup.py
Labels: approved, bot is merging ⏳

#3031 [16.0][MIG] l10n_es_ticketbai_batuz: Migration to 16.0
  l10n_es_ticketbai_batuz/README.rst
  l10n_es_ticketbai_batuz/__init__.py
  l10n_es_ticketbai_batuz/__manifest__.py
  l10n_es_ticketbai_batuz/data/account_fiscal_position_template_data.xml
  l10n_es_ticketbai_batuz/data/queue_job_data.xml
  l10n_es_ticketbai_batuz/data/tbai_tax_map_data.xml
  l10n_es_ticketbai_batuz/data/tbai_vat_regime_key_data.xml
  l10n_es_ticketbai_batuz/hooks.py
  l10n_es_ticketbai_batuz/i18n/es.po
  l10n_es_ticketbai_batuz/i18n/eu.po
  l10n_es_ticketbai_batuz/i18n/l10n_es_ticketbai_batuz.pot
  l10n_es_ticketbai_batuz/models/__init__.py
  l10n_es_ticketbai_batuz/models/account_fiscal_position.py
  l10n_es_ticketbai_batuz/models/account_move.py
  l10n_es_ticketbai_batuz/models/chart_template.py
  l10n_es_ticketbai_batuz/models/lroe_operation.py
  l10n_es_ticketbai_batuz/models/res_company.py
  l10n_es_ticketbai_batuz/models/res_partner.py
  l10n_es_ticketbai_batuz/models/ticketbai_invoice.py
  l10n_es_ticketbai_batuz/models/ticketbai_vat_regime_key.py
  l10n_es_ticketbai_batuz/readme/CONTRIBUTORS.rst
  l10n_es_ticketbai_batuz/readme/DESCRIPTION.rst
  l10n_es_ticketbai_batuz/readme/INSTALL.rst
  l10n_es_ticketbai_batuz/readme/USAGE.rst
  l10n_es_ticketbai_batuz/security/ir_rule.xml
  l10n_es_ticketbai_batuz/static/description/icon.png
  l10n_es_ticketbai_batuz/static/description/index.html
  l10n_es_ticketbai_batuz/static/src/description/icon.png
  l10n_es_ticketbai_batuz/static/src/img/binovo_logo.jpg
  l10n_es_ticketbai_batuz/static/src/img/binovo_logo_peque.jpg
  l10n_es_ticketbai_batuz/views/account_fiscal_position_views.xml
  l10n_es_ticketbai_batuz/views/account_move_views.xml
  l10n_es_ticketbai_batuz/views/lroe_operation_views.xml
  l10n_es_ticketbai_batuz/views/res_company_views.xml
  l10n_es_ticketbai_batuz/views/res_partner_views.xml
  l10n_es_ticketbai_batuz/views/tbai_vat_regime_key_views.xml
  l10n_es_ticketbai_batuz/wizard/__init__.py
  l10n_es_ticketbai_batuz/wizard/account_move_reversal.py
  l10n_es_ticketbai_batuz/wizard/account_move_reversal_views.xml
  setup/l10n_es_ticketbai_batuz/odoo/addons/l10n_es_ticketbai_batuz
  setup/l10n_es_ticketbai_batuz/setup.py
Labels: approved, bot is merging ⏳

#3055 [14.0][IMP] delivery_mrw: added new services
  delivery_mrw/models/delivery_carrier.py
  delivery_mrw/readme/CONTRIBUTORS.rst
Labels: approved, ready to merge, bot is merging ⏳

#3072 [14.0][FIX] l10n_es_ticketbai: Save reversed entry on account move correctly
  l10n_es_ticketbai/views/account_move_views.xml
Labels: bot is merging ⏳

#3074 [15.0][FIX] l10n_es_ticketbai: Save reversed entry on account move correctly
  l10n_es_ticketbai/views/account_move_views.xml
Labels: bot is merging ⏳

#3075 [16.0][FIX] l10n_es_ticketbai: Save reversed entry on account move correctly
  l10n_es_ticketbai/views/account_move_views.xml
Labels: bot is merging ⏳

#3066 [15.0][FIX] l10n_es_pos: Impresión de fecha en recibo
  l10n_es_pos/static/src/js/models.js
Labels: approved, bot is merging ⏳

#2974 [15.0][MIG] l10n_es_pos_by_device: Migration to 15.0
  l10n_es_pos_by_device/README.rst
  l10n_es_pos_by_device/__init__.py
  l10n_es_pos_by_device/__manifest__.py
  l10n_es_pos_by_device/i18n/es.po
  l10n_es_pos_by_device/i18n/l10n_es_pos_by_device.pot
  l10n_es_pos_by_device/models/__init__.py
  l10n_es_pos_by_device/models/pos_config.py
  l10n_es_pos_by_device/models/pos_device.py
  l10n_es_pos_by_device/models/pos_order.py
  l10n_es_pos_by_device/models/res_company.py
  l10n_es_pos_by_device/models/res_config_settings.py
  l10n_es_pos_by_device/readme/CONFIGURE.rst
  l10n_es_pos_by_device/readme/CONTRIBUTORS.rst
  l10n_es_pos_by_device/readme/DESCRIPTION.rst
  l10n_es_pos_by_device/readme/USAGE.rst
  l10n_es_pos_by_device/security/device_security.xml
  l10n_es_pos_by_device/security/ir.model.access.csv
  l10n_es_pos_by_device/static/description/icon.png
  l10n_es_pos_by_device/static/description/index.html
  l10n_es_pos_by_device/static/src/js/PaymentScreen.js
  l10n_es_pos_by_device/static/src/js/Screens/Chrome/Chrome.js
  l10n_es_pos_by_device/static/src/js/Screens/Chrome/DeviceName.js
  l10n_es_pos_by_device/static/src/js/Screens/Popups/CashOpeningPopup.js
  l10n_es_pos_by_device/static/src/js/Screens/Popups/ClosePosPopup.js
  l10n_es_pos_by_device/static/src/js/models.js
  l10n_es_pos_by_device/static/src/xml/Screens/Chrome/Chrome.xml
  l10n_es_pos_by_device/static/src/xml/Screens/Chrome/DeviceName.xml
  l10n_es_pos_by_device/views/pos_views.xml
  l10n_es_pos_by_device/views/res_config_views.xml
  setup/l10n_es_pos_by_device/odoo/addons/l10n_es_pos_by_device
  setup/l10n_es_pos_by_device/setup.py
Labels: approved, bot is merging ⏳

#3009 [14.0][ADD] l10n_es_payment_order_confirming_aef
  l10n_es_payment_order_confirming_aef/README.rst
  l10n_es_payment_order_confirming_aef/__init__.py
  l10n_es_payment_order_confirming_aef/__manifest__.py
  l10n_es_payment_order_confirming_aef/data/account_payment_method.xml
  l10n_es_payment_order_confirming_aef/models/__init__.py
  l10n_es_payment_order_confirming_aef/models/account_payment_mode.py
  l10n_es_payment_order_confirming_aef/models/account_payment_order.py
  l10n_es_payment_order_confirming_aef/models/confirming_aef.py
  l10n_es_payment_order_confirming_aef/readme/CONFIGURE.rst
  l10n_es_payment_order_confirming_aef/readme/CONTRIBUTORS.rst
  l10n_es_payment_order_confirming_aef/readme/DESCRIPTION.rst
  l10n_es_payment_order_confirming_aef/readme/USAGE.rst
  l10n_es_payment_order_confirming_aef/static/description/icon.png
  l10n_es_payment_order_confirming_aef/static/description/index.html
  l10n_es_payment_order_confirming_aef/tests/__init__.py
  l10n_es_payment_order_confirming_aef/tests/test_payment_order_confirming_aef.py
  l10n_es_payment_order_confirming_aef/views/account_payment_mode_view.xml
  setup/l10n_es_payment_order_confirming_aef/odoo/addons/l10n_es_payment_order_confirming_aef
  setup/l10n_es_payment_order_confirming_aef/setup.py
Labels: approved, bot is merging ⏳

#3078 [14.0][IMP+FIX] delivery_mrw: use WSDL tracking URL instead of local file + new "Referencia" field added
  delivery_mrw/api/mrw-api-tracking-prod.wsdl
  delivery_mrw/api/mrw_api.xml
  delivery_mrw/models/mrw_request.py
Labels: approved, bot is merging ⏳

#2917 [16.0][ADD] l10n_es_igic: PGC Canarias
  l10n_es_igic/README.rst
  l10n_es_igic/__init__.py
  l10n_es_igic/__manifest__.py
  l10n_es_igic/data/account.account.template-assoc-canary.csv
  l10n_es_igic/data/account.account.template-common-canary.csv
  l10n_es_igic/data/account.account.template-full-canary.csv
  l10n_es_igic/data/account.account.template-pymes-canary.csv
  l10n_es_igic/data/account_chart_template_data.xml
  l10n_es_igic/data/account_fiscal_position_template_canary_data.xml
  l10n_es_igic/data/account_tax_data.xml
  l10n_es_igic/data/account_tax_group_data.xml
  l10n_es_igic/readme/CONTRIBUTORS.rst
  l10n_es_igic/readme/DESCRIPTION.rst
  l10n_es_igic/readme/INSTALL.rst
  l10n_es_igic/static/description/icon.png
  l10n_es_igic/static/description/index.html
  setup/l10n_es_igic/odoo/addons/l10n_es_igic
  setup/l10n_es_igic/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3089 [15.0][FIX] l10n_es_pos: Remove not needed function
  l10n_es_pos/models/pos_order.py
Labels: bot is merging ⏳

#3090 [15.0][FIX] l10n_es_ticketbai_pos: Compatible with restaurant configuration
  l10n_es_ticketbai_pos/models/pos_config.py
  l10n_es_ticketbai_pos/models/pos_order.py
  l10n_es_ticketbai_pos/static/src/js/models.js
  l10n_es_ticketbai_pos/static/src/js/tbai_models.js
Labels: bot is merging ⏳

#3094 [14.0][IMP] l10n_es_aeat_mod123: Se incluye en el mapeo el impuesto 'Retenciones IRPF 24% (Rendimientos del capital)'
  l10n_es_aeat_mod123/data/tax_code_map_mod123.xml
Labels: bot is merging ⏳

#3093 [16.0][MIG] l10n_es_dua_sii: Migration to version 16.0
  l10n_es_dua_sii/README.rst
  l10n_es_dua_sii/__init__.py
  l10n_es_dua_sii/__manifest__.py
  l10n_es_dua_sii/data/tax_code_map_dua_sii_data.xml
  l10n_es_dua_sii/i18n/bg.po
  l10n_es_dua_sii/i18n/ca.po
  l10n_es_dua_sii/i18n/cs.po
  l10n_es_dua_sii/i18n/es.po
  l10n_es_dua_sii/i18n/es_CR.po
  l10n_es_dua_sii/i18n/fr.po
  l10n_es_dua_sii/i18n/gl.po
  l10n_es_dua_sii/i18n/hr.po
  l10n_es_dua_sii/i18n/l10n_es_dua_sii.pot
  l10n_es_dua_sii/i18n/nl.po
  l10n_es_dua_sii/i18n/pl.po
  l10n_es_dua_sii/i18n/pt.po
  l10n_es_dua_sii/i18n/pt_BR.po
  l10n_es_dua_sii/i18n/ru.po
  l10n_es_dua_sii/i18n/sl.po
  l10n_es_dua_sii/i18n/sv.po
  l10n_es_dua_sii/i18n/tr.po
  l10n_es_dua_sii/models/__init__.py
  l10n_es_dua_sii/models/account_move.py
  l10n_es_dua_sii/readme/CONFIGURATION.rst
  l10n_es_dua_sii/readme/CONTRIBUTORS.rst
  l10n_es_dua_sii/readme/DESCRIPTION.rst
  l10n_es_dua_sii/readme/ROADMAP.rst
  l10n_es_dua_sii/readme/USAGE.rst
  l10n_es_dua_sii/static/description/icon.png
  l10n_es_dua_sii/static/description/index.html
  l10n_es_dua_sii/tests/__init__.py
  l10n_es_dua_sii/tests/json/sii_in_invoice_p_iva10_bc_dict.json
  l10n_es_dua_sii/tests/json/sii_in_invoice_p_iva21_ibc_dict.json
  l10n_es_dua_sii/tests/test_dua_sii.py
  setup/l10n_es_dua_sii/odoo/addons/l10n_es_dua_sii
  setup/l10n_es_dua_sii/setup.py
Labels: approved, bot is merging ⏳

#3103 [16][FIX] l10n_es_aeat_sii_oca: broken view in Aeat SII Map Form
  l10n_es_aeat_sii_oca/views/aeat_sii_map_view.xml
Labels: approved, bot is merging ⏳

#2826 [16.0][MIG] l10n_es_account_banking_sepa_fsdd: Migration to 16.0
  l10n_es_account_banking_sepa_fsdd/README.rst
  l10n_es_account_banking_sepa_fsdd/__init__.py
  l10n_es_account_banking_sepa_fsdd/__manifest__.py
  l10n_es_account_banking_sepa_fsdd/i18n/ca.po
  l10n_es_account_banking_sepa_fsdd/i18n/es.po
  l10n_es_account_banking_sepa_fsdd/i18n/es_ES.po
  l10n_es_account_banking_sepa_fsdd/i18n/fr.po
  l10n_es_account_banking_sepa_fsdd/i18n/l10n_es_account_banking_sepa_fsdd.pot
  l10n_es_account_banking_sepa_fsdd/i18n/nl.po
  l10n_es_account_banking_sepa_fsdd/i18n/pt_BR.po
  l10n_es_account_banking_sepa_fsdd/i18n/sl.po
  l10n_es_account_banking_sepa_fsdd/models/__init__.py
  l10n_es_account_banking_sepa_fsdd/models/account_payment_mode.py
  l10n_es_account_banking_sepa_fsdd/models/account_payment_order.py
  l10n_es_account_banking_sepa_fsdd/readme/CONFIGURE.rst
  l10n_es_account_banking_sepa_fsdd/readme/CONTRIBUTORS.rst
  l10n_es_account_banking_sepa_fsdd/readme/DESCRIPTION.rst
  l10n_es_account_banking_sepa_fsdd/readme/INSTALL.rst
  l10n_es_account_banking_sepa_fsdd/static/description/icon.png
  l10n_es_account_banking_sepa_fsdd/static/description/index.html
  l10n_es_account_banking_sepa_fsdd/tests/__init__.py
  l10n_es_account_banking_sepa_fsdd/tests/test_l10n_es_account_banking_sepa_fsdd.py
  l10n_es_account_banking_sepa_fsdd/views/payment_mode_view.xml
  setup/l10n_es_account_banking_sepa_fsdd/odoo/addons/l10n_es_account_banking_sepa_fsdd
  setup/l10n_es_account_banking_sepa_fsdd/setup.py
Labels: bot is merging ⏳, stale

#3102 [14.0][FIX] l10n_es_ticketbai_pos - corregir cálculo de precio unitario com impuestos incluidos
  l10n_es_ticketbai_pos/static/src/js/models.js
Labels: approved, bot is merging ⏳

#3107 [16.0][FIX] l10n_es_ticketbai: Convert line data from other currencies
  l10n_es_ticketbai/models/account_move.py
Labels: bot is merging ⏳

#3030 [IMP] l10n_es_aeat_sii_oca: Change related field to compute
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#3110 [15.0][IMP] l10n_es_aeat_sii_oca: Change related field to compute
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#3099 [15.0][IMP] l10n_es_aeat_mod123: Se incluye en el mapeo el impuesto 'Retenciones IRPF 24% (Rendimientos del capital)'
  l10n_es_aeat_mod123/data/tax_code_map_mod123.xml
Labels: bot is merging ⏳

#3100 [16.0][IMP] l10n_es_aeat_mod123: Se incluye en el mapeo el impuesto 'Retenciones IRPF 24% (Rendimientos del capital)'
  l10n_es_aeat_mod123/data/tax_code_map_mod123.xml
Labels: bot is merging ⏳

#3120 [14.0][FIX] l10n_es_facturae_face: Set some record as noupdate False
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/data/edi.xml
  l10n_es_facturae_face/data/edi_output.xml
  l10n_es_facturae_face/data/face_data.xml
  l10n_es_facturae_face/migrations/14.0.2.2.0/post-migration.py
Labels: approved, bot is merging ⏳

#3118 [16.0][FIX] l10n_es_aeat: fix broken views
  l10n_es_aeat/views/aeat_export_configuration_view.xml
  l10n_es_aeat/views/aeat_tax_code_mapping_view.xml
Labels: approved, bot is merging ⏳

#3048 [16.0][MIG] l10n_es_aeat_mod303_oss: Migration to 16.0
  l10n_es_aeat_mod303_oss/README.rst
  l10n_es_aeat_mod303_oss/__init__.py
  l10n_es_aeat_mod303_oss/__manifest__.py
  l10n_es_aeat_mod303_oss/data/2021-07/l10n_es_aeat_map_tax_line.xml
  l10n_es_aeat_mod303_oss/data/2023/l10n_es_aeat_map_tax_line.xml
  l10n_es_aeat_mod303_oss/i18n/ca.po
  l10n_es_aeat_mod303_oss/i18n/l10n_es_aeat_mod303_oss.pot
  l10n_es_aeat_mod303_oss/models/__init__.py
  l10n_es_aeat_mod303_oss/models/mod303.py
  l10n_es_aeat_mod303_oss/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303_oss/readme/DESCRIPTION.rst
  l10n_es_aeat_mod303_oss/static/description/icon.png
  l10n_es_aeat_mod303_oss/static/description/icon_source.svg
  l10n_es_aeat_mod303_oss/static/description/index.html
  l10n_es_aeat_mod303_oss/tests/__init__.py
  l10n_es_aeat_mod303_oss/tests/test_l10n_es_aeat_mod303_oss.py
  setup/l10n_es_aeat_mod303_oss/odoo/addons/l10n_es_aeat_mod303_oss
  setup/l10n_es_aeat_mod303_oss/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3121 [15.0][BPRT] l10n_es_facturae_face: Port de 14 a 15 de múltiples commits
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/components/__init__.py
  l10n_es_facturae_face/components/edi_send_l10n_es_facturae_face.py
  l10n_es_facturae_face/components/edi_send_l10n_es_facturae_face_cancel.py
  l10n_es_facturae_face/components/edi_webservice_receive_face_l10n_es_facturae_face_update.py
  l10n_es_facturae_face/components/webservice_face.py
  l10n_es_facturae_face/data/edi.xml
  l10n_es_facturae_face/data/edi_output.xml
  l10n_es_facturae_face/data/face_data.xml
  l10n_es_facturae_face/migrations/15.0.2.0.0/post-migration.py
  l10n_es_facturae_face/migrations/15.0.2.1.0/post-migration.py
  l10n_es_facturae_face/models/__init__.py
  l10n_es_facturae_face/models/edi_exchange_record.py
  l10n_es_facturae_face/models/webservice_backend.py
  l10n_es_facturae_face/readme/CONTRIBUTORS.rst
  l10n_es_facturae_face/tests/test_facturae_face.py
  l10n_es_facturae_face/views/res_partner.xml
Labels: approved, bot is merging ⏳

#3059 [12.0][IMP] l10n_es_ticketbai: convert to company currency if invoice currency is different
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/tests/test_l10n_es_ticketbai_customer_invoice.py
Labels: approved, ready to merge, bot is merging ⏳

#3112 [16.0][MIG] l10n_es_aeat_sii_oss: Migration to 16.0
  l10n_es_aeat_sii_oss/README.rst
  l10n_es_aeat_sii_oss/__init__.py
  l10n_es_aeat_sii_oss/__manifest__.py
  l10n_es_aeat_sii_oss/data/aeat_sii_mapping_registration_keys_data.xml
  l10n_es_aeat_sii_oss/i18n/ca.po
  l10n_es_aeat_sii_oss/i18n/l10n_es_aeat_sii_oss.pot
  l10n_es_aeat_sii_oss/models/__init__.py
  l10n_es_aeat_sii_oss/models/account_move.py
  l10n_es_aeat_sii_oss/readme/CONFIGURE.rst
  l10n_es_aeat_sii_oss/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_oss/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_oss/readme/INSTALL.rst
  l10n_es_aeat_sii_oss/static/description/icon.png
  l10n_es_aeat_sii_oss/static/description/icon_source.svg
  l10n_es_aeat_sii_oss/static/description/index.html
  l10n_es_aeat_sii_oss/tests/__init__.py
  l10n_es_aeat_sii_oss/tests/test_l10n_es_aeat_sii.py
  setup/l10n_es_aeat_sii_oss/odoo/addons/l10n_es_aeat_sii_oss
  setup/l10n_es_aeat_sii_oss/setup.py
Labels: approved, bot is merging ⏳

#3116 [IMP] l10n_es_aeat_sii_oca: move reversal defaul sii_refund_type
  l10n_es_aeat_sii_oca/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
  l10n_es_aeat_sii_oca/wizards/account_move_reversal.py
Labels: approved, ready to merge, bot is merging ⏳

#3117 [15.0][MIG] l10n_es_aeat_mod369: Migration to 15.0
  l10n_es_aeat_mod369/README.rst
  l10n_es_aeat_mod369/__init__.py
  l10n_es_aeat_mod369/__manifest__.py
  l10n_es_aeat_mod369/data/2022/00/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/04/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/05/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/06/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/07/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/08/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/09/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod369/data/2022/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod369/data/2022/main/aeat.model.export.config.line.csv
  l10n_es_aeat_mod369/data/tax_code_map_mod369_data.xml
  l10n_es_aeat_mod369/docs/DR369e21.xlsx
  l10n_es_aeat_mod369/docs/Descripcion_PresentacionFichero369_v1.pdf
  l10n_es_aeat_mod369/i18n/es.po
  l10n_es_aeat_mod369/i18n/l10n_es_aeat_mod369.pot
  l10n_es_aeat_mod369/models/__init__.py
  l10n_es_aeat_mod369/models/account_tax.py
  l10n_es_aeat_mod369/models/l10n_es_aeat_tax_line.py
  l10n_es_aeat_mod369/models/mod369.py
  l10n_es_aeat_mod369/models/mod369_line.py
  l10n_es_aeat_mod369/models/mod369_line_grouped.py
  l10n_es_aeat_mod369/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod369/readme/DESCRIPTION.rst
  l10n_es_aeat_mod369/readme/ROADMAP.rst
  l10n_es_aeat_mod369/readme/USAGE.rst
  l10n_es_aeat_mod369/security/ir.model.access.csv
  l10n_es_aeat_mod369/security/l10n_es_aeat_mod369_security.xml
  l10n_es_aeat_mod369/static/description/icon.png
  l10n_es_aeat_mod369/static/description/index.html
  l10n_es_aeat_mod369/tests/__init__.py
  l10n_es_aeat_mod369/tests/test_l10n_es_aeat_mod369.py
  l10n_es_aeat_mod369/views/account_tax_view.xml
  l10n_es_aeat_mod369/views/mod369_view.xml
  setup/l10n_es_aeat_mod369/odoo/addons/l10n_es_aeat_mod369
  setup/l10n_es_aeat_mod369/setup.py
Labels: bot is merging ⏳
