Repository OCA/l10n-spain, pull requests merged in 2023-12, with the labels that each got.

#3288 [14.0][IMP] l10n_es_facturae: Add new fields
  l10n_es_facturae/README.rst
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/readme/CONTRIBUTORS.rst
  l10n_es_facturae/static/description/index.html
  l10n_es_facturae/views/account_move_view.xml
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#3335 [15.0][IMP] l10n_es_facturae: Add new fields
  l10n_es_facturae/README.rst
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/readme/CONTRIBUTORS.rst
  l10n_es_facturae/static/description/index.html
  l10n_es_facturae/views/account_move_view.xml
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#3336 [16.0][IMP] l10n_es_facturae: Add new fields
  l10n_es_facturae/README.rst
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/readme/CONTRIBUTORS.rst
  l10n_es_facturae/static/description/index.html
  l10n_es_facturae/views/account_move_view.xml
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#3314 [16.0][FIX] l10n_es_aeat: No ir.model forbidden access, missing sudo in field domain
  l10n_es_aeat/models/l10n_es_aeat_report.py
Labels: bot is merging ⏳

#3306 [12.0][IMP] l10n_es_ticketbai_api
  l10n_es_ticketbai_api/models/ticketbai_invoice_tax.py
Labels: approved, ready to merge, bot is merging ⏳

#3070 [12.0][IMP] l10n_es_ticketbai*: backport de #3044 + ajustes para v12
  l10n_es_ticketbai/models/account_invoice.py
  l10n_es_ticketbai/models/account_invoice_tax.py
  l10n_es_ticketbai/models/account_tax.py
  l10n_es_ticketbai_api/models/ticketbai_invoice_tax.py
Labels: bot is merging ⏳

#3340 [16.0][FIX] l10n_es_facturae: Facturae field visibility for all the childrens
  l10n_es_facturae/views/res_partner_view.xml
Labels: bot is merging ⏳

#3341 [16.0][FIX] l10n_es_facturae: Precio unitario
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/views/report_facturae.xml
Labels: approved, bot is merging ⏳

#3342 [16.0][IMP] l10n_es_aeat_mod_190: Retenciones IRPF Consejeros y Administradores
  l10n_es_aeat_mod190/data/tax_code_map_mod190_data.xml
Labels: approved, bot is merging ⏳

#3344 [15.0][IMP] l10n_es_aeat_mod_190: Retenciones IRPF Consejeros y Administradores
  l10n_es_aeat_mod190/data/tax_code_map_mod190_data.xml
Labels: bot is merging ⏳

#3343 [15.0][IMP] l10n_es_aeat_mod_111: Retenciones IRPF Consejeros y Administradores
  l10n_es_aeat_mod111/data/tax_code_map_mod111_data.xml
Labels: bot is merging ⏳

#3346 [16.0][FIX] l10n_es_aeat_mod303_oss: Make sure company's country is set
  l10n_es_aeat_mod303_oss/tests/test_l10n_es_aeat_mod303_oss.py
Labels: bot is merging ⏳

#3350 [15.0][FIX] l10n_es_aeat: Convert COM countries to France
  l10n_es_aeat/models/res_partner.py
Labels: approved, bot is merging ⏳

#3352 [16.0][FIX] l10n_es_aeat: Convert COM countries to France
  l10n_es_aeat/models/res_partner.py
Labels: bot is merging ⏳

#3351 [14.0][FIX] l10n_es_aeat: Convert COM countries to France
  l10n_es_aeat/models/res_partner.py
Labels: bot is merging ⏳

#3355 [16.0][FIX] l10n_es_aeat_sii_oca: Inherit proper view
  l10n_es_aeat_sii_oca/views/product_view.xml
Labels: bot is merging ⏳
