Repository OCA/l10n-spain, pull requests merged in 2024-09, with the labels that each got.

#3572 [16.0][IMP] Refactor para futura implementación Veri*FACTU.
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat/migrations/16.0.2.5.0/pre-migration.py
  l10n_es_aeat/models/__init__.py
  l10n_es_aeat/models/account_fiscal_position.py
  l10n_es_aeat/models/aeat_mixin.py
  l10n_es_aeat/models/res_partner.py
  l10n_es_aeat/static/description/index.html
  l10n_es_aeat/views/res_partner_view.xml
  l10n_es_aeat_sii_force_type/models/account_move.py
  l10n_es_aeat_sii_force_type/tests/test_l10n_es_aeat_sii_force_type.py
  l10n_es_aeat_sii_invoice_summary/models/account_move.py
  l10n_es_aeat_sii_invoice_summary/tests/test_l10n_es_aeat_sii_invoice_summary.py
  l10n_es_aeat_sii_match/models/account_move.py
  l10n_es_aeat_sii_match/models/aeat_sii_match_report.py
  l10n_es_aeat_sii_match/tests/test_l10n_es_aeat_sii_match.py
  l10n_es_aeat_sii_match/views/account_move_views.xml
  l10n_es_aeat_sii_oca/models/account_fiscal_position.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/models/res_company.py
  l10n_es_aeat_sii_oca/models/res_partner.py
  l10n_es_aeat_sii_oca/models/sii_mixin.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
  l10n_es_aeat_sii_oca/views/account_fiscal_position_view.xml
  l10n_es_aeat_sii_oca/views/account_move_views.xml
  l10n_es_aeat_sii_oca/views/res_partner_views.xml
  l10n_es_aeat_sii_oss/models/account_move.py
  l10n_es_aeat_sii_oss/tests/test_l10n_es_aeat_sii.py
  l10n_es_aeat_sii_taxfree/models/account_move.py
  l10n_es_aeat_sii_taxfree/tests/test_l10n_es_aeat_sii_taxfree.py
  l10n_es_dua_sii/models/account_move.py
  l10n_es_pos_sii/models/pos_order.py
  l10n_es_pos_sii/tests/test_l10n_es_pos_sii.py
  l10n_es_pos_sii/views/pos_order.xml
Labels: approved, bot is merging ⏳

#3710 [17.0][IMP] l10n_es_aeat: Refactor para futura implementación Veri*FACTU
  l10n_es_aeat/models/__init__.py
  l10n_es_aeat/models/account_fiscal_position.py
  l10n_es_aeat/models/aeat_mixin.py
  l10n_es_aeat/models/res_partner.py
  l10n_es_aeat/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#3712 [15.0][FIX] delivery_seur_atlas: prod env and request logging
  delivery_seur_atlas/models/delivery_carrier.py
  delivery_seur_atlas/models/seur_request_atlas.py
Labels: approved, bot is merging ⏳

#3713 [14.0][FIX] delivery_mrw: Avoid test error
  delivery_mrw/tests/test_delivery_mrw.py
Labels: bot is merging ⏳

#3345 [14.0][FIX] l10n_es_pos: OrderReceipt template name
  l10n_es_pos/static/src/xml/pos.xml
Labels: bot is merging ⏳, stale

#3644 [14.0][IMP] l10n_es_vat_porate: Use a proper account on investments and assets
  l10n_es_vat_prorate/models/account_move.py
  l10n_es_vat_prorate/models/res_company.py
  l10n_es_vat_prorate/tests/test_vat_prorate.py
  l10n_es_vat_prorate/views/res_company_views.xml
Labels: bot is merging ⏳

#3714 [15.0][IMP] l10n_es_vat_porate: Use a proper account on investments and assets
  l10n_es_vat_prorate/models/account_move.py
  l10n_es_vat_prorate/models/res_company.py
  l10n_es_vat_prorate/tests/test_vat_prorate.py
  l10n_es_vat_prorate/views/res_company_views.xml
Labels: bot is merging ⏳

#3715 [16.0][IMP] l10n_es_vat_porate: Use a proper account on investments and assets
  l10n_es_vat_prorate/models/account_move.py
  l10n_es_vat_prorate/models/res_company.py
  l10n_es_vat_prorate/tests/test_vat_prorate.py
  l10n_es_vat_prorate/views/res_company_views.xml
Labels: bot is merging ⏳

#3717 [16.0][FIX] l10n_es_pos_sii: Set own channel for POS order SII jobs
  l10n_es_pos_sii/__manifest__.py
  l10n_es_pos_sii/data/aeat_sii_queue_job.xml
  l10n_es_pos_sii/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#3723 [FIX][17.0] l10n_es_aeat: Wrong field for res.company
  l10n_es_aeat/models/aeat_mixin.py
Labels: approved, bot is merging ⏳

#3716 [15.0][FIX] delivery_seur_atlas: avoid `False` email
  delivery_seur_atlas/models/delivery_carrier.py
Labels: bot is merging ⏳

#3727 [15.0] Revert "[FIX] l10n_es_aeat_mod349: origin amount incorrect"
  l10n_es_aeat_mod349/models/mod349.py
Labels: bot is merging ⏳

#3728 [14.0] Revert "[FIX] l10n_es_aeat_mod349: origin amount incorrect"
  l10n_es_aeat_mod349/models/mod349.py
Labels: bot is merging ⏳

#3729 [16.0] Revert "[FIX] l10n_es_aeat_mod349: origin amount incorrect"
  l10n_es_aeat_mod349/models/mod349.py
Labels: bot is merging ⏳

#3683 [17.0][MIG] l10n_es_facturae_face: Migration to v17
  l10n_es_facturae_face/README.rst
  l10n_es_facturae_face/__init__.py
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/components/__init__.py
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_face_listener.py
  l10n_es_facturae_face/components/account_move_l10n_es_facturae_listener.py
  l10n_es_facturae_face/components/edi_input_process_l10n_es_facturae_l10n_es_facturae_face_update.py
  l10n_es_facturae_face/components/edi_send_l10n_es_facturae_face.py
  l10n_es_facturae_face/components/edi_send_l10n_es_facturae_face_cancel.py
  l10n_es_facturae_face/components/edi_webservice_receive_face_l10n_es_facturae_face_update.py
  l10n_es_facturae_face/components/webservice_face.py
  l10n_es_facturae_face/data/cron_data.xml
  l10n_es_facturae_face/data/edi.xml
  l10n_es_facturae_face/data/face_data.xml
  l10n_es_facturae_face/i18n/ca.po
  l10n_es_facturae_face/i18n/es.po
  l10n_es_facturae_face/i18n/l10n_es_facturae_face.pot
  l10n_es_facturae_face/models/__init__.py
  l10n_es_facturae_face/models/account_move.py
  l10n_es_facturae_face/models/edi_exchange_record.py
  l10n_es_facturae_face/models/res_company.py
  l10n_es_facturae_face/models/res_partner.py
  l10n_es_facturae_face/models/wsse_signature.py
  l10n_es_facturae_face/pyproject.toml
  l10n_es_facturae_face/readme/CONFIGURE.md
  l10n_es_facturae_face/readme/CONTRIBUTORS.md
  l10n_es_facturae_face/readme/DESCRIPTION.md
  l10n_es_facturae_face/readme/USAGE.md
  l10n_es_facturae_face/security/ir.model.access.csv
  l10n_es_facturae_face/static/description/icon.png
  l10n_es_facturae_face/static/description/index.html
  l10n_es_facturae_face/tests/__init__.py
  l10n_es_facturae_face/tests/test_facturae_face.py
  l10n_es_facturae_face/views/account_move.xml
  l10n_es_facturae_face/views/edi_exchange_record.xml
  l10n_es_facturae_face/views/res_company_view.xml
  l10n_es_facturae_face/views/res_partner.xml
  l10n_es_facturae_face/wizards/__init__.py
  l10n_es_facturae_face/wizards/edi_l10n_es_facturae_face_cancel.py
  l10n_es_facturae_face/wizards/edi_l10n_es_facturae_face_cancel.xml
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#3732 [15.0][FIX] delivery_seur_atlas: shipping to Andorra
  delivery_seur_atlas/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#3736 [16.0][IMP] l10n_es_aeat_sii_oca: send with quarters only for voluntary
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/models/res_company.py
  l10n_es_aeat_sii_oca/models/sii_mixin.py
  l10n_es_aeat_sii_oca/views/res_company_view.xml
Labels: bot is merging ⏳

#3739 [15.0][IMP] l10n_es_aeat_sii_oca: Updated taxes october 2024
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: bot is merging ⏳

#3740 [16.0][IMP] l10n_es_aeat_sii_oca: Updated taxes october 2024
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: bot is merging ⏳

#3741 [16.0][FIX] l10n_es_aeat_sii_oca: Missing mappings
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: bot is merging ⏳

#3742 [15.0][FIX] l10n_es_aeat_sii_oca: Missing mappings
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: bot is merging ⏳

#3743 [17.0] Revert "[FIX] l10n_es_aeat_mod349: origin amount incorrect"
  l10n_es_aeat_mod349/models/mod349.py
Labels: bot is merging ⏳

#3744 [15.0][FIX] l10n_es_aeat: Take into account inactive tax templates
  l10n_es_aeat/models/l10n_es_aeat_report_tax_mapping.py
  l10n_es_aeat/views/aeat_tax_code_mapping_view.xml
Labels: bot is merging ⏳

#3745 [16.0][FIX] l10n_es_aeat: Take into account inactive tax templates
  l10n_es_aeat/models/l10n_es_aeat_report_tax_mapping.py
  l10n_es_aeat/views/aeat_tax_code_mapping_view.xml
Labels: bot is merging ⏳

#3746 [17.0][FIX] l10n_es_aeat: Take into account inactive tax templates
  l10n_es_aeat/models/l10n_es_aeat_report_tax_mapping.py
  l10n_es_aeat/views/aeat_map_tax_views.xml
Labels: bot is merging ⏳
