Repository OCA/l10n-spain, pull requests merged in 2024-12, with the labels that each got.

#3691 [15.0][ADD] l10n_es_igic
  l10n_es_igic/README.rst
  l10n_es_igic/__init__.py
  l10n_es_igic/__manifest__.py
  l10n_es_igic/data/account.account.template-assoc-canary.csv
  l10n_es_igic/data/account.account.template-common-canary.csv
  l10n_es_igic/data/account.account.template-full-canary.csv
  l10n_es_igic/data/account.account.template-pymes-canary.csv
  l10n_es_igic/data/account_chart_template_data.xml
  l10n_es_igic/data/account_fiscal_position_template_canary_data.xml
  l10n_es_igic/data/account_tax_data.xml
  l10n_es_igic/data/account_tax_group_data.xml
  l10n_es_igic/i18n/es.po
  l10n_es_igic/i18n/l10n_es_igic.pot
  l10n_es_igic/readme/CONTRIBUTORS.rst
  l10n_es_igic/readme/DESCRIPTION.rst
  l10n_es_igic/readme/INSTALL.rst
  l10n_es_igic/static/description/icon.png
  l10n_es_igic/static/description/index.html
  setup/l10n_es_igic/odoo/addons/l10n_es_igic
  setup/l10n_es_igic/setup.py
Labels: approved, bot is merging ⏳, stale

#3832 [16.0][IMP] l10n_es_vat_prorate: Add hook for VAT prorate move line
  l10n_es_vat_prorate/models/account_move.py
Labels: bot is merging ⏳

#3681 [16.0][FIX] l10n_es_aeat_sii_taxfree: Avoid FacturaExpedida block treatment…
  l10n_es_aeat_sii_taxfree/models/account_move.py
Labels: bot is merging ⏳

#3837 [15.0][IMP] l10n_es_vat_book: Added missing taxes to mapping book
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#3839 [16.0][FIX] l10n_es_vat_book: Incorrect mapping for non deductible
  l10n_es_vat_book/data/aeat_vat_book_map_data.xml
Labels: bot is merging ⏳

#3838 [17.0][IMP] l10n_es_vat_book: Include october 2024 taxes
  l10n_es_vat_book/data/aeat.vat.book.map.line.csv
  l10n_es_vat_book/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_vat_book/report/vat_book_xlsx.py
Labels: bot is merging ⏳

#3843 [17.0][FIX] l10n_es_aeat_mod303: Missing "to regularize" flags
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#3840 [15.0][FIX] l10n_es_aeat_mod303: Missing "to regularize" flags
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#3841 [16.0][FIX] l10n_es_aeat_mod303: Missing "to regularize" flags
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#3830 [16.0][FIX] l10n_es_aeat_mod349: Solve error where rectifications for other periods do not have the correct original amount
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
Labels: bot is merging ⏳

#3847 [16.0][FIX] l10n_es_aeat_mod303: Fields 14, 15 and 80 miss the new taxes
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#3848 [15.0][FIX] l10n_es_aeat_mod303: Fields 14, 15 and 80 miss the new taxes
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#3849 [17.0][FIX] l10n_es_aeat_mod303: Fields 14, 15 and 80 miss the new taxes
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#3850 [IMP] Update pre-commit
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: approved, bot is merging ⏳

#3859 [16.0][IMP] l10n_es_vat_prorate: Include new october 2024 taxes
  l10n_es_vat_prorate/data/account_template_tax.xml
Labels: bot is merging ⏳

#3855 [IMP] l10n_es_mis_report: Include 4757
  l10n_es_mis_report/data/mis_report_balance_normal.xml
Labels: bot is merging ⏳

#3794 [IMP] l10n_es_aeat_mod303_oss: include lines oss in map mod303 2024-10
  l10n_es_aeat_mod303_oss/__manifest__.py
  l10n_es_aeat_mod303_oss/data/2024-10/l10n_es_aeat_map_tax_line.xml
  l10n_es_aeat_mod303_oss/models/mod303.py
  l10n_es_aeat_mod303_oss/static/description/index.html
Labels: bot is merging ⏳

#3808 [16.0][IMP] l10n_es_aeat_mod303_oss: include lines oss in map mod303 2024-10
  l10n_es_aeat_mod303_oss/__manifest__.py
  l10n_es_aeat_mod303_oss/data/2024-10/l10n_es_aeat_map_tax_line.xml
  l10n_es_aeat_mod303_oss/models/mod303.py
Labels: approved, ready to merge, bot is merging ⏳

#3863 [16.0][IMP] l10n_es_aeat_mod347_igic: propose maintainer
  l10n_es_aeat_mod347_igic/README.rst
  l10n_es_aeat_mod347_igic/__manifest__.py
  l10n_es_aeat_mod347_igic/static/description/index.html
Labels: bot is merging ⏳

#3694 [15.0][ADD] l10n_es_aeat_mod347_igic
  l10n_es_aeat_mod347_igic/README.rst
  l10n_es_aeat_mod347_igic/__init__.py
  l10n_es_aeat_mod347_igic/__manifest__.py
  l10n_es_aeat_mod347_igic/data/tax_code_map_mod347_igic_data.xml
  l10n_es_aeat_mod347_igic/i18n/l10n_es_aeat_mod347_igic.pot
  l10n_es_aeat_mod347_igic/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod347_igic/readme/DESCRIPTION.rst
  l10n_es_aeat_mod347_igic/readme/INSTALL.rst
  l10n_es_aeat_mod347_igic/static/description/icon.png
  l10n_es_aeat_mod347_igic/static/description/index.html
  setup/l10n_es_aeat_mod347_igic/odoo/addons/l10n_es_aeat_mod347_igic
  setup/l10n_es_aeat_mod347_igic/setup.py
Labels: approved, bot is merging ⏳

#3866 [17.0][FIX] l10n_es_igic: Refactorizado y recuperación de ids anteriores
  l10n_es_igic/README.rst
  l10n_es_igic/__init__.py
  l10n_es_igic/__manifest__.py
  l10n_es_igic/data/template/account.account-es_assec.csv
  l10n_es_igic/data/template/account.account-es_assoc_canary.csv
  l10n_es_igic/data/template/account.account-es_common.csv
  l10n_es_igic/data/template/account.account-es_common_canary.csv
  l10n_es_igic/data/template/account.account-es_full_canary.csv
  l10n_es_igic/data/template/account.account-es_pymes_canary.csv
  l10n_es_igic/data/template/account.fiscal.position-es_common.csv
  l10n_es_igic/data/template/account.tax-es_assoc_canary.csv
  l10n_es_igic/data/template/account.tax-es_common.csv
  l10n_es_igic/data/template/account.tax-es_common_canary.csv
  l10n_es_igic/data/template/account.tax-es_full_canary.csv
  l10n_es_igic/data/template/account.tax-es_pymes_canary.csv
  l10n_es_igic/data/template/account.tax.group-es_common.csv
  l10n_es_igic/models/template_es_canary.py
Labels: approved, bot is merging ⏳

#3869 [17.0][FW-PORT] l10n_es_aeat_mod347: make email template methods easier to extend
  l10n_es_aeat_mod347/models/mod347.py
Labels: bot is merging ⏳

#3867 [17.0][IMP] l10n_es_igic: Added pre-migration script
  l10n_es_igic/__manifest__.py
  l10n_es_igic/migrations/17.0.2.1.0/pre-migration.py
Labels: approved, bot is merging ⏳

#3865 [17.0][MIG] delivery_gls_asm: Migration to 17.0
  delivery_gls_asm/README.rst
  delivery_gls_asm/__init__.py
  delivery_gls_asm/__manifest__.py
  delivery_gls_asm/api/gls_asm_api.wsdl
  delivery_gls_asm/data/delivery_asm_data.xml
  delivery_gls_asm/i18n/ca.po
  delivery_gls_asm/i18n/delivery_gls_asm.pot
  delivery_gls_asm/i18n/es.po
  delivery_gls_asm/models/__init__.py
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/models/gls_asm_master_data.py
  delivery_gls_asm/models/gls_asm_request.py
  delivery_gls_asm/models/stock_picking.py
  delivery_gls_asm/pyproject.toml
  delivery_gls_asm/readme/CONFIGURE.md
  delivery_gls_asm/readme/CONTRIBUTORS.md
  delivery_gls_asm/readme/DESCRIPTION.md
  delivery_gls_asm/readme/INSTALL.md
  delivery_gls_asm/readme/ROADMAP.md
  delivery_gls_asm/readme/USAGE.md
  delivery_gls_asm/security/ir.model.access.csv
  delivery_gls_asm/static/description/icon.png
  delivery_gls_asm/static/description/icon.svg
  delivery_gls_asm/static/description/index.html
  delivery_gls_asm/tests/__init__.py
  delivery_gls_asm/tests/test_delivery_gls_asm.py
  delivery_gls_asm/views/delivery_asm_view.xml
  delivery_gls_asm/views/gls_asm_manifest_template.xml
  delivery_gls_asm/views/stock_picking_views.xml
  delivery_gls_asm/wizard/__init__.py
  delivery_gls_asm/wizard/gls_asm_manifest_wizard.py
  delivery_gls_asm/wizard/gls_asm_manifest_wizard_views.xml
  requirements.txt
Labels: approved, bot is merging ⏳

#3854 [15.0][FIX] l10n_es_facturae: required conditions
  l10n_es_facturae/views/res_partner_view.xml
Labels: approved, bot is merging ⏳
