Repository OCA/l10n-spain, pull requests merged in 2024-02, with the labels that each got.

#3398 [12.0][FIX] l10n_es_aeat_mod303: wrong result type on comparing with zero
  l10n_es_aeat_mod303/models/mod303.py
Labels: approved, ready to merge, bot is merging ⏳

#3420 [15.0][FIX] l10n_es_aeat_mod190: BOE format + chatter in report
  l10n_es_aeat_mod190/data/aeat_export_mod190_data.xml
  l10n_es_aeat_mod190/data/aeat_export_mod190_partner_data.xml
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
  l10n_es_aeat_mod190/tests/test_mod190.py
  l10n_es_aeat_mod190/views/mod190_line_view.xml
  l10n_es_aeat_mod190/views/mod190_view.xml
Labels: bot is merging ⏳

#3422 [16.0][FIX] l10n_es_aeat_mod190: BOE format + chatter in report
  l10n_es_aeat_mod190/data/aeat_export_mod190_data.xml
  l10n_es_aeat_mod190/data/aeat_export_mod190_partner_data.xml
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
  l10n_es_aeat_mod190/tests/test_mod190.py
  l10n_es_aeat_mod190/views/mod190_line_view.xml
  l10n_es_aeat_mod190/views/mod190_view.xml
Labels: bot is merging ⏳

#3421 [15.0][FIX] l10n_es_vat_book_oss: Wrong dependency
  l10n_es_vat_book_oss/README.rst
  l10n_es_vat_book_oss/__manifest__.py
  l10n_es_vat_book_oss/static/description/index.html
Labels: approved, bot is merging ⏳

#3402 [14.0][FIX] l10n_es_aeat_sii_oca: cliente intracomunitario, entrega extracomunitaria
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: approved, ready to merge, bot is merging ⏳

#3424 [16.0][FIX] l10n_es_facturae: Fix addition of invoice PDF by adding encoding
  l10n_es_facturae/models/account_move.py
Labels: approved, bot is merging ⏳

#3426 [13.0][FIX] l10n_es_aeat_mod347: incorrect company in reports and email template with multicompany.
  l10n_es_aeat_mod347/data/mail_template_data.xml
  l10n_es_aeat_mod347/views/report_347_partner.xml
Labels: approved, bot is merging ⏳

#3428 [FIX] l10n_es_dua_sii: compute dua invoice
  l10n_es_dua_sii/models/account_move.py
Labels: bot is merging ⏳

#3432 [14.0][IMP] delivery_gls_asm: Nuevo servicio '96 - BUSINESS PARCEL'
  delivery_gls_asm/models/gls_asm_master_data.py
Labels: approved, bot is merging ⏳

#3433 [14.0][FIX] l10n_es_aeat_mod347: compañia incorrecta en plantilla de correo.
  l10n_es_aeat_mod347/README.rst
  l10n_es_aeat_mod347/__manifest__.py
  l10n_es_aeat_mod347/data/mail_template_data.xml
  l10n_es_aeat_mod347/migrations/14.0.2.6.1/post-migration.py
  l10n_es_aeat_mod347/static/description/index.html
Labels: approved, bot is merging ⏳

#3434 [16.0][FIX] l10n_es_payment_order_confirming_aef: Put processing date as today
  l10n_es_payment_order_confirming_aef/models/confirming_aef.py
Labels: bot is merging ⏳

#3435 [15.0][FIX] l10n_es_payment_order_confirming_aef: Put processing date as today
  l10n_es_payment_order_confirming_aef/models/confirming_aef.py
Labels: approved, bot is merging ⏳

#3250 [FIX] l10n_es_ticketbai_batuz: Fecha factura rectificada se pasa a texto.
  l10n_es_ticketbai_batuz/models/account_move.py
Labels: approved, bot is merging ⏳

#3281 [16.0][ADD]l10n_es_sigaus_account: manage sigaus expenses in invoices
  l10n_es_sigaus_account/README.rst
  l10n_es_sigaus_account/__init__.py
  l10n_es_sigaus_account/__manifest__.py
  l10n_es_sigaus_account/data/data.xml
  l10n_es_sigaus_account/data/exception_templates.xml
  l10n_es_sigaus_account/hooks.py
  l10n_es_sigaus_account/i18n/es.po
  l10n_es_sigaus_account/models/__init__.py
  l10n_es_sigaus_account/models/account_fiscal_position.py
  l10n_es_sigaus_account/models/account_move.py
  l10n_es_sigaus_account/models/account_move_line.py
  l10n_es_sigaus_account/models/l10n_es_sigaus_amount.py
  l10n_es_sigaus_account/models/product_category.py
  l10n_es_sigaus_account/models/product_product.py
  l10n_es_sigaus_account/models/product_template.py
  l10n_es_sigaus_account/models/res_company.py
  l10n_es_sigaus_account/models/sigaus_line_mixin.py
  l10n_es_sigaus_account/models/sigaus_mixin.py
  l10n_es_sigaus_account/readme/CONFIGURE.rst
  l10n_es_sigaus_account/readme/CONTRIBUTORS.rst
  l10n_es_sigaus_account/readme/DESCRIPTION.rst
  l10n_es_sigaus_account/readme/ROADMAP.rst
  l10n_es_sigaus_account/readme/USAGE.rst
  l10n_es_sigaus_account/security/ir.model.access.csv
  l10n_es_sigaus_account/static/description/icon.png
  l10n_es_sigaus_account/static/description/icon.svg
  l10n_es_sigaus_account/static/description/index.html
  l10n_es_sigaus_account/tests/__init__.py
  l10n_es_sigaus_account/tests/common.py
  l10n_es_sigaus_account/tests/test_l10n_es_sigaus_account.py
  l10n_es_sigaus_account/tests/test_l10n_es_sigaus_general_values.py
  l10n_es_sigaus_account/views/account_fiscal_position_views.xml
  l10n_es_sigaus_account/views/account_move_views.xml
  l10n_es_sigaus_account/views/l10n_es_sigaus_amount_views.xml
  l10n_es_sigaus_account/views/product_category_views.xml
  l10n_es_sigaus_account/views/product_views.xml
  l10n_es_sigaus_account/views/report_invoice.xml
  l10n_es_sigaus_account/views/res_company_views.xml
  l10n_es_sigaus_account/wizard/__init__.py
  l10n_es_sigaus_account/wizard/account_move_reversal.py
  setup/l10n_es_sigaus_account/odoo/addons/l10n_es_sigaus_account
  setup/l10n_es_sigaus_account/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3378 [14.0][IMP] l10n_es_aeat_mod322: Fix comptuation of vinculated partners
  l10n_es_aeat_mod322/models/l10n_es_aeat_mod322_report.py
Labels: approved, bot is merging ⏳

#3446 [12.0][IMP] l10n_es_ticketbai: change init hook to make it more light
  l10n_es_ticketbai/hooks.py
Labels: approved, bot is merging ⏳

#3404 [16.0] [ADD] l10n_es _sigaus_sale, manage sigaus expenses in sales
  l10n_es_sigaus_sale/README.rst
  l10n_es_sigaus_sale/__init__.py
  l10n_es_sigaus_sale/__manifest__.py
  l10n_es_sigaus_sale/data/exception_templates.xml
  l10n_es_sigaus_sale/hooks.py
  l10n_es_sigaus_sale/i18n/es.po
  l10n_es_sigaus_sale/models/__init__.py
  l10n_es_sigaus_sale/models/account_move.py
  l10n_es_sigaus_sale/models/sale_order.py
  l10n_es_sigaus_sale/models/sale_order_line.py
  l10n_es_sigaus_sale/readme/CONFIGURE.rst
  l10n_es_sigaus_sale/readme/CONTRIBUTORS.rst
  l10n_es_sigaus_sale/readme/DESCRIPTION.rst
  l10n_es_sigaus_sale/readme/ROADMAP.rst
  l10n_es_sigaus_sale/readme/USAGE.rst
  l10n_es_sigaus_sale/report/ir_actions_report_templates.xml
  l10n_es_sigaus_sale/static/description/icon.png
  l10n_es_sigaus_sale/static/description/icon.svg
  l10n_es_sigaus_sale/static/description/index.html
  l10n_es_sigaus_sale/tests/__init__.py
  l10n_es_sigaus_sale/tests/test_l10n_es_sigaus_sale.py
  l10n_es_sigaus_sale/views/sale_order_views.xml
  setup/l10n_es_sigaus_sale/odoo/addons/l10n_es_sigaus_sale
  setup/l10n_es_sigaus_sale/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3325 [17.0][MIG] l10n_es_partner: Migration to 17.0
  l10n_es_partner/README.rst
  l10n_es_partner/__init__.py
  l10n_es_partner/__manifest__.py
  l10n_es_partner/data/l10n_es_partner_data.xml
  l10n_es_partner/gen_src/README.rst
  l10n_es_partner/gen_src/REGBANESP_CONESTAB_A.xls
  l10n_es_partner/gen_src/__init__.py
  l10n_es_partner/gen_src/bics.xls
  l10n_es_partner/gen_src/gen_data_banks.py
  l10n_es_partner/i18n/bg.po
  l10n_es_partner/i18n/ca.po
  l10n_es_partner/i18n/cs.po
  l10n_es_partner/i18n/de.po
  l10n_es_partner/i18n/es.po
  l10n_es_partner/i18n/es_CO.po
  l10n_es_partner/i18n/es_CR.po
  l10n_es_partner/i18n/es_ES.po
  l10n_es_partner/i18n/eu.po
  l10n_es_partner/i18n/fr.po
  l10n_es_partner/i18n/gl.po
  l10n_es_partner/i18n/hr.po
  l10n_es_partner/i18n/l10n_es_partner.pot
  l10n_es_partner/i18n/nl.po
  l10n_es_partner/i18n/pl.po
  l10n_es_partner/i18n/pt.po
  l10n_es_partner/i18n/pt_BR.po
  l10n_es_partner/i18n/ru.po
  l10n_es_partner/i18n/sl.po
  l10n_es_partner/i18n/sv.po
  l10n_es_partner/i18n/tr.po
  l10n_es_partner/i18n/vi.po
  l10n_es_partner/models/__init__.py
  l10n_es_partner/models/res_bank.py
  l10n_es_partner/models/res_partner.py
  l10n_es_partner/pyproject.toml
  l10n_es_partner/readme/CONFIGURE.md
  l10n_es_partner/readme/CONTRIBUTORS.md
  l10n_es_partner/readme/DESCRIPTION.md
  l10n_es_partner/readme/INSTALL.md
  l10n_es_partner/readme/ROADMAP.md
  l10n_es_partner/security/ir.model.access.csv
  l10n_es_partner/static/description/bank.svg
  l10n_es_partner/static/description/icon.png
  l10n_es_partner/static/description/index.html
  l10n_es_partner/tests/__init__.py
  l10n_es_partner/tests/test_l10n_es_partner.py
  l10n_es_partner/views/res_bank_view.xml
  l10n_es_partner/views/res_partner_view.xml
  l10n_es_partner/wizard/__init__.py
  l10n_es_partner/wizard/data_banks.xml
  l10n_es_partner/wizard/l10n_es_partner_wizard.py
  l10n_es_partner/wizard/l10n_es_partner_wizard.xml
Labels: approved, bot is merging ⏳

#3365 [16.0][ADD] l10n_es_aeat_sii_taxfree: module to send a reversal invoice to SII as F1
  l10n_es_aeat_sii_taxfree/README.rst
  l10n_es_aeat_sii_taxfree/__init__.py
  l10n_es_aeat_sii_taxfree/__manifest__.py
  l10n_es_aeat_sii_taxfree/i18n/es.po
  l10n_es_aeat_sii_taxfree/models/__init__.py
  l10n_es_aeat_sii_taxfree/models/account_fiscal_position.py
  l10n_es_aeat_sii_taxfree/models/account_move.py
  l10n_es_aeat_sii_taxfree/readme/CONFIGURE.rst
  l10n_es_aeat_sii_taxfree/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_taxfree/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_taxfree/readme/DEVELOP.rst
  l10n_es_aeat_sii_taxfree/readme/HISTORY.rst
  l10n_es_aeat_sii_taxfree/readme/INSTALL.rst
  l10n_es_aeat_sii_taxfree/readme/ROADMAP.rst
  l10n_es_aeat_sii_taxfree/readme/USAGE.rst
  l10n_es_aeat_sii_taxfree/static/description/icon.png
  l10n_es_aeat_sii_taxfree/static/description/index.html
  l10n_es_aeat_sii_taxfree/tests/__init__.py
  l10n_es_aeat_sii_taxfree/tests/test_l10n_es_aeat_sii_taxfree.py
  l10n_es_aeat_sii_taxfree/views/account_fiscal_position_views.xml
  setup/l10n_es_aeat_sii_taxfree/odoo/addons/l10n_es_aeat_sii_taxfree
  setup/l10n_es_aeat_sii_taxfree/setup.py
Labels: approved, bot is merging ⏳

#3405 [16.0] [ADD] l10n_es_sigaus_purchase, manage SIGAUS expenses in purchases
  l10n_es_sigaus_purchase/README.rst
  l10n_es_sigaus_purchase/__init__.py
  l10n_es_sigaus_purchase/__manifest__.py
  l10n_es_sigaus_purchase/hooks.py
  l10n_es_sigaus_purchase/i18n/es.po
  l10n_es_sigaus_purchase/models/__init__.py
  l10n_es_sigaus_purchase/models/account_move.py
  l10n_es_sigaus_purchase/models/purchase_order.py
  l10n_es_sigaus_purchase/models/purchase_order_line.py
  l10n_es_sigaus_purchase/readme/CONFIGURE.rst
  l10n_es_sigaus_purchase/readme/CONTRIBUTORS.rst
  l10n_es_sigaus_purchase/readme/DESCRIPTION.rst
  l10n_es_sigaus_purchase/readme/USAGE.rst
  l10n_es_sigaus_purchase/report/purchase_order_templates.xml
  l10n_es_sigaus_purchase/report/purchase_quotation_templates.xml
  l10n_es_sigaus_purchase/static/description/icon.png
  l10n_es_sigaus_purchase/static/description/icon.svg
  l10n_es_sigaus_purchase/static/description/index.html
  l10n_es_sigaus_purchase/tests/__init__.py
  l10n_es_sigaus_purchase/tests/test_l10n_es_sigaus_purchase.py
  l10n_es_sigaus_purchase/views/purchase_views.xml
  setup/l10n_es_sigaus_purchase/odoo/addons/l10n_es_sigaus_purchase
  setup/l10n_es_sigaus_purchase/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3454 [16.0][IMP]l10n_es_facturae: add facturae_hide_discount option
  l10n_es_facturae/README.rst
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/models/res_company.py
  l10n_es_facturae/models/res_partner.py
  l10n_es_facturae/readme/CONTRIBUTORS.rst
  l10n_es_facturae/static/description/index.html
  l10n_es_facturae/tests/common.py
  l10n_es_facturae/tests/test_l10n_es_facturae_32.py
  l10n_es_facturae/tests/test_l10n_es_facturae_321.py
  l10n_es_facturae/tests/test_l10n_es_facturae_322.py
  l10n_es_facturae/views/report_facturae.xml
  l10n_es_facturae/views/res_company.xml
  l10n_es_facturae/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#3457 [15.0][MIG] delivery_dhl_parcel: Migration to 15.0
  delivery_dhl_parcel/README.rst
  delivery_dhl_parcel/__init__.py
  delivery_dhl_parcel/__manifest__.py
  delivery_dhl_parcel/doc/Documento_integracion_WEB_SERVICE_B2B_B2C_ver6.pdf
  delivery_dhl_parcel/i18n/ca.po
  delivery_dhl_parcel/i18n/delivery_dhl_parcel.pot
  delivery_dhl_parcel/i18n/es.po
  delivery_dhl_parcel/models/__init__.py
  delivery_dhl_parcel/models/delivery_carrier.py
  delivery_dhl_parcel/models/dhl_parcel_request.py
  delivery_dhl_parcel/models/sale_order.py
  delivery_dhl_parcel/models/stock_picking.py
  delivery_dhl_parcel/readme/CONFIGURE.rst
  delivery_dhl_parcel/readme/CONTRIBUTORS.rst
  delivery_dhl_parcel/readme/DESCRIPTION.rst
  delivery_dhl_parcel/readme/INSTALL.rst
  delivery_dhl_parcel/readme/ROADMAP.rst
  delivery_dhl_parcel/readme/USAGE.rst
  delivery_dhl_parcel/security/ir.model.access.csv
  delivery_dhl_parcel/static/description/icon.png
  delivery_dhl_parcel/static/description/index.html
  delivery_dhl_parcel/tests/__init__.py
  delivery_dhl_parcel/tests/test_delivery_dhl_parcel.py
  delivery_dhl_parcel/views/delivery_carrier_view.xml
  delivery_dhl_parcel/views/stock_picking_views.xml
  delivery_dhl_parcel/wizard/__init__.py
  delivery_dhl_parcel/wizard/dhl_parcel_end_day_wizard.py
  delivery_dhl_parcel/wizard/dhl_parcel_end_day_wizard_views.xml
  setup/delivery_dhl_parcel/odoo/addons/delivery_dhl_parcel
  setup/delivery_dhl_parcel/setup.py
Labels: approved, bot is merging ⏳
