Repository OCA/l10n-spain, pull requests merged in 2024-01, with the labels that each got.

#3356 [14.0][FIX] l10n_es_aeat_sii_oca: Inherit proper view
  l10n_es_aeat_sii_oca/views/product_view.xml
Labels: bot is merging ⏳

#3357 [15.0][FIX] l10n_es_aeat_sii_oca: Inherit proper view
  l10n_es_aeat_sii_oca/views/product_view.xml
Labels: bot is merging ⏳

#3082 [16.0][ADD] l10n_es_vat_book_igic
  l10n_es_vat_book_igic/README.rst
  l10n_es_vat_book_igic/__init__.py
  l10n_es_vat_book_igic/__manifest__.py
  l10n_es_vat_book_igic/data/atc_vat_book_igic_map_data.xml
  l10n_es_vat_book_igic/readme/CONFIGURE.rst
  l10n_es_vat_book_igic/readme/CONTRIBUTORS.rst
  l10n_es_vat_book_igic/readme/DESCRIPTION.rst
  l10n_es_vat_book_igic/readme/INSTALL.rst
  l10n_es_vat_book_igic/readme/USAGE.rst
  l10n_es_vat_book_igic/static/description/icon.png
  l10n_es_vat_book_igic/static/description/index.html
  setup/l10n_es_vat_book_igic/odoo/addons/l10n_es_vat_book_igic
  setup/l10n_es_vat_book_igic/setup.py
Labels: bot is merging ⏳

#3267 [16.0][FIX] l10n_es_aeat_mod349: refund intermediate periods
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
Labels: approved, ready to merge, bot is merging ⏳

#3362 [15.0][FIX] l10n_es_aeat_sii_oca: Avoid singleton error on invoice posting
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#3364 [16.0][FIX] l10n_es_aeat_sii_oca: Avoid singleton error on invoice posting
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#3363 [15.0][FIX] l10n_es_aeat_sii_oca: Crash on sending cancellation to SII
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#3367 [15.0][FIX] l10n_es_aeat_mod347: Add food taxes to the model
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
Labels: bot is merging ⏳

#3368 [16.0][FIX] l10n_es_aeat_mod347: Add food taxes to the model
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
Labels: bot is merging ⏳

#3369 [14.0][FIX] l10n_es_aeat_mod347: Add food taxes to the model
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
Labels: bot is merging ⏳

#3371 [13.0][FIX] l10n_es_aeat_mod347: Add food taxes to the model
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
Labels: bot is merging ⏳

#3374 [16.0][IMP] l10n_es_aeat_mod390: Add 2023 version
  l10n_es_aeat_mod390/README.rst
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod390/static/description/index.html
Labels: bot is merging ⏳

#3375 [15.0][IMP] l10n_es_aeat_mod390: Add 2023 version
  l10n_es_aeat_mod390/README.rst
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod390/static/description/index.html
Labels: bot is merging ⏳

#3376 [14.0][IMP] l10n_es_aeat_mod390: Add 2023 version
  l10n_es_aeat_mod390/README.rst
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod390/static/description/index.html
Labels: bot is merging ⏳

#3377 [13.0][IMP] l10n_es_aeat_mod390: Add 2023 version
  l10n_es_aeat_mod390/README.rst
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod390/static/description/index.html
Labels: bot is merging ⏳

#3373 [15.0][IMP] l10n_es_aeat_sii_oca: show account registration date
  l10n_es_aeat_sii_oca/views/account_move_views.xml
Labels: bot is merging ⏳

#3379 [16.0][IMP] l10n_es_aeat_sii_oca: show account registration date
  l10n_es_aeat_sii_oca/views/account_move_views.xml
Labels: bot is merging ⏳

#3384 [16.0][IMP] l10n_es_aeat_report: Aeat reports sorted by date start
  l10n_es_aeat/models/l10n_es_aeat_report.py
  l10n_es_aeat/views/aeat_report_view.xml
Labels: approved, bot is merging ⏳

#3401 [FIX] l10n_es_facturae_face: upgrade zeep and its mocks
  l10n_es_facturae_face/README.rst
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/components/webservice_face.py
  l10n_es_facturae_face/readme/CONTRIBUTORS.rst
  l10n_es_facturae_face/static/description/index.html
  l10n_es_facturae_face/tests/test_facturae_face.py
  requirements.txt
Labels: approved, bot is merging ⏳

#3394 [FIX] l10n_es_aeat_mod190: allow partner access for non-accounting users
  l10n_es_aeat_mod190/views/partner_view.xml
Labels: approved, bot is merging ⏳

#3410 [15.0][FIX] l10n_es_facturae_face: Use Prod for testing
  l10n_es_facturae_face/data/face_data.xml
Labels: bot is merging ⏳

#3412 [14.0][FIX] l10n_es_facturae_face: Use Prod for testing
  l10n_es_facturae_face/data/face_data.xml
Labels: bot is merging ⏳

#3413 [13.0][FIX] l10n_es_facturae_face: Use Prod for testing
  l10n_es_facturae_face/data/face_data.xml
Labels: bot is merging ⏳

#3414 [12.0][FIX] l10n_es_facturae_face: Use Prod for testing
  l10n_es_facturae_face/data/face_data.xml
Labels: bot is merging ⏳

#3415 [11.0][FIX] l10n_es_facturae_face: Use Prod for testing
  l10n_es_facturae_face/data/face_data.xml
Labels: bot is merging ⏳

#3411 [16.0][FIX] l10n_es_facturae_face: Use Prod for testing
  l10n_es_aeat/README.rst
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat/static/description/index.html
  l10n_es_facturae/README.rst
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae/static/description/index.html
  l10n_es_facturae_face/README.rst
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/components/webservice_face.py
  l10n_es_facturae_face/data/face_data.xml
  l10n_es_facturae_face/readme/CONTRIBUTORS.rst
  l10n_es_facturae_face/static/description/index.html
  l10n_es_facturae_face/tests/test_facturae_face.py
  requirements.txt
Labels: bot is merging ⏳

#3393 [14.0][IMP] l10n_es_aeat_mod390: Soporte 5% IVA soportado (bienes corrientes) + Soporte 0%
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/models/mod390.py
Labels: approved, ready to merge, bot is merging ⏳

#3418 [15.0][IMP] l10n_es_aeat_mod390: Include new food taxes
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/models/mod390.py
Labels: bot is merging ⏳

#3419 [16.0][IMP] l10n_es_aeat_mod390: Include new food taxes
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/models/mod390.py
Labels: bot is merging ⏳

#3392 [15.0][IMP] l10n_es_aeat_mod347: Add more optional fields in partner_record tree view
  l10n_es_aeat_mod347/views/mod347_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3397 [15.0][BP] l10n_es_aeat: Order by date start
  l10n_es_aeat/models/l10n_es_aeat_report.py
  l10n_es_aeat/views/aeat_report_view.xml
Labels: bot is merging ⏳
