Repository OCA/l10n-spain, pull requests merged in 2024-10, with the labels that each got.

#3735 [16.0][FIX] l10n_es_partner: Fix vista formulario banco
  l10n_es_partner/views/res_bank_view.xml
Labels: approved, bot is merging ⏳

#3749 [17.0][MIG] l10n_es_payment_order_confirming_aef: Migration to 17.0
  l10n_es_payment_order_confirming_aef/README.rst
  l10n_es_payment_order_confirming_aef/__init__.py
  l10n_es_payment_order_confirming_aef/__manifest__.py
  l10n_es_payment_order_confirming_aef/data/account_payment_method.xml
  l10n_es_payment_order_confirming_aef/i18n/es.po
  l10n_es_payment_order_confirming_aef/i18n/l10n_es_payment_order_confirming_aef.pot
  l10n_es_payment_order_confirming_aef/models/__init__.py
  l10n_es_payment_order_confirming_aef/models/account_payment_method.py
  l10n_es_payment_order_confirming_aef/models/account_payment_mode.py
  l10n_es_payment_order_confirming_aef/models/account_payment_order.py
  l10n_es_payment_order_confirming_aef/models/confirming_aef.py
  l10n_es_payment_order_confirming_aef/pyproject.toml
  l10n_es_payment_order_confirming_aef/readme/CONFIGURE.md
  l10n_es_payment_order_confirming_aef/readme/CONTRIBUTORS.md
  l10n_es_payment_order_confirming_aef/readme/DESCRIPTION.md
  l10n_es_payment_order_confirming_aef/readme/USAGE.md
  l10n_es_payment_order_confirming_aef/static/description/icon.png
  l10n_es_payment_order_confirming_aef/static/description/index.html
  l10n_es_payment_order_confirming_aef/tests/__init__.py
  l10n_es_payment_order_confirming_aef/tests/test_payment_order_confirming_aef.py
  l10n_es_payment_order_confirming_aef/views/account_payment_mode_view.xml
Labels: bot is merging ⏳

#3748 [17.0] [MIG] l10n_es_reav: Migration to 17.0
  l10n_es_reav/README.rst
  l10n_es_reav/__init__.py
  l10n_es_reav/__manifest__.py
  l10n_es_reav/data/template/account.fiscal.position-es_common.csv
  l10n_es_reav/data/template/account.tax-es_common.csv
  l10n_es_reav/data/template/account.tax.group-es_common.csv
  l10n_es_reav/i18n/es.po
  l10n_es_reav/i18n/l10n_es_reav.pot
  l10n_es_reav/models/__init__.py
  l10n_es_reav/models/account_chart_template.py
  l10n_es_reav/pyproject.toml
  l10n_es_reav/readme/CONFIGURE.md
  l10n_es_reav/readme/CONTRIBUTORS.md
  l10n_es_reav/readme/DESCRIPTION.md
  l10n_es_reav/readme/USAGE.md
  l10n_es_reav/static/description/icon.png
  l10n_es_reav/static/description/index.html
  setup/l10n_es_reav/odoo/addons/l10n_es_reav
  setup/l10n_es_reav/setup.py
Labels: merged 🎉

#3752 [14.0][ADD] l10n_es_extra_data: nuevos impuestos no soportados por Odoo Oficial
  l10n_es_extra_data/README.rst
  l10n_es_extra_data/__init__.py
  l10n_es_extra_data/__manifest__.py
  l10n_es_extra_data/data/account_data.xml
  l10n_es_extra_data/data/account_fiscal_position_template_data.xml
  l10n_es_extra_data/data/account_tax_data.xml
  l10n_es_extra_data/i18n/l10n_es_extra_data.pot
  l10n_es_extra_data/readme/CONTRIBUTORS.rst
  l10n_es_extra_data/readme/DESCRIPTION.rst
  l10n_es_extra_data/readme/HISTORY.rst
  l10n_es_extra_data/readme/USAGE.rst
  l10n_es_extra_data/static/description/icon.png
  l10n_es_extra_data/static/description/index.html
  setup/l10n_es_extra_data/odoo/addons/l10n_es_extra_data
  setup/l10n_es_extra_data/setup.py
Labels: approved, bot is merging ⏳

#3755 [15.0][IMP] l10n_es_aeat_mod303: New declaration format for 2024-10
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/docs/303_register_design_e15v32.xlsx
  l10n_es_aeat_mod303/docs/DR303e15v34.xlsx
  l10n_es_aeat_mod303/docs/DR303e17v20_04.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_00.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_40.xlsx
  l10n_es_aeat_mod303/docs/DR303e22.xlsx
  l10n_es_aeat_mod303/docs/DR303e24v200.xlsx
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: bot is merging ⏳

#3750 [17.0][FIX] l10n_es_aeat_mod349: Fix tests compatibililty with account_edi_ubl_cii
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
Labels: bot is merging ⏳

#3758 [15.0][FIX] l10n_es_aeat_sii_oca: Take into account inactive tax templates
  l10n_es_aeat_sii_oca/models/sii_mixin.py
  l10n_es_aeat_sii_oca/views/aeat_sii_map_view.xml
Labels: bot is merging ⏳

#3757 [16.0][IMP] l10n_es_aeat_mod303: New declaration format for 2024-10
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/docs/303_register_design_e15v32.xlsx
  l10n_es_aeat_mod303/docs/DR303e15v34.xlsx
  l10n_es_aeat_mod303/docs/DR303e17v20_04.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_00.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_40.xlsx
  l10n_es_aeat_mod303/docs/DR303e22.xlsx
  l10n_es_aeat_mod303/docs/DR303e24v200.xlsx
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: bot is merging ⏳

#3679 [17.0][MIG] l10n_es_igic: Migration to version 17.0
  l10n_es_igic/README.rst
  l10n_es_igic/__init__.py
  l10n_es_igic/__manifest__.py
  l10n_es_igic/data/template/account.account-es_assec.csv
  l10n_es_igic/data/template/account.account-es_assoc_canary.csv
  l10n_es_igic/data/template/account.account-es_common.csv
  l10n_es_igic/data/template/account.account-es_full_canary.csv
  l10n_es_igic/data/template/account.account-es_pymes_canary.csv
  l10n_es_igic/data/template/account.fiscal.position-es_common.csv
  l10n_es_igic/data/template/account.tax-es_assoc_canary.csv
  l10n_es_igic/data/template/account.tax-es_common.csv
  l10n_es_igic/data/template/account.tax-es_full_canary.csv
  l10n_es_igic/data/template/account.tax-es_pymes_canary.csv
  l10n_es_igic/data/template/account.tax.group-es_common.csv
  l10n_es_igic/i18n/es.po
  l10n_es_igic/i18n/l10n_es_igic.pot
  l10n_es_igic/models/__init__.py
  l10n_es_igic/models/template_es_canary.py
  l10n_es_igic/pyproject.toml
  l10n_es_igic/readme/CONTRIBUTORS.md
  l10n_es_igic/readme/DESCRIPTION.md
  l10n_es_igic/readme/INSTALL.md
  l10n_es_igic/static/description/icon.png
  l10n_es_igic/static/description/index.html
Labels: approved, bot is merging ⏳

#3759 [16.0][FIX] l10n_es_aeat_sii_oca: Take into account inactive tax templates
  l10n_es_aeat_sii_oca/models/sii_mixin.py
  l10n_es_aeat_sii_oca/views/aeat_sii_map_view.xml
Labels: bot is merging ⏳

#3733 [13.0][ADD] l10n_es_extra_data: nuevos impuestos no soportados por Odoo Oficial
  l10n_es_extra_data/README.rst
  l10n_es_extra_data/__init__.py
  l10n_es_extra_data/__manifest__.py
  l10n_es_extra_data/data/account_data.xml
  l10n_es_extra_data/data/account_fiscal_position_template_data.xml
  l10n_es_extra_data/data/account_tax_data.xml
  l10n_es_extra_data/i18n/l10n_es_extra_data.pot
  l10n_es_extra_data/readme/CONTRIBUTORS.rst
  l10n_es_extra_data/readme/DESCRIPTION.rst
  l10n_es_extra_data/readme/HISTORY.rst
  l10n_es_extra_data/readme/USAGE.rst
  l10n_es_extra_data/static/description/icon.png
  l10n_es_extra_data/static/description/index.html
  setup/l10n_es_extra_data/odoo/addons/l10n_es_extra_data
  setup/l10n_es_extra_data/setup.py
Labels: bot is merging ⏳

#3763 [17.0][IMP] l10n_es_partner_mercantil: Remove DeprecationWarning: XML declarations in HTML module descriptions
  l10n_es_partner_mercantil/static/description/index.html
Labels: bot is merging ⏳

#3764 [17.0][IMP] l10n_es_payment_order_confirming_sabadell + l10n_es_payment_order_confirming_aef: Remove WARNING Two fields have the same label
  l10n_es_payment_order_confirming_aef/models/account_payment_mode.py
  l10n_es_payment_order_confirming_aef/views/account_payment_mode_view.xml
  l10n_es_payment_order_confirming_sabadell/models/account_payment_mode.py
  l10n_es_payment_order_confirming_sabadell/views/account_payment_mode_view.xml
Labels: bot is merging ⏳

#3765 [16.0][IMP] l10n_es_aeat_mod303: Mark the box only on complementary declarations
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
Labels: bot is merging ⏳

#3766 [17.0][IMP] l10n_es_aeat_mod303: Mark the box only on complementary declarations
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
Labels: bot is merging ⏳

#3767 [15.0][IMP] l10n_es_aeat_mod303: Mark the box only on complementary declarations
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
Labels: bot is merging ⏳

#3761 [14.0][FIX] l10n_es_mod303: Backports to reach New Declaration format for 2024-10
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/docs/303_register_design_e15v32.xlsx
  l10n_es_aeat_mod303/docs/DR303e15v34.xlsx
  l10n_es_aeat_mod303/docs/DR303e17v20_04.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_00.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_40.xlsx
  l10n_es_aeat_mod303/docs/DR303e22.xlsx
  l10n_es_aeat_mod303/docs/DR303e24v200.xlsx
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: approved, bot is merging ⏳

#3747 [16.0][IMP] l10n_es_igic: Add 5% reduced VAT
  l10n_es_igic/data/account_fiscal_position_template_canary_data.xml
  l10n_es_igic/data/account_tax_data.xml
  l10n_es_igic/data/account_tax_group_data.xml
  l10n_es_igic/i18n/es.po
  l10n_es_igic/i18n/l10n_es_igic.pot
Labels: approved, ready to merge, bot is merging ⏳

#3771 [17.0][FIX] l10n_es_igic: Corregidos impuestos Comercio Minorista
  l10n_es_igic/data/template/account.tax-es_assoc_canary.csv
  l10n_es_igic/data/template/account.tax-es_full_canary.csv
  l10n_es_igic/data/template/account.tax-es_pymes_canary.csv
Labels: approved, bot is merging ⏳

#3734 [12.0][IMP] l10n_es_extra_data: Nuevos impuestos no soportados por Odoo Oficial
  l10n_es_extra_data/README.rst
  l10n_es_extra_data/data/account_data.xml
  l10n_es_extra_data/data/account_fiscal_position_template_data.xml
  l10n_es_extra_data/data/account_tax_data.xml
  l10n_es_extra_data/i18n/l10n_es_extra_data.po
  l10n_es_extra_data/readme/CONTRIBUTORS.rst
  l10n_es_extra_data/static/description/index.html
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#3782 [15.0][FIX] l10n_es_payment_order_confirming_aef: Fix search domain confirming payment method in bank journal
  l10n_es_payment_order_confirming_aef/models/__init__.py
  l10n_es_payment_order_confirming_aef/models/account_payment_method.py
Labels: bot is merging ⏳

#3789 [15.0][FIX] l10n_es_aeat_mod190
  l10n_es_aeat_mod190/README.rst
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
  l10n_es_aeat_mod190/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod190/static/description/index.html
Labels: bot is merging ⏳

#3505 [15.0][ADD] l10n_es_aeat_mod592: Declaración impuestos al plástico
  l10n_es_aeat_mod592/README.rst
  l10n_es_aeat_mod592/__init__.py
  l10n_es_aeat_mod592/__manifest__.py
  l10n_es_aeat_mod592/data/ir_sequence_data.xml
  l10n_es_aeat_mod592/docs/Contabilidad_libro.pdf
  l10n_es_aeat_mod592/docs/Rég. Fiscal Adquir. y Repres. (ADSIPLRA).csv
  l10n_es_aeat_mod592/docs/Régimen Fiscal Fabricantes (ADSIPLRF).csv
  l10n_es_aeat_mod592/docs/plastico_campos_impfichero.xlsx
  l10n_es_aeat_mod592/docs/plastico_doc_impfichero.pdf
  l10n_es_aeat_mod592/i18n/es.po
  l10n_es_aeat_mod592/i18n/l10n_es_aeat_mod592.pot
  l10n_es_aeat_mod592/models/__init__.py
  l10n_es_aeat_mod592/models/misc.py
  l10n_es_aeat_mod592/models/mod592.py
  l10n_es_aeat_mod592/models/mod592_acquirer.py
  l10n_es_aeat_mod592/models/mod592_line_mixin.py
  l10n_es_aeat_mod592/models/mod592_manufacturer.py
  l10n_es_aeat_mod592/models/product_product.py
  l10n_es_aeat_mod592/models/product_template.py
  l10n_es_aeat_mod592/models/res_company.py
  l10n_es_aeat_mod592/models/res_partner.py
  l10n_es_aeat_mod592/readme/CONFIGURE.rst
  l10n_es_aeat_mod592/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod592/readme/DESCRIPTION.rst
  l10n_es_aeat_mod592/readme/ROADMAP.rst
  l10n_es_aeat_mod592/readme/USAGE.rst
  l10n_es_aeat_mod592/report/__init__.py
  l10n_es_aeat_mod592/report/aeat_mod592.xml
  l10n_es_aeat_mod592/report/common_templates.xml
  l10n_es_aeat_mod592/report/l10n_es_aeat_mod592_xlsx.py
  l10n_es_aeat_mod592/report/report_views.xml
  l10n_es_aeat_mod592/security/aeat_security.xml
  l10n_es_aeat_mod592/security/ir.model.access.csv
  l10n_es_aeat_mod592/static/description/icon.png
  l10n_es_aeat_mod592/static/description/icon_source.svg
  l10n_es_aeat_mod592/static/description/index.html
  l10n_es_aeat_mod592/tests/__init__.py
  l10n_es_aeat_mod592/tests/test_l10n_es_aeat_mod592.py
  l10n_es_aeat_mod592/views/mod592_acquirer_line_views.xml
  l10n_es_aeat_mod592/views/mod592_manufacturer_line_views.xml
  l10n_es_aeat_mod592/views/mod592_views.xml
  l10n_es_aeat_mod592/views/product_template_views.xml
  l10n_es_aeat_mod592/views/res_company_views.xml
  l10n_es_aeat_mod592/views/res_partner_views.xml
  setup/l10n_es_aeat_mod592/odoo/addons/l10n_es_aeat_mod592
  setup/l10n_es_aeat_mod592/setup.py
Labels: bot is merging ⏳

#3778 [16.0][IMP] l10n_es_igic: Usar método division en impuestos de minorista
  l10n_es_igic/data/account_tax_data.xml
Labels: approved, ready to merge, bot is merging ⏳

#3791 [16.0][FIX] l10n_es_irnr: Assign core tax_groups to taxes that had template…
  l10n_es_irnr/__manifest__.py
  l10n_es_irnr/migrations/16.0.1.2.1/pre-migration.py
  l10n_es_irnr/static/description/index.html
Labels: bot is merging ⏳

#3792 [IMP][12.0] l10n_es_aeat_mod390: Add 2023 version
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/aeat_export_mod390_2021_main_data.xml
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#3437 [15.0][IMP] l10n_es_facturae: Change facturae to commercial field
  l10n_es_facturae/README.rst
  l10n_es_facturae/data/Facturaev3_2.xsd
  l10n_es_facturae/data/Facturaev3_2_1.xsd
  l10n_es_facturae/data/Facturaev3_2_2.xsd
  l10n_es_facturae/migrations/15.0.1.10.0/pre-migration.py
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/models/res_partner.py
  l10n_es_facturae/readme/CONTRIBUTORS.rst
  l10n_es_facturae/static/description/index.html
  l10n_es_facturae/tests/common.py
  l10n_es_facturae/views/report_facturae.xml
  l10n_es_facturae/views/res_partner_view.xml
  l10n_es_facturae_face/i18n/es.po
  l10n_es_facturae_face/i18n/l10n_es_facturae_face.pot
  l10n_es_facturae_face/models/account_move.py
  l10n_es_facturae_face/tests/test_facturae_face.py
Labels: approved, ready to merge, bot is merging ⏳

#3777 [16.0][IMP] payment_redsys: remove website_sale dependency
  payment_redsys/__manifest__.py
  payment_redsys/models/payment_provider.py
Labels: approved, bot is merging ⏳

#3795 [17.0][FIX] l10n_es_aeat_mod303: casilla 17 modelo 2024-10
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
Labels: bot is merging ⏳

#3796 [15.0][FIX] l10n_es_aeat_mod303: casilla 17 modelo 2024-10
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
Labels: bot is merging ⏳
