Repository OCA/l10n-spain, pull requests merged in 2024-03, with the labels that each got.

#3320 [16.0][MIG] delivery_gls_asm: Migration to 16.0
  delivery_gls_asm/README.rst
  delivery_gls_asm/__init__.py
  delivery_gls_asm/__manifest__.py
  delivery_gls_asm/api/gls_asm_api.wsdl
  delivery_gls_asm/data/delivery_asm_data.xml
  delivery_gls_asm/i18n/ca.po
  delivery_gls_asm/i18n/delivery_gls_asm.pot
  delivery_gls_asm/i18n/es.po
  delivery_gls_asm/models/__init__.py
  delivery_gls_asm/models/delivery_carrier.py
  delivery_gls_asm/models/gls_asm_master_data.py
  delivery_gls_asm/models/gls_asm_request.py
  delivery_gls_asm/models/stock_picking.py
  delivery_gls_asm/readme/CONFIGURE.rst
  delivery_gls_asm/readme/CONTRIBUTORS.rst
  delivery_gls_asm/readme/DESCRIPTION.rst
  delivery_gls_asm/readme/INSTALL.rst
  delivery_gls_asm/readme/ROADMAP.rst
  delivery_gls_asm/readme/USAGE.rst
  delivery_gls_asm/security/ir.model.access.csv
  delivery_gls_asm/static/description/icon.png
  delivery_gls_asm/static/description/icon.svg
  delivery_gls_asm/static/description/index.html
  delivery_gls_asm/tests/__init__.py
  delivery_gls_asm/tests/test_delivery_gls_asm.py
  delivery_gls_asm/views/delivery_asm_view.xml
  delivery_gls_asm/views/gls_asm_manifest_template.xml
  delivery_gls_asm/views/stock_picking_views.xml
  delivery_gls_asm/wizard/__init__.py
  delivery_gls_asm/wizard/gls_asm_manifest_wizard.py
  delivery_gls_asm/wizard/gls_asm_manifest_wizard_views.xml
  requirements.txt
  setup/delivery_gls_asm/odoo/addons/delivery_gls_asm
  setup/delivery_gls_asm/setup.py
Labels: approved, bot is merging ⏳

#3122 [13.0][FIX] l10n_es_aeat_mod347: Multicompany report and mail
  l10n_es_aeat_mod347/__manifest__.py
  l10n_es_aeat_mod347/migrations/13.0.2.5.0/post-migration.py
  l10n_es_aeat_mod347/models/mod347.py
Labels: bot is merging ⏳, stale

#3464 [14.0][FIX] l10n_es_payment_order_confirming_aef: Make test resilient
  l10n_es_payment_order_confirming_aef/tests/test_payment_order_confirming_aef.py
Labels: bot is merging ⏳

#3465 [15.0][FIX] l10n_es_payment_order_confirming_aef: Make test resilient
  l10n_es_payment_order_confirming_aef/tests/test_payment_order_confirming_aef.py
Labels: bot is merging ⏳

#3466 [16.0][FIX] l10n_es_payment_order_confirming_aef: Make test resilient
  l10n_es_payment_order_confirming_aef/tests/test_payment_order_confirming_aef.py
Labels: bot is merging ⏳

#3463 [15.0][FIX] l10n_es_ticketbai_batuz: Fecha factura rectificada se pasa a te…
  l10n_es_ticketbai_batuz/models/account_move.py
Labels: bot is merging ⏳

#3467 [14.0][FIX] l10n_es_aeat_mod347: Don't abs the partner volume
  l10n_es_aeat_mod347/data/aeat_export_mod347_partner_data.xml
Labels: bot is merging ⏳

#3081 [16.0][ADD] l10n_es_aeat_mod347_igic
  l10n_es_aeat_mod347_igic/README.rst
  l10n_es_aeat_mod347_igic/__init__.py
  l10n_es_aeat_mod347_igic/__manifest__.py
  l10n_es_aeat_mod347_igic/data/tax_code_map_mod347_igic_data.xml
  l10n_es_aeat_mod347_igic/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod347_igic/readme/DESCRIPTION.rst
  l10n_es_aeat_mod347_igic/readme/INSTALL.rst
  l10n_es_aeat_mod347_igic/static/description/icon.png
  l10n_es_aeat_mod347_igic/static/description/index.html
  setup/l10n_es_aeat_mod347_igic/odoo/addons/l10n_es_aeat_mod347_igic
  setup/l10n_es_aeat_mod347_igic/setup.py
Labels: bot is merging ⏳

#3470 [15.0][FIX] l10n_es_aeat_mod347: Don't abs the partner volume
  l10n_es_aeat_mod347/data/aeat_export_mod347_partner_data.xml
Labels: bot is merging ⏳

#3444 [16.0][MIG] l10n_es_payment_order_confirming_sabadell: Migration to 16.0
  l10n_es_payment_order_confirming_sabadell/README.rst
  l10n_es_payment_order_confirming_sabadell/__init__.py
  l10n_es_payment_order_confirming_sabadell/__manifest__.py
  l10n_es_payment_order_confirming_sabadell/data/account_payment_method.xml
  l10n_es_payment_order_confirming_sabadell/i18n/ca.po
  l10n_es_payment_order_confirming_sabadell/i18n/es.po
  l10n_es_payment_order_confirming_sabadell/i18n/l10n_es_payment_order_confirming_sabadell.pot
  l10n_es_payment_order_confirming_sabadell/models/__init__.py
  l10n_es_payment_order_confirming_sabadell/models/account_payment_mode.py
  l10n_es_payment_order_confirming_sabadell/models/account_payment_order.py
  l10n_es_payment_order_confirming_sabadell/models/confirming_sabadell.py
  l10n_es_payment_order_confirming_sabadell/readme/CONFIGURE.rst
  l10n_es_payment_order_confirming_sabadell/readme/CONTRIBUTORS.rst
  l10n_es_payment_order_confirming_sabadell/readme/DESCRIPTION.rst
  l10n_es_payment_order_confirming_sabadell/readme/USAGE.rst
  l10n_es_payment_order_confirming_sabadell/static/description/icon.png
  l10n_es_payment_order_confirming_sabadell/static/description/index.html
  l10n_es_payment_order_confirming_sabadell/tests/__init__.py
  l10n_es_payment_order_confirming_sabadell/tests/test_payment_order_confirming_sabadell.py
  l10n_es_payment_order_confirming_sabadell/views/account_payment_mode_view.xml
  setup/l10n_es_payment_order_confirming_sabadell/odoo/addons/l10n_es_payment_order_confirming_sabadell
  setup/l10n_es_payment_order_confirming_sabadell/setup.py
Labels: approved, bot is merging ⏳

#3473 [16.0][FIX] l10n_es_aeat_sii_match: Check company when choosing certs
  l10n_es_aeat_sii_match/models/aeat_sii_match_report.py
Labels: approved, bot is merging ⏳

#3145 [15.0][FIX] l10n_es_pos_sii: default partner y roadmap.
  l10n_es_pos_sii/models/pos_order.py
  l10n_es_pos_sii/readme/ROADMAP.rst
Labels: approved, bot is merging ⏳, stale

#3477 [12.0][IMP] l10n_es_aeat_mod216: IRPF No residentes exento por convenio
  l10n_es_aeat_mod216/__manifest__.py
  l10n_es_aeat_mod216/data/tax_code_map_mod216_data.xml
  l10n_es_aeat_mod216/tests/test_l10n_es_aeat_mod216.py
  l10n_es_irnr/__manifest__.py
  l10n_es_irnr/data/fiscal_position_taxes_irnr.xml
  l10n_es_irnr/data/fiscal_positions_irnr.xml
  l10n_es_irnr/data/taxes_irnr.xml
Labels: bot is merging ⏳

#3481 [16.0][FIX] l10n_es_intrastat_report: Adapt to changes on confirmation
  l10n_es_intrastat_report/tests/test_l10n_es_intrastat_report.py
Labels: bot is merging ⏳

#3471 [16.0][FIX] l10n_es_aeat_mod347: Don't abs the partner volume
  l10n_es_aeat_mod347/data/aeat_export_mod347_partner_data.xml
Labels: bot is merging ⏳

#3476 [16.0] [IMP] l10n_es_sigaus_sale: Make sigaus line non invoicible
  l10n_es_sigaus_sale/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#3486 [17.0][MIG] l10n_es_aeat_mod303: Migration to version 17.0
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/__init__.py
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.account.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod303/data/l10n.es.aeat.mod303.report.activity.code.csv
  l10n_es_aeat_mod303/docs/303_register_design_e15v32.xlsx
  l10n_es_aeat_mod303/docs/DR303e15v34.xlsx
  l10n_es_aeat_mod303/docs/DR303e17v20_04.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_00.xlsx
  l10n_es_aeat_mod303/docs/DR303e18v10_40.xlsx
  l10n_es_aeat_mod303/docs/DR303e22.xlsx
  l10n_es_aeat_mod303/docs/DR303e23.xlsx
  l10n_es_aeat_mod303/i18n/bg.po
  l10n_es_aeat_mod303/i18n/ca.po
  l10n_es_aeat_mod303/i18n/cs.po
  l10n_es_aeat_mod303/i18n/de.po
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/es_CO.po
  l10n_es_aeat_mod303/i18n/es_CR.po
  l10n_es_aeat_mod303/i18n/eu.po
  l10n_es_aeat_mod303/i18n/fr.po
  l10n_es_aeat_mod303/i18n/gl.po
  l10n_es_aeat_mod303/i18n/hr.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/i18n/nl.po
  l10n_es_aeat_mod303/i18n/pl.po
  l10n_es_aeat_mod303/i18n/pt.po
  l10n_es_aeat_mod303/i18n/pt_BR.po
  l10n_es_aeat_mod303/i18n/sl.po
  l10n_es_aeat_mod303/i18n/sv.po
  l10n_es_aeat_mod303/i18n/tr.po
  l10n_es_aeat_mod303/i18n/vi.po
  l10n_es_aeat_mod303/models/__init__.py
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/pyproject.toml
  l10n_es_aeat_mod303/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod303/readme/DESCRIPTION.md
  l10n_es_aeat_mod303/readme/ROADMAP.md
  l10n_es_aeat_mod303/security/ir.model.access.csv
  l10n_es_aeat_mod303/security/l10n_es_aeat_mod303_security.xml
  l10n_es_aeat_mod303/static/description/icon.png
  l10n_es_aeat_mod303/static/description/icon_source.svg
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_mod303/tests/__init__.py
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
  l10n_es_aeat_mod303/views/l10n_es_aeat_mod303_report_activity_code_data_views.xml
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: bot is merging ⏳

#3469 [16.0][MIG] l10n_es_pos_by_device: Migration to 16.0
  l10n_es_pos_by_device/README.rst
  l10n_es_pos_by_device/__init__.py
  l10n_es_pos_by_device/__manifest__.py
  l10n_es_pos_by_device/i18n/es.po
  l10n_es_pos_by_device/i18n/l10n_es_pos_by_device.pot
  l10n_es_pos_by_device/models/__init__.py
  l10n_es_pos_by_device/models/pos_config.py
  l10n_es_pos_by_device/models/pos_device.py
  l10n_es_pos_by_device/models/pos_order.py
  l10n_es_pos_by_device/models/pos_session.py
  l10n_es_pos_by_device/models/res_company.py
  l10n_es_pos_by_device/models/res_config_settings.py
  l10n_es_pos_by_device/readme/CONFIGURE.rst
  l10n_es_pos_by_device/readme/CONTRIBUTORS.rst
  l10n_es_pos_by_device/readme/DESCRIPTION.rst
  l10n_es_pos_by_device/readme/USAGE.rst
  l10n_es_pos_by_device/security/device_security.xml
  l10n_es_pos_by_device/security/ir.model.access.csv
  l10n_es_pos_by_device/static/description/icon.png
  l10n_es_pos_by_device/static/description/index.html
  l10n_es_pos_by_device/static/src/js/PaymentScreen.esm.js
  l10n_es_pos_by_device/static/src/js/Screens/Chrome/Chrome.esm.js
  l10n_es_pos_by_device/static/src/js/Screens/Chrome/DeviceName.esm.js
  l10n_es_pos_by_device/static/src/js/models.esm.js
  l10n_es_pos_by_device/static/src/xml/Screens/Chrome/Chrome.xml
  l10n_es_pos_by_device/static/src/xml/Screens/Chrome/DeviceName.xml
  l10n_es_pos_by_device/views/pos_views.xml
  l10n_es_pos_by_device/views/res_config_views.xml
  setup/l10n_es_pos_by_device/odoo/addons/l10n_es_pos_by_device
  setup/l10n_es_pos_by_device/setup.py
Labels: approved, bot is merging ⏳

#3472 [14.0][FIX] l10n_es_dua_ticketbai_batuz: Correción mapeo impuestos
  l10n_es_dua_ticketbai_batuz/data/tax_code_map_dua_ticketbai_data.xml
Labels: approved, ready to merge, bot is merging ⏳

#3484 [14.0][FIX] l10n_es_aeat_mod303: update map tax line for field number 31.
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#3366 [16.0][ADD] l10n_es_aeat_sii_force_type: module to force "Tipo de Comunicación" for SII
  l10n_es_aeat_sii_force_type/README.rst
  l10n_es_aeat_sii_force_type/__init__.py
  l10n_es_aeat_sii_force_type/__manifest__.py
  l10n_es_aeat_sii_force_type/i18n/es.po
  l10n_es_aeat_sii_force_type/models/__init__.py
  l10n_es_aeat_sii_force_type/models/account_fiscal_position.py
  l10n_es_aeat_sii_force_type/models/account_move.py
  l10n_es_aeat_sii_force_type/readme/CONFIGURE.rst
  l10n_es_aeat_sii_force_type/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_force_type/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_force_type/readme/HISTORY.rst
  l10n_es_aeat_sii_force_type/readme/USAGE.rst
  l10n_es_aeat_sii_force_type/static/description/icon.png
  l10n_es_aeat_sii_force_type/static/description/index.html
  l10n_es_aeat_sii_force_type/tests/__init__.py
  l10n_es_aeat_sii_force_type/tests/test_l10n_es_aeat_sii_force_type.py
  l10n_es_aeat_sii_force_type/views/account_fiscal_position_view.xml
  l10n_es_aeat_sii_force_type/views/account_move_view.xml
  setup/l10n_es_aeat_sii_force_type/odoo/addons/l10n_es_aeat_sii_force_type
  setup/l10n_es_aeat_sii_force_type/setup.py
Labels: approved, bot is merging ⏳

#3492 [14.0][FIX] l10n_es_partner: Bank data download URL + local file fallback
  l10n_es_partner/gen_src/REGBANESP_CONESTAB_A.xls
  l10n_es_partner/wizard/l10n_es_partner_wizard.py
Labels: bot is merging ⏳

#3493 [14.0][FIX] l10n_es_partner: Change tools.file_path to tools.file_open in wiizard (for except)
  l10n_es_partner/wizard/l10n_es_partner_wizard.py
Labels: bot is merging ⏳

#3488 [17.0][MIG] l10n_es_aeat_mod111: Migration to version 17.0
  l10n_es_aeat_mod111/README.rst
  l10n_es_aeat_mod111/__init__.py
  l10n_es_aeat_mod111/__manifest__.py
  l10n_es_aeat_mod111/data/aeat_export_mod111_data.xml
  l10n_es_aeat_mod111/data/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod111/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod111/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod111/docs/dr111e16v17.xls
  l10n_es_aeat_mod111/i18n/bg.po
  l10n_es_aeat_mod111/i18n/ca.po
  l10n_es_aeat_mod111/i18n/cs.po
  l10n_es_aeat_mod111/i18n/de.po
  l10n_es_aeat_mod111/i18n/es.po
  l10n_es_aeat_mod111/i18n/es_CO.po
  l10n_es_aeat_mod111/i18n/es_CR.po
  l10n_es_aeat_mod111/i18n/es_ES.po
  l10n_es_aeat_mod111/i18n/eu.po
  l10n_es_aeat_mod111/i18n/fr.po
  l10n_es_aeat_mod111/i18n/gl.po
  l10n_es_aeat_mod111/i18n/hr.po
  l10n_es_aeat_mod111/i18n/l10n_es_aeat_mod111.pot
  l10n_es_aeat_mod111/i18n/nl.po
  l10n_es_aeat_mod111/i18n/pl.po
  l10n_es_aeat_mod111/i18n/pt.po
  l10n_es_aeat_mod111/i18n/pt_BR.po
  l10n_es_aeat_mod111/i18n/ru.po
  l10n_es_aeat_mod111/i18n/sl.po
  l10n_es_aeat_mod111/i18n/sv.po
  l10n_es_aeat_mod111/i18n/tr.po
  l10n_es_aeat_mod111/i18n/vi.po
  l10n_es_aeat_mod111/models/__init__.py
  l10n_es_aeat_mod111/models/mod111.py
  l10n_es_aeat_mod111/pyproject.toml
  l10n_es_aeat_mod111/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod111/readme/DESCRIPTION.md
  l10n_es_aeat_mod111/readme/ROADMAP.md
  l10n_es_aeat_mod111/readme/USAGE.md
  l10n_es_aeat_mod111/security/ir.model.access.csv
  l10n_es_aeat_mod111/security/l10n_es_aeat_mod111_security.xml
  l10n_es_aeat_mod111/static/description/icon.png
  l10n_es_aeat_mod111/static/description/icon_source.svg
  l10n_es_aeat_mod111/static/description/index.html
  l10n_es_aeat_mod111/tests/__init__.py
  l10n_es_aeat_mod111/tests/test_l10n_es_aeat_mod111.py
  l10n_es_aeat_mod111/views/mod111_view.xml
Labels: approved, bot is merging ⏳

#3494 [15.0][FIX] l10n_es_aeat_mod303: update map tax line for field number 31.
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
Labels: approved, bot is merging ⏳

#3495 [16.0][FIX] l10n_es_aeat_mod303: update map tax line for field number 31.
  l10n_es_aeat_mod303/data/2021-07/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#3499 [17.0][FIX] l10n_es_aeat_mod303: update map tax line for field number 31
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#3169 [13.0][OU-ADD]l10n_es_ticketbai_batuz-migration-script
  l10n_es_ticketbai_batuz/migrations/13.0.1.0.0/post-migration.py
  l10n_es_ticketbai_batuz/migrations/13.0.1.0.0/pre-migration.py
Labels: stale

#2975 [13.0][OU-ADD]l10n_es_ticketbai-migration-script
  l10n_es_ticketbai/migrations/13.0.1.0.0/post-migration.py
  l10n_es_ticketbai/migrations/13.0.1.0.0/pre-migration.py
Labels: stale

#3501 [16.0][IMP] l10n_es_sigaus_purchase: Calculate SIGAUS when using write/create methods in purchase.order.line
  l10n_es_sigaus_purchase/models/purchase_order.py
  l10n_es_sigaus_purchase/models/purchase_order_line.py
  l10n_es_sigaus_purchase/tests/test_l10n_es_sigaus_purchase.py
Labels: approved, bot is merging ⏳

#3502 [15.0][FIX] delivery_seur: prevent division by 0
  delivery_seur/models/seur_request.py
Labels: bot is merging ⏳

#3487 [12.0][ADD] l10n_es_ticketbai_oss: Add OSS support for TicketBai
  l10n_es_ticketbai_oss/README.rst
  l10n_es_ticketbai_oss/__init__.py
  l10n_es_ticketbai_oss/__manifest__.py
  l10n_es_ticketbai_oss/i18n/es.po
  l10n_es_ticketbai_oss/i18n/eu_ES.po
  l10n_es_ticketbai_oss/models/__init__.py
  l10n_es_ticketbai_oss/models/account_invoice_tax.py
  l10n_es_ticketbai_oss/models/account_tax.py
  l10n_es_ticketbai_oss/models/ticketbai_invoice_tax.py
  l10n_es_ticketbai_oss/static/description/icon.png
  l10n_es_ticketbai_oss/tests/__init__.py
  l10n_es_ticketbai_oss/tests/test_invoice_oss.py
  l10n_es_ticketbai_oss/views/account_tax_views.xml
  setup/l10n_es_ticketbai_oss/odoo/addons/l10n_es_ticketbai_oss
  setup/l10n_es_ticketbai_oss/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3439 [16.0][IMP] l10n_es_facturae: Change facturae to commercial field
  l10n_es_facturae/README.rst
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae/data/Facturaev3_2.xsd
  l10n_es_facturae/data/Facturaev3_2_1.xsd
  l10n_es_facturae/data/Facturaev3_2_2.xsd
  l10n_es_facturae/i18n/es.po
  l10n_es_facturae/i18n/l10n_es_facturae.pot
  l10n_es_facturae/migrations/16.0.1.7.0/pre-migration.py
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/models/res_partner.py
  l10n_es_facturae/readme/CONTRIBUTORS.rst
  l10n_es_facturae/static/description/index.html
  l10n_es_facturae/tests/common.py
  l10n_es_facturae/views/report_facturae.xml
  l10n_es_facturae/views/res_partner_view.xml
  l10n_es_facturae_face/i18n/ca.po
  l10n_es_facturae_face/i18n/es.po
  l10n_es_facturae_face/i18n/l10n_es_facturae_face.pot
  l10n_es_facturae_face/models/account_move.py
  l10n_es_facturae_face/tests/test_facturae_face.py
  l10n_es_facturae_face/views/res_partner.xml
Labels: approved, bot is merging ⏳

#3489 [17.0][MIG] l10n_es_aeat_mod347: Migration to version 17.0
  l10n_es_aeat_mod347/README.rst
  l10n_es_aeat_mod347/__init__.py
  l10n_es_aeat_mod347/__manifest__.py
  l10n_es_aeat_mod347/controllers/__init__.py
  l10n_es_aeat_mod347/controllers/main.py
  l10n_es_aeat_mod347/data/aeat_export_mod347_data.xml
  l10n_es_aeat_mod347/data/aeat_export_mod347_partner_data.xml
  l10n_es_aeat_mod347/data/aeat_export_mod347_real_state_data.xml
  l10n_es_aeat_mod347/data/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod347/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod347/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod347/data/mail_template_data.xml
  l10n_es_aeat_mod347/docs/347_register_design.pdf
  l10n_es_aeat_mod347/i18n/bg.po
  l10n_es_aeat_mod347/i18n/ca.po
  l10n_es_aeat_mod347/i18n/cs.po
  l10n_es_aeat_mod347/i18n/es.po
  l10n_es_aeat_mod347/i18n/es_CO.po
  l10n_es_aeat_mod347/i18n/es_CR.po
  l10n_es_aeat_mod347/i18n/eu.po
  l10n_es_aeat_mod347/i18n/fr.po
  l10n_es_aeat_mod347/i18n/gl.po
  l10n_es_aeat_mod347/i18n/hr.po
  l10n_es_aeat_mod347/i18n/l10n_es_aeat_mod347.pot
  l10n_es_aeat_mod347/i18n/nl.po
  l10n_es_aeat_mod347/i18n/pl.po
  l10n_es_aeat_mod347/i18n/pt.po
  l10n_es_aeat_mod347/i18n/pt_BR.po
  l10n_es_aeat_mod347/i18n/ru.po
  l10n_es_aeat_mod347/i18n/sl.po
  l10n_es_aeat_mod347/i18n/sv.po
  l10n_es_aeat_mod347/i18n/tr.po
  l10n_es_aeat_mod347/i18n/vi.po
  l10n_es_aeat_mod347/images/l10n_es_aeat_mod347.png
  l10n_es_aeat_mod347/models/__init__.py
  l10n_es_aeat_mod347/models/account_move.py
  l10n_es_aeat_mod347/models/mod347.py
  l10n_es_aeat_mod347/models/res_partner.py
  l10n_es_aeat_mod347/pyproject.toml
  l10n_es_aeat_mod347/readme/CONFIG.rst
  l10n_es_aeat_mod347/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod347/readme/DESCRIPTION.rst
  l10n_es_aeat_mod347/readme/INSTALL.rst
  l10n_es_aeat_mod347/readme/ROADMAP.rst
  l10n_es_aeat_mod347/readme/USAGE.rst
  l10n_es_aeat_mod347/security/ir.model.access.csv
  l10n_es_aeat_mod347/security/mod_347_security.xml
  l10n_es_aeat_mod347/static/description/icon.png
  l10n_es_aeat_mod347/static/description/icon_source.svg
  l10n_es_aeat_mod347/static/description/index.html
  l10n_es_aeat_mod347/static/src/img/347_bad.svg
  l10n_es_aeat_mod347/static/src/img/347_ok.svg
  l10n_es_aeat_mod347/tests/__init__.py
  l10n_es_aeat_mod347/tests/test_l10n_es_aeat_mod347.py
  l10n_es_aeat_mod347/views/account_move_view.xml
  l10n_es_aeat_mod347/views/mod347_templates.xml
  l10n_es_aeat_mod347/views/mod347_view.xml
  l10n_es_aeat_mod347/views/report_347_partner.xml
  l10n_es_aeat_mod347/views/res_partner_view.xml
Labels: approved, bot is merging ⏳
