Repository OCA/l10n-spain, pull requests merged in 2024-06, with the labels that each got.

#3625 [16.0][IMP] l10n_es_aeat_mod123: New tax 'Retenciones IRPF 19% (Compra consejero de sociedad)' added to tax mapping
  l10n_es_aeat_mod123/data/2024/tax_code_map_mod123.xml
Labels: bot is merging ⏳

#3621 [17.0][IMP]l10n_es_aeat_mod303: add dua taxes
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.tax.csv
Labels: approved, bot is merging ⏳

#3619 [16.0][MIG] l10n_es_location_nuts
  l10n_es_location_nuts/README.rst
  l10n_es_location_nuts/__init__.py
  l10n_es_location_nuts/__manifest__.py
  l10n_es_location_nuts/hooks.py
  l10n_es_location_nuts/i18n/ca.po
  l10n_es_location_nuts/i18n/es.po
  l10n_es_location_nuts/i18n/l10n_es_location_nuts.pot
  l10n_es_location_nuts/readme/CONFIGURE.rst
  l10n_es_location_nuts/readme/CONTRIBUTORS.rst
  l10n_es_location_nuts/readme/DESCRIPTION.rst
  l10n_es_location_nuts/readme/USAGE.rst
  l10n_es_location_nuts/static/description/icon.png
  l10n_es_location_nuts/static/description/index.html
  l10n_es_location_nuts/wizard/__init__.py
  l10n_es_location_nuts/wizard/nuts_import.py
  setup/l10n_es_location_nuts/odoo/addons/l10n_es_location_nuts
  setup/l10n_es_location_nuts/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3630 [17.0 ][FIX] l10n_es_aeat_mod123: Casilla 14 en vista lista
  l10n_es_aeat_mod123/models/mod123.py
  l10n_es_aeat_mod123/tests/test_l10n_es_aeat_mod123.py
  l10n_es_aeat_mod123/views/mod123_view.xml
Labels: bot is merging ⏳

#3613 [15.0][IMP] l10n_es_aeat_mod303: Return last period
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: approved, bot is merging ⏳

#3511 [17.0][MIG] payment_redsys: Migration to 17.0
  payment_redsys/README.rst
  payment_redsys/__init__.py
  payment_redsys/__manifest__.py
  payment_redsys/controllers/__init__.py
  payment_redsys/controllers/main.py
  payment_redsys/data/payment_redsys.xml
  payment_redsys/i18n/bg.po
  payment_redsys/i18n/ca.po
  payment_redsys/i18n/es.po
  payment_redsys/i18n/fr.po
  payment_redsys/i18n/gl.po
  payment_redsys/i18n/hr.po
  payment_redsys/i18n/payment_redsys.pot
  payment_redsys/i18n/pt_BR.po
  payment_redsys/i18n/sl.po
  payment_redsys/models/__init__.py
  payment_redsys/models/account_payment_method.py
  payment_redsys/models/payment_provider.py
  payment_redsys/models/payment_transaction.py
  payment_redsys/pyproject.toml
  payment_redsys/readme/CONFIGURE.md
  payment_redsys/readme/CONTRIBUTORS.md
  payment_redsys/readme/DESCRIPTION.md
  payment_redsys/readme/INSTALL.md
  payment_redsys/readme/ROADMAP.md
  payment_redsys/static/description/icon.png
  payment_redsys/static/description/index.html
  payment_redsys/static/img/bizum.png
  payment_redsys/static/src/img/redsys_icon.png
  payment_redsys/tests/__init__.py
  payment_redsys/tests/common.py
  payment_redsys/tests/test_redsys.py
  payment_redsys/views/payment_provider.xml
  payment_redsys/views/payment_redsys_templates.xml
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#3633 [17.0][MIG] l10n_es_aeat_mod303_vat_prorate: Migration to 17.0
  l10n_es_aeat_mod303_vat_prorate/README.rst
  l10n_es_aeat_mod303_vat_prorate/__init__.py
  l10n_es_aeat_mod303_vat_prorate/__manifest__.py
  l10n_es_aeat_mod303_vat_prorate/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303_vat_prorate/i18n/es.po
  l10n_es_aeat_mod303_vat_prorate/i18n/l10n_es_aeat_mod303_vat_prorate.pot
  l10n_es_aeat_mod303_vat_prorate/models/__init__.py
  l10n_es_aeat_mod303_vat_prorate/models/mod303.py
  l10n_es_aeat_mod303_vat_prorate/pyproject.toml
  l10n_es_aeat_mod303_vat_prorate/readme/CONFIGURE.md
  l10n_es_aeat_mod303_vat_prorate/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod303_vat_prorate/readme/DESCRIPTION.md
  l10n_es_aeat_mod303_vat_prorate/readme/ROADMAP.md
  l10n_es_aeat_mod303_vat_prorate/readme/USAGE.md
  l10n_es_aeat_mod303_vat_prorate/static/description/icon.png
  l10n_es_aeat_mod303_vat_prorate/static/description/index.html
  l10n_es_aeat_mod303_vat_prorate/tests/__init__.py
  l10n_es_aeat_mod303_vat_prorate/tests/test_l10n_es_aeat_mod303_vat_prorate.py
  l10n_es_aeat_mod303_vat_prorate/views/mod303_views.xml
Labels: approved, bot is merging ⏳

#3628 [17.0][IMP] l10n_es_cnae: Translate industries into Spanish
  l10n_es_cnae/README.rst
  l10n_es_cnae/data/res.partner.industry.csv
  l10n_es_cnae/i18n/ca_ES.po
  l10n_es_cnae/i18n/es.po
  l10n_es_cnae/i18n/l10n_es_cnae.pot
  l10n_es_cnae/readme/CONTRIBUTORS.md
  l10n_es_cnae/static/description/index.html
  l10n_es_cnae/tests/__init__.py
  l10n_es_cnae/tests/test_l10n_es_cnae.py
  l10n_es_cnae/wizard/res_partner_industry_eu_nace_wizard.py
Labels: approved, ready to merge, bot is merging ⏳

#3639 [17.0][IMP]l10n_es_aeat_mod390: add dua taxes
  l10n_es_aeat_mod390/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod390/data/l10n.es.aeat.map.tax.line.tax.csv
Labels: approved, bot is merging ⏳

#3640 [17.0][FIX]l10n_ca_cnae: Renombrar módulo a l10n_ca_es_cnae
  l10n_ca_cnae/tests/__init__.py
  l10n_ca_es_cnae/README.rst
  l10n_ca_es_cnae/__init__.py
  l10n_ca_es_cnae/__manifest__.py
  l10n_ca_es_cnae/data/res.partner.industry.cat.csv
  l10n_ca_es_cnae/i18n/ca.po
  l10n_ca_es_cnae/i18n/l10n_ca_cnae.pot
  l10n_ca_es_cnae/i18n/l10n_es_cnae.pot
  l10n_ca_es_cnae/pyproject.toml
  l10n_ca_es_cnae/readme/CONTRIBUTORS.md
  l10n_ca_es_cnae/readme/DESCRIPTION.md
  l10n_ca_es_cnae/readme/INSTALL.md
  l10n_ca_es_cnae/readme/USAGE.md
  l10n_ca_es_cnae/static/description/icon.png
  l10n_ca_es_cnae/static/description/index.html
  l10n_ca_es_cnae/tests/__init__.py
  l10n_ca_es_cnae/tests/test_l10n_ca_es_cnae.py
  l10n_ca_es_cnae/wizard/__init__.py
  l10n_ca_es_cnae/wizard/res_partner_industry_eu_nace_wizard.py
Labels: approved, bot is merging ⏳

#3626 [IMP]l10n_es_vat_prorate: add special vat prorrate
  l10n_es_vat_prorate/README.rst
  l10n_es_vat_prorate/models/account_move.py
  l10n_es_vat_prorate/models/res_company.py
  l10n_es_vat_prorate/readme/CONFIGURE.md
  l10n_es_vat_prorate/readme/CONTRIBUTORS.md
  l10n_es_vat_prorate/static/description/index.html
  l10n_es_vat_prorate/tests/test_vat_prorate.py
  l10n_es_vat_prorate/views/account_move_views.xml
  l10n_es_vat_prorate/views/res_company_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#3332 [14.0][FIX] AEF: Santander pide IBAN entero, incluidos digitos de control
  l10n_es_payment_order_confirming_aef/models/confirming_aef.py
Labels: approved, bot is merging ⏳

#3623 [15.0][IMP+FIX] l10n_es_payment_order_confirming_aef: Cambios en archivo de confirming
  l10n_es_payment_order_confirming_aef/README.rst
  l10n_es_payment_order_confirming_aef/models/account_payment_mode.py
  l10n_es_payment_order_confirming_aef/models/confirming_aef.py
  l10n_es_payment_order_confirming_aef/readme/CONFIGURE.rst
  l10n_es_payment_order_confirming_aef/static/description/index.html
  l10n_es_payment_order_confirming_aef/views/account_payment_mode_view.xml
Labels: bot is merging ⏳

#3642 [16.0][IMP+FIX] l10n_es_payment_order_confirming_aef: Cambios en archivo de confirming
  l10n_es_payment_order_confirming_aef/README.rst
  l10n_es_payment_order_confirming_aef/models/account_payment_mode.py
  l10n_es_payment_order_confirming_aef/models/confirming_aef.py
  l10n_es_payment_order_confirming_aef/readme/CONFIGURE.rst
  l10n_es_payment_order_confirming_aef/static/description/index.html
  l10n_es_payment_order_confirming_aef/views/account_payment_mode_view.xml
Labels: bot is merging ⏳
