Repository OCA/l10n-spain, pull requests merged in 2024-11, with the labels that each got.

#3530 [13.0][IMP] delivery_gls_asm: Nuevo servicio '96 - BUSINESS PARCEL'
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .oca_hooks.cfg
  .pre-commit-config.yaml
  delivery_gls_asm/models/gls_asm_master_data.py
Labels: approved, bot is merging ⏳, stale

#3797 [14.0][FIX] l10n_es_aeat_mod303: casilla 17 modelo 2024-10
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
Labels: bot is merging ⏳

#3768 [16.0][IMP] l10n_es_atc_mod420: Añadido impuestos comercio minorista y 5%
  l10n_es_atc_mod420/data/tax_code_map_mod420_data.xml
Labels: bot is merging ⏳

#3802 [16.0] l10n_es_facturae: fw ports from v15
  .oca/oca-port/blacklist/l10n_es_facturae.json
  l10n_es_facturae/README.rst
  l10n_es_facturae/models/res_partner.py
  l10n_es_facturae/readme/CONFIGURE.rst
  l10n_es_facturae/readme/USAGE.rst
  l10n_es_facturae/reports/report_facturae.py
  l10n_es_facturae/static/description/index.html
  l10n_es_facturae/views/account_move_view.xml
  l10n_es_facturae/wizard/create_facturae_view.xml
Labels: bot is merging ⏳

#3803 [17.0] l10n_es_facturae: fw ports
  .oca/oca-port/blacklist/l10n_es_facturae.json
  l10n_es_facturae/models/res_partner.py
  l10n_es_facturae/reports/report_facturae.py
  l10n_es_facturae/views/account_move_view.xml
  l10n_es_facturae/wizard/create_facturae_view.xml
Labels: approved, bot is merging ⏳

#3804 [15.0][IMP] payment_redsys: remove website_sale dependency
  payment_redsys/__manifest__.py
Labels: approved, bot is merging ⏳

#3548 [17.0][MIG] l10n_es_pos: Migration to 17.0
  l10n_es_pos_oca/README.rst
  l10n_es_pos_oca/__init__.py
  l10n_es_pos_oca/__manifest__.py
  l10n_es_pos_oca/hooks.py
  l10n_es_pos_oca/i18n/ca.po
  l10n_es_pos_oca/i18n/es.po
  l10n_es_pos_oca/i18n/l10n_es_pos.pot
  l10n_es_pos_oca/models/__init__.py
  l10n_es_pos_oca/models/ir_sequence.py
  l10n_es_pos_oca/models/pos_config.py
  l10n_es_pos_oca/models/pos_order.py
  l10n_es_pos_oca/models/pos_session.py
  l10n_es_pos_oca/pyproject.toml
  l10n_es_pos_oca/readme/CONFIGURE.md
  l10n_es_pos_oca/readme/CONTRIBUTORS.md
  l10n_es_pos_oca/readme/DESCRIPTION.md
  l10n_es_pos_oca/readme/INSTALL.md
  l10n_es_pos_oca/readme/ROADMAP.md
  l10n_es_pos_oca/static/description/icon.png
  l10n_es_pos_oca/static/description/index.html
  l10n_es_pos_oca/static/src/app/screens/payment_screen/payment_screen.esm.js
  l10n_es_pos_oca/static/src/app/screens/receipt_screen/receipt/order_receipt.xml
  l10n_es_pos_oca/static/src/app/screens/receipt_screen/receipt/receipt_header/receipt_header.xml
  l10n_es_pos_oca/static/src/app/screens/ticket_screen/ticket_screen.esm.js
  l10n_es_pos_oca/static/src/app/screens/ticket_screen/ticket_screen.xml
  l10n_es_pos_oca/static/src/app/store/models.esm.js
  l10n_es_pos_oca/static/src/app/store/pos_store.esm.js
  l10n_es_pos_oca/views/pos_views.xml
  l10n_es_pos_oca/views/res_config_settings_views.xml
  l10n_es_pos_oca/wizard/__init__.py
  l10n_es_pos_oca/wizard/res_config_settings.py
Labels: approved, bot is merging ⏳

#3663 [17.0][MIG] l10n_es_intrastat_report
  l10n_es_intrastat_report/README.rst
  l10n_es_intrastat_report/__init__.py
  l10n_es_intrastat_report/__manifest__.py
  l10n_es_intrastat_report/data/Estruc_NC2023.xlsx
  l10n_es_intrastat_report/data/NC_20.xls
  l10n_es_intrastat_report/data/intrastat_transaction.xml
  l10n_es_intrastat_report/hooks.py
  l10n_es_intrastat_report/i18n/ca.po
  l10n_es_intrastat_report/i18n/es.po
  l10n_es_intrastat_report/i18n/l10n_es_intrastat_report.pot
  l10n_es_intrastat_report/models/__init__.py
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
  l10n_es_intrastat_report/models/stock_location.py
  l10n_es_intrastat_report/models/template_es_common.py
  l10n_es_intrastat_report/pyproject.toml
  l10n_es_intrastat_report/readme/CONFIGURE.md
  l10n_es_intrastat_report/readme/CONTRIBUTORS.md
  l10n_es_intrastat_report/readme/DESCRIPTION.md
  l10n_es_intrastat_report/readme/INSTALL.md
  l10n_es_intrastat_report/readme/ROADMAP.md
  l10n_es_intrastat_report/readme/USAGE.md
  l10n_es_intrastat_report/report/__init__.py
  l10n_es_intrastat_report/report/intrastat_product_report_xls.py
  l10n_es_intrastat_report/security/ir.model.access.csv
  l10n_es_intrastat_report/static/description/icon.png
  l10n_es_intrastat_report/static/description/index.html
  l10n_es_intrastat_report/tests/__init__.py
  l10n_es_intrastat_report/tests/test_l10n_es_intrastat_report.py
  l10n_es_intrastat_report/views/l10n_es_intrastat_product.xml
  l10n_es_intrastat_report/wizards/__init__.py
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.py
  l10n_es_intrastat_report/wizards/l10n_es_intrastat_code_import.xml
Labels: approved, bot is merging ⏳

#3815 [16.0][IMP] l10n_es_aeat_mod349: Add mappings for new taxes october 2024
  l10n_es_aeat_mod349/data/aeat_349_map_data.xml
Labels: bot is merging ⏳

#3816 [17.0][IMP] l10n_es_aeat_mod349: Add mappings for new taxes october 2024
  l10n_es_aeat_mod349/data/aeat.349.map.line.csv
  l10n_es_aeat_mod349/data/l10n.es.aeat.map.tax.line.tax.csv
Labels: bot is merging ⏳

#3817 [16.0][FIX] l10n_es_aeat_partner_check: View is not correct
  l10n_es_aeat_partner_check/views/res_partner_view.xml
Labels: approved

#3818 [14.0][FIX] l10n_es_aeat_partner_check: View is not correct
  l10n_es_aeat_partner_check/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#3819 [15.0][FIX] l10n_es_aeat_partner_check: View is not correct
  l10n_es_aeat_partner_check/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#3820 [16.0][IMP] l10n_es_aeat_mod347: Reubicate not_in_mod347
  l10n_es_aeat_mod347/views/account_move_view.xml
Labels: bot is merging ⏳

#3821 [17.0][IMP] l10n_es_aeat_mod347: Reubicate not_in_mod347
  l10n_es_aeat_mod347/views/account_move_view.xml
Labels: bot is merging ⏳

#3822 [15.0][IMP] l10n_es_aeat_mod347: Reubicate not_in_mod347
  l10n_es_aeat_mod347/views/account_move_view.xml
Labels: bot is merging ⏳

#3824 [16.0][IMP] l10n_es_aeat_sii_oca: Add Enable SII to journals to enable compatibilities (hr_expense for example)
  l10n_es_aeat_sii_oca/models/__init__.py
  l10n_es_aeat_sii_oca/models/account_journal.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/views/account_journal_view.xml
Labels: bot is merging ⏳

#3827 [15.0][IMP] l10n_es_aeat_sii_oca: Add Enable SII to journals to enable compatibilities (hr_expense for example)
  l10n_es_aeat_sii_oca/models/__init__.py
  l10n_es_aeat_sii_oca/models/account_journal.py
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/views/account_journal_view.xml
Labels: bot is merging ⏳
