Repository OCA/l10n-spain, pull requests merged in 2024-05, with the labels that each got.

#3562 [14.0][IMP] delivery_gls_asm: rename/add shipping times
  delivery_gls_asm/models/gls_asm_master_data.py
Labels: approved, bot is merging ⏳

#3359 [16.0][IMP] l10n_es_mod_303: Cuota a compensar pendiente (casilla 110)
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303/static/description/index.html
Labels: approved, bot is merging ⏳

#3491 [17.0][MIG] l10n_es_vat_book: Migration to version 17.0
  l10n_es_vat_book/README.rst
  l10n_es_vat_book/__init__.py
  l10n_es_vat_book/__manifest__.py
  l10n_es_vat_book/data/aeat.vat.book.map.line.csv
  l10n_es_vat_book/data/l10n.es.aeat.map.tax.line.account.csv
  l10n_es_vat_book/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_vat_book/i18n/bg.po
  l10n_es_vat_book/i18n/ca.po
  l10n_es_vat_book/i18n/cs.po
  l10n_es_vat_book/i18n/de.po
  l10n_es_vat_book/i18n/es.po
  l10n_es_vat_book/i18n/es_CO.po
  l10n_es_vat_book/i18n/es_CR.po
  l10n_es_vat_book/i18n/eu.po
  l10n_es_vat_book/i18n/fr.po
  l10n_es_vat_book/i18n/gl.po
  l10n_es_vat_book/i18n/hr.po
  l10n_es_vat_book/i18n/l10n_es_vat_book.pot
  l10n_es_vat_book/i18n/nl.po
  l10n_es_vat_book/i18n/pl.po
  l10n_es_vat_book/i18n/pt.po
  l10n_es_vat_book/i18n/pt_BR.po
  l10n_es_vat_book/i18n/ru.po
  l10n_es_vat_book/i18n/sl.po
  l10n_es_vat_book/i18n/sv.po
  l10n_es_vat_book/i18n/tr.po
  l10n_es_vat_book/i18n/vi.po
  l10n_es_vat_book/models/__init__.py
  l10n_es_vat_book/models/aeat_vat_book_map_line.py
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/models/l10n_es_vat_book_line.py
  l10n_es_vat_book/models/l10n_es_vat_book_line_tax.py
  l10n_es_vat_book/models/l10n_es_vat_book_summary.py
  l10n_es_vat_book/models/l10n_es_vat_book_tax_summary.py
  l10n_es_vat_book/pyproject.toml
  l10n_es_vat_book/readme/CONFIGURE.rst
  l10n_es_vat_book/readme/CONTRIBUTORS.rst
  l10n_es_vat_book/readme/DESCRIPTION.rst
  l10n_es_vat_book/readme/INSTALL.rst
  l10n_es_vat_book/readme/ROADMAP.rst
  l10n_es_vat_book/readme/USAGE.rst
  l10n_es_vat_book/report/__init__.py
  l10n_es_vat_book/report/common_templates.xml
  l10n_es_vat_book/report/report_views.xml
  l10n_es_vat_book/report/vat_book_invoices_issued.xml
  l10n_es_vat_book/report/vat_book_invoices_received.xml
  l10n_es_vat_book/report/vat_book_xlsx.py
  l10n_es_vat_book/report/vat_book_xlsx.xml
  l10n_es_vat_book/security/ir.model.access.csv
  l10n_es_vat_book/security/ir_rule.xml
  l10n_es_vat_book/static/description/icon.png
  l10n_es_vat_book/static/description/index.html
  l10n_es_vat_book/tests/__init__.py
  l10n_es_vat_book/tests/test_l10n_es_aeat_vat_book.py
  l10n_es_vat_book/views/aeat_vat_book_map_view.xml
  l10n_es_vat_book/views/l10n_es_vat_book.xml
  l10n_es_vat_book/views/l10n_es_vat_book_line.xml
  l10n_es_vat_book/views/l10n_es_vat_book_summary.xml
  l10n_es_vat_book/views/l10n_es_vat_book_tax_summary.xml
Labels: approved, ready to merge, bot is merging ⏳

#3558 [16.0][IMP] l10n_es_aeat_mod190: Update/add subkeys
  l10n_es_aeat_mod190/README.rst
  l10n_es_aeat_mod190/__manifest__.py
  l10n_es_aeat_mod190/data/perception_subkey_data.xml
  l10n_es_aeat_mod190/migrations/16.0.1.3.0/pre-migration.py
  l10n_es_aeat_mod190/static/description/index.html
  l10n_es_aeat_mod190/tests/test_mod190.py
Labels: bot is merging ⏳

#3567 [15.0][IMP] delivery_gls_asm: rename/add shipping times
  delivery_gls_asm/models/gls_asm_master_data.py
Labels: approved, bot is merging ⏳

#3569 [16.0][IMP] delivery_gls_asm: rename/add shipping times
  delivery_gls_asm/models/gls_asm_master_data.py
Labels: approved, bot is merging ⏳

#3566 [17.0][MIG] l10n_es_account _banking_sepa_fsdd: Migration to 17.0
  l10n_es_account_banking_sepa_fsdd/README.rst
  l10n_es_account_banking_sepa_fsdd/__init__.py
  l10n_es_account_banking_sepa_fsdd/__manifest__.py
  l10n_es_account_banking_sepa_fsdd/i18n/ca.po
  l10n_es_account_banking_sepa_fsdd/i18n/es.po
  l10n_es_account_banking_sepa_fsdd/i18n/es_ES.po
  l10n_es_account_banking_sepa_fsdd/i18n/fr.po
  l10n_es_account_banking_sepa_fsdd/i18n/l10n_es_account_banking_sepa_fsdd.pot
  l10n_es_account_banking_sepa_fsdd/i18n/nl.po
  l10n_es_account_banking_sepa_fsdd/i18n/pt_BR.po
  l10n_es_account_banking_sepa_fsdd/i18n/sl.po
  l10n_es_account_banking_sepa_fsdd/models/__init__.py
  l10n_es_account_banking_sepa_fsdd/models/account_payment_mode.py
  l10n_es_account_banking_sepa_fsdd/models/account_payment_order.py
  l10n_es_account_banking_sepa_fsdd/pyproject.toml
  l10n_es_account_banking_sepa_fsdd/readme/CONFIGURE.md
  l10n_es_account_banking_sepa_fsdd/readme/CONTRIBUTORS.md
  l10n_es_account_banking_sepa_fsdd/readme/DESCRIPTION.md
  l10n_es_account_banking_sepa_fsdd/readme/INSTALL.md
  l10n_es_account_banking_sepa_fsdd/static/description/icon.png
  l10n_es_account_banking_sepa_fsdd/static/description/index.html
  l10n_es_account_banking_sepa_fsdd/tests/__init__.py
  l10n_es_account_banking_sepa_fsdd/tests/test_l10n_es_account_banking_sepa_fsdd.py
  l10n_es_account_banking_sepa_fsdd/views/payment_mode_view.xml
Labels: approved, bot is merging ⏳

#3550 [16.0][FIX] l10n_es_*: Fix minimum models read permissions for readonly acc…
  l10n_es_aeat_mod190/views/account_invoice_view.xml
  l10n_es_aeat_sii_oca/views/account_move_views.xml
  l10n_es_ticketbai/views/account_move_views.xml
  l10n_es_ticketbai_batuz/views/account_move_views.xml
Labels: approved, bot is merging ⏳

#3541 [17.0][MIG] l10n_es_aeat_mod115: Migration to 17.0
  l10n_es_aeat_mod115/README.rst
  l10n_es_aeat_mod115/__init__.py
  l10n_es_aeat_mod115/__manifest__.py
  l10n_es_aeat_mod115/data/aeat_export_mod115_data.xml
  l10n_es_aeat_mod115/data/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod115/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod115/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod115/docs/DR115e15v11.xls
  l10n_es_aeat_mod115/i18n/bg.po
  l10n_es_aeat_mod115/i18n/ca.po
  l10n_es_aeat_mod115/i18n/cs.po
  l10n_es_aeat_mod115/i18n/es.po
  l10n_es_aeat_mod115/i18n/es_CO.po
  l10n_es_aeat_mod115/i18n/es_CR.po
  l10n_es_aeat_mod115/i18n/eu.po
  l10n_es_aeat_mod115/i18n/fr.po
  l10n_es_aeat_mod115/i18n/gl.po
  l10n_es_aeat_mod115/i18n/hr.po
  l10n_es_aeat_mod115/i18n/l10n_es_aeat_mod115.pot
  l10n_es_aeat_mod115/i18n/nl.po
  l10n_es_aeat_mod115/i18n/pl.po
  l10n_es_aeat_mod115/i18n/pt.po
  l10n_es_aeat_mod115/i18n/pt_BR.po
  l10n_es_aeat_mod115/i18n/ru.po
  l10n_es_aeat_mod115/i18n/sl.po
  l10n_es_aeat_mod115/i18n/sv.po
  l10n_es_aeat_mod115/i18n/tr.po
  l10n_es_aeat_mod115/i18n/vi.po
  l10n_es_aeat_mod115/models/__init__.py
  l10n_es_aeat_mod115/models/mod115.py
  l10n_es_aeat_mod115/pyproject.toml
  l10n_es_aeat_mod115/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod115/readme/DESCRIPTION.md
  l10n_es_aeat_mod115/readme/USAGE.md
  l10n_es_aeat_mod115/security/ir.model.access.csv
  l10n_es_aeat_mod115/security/l10n_es_aeat_mod115_security.xml
  l10n_es_aeat_mod115/static/description/icon.png
  l10n_es_aeat_mod115/static/description/icon_source.svg
  l10n_es_aeat_mod115/static/description/index.html
  l10n_es_aeat_mod115/tests/__init__.py
  l10n_es_aeat_mod115/tests/test_l10n_es_aeat_mod115.py
  l10n_es_aeat_mod115/views/mod115_view.xml
Labels: bot is merging ⏳

#3580 [16.0][FIX] Vista form en 123: Atributos states y attrs no funcionan bien juntos
  l10n_es_aeat_mod123/views/mod123_view.xml
  l10n_es_aeat_mod390/static/description/index.html
Labels: bot is merging ⏳

#3544 [16.0][IMP] l10n_es_aeat_mod349: functionality to get the country_code
  l10n_es_aeat_mod349/README.rst
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod349/static/description/index.html
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
Labels: approved, ready to merge, bot is merging ⏳

#3534 [16.0][IMP] l10n_es_aeat_mod303: Return last period
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: approved, bot is merging ⏳

#3581 [16.0][FIX] l10n_es_aeat_mod123: Casilla 14 en vista lista
  l10n_es_aeat_mod123/models/mod123.py
  l10n_es_aeat_mod123/tests/test_l10n_es_aeat_mod123.py
  l10n_es_aeat_mod123/views/mod123_view.xml
Labels: approved, bot is merging ⏳

#3576 [17.0][MIG] l10n_es_account_statement_import_n43: migration to 17.0
  l10n_es_account_statement_import_n43/README.rst
  l10n_es_account_statement_import_n43/__init__.py
  l10n_es_account_statement_import_n43/__manifest__.py
  l10n_es_account_statement_import_n43/doc/norma_43_castellano.pdf
  l10n_es_account_statement_import_n43/i18n/ca.po
  l10n_es_account_statement_import_n43/i18n/es.po
  l10n_es_account_statement_import_n43/i18n/eu.po
  l10n_es_account_statement_import_n43/i18n/fr.po
  l10n_es_account_statement_import_n43/i18n/gl.po
  l10n_es_account_statement_import_n43/i18n/l10n_es_account_bank_statement_import_n43.pot
  l10n_es_account_statement_import_n43/i18n/l10n_es_account_statement_import_n43.pot
  l10n_es_account_statement_import_n43/i18n/sl.po
  l10n_es_account_statement_import_n43/models/__init__.py
  l10n_es_account_statement_import_n43/models/account_journal.py
  l10n_es_account_statement_import_n43/pyproject.toml
  l10n_es_account_statement_import_n43/readme/CONTRIBUTORS.md
  l10n_es_account_statement_import_n43/readme/DESCRIPTION.md
  l10n_es_account_statement_import_n43/readme/ROADMAP.md
  l10n_es_account_statement_import_n43/readme/USAGE.md
  l10n_es_account_statement_import_n43/static/description/icon.png
  l10n_es_account_statement_import_n43/static/description/icon_src.svg
  l10n_es_account_statement_import_n43/static/description/index.html
  l10n_es_account_statement_import_n43/tests/__init__.py
  l10n_es_account_statement_import_n43/tests/test.n43
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
  l10n_es_account_statement_import_n43/tests/testmulti.n43
  l10n_es_account_statement_import_n43/views/account_journal_views.xml
  l10n_es_account_statement_import_n43/wizards/__init__.py
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
  l10n_es_account_statement_import_n43/wizards/account_statement_import_view.xml
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#3578 [17.0][MIG] l10n_es_atc: Migration to 17.0
  l10n_es_atc/README.rst
  l10n_es_atc/__init__.py
  l10n_es_atc/__manifest__.py
  l10n_es_atc/data/atc_partner.xml
  l10n_es_atc/i18n/es.po
  l10n_es_atc/i18n/l10n_es_atc.pot
  l10n_es_atc/pyproject.toml
  l10n_es_atc/readme/CONTRIBUTORS.md
  l10n_es_atc/readme/DESCRIPTION.md
  l10n_es_atc/security/atc_security.xml
  l10n_es_atc/static/description/icon.png
  l10n_es_atc/static/description/index.html
  l10n_es_atc/views/atc_menuitem.xml
Labels: bot is merging ⏳

#3490 [17.0][MIG] l10n_es_aeat_mod390: Migration to version 17.0
  l10n_es_aeat_mod390/README.rst
  l10n_es_aeat_mod390/__init__.py
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub04_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub07_data.xml
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub08_data.xml
  l10n_es_aeat_mod390/data/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod390/data/l10n.es.aeat.map.tax.line.account.csv
  l10n_es_aeat_mod390/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod390/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod390/docs/dr390e2022.xlsx
  l10n_es_aeat_mod390/docs/instr390.pdf
  l10n_es_aeat_mod390/i18n/ca.po
  l10n_es_aeat_mod390/i18n/es.po
  l10n_es_aeat_mod390/i18n/l10n_es_aeat_mod390.pot
  l10n_es_aeat_mod390/models/__init__.py
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/pyproject.toml
  l10n_es_aeat_mod390/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod390/readme/DESCRIPTION.md
  l10n_es_aeat_mod390/readme/INSTALL.md
  l10n_es_aeat_mod390/readme/ROADMAP.md
  l10n_es_aeat_mod390/readme/USAGE.md
  l10n_es_aeat_mod390/security/ir.model.access.csv
  l10n_es_aeat_mod390/security/l10n_es_aeat_mod390_security.xml
  l10n_es_aeat_mod390/static/description/icon.png
  l10n_es_aeat_mod390/static/description/icon.svg
  l10n_es_aeat_mod390/static/description/index.html
  l10n_es_aeat_mod390/tests/__init__.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: bot is merging ⏳

#3584 [17.0][FIX] l10n_es_account_statement_import_n43: use file_path instead of get_module_resource in tests
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
Labels: approved, bot is merging ⏳

#3582 [15.0][MIG] l10n_es_payment_order_confirming_sabadell: Migration to 15.0
  l10n_es_payment_order_confirming_sabadell/README.rst
  l10n_es_payment_order_confirming_sabadell/__init__.py
  l10n_es_payment_order_confirming_sabadell/__manifest__.py
  l10n_es_payment_order_confirming_sabadell/data/account_payment_method.xml
  l10n_es_payment_order_confirming_sabadell/i18n/ca.po
  l10n_es_payment_order_confirming_sabadell/i18n/es.po
  l10n_es_payment_order_confirming_sabadell/i18n/l10n_es_payment_order_confirming_sabadell.pot
  l10n_es_payment_order_confirming_sabadell/models/__init__.py
  l10n_es_payment_order_confirming_sabadell/models/account_payment_mode.py
  l10n_es_payment_order_confirming_sabadell/models/account_payment_order.py
  l10n_es_payment_order_confirming_sabadell/models/confirming_sabadell.py
  l10n_es_payment_order_confirming_sabadell/readme/CONFIGURE.rst
  l10n_es_payment_order_confirming_sabadell/readme/CONTRIBUTORS.rst
  l10n_es_payment_order_confirming_sabadell/readme/DESCRIPTION.rst
  l10n_es_payment_order_confirming_sabadell/readme/USAGE.rst
  l10n_es_payment_order_confirming_sabadell/static/description/icon.png
  l10n_es_payment_order_confirming_sabadell/static/description/index.html
  l10n_es_payment_order_confirming_sabadell/tests/__init__.py
  l10n_es_payment_order_confirming_sabadell/tests/test_payment_order_confirming_sabadell.py
  l10n_es_payment_order_confirming_sabadell/views/account_payment_mode_view.xml
  setup/l10n_es_payment_order_confirming_sabadell/odoo/addons/l10n_es_payment_order_confirming_sabadell
  setup/l10n_es_payment_order_confirming_sabadell/setup.py
Labels: bot is merging ⏳

#3587 [17.0][IMP] l10n_es_mod_303: Cuota a compensar (casilla 110)
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod303/static/description/index.html
Labels: bot is merging ⏳

#3595 [16.0][FIX] l10n_es_aeat_sii_oca: Exclude tax agency connection from tests
  l10n_es_aeat_sii_oca/data/aeat_sii_tax_agency_data.xml
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: bot is merging ⏳

#3594 [15.0][FIX] l10n_es_aeat_sii_oca: Exclude tax agency connection from tests
  l10n_es_aeat_sii_oca/data/aeat_sii_tax_agency_data.xml
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: bot is merging ⏳

#3559 [15.0][IMP] l10n_es_aeat_mod190: Refactor code + improve UX
  l10n_es_aeat_mod190/README.rst
  l10n_es_aeat_mod190/models/account_move.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_perception.py
  l10n_es_aeat_mod190/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod190/static/description/index.html
  l10n_es_aeat_mod190/tests/test_mod190.py
  l10n_es_aeat_mod190/views/mod190_view.xml
Labels: bot is merging ⏳

#3593 [14.0][FIX] l10n_es_aeat_sii_oca: Exclude tax agency connection from tests
  l10n_es_aeat_sii_oca/data/aeat_sii_tax_agency_data.xml
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: bot is merging ⏳

#3531 [14.0] [IMP] l10n_es_irnr & l10n_es_aeat_mod216: impuestos no residentes con convenio
  l10n_es_aeat_mod216/data/tax_code_map_mod216_data.xml
  l10n_es_aeat_mod216/tests/test_l10n_es_aeat_mod216.py
  l10n_es_irnr/data/fiscal_position_taxes_irnr.xml
  l10n_es_irnr/data/fiscal_positions_irnr.xml
  l10n_es_irnr/data/taxes_irnr.xml
Labels: bot is merging ⏳

#3596 [15.0][FIX] l10n_es_aeat_mod303: soporte para cuenta tributaria
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: bot is merging ⏳

#3561 [15.0][IMP] l10n_es_aeat_mod390 - Add support for fields 31 and 32
  l10n_es_aeat_mod390/README.rst
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/models/__init__.py
  l10n_es_aeat_mod390/models/account_move.py
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/static/description/index.html
  l10n_es_aeat_mod390/views/account_move_view.xml
Labels: bot is merging ⏳

#3590 [16.0][IMP] l10n_es_aeat_mod347: make email templates easier to extend
  l10n_es_aeat_mod347/models/mod347.py
Labels: bot is merging ⏳

#3577 [16.0][ADD] l10n_es_atc_mod415
  l10n_es_atc_mod415/README.rst
  l10n_es_atc_mod415/__init__.py
  l10n_es_atc_mod415/__manifest__.py
  l10n_es_atc_mod415/data/mail_template_data.xml
  l10n_es_atc_mod415/data/tax_code_map_mod415_data.xml
  l10n_es_atc_mod415/i18n/es.po
  l10n_es_atc_mod415/models/__init__.py
  l10n_es_atc_mod415/models/account_move.py
  l10n_es_atc_mod415/models/mod415.py
  l10n_es_atc_mod415/models/res_partner.py
  l10n_es_atc_mod415/readme/CONTRIBUTORS.rst
  l10n_es_atc_mod415/readme/DESCRIPTION.rst
  l10n_es_atc_mod415/readme/INSTALL.rst
  l10n_es_atc_mod415/security/ir.model.access.csv
  l10n_es_atc_mod415/security/mod_415_security.xml
  l10n_es_atc_mod415/static/description/icon.png
  l10n_es_atc_mod415/static/description/index.html
  l10n_es_atc_mod415/tests/__init__.py
  l10n_es_atc_mod415/tests/test_l10n_es_atc_mod415.py
  l10n_es_atc_mod415/views/account_move_view.xml
  l10n_es_atc_mod415/views/mod415_templates.xml
  l10n_es_atc_mod415/views/mod415_view.xml
  l10n_es_atc_mod415/views/report_415_partner.xml
  l10n_es_atc_mod415/views/res_partner_view.xml
  setup/l10n_es_atc_mod415/odoo/addons/l10n_es_atc_mod415
  setup/l10n_es_atc_mod415/setup.py
Labels: bot is merging ⏳

#3597 [16.0][IMP] l10n_es_aeat_mod190: Refactor code + improve UX
  l10n_es_aeat_mod190/README.rst
  l10n_es_aeat_mod190/models/account_move.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_perception.py
  l10n_es_aeat_mod190/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod190/static/description/index.html
  l10n_es_aeat_mod190/tests/test_mod190.py
  l10n_es_aeat_mod190/views/mod190_view.xml
Labels: bot is merging ⏳

#3591 [16.0][IMP] l10n_es_atc: Modificar pestaña AEAT en contacto
  l10n_es_atc/__init__.py
  l10n_es_atc/models/__init__.py
  l10n_es_atc/models/res_partner.py
  l10n_es_atc/static/description/index.html
Labels: bot is merging ⏳

#3600 [16.0][IMP] l10n_es_aeat_mod390 - Add support for fields 31 and 32
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/models/__init__.py
  l10n_es_aeat_mod390/models/account_move.py
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/views/account_move_view.xml
Labels: bot is merging ⏳

#3601 [17.0][IMP] l10n_es_aeat_mod390 - Add support for fields 31 and 32
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod390/models/__init__.py
  l10n_es_aeat_mod390/models/account_move.py
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/views/account_move_view.xml
Labels: bot is merging ⏳

#3602 [16.0][IMP] l10n_es_aeat_sii_oca: Reactivate agencies tests
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: bot is merging ⏳

#3588 [14.0][MIG] l10n_es_aeat_sii_invoice_summary: Migration to 14.0
  l10n_es_aeat_sii_invoice_summary/README.rst
  l10n_es_aeat_sii_invoice_summary/__init__.py
  l10n_es_aeat_sii_invoice_summary/__manifest__.py
  l10n_es_aeat_sii_invoice_summary/i18n/es.po
  l10n_es_aeat_sii_invoice_summary/i18n/l10n_es_aeat_sii_invoice_summary.pot
  l10n_es_aeat_sii_invoice_summary/models/__init__.py
  l10n_es_aeat_sii_invoice_summary/models/account_move.py
  l10n_es_aeat_sii_invoice_summary/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_invoice_summary/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_invoice_summary/readme/ROADMAP.rst
  l10n_es_aeat_sii_invoice_summary/readme/USAGE.rst
  l10n_es_aeat_sii_invoice_summary/static/description/icon.png
  l10n_es_aeat_sii_invoice_summary/static/description/index.html
  l10n_es_aeat_sii_invoice_summary/tests/__init__.py
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva0_sp_i_s_iva0_ic_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva0_sp_i_s_iva0_ic_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_irpf1_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_irpf1_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_iva0_ns_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_iva0_ns_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_iva21s_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_iva21s_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_req014_s_iva21s_s_req52_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_req014_s_iva21s_s_req52_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva_e_s_iva0_e_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva_e_s_iva0_e_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva0_sp_i_s_iva0_ic_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva0_sp_i_s_iva0_ic_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva10b_s_iva10b_s_iva21s_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva10b_s_iva10b_s_iva21s_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva_e_s_iva0_e_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva_e_s_iva0_e_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/test_l10n_es_aeat_sii_invoice_summary.py
  l10n_es_aeat_sii_invoice_summary/views/account_move_view.xml
  setup/l10n_es_aeat_sii_invoice_summary/odoo/addons/l10n_es_aeat_sii_invoice_summary
  setup/l10n_es_aeat_sii_invoice_summary/odoo/addons/l10n_es_aeat_sii_invoice_summary~98ccc3435 ([MIG] l10n_es_aeat_sii_invoice_summary: Migration to 14.0)
  setup/l10n_es_aeat_sii_invoice_summary/setup.py
Labels: bot is merging ⏳

#3604 [14.0][IMP] l10n_es_aeat_sii_invoice_summary: Show summary fields only on customer invoices
  l10n_es_aeat_sii_invoice_summary/README.rst
  l10n_es_aeat_sii_invoice_summary/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_invoice_summary/static/description/index.html
  l10n_es_aeat_sii_invoice_summary/views/account_move_view.xml
Labels: bot is merging ⏳

#3583 [17.0][MIG] l10n_es_vat_prorate: Migration to 17.0
  l10n_es_vat_prorate/README.rst
  l10n_es_vat_prorate/__init__.py
  l10n_es_vat_prorate/__manifest__.py
  l10n_es_vat_prorate/i18n/ca.po
  l10n_es_vat_prorate/i18n/es.po
  l10n_es_vat_prorate/i18n/l10n_es_vat_prorate.pot
  l10n_es_vat_prorate/models/__init__.py
  l10n_es_vat_prorate/models/account_move.py
  l10n_es_vat_prorate/models/account_tax.py
  l10n_es_vat_prorate/models/prorate_taxes.py
  l10n_es_vat_prorate/models/res_company.py
  l10n_es_vat_prorate/pyproject.toml
  l10n_es_vat_prorate/readme/CONFIGURE.md
  l10n_es_vat_prorate/readme/CONTRIBUTORS.md
  l10n_es_vat_prorate/readme/DESCRIPTION.md
  l10n_es_vat_prorate/readme/ROADMAP.md
  l10n_es_vat_prorate/security/ir.model.access.csv
  l10n_es_vat_prorate/static/description/icon.png
  l10n_es_vat_prorate/static/description/index.html
  l10n_es_vat_prorate/tests/__init__.py
  l10n_es_vat_prorate/tests/json/sii_in_invoice_p_iva0_ns_p_iva10_bc_dict.json
  l10n_es_vat_prorate/tests/json/sii_in_invoice_p_iva10_bc_dict.json
  l10n_es_vat_prorate/tests/json/sii_in_invoice_p_iva10_bc_p_irpf19_p_iva21_sc_p_irpf19_dict.json
  l10n_es_vat_prorate/tests/json/sii_in_invoice_p_iva10_bc_p_irpf1_dict.json
  l10n_es_vat_prorate/tests/json/sii_in_invoice_p_iva10_bc_p_req014_p_iva21_sc_p_req52_dict.json
  l10n_es_vat_prorate/tests/json/sii_in_invoice_p_iva21_sp_ex_dict.json
  l10n_es_vat_prorate/tests/json/sii_in_refund_p_iva10_bc_dict.json
  l10n_es_vat_prorate/tests/json/sii_in_refund_p_iva21_sp_in_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva0_sp_i_s_iva0_ic_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva10b_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva10b_s_irpf1_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva10b_s_iva0_ns_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva10b_s_iva21s_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva10b_s_req014_s_iva21s_s_req52_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva_e_s_iva0_e_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_refund_s_iva0_sp_i_s_iva0_ic_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_refund_s_iva10b_s_iva10b_s_iva21s_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_refund_s_iva_e_s_iva0_e_dict.json
  l10n_es_vat_prorate/tests/test_prorate_sii.py
  l10n_es_vat_prorate/tests/test_vat_prorate.py
  l10n_es_vat_prorate/views/account_move_views.xml
  l10n_es_vat_prorate/views/account_tax_views.xml
  l10n_es_vat_prorate/views/res_company_prorate_views.xml
  l10n_es_vat_prorate/views/res_company_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#3609 [16.0][FIX] l10n_es_aeat_sii_oca: check coming from move
  l10n_es_aeat_sii_oca/wizards/account_move_reversal.py
Labels: bot is merging ⏳

#3611 [14.0][IMP] l10n_es_aeat_sii_invoice_summary: Define a specific string for the fields in form view
  l10n_es_aeat_sii_invoice_summary/i18n/es.po
  l10n_es_aeat_sii_invoice_summary/i18n/l10n_es_aeat_sii_invoice_summary.pot
  l10n_es_aeat_sii_invoice_summary/views/account_move_view.xml
Labels: bot is merging ⏳

#3612 [16.0][IMP] delivery_gls_asm: Check value being sent
  delivery_gls_asm/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#3603 [14.0][ADD] l10n_es_vat_book_invoice_summary: New module
  l10n_es_vat_book_invoice_summary/README.rst
  l10n_es_vat_book_invoice_summary/__init__.py
  l10n_es_vat_book_invoice_summary/__manifest__.py
  l10n_es_vat_book_invoice_summary/i18n/es.po
  l10n_es_vat_book_invoice_summary/i18n/l10n_es_vat_book_invoice_summary.pot
  l10n_es_vat_book_invoice_summary/readme/CONTRIBUTORS.rst
  l10n_es_vat_book_invoice_summary/readme/DESCRIPTION.rst
  l10n_es_vat_book_invoice_summary/report/__init__.py
  l10n_es_vat_book_invoice_summary/report/vat_book_xlsx.py
  l10n_es_vat_book_invoice_summary/static/description/icon.png
  l10n_es_vat_book_invoice_summary/static/description/index.html
  l10n_es_vat_book_invoice_summary/tests/__init__.py
  l10n_es_vat_book_invoice_summary/tests/test_l10n_es_vat_book_invoice_summary.py
  setup/l10n_es_vat_book_invoice_summary/odoo/addons/l10n_es_vat_book_invoice_summary
  setup/l10n_es_vat_book_invoice_summary/setup.py
Labels: bot is merging ⏳

#3614 [14.0][IMP] l10n_es_aeat_sii_invoice_summary: Changes in the visibility and required of the fields
  l10n_es_aeat_sii_invoice_summary/models/account_move.py
  l10n_es_aeat_sii_invoice_summary/tests/test_l10n_es_aeat_sii_invoice_summary.py
  l10n_es_aeat_sii_invoice_summary/views/account_move_view.xml
Labels: bot is merging ⏳

#3616 [MIG] l10n_es_cnae: Migration to 17.0
  l10n_es_cnae/README.rst
  l10n_es_cnae/__init__.py
  l10n_es_cnae/__manifest__.py
  l10n_es_cnae/data/res.partner.industry.csv
  l10n_es_cnae/i18n/ca_ES.po
  l10n_es_cnae/i18n/es.po
  l10n_es_cnae/i18n/l10n_es_cnae.pot
  l10n_es_cnae/pyproject.toml
  l10n_es_cnae/readme/CONTRIBUTORS.md
  l10n_es_cnae/readme/DESCRIPTION.md
  l10n_es_cnae/readme/INSTALL.md
  l10n_es_cnae/readme/USAGE.md
  l10n_es_cnae/static/description/icon.png
  l10n_es_cnae/static/description/index.html
  l10n_es_cnae/wizard/__init__.py
  l10n_es_cnae/wizard/res_partner_industry_eu_nace_wizard.py
Labels: approved, bot is merging ⏳
