Repository OCA/l10n-spain, pull requests merged in 2024-04, with the labels that each got.

#3479 [15.0][IMP] l10n_es_ticketbai_batuz: LROE modelo 140 implementar grupo de cuenta contable L20 e importe gasto IRPF
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai_batuz/models/account_move.py
Labels: approved, bot is merging ⏳

#3506 [15.0][FIX] l10n_es_dua_ticketbai_batuz: Corrección mapeo impuestos
  l10n_es_dua_ticketbai_batuz/data/tax_code_map_dua_ticketbai_data.xml
Labels: bot is merging ⏳

#3509 [16.0] [IMP] l10n_es_ticketbai_batuz cuenta contable IRPF - [FIX] l10n_es_ticketbai envío rectificativa recibida como emitida
  l10n_es_ticketbai/models/account_move.py
  l10n_es_ticketbai_batuz/models/account_move.py
Labels: bot is merging ⏳

#3513 [16.0][IMP] l10n_es_aeat_sii_taxfree: Improve module's readme
  l10n_es_aeat_sii_taxfree/README.rst
  l10n_es_aeat_sii_taxfree/readme/CONFIGURE.rst
  l10n_es_aeat_sii_taxfree/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_taxfree/readme/USAGE.rst
  l10n_es_aeat_sii_taxfree/static/description/SII_devolucion_IVA_viajeros.csv
  l10n_es_aeat_sii_taxfree/static/description/config_pos_fiscal.png
  l10n_es_aeat_sii_taxfree/static/description/index.html
Labels: approved, bot is merging ⏳

#3517 [16.0][FIX] l10n_es_sigaus_stock_picking_report_valued: Show sigaus amount in picking lines without taxes
  l10n_es_sigaus_stock_picking_report_valued/report/report_deliveryslip.xml
Labels: approved, bot is merging ⏳

#3516 [16.0][MIG] l10n_es_vat_book_oss: Migration to 16.0
  l10n_es_vat_book_oss/README.rst
  l10n_es_vat_book_oss/__init__.py
  l10n_es_vat_book_oss/__manifest__.py
  l10n_es_vat_book_oss/i18n/es.po
  l10n_es_vat_book_oss/i18n/l10n_es_vat_book_oss.pot
  l10n_es_vat_book_oss/models/__init__.py
  l10n_es_vat_book_oss/models/aeat_vat_book_map_lines.py
  l10n_es_vat_book_oss/models/l10n_es_vat_book.py
  l10n_es_vat_book_oss/readme/CONFIGURE.rst
  l10n_es_vat_book_oss/readme/CONTRIBUTORS.rst
  l10n_es_vat_book_oss/readme/DESCRIPTION.rst
  l10n_es_vat_book_oss/readme/INSTALL.rst
  l10n_es_vat_book_oss/readme/USAGE.rst
  l10n_es_vat_book_oss/static/description/icon.png
  l10n_es_vat_book_oss/static/description/index.html
  l10n_es_vat_book_oss/tests/__init__.py
  l10n_es_vat_book_oss/tests/test_l10n_es_aeat_vat_book_oss.py
  setup/l10n_es_vat_book_oss/odoo/addons/l10n_es_vat_book_oss
  setup/l10n_es_vat_book_oss/setup.py
Labels: approved, bot is merging ⏳

#3523 [16.0][FIX] l10n_es_igic: Move accounts 4707,4757 out of common
  l10n_es_igic/data/account.account.template-common-canary.csv
  l10n_es_igic/data/account.account.template-full-canary.csv
  l10n_es_igic/data/account.account.template-pymes-canary.csv
Labels: bot is merging ⏳

#3515 [16.0][FIX] l10n_es_aeat_mod303: comunicar IBAN en ingresos
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: bot is merging ⏳

#3389 [16.0][IMP] l10n_es_aeat: NIF del representante legal por defecto
  l10n_es_aeat/README.rst
  l10n_es_aeat/i18n/es.po
  l10n_es_aeat/i18n/l10n_es_aeat.pot
  l10n_es_aeat/models/l10n_es_aeat_report.py
  l10n_es_aeat/models/res_company.py
  l10n_es_aeat/readme/CONTRIBUTORS.rst
  l10n_es_aeat/static/description/index.html
  l10n_es_aeat/tests/test_l10n_es_aeat_report.py
  l10n_es_aeat/views/aeat_report_view.xml
  l10n_es_aeat/views/res_company_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3535 [17.0][FIX] l10n_es_aeat: Do not load demo data in tests
  l10n_es_aeat/tests/test_l10n_es_aeat_mod_base.py
Labels: bot is merging ⏳

#3536 [15.0][FIX] l10n_es_aeat_mod347: compañia incorrecta en plantilla de correo.
  l10n_es_aeat_mod347/README.rst
  l10n_es_aeat_mod347/__manifest__.py
  l10n_es_aeat_mod347/data/mail_template_data.xml
  l10n_es_aeat_mod347/migrations/15.0.1.9.1/post-migration.py
  l10n_es_aeat_mod347/static/description/index.html
Labels: approved, bot is merging ⏳

#3537 [16.0][FIX] l10n_es_igic: Sujeto Pasivo, factor -100
  l10n_es_igic/data/account_tax_data.xml
Labels: bot is merging ⏳

#3524 [FIX] l10n_es_aeat_mod303: soporte para cuenta tributaria
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/ROADMAP.md
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: bot is merging ⏳

#3540 [16.0][FIX] l10n_es_aeat_mod349: permitir a los comerciales ver sus facturas
  l10n_es_aeat_mod349/views/account_move_view.xml
Labels: bot is merging ⏳

#3331 [16.0][IMP] l10n_es_aeat_mod349: implement more error texts
  l10n_es_aeat_mod349/i18n/es.po
  l10n_es_aeat_mod349/i18n/l10n_es_aeat_mod349.pot
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
Labels: approved, ready to merge, bot is merging ⏳

#3526 [15.0] [IMP] l10n_es_irnr & l10n_es_aeat_mod216: impuestos no residentes con convenio
  l10n_es_aeat_mod216/data/tax_code_map_mod216_data.xml
  l10n_es_aeat_mod216/tests/test_l10n_es_aeat_mod216.py
  l10n_es_irnr/data/fiscal_position_taxes_irnr.xml
  l10n_es_irnr/data/fiscal_positions_irnr.xml
  l10n_es_irnr/data/taxes_irnr.xml
Labels: approved, ready to merge, bot is merging ⏳

#3545 [15.0][IMP] l10n_es_aeat_mod190: Update/add subkeys
  l10n_es_aeat_mod190/README.rst
  l10n_es_aeat_mod190/__manifest__.py
  l10n_es_aeat_mod190/data/perception_subkey_data.xml
  l10n_es_aeat_mod190/migrations/15.0.1.3.0/pre-migration.py
  l10n_es_aeat_mod190/static/description/index.html
  l10n_es_aeat_mod190/tests/test_mod190.py
Labels: bot is merging ⏳

#3553 [16.0][FIX] l10n_es_aeat_mod347: compañia incorrecta en plantilla de correo.
  l10n_es_aeat_mod347/README.rst
  l10n_es_aeat_mod347/__manifest__.py
  l10n_es_aeat_mod347/data/mail_template_data.xml
  l10n_es_aeat_mod347/migrations/16.0.1.7.1/post-migration.py
  l10n_es_aeat_mod347/static/description/index.html
Labels: approved, bot is merging ⏳

#3554 [17.0][FIX] l10n_es_aeat_mod347: compañia incorrecta en plantilla de correo.
  l10n_es_aeat_mod347/__manifest__.py
  l10n_es_aeat_mod347/data/mail_template_data.xml
  l10n_es_aeat_mod347/migrations/17.0.1.0.1/post-migration.py
  l10n_es_aeat_mod347/static/description/index.html
Labels: approved, bot is merging ⏳

#3555 [16.0][IMP] l10n_es_pos_by_device: added model description
  l10n_es_pos_by_device/models/pos_device.py
Labels: approved, bot is merging ⏳
