Repository OCA/l10n-spain, pull requests merged in 2024-08, with the labels that each got.

#3671 [16.0][MIG] l10n_es_vat_book_invoice_summary: Migration to 16.0
  l10n_es_vat_book_invoice_summary/README.rst
  l10n_es_vat_book_invoice_summary/__init__.py
  l10n_es_vat_book_invoice_summary/__manifest__.py
  l10n_es_vat_book_invoice_summary/i18n/es.po
  l10n_es_vat_book_invoice_summary/i18n/l10n_es_vat_book_invoice_summary.pot
  l10n_es_vat_book_invoice_summary/readme/CONTRIBUTORS.rst
  l10n_es_vat_book_invoice_summary/readme/DESCRIPTION.rst
  l10n_es_vat_book_invoice_summary/report/__init__.py
  l10n_es_vat_book_invoice_summary/report/vat_book_xlsx.py
  l10n_es_vat_book_invoice_summary/static/description/icon.png
  l10n_es_vat_book_invoice_summary/static/description/index.html
  l10n_es_vat_book_invoice_summary/tests/__init__.py
  l10n_es_vat_book_invoice_summary/tests/test_l10n_es_vat_book_invoice_summary.py
  setup/l10n_es_vat_book_invoice_summary/odoo/addons/l10n_es_vat_book_invoice_summary
  setup/l10n_es_vat_book_invoice_summary/setup.py
Labels: approved, bot is merging ⏳

#3678 [17.0] [IMP] l10n_es_vat_prorate: move prorate type to prorate level and add… … constraint
  l10n_es_aeat_mod303_vat_prorate/models/mod303.py
  l10n_es_vat_prorate/__init__.py
  l10n_es_vat_prorate/__manifest__.py
  l10n_es_vat_prorate/hooks.py
  l10n_es_vat_prorate/models/account_move.py
  l10n_es_vat_prorate/models/res_company.py
  l10n_es_vat_prorate/static/description/index.html
  l10n_es_vat_prorate/tests/test_vat_prorate.py
  l10n_es_vat_prorate/views/account_move_views.xml
  l10n_es_vat_prorate/views/res_company_prorate_views.xml
  l10n_es_vat_prorate/views/res_company_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#3657 [15.0][ADD] delivery_seur_atlas: New module
  delivery_seur_atlas/README.rst
  delivery_seur_atlas/__init__.py
  delivery_seur_atlas/__manifest__.py
  delivery_seur_atlas/models/__init__.py
  delivery_seur_atlas/models/delivery_carrier.py
  delivery_seur_atlas/models/seur_master_data.py
  delivery_seur_atlas/models/seur_request_atlas.py
  delivery_seur_atlas/readme/CONFIGURE.md
  delivery_seur_atlas/readme/CONTEXT.md
  delivery_seur_atlas/readme/CONTRIBUTORS.md
  delivery_seur_atlas/readme/DESCRIPTION.md
  delivery_seur_atlas/readme/INSTALL.md
  delivery_seur_atlas/readme/ROADMAP.md
  delivery_seur_atlas/readme/USAGE.md
  delivery_seur_atlas/static/description/icon.png
  delivery_seur_atlas/static/description/index.html
  delivery_seur_atlas/tests/__init__.py
  delivery_seur_atlas/tests/test_delivery_seur_atlas.py
  delivery_seur_atlas/views/delivery_carrier_views.xml
  setup/delivery_seur_atlas/odoo/addons/delivery_seur_atlas
  setup/delivery_seur_atlas/setup.py
Labels: approved, bot is merging ⏳

#3656 [IMP] l10n_es_aeat_mod303_vat_prorate: add special vat prorate
  l10n_es_aeat_mod303_vat_prorate/README.rst
  l10n_es_aeat_mod303_vat_prorate/models/mod303.py
  l10n_es_aeat_mod303_vat_prorate/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod303_vat_prorate/readme/ROADMAP.md
  l10n_es_aeat_mod303_vat_prorate/static/description/index.html
  l10n_es_aeat_mod303_vat_prorate/tests/test_l10n_es_aeat_mod303_vat_prorate.py
  l10n_es_aeat_mod303_vat_prorate/views/mod303_views.xml
Labels: bot is merging ⏳

#3705 [16.0][FIX] l10n_es_aeat_sii_match: avoid buggy deepdiff release
  l10n_es_aeat_sii_match/__manifest__.py
  l10n_es_aeat_sii_match/static/description/index.html
  requirements.txt
Labels: bot is merging ⏳

#3546 [16.0][ADD] l10n_es_atc_mod420
  l10n_es_atc_mod420/README.rst
  l10n_es_atc_mod420/__init__.py
  l10n_es_atc_mod420/__manifest__.py
  l10n_es_atc_mod420/data/tax_code_map_mod420_data.xml
  l10n_es_atc_mod420/docs/420.pdf
  l10n_es_atc_mod420/docs/boe-modelo-420-quipu-descargar.pdf
  l10n_es_atc_mod420/i18n/es.po
  l10n_es_atc_mod420/models/__init__.py
  l10n_es_atc_mod420/models/mod420.py
  l10n_es_atc_mod420/readme/CONTRIBUTORS.rst
  l10n_es_atc_mod420/readme/DESCRIPTION.rst
  l10n_es_atc_mod420/readme/USAGE.rst
  l10n_es_atc_mod420/security/ir.model.access.csv
  l10n_es_atc_mod420/static/description/icon.png
  l10n_es_atc_mod420/static/description/index.html
  l10n_es_atc_mod420/static/src/pdf/caratula_sobre_420.pdf
  l10n_es_atc_mod420/tests/__init__.py
  l10n_es_atc_mod420/tests/test_l10n_es_atc_mod420.py
  l10n_es_atc_mod420/views/mod420_view.xml
  setup/l10n_es_atc_mod420/odoo/addons/l10n_es_atc_mod420
  setup/l10n_es_atc_mod420/setup.py
Labels: bot is merging ⏳

#3707 [16.0][FIX] l10n_es_aeat_sii_oca: Don't requeue pending invoices
  l10n_es_aeat_sii_oca/models/sii_mixin.py
Labels: bot is merging ⏳
