Repository OCA/l10n-spain, pull requests merged in 2024-07, with the labels that each got.

#3652 [17.0][FIX]l10n_ca_es_cnae: correccion de autoria/eliminar .pot innecesarios
  l10n_ca_es_cnae/README.rst
  l10n_ca_es_cnae/__manifest__.py
  l10n_ca_es_cnae/i18n/l10n_ca_cnae.pot
  l10n_ca_es_cnae/i18n/l10n_es_cnae.pot
  l10n_ca_es_cnae/readme/CONTRIBUTORS.md
  l10n_ca_es_cnae/static/description/index.html
Labels: approved, bot is merging ⏳

#3573 [16.0][IMP] l10n_es_aeat_mod369: account move creation from 369 AEAT model
  l10n_es_aeat_mod369/i18n/es.po
  l10n_es_aeat_mod369/i18n/l10n_es_aeat_mod369.pot
  l10n_es_aeat_mod369/models/mod369.py
  l10n_es_aeat_mod369/tests/test_l10n_es_aeat_mod369.py
Labels: approved, ready to merge, bot is merging ⏳

#3659 [15.0][FIX] delivery_dhl_parcel: show full name
  delivery_dhl_parcel/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#3592 [16.0][FIX] l10n_es_aeat_mod347: Handle traceback on partner selection
  l10n_es_aeat_mod347/models/mod347.py
Labels: bot is merging ⏳

#3570 [17.0][MIG] l10n_es_mis_report: Migration to 17.0
  l10n_es_mis_report/README.rst
  l10n_es_mis_report/__init__.py
  l10n_es_mis_report/__manifest__.py
  l10n_es_mis_report/data/mis_report_balance_abreviated.xml
  l10n_es_mis_report/data/mis_report_balance_normal.xml
  l10n_es_mis_report/data/mis_report_balance_sme.xml
  l10n_es_mis_report/data/mis_report_balance_sme_sfl.xml
  l10n_es_mis_report/data/mis_report_pyg_abreviated.xml
  l10n_es_mis_report/data/mis_report_pyg_normal.xml
  l10n_es_mis_report/data/mis_report_pyg_sme.xml
  l10n_es_mis_report/data/mis_report_pyg_sme_sfl.xml
  l10n_es_mis_report/data/mis_report_revenues_expenses_normal.xml
  l10n_es_mis_report/data/mis_report_styles.xml
  l10n_es_mis_report/i18n/ca.po
  l10n_es_mis_report/i18n/es.po
  l10n_es_mis_report/i18n/l10n_es_mis_report.pot
  l10n_es_mis_report/pyproject.toml
  l10n_es_mis_report/readme/CONTRIBUTORS.md
  l10n_es_mis_report/readme/DESCRIPTION.md
  l10n_es_mis_report/readme/INSTALL.md
  l10n_es_mis_report/readme/USAGE.md
  l10n_es_mis_report/static/description/icon.png
  l10n_es_mis_report/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#3665 [16.0][FIX] l10n_es_payment_order_confirming_sabadell: Fix search domain for Sabadell confirming payment method in bank journal
  l10n_es_payment_order_confirming_sabadell/models/__init__.py
  l10n_es_payment_order_confirming_sabadell/models/account_payment_method.py
Labels: bot is merging ⏳

#3661 [16.0][FIX] l10n_es_aeat_sii_force_type: Apply force type values when invoi…
  l10n_es_aeat_sii_force_type/README.rst
  l10n_es_aeat_sii_force_type/models/account_move.py
  l10n_es_aeat_sii_force_type/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_force_type/static/description/index.html
  l10n_es_aeat_sii_force_type/tests/test_l10n_es_aeat_sii_force_type.py
Labels: approved, bot is merging ⏳

#3071 [16.0][MIG] l10n_es_aeat_sii_invoice_summary: Migration to 16.0
  l10n_es_aeat_sii_invoice_summary/README.rst
  l10n_es_aeat_sii_invoice_summary/__init__.py
  l10n_es_aeat_sii_invoice_summary/__manifest__.py
  l10n_es_aeat_sii_invoice_summary/i18n/es.po
  l10n_es_aeat_sii_invoice_summary/i18n/l10n_es_aeat_sii_invoice_summary.pot
  l10n_es_aeat_sii_invoice_summary/models/__init__.py
  l10n_es_aeat_sii_invoice_summary/models/account_move.py
  l10n_es_aeat_sii_invoice_summary/readme/CONTRIBUTORS.rst
  l10n_es_aeat_sii_invoice_summary/readme/DESCRIPTION.rst
  l10n_es_aeat_sii_invoice_summary/readme/ROADMAP.rst
  l10n_es_aeat_sii_invoice_summary/readme/USAGE.rst
  l10n_es_aeat_sii_invoice_summary/static/description/icon.png
  l10n_es_aeat_sii_invoice_summary/static/description/index.html
  l10n_es_aeat_sii_invoice_summary/tests/__init__.py
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva0_sp_i_s_iva0_ic_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva0_sp_i_s_iva0_ic_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_irpf1_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_irpf1_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_iva0_ns_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_iva0_ns_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_iva21s_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_iva21s_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_req014_s_iva21s_s_req52_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_req014_s_iva21s_s_req52_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva_e_s_iva0_e_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva_e_s_iva0_e_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva0_sp_i_s_iva0_ic_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva0_sp_i_s_iva0_ic_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva10b_s_iva10b_s_iva21s_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva10b_s_iva10b_s_iva21s_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva_e_s_iva0_e_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva_e_s_iva0_e_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/test_l10n_es_aeat_sii_invoice_summary.py
  l10n_es_aeat_sii_invoice_summary/views/account_move_view.xml
  setup/l10n_es_aeat_sii_invoice_summary/odoo/addons/l10n_es_aeat_sii_invoice_summary
  setup/l10n_es_aeat_sii_invoice_summary/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#3664 [16.0][FIX] l10n_es_payment_order_confirming_aef: Fix search domain for AEF confirming payment method in bank journal
  l10n_es_payment_order_confirming_aef/models/__init__.py
  l10n_es_payment_order_confirming_aef/models/account_payment_method.py
Labels: bot is merging ⏳

#3672 [17.0][MIG] l10n_es_aeat_mod130: Migration to version 17.0
  l10n_es_aeat_mod130/README.rst
  l10n_es_aeat_mod130/__init__.py
  l10n_es_aeat_mod130/__manifest__.py
  l10n_es_aeat_mod130/data/aeat_export_mod130_data.xml
  l10n_es_aeat_mod130/doc/DR130e15v12.xls
  l10n_es_aeat_mod130/i18n/bg.po
  l10n_es_aeat_mod130/i18n/ca.po
  l10n_es_aeat_mod130/i18n/ca_ES.po
  l10n_es_aeat_mod130/i18n/cs.po
  l10n_es_aeat_mod130/i18n/en_US.po
  l10n_es_aeat_mod130/i18n/es.po
  l10n_es_aeat_mod130/i18n/es_CO.po
  l10n_es_aeat_mod130/i18n/es_CR.po
  l10n_es_aeat_mod130/i18n/eu.po
  l10n_es_aeat_mod130/i18n/fr.po
  l10n_es_aeat_mod130/i18n/gl.po
  l10n_es_aeat_mod130/i18n/hr.po
  l10n_es_aeat_mod130/i18n/l10n_es_aeat_mod130.pot
  l10n_es_aeat_mod130/i18n/nl.po
  l10n_es_aeat_mod130/i18n/pl.po
  l10n_es_aeat_mod130/i18n/pt.po
  l10n_es_aeat_mod130/i18n/pt_BR.po
  l10n_es_aeat_mod130/i18n/ru.po
  l10n_es_aeat_mod130/i18n/sl.po
  l10n_es_aeat_mod130/i18n/sv.po
  l10n_es_aeat_mod130/i18n/tr.po
  l10n_es_aeat_mod130/i18n/vi.po
  l10n_es_aeat_mod130/models/__init__.py
  l10n_es_aeat_mod130/models/mod130.py
  l10n_es_aeat_mod130/pyproject.toml
  l10n_es_aeat_mod130/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod130/readme/DESCRIPTION.md
  l10n_es_aeat_mod130/readme/ROADMAP.md
  l10n_es_aeat_mod130/security/ir.model.access.csv
  l10n_es_aeat_mod130/security/ir_rule.xml
  l10n_es_aeat_mod130/static/description/icon.png
  l10n_es_aeat_mod130/static/description/icon_source.svg
  l10n_es_aeat_mod130/static/description/index.html
  l10n_es_aeat_mod130/tests/__init__.py
  l10n_es_aeat_mod130/tests/test_l10n_es_aeat_mod130.py
  l10n_es_aeat_mod130/views/mod130_view.xml
Labels: bot is merging ⏳

#3675 [16.0][MIG] l10n_es_aeat_mod130: Migration to version 16.0
  l10n_es_aeat_mod130/README.rst
  l10n_es_aeat_mod130/__init__.py
  l10n_es_aeat_mod130/__manifest__.py
  l10n_es_aeat_mod130/data/aeat_export_mod130_data.xml
  l10n_es_aeat_mod130/doc/DR130e15v12.xls
  l10n_es_aeat_mod130/i18n/bg.po
  l10n_es_aeat_mod130/i18n/ca.po
  l10n_es_aeat_mod130/i18n/ca_ES.po
  l10n_es_aeat_mod130/i18n/cs.po
  l10n_es_aeat_mod130/i18n/en_US.po
  l10n_es_aeat_mod130/i18n/es.po
  l10n_es_aeat_mod130/i18n/es_CO.po
  l10n_es_aeat_mod130/i18n/es_CR.po
  l10n_es_aeat_mod130/i18n/eu.po
  l10n_es_aeat_mod130/i18n/fr.po
  l10n_es_aeat_mod130/i18n/gl.po
  l10n_es_aeat_mod130/i18n/hr.po
  l10n_es_aeat_mod130/i18n/l10n_es_aeat_mod130.pot
  l10n_es_aeat_mod130/i18n/nl.po
  l10n_es_aeat_mod130/i18n/pl.po
  l10n_es_aeat_mod130/i18n/pt.po
  l10n_es_aeat_mod130/i18n/pt_BR.po
  l10n_es_aeat_mod130/i18n/ru.po
  l10n_es_aeat_mod130/i18n/sl.po
  l10n_es_aeat_mod130/i18n/sv.po
  l10n_es_aeat_mod130/i18n/tr.po
  l10n_es_aeat_mod130/i18n/vi.po
  l10n_es_aeat_mod130/models/__init__.py
  l10n_es_aeat_mod130/models/mod130.py
  l10n_es_aeat_mod130/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod130/readme/DESCRIPTION.rst
  l10n_es_aeat_mod130/readme/ROADMAP.rst
  l10n_es_aeat_mod130/security/ir.model.access.csv
  l10n_es_aeat_mod130/security/ir_rule.xml
  l10n_es_aeat_mod130/static/description/icon.png
  l10n_es_aeat_mod130/static/description/icon_source.svg
  l10n_es_aeat_mod130/static/description/index.html
  l10n_es_aeat_mod130/tests/__init__.py
  l10n_es_aeat_mod130/tests/test_l10n_es_aeat_mod130.py
  l10n_es_aeat_mod130/views/mod130_view.xml
  setup/l10n_es_aeat_mod130/odoo/addons/l10n_es_aeat_mod130
  setup/l10n_es_aeat_mod130/setup.py
Labels: bot is merging ⏳

#3674 [17.0][MIG] l10n_es_payment_order_confirming_sabadell: Migration to version 17.0
  l10n_es_payment_order_confirming_sabadell/README.rst
  l10n_es_payment_order_confirming_sabadell/__init__.py
  l10n_es_payment_order_confirming_sabadell/__manifest__.py
  l10n_es_payment_order_confirming_sabadell/data/account_payment_method.xml
  l10n_es_payment_order_confirming_sabadell/i18n/ca.po
  l10n_es_payment_order_confirming_sabadell/i18n/es.po
  l10n_es_payment_order_confirming_sabadell/i18n/l10n_es_payment_order_confirming_sabadell.pot
  l10n_es_payment_order_confirming_sabadell/models/__init__.py
  l10n_es_payment_order_confirming_sabadell/models/account_payment_method.py
  l10n_es_payment_order_confirming_sabadell/models/account_payment_mode.py
  l10n_es_payment_order_confirming_sabadell/models/account_payment_order.py
  l10n_es_payment_order_confirming_sabadell/models/confirming_sabadell.py
  l10n_es_payment_order_confirming_sabadell/pyproject.toml
  l10n_es_payment_order_confirming_sabadell/readme/CONFIGURE.md
  l10n_es_payment_order_confirming_sabadell/readme/CONTRIBUTORS.md
  l10n_es_payment_order_confirming_sabadell/readme/DESCRIPTION.md
  l10n_es_payment_order_confirming_sabadell/readme/USAGE.md
  l10n_es_payment_order_confirming_sabadell/static/description/icon.png
  l10n_es_payment_order_confirming_sabadell/static/description/index.html
  l10n_es_payment_order_confirming_sabadell/tests/__init__.py
  l10n_es_payment_order_confirming_sabadell/tests/test_payment_order_confirming_sabadell.py
  l10n_es_payment_order_confirming_sabadell/views/account_payment_mode_view.xml
Labels: approved, bot is merging ⏳

#3684 [15.0][FIX] l10n_es_aeat_mod303: Allow to do monthly return
  l10n_es_aeat_mod303/models/mod303.py
Labels: bot is merging ⏳

#3686 [16.0][FIX] l10n_es_aeat_sii_oca/l10n_es_intrastat_report: Rename test helper method
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
  l10n_es_aeat_sii_taxfree/tests/test_l10n_es_aeat_sii_taxfree.py
  l10n_es_intrastat_report/tests/test_l10n_es_intrastat_report.py
Labels: bot is merging ⏳

#3685 [16.0][FIX] l10n_es_aeat_mod303: Allow to do monthly return
  l10n_es_aeat_mod303/models/mod303.py
Labels: bot is merging ⏳

#3687 [17.0][IMP] l10n_es_aeat_mod303: Return last period - Including fix
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: bot is merging ⏳
