Repository OCA/l10n-spain, pull requests merged in 2025-02, with the labels that each got.

#3985 [16.0][FIX] l10n_es_aeat_mod390: Calculation of field 85
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
Labels: bot is merging ⏳

#3836 [16.0][IMP] l10n_es_aeat_sii_oca: Improve SII not sent filter to use sii_enabled field
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/models/sii_mixin.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
  l10n_es_aeat_sii_oca/views/account_move_views.xml
Labels: bot is merging ⏳

#3779 [12.0][IMP] l10n_es_aeat_mod303: update 2024-10
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303/readme/ROADMAP.rst
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_mod303/views/mod303_view.xml
  l10n_es_aeat_mod390/README.rst
  l10n_es_aeat_mod390/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#3901 [FIX] [15.0] l10n_es_ticketbai: fix error in post-migration script w…
  l10n_es_ticketbai/migrations/15.0.1.4.6/post-migration.py
Labels: approved

#3935 [16.0] [IMP] l10n_es_ticketai: refactor account.move create method logic and apply model_create_multi decorator
  l10n_es_ticketbai/models/account_move.py
Labels: approved, bot is merging ⏳

#4001 [16.0][FIX] l10n_es_aeat_mod347: Missing non deductible taxes
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
Labels: bot is merging ⏳

#4003 [15.0][FIX] l10n_es_aeat_mod347: Missing non deductible taxes
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
Labels: bot is merging ⏳

#4012 [16.0][FIX] l10n_es_facturae: Activar tests + correcciones de importes
  delivery_gls_asm/tests/__init__.py
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/tests/common.py
  l10n_es_facturae/tests/test_l10n_es_facturae_32.py
  l10n_es_facturae/tests/test_l10n_es_facturae_321.py
  l10n_es_facturae/tests/test_l10n_es_facturae_322.py
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#4011 [16.0][IMP] l10n_es_facturae: Retención de garantía
  l10n_es_facturae/i18n/es.po
  l10n_es_facturae/i18n/l10n_es_facturae.pot
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/tests/common.py
  l10n_es_facturae/views/account_move_view.xml
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#4015 [16.0][IMP] l10n_es_facturae: Importe retención garantía modificable
  l10n_es_facturae/models/account_move.py
Labels: bot is merging ⏳

#4018 [16.0][IMP] l10n_es_facturae_face: we need to check by type, not the id of the record
  l10n_es_facturae_face/tests/test_facturae_face.py
Labels: bot is merging ⏳

#4022 [15.0][FIX] l10n_es_aeat_mod303: Recargo equivalencia 0.5%
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#4021 [16.0][FIX] l10n_es_aeat_mod303: New BOE format 2025
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/docs/DR303e25v101.xlsx
Labels: bot is merging ⏳

#4027 [18.0][MIG] l10n_es_toponyms: Migration to version 18.0
  l10n_es_toponyms/README.rst
  l10n_es_toponyms/__init__.py
  l10n_es_toponyms/__manifest__.py
  l10n_es_toponyms/i18n/bg.po
  l10n_es_toponyms/i18n/ca.po
  l10n_es_toponyms/i18n/cs.po
  l10n_es_toponyms/i18n/de.po
  l10n_es_toponyms/i18n/es.po
  l10n_es_toponyms/i18n/es_CO.po
  l10n_es_toponyms/i18n/es_CR.po
  l10n_es_toponyms/i18n/eu.po
  l10n_es_toponyms/i18n/fr.po
  l10n_es_toponyms/i18n/gl.po
  l10n_es_toponyms/i18n/hr.po
  l10n_es_toponyms/i18n/l10n_es_toponyms.pot
  l10n_es_toponyms/i18n/nl.po
  l10n_es_toponyms/i18n/pl.po
  l10n_es_toponyms/i18n/pt.po
  l10n_es_toponyms/i18n/pt_BR.po
  l10n_es_toponyms/i18n/ru.po
  l10n_es_toponyms/i18n/sl.po
  l10n_es_toponyms/i18n/sv.po
  l10n_es_toponyms/i18n/tr.po
  l10n_es_toponyms/i18n/vi.po
  l10n_es_toponyms/pyproject.toml
  l10n_es_toponyms/readme/CONTRIBUTORS.md
  l10n_es_toponyms/readme/DESCRIPTION.md
  l10n_es_toponyms/readme/INSTALL.md
  l10n_es_toponyms/readme/USAGE.md
  l10n_es_toponyms/security/ir.model.access.csv
  l10n_es_toponyms/static/description/icon.png
  l10n_es_toponyms/static/description/icon.svg
  l10n_es_toponyms/static/description/index.html
  l10n_es_toponyms/tests/__init__.py
  l10n_es_toponyms/tests/test_l10n_es_toponyms.py
  l10n_es_toponyms/wizard/__init__.py
  l10n_es_toponyms/wizard/geonames_import.py
  l10n_es_toponyms/wizard/l10n_es_toponyms_wizard.py
  l10n_es_toponyms/wizard/l10n_es_toponyms_wizard.xml
Labels: bot is merging ⏳

#4028 [16.0][IMP] l10n_es_aeat_mod347_igic: Added IGIC Exento Soportado to map
  l10n_es_aeat_mod347_igic/data/tax_code_map_mod347_igic_data.xml
Labels: bot is merging ⏳

#4032 [16.0][FIX] l10n_es_facturae: traceback error when partner_id has not zip field
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#4004 [16.0][FIX] l10n_es_aeat_mod369: Fix neg_corrections calculation, there could be more that one refund line by country
  l10n_es_aeat_mod369/models/mod369_line_grouped.py
Labels: approved, bot is merging ⏳

#4031 [14.0][FIX] l10n_es_aeat_mod303: New BOE format 2025
  delivery_gls_asm/tests/__init__.py
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/docs/DR303e25v101.xlsx
Labels: approved, bot is merging ⏳

#3996 [17.0][FIX] l10n_es_aeat_mod*: Fix tests related to S_IVA21ISP
  delivery_gls_asm/tests/__init__.py
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
  l10n_es_aeat_mod349/data/aeat.349.map.line.csv
  l10n_es_aeat_mod349/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
  l10n_es_facturae/data/account_tax_template.xml
  l10n_es_facturae/data/template/account.tax-es_common.csv
Labels: bot is merging ⏳

#4002 [17.0][FIX] l10n_es_aeat_mod347: Missing non deductible taxes
  l10n_es_aeat_mod347/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod347/data/l10n.es.aeat.map.tax.line.tax.csv
Labels: bot is merging ⏳

#4026 [17.0][FIX] l10n_es_aeat_mod303: New BOE format 2025
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/docs/DR303e25v101.xlsx
Labels: bot is merging ⏳

#3986 [17.0][IMP] l10n_es_aeat_mod390: Casillas 658 y 84
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: approved, bot is merging ⏳

#4035 [12.0][FIX] l10n_es_aeat_mod303: New BOE format 2025
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/docs/DR303e25v101.xlsx
Labels: approved, bot is merging ⏳

#3658 [17.0][MIG] delivery_dhl_parcel: Migration to 17.0
  delivery_dhl_parcel/README.rst
  delivery_dhl_parcel/__init__.py
  delivery_dhl_parcel/__manifest__.py
  delivery_dhl_parcel/doc/Documento_integracion_WEB_SERVICE_B2B_B2C_ver6.pdf
  delivery_dhl_parcel/i18n/ca.po
  delivery_dhl_parcel/i18n/delivery_dhl_parcel.pot
  delivery_dhl_parcel/i18n/es.po
  delivery_dhl_parcel/models/__init__.py
  delivery_dhl_parcel/models/delivery_carrier.py
  delivery_dhl_parcel/models/dhl_parcel_request.py
  delivery_dhl_parcel/models/sale_order.py
  delivery_dhl_parcel/models/stock_picking.py
  delivery_dhl_parcel/pyproject.toml
  delivery_dhl_parcel/readme/CONFIGURE.md
  delivery_dhl_parcel/readme/CONTRIBUTORS.md
  delivery_dhl_parcel/readme/DESCRIPTION.md
  delivery_dhl_parcel/readme/INSTALL.md
  delivery_dhl_parcel/readme/ROADMAP.md
  delivery_dhl_parcel/readme/USAGE.md
  delivery_dhl_parcel/security/ir.model.access.csv
  delivery_dhl_parcel/static/description/icon.png
  delivery_dhl_parcel/static/description/index.html
  delivery_dhl_parcel/tests/__init__.py
  delivery_dhl_parcel/tests/test_delivery_dhl_parcel.py
  delivery_dhl_parcel/views/delivery_carrier_view.xml
  delivery_dhl_parcel/views/stock_picking_views.xml
  delivery_dhl_parcel/wizard/__init__.py
  delivery_dhl_parcel/wizard/dhl_parcel_end_day_wizard.py
  delivery_dhl_parcel/wizard/dhl_parcel_end_day_wizard_views.xml
Labels: approved, bot is merging ⏳

#4043 [16.0][FIX] l10n_es*: Post-install test + fallback to load CoA
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
  l10n_es_aeat_sii_force_type/tests/test_l10n_es_aeat_sii_force_type.py
  l10n_es_facturae/tests/common.py
  l10n_es_facturae_face/tests/test_facturae_face.py
  l10n_es_payment_order_confirming_sabadell/tests/test_payment_order_confirming_sabadell.py
  l10n_es_sigaus_account/tests/common.py
  l10n_es_ticketbai_api/tests/common.py
Labels: approved, bot is merging ⏳

#3994 [17.0][IMP] l10n_es_aeat: vat_representative by default
  l10n_es_aeat/README.rst
  l10n_es_aeat/i18n/es.po
  l10n_es_aeat/i18n/l10n_es_aeat.pot
  l10n_es_aeat/models/l10n_es_aeat_report.py
  l10n_es_aeat/models/res_company.py
  l10n_es_aeat/readme/CONTRIBUTORS.md
  l10n_es_aeat/static/description/index.html
  l10n_es_aeat/tests/test_l10n_es_aeat_report.py
  l10n_es_aeat/views/res_company_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#4048 [16.0][FIX] l10n_es_aeat_mod303: Avoid negatives in fee to compensate
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
Labels: bot is merging ⏳

#4052 [17.0][IMP]l10n_es_facturae: cambio restricciones Unidad Tramitadora y Oficina Contable
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/tests/common.py
  l10n_es_facturae_face/models/account_move.py
  l10n_es_facturae_face/tests/test_facturae_face.py
Labels: approved, bot is merging ⏳

#4010 [17.0][MIG] l10n_es_vat_book_oss: Migration to 17.0
  l10n_es_vat_book_oss/README.rst
  l10n_es_vat_book_oss/__init__.py
  l10n_es_vat_book_oss/__manifest__.py
  l10n_es_vat_book_oss/i18n/es.po
  l10n_es_vat_book_oss/i18n/l10n_es_vat_book_oss.pot
  l10n_es_vat_book_oss/models/__init__.py
  l10n_es_vat_book_oss/models/aeat_vat_book_map_lines.py
  l10n_es_vat_book_oss/models/l10n_es_vat_book.py
  l10n_es_vat_book_oss/pyproject.toml
  l10n_es_vat_book_oss/readme/CONFIGURE.md
  l10n_es_vat_book_oss/readme/CONTRIBUTORS.md
  l10n_es_vat_book_oss/readme/DESCRIPTION.md
  l10n_es_vat_book_oss/readme/INSTALL.md
  l10n_es_vat_book_oss/readme/USAGE.md
  l10n_es_vat_book_oss/static/description/icon.png
  l10n_es_vat_book_oss/static/description/index.html
  l10n_es_vat_book_oss/tests/__init__.py
  l10n_es_vat_book_oss/tests/test_l10n_es_aeat_vat_book_oss.py
Labels: approved, bot is merging ⏳

#4025 [16.0][IMP] l10n_es_facturae: Restar el importe de retención de garantía del total
  l10n_es_facturae/tests/common.py
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#4053 [17.0][IMP] l10n_es_facturae: Retención de garantía
  l10n_es_facturae/i18n/es.po
  l10n_es_facturae/i18n/l10n_es_facturae.pot
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/tests/common.py
  l10n_es_facturae/views/account_move_view.xml
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#4054 [16.0][FIX] l10n_es_atc_mod415: Added IGIC Exento Soportado to map
  l10n_es_atc_mod415/data/tax_code_map_mod415_data.xml
Labels: bot is merging ⏳
