Repository OCA/l10n-spain, pull requests merged in 2025-05, with the labels that each got.

#4154 [16.0][IMP] l10n_es_sigaus_account: add sigaus_subject option in partner
  l10n_es_sigaus_account/__manifest__.py
  l10n_es_sigaus_account/models/__init__.py
  l10n_es_sigaus_account/models/account_move.py
  l10n_es_sigaus_account/models/res_partner.py
  l10n_es_sigaus_account/models/sigaus_mixin.py
  l10n_es_sigaus_account/tests/common.py
  l10n_es_sigaus_account/tests/test_l10n_es_sigaus_account.py
  l10n_es_sigaus_account/views/res_partner.xml
  l10n_es_sigaus_purchase/models/purchase_order.py
  l10n_es_sigaus_sale/models/sale_order.py
Labels: bot is merging ⏳

#4176 [16.0][IMP] l10n_es_aeat_mod347: Field Not in mod347 in partner converted to company dependent
  l10n_es_aeat_mod347/__manifest__.py
  l10n_es_aeat_mod347/migrations/16.0.1.11.5/post-migration.py
  l10n_es_aeat_mod347/migrations/16.0.1.11.5/pre-migration.py
  l10n_es_aeat_mod347/models/res_partner.py
Labels: bot is merging ⏳

#3870 [17.0][MIG] l10n_es_atc_mod415: Migration to 17.0
  l10n_es_atc_mod415/README.rst
  l10n_es_atc_mod415/__init__.py
  l10n_es_atc_mod415/__manifest__.py
  l10n_es_atc_mod415/data/l10n.es.aeat.map.tax.csv
  l10n_es_atc_mod415/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_atc_mod415/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_atc_mod415/data/mail_template_data.xml
  l10n_es_atc_mod415/i18n/es.po
  l10n_es_atc_mod415/i18n/l10n_es_atc_mod415.pot
  l10n_es_atc_mod415/models/__init__.py
  l10n_es_atc_mod415/models/account_move.py
  l10n_es_atc_mod415/models/mod415.py
  l10n_es_atc_mod415/models/res_partner.py
  l10n_es_atc_mod415/pyproject.toml
  l10n_es_atc_mod415/readme/CONTRIBUTORS.md
  l10n_es_atc_mod415/readme/DESCRIPTION.md
  l10n_es_atc_mod415/readme/INSTALL.md
  l10n_es_atc_mod415/security/ir.model.access.csv
  l10n_es_atc_mod415/security/mod_415_security.xml
  l10n_es_atc_mod415/static/description/icon.png
  l10n_es_atc_mod415/static/description/index.html
  l10n_es_atc_mod415/tests/__init__.py
  l10n_es_atc_mod415/tests/test_l10n_es_atc_mod415.py
  l10n_es_atc_mod415/views/account_move_view.xml
  l10n_es_atc_mod415/views/mod415_templates.xml
  l10n_es_atc_mod415/views/mod415_view.xml
  l10n_es_atc_mod415/views/report_415_partner.xml
  l10n_es_atc_mod415/views/res_partner_view.xml
Labels: bot is merging ⏳

#4179 [17.0][MIG] l10n_es_aeat_sii_invoice_summary
  l10n_es_aeat_sii_invoice_summary/README.rst
  l10n_es_aeat_sii_invoice_summary/__init__.py
  l10n_es_aeat_sii_invoice_summary/__manifest__.py
  l10n_es_aeat_sii_invoice_summary/i18n/es.po
  l10n_es_aeat_sii_invoice_summary/i18n/l10n_es_aeat_sii_invoice_summary.pot
  l10n_es_aeat_sii_invoice_summary/models/__init__.py
  l10n_es_aeat_sii_invoice_summary/models/account_move.py
  l10n_es_aeat_sii_invoice_summary/pyproject.toml
  l10n_es_aeat_sii_invoice_summary/readme/CONTRIBUTORS.md
  l10n_es_aeat_sii_invoice_summary/readme/DESCRIPTION.md
  l10n_es_aeat_sii_invoice_summary/readme/ROADMAP.md
  l10n_es_aeat_sii_invoice_summary/readme/USAGE.md
  l10n_es_aeat_sii_invoice_summary/static/description/icon.png
  l10n_es_aeat_sii_invoice_summary/static/description/index.html
  l10n_es_aeat_sii_invoice_summary/tests/__init__.py
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva0_sp_i_s_iva0_g_i_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva0_sp_i_s_iva0_g_i_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_irpf1_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_irpf1_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_iva0_ns_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_iva0_ns_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_iva21s_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_iva21s_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_req014_s_iva21s_s_req52_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_s_req014_s_iva21s_s_req52_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva10b_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva_e_s_iva0_g_e_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_invoice_s_iva_e_s_iva0_g_e_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva0_sp_i_s_iva0_g_i_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva0_sp_i_s_iva0_g_i_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva10b_s_iva10b_s_iva21s_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva10b_s_iva10b_s_iva21s_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva_e_s_iva0_g_e_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/json/sii_out_refund_s_iva_e_s_iva0_g_e_same_dict.json
  l10n_es_aeat_sii_invoice_summary/tests/test_l10n_es_aeat_sii_invoice_summary.py
  l10n_es_aeat_sii_invoice_summary/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#4191 [17.0][MIG] l10n_es_aeat_mod216: Migration to version 17.0
  l10n_es_aeat_mod216/README.rst
  l10n_es_aeat_mod216/__init__.py
  l10n_es_aeat_mod216/__manifest__.py
  l10n_es_aeat_mod216/data/aeat_export_mod216_data.xml
  l10n_es_aeat_mod216/data/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod216/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod216/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod216/docs/DR-216e16_v1.06.pdf
  l10n_es_aeat_mod216/i18n/bg.po
  l10n_es_aeat_mod216/i18n/ca.po
  l10n_es_aeat_mod216/i18n/cs.po
  l10n_es_aeat_mod216/i18n/de.po
  l10n_es_aeat_mod216/i18n/es.po
  l10n_es_aeat_mod216/i18n/es_CO.po
  l10n_es_aeat_mod216/i18n/es_CR.po
  l10n_es_aeat_mod216/i18n/es_ES.po
  l10n_es_aeat_mod216/i18n/eu.po
  l10n_es_aeat_mod216/i18n/fr.po
  l10n_es_aeat_mod216/i18n/gl.po
  l10n_es_aeat_mod216/i18n/hr.po
  l10n_es_aeat_mod216/i18n/l10n_es_aeat_mod216.pot
  l10n_es_aeat_mod216/i18n/nl.po
  l10n_es_aeat_mod216/i18n/pl.po
  l10n_es_aeat_mod216/i18n/pt.po
  l10n_es_aeat_mod216/i18n/pt_BR.po
  l10n_es_aeat_mod216/i18n/ru.po
  l10n_es_aeat_mod216/i18n/sl.po
  l10n_es_aeat_mod216/i18n/sv.po
  l10n_es_aeat_mod216/i18n/tr.po
  l10n_es_aeat_mod216/i18n/vi.po
  l10n_es_aeat_mod216/models/__init__.py
  l10n_es_aeat_mod216/models/mod216.py
  l10n_es_aeat_mod216/pyproject.toml
  l10n_es_aeat_mod216/readme/CONFIGURE.md
  l10n_es_aeat_mod216/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod216/readme/DESCRIPTION.md
  l10n_es_aeat_mod216/readme/USAGE.md
  l10n_es_aeat_mod216/security/ir.model.access.csv
  l10n_es_aeat_mod216/security/ir_rule.xml
  l10n_es_aeat_mod216/static/description/icon.png
  l10n_es_aeat_mod216/static/description/icon_source.svg
  l10n_es_aeat_mod216/static/description/index.html
  l10n_es_aeat_mod216/tests/__init__.py
  l10n_es_aeat_mod216/tests/test_l10n_es_aeat_mod216.py
  l10n_es_aeat_mod216/views/mod216_view.xml
Labels: bot is merging ⏳

#3947 [15.0][IMP] l10n_es_aeat_mod390 - Include fields 31, 32 in 2024 tax mapping and add support for fields 45, 46
  l10n_es_aeat_mod390/data/2024/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/2024/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/models/account_move.py
  l10n_es_aeat_mod390/models/mod390.py
Labels: approved, ready to merge, bot is merging ⏳

#4194 [17.0][IMP] l10n_es_aeat_mod390 - Include fields 31, 32 in 2024 tax mapping and add support for fields 45, 46
  l10n_es_aeat_mod390/README.rst
  l10n_es_aeat_mod390/data/2024/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/2024/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod390/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod390/models/__init__.py
  l10n_es_aeat_mod390/models/account_move.py
  l10n_es_aeat_mod390/models/l10n_es_aeat_map_tax_line.py
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/readme/ROADMAP.md
  l10n_es_aeat_mod390/static/description/index.html
Labels: bot is merging ⏳

#4192 [17.0][MIG] l10n_es_aeat_mod296: Migration to version 17.0
  l10n_es_aeat_mod296/README.rst
  l10n_es_aeat_mod296/__init__.py
  l10n_es_aeat_mod296/__manifest__.py
  l10n_es_aeat_mod296/data/aeat_export_mod296_data.xml
  l10n_es_aeat_mod296/data/aeat_export_mod296_line_data.xml
  l10n_es_aeat_mod296/data/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod296/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod296/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod296/docs/DR296_2017.pdf
  l10n_es_aeat_mod296/docs/instrucciones_296.pdf
  l10n_es_aeat_mod296/docs/register_design_296_2008.pdf
  l10n_es_aeat_mod296/i18n/es.po
  l10n_es_aeat_mod296/i18n/l10n_es_aeat_mod296.pot
  l10n_es_aeat_mod296/models/__init__.py
  l10n_es_aeat_mod296/models/mod296.py
  l10n_es_aeat_mod296/pyproject.toml
  l10n_es_aeat_mod296/readme/CONFIGURE.md
  l10n_es_aeat_mod296/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod296/readme/DESCRIPTION.md
  l10n_es_aeat_mod296/readme/USAGE.md
  l10n_es_aeat_mod296/security/ir.model.access.csv
  l10n_es_aeat_mod296/security/ir_rule.xml
  l10n_es_aeat_mod296/static/description/icon.png
  l10n_es_aeat_mod296/static/description/icon_source.svg
  l10n_es_aeat_mod296/static/description/index.html
  l10n_es_aeat_mod296/tests/__init__.py
  l10n_es_aeat_mod296/tests/test_l10n_es_aeat_mod296.py
  l10n_es_aeat_mod296/views/mod296_views.xml
Labels: bot is merging ⏳

#4199 [16.0][IMP] l10n_es_aeat_mod216: version 2024
  l10n_es_aeat_mod216/README.rst
  l10n_es_aeat_mod216/__manifest__.py
  l10n_es_aeat_mod216/data/2016/aeat_export_mod216_data.xml
  l10n_es_aeat_mod216/data/2016/tax_code_map_mod216_data.xml
  l10n_es_aeat_mod216/data/2024/aeat.model.export.config.csv
  l10n_es_aeat_mod216/data/2024/aeat.model.export.config.line.csv
  l10n_es_aeat_mod216/data/2024/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod216/data/2024/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod216/i18n/es.po
  l10n_es_aeat_mod216/i18n/l10n_es_aeat_mod216.pot
  l10n_es_aeat_mod216/migrations/16.0.1.3.0/pre-migrate.py
  l10n_es_aeat_mod216/models/mod216.py
  l10n_es_aeat_mod216/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod216/readme/USAGE.rst
  l10n_es_aeat_mod216/static/description/index.html
  l10n_es_aeat_mod216/tests/test_l10n_es_aeat_mod216.py
  l10n_es_aeat_mod216/views/mod216_view.xml
Labels: bot is merging ⏳

#4208 [17.0][FIX] delivery_gls_asm: fix obsolete link
  delivery_gls_asm/models/gls_asm_master_data.py
Labels: approved, bot is merging ⏳

#4210 [14.0][FIX] delivery_gls_asm: fix obsolete link
  delivery_gls_asm/models/gls_asm_master_data.py
Labels: approved, bot is merging ⏳
