Repository OCA/l10n-spain, pull requests merged in 2025-04, with the labels that each got.

#4111 [16.0][IMP] l10n_es_partner: Inject the field search more elegantly
  l10n_es_partner/models/res_partner.py
Labels: bot is merging ⏳

#4112 [17.0][IMP] l10n_es_partner: Inject the field search more elegantly
  l10n_es_partner/models/res_partner.py
Labels: bot is merging ⏳

#4105 [16.0][IMP] l10n_es_account_statement_import_n43: avoid use of retrieve_partner as we are already searching the partner
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
Labels: approved, bot is merging ⏳

#4114 [16.0][MIG] l10n_es_ticketbai_oss: Migration to 16.0
  l10n_es_ticketbai_oss/README.rst
  l10n_es_ticketbai_oss/__init__.py
  l10n_es_ticketbai_oss/__manifest__.py
  l10n_es_ticketbai_oss/data/vat_regime_key_data.xml
  l10n_es_ticketbai_oss/i18n/es.po
  l10n_es_ticketbai_oss/i18n/l10n_es_ticketbai_oss.pot
  l10n_es_ticketbai_oss/models/__init__.py
  l10n_es_ticketbai_oss/models/ticketbai_invoice_tax.py
  l10n_es_ticketbai_oss/readme/CONFIGURE.rst
  l10n_es_ticketbai_oss/readme/CONTRIBUTORS.rst
  l10n_es_ticketbai_oss/readme/DESCRIPTION.rst
  l10n_es_ticketbai_oss/readme/INSTALL.rst
  l10n_es_ticketbai_oss/static/description/icon.png
  l10n_es_ticketbai_oss/static/description/index.html
  l10n_es_ticketbai_oss/tests/__init__.py
  l10n_es_ticketbai_oss/tests/test_invoice_oss.py
  setup/l10n_es_ticketbai_oss/odoo/addons/l10n_es_ticketbai_oss
  setup/l10n_es_ticketbai_oss/setup.py
Labels: bot is merging ⏳

#4116 [16.0][FIX] l10n_es_partner: display address with commercial name
  l10n_es_partner/models/res_partner.py
  l10n_es_partner/tests/test_l10n_es_partner.py
Labels: bot is merging ⏳

#4106 [18.0][MIG] l10n_es_partner_mercantil: Migration to 18.0
  l10n_es_partner_mercantil/README.rst
  l10n_es_partner_mercantil/__init__.py
  l10n_es_partner_mercantil/__manifest__.py
  l10n_es_partner_mercantil/i18n/bg.po
  l10n_es_partner_mercantil/i18n/ca.po
  l10n_es_partner_mercantil/i18n/es.po
  l10n_es_partner_mercantil/i18n/eu.po
  l10n_es_partner_mercantil/i18n/fr.po
  l10n_es_partner_mercantil/i18n/gl.po
  l10n_es_partner_mercantil/i18n/hr.po
  l10n_es_partner_mercantil/i18n/l10n_es_partner_mercantil.pot
  l10n_es_partner_mercantil/i18n/nl.po
  l10n_es_partner_mercantil/i18n/pt.po
  l10n_es_partner_mercantil/i18n/pt_BR.po
  l10n_es_partner_mercantil/i18n/sl.po
  l10n_es_partner_mercantil/models/__init__.py
  l10n_es_partner_mercantil/models/partner_es.py
  l10n_es_partner_mercantil/pyproject.toml
  l10n_es_partner_mercantil/readme/CONTRIBUTORS.md
  l10n_es_partner_mercantil/readme/DESCRIPTION.md
  l10n_es_partner_mercantil/readme/USAGE.md
  l10n_es_partner_mercantil/static/description/icon.png
  l10n_es_partner_mercantil/static/description/icon.svg
  l10n_es_partner_mercantil/static/description/index.html
  l10n_es_partner_mercantil/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#4119 [16.0][FIX] l10n_es_ticketbai_oss: recover code removed by mistake
  l10n_es_ticketbai_oss/models/ticketbai_invoice_tax.py
Labels: bot is merging ⏳

#4120 [16.0][FIX] l10n_es_partner: prevent replacing multiple times
  l10n_es_partner/models/res_partner.py
  l10n_es_partner/tests/test_l10n_es_partner.py
Labels: approved, bot is merging ⏳

#4118 [17.0][FIX] l10n_es_facturae: Taxes withheld need to be divided by 100, just like taxes
  l10n_es_facturae/views/report_facturae.xml
Labels: approved, bot is merging ⏳

#4122 [16.0][FIX] l10n_es_facturae: Taxes withheld need to be divided by 100, just like taxes
  l10n_es_facturae/views/report_facturae.xml
Labels: bot is merging ⏳

#4125 [16.0][FIX] l10n_es_facturae: Use AEAT test
  l10n_es_facturae/tests/common.py
Labels: bot is merging ⏳

#4117 [15.0][FIX] l10n_es_aeat: Consider Northern Ireland as European
  l10n_es_aeat/models/res_partner.py
Labels: bot is merging ⏳

#4131 [16.0][FIX] l10n_es_partner: Contact name may be empty
  l10n_es_partner/models/res_partner.py
Labels: bot is merging ⏳

#4128 [16.0][FIX] l10n_es_aeat: Consider Northern Ireland as European
  l10n_es_aeat/models/res_partner.py
Labels: bot is merging ⏳

#4129 [17.0][FIX] l10n_es_aeat: Consider Northern Ireland as European
  l10n_es_aeat/models/res_partner.py
Labels: bot is merging ⏳

#4104 [17.0][ADD] l10n_es_vat_book_pos: New module l10n_es_vat_book_pos
  l10n_es_vat_book_pos/README.rst
  l10n_es_vat_book_pos/__init__.py
  l10n_es_vat_book_pos/__manifest__.py
  l10n_es_vat_book_pos/models/__init__.py
  l10n_es_vat_book_pos/models/l10n_es_vat_book.py
  l10n_es_vat_book_pos/pyproject.toml
  l10n_es_vat_book_pos/readme/CONTRIBUTORS.md
  l10n_es_vat_book_pos/readme/DESCRIPTION.md
  l10n_es_vat_book_pos/static/description/icon.png
  l10n_es_vat_book_pos/static/description/icon.svg
  l10n_es_vat_book_pos/static/description/index.html
  l10n_es_vat_book_pos/tests/__init__.py
  l10n_es_vat_book_pos/tests/test_vat_book_pos.py
Labels: approved, bot is merging ⏳

#4109 [16.0][FIX] l10n_es_intrastat_report: Incompatibility with other intrastat
  l10n_es_intrastat_report/README.rst
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
  l10n_es_intrastat_report/readme/CONTRIBUTORS.rst
  l10n_es_intrastat_report/static/description/index.html
  l10n_es_intrastat_report/views/l10n_es_intrastat_product.xml
Labels: approved, bot is merging ⏳

#4132 [17.0][FIX] l10n_es_aeat_mod347: Proper view inheritance
  l10n_es_aeat_mod347/views/res_partner_view.xml
Labels: bot is merging ⏳

#4134 [15.0][FIX] l10n_es_aeat_mod347: Proper view inheritance
  l10n_es_aeat_mod347/views/res_partner_view.xml
Labels: bot is merging ⏳

#4133 [16.0][FIX] l10n_es_aeat_mod347: Proper view inheritance
  l10n_es_aeat_mod347/views/res_partner_view.xml
Labels: bot is merging ⏳

#4130 [16.0][FIX] l10n_es_facturae: The city field in the partner is required for the FacturaE process. If the user does not provide it, document generation fails and module crashes.
  l10n_es_facturae/models/res_partner.py
Labels: approved, bot is merging ⏳

#4135 [17.0][FIX] l10n_es_facturae: The city field in the partner is required for the FacturaE process. If the user does not provide it, document generation fails and module crashes.
  l10n_es_facturae/models/res_partner.py
Labels: approved, merged 🎉

#3998 [18.0][MIG] l10n_es_partner: Migration to 18.0
  l10n_es_partner/README.rst
  l10n_es_partner/__init__.py
  l10n_es_partner/__manifest__.py
  l10n_es_partner/data/l10n_es_partner_data.xml
  l10n_es_partner/gen_src/README.rst
  l10n_es_partner/gen_src/REGBANESP_CONESTAB_A.xls
  l10n_es_partner/gen_src/__init__.py
  l10n_es_partner/gen_src/bics.xls
  l10n_es_partner/gen_src/gen_data_banks.py
  l10n_es_partner/i18n/bg.po
  l10n_es_partner/i18n/ca.po
  l10n_es_partner/i18n/cs.po
  l10n_es_partner/i18n/de.po
  l10n_es_partner/i18n/es.po
  l10n_es_partner/i18n/es_CO.po
  l10n_es_partner/i18n/es_CR.po
  l10n_es_partner/i18n/es_ES.po
  l10n_es_partner/i18n/eu.po
  l10n_es_partner/i18n/fr.po
  l10n_es_partner/i18n/gl.po
  l10n_es_partner/i18n/hr.po
  l10n_es_partner/i18n/l10n_es_partner.pot
  l10n_es_partner/i18n/nl.po
  l10n_es_partner/i18n/pl.po
  l10n_es_partner/i18n/pt.po
  l10n_es_partner/i18n/pt_BR.po
  l10n_es_partner/i18n/ru.po
  l10n_es_partner/i18n/sl.po
  l10n_es_partner/i18n/sv.po
  l10n_es_partner/i18n/tr.po
  l10n_es_partner/i18n/vi.po
  l10n_es_partner/models/__init__.py
  l10n_es_partner/models/res_bank.py
  l10n_es_partner/models/res_partner.py
  l10n_es_partner/pyproject.toml
  l10n_es_partner/readme/CONFIGURE.md
  l10n_es_partner/readme/CONTRIBUTORS.md
  l10n_es_partner/readme/DESCRIPTION.md
  l10n_es_partner/readme/INSTALL.md
  l10n_es_partner/readme/ROADMAP.md
  l10n_es_partner/security/ir.model.access.csv
  l10n_es_partner/static/description/bank.svg
  l10n_es_partner/static/description/icon.png
  l10n_es_partner/static/description/index.html
  l10n_es_partner/tests/__init__.py
  l10n_es_partner/tests/test_l10n_es_partner.py
  l10n_es_partner/views/res_bank_view.xml
  l10n_es_partner/views/res_partner_view.xml
  l10n_es_partner/wizard/__init__.py
  l10n_es_partner/wizard/data_banks.xml
  l10n_es_partner/wizard/l10n_es_partner_wizard.py
  l10n_es_partner/wizard/l10n_es_partner_wizard.xml
Labels: bot is merging ⏳

#4136 [16.0][FIX] l10n_es_intrastat_report: Conflicting UserError incompatibility
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
Labels: approved, bot is merging ⏳

#4137 [17.0][FIX] l10n_es_aeat: post_install report tests
  l10n_es_aeat/tests/test_l10n_es_aeat_report.py
Labels: bot is merging ⏳

#4139 [17.0][FIX] l10n_es_igic_reav: xmlid rename
  l10n_es_igic_reav/data/template/account.fiscal.position-es_pymes_canary.csv
Labels: approved, bot is merging ⏳

#4143 [17.0] [FIX] l10n_es_facturae: Use AEAT test
  l10n_es_facturae/tests/common.py
Labels: approved, bot is merging ⏳

#4144 [17.0][I18N] l10n_es_*: Remove es_ES + clean equivalent po
  l10n_es_account_banking_sepa_fsdd/i18n/es.po
  l10n_es_account_banking_sepa_fsdd/i18n/es_ES.po
  l10n_es_aeat_mod111/i18n/es_ES.po
  l10n_es_aeat_mod123/i18n/es.po
  l10n_es_aeat_mod123/i18n/es_ES.po
  l10n_es_partner/i18n/es_ES.po
Labels: bot is merging ⏳

#4145 [16.0] [FIX] l10n_es_aeat_mod_130: Error in referenced field of the result of declaration
  l10n_es_aeat_mod130/data/aeat_export_mod130_data.xml
Labels: bot is merging ⏳

#3956 [15.0][IMP] l10n_es_aeat_mod390_oss: Add field 126 to BOE export
  l10n_es_aeat_mod390_oss/__manifest__.py
  l10n_es_aeat_mod390_oss/data/aeat_export_mod390_sub06_data.xml
  l10n_es_aeat_mod390_oss/static/description/index.html
Labels: approved, bot is merging ⏳

#4147 [17.0] [FIX] l10n_es_aeat_mod_130: Error in referenced field of the result of declaration
  l10n_es_aeat_mod130/data/aeat_export_mod130_data.xml
Labels: bot is merging ⏳

#3932 [15.0][IMP] l10n_es_aeat_mod390_oss: include lines oss in map mod390 2024
  l10n_es_aeat_mod390_oss/__manifest__.py
  l10n_es_aeat_mod390_oss/data/2023/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390_oss/data/2024/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390_oss/models/mod390.py
Labels: approved, bot is merging ⏳

#4146 [18.0][MIG] l10n_es_account_statement_import_n43: Migration to 18.0
  l10n_es_account_statement_import_n43/README.rst
  l10n_es_account_statement_import_n43/__init__.py
  l10n_es_account_statement_import_n43/__manifest__.py
  l10n_es_account_statement_import_n43/doc/norma_43_castellano.pdf
  l10n_es_account_statement_import_n43/i18n/ca.po
  l10n_es_account_statement_import_n43/i18n/es.po
  l10n_es_account_statement_import_n43/i18n/eu.po
  l10n_es_account_statement_import_n43/i18n/fr.po
  l10n_es_account_statement_import_n43/i18n/gl.po
  l10n_es_account_statement_import_n43/i18n/l10n_es_account_bank_statement_import_n43.pot
  l10n_es_account_statement_import_n43/i18n/l10n_es_account_statement_import_n43.pot
  l10n_es_account_statement_import_n43/i18n/sl.po
  l10n_es_account_statement_import_n43/models/__init__.py
  l10n_es_account_statement_import_n43/models/account_journal.py
  l10n_es_account_statement_import_n43/pyproject.toml
  l10n_es_account_statement_import_n43/readme/CONTRIBUTORS.md
  l10n_es_account_statement_import_n43/readme/DESCRIPTION.md
  l10n_es_account_statement_import_n43/readme/ROADMAP.md
  l10n_es_account_statement_import_n43/readme/USAGE.md
  l10n_es_account_statement_import_n43/static/description/icon.png
  l10n_es_account_statement_import_n43/static/description/icon_src.svg
  l10n_es_account_statement_import_n43/static/description/index.html
  l10n_es_account_statement_import_n43/tests/__init__.py
  l10n_es_account_statement_import_n43/tests/test.n43
  l10n_es_account_statement_import_n43/tests/test_l10n_es_account_bank_statement_import_n43.py
  l10n_es_account_statement_import_n43/tests/testmulti.n43
  l10n_es_account_statement_import_n43/views/account_journal_views.xml
  l10n_es_account_statement_import_n43/wizards/__init__.py
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
  l10n_es_account_statement_import_n43/wizards/account_statement_import_view.xml
  requirements.txt
Labels: bot is merging ⏳

#3810 [16.0][MIG] delivery_seur_atlas: Migration to 16.0
  delivery_seur_atlas/README.rst
  delivery_seur_atlas/__init__.py
  delivery_seur_atlas/__manifest__.py
  delivery_seur_atlas/i18n/delivery_seur_atlas.pot
  delivery_seur_atlas/i18n/es.po
  delivery_seur_atlas/models/__init__.py
  delivery_seur_atlas/models/delivery_carrier.py
  delivery_seur_atlas/models/seur_master_data.py
  delivery_seur_atlas/models/seur_request_atlas.py
  delivery_seur_atlas/readme/CONFIGURE.md
  delivery_seur_atlas/readme/CONTEXT.md
  delivery_seur_atlas/readme/CONTRIBUTORS.md
  delivery_seur_atlas/readme/DESCRIPTION.md
  delivery_seur_atlas/readme/INSTALL.md
  delivery_seur_atlas/readme/ROADMAP.md
  delivery_seur_atlas/readme/USAGE.md
  delivery_seur_atlas/static/description/icon.png
  delivery_seur_atlas/static/description/index.html
  delivery_seur_atlas/tests/__init__.py
  delivery_seur_atlas/tests/test_delivery_seur_atlas.py
  delivery_seur_atlas/views/delivery_carrier_views.xml
  setup/delivery_seur_atlas/odoo/addons/delivery_seur_atlas
  setup/delivery_seur_atlas/setup.py
Labels: bot is merging ⏳, stale

#4170 [14.0][FIX] l10n_es_aeat: Take into account inactive tax templates
  l10n_es_aeat/models/l10n_es_aeat_report_tax_mapping.py
  l10n_es_aeat/views/aeat_tax_code_mapping_view.xml
Labels: bot is merging ⏳

#4167 [17.0][IMP] l10n_es_aeat_mod190: Compute deductible expenses
  l10n_es_aeat_mod190/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod190/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
  l10n_es_aeat_mod190/tests/test_mod190.py
  l10n_es_aeat_mod190/views/mod190_line_view.xml
Labels: bot is merging ⏳
