Repository OCA/l10n-spain, pull requests merged in 2025-06, with the labels that each got.

#4214 [17.0] [FIX] l10n_es_aeat_sii_oca: make some fields copy=False
  l10n_es_aeat_sii_oca/models/sii_mixin.py
Labels: bot is merging ⏳

#4216 [17.0] [IMP] l10n_es_aeat_sii_oca: add sii_start_date config option to company
  l10n_es_aeat_sii_oca/models/account_move.py
  l10n_es_aeat_sii_oca/models/res_company.py
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
  l10n_es_aeat_sii_oca/views/res_company_view.xml
Labels: approved, bot is merging ⏳

#4201 [17.0][IMP] l10n_es_aeat: Allow set tax agency by journal
  l10n_es_aeat/data/aeat_tax_agency_data.xml
  l10n_es_aeat/models/account_journal.py
  l10n_es_aeat/views/account_journal_view.xml
Labels: approved, bot is merging ⏳

#4212 [17.0][IMP] l10n_es_aeat*: cambio de menu a declaraciones con submenus por agencia
  l10n_es_aeat/i18n/es.po
  l10n_es_aeat/i18n/eu.po
  l10n_es_aeat/i18n/l10n_es_aeat.pot
  l10n_es_aeat/views/aeat_menuitem.xml
  l10n_es_aeat_mod111/views/mod111_view.xml
  l10n_es_aeat_mod115/views/mod115_view.xml
  l10n_es_aeat_mod123/views/mod123_view.xml
  l10n_es_aeat_mod130/views/mod130_view.xml
  l10n_es_aeat_mod190/views/mod190_view.xml
  l10n_es_aeat_mod216/views/mod216_view.xml
  l10n_es_aeat_mod296/views/mod296_views.xml
  l10n_es_aeat_mod303/views/mod303_view.xml
  l10n_es_aeat_mod347/views/mod347_view.xml
  l10n_es_aeat_mod349/views/mod349_view.xml
  l10n_es_aeat_mod390/views/mod390_view.xml
  l10n_es_aeat_mod592/views/mod592_views.xml
  l10n_es_aeat_sii_match/views/aeat_sii_match_report.xml
  l10n_es_vat_book/views/l10n_es_vat_book.xml
Labels: bot is merging ⏳

#4228 [18.0][FIX] l10n_es_aeat: post_install report tests
  l10n_es_aeat/tests/test_l10n_es_aeat_report.py
Labels: bot is merging ⏳

#4230 [18.0][MIG] l10n_es_aeat_mod303: Migration to 18.0
  l10n_es_aeat_mod303/README.rst
  l10n_es_aeat_mod303/__init__.py
  l10n_es_aeat_mod303/__manifest__.py
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2022/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2023/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.account.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.csv
  l10n_es_aeat_mod303/data/2024-10/aeat.model.export.config.line.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod303/data/l10n.es.aeat.mod303.report.activity.code.csv
  l10n_es_aeat_mod303/docs/DR303e23.xlsx
  l10n_es_aeat_mod303/docs/DR303e24v200.xlsx
  l10n_es_aeat_mod303/docs/DR303e25v101.xlsx
  l10n_es_aeat_mod303/i18n/bg.po
  l10n_es_aeat_mod303/i18n/ca.po
  l10n_es_aeat_mod303/i18n/cs.po
  l10n_es_aeat_mod303/i18n/de.po
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/es_CO.po
  l10n_es_aeat_mod303/i18n/es_CR.po
  l10n_es_aeat_mod303/i18n/eu.po
  l10n_es_aeat_mod303/i18n/fr.po
  l10n_es_aeat_mod303/i18n/gl.po
  l10n_es_aeat_mod303/i18n/hr.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/i18n/nl.po
  l10n_es_aeat_mod303/i18n/pl.po
  l10n_es_aeat_mod303/i18n/pt.po
  l10n_es_aeat_mod303/i18n/pt_BR.po
  l10n_es_aeat_mod303/i18n/sl.po
  l10n_es_aeat_mod303/i18n/sv.po
  l10n_es_aeat_mod303/i18n/tr.po
  l10n_es_aeat_mod303/i18n/vi.po
  l10n_es_aeat_mod303/models/__init__.py
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/pyproject.toml
  l10n_es_aeat_mod303/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod303/readme/DESCRIPTION.md
  l10n_es_aeat_mod303/readme/ROADMAP.md
  l10n_es_aeat_mod303/security/ir.model.access.csv
  l10n_es_aeat_mod303/security/l10n_es_aeat_mod303_security.xml
  l10n_es_aeat_mod303/static/description/icon.png
  l10n_es_aeat_mod303/static/description/icon_source.svg
  l10n_es_aeat_mod303/static/description/index.html
  l10n_es_aeat_mod303/tests/__init__.py
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
  l10n_es_aeat_mod303/views/l10n_es_aeat_mod303_report_activity_code_data_views.xml
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: bot is merging ⏳

#4023 [18.0][MIG] account_promissory_note_caixabank: Migration to 18.0
  account_promissory_note_caixabank/README.rst
  account_promissory_note_caixabank/__init__.py
  account_promissory_note_caixabank/__manifest__.py
  account_promissory_note_caixabank/i18n/account_promissory_note_caixabank.pot
  account_promissory_note_caixabank/i18n/ca.po
  account_promissory_note_caixabank/i18n/es.po
  account_promissory_note_caixabank/models/__init__.py
  account_promissory_note_caixabank/models/res_company.py
  account_promissory_note_caixabank/pyproject.toml
  account_promissory_note_caixabank/readme/CONFIGURE.md
  account_promissory_note_caixabank/readme/CONTRIBUTORS.md
  account_promissory_note_caixabank/readme/DESCRIPTION.md
  account_promissory_note_caixabank/readme/USAGE.md
  account_promissory_note_caixabank/report/__init__.py
  account_promissory_note_caixabank/report/account_promissory_note_writing_report.xml
  account_promissory_note_caixabank/report/check_print.py
  account_promissory_note_caixabank/static/description/icon.png
  account_promissory_note_caixabank/static/description/index.html
  account_promissory_note_caixabank/views/report_promissory_note.xml
Labels: bot is merging ⏳

#4217 [18.0][MIG] l10n_es_account_asset: Migration to 18.0
  l10n_es_account_asset/README.rst
  l10n_es_account_asset/__init__.py
  l10n_es_account_asset/__manifest__.py
  l10n_es_account_asset/i18n/ca.po
  l10n_es_account_asset/i18n/cs.po
  l10n_es_account_asset/i18n/de.po
  l10n_es_account_asset/i18n/es.po
  l10n_es_account_asset/i18n/es_CO.po
  l10n_es_account_asset/i18n/fr.po
  l10n_es_account_asset/i18n/fr_BE.po
  l10n_es_account_asset/i18n/gl.po
  l10n_es_account_asset/i18n/hr.po
  l10n_es_account_asset/i18n/l10n_es_account_asset.pot
  l10n_es_account_asset/i18n/pl.po
  l10n_es_account_asset/i18n/pt.po
  l10n_es_account_asset/i18n/pt_BR.po
  l10n_es_account_asset/i18n/ru.po
  l10n_es_account_asset/i18n/sl.po
  l10n_es_account_asset/i18n/sv.po
  l10n_es_account_asset/i18n/vi.po
  l10n_es_account_asset/models/__init__.py
  l10n_es_account_asset/models/account_asset.py
  l10n_es_account_asset/models/account_asset_profile.py
  l10n_es_account_asset/pyproject.toml
  l10n_es_account_asset/readme/CONTRIBUTORS.md
  l10n_es_account_asset/readme/DESCRIPTION.md
  l10n_es_account_asset/static/description/icon.png
  l10n_es_account_asset/static/description/index.html
  l10n_es_account_asset/tests/__init__.py
  l10n_es_account_asset/tests/test_l10n_es_account_asset.py
  l10n_es_account_asset/views/account_asset_profile_views.xml
  l10n_es_account_asset/views/account_asset_views.xml
Labels: approved, bot is merging ⏳

#4152 [18.0][MIG] l10n_es_aeat_mod111: Migration to 18.0
  l10n_es_aeat_mod111/README.rst
  l10n_es_aeat_mod111/__init__.py
  l10n_es_aeat_mod111/__manifest__.py
  l10n_es_aeat_mod111/data/aeat_export_mod111_data.xml
  l10n_es_aeat_mod111/data/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod111/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod111/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod111/docs/dr111e16v17.xls
  l10n_es_aeat_mod111/i18n/bg.po
  l10n_es_aeat_mod111/i18n/ca.po
  l10n_es_aeat_mod111/i18n/cs.po
  l10n_es_aeat_mod111/i18n/de.po
  l10n_es_aeat_mod111/i18n/es.po
  l10n_es_aeat_mod111/i18n/es_CO.po
  l10n_es_aeat_mod111/i18n/es_CR.po
  l10n_es_aeat_mod111/i18n/eu.po
  l10n_es_aeat_mod111/i18n/fr.po
  l10n_es_aeat_mod111/i18n/gl.po
  l10n_es_aeat_mod111/i18n/hr.po
  l10n_es_aeat_mod111/i18n/l10n_es_aeat_mod111.pot
  l10n_es_aeat_mod111/i18n/nl.po
  l10n_es_aeat_mod111/i18n/pl.po
  l10n_es_aeat_mod111/i18n/pt.po
  l10n_es_aeat_mod111/i18n/pt_BR.po
  l10n_es_aeat_mod111/i18n/ru.po
  l10n_es_aeat_mod111/i18n/sl.po
  l10n_es_aeat_mod111/i18n/sv.po
  l10n_es_aeat_mod111/i18n/tr.po
  l10n_es_aeat_mod111/i18n/vi.po
  l10n_es_aeat_mod111/models/__init__.py
  l10n_es_aeat_mod111/models/mod111.py
  l10n_es_aeat_mod111/pyproject.toml
  l10n_es_aeat_mod111/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod111/readme/DESCRIPTION.md
  l10n_es_aeat_mod111/readme/ROADMAP.md
  l10n_es_aeat_mod111/readme/USAGE.md
  l10n_es_aeat_mod111/security/ir.model.access.csv
  l10n_es_aeat_mod111/security/l10n_es_aeat_mod111_security.xml
  l10n_es_aeat_mod111/static/description/icon.png
  l10n_es_aeat_mod111/static/description/icon_source.svg
  l10n_es_aeat_mod111/static/description/index.html
  l10n_es_aeat_mod111/tests/__init__.py
  l10n_es_aeat_mod111/tests/test_l10n_es_aeat_mod111.py
  l10n_es_aeat_mod111/views/mod111_view.xml
Labels: bot is merging ⏳

#3969 [18.0][MIG] l10n_es_mis_report
  l10n_es_mis_report/README.rst
  l10n_es_mis_report/__init__.py
  l10n_es_mis_report/__manifest__.py
  l10n_es_mis_report/data/mis_report_balance_abreviated.xml
  l10n_es_mis_report/data/mis_report_balance_normal.xml
  l10n_es_mis_report/data/mis_report_balance_sme.xml
  l10n_es_mis_report/data/mis_report_balance_sme_sfl.xml
  l10n_es_mis_report/data/mis_report_pyg_abreviated.xml
  l10n_es_mis_report/data/mis_report_pyg_normal.xml
  l10n_es_mis_report/data/mis_report_pyg_sme.xml
  l10n_es_mis_report/data/mis_report_pyg_sme_sfl.xml
  l10n_es_mis_report/data/mis_report_revenues_expenses_normal.xml
  l10n_es_mis_report/data/mis_report_styles.xml
  l10n_es_mis_report/i18n/ca.po
  l10n_es_mis_report/i18n/es.po
  l10n_es_mis_report/i18n/l10n_es_mis_report.pot
  l10n_es_mis_report/pyproject.toml
  l10n_es_mis_report/readme/CONTRIBUTORS.md
  l10n_es_mis_report/readme/DESCRIPTION.md
  l10n_es_mis_report/readme/INSTALL.md
  l10n_es_mis_report/readme/USAGE.md
  l10n_es_mis_report/static/description/icon.png
  l10n_es_mis_report/static/description/index.html
Labels: bot is merging ⏳, stale

#4233 [18.0][IMP] l10n_es_aeat_mod111: Change submenu
  l10n_es_aeat_mod111/views/mod111_view.xml
Labels: bot is merging ⏳

#4236 [18.0][MIG] l10n_es_cnae: Migration to 18.0
  l10n_es_cnae/README.rst
  l10n_es_cnae/__init__.py
  l10n_es_cnae/__manifest__.py
  l10n_es_cnae/data/res.partner.industry.csv
  l10n_es_cnae/i18n/es.po
  l10n_es_cnae/i18n/l10n_es_cnae.pot
  l10n_es_cnae/pyproject.toml
  l10n_es_cnae/readme/CONTRIBUTORS.md
  l10n_es_cnae/readme/DESCRIPTION.md
  l10n_es_cnae/readme/INSTALL.md
  l10n_es_cnae/readme/USAGE.md
  l10n_es_cnae/static/description/icon.png
  l10n_es_cnae/static/description/index.html
  l10n_es_cnae/tests/__init__.py
  l10n_es_cnae/tests/test_l10n_es_cnae.py
  l10n_es_cnae/wizard/__init__.py
  l10n_es_cnae/wizard/res_partner_industry_eu_nace_wizard.py
Labels: bot is merging ⏳

#3955 [15.0] [IMP] l10n_es_ticketbai_pos
  l10n_es_ticketbai_pos/README.rst
  l10n_es_ticketbai_pos/static/src/js/widgets.js
Labels: approved, ready to merge, bot is merging ⏳

#3693 [15.0][ADD] l10n_es_vat_book_igic
  l10n_es_vat_book_igic/README.rst
  l10n_es_vat_book_igic/__init__.py
  l10n_es_vat_book_igic/__manifest__.py
  l10n_es_vat_book_igic/data/atc_vat_book_igic_map_data.xml
  l10n_es_vat_book_igic/i18n/l10n_es_vat_book_igic.pot
  l10n_es_vat_book_igic/readme/CONFIGURE.rst
  l10n_es_vat_book_igic/readme/CONTRIBUTORS.rst
  l10n_es_vat_book_igic/readme/DESCRIPTION.rst
  l10n_es_vat_book_igic/readme/INSTALL.rst
  l10n_es_vat_book_igic/readme/USAGE.rst
  l10n_es_vat_book_igic/static/description/icon.png
  l10n_es_vat_book_igic/static/description/index.html
  setup/l10n_es_vat_book_igic/odoo/addons/l10n_es_vat_book_igic
  setup/l10n_es_vat_book_igic/setup.py
Labels: approved, bot is merging ⏳, stale

#4204 [17.0][IMP] l10n_es_aeat_mod216: version 2024
  l10n_es_aeat_mod216/README.rst
  l10n_es_aeat_mod216/__manifest__.py
  l10n_es_aeat_mod216/data/2016/aeat_export_mod216_data.xml
  l10n_es_aeat_mod216/data/2016/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod216/data/2016/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod216/data/2024/aeat.model.export.config.csv
  l10n_es_aeat_mod216/data/2024/aeat.model.export.config.line.csv
  l10n_es_aeat_mod216/data/2024/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod216/data/2024/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod216/data/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod216/i18n/es.po
  l10n_es_aeat_mod216/i18n/l10n_es_aeat_mod216.pot
  l10n_es_aeat_mod216/migrations/17.0.1.1.0/pre-migrate.py
  l10n_es_aeat_mod216/models/mod216.py
  l10n_es_aeat_mod216/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod216/readme/USAGE.md
  l10n_es_aeat_mod216/static/description/index.html
  l10n_es_aeat_mod216/tests/test_l10n_es_aeat_mod216.py
  l10n_es_aeat_mod216/views/mod216_view.xml
Labels: bot is merging ⏳

#4153 [18.0][MIG] l10n_es_aeat_mod123: Migration to 18.0
  l10n_es_aeat_mod123/README.rst
  l10n_es_aeat_mod123/__init__.py
  l10n_es_aeat_mod123/__manifest__.py
  l10n_es_aeat_mod123/data/2016/aeat.model.export.config.csv
  l10n_es_aeat_mod123/data/2016/aeat.model.export.config.line.csv
  l10n_es_aeat_mod123/data/2016/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod123/data/2016/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod123/data/2024/aeat.model.export.config.csv
  l10n_es_aeat_mod123/data/2024/aeat.model.export.config.line.csv
  l10n_es_aeat_mod123/data/2024/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod123/data/2024/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod123/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod123/i18n/bg.po
  l10n_es_aeat_mod123/i18n/ca.po
  l10n_es_aeat_mod123/i18n/cs.po
  l10n_es_aeat_mod123/i18n/de.po
  l10n_es_aeat_mod123/i18n/es.po
  l10n_es_aeat_mod123/i18n/es_CO.po
  l10n_es_aeat_mod123/i18n/es_CR.po
  l10n_es_aeat_mod123/i18n/eu.po
  l10n_es_aeat_mod123/i18n/fr.po
  l10n_es_aeat_mod123/i18n/gl.po
  l10n_es_aeat_mod123/i18n/hr.po
  l10n_es_aeat_mod123/i18n/l10n_es_aeat_mod123.pot
  l10n_es_aeat_mod123/i18n/nl.po
  l10n_es_aeat_mod123/i18n/pl.po
  l10n_es_aeat_mod123/i18n/pt.po
  l10n_es_aeat_mod123/i18n/pt_BR.po
  l10n_es_aeat_mod123/i18n/sl.po
  l10n_es_aeat_mod123/i18n/sv.po
  l10n_es_aeat_mod123/i18n/tr.po
  l10n_es_aeat_mod123/i18n/vi.po
  l10n_es_aeat_mod123/models/__init__.py
  l10n_es_aeat_mod123/models/mod123.py
  l10n_es_aeat_mod123/pyproject.toml
  l10n_es_aeat_mod123/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod123/readme/DESCRIPTION.md
  l10n_es_aeat_mod123/readme/USAGE.md
  l10n_es_aeat_mod123/security/ir.model.access.csv
  l10n_es_aeat_mod123/security/mod_123_security.xml
  l10n_es_aeat_mod123/static/description/icon.png
  l10n_es_aeat_mod123/static/description/icon_source.svg
  l10n_es_aeat_mod123/static/description/index.html
  l10n_es_aeat_mod123/tests/__init__.py
  l10n_es_aeat_mod123/tests/test_l10n_es_aeat_mod123.py
  l10n_es_aeat_mod123/views/mod123_view.xml
Labels: bot is merging ⏳

#4241 [18.0][MIG] l10n_es_aeat_mod115: Migration to 18.0
  l10n_es_aeat_mod115/README.rst
  l10n_es_aeat_mod115/__init__.py
  l10n_es_aeat_mod115/__manifest__.py
  l10n_es_aeat_mod115/data/aeat.model.export.config.csv
  l10n_es_aeat_mod115/data/aeat.model.export.config.line.csv
  l10n_es_aeat_mod115/data/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod115/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod115/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod115/docs/DR115e15v11.xls
  l10n_es_aeat_mod115/i18n/bg.po
  l10n_es_aeat_mod115/i18n/ca.po
  l10n_es_aeat_mod115/i18n/cs.po
  l10n_es_aeat_mod115/i18n/es.po
  l10n_es_aeat_mod115/i18n/es_CO.po
  l10n_es_aeat_mod115/i18n/es_CR.po
  l10n_es_aeat_mod115/i18n/eu.po
  l10n_es_aeat_mod115/i18n/fr.po
  l10n_es_aeat_mod115/i18n/gl.po
  l10n_es_aeat_mod115/i18n/hr.po
  l10n_es_aeat_mod115/i18n/l10n_es_aeat_mod115.pot
  l10n_es_aeat_mod115/i18n/nl.po
  l10n_es_aeat_mod115/i18n/pl.po
  l10n_es_aeat_mod115/i18n/pt.po
  l10n_es_aeat_mod115/i18n/pt_BR.po
  l10n_es_aeat_mod115/i18n/ru.po
  l10n_es_aeat_mod115/i18n/sl.po
  l10n_es_aeat_mod115/i18n/sv.po
  l10n_es_aeat_mod115/i18n/tr.po
  l10n_es_aeat_mod115/i18n/vi.po
  l10n_es_aeat_mod115/models/__init__.py
  l10n_es_aeat_mod115/models/mod115.py
  l10n_es_aeat_mod115/pyproject.toml
  l10n_es_aeat_mod115/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod115/readme/DESCRIPTION.md
  l10n_es_aeat_mod115/readme/USAGE.md
  l10n_es_aeat_mod115/security/ir.model.access.csv
  l10n_es_aeat_mod115/security/l10n_es_aeat_mod115_security.xml
  l10n_es_aeat_mod115/static/description/icon.png
  l10n_es_aeat_mod115/static/description/icon_source.svg
  l10n_es_aeat_mod115/static/description/index.html
  l10n_es_aeat_mod115/tests/__init__.py
  l10n_es_aeat_mod115/tests/test_l10n_es_aeat_mod115.py
  l10n_es_aeat_mod115/views/mod115_view.xml
Labels: bot is merging ⏳

#4098 [18.0][MIG] l10n_es_vat_book
  l10n_es_vat_book/README.rst
  l10n_es_vat_book/__init__.py
  l10n_es_vat_book/__manifest__.py
  l10n_es_vat_book/data/aeat.vat.book.map.line.csv
  l10n_es_vat_book/data/l10n.es.aeat.map.tax.line.account.csv
  l10n_es_vat_book/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_vat_book/i18n/bg.po
  l10n_es_vat_book/i18n/ca.po
  l10n_es_vat_book/i18n/cs.po
  l10n_es_vat_book/i18n/de.po
  l10n_es_vat_book/i18n/es.po
  l10n_es_vat_book/i18n/es_CO.po
  l10n_es_vat_book/i18n/es_CR.po
  l10n_es_vat_book/i18n/eu.po
  l10n_es_vat_book/i18n/fr.po
  l10n_es_vat_book/i18n/gl.po
  l10n_es_vat_book/i18n/hr.po
  l10n_es_vat_book/i18n/l10n_es_vat_book.pot
  l10n_es_vat_book/i18n/nl.po
  l10n_es_vat_book/i18n/pl.po
  l10n_es_vat_book/i18n/pt.po
  l10n_es_vat_book/i18n/pt_BR.po
  l10n_es_vat_book/i18n/ru.po
  l10n_es_vat_book/i18n/sl.po
  l10n_es_vat_book/i18n/sv.po
  l10n_es_vat_book/i18n/tr.po
  l10n_es_vat_book/i18n/vi.po
  l10n_es_vat_book/models/__init__.py
  l10n_es_vat_book/models/aeat_vat_book_map_line.py
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/models/l10n_es_vat_book_line.py
  l10n_es_vat_book/models/l10n_es_vat_book_line_tax.py
  l10n_es_vat_book/models/l10n_es_vat_book_summary.py
  l10n_es_vat_book/models/l10n_es_vat_book_tax_summary.py
  l10n_es_vat_book/pyproject.toml
  l10n_es_vat_book/readme/CONFIGURE.md
  l10n_es_vat_book/readme/CONTRIBUTORS.md
  l10n_es_vat_book/readme/DESCRIPTION.md
  l10n_es_vat_book/readme/INSTALL.md
  l10n_es_vat_book/readme/ROADMAP.md
  l10n_es_vat_book/readme/USAGE.md
  l10n_es_vat_book/report/__init__.py
  l10n_es_vat_book/report/common_templates.xml
  l10n_es_vat_book/report/report_views.xml
  l10n_es_vat_book/report/vat_book_invoices_issued.xml
  l10n_es_vat_book/report/vat_book_invoices_received.xml
  l10n_es_vat_book/report/vat_book_xlsx.py
  l10n_es_vat_book/report/vat_book_xlsx.xml
  l10n_es_vat_book/security/ir.model.access.csv
  l10n_es_vat_book/security/ir_rule.xml
  l10n_es_vat_book/static/description/icon.png
  l10n_es_vat_book/static/description/index.html
  l10n_es_vat_book/tests/__init__.py
  l10n_es_vat_book/tests/test_l10n_es_aeat_vat_book.py
  l10n_es_vat_book/views/aeat_vat_book_map_view.xml
  l10n_es_vat_book/views/l10n_es_vat_book.xml
  l10n_es_vat_book/views/l10n_es_vat_book_line.xml
  l10n_es_vat_book/views/l10n_es_vat_book_summary.xml
  l10n_es_vat_book/views/l10n_es_vat_book_tax_summary.xml
Labels: approved, bot is merging ⏳

#4190 [18.0][MIG] l10n_es_payment_order_confirming_sabadell: Migration to 18.0
  l10n_es_payment_order_confirming_sabadell/README.rst
  l10n_es_payment_order_confirming_sabadell/__init__.py
  l10n_es_payment_order_confirming_sabadell/__manifest__.py
  l10n_es_payment_order_confirming_sabadell/data/account_payment_method.xml
  l10n_es_payment_order_confirming_sabadell/i18n/ca.po
  l10n_es_payment_order_confirming_sabadell/i18n/es.po
  l10n_es_payment_order_confirming_sabadell/i18n/l10n_es_payment_order_confirming_sabadell.pot
  l10n_es_payment_order_confirming_sabadell/models/__init__.py
  l10n_es_payment_order_confirming_sabadell/models/account_payment_method.py
  l10n_es_payment_order_confirming_sabadell/models/account_payment_mode.py
  l10n_es_payment_order_confirming_sabadell/models/account_payment_order.py
  l10n_es_payment_order_confirming_sabadell/models/confirming_sabadell.py
  l10n_es_payment_order_confirming_sabadell/pyproject.toml
  l10n_es_payment_order_confirming_sabadell/readme/CONFIGURE.md
  l10n_es_payment_order_confirming_sabadell/readme/CONTRIBUTORS.md
  l10n_es_payment_order_confirming_sabadell/readme/DESCRIPTION.md
  l10n_es_payment_order_confirming_sabadell/readme/USAGE.md
  l10n_es_payment_order_confirming_sabadell/static/description/icon.png
  l10n_es_payment_order_confirming_sabadell/static/description/index.html
  l10n_es_payment_order_confirming_sabadell/tests/__init__.py
  l10n_es_payment_order_confirming_sabadell/tests/test_payment_order_confirming_sabadell.py
  l10n_es_payment_order_confirming_sabadell/views/account_payment_mode_view.xml
Labels: bot is merging ⏳

#4246 [18.0][MIG] l10n_ca_es_cnae: Migration to 18.0
  l10n_ca_es_cnae/README.rst
  l10n_ca_es_cnae/__init__.py
  l10n_ca_es_cnae/__manifest__.py
  l10n_ca_es_cnae/data/res.partner.industry.cat.csv
  l10n_ca_es_cnae/i18n/ca.po
  l10n_ca_es_cnae/i18n/l10n_ca_es_cnae.pot
  l10n_ca_es_cnae/pyproject.toml
  l10n_ca_es_cnae/readme/CONTRIBUTORS.md
  l10n_ca_es_cnae/readme/DESCRIPTION.md
  l10n_ca_es_cnae/readme/INSTALL.md
  l10n_ca_es_cnae/readme/USAGE.md
  l10n_ca_es_cnae/static/description/icon.png
  l10n_ca_es_cnae/static/description/index.html
  l10n_ca_es_cnae/tests/__init__.py
  l10n_ca_es_cnae/tests/test_l10n_ca_es_cnae.py
  l10n_ca_es_cnae/wizard/__init__.py
  l10n_ca_es_cnae/wizard/res_partner_industry_eu_nace_wizard.py
Labels: approved, bot is merging ⏳

#3825 [16.0][MIG] l10n_es_aeat_mod592: Migration to 16.0
  l10n_es_aeat_mod592/README.rst
  l10n_es_aeat_mod592/__init__.py
  l10n_es_aeat_mod592/__manifest__.py
  l10n_es_aeat_mod592/data/ir_sequence_data.xml
  l10n_es_aeat_mod592/docs/Contabilidad_libro.pdf
  l10n_es_aeat_mod592/docs/Rég. Fiscal Adquir. y Repres. (ADSIPLRA).csv
  l10n_es_aeat_mod592/docs/Régimen Fiscal Fabricantes (ADSIPLRF).csv
  l10n_es_aeat_mod592/docs/plastico_campos_impfichero.xlsx
  l10n_es_aeat_mod592/docs/plastico_doc_impfichero.pdf
  l10n_es_aeat_mod592/i18n/es.po
  l10n_es_aeat_mod592/i18n/l10n_es_aeat_mod592.pot
  l10n_es_aeat_mod592/models/__init__.py
  l10n_es_aeat_mod592/models/misc.py
  l10n_es_aeat_mod592/models/mod592.py
  l10n_es_aeat_mod592/models/mod592_acquirer.py
  l10n_es_aeat_mod592/models/mod592_line_mixin.py
  l10n_es_aeat_mod592/models/mod592_manufacturer.py
  l10n_es_aeat_mod592/models/product_product.py
  l10n_es_aeat_mod592/models/product_template.py
  l10n_es_aeat_mod592/models/res_company.py
  l10n_es_aeat_mod592/models/res_partner.py
  l10n_es_aeat_mod592/readme/CONFIGURE.rst
  l10n_es_aeat_mod592/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod592/readme/DESCRIPTION.rst
  l10n_es_aeat_mod592/readme/ROADMAP.rst
  l10n_es_aeat_mod592/readme/USAGE.rst
  l10n_es_aeat_mod592/report/__init__.py
  l10n_es_aeat_mod592/report/aeat_mod592.xml
  l10n_es_aeat_mod592/report/common_templates.xml
  l10n_es_aeat_mod592/report/l10n_es_aeat_mod592_csv.py
  l10n_es_aeat_mod592/report/l10n_es_aeat_mod592_xlsx.py
  l10n_es_aeat_mod592/report/report_views.xml
  l10n_es_aeat_mod592/security/aeat_security.xml
  l10n_es_aeat_mod592/security/ir.model.access.csv
  l10n_es_aeat_mod592/static/description/icon.png
  l10n_es_aeat_mod592/static/description/icon_source.svg
  l10n_es_aeat_mod592/static/description/index.html
  l10n_es_aeat_mod592/tests/__init__.py
  l10n_es_aeat_mod592/tests/test_l10n_es_aeat_mod592.py
  l10n_es_aeat_mod592/views/mod592_acquirer_line_views.xml
  l10n_es_aeat_mod592/views/mod592_manufacturer_line_views.xml
  l10n_es_aeat_mod592/views/mod592_views.xml
  l10n_es_aeat_mod592/views/product_template_views.xml
  l10n_es_aeat_mod592/views/res_company_views.xml
  l10n_es_aeat_mod592/views/res_partner_views.xml
  setup/l10n_es_aeat_mod592/odoo/addons/l10n_es_aeat_mod592
  setup/l10n_es_aeat_mod592/setup.py
Labels: bot is merging ⏳

#4253 [16.0][FIX] l10n_es_aeat_sii_oca: No taxable reason for services
  l10n_es_aeat_sii_oca/models/sii_mixin.py
Labels: bot is merging ⏳

#4254 [17.0][FIX] l10n_es_aeat_sii_oca: No taxable reason for services
  l10n_es_aeat_sii_oca/models/sii_mixin.py
Labels: bot is merging ⏳

#4243 [14.0][FIX] l10n_es_payment_order_confirming_aef - trasladar la moneda correcta al fichero generado
  l10n_es_payment_order_confirming_aef/models/confirming_aef.py
Labels: bot is merging ⏳

#4257 [18.0][MIG] l10n_es_aeat_mod349: Migration to 18.0
  l10n_es_aeat_mod349/README.rst
  l10n_es_aeat_mod349/__init__.py
  l10n_es_aeat_mod349/__manifest__.py
  l10n_es_aeat_mod349/data/aeat.349.map.line.csv
  l10n_es_aeat_mod349/data/aeat_export_mod349_data.xml
  l10n_es_aeat_mod349/data/aeat_export_mod349_partner_data.xml
  l10n_es_aeat_mod349/data/aeat_export_mod349_partner_refund_data.xml
  l10n_es_aeat_mod349/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod349/docs/BOE-A-2010-5098.pdf
  l10n_es_aeat_mod349/docs/NREG-349-2016.docx
  l10n_es_aeat_mod349/i18n/ca.po
  l10n_es_aeat_mod349/i18n/es.po
  l10n_es_aeat_mod349/i18n/l10n_es_aeat_mod349.pot
  l10n_es_aeat_mod349/models/__init__.py
  l10n_es_aeat_mod349/models/account_move.py
  l10n_es_aeat_mod349/models/account_tax.py
  l10n_es_aeat_mod349/models/aeat_349_map_line.py
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/pyproject.toml
  l10n_es_aeat_mod349/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod349/readme/DESCRIPTION.md
  l10n_es_aeat_mod349/readme/ROADMAP.md
  l10n_es_aeat_mod349/readme/USAGE.md
  l10n_es_aeat_mod349/report/aeat_mod349.xml
  l10n_es_aeat_mod349/report/common_templates.xml
  l10n_es_aeat_mod349/report/report_views.xml
  l10n_es_aeat_mod349/security/ir.model.access.csv
  l10n_es_aeat_mod349/security/mod_349_security.xml
  l10n_es_aeat_mod349/static/description/icon.png
  l10n_es_aeat_mod349/static/description/icon_source.svg
  l10n_es_aeat_mod349/static/description/index.html
  l10n_es_aeat_mod349/tests/__init__.py
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
  l10n_es_aeat_mod349/views/account_move_view.xml
  l10n_es_aeat_mod349/views/account_tax_view.xml
  l10n_es_aeat_mod349/views/aeat_349_map_view.xml
  l10n_es_aeat_mod349/views/mod349_view.xml
Labels: bot is merging ⏳
