Repository OCA/l10n-spain, pull requests merged in 2025-03, with the labels that each got.

#4058 [17.0][FIX] l10n_es_partner: Inject _rec_names_search properly
  l10n_es_partner/models/res_partner.py
Labels: bot is merging ⏳

#4057 [16.0][FIX] l10n_es_partner: Inject _rec_names_search properly
  l10n_es_partner/models/res_partner.py
Labels: approved, bot is merging ⏳

#4061 [17.0][FIX]l10n_es_facturae: solucion error facturae sin campos DIR3
  l10n_es_facturae/views/report_facturae.xml
Labels: approved, bot is merging ⏳

#4059 [16.0][FIX] l10n_es_aeat_sii_taxfree: Test inheritance
  l10n_es_aeat_sii_taxfree/tests/test_l10n_es_aeat_sii_taxfree.py
Labels: bot is merging ⏳

#4009 [17.0][MIG] l10n_es_aeat_mod303_oss: Migration to 17.0
  l10n_es_aeat_mod303_oss/README.rst
  l10n_es_aeat_mod303_oss/__init__.py
  l10n_es_aeat_mod303_oss/__manifest__.py
  l10n_es_aeat_mod303_oss/data/2024-10/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303_oss/i18n/ca.po
  l10n_es_aeat_mod303_oss/i18n/ca_ES.po
  l10n_es_aeat_mod303_oss/i18n/es.po
  l10n_es_aeat_mod303_oss/i18n/l10n_es_aeat_mod303_oss.pot
  l10n_es_aeat_mod303_oss/models/__init__.py
  l10n_es_aeat_mod303_oss/models/l10n_es_aeat_map_tax_line.py
  l10n_es_aeat_mod303_oss/models/mod303.py
  l10n_es_aeat_mod303_oss/pyproject.toml
  l10n_es_aeat_mod303_oss/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod303_oss/readme/DESCRIPTION.md
  l10n_es_aeat_mod303_oss/static/description/icon.png
  l10n_es_aeat_mod303_oss/static/description/icon_source.svg
  l10n_es_aeat_mod303_oss/static/description/index.html
  l10n_es_aeat_mod303_oss/tests/__init__.py
  l10n_es_aeat_mod303_oss/tests/test_l10n_es_aeat_mod303_oss.py
Labels: approved, ready to merge, bot is merging ⏳

#4062 [17.0][FIX] l10n_es_facturae: Fix base64 decoding for attachments
  l10n_es_facturae/models/account_move.py
Labels: approved, bot is merging ⏳

#3805 [17.0][IMP] payment_redsys: remove website_sale dependency
  payment_redsys/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#4069 [16.0][FIX] l10n_es_aeat_sii_oca: Inhibit agencies test
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
Labels: bot is merging ⏳

#4037 [16.0][FIX] l10n_es_aeat_mod190: computo primeros hijos
  l10n_es_aeat_mod190/i18n/es.po
  l10n_es_aeat_mod190/i18n/l10n_es_aeat_mod190.pot
  l10n_es_aeat_mod190/models/res_partner.py
  l10n_es_aeat_mod190/views/partner_view.xml
Labels: approved, bot is merging ⏳

#4072 [15.0][FIX] l10n_es_facturae: Constraint error when a child contact is created directly
  l10n_es_facturae/models/res_partner.py
  l10n_es_facturae/tests/common.py
Labels: approved, bot is merging ⏳

#4074 [17.0][FIX] l10n_es_facturae: Constraint error when a child contact is created directly
  l10n_es_facturae/models/res_partner.py
  l10n_es_facturae/tests/common.py
Labels: bot is merging ⏳

#4075 [16.0][FIX] l10n_es_facturae: Constraint error when a child contact is created directly
  l10n_es_facturae/models/res_partner.py
  l10n_es_facturae/tests/common.py
Labels: bot is merging ⏳

#4073 [17.0][MIG] delivery_seur_atlas: Migration to 17.0
  delivery_seur_atlas/README.rst
  delivery_seur_atlas/__init__.py
  delivery_seur_atlas/__manifest__.py
  delivery_seur_atlas/i18n/delivery_seur_atlas.pot
  delivery_seur_atlas/i18n/es.po
  delivery_seur_atlas/models/__init__.py
  delivery_seur_atlas/models/delivery_carrier.py
  delivery_seur_atlas/models/seur_master_data.py
  delivery_seur_atlas/models/seur_request_atlas.py
  delivery_seur_atlas/pyproject.toml
  delivery_seur_atlas/readme/CONFIGURE.md
  delivery_seur_atlas/readme/CONTEXT.md
  delivery_seur_atlas/readme/CONTRIBUTORS.md
  delivery_seur_atlas/readme/DESCRIPTION.md
  delivery_seur_atlas/readme/INSTALL.md
  delivery_seur_atlas/readme/ROADMAP.md
  delivery_seur_atlas/readme/USAGE.md
  delivery_seur_atlas/static/description/icon.png
  delivery_seur_atlas/static/description/index.html
  delivery_seur_atlas/tests/__init__.py
  delivery_seur_atlas/tests/test_delivery_seur_atlas.py
  delivery_seur_atlas/views/delivery_carrier_views.xml
Labels: bot is merging ⏳

#4078 [17.0][FIX] l10n_es_vat_book_oss: Dependency name
  l10n_es_vat_book_oss/readme/INSTALL.md
Labels: needs review, bot is merging ⏳

#4038 [17.0][MIG] l10n_es_aeat_sii_oss: Migration to 17.0
  l10n_es_aeat_sii_oss/README.rst
  l10n_es_aeat_sii_oss/__init__.py
  l10n_es_aeat_sii_oss/__manifest__.py
  l10n_es_aeat_sii_oss/data/aeat_sii_mapping_registration_keys_data.xml
  l10n_es_aeat_sii_oss/i18n/ca.po
  l10n_es_aeat_sii_oss/i18n/es.po
  l10n_es_aeat_sii_oss/i18n/l10n_es_aeat_sii_oss.pot
  l10n_es_aeat_sii_oss/models/__init__.py
  l10n_es_aeat_sii_oss/models/account_move.py
  l10n_es_aeat_sii_oss/pyproject.toml
  l10n_es_aeat_sii_oss/readme/CONFIGURE.md
  l10n_es_aeat_sii_oss/readme/CONTRIBUTORS.md
  l10n_es_aeat_sii_oss/readme/DESCRIPTION.md
  l10n_es_aeat_sii_oss/readme/INSTALL.md
  l10n_es_aeat_sii_oss/static/description/icon.png
  l10n_es_aeat_sii_oss/static/description/icon_source.svg
  l10n_es_aeat_sii_oss/static/description/index.html
  l10n_es_aeat_sii_oss/tests/__init__.py
  l10n_es_aeat_sii_oss/tests/test_l10n_es_aeat_sii.py
Labels: approved, bot is merging ⏳

#4081 [17.0][OU-ADD] l10n_es_facturae: Add migration Script
  l10n_es_facturae/migrations/17.0.1.1.3/pre-migration.py
Labels: bot is merging ⏳

#4079 [16.0][IMP] l10n_es_aeat_mod190: Cálculo gastos deducibles
  l10n_es_aeat_mod190/data/tax_code_map_mod190_data.xml
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
  l10n_es_aeat_mod190/tests/test_mod190.py
  l10n_es_aeat_mod190/views/mod190_line_view.xml
Labels: approved, bot is merging ⏳

#4083 [17.0][IMP] l10n_es_igic: Add Account 112 & 113
  l10n_es_igic/data/template/account.account-es_common_canary.csv
Labels: approved, bot is merging ⏳

#4080 [16.0][OU-ADD] l10n_es_facturae: Add migration Script
  l10n_es_facturae/migrations/16.0.1.10.0/pre-migration.py
Labels: approved, bot is merging ⏳

#4076 [17.0][IMP] l10n_es_igic: tax names changed
  l10n_es_igic/data/template/account.tax-es_common_canary.csv
Labels: approved, ready to merge, bot is merging ⏳

#4086 [17.0][IMP] l10n_es_facturae: Remove obsolete file
  l10n_es_facturae/data/account_tax_template.xml
Labels: bot is merging ⏳

#4084 [17.0][FIX] l10n_es_*: Fix intra/extra-community taxes refs and new exempt taxes
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat/migrations/17.0.2.3.1/pre-migration.py
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/data/2023/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
  l10n_es_aeat_mod347/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod347/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod390/data/2024/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod390/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod390/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
  l10n_es_aeat_sii_oca/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_sii_oca/tests/json/sii_out_invoice_s_iva0_sp_i_s_iva0_g_i_dict.json
  l10n_es_aeat_sii_oca/tests/json/sii_out_invoice_s_iva_e_s_iva0_g_e_dict.json
  l10n_es_aeat_sii_oca/tests/json/sii_out_refund_s_iva0_sp_i_s_iva0_g_i_dict.json
  l10n_es_aeat_sii_oca/tests/json/sii_out_refund_s_iva_e_s_iva0_g_e_dict.json
  l10n_es_aeat_sii_oca/tests/test_l10n_es_aeat_sii.py
  l10n_es_facturae/data/template/account.tax-es_common.csv
  l10n_es_vat_book/data/aeat.vat.book.map.line.csv
  l10n_es_vat_book/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva0_sp_i_s_iva0_g_i_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_invoice_s_iva_e_s_iva0_g_e_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_refund_s_iva0_sp_i_s_iva0_g_i_dict.json
  l10n_es_vat_prorate/tests/json/sii_out_refund_s_iva_e_s_iva0_g_e_dict.json
  l10n_es_vat_prorate/tests/test_prorate_sii.py
Labels: approved, bot is merging ⏳

#4089 [16.0][OU-FIX] l10n_es_facturae: typo error
  l10n_es_facturae/migrations/16.0.1.10.0/pre-migration.py
Labels: approved

#4088 [16.0][IMP] l10n_es_facturae: remove unidad tramitadora and oficina contable checks.
  l10n_es_facturae/models/account_move.py
  l10n_es_facturae/tests/common.py
  l10n_es_facturae_face/models/account_move.py
  l10n_es_facturae_face/tests/test_facturae_face.py
Labels: approved, bot is merging ⏳

#4091 [FIX] l10n_es_aeat: fix name external id, deleted 'account' in final name
  l10n_es_aeat/migrations/17.0.2.3.1/pre-migration.py
Labels: approved

#4095 [16.0][FIX] l10n_es_facturae: Align facturae_code field position with v17
  l10n_es_facturae/views/account_tax_view.xml
Labels: approved, bot is merging ⏳

#4099 [17.0][FIX] l10n_es_igic_reav: xmlid rename
  l10n_es_igic_reav/data/template/account.fiscal.position-es_full_canary.csv
  l10n_es_igic_reav/data/template/account.fiscal.position-es_pymes_canary.csv
Labels: approved, bot is merging ⏳
