Repository OCA/l10n-spain, pull requests merged in 2025-08, with the labels that each got.

#4331 [17.0][IMP] l10n_es_vat_book: Test inactive taxes
  l10n_es_vat_book/tests/test_l10n_es_aeat_vat_book.py
Labels: bot is merging ⏳

#4333 [18.0][IMP] l10n_es_vat_book: Test inactive taxes
  l10n_es_vat_book/tests/test_l10n_es_aeat_vat_book.py
Labels: bot is merging ⏳

#4336 [17.0][FIX] l10n_es_intrastat_report: Define the appropriate fiscal positions with Intrastat
  l10n_es_intrastat_report/hooks.py
  l10n_es_intrastat_report/tests/test_l10n_es_intrastat_report.py
Labels: bot is merging ⏳

#4250 [18.0][MIG] l10n_es_aeat_mod296:
  l10n_es_aeat_mod296/README.rst
  l10n_es_aeat_mod296/__init__.py
  l10n_es_aeat_mod296/__manifest__.py
  l10n_es_aeat_mod296/data/aeat.model.export.config.csv
  l10n_es_aeat_mod296/data/aeat.model.export.config.line.csv
  l10n_es_aeat_mod296/data/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod296/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod296/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod296/docs/DR296_2017.pdf
  l10n_es_aeat_mod296/docs/instrucciones_296.pdf
  l10n_es_aeat_mod296/docs/register_design_296_2008.pdf
  l10n_es_aeat_mod296/i18n/es.po
  l10n_es_aeat_mod296/i18n/l10n_es_aeat_mod296.pot
  l10n_es_aeat_mod296/models/__init__.py
  l10n_es_aeat_mod296/models/mod296.py
  l10n_es_aeat_mod296/pyproject.toml
  l10n_es_aeat_mod296/readme/CONFIGURE.md
  l10n_es_aeat_mod296/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod296/readme/DESCRIPTION.md
  l10n_es_aeat_mod296/readme/USAGE.md
  l10n_es_aeat_mod296/security/ir.model.access.csv
  l10n_es_aeat_mod296/security/ir_rule.xml
  l10n_es_aeat_mod296/static/description/icon.png
  l10n_es_aeat_mod296/static/description/icon_source.svg
  l10n_es_aeat_mod296/static/description/index.html
  l10n_es_aeat_mod296/tests/__init__.py
  l10n_es_aeat_mod296/tests/test_l10n_es_aeat_mod296.py
  l10n_es_aeat_mod296/views/mod296_views.xml
Labels: bot is merging ⏳

#4345 [16.0][IMP]l10n_es_pos_sii: Added group to sii_registration_key and sii_registration_key_code to allow the pos users to interact whit the pos orders.
  l10n_es_pos_sii/views/pos_order.xml
Labels: bot is merging ⏳

#4334 [18.0][IMP] l10n_es_aeat_mod347: Field Not in mod347 in partner converted to company dependent
  l10n_es_aeat_mod347/README.rst
  l10n_es_aeat_mod347/__manifest__.py
  l10n_es_aeat_mod347/migrations/18.0.1.1.0/pre-migration.py
  l10n_es_aeat_mod347/models/res_partner.py
  l10n_es_aeat_mod347/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#4349 [17.0][FIX] l10n_es_aeat_mod303: Remove missing tax from tests
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
  l10n_es_facturae/data/template/account.tax-es_common.csv
Labels: bot is merging ⏳

#4351 [18.0][MIG] l10n_es_aeat_mod190: Migration to 18
  l10n_es_aeat_mod190/README.rst
  l10n_es_aeat_mod190/__init__.py
  l10n_es_aeat_mod190/__manifest__.py
  l10n_es_aeat_mod190/data/aeat.model.export.config.csv
  l10n_es_aeat_mod190/data/aeat.model.export.config.line.csv
  l10n_es_aeat_mod190/data/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod190/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod190/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod190/data/perception_key_data.xml
  l10n_es_aeat_mod190/data/perception_subkey_data.xml
  l10n_es_aeat_mod190/docs/DR190_2017.pdf
  l10n_es_aeat_mod190/docs/DR190_2024.pdf
  l10n_es_aeat_mod190/i18n/ca.po
  l10n_es_aeat_mod190/i18n/ca_ES.po
  l10n_es_aeat_mod190/i18n/es.po
  l10n_es_aeat_mod190/i18n/l10n_es_aeat_mod190.pot
  l10n_es_aeat_mod190/migrations/18.0.1.0.0/pre-migration.py
  l10n_es_aeat_mod190/models/__init__.py
  l10n_es_aeat_mod190/models/account_fiscal_position.py
  l10n_es_aeat_mod190/models/account_move.py
  l10n_es_aeat_mod190/models/account_move_line.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_perception.py
  l10n_es_aeat_mod190/models/res_partner.py
  l10n_es_aeat_mod190/pyproject.toml
  l10n_es_aeat_mod190/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod190/readme/DESCRIPTION.md
  l10n_es_aeat_mod190/readme/ROADMAP.md
  l10n_es_aeat_mod190/readme/USAGE.md
  l10n_es_aeat_mod190/security/ir.model.access.csv
  l10n_es_aeat_mod190/security/l10n_es_aeat_mod190_security.xml
  l10n_es_aeat_mod190/static/description/icon.png
  l10n_es_aeat_mod190/static/description/icon_source.svg
  l10n_es_aeat_mod190/static/description/index.html
  l10n_es_aeat_mod190/tests/__init__.py
  l10n_es_aeat_mod190/tests/test_mod190.py
  l10n_es_aeat_mod190/views/account_fiscal_position.xml
  l10n_es_aeat_mod190/views/account_invoice_view.xml
  l10n_es_aeat_mod190/views/account_move_view.xml
  l10n_es_aeat_mod190/views/mod190_line_view.xml
  l10n_es_aeat_mod190/views/mod190_view.xml
  l10n_es_aeat_mod190/views/partner_view.xml
Labels: approved, bot is merging ⏳

#4354 [FIX] l10n_es_partner: Fix vista formulario banco
  l10n_es_partner/views/res_bank_view.xml
Labels: bot is merging ⏳

#4353 [15.0][FIX] l10n_es_intrastat_report: wrong country code for csv export
  l10n_es_intrastat_report/models/l10n_es_intrastat_product_declaration.py
Labels: approved, bot is merging ⏳
