Repository OCA/l10n-spain, pull requests merged in 2025-01, with the labels that each got.

#3873 [16.0][FIX] l10n_es_pos: compatibility with kitchen order printers
  l10n_es_pos/static/src/xml/pos.xml
Labels: approved, bot is merging ⏳

#3399 [15.0][BP] l10n_es_aeat_mod390: casillas 85, 95, 97, 98 y 662
  l10n_es_aeat_mod390/README.rst
  l10n_es_aeat_mod390/data/aeat_export_mod390_2019_sub06_data.xml
  l10n_es_aeat_mod390/i18n/es.po
  l10n_es_aeat_mod390/i18n/l10n_es_aeat_mod390.pot
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod390/static/description/index.html
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: bot is merging ⏳

#3878 [15.0][FIX] l10n_es_aeat_sii_oca: cancel one invoice
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#3883 [16.0][FIX] l10n_es_aeat_sii_oca: cancel one invoice
  l10n_es_aeat_sii_oca/models/account_move.py
Labels: bot is merging ⏳

#3885 [IMP] l10n_es_aeat_sii_oca: Impuesto ganadería y pesca (10,5%)
  l10n_es_aeat_sii_oca/data/aeat_sii_map_data.xml
Labels: approved, bot is merging ⏳

#3880 [15.0][FIX] l10n_es_aeat_mod349: refund intermediate periods
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
Labels: bot is merging ⏳

#3889 [15.0][IMP] l10n_es_aeat_mod303: Follow 2 column layout in exonerated 390
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: bot is merging ⏳

#3887 [16.0][IMP] l10n_es_aeat: Reverse order for reports
  l10n_es_aeat/models/l10n_es_aeat_report.py
Labels: bot is merging ⏳

#3891 [17.0][IMP] l10n_es_aeat: Reverse order for reports
  l10n_es_aeat/models/l10n_es_aeat_report.py
Labels: bot is merging ⏳

#3892 [16.0][IMP] l10n_es_aeat_mod303: Follow 2 column layout in exonerated 390
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: bot is merging ⏳

#3893 [17.0][IMP] l10n_es_aeat_mod303: Follow 2 column layout in exonerated 390
  l10n_es_aeat_mod303/views/mod303_view.xml
Labels: bot is merging ⏳

#3877 [17.0][IMP] l10n_es_aeat_mod390: Cálculo casillas 85, 95, 97, 98 y 662
  l10n_es_aeat_mod390/README.rst
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/i18n/es.po
  l10n_es_aeat_mod390/i18n/l10n_es_aeat_mod390.pot
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod390/static/description/index.html
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: bot is merging ⏳

#3903 [16.0][IMP] l10n_es_aeat_mod390: 2024 tax mapping and BOE export format
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2024/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2024/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/2024/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod390/data/2024/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod390/data/tax_code_map_mod390_data.xml
  l10n_es_aeat_mod390/docs/dr390e2024.xlsx
  l10n_es_aeat_mod390/docs/instr390.pdf
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
Labels: bot is merging ⏳

#3904 [17.0][IMP] l10n_es_aeat_mod390: 2024 tax mapping and BOE export format
  l10n_es_aeat_mod390/__manifest__.py
  l10n_es_aeat_mod390/data/2023/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2024/aeat.model.export.config.csv
  l10n_es_aeat_mod390/data/2024/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/2024/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod390/data/2024/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod390/data/2024/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod390/data/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod390/docs/dr390e2024.xlsx
  l10n_es_aeat_mod390/docs/instr390.pdf
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
Labels: bot is merging ⏳

#3908 [16.0][FIX] l10n_es_atc: No auto-install
  l10n_es_atc/__manifest__.py
Labels: bot is merging ⏳

#3910 [16.0][IMP] l10n_es_aeat_mod347: Don't auto-delete 347 mail
  l10n_es_aeat_mod347/data/mail_template_data.xml
Labels: bot is merging ⏳

#3911 [15.0][IMP] l10n_es_aeat_mod347: New october 2024 taxes mapping + auto-delete
  l10n_es_aeat_mod347/data/mail_template_data.xml
  l10n_es_aeat_mod347/data/tax_code_map_mod347_data.xml
Labels: bot is merging ⏳

#3914 [15.0][FIX] l10n_es_aeat_mod190: Add modifications for 2024
  l10n_es_aeat_mod190/data/aeat_export_mod190_partner_data.xml
  l10n_es_aeat_mod190/docs/DR190_2024.pdf
Labels: bot is merging ⏳

#3898 [16.0][FIX] l10n_es_aeat_mod190: Add modifications for 2024
  l10n_es_aeat_mod190/data/aeat_export_mod190_partner_data.xml
  l10n_es_aeat_mod190/docs/DR190_2024.pdf
Labels: bot is merging ⏳

#3915 [17.0][FIX] l10n_es_atc: No auto-install
  l10n_es_atc/__manifest__.py
Labels: bot is merging ⏳

#3920 [17.0][IMP] l10n_es_aeat_mod347: New october 2024 taxes mapping + auto-delete
  l10n_es_aeat_mod347/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod347/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod347/data/mail_template_data.xml
Labels: bot is merging ⏳

#3919 [15.0][IMP] l10n_es_vat_book + l10n_es_aeat: Drill through on tax summary
  l10n_es_aeat/models/l10n_es_aeat_report.py
  l10n_es_aeat/models/l10n_es_aeat_tax_line.py
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/models/l10n_es_vat_book_line_tax.py
  l10n_es_vat_book/models/l10n_es_vat_book_tax_summary.py
  l10n_es_vat_book/views/l10n_es_vat_book_tax_summary.xml
Labels: bot is merging ⏳

#3922 [16.0][IMP] l10n_es_vat_book + l10n_es_aeat: Drill through on tax summary
  l10n_es_aeat/models/l10n_es_aeat_report.py
  l10n_es_aeat/models/l10n_es_aeat_tax_line.py
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/models/l10n_es_vat_book_line_tax.py
  l10n_es_vat_book/models/l10n_es_vat_book_tax_summary.py
  l10n_es_vat_book/views/l10n_es_vat_book_tax_summary.xml
Labels: bot is merging ⏳

#3924 [15.0][FIX] l10n_es_aeat_mod303: Remove field 96
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#3925 [16.0][FIX] l10n_es_aeat_mod390: Missing 0% taxes in field 99
  l10n_es_aeat_mod390/data/2024/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#3926 [17.0][IMP] l10n_es_vat_book + l10n_es_aeat: Drill through on tax summary
  l10n_es_aeat/models/l10n_es_aeat_report.py
  l10n_es_aeat/models/l10n_es_aeat_tax_line.py
  l10n_es_vat_book/models/l10n_es_vat_book.py
  l10n_es_vat_book/models/l10n_es_vat_book_line_tax.py
  l10n_es_vat_book/models/l10n_es_vat_book_tax_summary.py
  l10n_es_vat_book/views/l10n_es_vat_book_tax_summary.xml
Labels: bot is merging ⏳

#3927 [16.0][FIX] l10n_es_aeat_mod303: Remove field 96
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#3928 [17.0][FIX] l10n_es_aeat_mod390: Missing 0% taxes in field 99
  l10n_es_aeat_mod390/data/2024/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#3929 [17.0][FIX] l10n_es_aeat_mod303: Remove field 96
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: bot is merging ⏳

#3912 [14.0][IMP] l10n_es_aeat_mod303_oss: include lines oss in map mod303 2024-10
  l10n_es_aeat_mod303_oss/__manifest__.py
  l10n_es_aeat_mod303_oss/data/2024-10/l10n_es_aeat_map_tax_line.xml
  l10n_es_aeat_mod303_oss/models/mod303.py
  l10n_es_aeat_mod303_oss/static/description/index.html
Labels: bot is merging ⏳

#3930 [16.0] [FIX] l10n_es_pos_by_device: remove dead code overwrite in pos.config
  l10n_es_pos_by_device/models/pos_config.py
Labels: approved, bot is merging ⏳

#3756 [17.0] [ADD] l10n_es_igic_reav: reav fiscal data for canary localization
  l10n_es_igic_reav/README.rst
  l10n_es_igic_reav/__init__.py
  l10n_es_igic_reav/__manifest__.py
  l10n_es_igic_reav/data/template/account.fiscal.position-es_full_canary.csv
  l10n_es_igic_reav/data/template/account.fiscal.position-es_pymes_canary.csv
  l10n_es_igic_reav/data/template/account.tax-es_full_canary.csv
  l10n_es_igic_reav/data/template/account.tax-es_pymes_canary.csv
  l10n_es_igic_reav/models/__init__.py
  l10n_es_igic_reav/models/account_chart_template.py
  l10n_es_igic_reav/pyproject.toml
  l10n_es_igic_reav/readme/CONFIGURE.md
  l10n_es_igic_reav/readme/CONTRIBUTORS.md
  l10n_es_igic_reav/readme/DESCRIPTION.md
  l10n_es_igic_reav/readme/USAGE.md
  l10n_es_igic_reav/static/description/icon.png
  l10n_es_igic_reav/static/description/index.html
Labels: approved, bot is merging ⏳

#3874 [16.0][FIX] l10n_es_aeat_mod303: Error generación asiento contable cuando sale a pagar pero se compensa parcialmente con ejercicios anteriores
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: approved, ready to merge, bot is merging ⏳

#3938 [17.0][FIX] l10n_es_aeat_mod347: fix on partner_records' states
  l10n_es_aeat_mod347/__init__.py
  l10n_es_aeat_mod347/models/mod347.py
  l10n_es_aeat_mod347/tests/test_l10n_es_aeat_mod347.py
  l10n_es_aeat_mod347/wizard/__init__.py
  l10n_es_aeat_mod347/wizard/mail_compose_message.py
Labels: bot is merging ⏳

#3934 [16.0][IMP] l10n_es_aeat_mod347: Display move name or move ref depending on its move_type
  l10n_es_aeat_mod347/views/report_347_partner.xml
Labels: approved, bot is merging ⏳

#3943 [16.0][FIX] l10n_es_aeat_mod347: Take into account inactive taxes
  l10n_es_aeat_mod347/models/mod347.py
Labels: bot is merging ⏳

#3945 [15.0][FIX] l10n_es_aeat_mod347: Take into account inactive taxes
  l10n_es_aeat_mod347/models/mod347.py
Labels: bot is merging ⏳

#3944 [16.0][FIX] l10n_es_aeat_mod347: Avoid fake quarter amounts trackings
  l10n_es_aeat_mod347/models/mod347.py
Labels: bot is merging ⏳

#3835 [17.0][IMP]l10n_es_facturae: readme improve usage
  l10n_es_facturae/README.rst
  l10n_es_facturae/readme/CONFIGURE.md
  l10n_es_facturae/readme/CONTEXT.md
  l10n_es_facturae/readme/DESCRIPTION.md
  l10n_es_facturae/readme/HISTORY.md
  l10n_es_facturae/readme/USAGE.md
  l10n_es_facturae/static/description/index.html
  l10n_es_facturae/static/description/usage_01.png
  l10n_es_facturae/static/description/usage_02.png
  l10n_es_facturae/static/description/usage_03.png
  l10n_es_facturae/static/description/usage_04.png
  l10n_es_facturae/static/description/usage_05.png
  l10n_es_facturae/static/description/usage_06.png
  l10n_es_facturae/static/description/usage_07.png
  l10n_es_facturae/static/description/usage_08.png
  l10n_es_facturae/static/description/usage_09.png
  l10n_es_facturae/static/description/usage_10.png
Labels: bot is merging ⏳

#3946 [15.0][FIX] l10n_es_aeat_mod347: Avoid fake quarter amounts trackings
  l10n_es_aeat_mod347/models/mod347.py
Labels: bot is merging ⏳

#3940 [17.0][FIX] l10n_es_aeat_mod303: Error generación asiento contable cuando s…
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/models/mod303.py
  l10n_es_aeat_mod303/tests/test_l10n_es_aeat_mod303.py
Labels: approved, bot is merging ⏳

#3937 [16.0][FIX] l10n_es_aeat + l10n_es_facturae + l10n_es_facturae_face:
  l10n_es_aeat/__manifest__.py
  l10n_es_aeat_sii_match/__manifest__.py
  l10n_es_aeat_sii_oca/__manifest__.py
  l10n_es_facturae/__manifest__.py
  l10n_es_facturae_face/__manifest__.py
  requirements.txt
  test-requirements.txt
Labels: bot is merging ⏳

#3933 [17.0][MIG] l10n_es_aeat_mod190: Migration to 17.0
  l10n_es_aeat_mod190/README.rst
  l10n_es_aeat_mod190/__init__.py
  l10n_es_aeat_mod190/__manifest__.py
  l10n_es_aeat_mod190/data/aeat_export_mod190_data.xml
  l10n_es_aeat_mod190/data/aeat_export_mod190_partner_data.xml
  l10n_es_aeat_mod190/data/l10n.es.aeat.map.tax.csv
  l10n_es_aeat_mod190/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod190/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_aeat_mod190/data/perception_key_data.xml
  l10n_es_aeat_mod190/data/perception_subkey_data.xml
  l10n_es_aeat_mod190/docs/DR190_2017.pdf
  l10n_es_aeat_mod190/docs/DR190_2024.pdf
  l10n_es_aeat_mod190/i18n/ca.po
  l10n_es_aeat_mod190/i18n/ca_ES.po
  l10n_es_aeat_mod190/i18n/es.po
  l10n_es_aeat_mod190/i18n/l10n_es_aeat_mod190.pot
  l10n_es_aeat_mod190/models/__init__.py
  l10n_es_aeat_mod190/models/account_fiscal_position.py
  l10n_es_aeat_mod190/models/account_move.py
  l10n_es_aeat_mod190/models/account_move_line.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
  l10n_es_aeat_mod190/models/l10n_es_aeat_perception.py
  l10n_es_aeat_mod190/models/res_partner.py
  l10n_es_aeat_mod190/pyproject.toml
  l10n_es_aeat_mod190/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod190/readme/DESCRIPTION.md
  l10n_es_aeat_mod190/readme/ROADMAP.md
  l10n_es_aeat_mod190/readme/USAGE.md
  l10n_es_aeat_mod190/security/ir.model.access.csv
  l10n_es_aeat_mod190/security/l10n_es_aeat_mod190_security.xml
  l10n_es_aeat_mod190/static/description/icon.png
  l10n_es_aeat_mod190/static/description/icon_source.svg
  l10n_es_aeat_mod190/static/description/index.html
  l10n_es_aeat_mod190/tests/__init__.py
  l10n_es_aeat_mod190/tests/test_mod190.py
  l10n_es_aeat_mod190/views/account_fiscal_position.xml
  l10n_es_aeat_mod190/views/account_invoice_view.xml
  l10n_es_aeat_mod190/views/account_move_view.xml
  l10n_es_aeat_mod190/views/mod190_line_view.xml
  l10n_es_aeat_mod190/views/mod190_view.xml
  l10n_es_aeat_mod190/views/partner_view.xml
Labels: approved, bot is merging ⏳

#3951 [16.0][IMP] l10n_es_aeat_mod347: Partner record state improvements
  l10n_es_aeat_mod347/models/mod347.py
Labels: bot is merging ⏳

#3953 [17.0][IMP] l10n_es_aeat_mod347: Partner record state improvements
  l10n_es_aeat_mod347/models/mod347.py
Labels: bot is merging ⏳

#3952 [15.0][IMP] l10n_es_aeat_mod347: Partner record state improvements
  l10n_es_aeat_mod347/models/mod347.py
Labels: bot is merging ⏳

#3950 [IMP] l10n_es_aeat_mod390: Add field 662 to BOE export
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.line.csv
Labels: bot is merging ⏳

#3959 [16.0][FIX] l10n_es_aeat_mod190: Computes de casilla 02 y 03
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
Labels: approved, bot is merging ⏳

#3962 [16.0][FIX] l10n_es_aeat_mod303: Missing taxes in 25-26
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#3963 [15.0][FIX] l10n_es_aeat_mod303: Missing taxes in 25-26
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#3965 [15.0][IMP] l10n_es_aeat_mod347: Display move name or move ref depending on its move_type
  l10n_es_aeat_mod347/views/report_347_partner.xml
Labels: bot is merging ⏳

#3958 [16.0][ADD] l10n_es_dua_igic
  l10n_es_dua_igic/README.rst
  l10n_es_dua_igic/__init__.py
  l10n_es_dua_igic/__manifest__.py
  l10n_es_dua_igic/data/fiscal_position_taxes_dua.xml
  l10n_es_dua_igic/data/fiscal_positions_dua.xml
  l10n_es_dua_igic/data/products_dua.xml
  l10n_es_dua_igic/data/tax_group_data.xml
  l10n_es_dua_igic/data/taxes_dua.xml
  l10n_es_dua_igic/i18n/es.po
  l10n_es_dua_igic/readme/CONFIGURE.md
  l10n_es_dua_igic/readme/CONTRIBUTORS.md
  l10n_es_dua_igic/readme/DESCRIPTION.md
  l10n_es_dua_igic/readme/USAGE.md
  l10n_es_dua_igic/static/description/icon.png
  l10n_es_dua_igic/static/description/index.html
  setup/l10n_es_dua_igic/odoo/addons/l10n_es_dua_igic
  setup/l10n_es_dua_igic/setup.py
Labels: approved, bot is merging ⏳

#3966 [17.0][IMP] l10n_es_aeat_mod347: Display move name or move ref depending on its move_type
  l10n_es_aeat_mod347/views/report_347_partner.xml
Labels: bot is merging ⏳

#3967 [17.0][FIX] l10n_es_aeat_mod190: Compute casilla 02 y 03
  l10n_es_aeat_mod190/models/l10n_es_aeat_mod190_report.py
Labels: bot is merging ⏳

#3949 [16.0][ADD] l10n_es_facturae_igic
  l10n_es_facturae_igic/README.rst
  l10n_es_facturae_igic/__init__.py
  l10n_es_facturae_igic/__manifest__.py
  l10n_es_facturae_igic/data/account_tax_template.xml
  l10n_es_facturae_igic/readme/CONFIGURE.rst
  l10n_es_facturae_igic/readme/CONTRIBUTORS.rst
  l10n_es_facturae_igic/readme/DESCRIPTION.rst
  l10n_es_facturae_igic/readme/INSTALL.rst
  l10n_es_facturae_igic/readme/USAGE.rst
  l10n_es_facturae_igic/static/description/index.html
  setup/l10n_es_facturae_igic/odoo/addons/l10n_es_facturae_igic
  setup/l10n_es_facturae_igic/setup.py
Labels: approved, bot is merging ⏳

#3954 [16.0][FIX] pinned requests_pkcs12 version due cryptography dependency
  l10n_es_ticketbai_api_batuz/__manifest__.py
  requirements.txt
  test-requirements.txt
Labels: bot is merging ⏳

#3974 [16.0][IMP] l10n_es_aeat*: Show only fields with values by default
  l10n_es_aeat/i18n/es.po
  l10n_es_aeat/i18n/l10n_es_aeat.pot
  l10n_es_aeat/models/l10n_es_aeat_report_tax_mapping.py
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/views/mod303_view.xml
  l10n_es_aeat_mod390/i18n/es.po
  l10n_es_aeat_mod390/i18n/l10n_es_aeat_mod390.pot
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: approved, bot is merging ⏳

#3976 [16.0][FIX] l10n_es_aeat_mod390: Missing fields 60 and 61
  l10n_es_aeat_mod390/data/2024/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/2024/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod390/models/mod390.py
Labels: bot is merging ⏳

#3960 [15.0][FIX] l10n_es_aeat_mod390: computation of fields 97 and 662
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
Labels: approved, bot is merging ⏳

#3977 [17.0][IMP] l10n_es_aeat*: Show only fields with values by default
  l10n_es_aeat/i18n/es.po
  l10n_es_aeat/i18n/l10n_es_aeat.pot
  l10n_es_aeat/models/l10n_es_aeat_report_tax_mapping.py
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/views/mod303_view.xml
  l10n_es_aeat_mod390/i18n/es.po
  l10n_es_aeat_mod390/i18n/l10n_es_aeat_mod390.pot
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: bot is merging ⏳

#3979 [16.0][FIX] l10n_es_aeat_mod390: computation of fields 97 and 662
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
Labels: bot is merging ⏳

#3981 [15.0][FIX] l10n_es_aeat_mod390: Missing fields 60 and 61
  l10n_es_aeat_mod390/data/2024/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/data/2024/l10n.es.aeat.map.tax.line.csv
  l10n_es_aeat_mod390/models/mod390.py
Labels: bot is merging ⏳

#3980 [15.0][IMP] l10n_es_aeat*: Show only fields with values by default
  l10n_es_aeat/i18n/es.po
  l10n_es_aeat/i18n/l10n_es_aeat.pot
  l10n_es_aeat/models/l10n_es_aeat_report_tax_mapping.py
  l10n_es_aeat_mod303/i18n/es.po
  l10n_es_aeat_mod303/i18n/l10n_es_aeat_mod303.pot
  l10n_es_aeat_mod303/views/mod303_view.xml
  l10n_es_aeat_mod390/i18n/es.po
  l10n_es_aeat_mod390/i18n/l10n_es_aeat_mod390.pot
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: bot is merging ⏳

#3948 [15.0][FIX] l10n_es_aeat_mod390: Calculation of field 85
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/tests/test_l10n_es_aeat_mod390.py
Labels: approved, ready to merge, bot is merging ⏳

#3972 [16.0][IMP] l10n_es_aeat_mod390: Casillas 658 y 84
  l10n_es_aeat_mod390/data/2021/aeat.model.export.config.line.csv
  l10n_es_aeat_mod390/models/mod390.py
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: approved, bot is merging ⏳
