Repository OCA/l10n-spain, pull requests merged in 2025-10, with the labels that each got.

#4411 [16.0][FIX] l10n_es_vat_prorate: Fix modulo después de la actualización de la prorrata especial
  l10n_es_vat_prorate/__manifest__.py
  l10n_es_vat_prorate/migrations/16.0.2.0.1/post-migrate.py
Labels: approved, bot is merging ⏳

#4406 [16.0] [IMP] l10n_es_ticketbai_pos: several fixes
  l10n_es_ticketbai_pos/i18n/es.po
  l10n_es_ticketbai_pos/i18n/l10n_es_ticketbai_pos.pot
  l10n_es_ticketbai_pos/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  l10n_es_ticketbai_pos/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  l10n_es_ticketbai_pos/static/src/js/Screens/ProductScreen/ProductScreen.js
  l10n_es_ticketbai_pos/static/src/js/models.js
  l10n_es_ticketbai_pos/static/src/js/tbai_models.js
Labels: approved, ready to merge, bot is merging ⏳

#4352 [18.0][MIG] l10n_es_facturae_face: Migration to 18.0
  l10n_es_facturae_face/README.rst
  l10n_es_facturae_face/__init__.py
  l10n_es_facturae_face/__manifest__.py
  l10n_es_facturae_face/data/cron_data.xml
  l10n_es_facturae_face/data/edi.xml
  l10n_es_facturae_face/data/face_data.xml
  l10n_es_facturae_face/i18n/ca.po
  l10n_es_facturae_face/i18n/es.po
  l10n_es_facturae_face/i18n/l10n_es_facturae_face.pot
  l10n_es_facturae_face/models/__init__.py
  l10n_es_facturae_face/models/account_move.py
  l10n_es_facturae_face/models/edi_exchange_record.py
  l10n_es_facturae_face/models/l10n_es_facturae_face_base_handler.py
  l10n_es_facturae_face/models/l10n_es_facturae_face_cancel_handler.py
  l10n_es_facturae_face/models/l10n_es_facturae_face_output_handler.py
  l10n_es_facturae_face/models/l10n_es_facturae_face_update_handler.py
  l10n_es_facturae_face/models/res_company.py
  l10n_es_facturae_face/models/res_partner.py
  l10n_es_facturae_face/models/wsse_signature.py
  l10n_es_facturae_face/pyproject.toml
  l10n_es_facturae_face/readme/CONFIGURE.md
  l10n_es_facturae_face/readme/CONTRIBUTORS.md
  l10n_es_facturae_face/readme/DESCRIPTION.md
  l10n_es_facturae_face/readme/USAGE.md
  l10n_es_facturae_face/security/ir.model.access.csv
  l10n_es_facturae_face/static/description/icon.png
  l10n_es_facturae_face/static/description/index.html
  l10n_es_facturae_face/tests/__init__.py
  l10n_es_facturae_face/tests/test_facturae_face.py
  l10n_es_facturae_face/views/account_move.xml
  l10n_es_facturae_face/views/edi_exchange_record.xml
  l10n_es_facturae_face/views/res_company_view.xml
  l10n_es_facturae_face/views/res_partner.xml
  l10n_es_facturae_face/wizards/__init__.py
  l10n_es_facturae_face/wizards/edi_l10n_es_facturae_face_cancel.py
  l10n_es_facturae_face/wizards/edi_l10n_es_facturae_face_cancel.xml
Labels: bot is merging ⏳
