Repository OCA/l10n-spain, pull requests merged in 2025-07, with the labels that each got.

#4264 [IMP] l10n_es_facturae_face: Improve cron. Allow to update a smaller set of records
  l10n_es_facturae_face/models/edi_exchange_record.py
  l10n_es_facturae_face/tests/test_facturae_face.py
Labels: approved, bot is merging ⏳

#4273 [17.0] [IMP] l10n_es_aeat_mod303: add dua taxes to 2024-10 format
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#4274 [18.0] [IMP] l10n_es_aeat_mod303: add dua taxes to 2024-10 format
  l10n_es_aeat_mod303/data/2024-10/l10n.es.aeat.map.tax.line.csv
Labels: bot is merging ⏳

#4277 [16.0][FIX] l10n_es_vat_book: avoid KeyError if other_tax_ids not present
  l10n_es_vat_book/models/l10n_es_vat_book.py
Labels: bot is merging ⏳

#4163 [15.0][IMP] l10n_es_aeat_mod592: Define quoting=QUOTE_NONE to avoid quotation marks in the generated csv file.
  l10n_es_aeat_mod592/report/l10n_es_aeat_mod592_csv.py
Labels: bot is merging ⏳

#4282 [16.0][I18N] payment_redsys: Avoid duplicated label + Remove unused languages
  payment_redsys/i18n/bg.po
  payment_redsys/i18n/ca.po
  payment_redsys/i18n/de.po
  payment_redsys/i18n/es.po
  payment_redsys/i18n/fr.po
  payment_redsys/i18n/gl.po
  payment_redsys/i18n/hr.po
  payment_redsys/i18n/payment_redsys.pot
  payment_redsys/i18n/pt_BR.po
  payment_redsys/i18n/sl.po
  payment_redsys/models/payment_provider.py
  payment_redsys/views/payment_provider.xml
Labels: bot is merging ⏳

#4280 [16.0][IMP] l10n_es_account_statement_import_n43: Make partner search optional
  l10n_es_account_statement_import_n43/i18n/es.po
  l10n_es_account_statement_import_n43/i18n/l10n_es_account_bank_statement_import_n43.pot
  l10n_es_account_statement_import_n43/i18n/l10n_es_account_statement_import_n43.pot
  l10n_es_account_statement_import_n43/models/account_journal.py
  l10n_es_account_statement_import_n43/views/account_journal_views.xml
  l10n_es_account_statement_import_n43/wizards/account_statement_import_n43.py
Labels: approved, bot is merging ⏳

#4287 [16.0][IMP] l10n_es_vat_prorate / l10n_es_aeat_mod303_vat_prorate: Special prorate
  l10n_es_aeat_mod303_vat_prorate/README.rst
  l10n_es_aeat_mod303_vat_prorate/models/mod303.py
  l10n_es_aeat_mod303_vat_prorate/readme/CONTRIBUTORS.rst
  l10n_es_aeat_mod303_vat_prorate/readme/ROADMAP.rst
  l10n_es_aeat_mod303_vat_prorate/static/description/index.html
  l10n_es_aeat_mod303_vat_prorate/tests/test_l10n_es_aeat_mod303_vat_prorate.py
  l10n_es_aeat_mod303_vat_prorate/views/mod303_views.xml
  l10n_es_vat_prorate/README.rst
  l10n_es_vat_prorate/__init__.py
  l10n_es_vat_prorate/__manifest__.py
  l10n_es_vat_prorate/hooks.py
  l10n_es_vat_prorate/i18n/ca.po
  l10n_es_vat_prorate/i18n/es.po
  l10n_es_vat_prorate/i18n/l10n_es_vat_prorate.pot
  l10n_es_vat_prorate/migrations/16.0.2.0.0/pre-migration.py
  l10n_es_vat_prorate/models/account_move.py
  l10n_es_vat_prorate/models/account_tax.py
  l10n_es_vat_prorate/models/res_company.py
  l10n_es_vat_prorate/readme/CONFIGURE.rst
  l10n_es_vat_prorate/readme/CONTRIBUTORS.rst
  l10n_es_vat_prorate/static/description/index.html
  l10n_es_vat_prorate/tests/test_vat_prorate.py
  l10n_es_vat_prorate/views/account_move_views.xml
  l10n_es_vat_prorate/views/res_company_prorate_views.xml
Labels: approved, bot is merging ⏳

#4288 [17.0][IMP+FIX+I18N] l10n_es_vat_prorate: Feedback from v16 backport
  l10n_es_vat_prorate/i18n/ca.po
  l10n_es_vat_prorate/i18n/es.po
  l10n_es_vat_prorate/i18n/l10n_es_vat_prorate.pot
  l10n_es_vat_prorate/models/account_move.py
  l10n_es_vat_prorate/models/account_tax.py
  l10n_es_vat_prorate/models/res_company.py
  l10n_es_vat_prorate/views/account_move_views.xml
  l10n_es_vat_prorate/views/res_company_prorate_views.xml
Labels: bot is merging ⏳

#4299 [18.0][FIX] l10n_es_partner: Reduce logger level using local data
  l10n_es_partner/wizard/l10n_es_partner_wizard.py
Labels: bot is merging ⏳

#4300 [17.0][IMP] l10n_es_atc: Adapt to l10n_es_aeat report menu
  l10n_es_atc/README.rst
  l10n_es_atc/readme/CONTRIBUTORS.md
  l10n_es_atc/static/description/index.html
  l10n_es_atc/views/atc_menuitem.xml
Labels: bot is merging ⏳

#4306 [18.0][MIG] l10n_es_aeat_mod130: Migration to 18.0
  l10n_es_aeat_mod130/README.rst
  l10n_es_aeat_mod130/__init__.py
  l10n_es_aeat_mod130/__manifest__.py
  l10n_es_aeat_mod130/data/aeat_export_mod130_data.xml
  l10n_es_aeat_mod130/doc/DR130e15v12.xls
  l10n_es_aeat_mod130/i18n/bg.po
  l10n_es_aeat_mod130/i18n/ca.po
  l10n_es_aeat_mod130/i18n/ca_ES.po
  l10n_es_aeat_mod130/i18n/cs.po
  l10n_es_aeat_mod130/i18n/en_US.po
  l10n_es_aeat_mod130/i18n/es.po
  l10n_es_aeat_mod130/i18n/es_CO.po
  l10n_es_aeat_mod130/i18n/es_CR.po
  l10n_es_aeat_mod130/i18n/eu.po
  l10n_es_aeat_mod130/i18n/fr.po
  l10n_es_aeat_mod130/i18n/gl.po
  l10n_es_aeat_mod130/i18n/hr.po
  l10n_es_aeat_mod130/i18n/l10n_es_aeat_mod130.pot
  l10n_es_aeat_mod130/i18n/nl.po
  l10n_es_aeat_mod130/i18n/pl.po
  l10n_es_aeat_mod130/i18n/pt.po
  l10n_es_aeat_mod130/i18n/pt_BR.po
  l10n_es_aeat_mod130/i18n/ru.po
  l10n_es_aeat_mod130/i18n/sl.po
  l10n_es_aeat_mod130/i18n/sv.po
  l10n_es_aeat_mod130/i18n/tr.po
  l10n_es_aeat_mod130/i18n/vi.po
  l10n_es_aeat_mod130/models/__init__.py
  l10n_es_aeat_mod130/models/mod130.py
  l10n_es_aeat_mod130/pyproject.toml
  l10n_es_aeat_mod130/readme/CONTRIBUTORS.md
  l10n_es_aeat_mod130/readme/DESCRIPTION.md
  l10n_es_aeat_mod130/readme/ROADMAP.md
  l10n_es_aeat_mod130/security/ir.model.access.csv
  l10n_es_aeat_mod130/security/ir_rule.xml
  l10n_es_aeat_mod130/static/description/icon.png
  l10n_es_aeat_mod130/static/description/icon_source.svg
  l10n_es_aeat_mod130/static/description/index.html
  l10n_es_aeat_mod130/tests/__init__.py
  l10n_es_aeat_mod130/tests/test_l10n_es_aeat_mod130.py
  l10n_es_aeat_mod130/views/mod130_view.xml
Labels: bot is merging ⏳

#4312 [17.0][OU-ADD] l10n_es_aeat_sii_oca: Migration scripts
  l10n_es_aeat_sii_oca/migrations/17.0.1.0.0/post-migration.py
Labels: approved

#4315 [17.0] delivery_dhl_parcel,delivery_gls_asm: Update maintainers
  delivery_dhl_parcel/__manifest__.py
  delivery_gls_asm/__manifest__.py
Labels: bot is merging ⏳

#4314 [16.0] delivery_gls_asm: Update maintainers
  delivery_gls_asm/__manifest__.py
Labels: bot is merging ⏳

#4316 [18.0] delivery_gls_asm: Update maintainers
  delivery_gls_asm/__manifest__.py
Labels: bot is merging ⏳

#4319 [14.0][FIX] l10n_es_aeat_mod349: Solve error where rectifications for other periods do not have the original amount
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
Labels: bot is merging ⏳

#4320 [14.0][FIX] l10n_es_aeat_mod349: Don't look for cancelled reports
  l10n_es_aeat_mod349/models/mod349.py
Labels: bot is merging ⏳

#4321 [15.0][FIX] l10n_es_aeat_mod349: Solve error where rectifications for other periods do not have the original amount
  l10n_es_aeat_mod349/models/mod349.py
  l10n_es_aeat_mod349/tests/test_l10n_es_aeat_mod349.py
Labels: bot is merging ⏳

#4322 [15.0][FIX] l10n_es_aeat_mod349: Don't look for cancelled reports
  l10n_es_aeat_mod349/models/mod349.py
Labels: bot is merging ⏳

#4327 [18.0][IMP] l10n_es_aeat_mod390: cambio de menu a declaraciones con submenus por agencia
  l10n_es_aeat_mod390/views/mod390_view.xml
Labels: bot is merging ⏳
