Repository OCA/l10n-spain, pull requests merged in 2025-09, with the labels that each got.

#4361 [15.0][IMP] delivery_gls_asm: build 'destinatario' country from ISO country code instead of phone_code
  delivery_gls_asm/models/delivery_carrier.py
Labels: approved, bot is merging ⏳

#4363 [17.0][IMP] delivery_gls_asm: build 'destinatario' country from ISO country code instead of phone_code
  delivery_gls_asm/models/delivery_carrier.py
Labels: bot is merging ⏳

#4356 [17.0][OU-ADD] payment_redsys: Enable payment methods for redsys
  payment_redsys/migrations/17.0.1.0.0/post-migration.py
Labels: approved

#4371 [18.0][FIX] l10n_es_aeat_mod349: Wrong domain
  l10n_es_aeat_mod349/models/account_move.py
Labels: bot is merging ⏳

#4260 [17.0][ADD] l10n_es_atc_mod425: Modelo 425
  l10n_es_atc_mod425/README.rst
  l10n_es_atc_mod425/__init__.py
  l10n_es_atc_mod425/__manifest__.py
  l10n_es_atc_mod425/data/l10n.es.aeat.map.tax.csv
  l10n_es_atc_mod425/data/l10n.es.aeat.map.tax.line.account.csv
  l10n_es_atc_mod425/data/l10n.es.aeat.map.tax.line.csv
  l10n_es_atc_mod425/data/l10n.es.aeat.map.tax.line.tax.csv
  l10n_es_atc_mod425/models/__init__.py
  l10n_es_atc_mod425/models/mod425.py
  l10n_es_atc_mod425/pyproject.toml
  l10n_es_atc_mod425/readme/CONTRIBUTORS.md
  l10n_es_atc_mod425/readme/DESCRIPTION.md
  l10n_es_atc_mod425/readme/INSTALL.md
  l10n_es_atc_mod425/readme/ROADMAP.md
  l10n_es_atc_mod425/readme/USAGE.md
  l10n_es_atc_mod425/reports/Presentacion-425-XMLSchema.xsd
  l10n_es_atc_mod425/reports/mod425_report.xml
  l10n_es_atc_mod425/security/ir.model.access.csv
  l10n_es_atc_mod425/security/l10n_es_atc_mod425_security.xml
  l10n_es_atc_mod425/static/description/icon.png
  l10n_es_atc_mod425/static/description/index.html
  l10n_es_atc_mod425/static/src/pdf/caratula_sobre_425.pdf
  l10n_es_atc_mod425/tests/__init__.py
  l10n_es_atc_mod425/tests/test_l10n_es_atc_mod425.py
  l10n_es_atc_mod425/views/mod425_view.xml
Labels: approved, bot is merging ⏳

#4384 [16.0][IMP] l10n_es_verifactu_oca: Added a QR in the header according to AEAT requirements.
  l10n_es_verifactu_oca/views/report_invoice.xml
Labels: approved, ready to merge, bot is merging ⏳

#4398 [16.0][FIX] l10n_es_verifactu_oca: Proper identifier for receiver
  l10n_es_verifactu_oca/models/account_move.py
Labels: bot is merging ⏳

#4403 [16.0][FIX] l10n_es_verifactu_oca: View imported twice
  l10n_es_verifactu_oca/__manifest__.py
Labels: bot is merging ⏳

#4405 [16.0][FIX] l10n_es_aeat_sii_match: Duplicated label
  l10n_es_aeat_sii_match/i18n/es.po
  l10n_es_aeat_sii_match/i18n/l10n_es_aeat_sii_match.pot
  l10n_es_aeat_sii_match/models/aeat_sii_match_report.py
Labels: bot is merging ⏳

#4408 [17.0][IMP] l10n_es_aeat_sii_oca: Send now option
  l10n_es_aeat_sii_oca/i18n/es.po
  l10n_es_aeat_sii_oca/i18n/l10n_es_aeat_sii_oca.pot
  l10n_es_aeat_sii_oca/models/sii_mixin.py
  l10n_es_aeat_sii_oca/views/account_move_views.xml
Labels: bot is merging ⏳
